local data_types =
{
	-- Items
	item = 
	{
		["ammo"] = "item",
		["armor"] = "item",
		["blueprint"] = "item",
		["blueprint-book"] = "item",
		["capsule"] = "item",
		["copy-paste-tool"] = "item",
		["deconstruction-item"] = "item",
		["gun"] = "item",
		["item"] = "item",
		["item-with-entity-data"] = "item",
		["item-with-inventory"] = "item",
		["item-with-label"] = "item",
		["item-with-tags"] = "item",
		["mining-tool"] = "item",
		["module"] = "item",
		["rail-planner"] = "item",
		["repair-tool"] = "item",
		["selection-tool"] = "item",
		["spidertron-remote"] = "item",
		["tool"] = "item",
		["upgrade-item"] = "item",
	},

	-- Entities
	entity =
	{
		["accumulator"] = "entity",
		["ammo-turret"] = "entity",
		["arithmetic-combinator"] = "entity",
		["arrow"] = "entity",
		["artillery-flare"] = "entity",
		["artillery-projectile"] = "entity",
		["artillery-turret"] = "entity",
		["artillery-wagon"] = "entity",
		["assembling-machine"] = "entity",
		["beacon"] = "entity",
		["beam"] = "entity",
		["boiler"] = "entity",
		["burner-generator"] = "entity",
		["car"] = "entity",
		["cargo-wagon"] = "entity",
		["character"] = "entity",
		["character-corpse"] = "entity",
		["cliff"] = "entity",
		["combat-robot"] = "entity",
		["constant-combinator"] = "entity",
		["construction-robot"] = "entity",
		["container"] = "entity",
		["corpse"] = "entity",
		["curved-rail"] = "entity",
		["decider-combinator"] = "entity",
		["deconstructible-tile-proxy"] = "entity",
		["electric-energy-interface"] = "entity",
		["electric-pole"] = "entity",
		["electric-turret"] = "entity",
		["entity-ghost"] = "entity",
		["explosion"] = "entity",
		["fire"] = "entity",
		["fish"] = "entity",
		["flame-thrower-explosion"] = "entity",
		["fluid-turret"] = "entity",
		["fluid-wagon"] = "entity",
		["flying-text"] = "entity",
		["furnace"] = "entity",
		["gate"] = "entity",
		["generator"] = "entity",
		["heat-interface"] = "entity",
		["heat-pipe"] = "entity",
		["highlight-box"] = "entity",
		["infinity-container"] = "entity",
		["infinity-pipe"] = "entity",
		["inserter"] = "entity",
		["item-entity"] = "entity",
		["item-request-proxy"] = "entity",
		["lab"] = "entity",
		["lamp"] = "entity",
		["land-mine"] = "entity",
		["leaf-particle"] = "entity",
		["linked-belt"] = "entity",
		["linked-container"] = "entity",
		["loader"] = "entity",
		["loader-1x1"] = "entity",
		["locomotive"] = "entity",
		["logistic-container"] = "entity",
		["logistic-robot"] = "entity",
		["market"] = "entity",
		["mining-drill"] = "entity",
		["offshore-pump"] = "entity",
		["particle"] = "entity",
		["particle-source"] = "entity",
		["pipe"] = "entity",
		["pipe-to-ground"] = "entity",
		["player-port"] = "entity",
		["power-switch"] = "entity",
		["programmable-speaker"] = "entity",
		["projectile"] = "entity",
		["pump"] = "entity",
		["radar"] = "entity",
		["rail-chain-signal"] = "entity",
		["rail-remnants"] = "entity",
		["rail-signal"] = "entity",
		["reactor"] = "entity",
		["resource"] = "entity",
		["roboport"] = "entity",
		["rocket-silo"] = "entity",
		["rocket-silo-rocket"] = "entity",
		["rocket-silo-rocket-shadow"] = "entity",
		["simple-entity"] = "entity",
		["simple-entity-with-force"] = "entity",
		["simple-entity-with-owner"] = "entity",
		["smoke"] = "entity",
		["smoke-with-trigger"] = "entity",
		["solar-panel"] = "entity",
		["speech-bubble"] = "entity",
		["spider-leg"] = "entity",
		["spider-vehicle"] = "entity",
		["splitter"] = "entity",
		["sticker"] = "entity",
		["storage-tank"] = "entity",
		["straight-rail"] = "entity",
		["stream"] = "entity",
		["tile-ghost"] = "entity",
		["train-stop"] = "entity",
		["transport-belt"] = "entity",
		["tree"] = "entity",
		["turret"] = "entity",
		["underground-belt"] = "entity",
		["unit"] = "entity",
		["unit-spawner"] = "entity",
		["wall"] = "entity",
	},

	sub_types =
	{
		"accumulator",
		"achievement",
		"active-defense-equipment",
		"ambient-sound",
		"ammo",
		"ammo-category",
		"ammo-turret",
		"arithmetic-combinator",
		"armor",
		"arrow",
		"artillery-flare",
		"artillery-projectile",
		"artillery-turret",
		"artillery-wagon",
		"assembling-machine",
		"autoplace-control",
		"battery-equipment",
		"beacon",
		"beam",
		"belt-immunity-equipment",
		"blueprint",
		"blueprint-book",
		"boiler",
		"build-entity-achievement",
		"burner-generator",
		"capsule",
		"car",
		"cargo-wagon",
		"character",
		"character-corpse",
		"cliff",
		"combat-robot",
		"combat-robot-count",
		"constant-combinator",
		"construct-with-robots-achievement",
		"construction-robot",
		"container",
		"copy-paste-tool",
		"corpse",
		"curved-rail",
		"custom-input",
		"damage-type",
		"decider-combinator",
		"deconstruct-with-robots-achievement",
		"deconstructible-tile-proxy",
		"deconstruction-item",
		"deliver-by-robots-achievement",
		"dont-build-entity-achievement",
		"dont-craft-manually-achievement",
		"dont-use-entity-in-energy-production-achievement",
		"editor-controller",
		"electric-energy-interface",
		"electric-pole",
		"electric-turret",
		"energy-shield-equipment",
		"entity-ghost",
		"equipment-category",
		"equipment-grid",
		"explosion",
		"finish-the-game-achievement",
		"fire",
		"fish",
		"flame-thrower-explosion",
		"fluid",
		"fluid-turret",
		"fluid-wagon",
		"flying-text",
		"font",
		"fuel-category",
		"furnace",
		"gate",
		"generator",
		"generator-equipment",
		"god-controller",
		"group-attack-achievement",
		"gun",
		"heat-interface",
		"heat-pipe",
		"highlight-box",
		"infinity-container",
		"infinity-pipe",
		"inserter",
		"item",
		"item-entity",
		"item-group",
		"item-request-proxy",
		"item-subgroup",
		"item-with-entity-data",
		"item-with-inventory",
		"item-with-label",
		"item-with-tags",
		"kill-achievement",
		"lab",
		"lamp",
		"land-mine",
		"leaf-particle",
		"linked-belt",
		"linked-container",
		"loader",
		"loader-1x1",
		"locomotive",
		"logistic-container",
		"logistic-robot",
		"map-settings",
		"market",
		"mining-drill",
		"mining-tool",
		"module",
		"module-category",
		"mouse-cursor",
		"movement-bonus-equipment",
		"night-vision-equipment",
		"noise-expression",
		"noise-layer",
		"offshore-pump",
		"optimized-decorative",
		"optimized-particle",
		"particle",
		"particle-source",
		"pipe",
		"pipe-to-ground",
		"player-damaged-achievement",
		"player-port",
		"power-switch",
		"produce-achievement",
		"produce-per-hour-achievement",
		"programmable-speaker",
		"projectile",
		"pump",
		"radar",
		"rail-chain-signal",
		"rail-planner",
		"rail-remnants",
		"rail-signal",
		"reactor",
		"recipe",
		"recipe-category",
		"repair-tool",
		"research-achievement",
		"resource",
		"resource-category",
		"roboport",
		"roboport-equipment",
		"rocket-silo",
		"rocket-silo-rocket",
		"rocket-silo-rocket-shadow",
		"selection-tool",
		"shortcut",
		"simple-entity",
		"simple-entity-with-force",
		"simple-entity-with-owner",
		"smoke",
		"smoke-with-trigger",
		"solar-panel",
		"solar-panel-equipment",
		"spectator-controller",
		"speech-bubble",
		"spider-leg",
		"spider-vehicle",
		"spidertron-remote",
		"splitter",
		"sprite",
		"storage-tank",
		"straight-rail",
		"stream",
		"technology",
		"tile",
		"tile-effect",
		"tile-ghost",
		"tips-and-tricks-item",
		"tips-and-tricks-item-category",
		"tool",
		"train-path-achievement",
		"train-stop",
		"transport-belt",
		"tree",
		"trigger-target-type",
		"trivial-smoke",
		"turret",
		"tutorial",
		"underground-belt",
		"unit",
		"unit-spawner",
		"upgrade-item",
		"utility-constants",
		"utility-sounds",
		"utility-sprites",
		"virtual-signal",
		"wall",
		"wind-sound",
	},
}


return data_types