data:extend({
  {
    type = "custom-input",
    name = "qis-search",
    key_sequence = "SHIFT + F",
    order = "a",
  },
  {
    type = "custom-input",
    name = "qis-nav-up",
    key_sequence = "UP",
    alternative_key_sequence = "SHIFT + K",
    order = "ba",
  },
  {
    type = "custom-input",
    name = "qis-nav-down",
    key_sequence = "DOWN",
    alternative_key_sequence = "SHIFT + J",
    order = "bb",
  },
  {
    type = "custom-input",
    name = "qis-quick-trash-all",
    key_sequence = "CONTROL + SHIFT + T",
    order = "c",
  },
  {
    type = "custom-input",
    name = "qis-confirm",
    key_sequence = "E",
    alternative_key_sequence = "ENTER",
    order = "d",
  },
  {
    type = "custom-input",
    name = "qis-shift-confirm",
    key_sequence = "SHIFT + E",
    alternative_key_sequence = "SHIFT + ENTER",
    order = "e",
  },
  {
    type = "custom-input",
    name = "qis-control-confirm",
    key_sequence = "CONTROL + E",
    alternative_key_sequence = "CONTROL + ENTER",
    order = "f",
  },
  {
    type = "custom-input",
    name = "qis-cycle-infinity-filter-mode",
    key_sequence = "SPACE",
    order = "g",
  },
})
