local resistances = {
	{ type = "fire", percent = 100 },
	{ type = "explosion", percent = 50 },
	{ type = "impact", percent = 50 },
}
--{"floor-layer", "player-layer", "water-tile", "object-layer"},
local collision_mask_blocking = { layers = {
	player = true,
	object = true,
} }
local collision_mask_nonblocking = { layers = {
	item = true,
} }
data:extend({
	{
		type = "container",
		name = "aai-big-ship-wreck-1",
		inventory_type = "normal",
		icon = "__base__/graphics/icons/crash-site-spaceship-wreck-big-2.png",
		icon_size = 32,
		flags = { "placeable-neutral" },
		subgroup = "wrecks",
		order = "d[remnants]-d[ship-wreck]-a[big]-a",
		max_health = 300,
		minable = {
			mining_time = 5,
			results = {
				{ type = "item", name = "iron-plate", amount = 62 },
				{ type = "item", name = "copper-plate", amount = 38 },
				{ type = "item", name = "steel-plate", amount = 7 },
				{ type = "item", name = "iron-gear-wheel", amount = 9 },
				{ type = "item", name = "electronic-circuit", amount = 2 },
			},
		},
		resistances = resistances,
		collision_box = { { -1.8, -1.5 }, { 1.8, 1.5 } },
		collision_mask = collision_mask_blocking,
		selection_box = { { -2.7, -1.5 }, { 2.7, 1.5 } },
		inventory_size = 3,
		picture = {
			filename = "__zzzcompability__/graphics/entity/ship-wreck/big-ship-wreck-1.png",
			width = 256,
			height = 212,
			shift = { 0.7, 0 },
		},
	},
	{
		type = "container",
		name = "aai-big-ship-wreck-2",
		inventory_type = "normal",
		icon = "__base__/graphics/icons/crash-site-spaceship-wreck-big-2.png",
		icon_size = 32,
		flags = { "placeable-neutral" },
		subgroup = "wrecks",
		order = "d[remnants]-d[ship-wreck]-a[big]-b",
		max_health = 300,
		minable = {
			mining_time = 0.5 * 10,
			results = {
				{type="item", name = "iron-plate", amount = 58 },
				{type="item", name = "copper-plate", amount = 36 },
				{type="item", name = "steel-plate", amount = 3 },
				{type="item", name = "iron-gear-wheel", amount = 7 },
				{type="item", name = "electronic-circuit", amount = 1 },
			},
		},
		resistances = resistances,
		collision_box = { { -1.4, -1.2 }, { 1.4, 1.2 } },
		collision_mask = collision_mask_blocking,
		selection_box = { { -2, -1.5 }, { 2, 1.5 } },
		inventory_size = 3,
		picture = {
			filename = "__zzzcompability__/graphics/entity/ship-wreck/big-ship-wreck-2.png",
			width = 164,
			height = 129,
			shift = { -0.5, 0.6 },
		},
	},
	{
		type = "container",
		name = "aai-big-ship-wreck-3",
		inventory_type = "normal",
		icon = "__base__/graphics/icons/crash-site-spaceship-wreck-big-1.png",
		icon_size = 32,
		flags = { "placeable-neutral" },
		subgroup = "wrecks",
		order = "d[remnants]-d[ship-wreck]-a[big]-c",
		max_health = 300,
		minable = {
			mining_time = 0.5 * 10,
			results = {
				{type="item", name = "iron-plate", amount = 38 },
				{type="item", name = "copper-plate", amount = 44 },
				{type="item", name = "steel-plate", amount = 2 },
				{type="item", name = "iron-gear-wheel", amount = 5 },
				{type="item", name = "electronic-circuit", amount = 1 },
			},
		},
		resistances = resistances,
		collision_box = { { -0.8, -0.8 }, { 0.8, 0.8 } },
		collision_mask = collision_mask_blocking,
		selection_box = { { -2, -1.5 }, { 2, 1.5 } },
		inventory_size = 3,
		picture = {
			filename = "__zzzcompability__/graphics/entity/ship-wreck/big-ship-wreck-3.png",
			width = 165,
			height = 131,
		},
	},

	{
		type = "container",
		name = "aai-medium-ship-wreck-1",
		icon = "__base__/graphics/icons/crash-site-spaceship-wreck-medium-1.png",
		icon_size = 32,
		flags = { "placeable-neutral", "placeable-off-grid", "not-on-map" },
		subgroup = "wrecks",
		order = "d[remnants]-d[ship-wreck]-b[medium]-a",
		max_health = 200,
		minable = {
			mining_time = 0.5 * 5,
			results = {
				{type="item", name = "iron-plate", amount = 24 },
				{type="item", name = "iron-gear-wheel", amount = 3 },
			},
		},
		resistances = resistances,
		collision_box = { { -0.1, -0.1 }, { 0.1, 0.1 } },
		collision_mask = collision_mask_nonblocking,
		selection_box = { { -1.5, -1.2 }, { 1.5, 1.2 } },
		inventory_size = 1,
		picture = {
			filename = "__zzzcompability__/graphics/entity/ship-wreck/medium-ship-wreck-1.png",
			width = 120,
			height = 85,
		},
	},
	{
		type = "container",
		name = "aai-medium-ship-wreck-2",
		icon = "__base__/graphics/icons/crash-site-spaceship-wreck-medium-2.png",
		icon_size = 32,
		flags = { "placeable-neutral", "placeable-off-grid", "not-on-map" },
		subgroup = "wrecks",
		order = "d[remnants]-d[ship-wreck]-b[medium]-a",
		max_health = 200,
		minable = {
			mining_time = 0.5 * 5,
			results = {
				{type="item", name = "copper-plate", amount = 18 },
				{type="item", name = "iron-gear-wheel", amount = 2 },
			},
		},
		resistances = resistances,
		collision_box = { { -0.1, -0.1 }, { 0.1, 0.1 } },
		collision_mask = collision_mask_nonblocking,
		selection_box = { { -1.5, -1.2 }, { 1.5, 1.2 } },
		inventory_size = 1,
		picture = {
			filename = "__zzzcompability__/graphics/entity/ship-wreck/medium-ship-wreck-2.png",
			width = 126,
			height = 107,
			shift = { 0.3, 0.1 },
		},
	},

	{
		type = "simple-entity",
		name = "aai-small-ship-wreck",
		icon = "__base__/graphics/icons/crash-site-spaceship-wreck-small-1.png",
		icon_size = 32,
		flags = { "placeable-neutral", "placeable-off-grid", "not-on-map" },
		subgroup = "wrecks",
		order = "d[remnants]-d[ship-wreck]-c[small]-a",
		max_health = 100,
		minable = {
			mining_time = 0.5 * 3,
			results = {
				{type="item", name = "iron-plate", probability = 0.75, amount_min = 5, amount_max = 25 },
				{type="item", name = "copper-plate", probability = 0.25, amount_min = 5, amount_max = 25 },
				{type="item", name = "iron-gear-wheel", probability = 0.5, amount_min = 2, amount_max = 5 },
			},
		},
		resistances = resistances,
		collision_box = { { -0.7, -0.7 }, { 0.7, 0.7 } },
		collision_mask = collision_mask_nonblocking,
		selection_box = { { -1.3, -1.1 }, { 1.3, 1.1 } },
		pictures = {
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-a.png",
				width = 65,
				height = 68,
			},
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-b.png",
				width = 109,
				height = 67,
			},
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-c.png",
				width = 63,
				height = 54,
			},
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-d.png",
				width = 82,
				height = 67,
			},
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-e.png",
				width = 78,
				height = 75,
				shift = { 0.3, -0.2 },
			},
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-f.png",
				width = 58,
				height = 35,
			},
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-g.png",
				width = 80,
				height = 72,
			},
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-h.png",
				width = 79,
				height = 54,
			},
			{
				filename = "__zzzcompability__/graphics/entity/ship-wreck/small-ship-wreck-i.png",
				width = 56,
				height = 55,
			},
		},
		render_layer = "object",
	},
})
