local l_ruins = {}

table.insert(l_ruins, require("largeRuins/destroyedEnemyFort"))
table.insert(l_ruins, require("largeRuins/destroyedFort"))
table.insert(l_ruins, require("largeRuins/earlyGame"))
table.insert(l_ruins, require("largeRuins/loggingOutpost"))
table.insert(l_ruins, require("largeRuins/mainBus"))
table.insert(l_ruins, require("largeRuins/nuclearPower"))
table.insert(l_ruins, require("largeRuins/orchard"))
table.insert(l_ruins, require("largeRuins/SOS"))
table.insert(l_ruins, require("largeRuins/swamp"))
table.insert(l_ruins, require("largeRuins/trainMining"))
table.insert(l_ruins, require("largeRuins/trainMining2"))
table.insert(l_ruins, require("largeRuins/walledOrchard"))
table.insert(l_ruins, require("largeRuins/walledGrotto"))

table.insert(l_ruins, require("drdLarge/burner1"))
table.insert(l_ruins, require("drdLarge/dump"))
table.insert(l_ruins, require("drdLarge/heater1"))
table.insert(l_ruins, require("drdLarge/laser1-1"))
table.insert(l_ruins, require("drdLarge/ore-comb1"))
table.insert(l_ruins, require("drdLarge/orecrusher1"))
table.insert(l_ruins, require("drdLarge/sniper1-1"))
table.insert(l_ruins, require("drdLarge/traindepo1"))
table.insert(l_ruins, require("drdLarge/turret4-1"))
table.insert(l_ruins, require("drdLarge/turret4-2"))
table.insert(l_ruins, require("drdLarge/turret5-1"))
table.insert(l_ruins, require("drdLarge/turret5-2"))
table.insert(l_ruins, require("drdLarge/turret5-3"))
table.insert(l_ruins, require("drdLarge/turret5-4"))
table.insert(l_ruins, require("drdLarge/wind1"))
table.insert(l_ruins, require("drdLarge/woodfarm1"))

return l_ruins
