data:extend(
{
	--[[{
		type = "fluid",
		name = "water-phosphoric-waste",
		icon = "__Clowns-Processing__/graphics/icons/water-radioactive-waste.png",
		icon_size = 32,
		default_temperature = 25,
		heat_capacity = "0.1KJ",
		base_color = {r = 0.9, g = 0.9, b = 0.4},
		flow_color = {r = 0.9, g = 0.9, b = 0.4},
		max_temperature = 100,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
	},
	{
		type = "fluid",
		name = "water-uranyl-waste",
		icon = "__Clowns-Processing__/graphics/icons/water-radioactive-waste.png",
		icon_size = 32,
		default_temperature = 25,
		heat_capacity = "0.1KJ",
		base_color = {r = 0.9, g = 0.9, b = 0.4},
		flow_color = {r = 0.9, g = 0.9, b = 0.4},
		max_temperature = 100,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
	},
	{
		type = "fluid",
		name = "water-thoric-waste",
		icon = "__Clowns-Processing__/graphics/icons/water-radioactive-waste.png",
		icon_size = 32,
		default_temperature = 25,
		heat_capacity = "0.1KJ",
		base_color = {r = 0.9, g = 0.9, b = 0.4},
		flow_color = {r = 0.9, g = 0.9, b = 0.4},
		max_temperature = 100,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
	},]]
	{
		type = "fluid",
		name = "water-radioactive-waste",
		icon = "__Clowns-AngelBob-Nuclear__/graphics/icons/water-radioactive-waste.png",
		icon_size = 32,
		default_temperature = 25,
		heat_capacity = "0.1KJ",
		base_color = {r = 0, g = 1, b = 0},
		flow_color = {r = 0, g = 1, b = 0},
		max_temperature = 100,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
	},
}
)