return
{
  entities =
  {
    {"transport-belt", {x = 9.5, y = -14.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 9.5, y = -15.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 5.5, y = -12.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 7.5, y = -12.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 6.5, y = -12.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 9.5, y = -13.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 9.5, y = -12.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 8.5, y = -12.5}, {dir = "west", dead = 0.6, }},
    {"lab", {x = -10.5, y = -9.5}, {dead = 0.6, }},
    {"lab", {x = -6.5, y = -9.5}, {dead = 0.6, }},
    {"fast-inserter", {x = -4.5, y = -10.5}, {dir = "west", dead = 0.6, }},
    {"lab", {x = -2.5, y = -9.5}, {dead = 0.6, }},
    {"lab", {x = 1.5, y = -9.5}, {dead = 0.6, }},
    {"fast-inserter", {x = 3.5, y = -10.5}, {dir = "west", }},
    {"fast-inserter", {x = 5.5, y = -11.5}, {}},
    {"lab", {x = 5.5, y = -9.5}, {dead = 0.6, }},
    {"fast-inserter", {x = 6.5, y = -11.5}, {}},
    {"small-electric-pole-remnants", {x = -4.5, y = -9.5}, {}},
    {"fast-inserter", {x = -0.5, y = -8.5}, {dir = "west", dead = 0.6, }},
    {"small-electric-pole-remnants", {x = 3.5, y = -9.5}, {}},
    {"fast-inserter", {x = 3.5, y = -8.5}, {dir = "west", }},
    {"transport-belt", {x = 13.5, y = -8.5}, {dead = 0.6, }},
    {"fast-inserter", {x = -10.5, y = -7.5}, {dir = "south", dead = 0.6, }},
    {"lab", {x = -10.5, y = -5.5}, {dead = 0.6, }},
    {"small-electric-pole-remnants", {x = -8.5, y = -7.5}, {}},
    {"fast-inserter", {x = -8.5, y = -6.5}, {dir = "east", dead = 0.6, }},
    {"lab", {x = -6.5, y = -5.5}, {dead = 0.6, }},
    {"fast-inserter", {x = -4.5, y = -6.5}, {dir = "east", dead = 0.6, }},
    {"lab", {x = -2.5, y = -5.5}, {dead = 0.6, }},
    {"lab", {x = 1.5, y = -5.5}, {dead = 0.6, }},
    {"fast-inserter", {x = 3.5, y = -6.5}, {dir = "east", dead = 0.6, }},
    {"fast-inserter", {x = 4.5, y = -7.5}, {dead = 0.6, }},
    {"small-electric-pole-remnants", {x = 5.5, y = -7.5}, {}},
    {"lab", {x = 5.5, y = -5.5}, {dead = 0.6, }},
    {"fast-inserter", {x = 6.5, y = -7.5}, {dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = -7.5}, {dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = -6.5}, {dead = 0.6, }},
    {"small-electric-pole-remnants", {x = -4.5, y = -5.5}, {}},
    {"small-electric-pole-remnants", {x = -0.5, y = -5.5}, {}},
    {"small-electric-pole-remnants", {x = 3.5, y = -5.5}, {}},
    {"fast-inserter", {x = 3.5, y = -4.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = -5.5}, {}},
    {"transport-belt", {x = 13.5, y = -4.5}, {dead = 0.6, }},
    {"transport-belt", {x = -11.5, y = -3.5}, {dir = "east", }},
    {"transport-belt", {x = -10.5, y = -3.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -9.5, y = -3.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -8.5, y = -3.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -7.5, y = -3.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -6.5, y = -3.5}, {dir = "east", }},
    {"transport-belt", {x = -5.5, y = -3.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -4.5, y = -3.5}, {dir = "south", }},
    {"transport-belt", {x = -4.5, y = -2.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = -3.5}, {dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = -2.5}, {dead = 0.6, }},
    {"straight-rail-remnants", {x = -13, y = -1}, {}},
    {"train-stop-remnants", {x = -11, y = -1}, {}},
    {"transport-belt", {x = -4.5, y = -1.5}, {dir = "south", }},
    {"transport-belt", {x = -4.5, y = -0.5}, {dir = "south", dead = 0.6, }},
    {"small-electric-pole-remnants", {x = 5.5, y = -1.5}, {}},
    {"radar", {x = 7.5, y = 0.5}, {dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = -1.5}, {dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = -0.5}, {dead = 0.6, }},
    {"straight-rail-remnants", {x = -13, y = 1}, {}},
    {"transport-belt", {x = -4.5, y = 0.5}, {dir = "south", }},
    {"transport-belt", {x = -4.5, y = 1.5}, {dir = "south", dead = 0.6, }},
    {"stone-furnace", {x = -1, y = 2}, {dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = 0.5}, {dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = 1.5}, {dead = 0.6, }},
    {"straight-rail-remnants", {x = -13, y = 3}, {}},
    {"transport-belt", {x = -8.5, y = 2.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -7.5, y = 2.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -6.5, y = 2.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -4.5, y = 2.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -4.5, y = 3.5}, {dead = 0.6, }},
    {"transport-belt", {x = -5.5, y = 3.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = -5.5, y = 2.5}, {dir = "south", }},
    {"transport-belt", {x = -3.5, y = 2.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = -3.5, y = 3.5}, {dir = "south", dead = 0.6, }},
    {"stone-furnace", {x = -1, y = 4}, {dead = 0.6, }},
    {"small-electric-pole-remnants", {x = 0.5, y = 3.5}, {}},
    {"fast-inserter", {x = 0.5, y = 2.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 1.5, y = 3.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = 2.5}, {dead = 0.6, }},
    {"transport-belt", {x = 13.5, y = 3.5}, {dead = 0.6, }},
    {"straight-rail-remnants", {x = -13, y = 5}, {}},
    {"small-electric-pole-remnants", {x = -2.5, y = 5.5}, {}},
    {"transport-belt", {x = -3.5, y = 5.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = -3.5, y = 4.5}, {dir = "south", dead = 0.6, }},
    {"fast-inserter", {x = -2.5, y = 4.5}, {dir = "west", }},
    {"stone-furnace", {x = -1, y = 6}, {dead = 0.6, }},
    {"fast-inserter", {x = 0.5, y = 4.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 1.5, y = 4.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 1.5, y = 5.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 7.5, y = 4.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = 7.5, y = 5.5}, {dead = 0.6, }},
    {"transport-belt", {x = 9.5, y = 4.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = 8.5, y = 4.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = 11.5, y = 4.5}, {dir = "east", dead = 0.6, }},
    {"transport-belt", {x = 10.5, y = 4.5}, {dir = "east", }},
    {"transport-belt", {x = 13.5, y = 4.5}, {}},
    {"transport-belt", {x = 12.5, y = 4.5}, {dir = "east", dead = 0.6, }},
    {"straight-rail-remnants", {x = -13, y = 7}, {}},
    {"transport-belt", {x = -3.5, y = 6.5}, {dir = "south", dead = 0.6, }},
    {"fast-inserter", {x = -2.5, y = 6.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = -3.5, y = 7.5}, {dir = "south", dead = 0.6, }},
    {"stone-furnace", {x = -1, y = 8}, {dead = 0.6, }},
    {"small-electric-pole-remnants", {x = 0.5, y = 7.5}, {}},
    {"transport-belt", {x = 1.5, y = 6.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 1.5, y = 7.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 7.5, y = 6.5}, {dead = 0.6, }},
    {"transport-belt", {x = 7.5, y = 7.5}, {dead = 0.6, }},
    {"straight-rail-remnants", {x = -13, y = 9}, {}},
    {"transport-belt", {x = -3.5, y = 9.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = -3.5, y = 8.5}, {dir = "south", dead = 0.6, }},
    {"stone-furnace", {x = -1, y = 10}, {dead = 0.6, }},
    {"fast-inserter", {x = 0.5, y = 8.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 1.5, y = 8.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 1.5, y = 9.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 7.5, y = 8.5}, {}},
    {"transport-belt", {x = 7.5, y = 9.5}, {dead = 0.6, }},
    {"straight-rail-remnants", {x = -13, y = 11}, {}},
    {"small-electric-pole-remnants", {x = -2.5, y = 11.5}, {}},
    {"transport-belt", {x = -3.5, y = 11.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = -3.5, y = 10.5}, {dir = "south", dead = 0.6, }},
    {"fast-inserter", {x = -2.5, y = 10.5}, {dir = "west", dead = 0.6, }},
    {"stone-furnace", {x = -1, y = 12}, {dead = 0.6, }},
    {"small-electric-pole-remnants", {x = 0.5, y = 11.5}, {}},
    {"transport-belt", {x = 1.5, y = 11.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 1.5, y = 10.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = 7.5, y = 10.5}, {}},
    {"transport-belt", {x = 7.5, y = 11.5}, {dead = 0.6, }},
    {"straight-rail-remnants", {x = -13, y = 13}, {}},
    {"fast-inserter", {x = -2.5, y = 12.5}, {dir = "west", }},
    {"transport-belt", {x = -3.5, y = 13.5}, {dir = "south", dead = 0.6, }},
    {"transport-belt", {x = -3.5, y = 12.5}, {dir = "south", dead = 0.6, }},
    {"stone-furnace", {x = -1, y = 14}, {}},
    {"transport-belt", {x = 1.5, y = 13.5}, {dir = "south", dead = 0.6, }},
    {"fast-inserter", {x = 0.5, y = 12.5}, {dir = "west", dead = 0.6, }},
    {"fast-inserter", {x = 0.5, y = 13.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 1.5, y = 12.5}, {dir = "south", dead = 0.6, }},
    {"assembling-machine-2", {x = 4.5, y = 13.5}, {dead = 0.6, }},
    {"fast-inserter", {x = 2.5, y = 13.5}, {dir = "west", dead = 0.6, }},
    {"transport-belt", {x = 7.5, y = 12.5}, {dead = 0.6, }},
    {"fast-inserter", {x = 6.5, y = 12.5}, {dir = "west", dead = 0.6, }},
  },
}
