return
{
  entities =
  {
    {"electric-furnace-remnants", {x = -4.5, y = -13.5}, {}},
    {"express-transport-belt-remnants", {x = -1.5, y = -12.5}, {}},
    {"express-transport-belt", {x = 4.5, y = -12.5}, {dead = 0.2}},
    {"express-transport-belt-remnants", {x = -7.5, y = -11.5}, {}},
    {"express-transport-belt-remnants", {x = -7.5, y = -10.5}, {}},
    {"fast-inserter-remnants", {x = -6.5, y = -10.5}, {dir = "east", }},
    {"electric-furnace", {x = -4.5, y = -10.5}, {dead = 0.2}},
    {"fast-inserter", {x = -2.5, y = -10.5}, {dir = "east", dead = 0.2}},
    {"fast-inserter", {x = -0.5, y = -10.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = -11.5}, {dead = 0.2}},
    {"express-underground-belt-remnants", {x = -1.5, y = -10.5}, {dir = "east", }},
    {"electric-furnace", {x = 1.5, y = -10.5}, {dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -11.5}, {dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -10.5}, {dead = 0.2}},
    {"express-transport-belt-remnants", {x = -7.5, y = -9.5}, {}},
    {"express-transport-belt", {x = -7.5, y = -8.5}, {dead = 0.2}},
    {"beacon", {x = -1.5, y = -8.5}, {}},
    {"electric-furnace", {x = 1.5, y = -7.5}, {dead = 0.2}},
    {"fast-inserter", {x = 3.5, y = -9.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -9.5}, {dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -8.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = -7.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = -6.5}, {dead = 0.2}},
    {"fast-inserter", {x = -6.5, y = -6.5}, {dir = "east", dead = 0.2}},
    {"electric-furnace-remnants", {x = -4.5, y = -7.5}, {}},
    {"fast-inserter", {x = -2.5, y = -6.5}, {dir = "east", dead = 0.2}},
    {"fast-inserter", {x = -0.5, y = -6.5}, {dir = "west", dead = 0.2}},
    {"express-underground-belt", {x = -1.5, y = -6.5}, {dead = 0.2}},
    {"fast-inserter", {x = 3.5, y = -6.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -7.5}, {dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -6.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = -5.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = -4.5}, {dead = 0.2}},
    {"fast-inserter", {x = -6.5, y = -5.5}, {dir = "east", dead = 0.2}},
    {"electric-furnace", {x = -4.5, y = -4.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = -5.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = -4.5}, {dead = 0.2}},
    {"electric-furnace", {x = 1.5, y = -4.5}, {dead = 0.2}},
    {"fast-inserter", {x = 3.5, y = -5.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -5.5}, {dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -4.5}, {dead = 0.2}},
    {"substation-remnants", {x = -9, y = -3}, {}},
    {"express-transport-belt", {x = -7.5, y = -3.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = -2.5}, {dead = 0.2}},
    {"electric-furnace", {x = -4.5, y = -1.5}, {dead = 0.2}},
    {"fast-inserter", {x = -2.5, y = -2.5}, {dir = "east", dead = 0.2}},
    {"fast-inserter", {x = -2.5, y = -3.5}, {dir = "east", dead = 0.2}},
    {"fast-inserter", {x = -0.5, y = -2.5}, {dir = "west", dead = 0.2}},
    {"fast-inserter", {x = -0.5, y = -3.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = -3.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = -2.5}, {dead = 0.2}},
    {"electric-furnace", {x = 1.5, y = -1.5}, {dead = 0.2}},
    {"substation-remnants", {x = 6, y = -3}, {}},
    {"express-transport-belt", {x = 4.5, y = -3.5}, {dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -2.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = -1.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = -0.5}, {dead = 0.2}},
    {"fast-inserter", {x = -6.5, y = -0.5}, {dir = "east", dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = -1.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = -0.5}, {dead = 0.2}},
    {"fast-inserter", {x = 3.5, y = -0.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -1.5}, {dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = -0.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = 0.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = 1.5}, {dead = 0.2}},
    {"fast-inserter", {x = -6.5, y = 0.5}, {dir = "east", dead = 0.2}},
    {"electric-furnace", {x = -4.5, y = 1.5}, {dead = 0.2}},
    {"fast-inserter", {x = -2.5, y = 0.5}, {dir = "east", dead = 0.2}},
    {"fast-inserter", {x = -0.5, y = 0.5}, {dir = "west", dead = 0.2}},
    {"express-underground-belt-remnants", {x = -1.5, y = 0.5}, {dir = "east", }},
    {"electric-furnace", {x = 1.5, y = 1.5}, {dead = 0.2}},
    {"fast-inserter", {x = 3.5, y = 0.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = 0.5}, {dead = 0.2}},
    {"express-transport-belt", {x = 4.5, y = 1.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = 2.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = 3.5}, {dead = 0.2}},
    {"fast-inserter", {x = -6.5, y = 3.5}, {dir = "east", dead = 0.2}},
    {"electric-furnace", {x = -4.5, y = 4.5}, {dead = 0.2}},
    {"beacon-remnants", {x = -1.5, y = 2.5}, {}},
    {"express-transport-belt-remnants", {x = 4.5, y = 3.5}, {}},
    {"express-transport-belt", {x = 4.5, y = 2.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -7.5, y = 4.5}, {dead = 0.2}},
    {"fast-inserter", {x = -2.5, y = 4.5}, {dir = "east", dead = 0.2}},
    {"fast-inserter-remnants", {x = -0.5, y = 4.5}, {dir = "west", }},
    {"express-underground-belt", {x = -1.5, y = 4.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = 5.5}, {dead = 0.2}},
    {"electric-furnace-remnants", {x = 1.5, y = 4.5}, {}},
    {"fast-inserter-remnants", {x = 3.5, y = 4.5}, {dir = "west", }},
    {"express-transport-belt-remnants", {x = 4.5, y = 4.5}, {}},
    {"express-transport-belt", {x = -1.5, y = 7.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = 6.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = 9.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = 8.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -1.5, y = 10.5}, {dead = 0.2}},
    {"express-transport-belt", {x = -0.5, y = 10.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = 1.5, y = 10.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = 0.5, y = 10.5}, {dir = "west", dead = 0.2}},
    {"fast-inserter", {x = 0.5, y = 11.5}, {dir = "south", dead = 0.2}},
    {"fast-inserter", {x = 1.5, y = 11.5}, {dir = "south", dead = 0.2}},
    {"express-transport-belt", {x = 3.5, y = 10.5}, {dir = "west", dead = 0.2}},
    {"express-transport-belt", {x = 2.5, y = 10.5}, {dir = "west", dead = 0.2}},
    {"fast-inserter", {x = 2.5, y = 11.5}, {dir = "south", dead = 0.2}},
    {"fast-inserter", {x = 3.5, y = 11.5}, {dir = "south", dead = 0.2}},
    {"substation-remnants", {x = 5, y = 12}, {}},
    {"curved-rail-remnants", {x = 10, y = 14}, {dir = "east", }},
    {"train-stop-remnants", {x = -7, y = 13}, {dir = "west", }},
    {"iron-chest", {x = 0.5, y = 12.5}, {items = {["iron-ore"] = {type = "random", min = 24, max = 53}}, }},
    {"iron-chest", {x = 1.5, y = 12.5}, {items = {["iron-ore"] = {type = "random", min = 34, max = 80}}, }},
    {"fast-inserter", {x = 1.5, y = 13.5}, {dir = "south", dead = 0.2}},
    {"fast-inserter", {x = 0.5, y = 13.5}, {dir = "south", dead = 0.2}},
    {"iron-chest", {x = 2.5, y = 12.5}, {}},
    {"iron-chest", {x = 3.5, y = 12.5}, {items = {["iron-ore"] = {type = "random", min = 24, max = 53}}, }},
    {"fast-inserter", {x = 3.5, y = 13.5}, {dir = "south", dead = 0.2}},
    {"fast-inserter", {x = 2.5, y = 13.5}, {dir = "south", dead = 0.2}},
    {"straight-rail", {x = -7, y = 15}, {dir = "east", }},
    {"straight-rail", {x = -5, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = -3, y = 15}, {dir = "east", }},
    {"straight-rail", {x = -1, y = 15}, {dir = "east", }},
    {"straight-rail", {x = 1, y = 15}, {dir = "east", }},
    {"straight-rail", {x = 3, y = 15}, {dir = "east", }},
    {"straight-rail", {x = 5, y = 15}, {dir = "east", }},
  },
}
