return
{
  entities =
  {
    {"wall-remnants", {x = -6.5, y = -14.5}, {}},
    {"laser-turret-remnants", {x = -2, y = -15}, {}},
    {"laser-turret-remnants", {x = 1, y = -15}, {}},
    {"laser-turret-remnants", {x = 5, y = -15}, {}},
    {"wall-remnants", {x = -5.5, y = -12.5}, {}},
    {"wall-remnants", {x = -5.5, y = -13.5}, {}},
    {"big-biter-corpse", {x = -0.3, y = -13.44}, {}},
    {"wall-remnants", {x = 1.5, y = -12.5}, {}},
    {"wall-remnants", {x = 0.5, y = -12.5}, {}},
    {"medium-electric-pole-remnants", {x = 3.5, y = -13.5}, {}},
    {"wall-remnants", {x = 3.5, y = -12.5}, {}},
    {"wall-remnants", {x = 2.5, y = -12.5}, {}},
    {"wall-remnants", {x = 4.5, y = -12.5}, {}},
    {"laser-turret-remnants", {x = 10, y = -14}, {}},
    {"land-mine-remnants", {x = -10.5, y = -11.5}, {}},
    {"wall-remnants", {x = -4.5, y = -11.5}, {}},
    {"wall-remnants", {x = -5.5, y = -11.5}, {}},
    {"wall-remnants", {x = -2.5, y = -11.5}, {}},
    {"wall-remnants", {x = -3.5, y = -11.5}, {}},
    {"wall-remnants", {x = -0.5, y = -11.5}, {}},
    {"wall-remnants", {x = -1.5, y = -11.5}, {}},
    {"wall-remnants", {x = 5.5, y = -10.5}, {}},
    {"wall-remnants", {x = 5.5, y = -11.5}, {}},
    {"wall-remnants", {x = 4.5, y = -11.5}, {}},
    {"medium-electric-pole-remnants", {x = 12.5, y = -11.5}, {}},
    {"medium-biter-corpse", {x = -7.38, y = -8.86}, {dir = "east", }},
    {"medium-biter-corpse", {x = -1.67, y = -9.27}, {dir = "east", }},
    {"big-biter-corpse", {x = 1.64, y = -8.29}, {dir = "east", }},
    {"medium-biter-corpse", {x = 7.7, y = -9.2}, {dir = "east", }},
    {"wall-remnants", {x = 7.5, y = -8.5}, {}},
    {"wall-remnants", {x = 6.5, y = -9.5}, {}},
    {"laser-turret-remnants", {x = 11, y = -10}, {}},
    {"land-mine-remnants", {x = -10.5, y = -7.5}, {}},
    {"land-mine-remnants", {x = -3.5, y = -7.5}, {}},
    {"wall-remnants", {x = 7.5, y = -7.5}, {}},
    {"wall-remnants", {x = 8.5, y = -6.5}, {}},
    {"wall-remnants", {x = 8.5, y = -7.5}, {}},
    {"laser-turret-remnants", {x = 11, y = -8}, {}},
    {"big-biter-corpse", {x = -4.75, y = -4.1}, {dir = "southeast", }},
    {"medium-spitter-corpse", {x = 2.69, y = -4.55}, {dir = "east", }},
    {"medium-biter-corpse", {x = 5.28, y = -4.08}, {dir = "east", }},
    {"wall-remnants", {x = 9.5, y = -4.5}, {}},
    {"wall-remnants", {x = 9.5, y = -5.5}, {}},
    {"medium-biter-corpse", {x = 11.89, y = -4.66}, {dir = "southeast", }},
    {"medium-electric-pole-remnants", {x = 14.5, y = -5.5}, {}},
    {"land-mine-remnants", {x = -12.5, y = -2.5}, {}},
    {"medium-spitter-corpse", {x = -10.88, y = -2.91}, {dir = "southeast", }},
    {"land-mine-remnants", {x = -6.5, y = -2.5}, {}},
    {"land-mine-remnants", {x = -0.5, y = -2.5}, {}},
    {"medium-biter-corpse", {x = 0.48, y = -2.55}, {dir = "east", }},
    {"land-mine-remnants", {x = 1.5, y = -2.5}, {}},
    {"land-mine-remnants", {x = 5.5, y = -3.5}, {}},
    {"wall-remnants", {x = 9.5, y = -3.5}, {}},
    {"wall-remnants", {x = 10.5, y = -2.5}, {}},
    {"laser-turret-remnants", {x = 14, y = -3}, {}},
    {"medium-spitter-corpse", {x = -4.29, y = -0.06}, {dir = "east", }},
    {"land-mine-remnants", {x = 0.5, y = -0.5}, {}},
    {"land-mine-remnants", {x = 4.5, y = -1.5}, {}},
    {"wall-remnants", {x = 10.5, y = -0.5}, {}},
    {"wall-remnants", {x = 10.5, y = -1.5}, {}},
    {"laser-turret-remnants", {x = 14, y = -1}, {}},
    {"medium-spitter-corpse", {x = -9.66, y = 0.45}, {dir = "east", }},
    {"land-mine-remnants", {x = -2.5, y = 1.5}, {}},
    {"small-biter-corpse", {x = 3.68, y = 0.81}, {dir = "east", }},
    {"land-mine-remnants", {x = 2.5, y = 1.5}, {}},
    {"wall-remnants", {x = 11.5, y = 1.5}, {}},
    {"wall-remnants", {x = 10.5, y = 1.5}, {}},
    {"wall-remnants", {x = 10.5, y = 0.5}, {}},
    {"land-mine-remnants", {x = -7.5, y = 2.5}, {}},
    {"medium-biter-corpse", {x = -4.18, y = 3.11}, {dir = "east", }},
    {"big-biter-corpse", {x = 8.33, y = 2.3}, {dir = "southeast", }},
    {"wall-remnants", {x = 11.5, y = 2.5}, {}},
    {"wall-remnants", {x = 12.5, y = 3.5}, {}},
    {"wall-remnants", {x = 12.5, y = 2.5}, {}},
    {"big-biter-corpse", {x = -8.95, y = 5.77}, {dir = "east", }},
    {"land-mine-remnants", {x = -3.5, y = 5.5}, {}},
    {"big-biter-corpse", {x = -0.67, y = 4.68}, {dir = "southeast", }},
    {"medium-spitter-corpse", {x = 2.66, y = 5.45}, {dir = "east", }},
    {"land-mine-remnants", {x = 8.5, y = 4.5}, {}},
    {"land-mine-remnants", {x = -11.5, y = 7.5}, {}},
    {"medium-biter-corpse", {x = 6, y = 6.27}, {dir = "east", }},
    {"small-spitter-corpse", {x = -6.57, y = 8.63}, {dir = "east", }},
    {"big-biter-corpse", {x = 9.18, y = 9.38}, {dir = "southeast", }},
    {"medium-biter-corpse", {x = -1, y = 11.6}, {dir = "east", }},
    {"small-spitter-corpse", {x = 3.28, y = 10.34}, {dir = "east", }},
    {"land-mine-remnants", {x = 9.5, y = 11.5}, {}},
    {"small-biter-corpse", {x = -12.01, y = 14.14}, {dir = "east", }},
  },
}
