local graphics = "__mining-patch-planner__/graphics/"

data:extend{
	{
		type = "sprite",
		name = "mpp_advanced_settings",
		filename = graphics.."advanced-settings.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_advanced_settings_black",
		filename = graphics.."advanced-settings-black.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_no_entity",
		filename = graphics.."no-entity.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_plus",
		filename = graphics.."plus.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_cross",
		filename = graphics.."cross.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_blueprint_add",
		filename = graphics.."blueprint_add.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_direction_north",
		filename = graphics.."arrow-north.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_direction_east",
		filename = graphics.."arrow-east.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_direction_south",
		filename = graphics.."arrow-south.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_direction_west",
		filename = graphics.."arrow-west.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_miner_coverage",
		filename = graphics.."miner_coverage.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_miner_coverage_disabled",
		filename = graphics.."miner_coverage_disabled.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_omit_landfill",
		filename = graphics.."omit_landfill.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_align_start",
		filename = graphics.."align_start.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_omit_deconstruct",
		filename = graphics.."omit_deconstruct.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_deconstruct",
		filename = graphics.."deconstruct.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_no_module",
		filename = graphics.."no_module.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_show_all_miners",
		filename = graphics.."show_all_miners.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_no_pipe",
		filename = graphics.."no_pipe.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_no_lamp",
		filename = graphics.."no_lamp.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_force_pipe_disabled",
		filename = graphics.."force_pipe_disabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_force_pipe_enabled",
		filename = graphics.."force_pipe_enabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_print_placement_info_disabled",
		filename = graphics.."print-placement-info-disabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_print_placement_info_enabled",
		filename = graphics.."print-placement-info-enabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_display_lane_filling_disabled",
		filename = graphics.."display-lane-filling-disabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_display_lane_filling_enabled",
		filename = graphics.."display-lane-filling-enabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_debugging_grid_convolution",
		filename = graphics.."grid_convolution.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_entity_filtering_mode_enabled",
		filename = graphics.."entity_filtering_mode_enabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_entity_filtering_mode_disabled",
		filename = graphics.."entity_filtering_mode_disabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_entity_filtered_overlay",
		filename = graphics.."entity_filtered_overlay.png",
		size = 64,
		mipmap_count = 0,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_undo_enabled",
		filename = graphics.."undo_enabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_undo_disabled",
		filename = graphics.."undo_disabled.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_tooltip_category_size",
		filename = graphics.."tooltip-category-size.png",
		priority = "extra-high-no-scale",
		size = 40,
		mipmap_count = 2,
		flags = { "gui-icon" },
		scale = 0.5,
	},
	{
		type = "sprite",
		name = "mpp_tooltip_category_area",
		filename = graphics.."tooltip-category-area.png",
		priority = "extra-high-no-scale",
		size = 40,
		mipmap_count = 2,
		flags = { "gui-icon" },
		scale = 0.5,
	},
	{
		type = "sprite",
		name = "mpp_tooltip_category_mining_area",
		filename = graphics.."tooltip-category-mining-area.png",
		priority = "extra-high-no-scale",
		size = 40,
		mipmap_count = 2,
		flags = { "gui-icon" },
		scale = 0.5,
	},
	{
		type = "sprite",
		name = "mpp_tooltip_category_supply_area",
		filename = graphics.."tooltip-category-supply-area.png",
		priority = "extra-high-no-scale",
		size = 40,
		mipmap_count = 2,
		flags = { "gui-icon" },
		scale = 0.5,
	},
}