replaceSTEAMENGINES("steam-engine", "1")
replaceSTEAMENGINES("steam-engine-2", "2")
replaceSTEAMENGINES("steam-engine-3", "3")
replaceSTEAMENGINES("steam-engine-4", "4")
replaceSTEAMENGINES("steam-engine-5", "5")