return
{
  entities =
  {
    {"medium-electric-pole", {x = -5.5, y = -6.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pump", {x = -4.5, y = -7}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -5.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -4.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe-to-ground", {x = -4.5, y = -5.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"chemical-plant", {x = -2.5, y = -3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 50, max = 150}}, dead = 0.7}},
    {"pipe", {x = -0.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"storage-tank", {x = 1.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"storage-tank", {x = 4.5, y = -3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = -2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -4.5, y = -2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe-to-ground", {x = -4.5, y = -3.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -0.5, y = -2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -0.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"small-lamp", {x = -5.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -5.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -4.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe-to-ground", {x = -4.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"medium-electric-pole", {x = -2.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"chemical-plant", {x = -2.5, y = 0.5}, {dir = "west", dmg = {dmg = {type = "random", min = 50, max = 150}}, dead = 0.7}},
    {"pipe", {x = -0.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -0.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"chemical-plant", {x = 4.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 50, max = 150}}, dead = 0.7}},
    {"pipe", {x = -6.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -4.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe-to-ground", {x = -4.5, y = 0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -0.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -0.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"storage-tank", {x = 6.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"small-lamp", {x = 6.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -5.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -4.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe-to-ground", {x = -4.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"chemical-plant", {x = -2.5, y = 4.5}, {dir = "west", dmg = {dmg = {type = "random", min = 50, max = 150}}, dead = 0.7}},
    {"pipe", {x = -0.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -0.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"medium-electric-pole", {x = 4.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = 5.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -6.5, y = 4.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe-to-ground", {x = -4.5, y = 4.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe", {x = -4.5, y = 5.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"pipe-to-ground", {x = -4.5, y = 6.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"medium-electric-pole", {x = -2.5, y = 6.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"small-lamp", {x = -1.5, y = 6.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
  },
}
