return
{
  entities =
  {
    {"transport-belt-remnants", {x = -6, y = -6}, {dir = "south", }},
    {"fast-transport-belt", {x = -2, y = -6}, {dir = "east", }},
    {"fast-transport-belt", {x = -1, y = -6}, {dir = "east", }},
    {"fast-transport-belt-remnants", {x = 1, y = -6}, {dir = "east", }},
    {"fast-transport-belt-remnants", {x = 0, y = -6}, {dir = "east", }},
    {"fast-transport-belt", {x = 2, y = -6}, {dir = "east", }},
    {"fast-transport-belt", {x = 3, y = -6}, {dir = "east", }},
    {"fast-transport-belt", {x = 4, y = -6}, {dir = "east", }},
    {"fast-transport-belt", {x = 5, y = -6}, {dir = "east", }},
    {"fast-transport-belt", {x = 6, y = -6}, {dir = "east", }},
    {"transport-belt-remnants", {x = -6, y = -5}, {dir = "south", }},
    {"transport-belt", {x = -6, y = -4}, {dir = "south", }},
    {"steel-furnace", {x = -2.5, y = -3.5}, {}},
    {"inserter", {x = -2, y = -5}, {dir = "south", }},
    {"medium-electric-pole", {x = -1, y = -5}, {}},
    {"inserter-remnants", {x = 0, y = -5}, {}},
    {"steel-furnace", {x = 1.5, y = -3.5}, {}},
    {"inserter-remnants", {x = 2, y = -5}, {}},
    {"medium-electric-pole-remnants", {x = 5, y = -5}, {dir = "west", }},
    {"inserter", {x = 4, y = -5}, {dir = "south", }},
    {"steel-furnace", {x = 5.5, y = -3.5}, {}},
    {"inserter-remnants", {x = 6, y = -5}, {}},
    {"underground-belt", {x = -6, y = -2}, {dir = "south", }},
    {"transport-belt", {x = -6, y = -3}, {dir = "south", }},
    {"long-handed-inserter", {x = -3, y = -2}, {dir = "south", }},
    {"long-handed-inserter-remnants", {x = -1, y = -2}, {}},
    {"inserter", {x = -2, y = -2}, {dir = "south", }},
    {"steel-furnace-remnants", {x = -0.5, y = -3.5}, {dir = "south", }},
    {"inserter", {x = 0, y = -2}, {dir = "south", }},
    {"long-handed-inserter", {x = 1, y = -2}, {dir = "south", }},
    {"inserter-remnants", {x = 2, y = -2}, {}},
    {"long-handed-inserter-remnants", {x = 3, y = -2}, {}},
    {"inserter-remnants", {x = 4, y = -2}, {}},
    {"long-handed-inserter-remnants", {x = 5, y = -2}, {}},
    {"steel-furnace-remnants", {x = 3.5, y = -3.5}, {dir = "south", }},
    {"inserter", {x = 6, y = -2}, {dir = "south", }},
    {"fast-transport-belt", {x = -6, y = -1}, {dir = "east", }},
    {"fast-transport-belt", {x = -5, y = -1}, {dir = "east", }},
    {"transport-belt", {x = -5, y = 0}, {dir = "east", }},
    {"underground-belt", {x = -6, y = 0}, {dir = "south", }},
    {"fast-transport-belt", {x = -4, y = -1}, {dir = "east", }},
    {"fast-transport-belt", {x = -3, y = -1}, {dir = "east", }},
    {"transport-belt", {x = -4, y = 0}, {dir = "east", }},
    {"transport-belt", {x = -3, y = 0}, {dir = "east", }},
    {"transport-belt-remnants", {x = -1, y = 0}, {dir = "east", }},
    {"fast-transport-belt", {x = -2, y = -1}, {dir = "east", }},
    {"fast-transport-belt", {x = -1, y = -1}, {dir = "east", }},
    {"transport-belt", {x = -2, y = 0}, {dir = "east", }},
    {"transport-belt-remnants", {x = 1, y = 0}, {dir = "east", }},
    {"transport-belt-remnants", {x = 0, y = 0}, {dir = "east", }},
    {"fast-transport-belt", {x = 0, y = -1}, {dir = "east", }},
    {"fast-transport-belt", {x = 1, y = -1}, {dir = "east", }},
    {"transport-belt-remnants", {x = 3, y = 0}, {dir = "east", }},
    {"transport-belt-remnants", {x = 2, y = 0}, {dir = "east", }},
    {"fast-transport-belt", {x = 2, y = -1}, {dir = "east", }},
    {"fast-transport-belt", {x = 3, y = -1}, {dir = "east", }},
    {"transport-belt-remnants", {x = 5, y = 0}, {dir = "east", }},
    {"transport-belt-remnants", {x = 4, y = 0}, {dir = "east", }},
    {"fast-transport-belt", {x = 4, y = -1}, {dir = "east", }},
    {"fast-transport-belt", {x = 5, y = -1}, {dir = "east", }},
    {"transport-belt-remnants", {x = 6, y = 0}, {dir = "east", }},
    {"fast-transport-belt", {x = 6, y = -1}, {dir = "east", }},
    {"transport-belt", {x = -5, y = 1}, {}},
    {"transport-belt", {x = -6, y = 1}, {dir = "east", }},
    {"fast-transport-belt", {x = -4, y = 1}, {dir = "east", }},
    {"fast-transport-belt", {x = -3, y = 1}, {dir = "east", }},
    {"fast-transport-belt", {x = -4, y = 2}, {}},
    {"long-handed-inserter", {x = -3, y = 2}, {}},
    {"fast-transport-belt", {x = -2, y = 1}, {dir = "east", }},
    {"fast-transport-belt", {x = -1, y = 1}, {dir = "east", }},
    {"long-handed-inserter", {x = -1, y = 2}, {}},
    {"inserter", {x = -2, y = 2}, {}},
    {"inserter-remnants", {x = 0, y = 2}, {}},
    {"long-handed-inserter-remnants", {x = 1, y = 2}, {}},
    {"fast-transport-belt", {x = 0, y = 1}, {dir = "east", }},
    {"fast-transport-belt", {x = 1, y = 1}, {dir = "east", }},
    {"long-handed-inserter-remnants", {x = 3, y = 2}, {}},
    {"fast-transport-belt", {x = 2, y = 1}, {dir = "east", }},
    {"fast-transport-belt", {x = 3, y = 1}, {dir = "east", }},
    {"inserter", {x = 2, y = 2}, {}},
    {"inserter-remnants", {x = 4, y = 2}, {}},
    {"fast-transport-belt-remnants", {x = 5, y = 1}, {dir = "east", }},
    {"fast-transport-belt", {x = 4, y = 1}, {dir = "east", }},
    {"long-handed-inserter", {x = 5, y = 2}, {}},
    {"fast-transport-belt", {x = 6, y = 1}, {dir = "east", }},
    {"inserter", {x = 6, y = 2}, {}},
    {"fast-transport-belt", {x = -5, y = 3}, {dir = "east", }},
    {"fast-transport-belt", {x = -6, y = 3}, {dir = "east", }},
    {"steel-furnace", {x = -2.5, y = 3.5}, {}},
    {"fast-transport-belt", {x = -4, y = 3}, {}},
    {"steel-furnace-remnants", {x = -0.5, y = 3.5}, {dir = "south", }},
    {"steel-furnace", {x = 1.5, y = 3.5}, {}},
    {"steel-furnace", {x = 3.5, y = 3.5}, {}},
    {"steel-furnace", {x = 5.5, y = 3.5}, {}},
    {"medium-electric-pole-remnants", {x = -1, y = 5}, {dir = "east", }},
    {"inserter", {x = -2, y = 5}, {}},
    {"fast-transport-belt", {x = -2, y = 6}, {dir = "east", }},
    {"fast-transport-belt", {x = -1, y = 6}, {dir = "east", }},
    {"inserter-remnants", {x = 0, y = 5}, {}},
    {"fast-transport-belt", {x = 0, y = 6}, {dir = "east", }},
    {"fast-transport-belt", {x = 1, y = 6}, {dir = "east", }},
    {"inserter", {x = 2, y = 5}, {}},
    {"fast-transport-belt", {x = 2, y = 6}, {dir = "east", }},
    {"fast-transport-belt", {x = 3, y = 6}, {dir = "east", }},
    {"inserter-remnants", {x = 4, y = 5}, {}},
    {"fast-transport-belt", {x = 4, y = 6}, {dir = "east", }},
    {"fast-transport-belt", {x = 5, y = 6}, {dir = "east", }},
    {"medium-electric-pole", {x = 5, y = 5}, {}},
    {"inserter", {x = 6, y = 5}, {}},
    {"fast-transport-belt", {x = 6, y = 6}, {dir = "east", }},
  },
}
