return
{
  variables =
  {
    {name = "random-tree", type = "entity-expression", value = {type = "random-of-entity-type", entity_type = "tree"}}
  },
  entities =
  {
    {{type = "variable", name = "random-tree"}, {x = -5.59, y = -5.54}, {}},
    {{type = "variable", name = "random-tree"}, {x = -0.9, y = -5.51}, {}},
    {{type = "variable", name = "random-tree"}, {x = 6.45, y = -4.49}, {}},
    {{type = "variable", name = "random-tree"}, {x = -3.36, y = -3.28}, {}},
    {{type = "variable", name = "random-tree"}, {x = 2.38, y = -3.26}, {}},
    {{type = "variable", name = "random-tree"}, {x = -4.57, y = -0.59}, {}},
    {{type = "variable", name = "random-tree"}, {x = -6.44, y = 1.95}, {}},
    {{type = "variable", name = "random-tree"}, {x = -0.9, y = 0.84}, {}},
    {{type = "variable", name = "random-tree"}, {x = 5.96, y = 1.23}, {}},
    {{type = "variable", name = "random-tree"}, {x = -4.88, y = 5.86}, {}},
    {{type = "variable", name = "random-tree"}, {x = 3.22, y = 6.28}, {}},
    {{type = "variable", name = "random-tree"}, {x = 3.15, y = 5.38}, {}},
    {{type = "variable", name = "random-tree"}, {x = -1.26, y = 6.51}, {}},
    {{type = "variable", name = "random-tree"}, {x = 6.81, y = 6.92}, {}},
  },
  tiles =
  {
    {"water-shallow", {x = -8, y = -4}},
    {"water-shallow", {x = -8, y = -3}},
    {"water-shallow", {x = -8, y = -2}},
    {"water-shallow", {x = -8, y = -1}},
    {"water-shallow", {x = -8, y = 0}},
    {"water-shallow", {x = -8, y = 3}},
    {"water-shallow", {x = -8, y = 4}},
    {"water-shallow", {x = -8, y = 5}},
    {"water-shallow", {x = -7, y = -8}},
    {"water-shallow", {x = -7, y = -5}},
    {"water-shallow", {x = -7, y = -4}},
    {"water-shallow", {x = -7, y = -3}},
    {"water-shallow", {x = -7, y = -2}},
    {"water-shallow", {x = -7, y = -1}},
    {"water-shallow", {x = -7, y = 0}},
    {"water-shallow", {x = -7, y = 3}},
    {"water-shallow", {x = -7, y = 4}},
    {"water-shallow", {x = -7, y = 5}},
    {"water-shallow", {x = -6, y = -5}},
    {"water-shallow", {x = -6, y = -4}},
    {"water-shallow", {x = -6, y = -3}},
    {"water-shallow", {x = -6, y = -2}},
    {"water-shallow", {x = -6, y = -1}},
    {"water-shallow", {x = -6, y = 0}},
    {"water-shallow", {x = -6, y = 1}},
    {"water-shallow", {x = -6, y = 2}},
    {"water-shallow", {x = -6, y = 3}},
    {"water-shallow", {x = -6, y = 4}},
    {"water-shallow", {x = -5, y = -7}},
    {"water-shallow", {x = -5, y = -6}},
    {"water-shallow", {x = -5, y = -5}},
    {"water-shallow", {x = -5, y = -4}},
    {"water-shallow", {x = -5, y = -3}},
    {"water-shallow", {x = -5, y = -2}},
    {"water-shallow", {x = -5, y = 0}},
    {"water-shallow", {x = -5, y = 1}},
    {"water-shallow", {x = -5, y = 2}},
    {"water-shallow", {x = -5, y = 3}},
    {"water-shallow", {x = -5, y = 4}},
    {"water-shallow", {x = -4, y = -8}},
    {"water-shallow", {x = -4, y = -7}},
    {"water-shallow", {x = -4, y = -6}},
    {"water-shallow", {x = -4, y = -5}},
    {"water-shallow", {x = -4, y = -2}},
    {"water-shallow", {x = -4, y = -1}},
    {"water-shallow", {x = -4, y = 0}},
    {"water-shallow", {x = -4, y = 1}},
    {"water-shallow", {x = -4, y = 2}},
    {"water-shallow", {x = -4, y = 3}},
    {"water-shallow", {x = -4, y = 4}},
    {"water-shallow", {x = -4, y = 5}},
    {"water-shallow", {x = -4, y = 6}},
    {"water-shallow", {x = -3, y = -8}},
    {"water-shallow", {x = -3, y = -7}},
    {"water-shallow", {x = -3, y = -6}},
    {"water-shallow", {x = -3, y = -5}},
    {"water-shallow", {x = -3, y = -2}},
    {"water-shallow", {x = -3, y = -1}},
    {"water-shallow", {x = -3, y = 0}},
    {"water-shallow", {x = -3, y = 1}},
    {"water-shallow", {x = -3, y = 2}},
    {"water-shallow", {x = -3, y = 3}},
    {"water-shallow", {x = -3, y = 4}},
    {"water-shallow", {x = -3, y = 5}},
    {"water-shallow", {x = -3, y = 6}},
    {"water-shallow", {x = -2, y = -8}},
    {"water-shallow", {x = -2, y = -7}},
    {"water-shallow", {x = -2, y = -5}},
    {"water-shallow", {x = -2, y = -4}},
    {"water-shallow", {x = -2, y = -3}},
    {"water-shallow", {x = -2, y = -2}},
    {"water-shallow", {x = -2, y = -1}},
    {"water-shallow", {x = -2, y = 2}},
    {"water-shallow", {x = -2, y = 3}},
    {"water-shallow", {x = -2, y = 4}},
    {"water-shallow", {x = -2, y = 5}},
    {"water-shallow", {x = -1, y = -8}},
    {"water-shallow", {x = -1, y = -7}},
    {"water-shallow", {x = -1, y = -5}},
    {"water-shallow", {x = -1, y = -4}},
    {"water-shallow", {x = -1, y = -3}},
    {"water-shallow", {x = -1, y = -2}},
    {"water-shallow", {x = -1, y = -1}},
    {"water-shallow", {x = -1, y = 2}},
    {"water-shallow", {x = -1, y = 3}},
    {"water-shallow", {x = -1, y = 4}},
    {"water-shallow", {x = -1, y = 5}},
    {"water-shallow", {x = 0, y = -8}},
    {"water-shallow", {x = 0, y = -7}},
    {"water-shallow", {x = 0, y = -6}},
    {"water-shallow", {x = 0, y = -5}},
    {"water-shallow", {x = 0, y = -4}},
    {"water-shallow", {x = 0, y = -3}},
    {"water-shallow", {x = 0, y = -2}},
    {"water-shallow", {x = 0, y = -1}},
    {"water-shallow", {x = 0, y = 0}},
    {"water-shallow", {x = 0, y = 1}},
    {"water-shallow", {x = 0, y = 2}},
    {"water-shallow", {x = 0, y = 3}},
    {"water-shallow", {x = 0, y = 4}},
    {"water-shallow", {x = 0, y = 5}},
    {"water-shallow", {x = 0, y = 6}},
    {"water-shallow", {x = 1, y = -8}},
    {"water-shallow", {x = 1, y = -7}},
    {"water-shallow", {x = 1, y = -6}},
    {"water-shallow", {x = 1, y = -5}},
    {"water-shallow", {x = 1, y = -2}},
    {"water-shallow", {x = 1, y = -1}},
    {"water-shallow", {x = 1, y = 0}},
    {"water-shallow", {x = 1, y = 1}},
    {"water-shallow", {x = 1, y = 2}},
    {"water-shallow", {x = 1, y = 3}},
    {"water-shallow", {x = 1, y = 4}},
    {"water-shallow", {x = 1, y = 5}},
    {"water-shallow", {x = 1, y = 6}},
    {"water-shallow", {x = 2, y = -8}},
    {"water-shallow", {x = 2, y = -7}},
    {"water-shallow", {x = 2, y = -6}},
    {"water-shallow", {x = 2, y = -5}},
    {"water-shallow", {x = 2, y = -2}},
    {"water-shallow", {x = 2, y = -1}},
    {"water-shallow", {x = 2, y = 0}},
    {"water-shallow", {x = 2, y = 1}},
    {"water-shallow", {x = 2, y = 2}},
    {"water-shallow", {x = 2, y = 3}},
    {"water-shallow", {x = 3, y = -8}},
    {"water-shallow", {x = 3, y = -7}},
    {"water-shallow", {x = 3, y = -6}},
    {"water-shallow", {x = 3, y = -5}},
    {"water-shallow", {x = 3, y = -4}},
    {"water-shallow", {x = 3, y = -3}},
    {"water-shallow", {x = 3, y = -2}},
    {"water-shallow", {x = 3, y = -1}},
    {"water-shallow", {x = 3, y = 0}},
    {"water-shallow", {x = 3, y = 1}},
    {"water-shallow", {x = 3, y = 2}},
    {"water-shallow", {x = 3, y = 3}},
    {"water-shallow", {x = 4, y = -8}},
    {"water-shallow", {x = 4, y = -7}},
    {"water-shallow", {x = 4, y = -6}},
    {"water-shallow", {x = 4, y = -5}},
    {"water-shallow", {x = 4, y = -4}},
    {"water-shallow", {x = 4, y = -3}},
    {"water-shallow", {x = 4, y = -2}},
    {"water-shallow", {x = 4, y = -1}},
    {"water-shallow", {x = 4, y = 0}},
    {"water-shallow", {x = 4, y = 1}},
    {"water-shallow", {x = 4, y = 2}},
    {"water-shallow", {x = 4, y = 3}},
    {"water-shallow", {x = 4, y = 4}},
    {"water-shallow", {x = 4, y = 5}},
    {"water-shallow", {x = 4, y = 6}},
    {"water-shallow", {x = 5, y = -8}},
    {"water-shallow", {x = 5, y = -7}},
    {"water-shallow", {x = 5, y = -6}},
    {"water-shallow", {x = 5, y = -5}},
    {"water-shallow", {x = 5, y = -4}},
    {"water-shallow", {x = 5, y = -3}},
    {"water-shallow", {x = 5, y = -2}},
    {"water-shallow", {x = 5, y = -1}},
    {"water-shallow", {x = 5, y = 2}},
    {"water-shallow", {x = 5, y = 3}},
    {"water-shallow", {x = 5, y = 4}},
    {"water-shallow", {x = 5, y = 5}},
    {"water-shallow", {x = 5, y = 6}},
    {"water-shallow", {x = 6, y = -8}},
    {"water-shallow", {x = 6, y = -7}},
    {"water-shallow", {x = 6, y = -6}},
    {"water-shallow", {x = 6, y = -4}},
    {"water-shallow", {x = 6, y = -3}},
    {"water-shallow", {x = 6, y = -2}},
    {"water-shallow", {x = 6, y = -1}},
    {"water-shallow", {x = 6, y = 2}},
    {"water-shallow", {x = 6, y = 3}},
    {"water-shallow", {x = 6, y = 4}},
    {"water-shallow", {x = 6, y = 5}},
    {"water-shallow", {x = 7, y = -2}},
    {"water-shallow", {x = 7, y = -1}},
    {"water-shallow", {x = 7, y = 0}},
    {"water-shallow", {x = 7, y = 1}},
    {"water-shallow", {x = 7, y = 2}},
    {"water-shallow", {x = 7, y = 3}},
    {"water-shallow", {x = 7, y = 4}},
    {"water-shallow", {x = 7, y = 5}},
  }
}
