return
{
  entities =
  {
    {"stone-wall", {x = -5.5, y = -4.5}, {}},
    {"tree-05", {x = -4.5, y = -4.5}, {}},
    {"stone-wall", {x = -5.5, y = -5.5}, {}},
    {"stone-wall", {x = -4.5, y = -5.5}, {}},
    {"stone-wall", {x = -2.5, y = -5.5}, {}},
    {"gate", {x = -3.5, y = -5.5}, {dir = "east", }},
    {"stone-wall", {x = -1.5, y = -5.5}, {}},
    {"stone-wall", {x = -0.5, y = -5.5}, {}},
    {"stone-wall", {x = 0.5, y = -5.5}, {}},
    {"stone-wall", {x = 3.5, y = -5.5}, {}},
    {"stone-wall", {x = 6.5, y = -4.5}, {}},
    {"stone-wall", {x = 6.5, y = -5.5}, {}},
    {"stone-wall", {x = -5.5, y = -2.5}, {}},
    {"stone-wall", {x = -4.5, y = -2.5}, {}},
    {"stone-wall", {x = -5.5, y = -3.5}, {}},
    {"stone-wall", {x = -3.5, y = -2.5}, {}},
    {"stone-wall", {x = -2.5, y = -2.5}, {}},
    {"pipe-to-ground", {x = -0.5, y = -2.5}, {}},
    {"pipe-to-ground", {x = -0.5, y = -3.5}, {dir = "south", }},
    {"stone-wall", {x = 0.5, y = -2.5}, {}},
    {"stone-wall", {x = 1.5, y = -2.5}, {}},
    {"stone-wall", {x = 2.5, y = -2.5}, {}},
    {"stone-wall", {x = 3.5, y = -2.5}, {}},
    {"land-mine", {x = 2.45, y = -1.72}, {force = "enemy", }},
    {"stone-wall", {x = 2.5, y = -3.5}, {}},
    {"stone-wall", {x = 4.5, y = -2.5}, {}},
    {"tree-05", {x = -1.5, y = -1.5}, {}},
    {"tree-05", {x = 4.5, y = -1.5}, {}},
    {"stone-wall", {x = 6.5, y = -0.5}, {}},
    {"stone-wall", {x = 6.5, y = -1.5}, {}},
    {"stone-wall", {x = -5.5, y = 1.5}, {}},
    {"stone-wall", {x = -4.5, y = 1.5}, {}},
    {"stone-wall", {x = -5.5, y = 0.5}, {}},
    {"stone-wall", {x = -2.5, y = 1.5}, {}},
    {"stone-wall", {x = -1.5, y = 1.5}, {}},
    {"gate", {x = -0.5, y = 1.5}, {dir = "east", }},
    {"stone-wall", {x = -1.5, y = 0.5}, {}},
    {"stone-wall", {x = 0.5, y = 1.5}, {}},
    {"stone-wall", {x = 1.5, y = 1.5}, {}},
    {"stone-wall", {x = 2.5, y = 1.5}, {}},
    {"stone-wall", {x = 3.5, y = 1.5}, {}},
    {"stone-wall", {x = 4.5, y = 1.5}, {}},
    {"stone-wall", {x = 4.5, y = 0.5}, {}},
    {"stone-wall", {x = 6.5, y = 0.5}, {}},
    {"stone-wall", {x = -5.5, y = 3.5}, {}},
    {"stone-wall", {x = -5.5, y = 2.5}, {}},
    {"land-mine", {x = -4.34, y = 2.50}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = 2.5}, {}},
    {"tree-05", {x = 2.5, y = 2.5}, {}},
    {"stone-wall", {x = 4.5, y = 3.5}, {}},
    {"stone-wall", {x = 4.5, y = 2.5}, {}},
    {"stone-wall", {x = 6.5, y = 3.5}, {}},
    {"stone-wall", {x = -4.5, y = 5.5}, {}},
    {"stone-wall", {x = -5.5, y = 4.5}, {}},
    {"stone-wall", {x = -2.5, y = 5.5}, {}},
    {"stone-wall", {x = -1.5, y = 5.5}, {}},
    {"stone-wall", {x = -0.5, y = 5.5}, {}},
    {"stone-wall", {x = 0.5, y = 5.5}, {}},
    {"gate", {x = 1.5, y = 5.5}, {dir = "east", }},
    {"stone-wall", {x = 0.5, y = 4.5}, {}},
    {"stone-wall", {x = 3.5, y = 5.5}, {}},
    {"stone-wall", {x = 2.5, y = 5.5}, {}},
    {"stone-wall", {x = 4.5, y = 5.5}, {}},
    {"gate", {x = 5.5, y = 5.5}, {dir = "east", }},
    {"stone-wall", {x = 4.5, y = 4.5}, {}},
    {"stone-wall", {x = 6.5, y = 5.5}, {}},
    {"stone-wall", {x = 6.5, y = 4.5}, {}},
  },
}
