data:extend({
	{
		type = "recipe",
		name = "super_charger",
		energy_required = 20,
		enabled = false,
		ingredients = {
			{ type = "item", name = "bet-charger-3", amount = 2 },
			{ type = "item", name = "bob-advanced-processing-unit", amount = 50 },
			{ type = "item", name = "bob-insulated-cable", amount = 30 },
			{ type = "item", name = "bob-gilded-copper-cable", amount = 20 },
			{ type = "item", name = "bob-nitinol-gear-wheel", amount = 5 },
			{ type = "item", name = "bob-nitinol-alloy", amount = 30 },
			{ type = "item", name = "bob-speed-module-4", amount = 2 },
		},
		results = { { type = "item", name = "super_charger", amount = 1 } },
	},
	{
		type = "recipe",
		name = "hiend_loco",
		energy_required = 5,
		enabled = false,
		ingredients = {
			{ type = "item", name = "bet-locomotive", amount = 1 },
			{ type = "item", name = "bob-advanced-processing-unit", amount = 20 },
			{ type = "item", name = "bob-nitinol-bearing", amount = 20 },
			{ type = "item", name = "bob-nitinol-gear-wheel", amount = 15 },
			{ type = "item", name = "bob-nitinol-alloy", amount = 10 },
			{ type = "item", name = "bob-speed-module-4", amount = 5 },
		},
		results = { { type = "item", name = "hiend_loco", amount = 1 } },
	},
	{
		type = "recipe",
		name = "hiend_wagon",
		energy_required = 5,
		enabled = false,
		ingredients = {
			{ type = "item", name = "bob-cargo-wagon-3", amount = 1 },
			{ type = "item", name = "bob-advanced-processing-unit", amount = 20 },
			{ type = "item", name = "bob-nitinol-bearing", amount = 15 },
			{ type = "item", name = "bob-nitinol-gear-wheel", amount = 10 },
			{ type = "item", name = "bob-nitinol-alloy", amount = 10 },
		},
		results = { { type = "item", name = "hiend_wagon", amount = 1 } },
	},
	{
		type = "recipe",
		name = "hiend_fluid_wagon",
		energy_required = 5,
		enabled = false,
		ingredients = {
			{ type = "item", name = "bob-fluid-wagon-3", amount = 1 },
			{ type = "item", name = "bob-advanced-processing-unit", amount = 20 },
			{ type = "item", name = "bob-nitinol-bearing", amount = 15 },
			{ type = "item", name = "bob-nitinol-gear-wheel", amount = 10 },
			{ type = "item", name = "bob-nitinol-alloy", amount = 10 },
			{ type = "item", name = "bob-storage-tank-4", amount = 1 },
		},
		results = { { type = "item", name = "hiend_fluid_wagon", amount = 1 } },
	},
})
