replaceSTONEFURNACE("stone-furnace")
replaceCHEMICALSTONEFURNACE("chemical-boiler")
replaceMIXINGSTONEFURNACE("mixing-furnace")
replaceSTEELFURNACE("steel-furnace")
replaceASTEELFURNACE("chemical-steel-furnace", "chemical-steel-furnace" )
replaceASTEELFURNACE("mixing-steel-furnace", "mixing-steel-furnace" )
replaceELECTRICFURNACE("electric-furnace", "1" )
replaceELECTRICFURNACE("electric-furnace-2", "2" )
replaceELECTRICFURNACE("electric-furnace-3", "3" )
replaceAELECTRICFURNACE("electric-chemical-mixing-furnace", "electric-multitask-furnace-1" )
replaceAELECTRICFURNACE("electric-chemical-mixing-furnace-2", "electric-multitask-furnace-2" )
replaceAELECTRICFURNACE("chemical-furnace", "chemical-electric-furnace" )
replaceAELECTRICFURNACE("electric-mixing-furnace", "electric-mixing-furnace" )
