data:extend({
{
    type = "fluid",
    name = "gas-nitrous-oxide",
    icon = "__PCP__/graphics/icons/gas-nitrous-oxide.png",
	icon_size = 32,
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 1, g = 1, b = 1},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-hydrogen-cyanide",
    icon = "__PCP__/graphics/icons/gas-hydrogen-cyanide.png",
	icon_size = 32,
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 1, g = 1, b = 1},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-phosgene",
    icon = "__PCP__/graphics/icons/gas-phosgene.png",
	icon_size = 32,
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 1, g = 1, b = 1},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-acetone",
    icon = "__PCP__/graphics/icons/liquid-acetone.png",
	icon_size = 32,
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 1, g = 1, b = 1},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-acetone-cyanohydrin",
    icon = "__PCP__/graphics/icons/liquid-acetone-cyanohydrin.png",
	icon_size = 32,
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 1, g = 1, b = 1},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-acrylonitrile",
    icon = "__PCP__/graphics/icons/liquid-acrylonitrile.png",
	icon_size = 32,
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 1, g = 1, b = 1},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-methyl-methacrylate",
    icon = "__PCP__/graphics/icons/liquid-methyl-methacrylate.png",
	icon_size = 32,
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 1, g = 1, b = 1},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-vinyl-chloride",
    icon = "__PCP__/graphics/icons/gas-vinyl-chloride.png",
	icon_size = 32,
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 1, g = 1, b = 1},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
})