return
{
  entities =
  {
    {"electric-mining-drill", {x = -6.5, y = -13.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -4.5, y = -14.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -2.5, y = -13.5}, {dir = "west", }},
    {"fast-transport-belt", {x = -4.5, y = -12.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = -13.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -6.5, y = -10.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -4.5, y = -10.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = -11.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -2.5, y = -10.5}, {dir = "west", }},
    {"electric-mining-drill", {x = 1.5, y = -10.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 3.5, y = -10.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 5.5, y = -10.5}, {dir = "west", }},
    {"medium-electric-pole", {x = 7.5, y = -10.5}, {}},
    {"medium-electric-pole", {x = -8.5, y = -9.5}, {}},
    {"electric-mining-drill", {x = -6.5, y = -7.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -4.5, y = -8.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = -9.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -2.5, y = -7.5}, {dir = "west", }},
    {"medium-electric-pole", {x = -0.5, y = -9.5}, {}},
    {"fast-transport-belt", {x = 3.5, y = -8.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = -9.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 5.5, y = -7.5}, {dir = "west", }},
    {"fast-transport-belt", {x = -4.5, y = -6.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = -7.5}, {dir = "south", }},
    {"electric-mining-drill-remnants", {x = 1.5, y = -7.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = -6.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = -7.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -6.5, y = -4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -4.5, y = -4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = -5.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -2.5, y = -4.5}, {dir = "west", }},
    {"electric-mining-drill", {x = 1.5, y = -4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 3.5, y = -4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = -5.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 5.5, y = -4.5}, {dir = "west", }},
    {"electric-mining-drill", {x = 9.5, y = -4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 11.5, y = -4.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 13.5, y = -4.5}, {dir = "west", }},
    {"medium-electric-pole", {x = -8.5, y = -3.5}, {}},
    {"fast-transport-belt", {x = -4.5, y = -2.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = -3.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -2.5, y = -1.5}, {dir = "west", }},
    {"medium-electric-pole", {x = -0.5, y = -2.5}, {}},
    {"fast-transport-belt", {x = 3.5, y = -2.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = -3.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 5.5, y = -1.5}, {dir = "west", }},
    {"medium-electric-pole", {x = 7.5, y = -3.5}, {}},
    {"fast-transport-belt", {x = 11.5, y = -2.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = -3.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 13.5, y = -1.5}, {dir = "west", }},
    {"medium-electric-pole", {x = 15.5, y = -3.5}, {}},
    {"electric-mining-drill-remnants", {x = -6.5, y = -1.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = -0.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = -1.5}, {dir = "south", }},
    {"electric-mining-drill-remnants", {x = 1.5, y = -1.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = -0.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = -1.5}, {dir = "south", }},
    {"electric-mining-drill-remnants", {x = 9.5, y = -1.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = -0.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = -1.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -6.5, y = 1.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -4.5, y = 1.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = 0.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -2.5, y = 1.5}, {dir = "west", }},
    {"electric-mining-drill-remnants", {x = 1.5, y = 1.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = 0.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = 1.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 5.5, y = 1.5}, {dir = "west", }},
    {"electric-mining-drill", {x = 9.5, y = 1.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 11.5, y = 1.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = 0.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 13.5, y = 1.5}, {dir = "west", }},
    {"electric-mining-drill", {x = -6.5, y = 4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -4.5, y = 3.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = 2.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 1.5, y = 4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 3.5, y = 3.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = 2.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 5.5, y = 4.5}, {dir = "west", }},
    {"fast-transport-belt", {x = 11.5, y = 3.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = 2.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 13.5, y = 4.5}, {dir = "west", }},
    {"medium-electric-pole", {x = -8.5, y = 4.5}, {}},
    {"fast-transport-belt", {x = -4.5, y = 4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = 5.5}, {dir = "south", }},
    {"electric-mining-drill-remnants", {x = -2.5, y = 4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = 4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = 5.5}, {dir = "south", }},
    {"medium-electric-pole", {x = 7.5, y = 5.5}, {}},
    {"electric-mining-drill-remnants", {x = 9.5, y = 4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = 5.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = 4.5}, {dir = "south", }},
    {"medium-electric-pole", {x = 15.5, y = 5.5}, {}},
    {"stone-wall", {x = -14.5, y = 7.5}, {}},
    {"wall-remnants", {x = -14.5, y = 6.5}, {}},
    {"stone-wall", {x = -12.5, y = 7.5}, {}},
    {"stone-wall", {x = -12.5, y = 6.5}, {}},
    {"stone-wall", {x = -13.5, y = 7.5}, {}},
    {"wall-remnants", {x = -13.5, y = 6.5}, {}},
    {"stone-wall", {x = -10.5, y = 6.5}, {}},
    {"stone-wall", {x = -10.5, y = 7.5}, {}},
    {"stone-wall", {x = -11.5, y = 6.5}, {}},
    {"stone-wall", {x = -11.5, y = 7.5}, {}},
    {"stone-wall", {x = -8.5, y = 6.5}, {}},
    {"stone-wall", {x = -9.5, y = 6.5}, {}},
    {"stone-wall", {x = -9.5, y = 7.5}, {}},
    {"electric-mining-drill", {x = -6.5, y = 7.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -4.5, y = 7.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = 6.5}, {dir = "south", }},
    {"electric-mining-drill", {x = -2.5, y = 7.5}, {dir = "west", }},
    {"medium-electric-pole", {x = -0.5, y = 6.5}, {}},
    {"electric-mining-drill", {x = 1.5, y = 7.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 3.5, y = 7.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = 6.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 5.5, y = 7.5}, {dir = "west", }},
    {"electric-mining-drill", {x = 9.5, y = 7.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 11.5, y = 7.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = 6.5}, {dir = "south", }},
    {"electric-mining-drill", {x = 13.5, y = 7.5}, {dir = "west", }},
    {"stone-wall", {x = -14.5, y = 9.5}, {}},
    {"wall-remnants", {x = -14.5, y = 8.5}, {}},
    {"laser-turret", {x = -13, y = 9}, {dir = "west", }},
    {"laser-turret", {x = -11, y = 9}, {dir = "west", }},
    {"laser-turret", {x = -9, y = 9}, {dir = "west", }},
    {"stone-wall", {x = -6.5, y = 9.5}, {}},
    {"stone-wall", {x = -7.5, y = 9.5}, {}},
    {"fast-transport-belt", {x = -4.5, y = 9.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = 8.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = 9.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 3.5, y = 8.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = 9.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 11.5, y = 8.5}, {dir = "south", }},
    {"wall-remnants", {x = -14.5, y = 10.5}, {}},
    {"wall-remnants", {x = -14.5, y = 11.5}, {}},
    {"laser-turret", {x = -13, y = 11}, {dir = "west", }},
    {"medium-electric-pole", {x = -10.5, y = 10.5}, {}},
    {"laser-turret", {x = -9, y = 11}, {dir = "west", }},
    {"stone-wall", {x = -6.5, y = 11.5}, {}},
    {"stone-wall", {x = -6.5, y = 10.5}, {}},
    {"stone-wall", {x = -7.5, y = 10.5}, {}},
    {"stone-wall", {x = -7.5, y = 11.5}, {}},
    {"fast-transport-belt", {x = -4.5, y = 10.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -2.5, y = 10.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -3.5, y = 10.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -0.5, y = 10.5}, {dir = "east", }},
    {"fast-inserter-remnants", {x = -0.5, y = 11.5}, {}},
    {"fast-inserter", {x = -1.5, y = 11.5}, {}},
    {"fast-transport-belt", {x = -1.5, y = 10.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 1.5, y = 10.5}, {dir = "east", }},
    {"fast-inserter-remnants", {x = 1.5, y = 11.5}, {}},
    {"fast-transport-belt", {x = 0.5, y = 10.5}, {dir = "east", }},
    {"fast-inserter", {x = 0.5, y = 11.5}, {}},
    {"fast-transport-belt", {x = 3.5, y = 10.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 5.5, y = 10.5}, {dir = "east", }},
    {"fast-inserter", {x = 5.5, y = 11.5}, {}},
    {"fast-transport-belt", {x = 4.5, y = 10.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 7.5, y = 10.5}, {dir = "west", }},
    {"fast-inserter-remnants", {x = 7.5, y = 11.5}, {}},
    {"fast-transport-belt", {x = 6.5, y = 10.5}, {dir = "east", }},
    {"fast-inserter", {x = 6.5, y = 11.5}, {}},
    {"fast-transport-belt", {x = 9.5, y = 10.5}, {dir = "west", }},
    {"fast-inserter", {x = 8.5, y = 11.5}, {}},
    {"fast-transport-belt", {x = 8.5, y = 10.5}, {dir = "west", }},
    {"fast-transport-belt", {x = 11.5, y = 10.5}, {dir = "west", }},
    {"fast-transport-belt", {x = 10.5, y = 10.5}, {dir = "west", }},
    {"stone-wall", {x = -14.5, y = 12.5}, {}},
    {"stone-wall", {x = -14.5, y = 13.5}, {dmg = {dmg = 172}, }},
    {"laser-turret", {x = -13, y = 13}, {dir = "west", }},
    {"lamp-remnants", {x = -11.5, y = 12.5}, {}},
    {"train-stop-remnants", {x = -11, y = 13}, {dir = "west", }},
    {"wall-remnants", {x = -8.5, y = 13.5}, {}},
    {"stone-wall", {x = -6.5, y = 13.5}, {}},
    {"stone-wall", {x = -6.5, y = 12.5}, {}},
    {"wall-remnants", {x = -7.5, y = 13.5}, {}},
    {"medium-electric-pole", {x = -4.5, y = 12.5}, {}},
    {"steel-chest", {x = -0.5, y = 12.5}, {}},
    {"fast-inserter-remnants", {x = -0.5, y = 13.5}, {}},
    {"steel-chest", {x = -1.5, y = 12.5}, {}},
    {"fast-inserter-remnants", {x = -1.5, y = 13.5}, {}},
    {"fast-inserter", {x = 1.5, y = 13.5}, {}},
    {"steel-chest", {x = 1.5, y = 12.5}, {}},
    {"fast-inserter", {x = 0.5, y = 13.5}, {}},
    {"steel-chest-remnants", {x = 0.5, y = 12.5}, {dir = "east", }},
    {"medium-electric-pole-remnants", {x = 3.5, y = 12.5}, {dir = "east", }},
    {"lamp-remnants", {x = 2.5, y = 12.5}, {}},
    {"fast-inserter", {x = 5.5, y = 13.5}, {}},
    {"steel-chest-remnants", {x = 5.5, y = 12.5}, {dir = "east", }},
    {"lamp-remnants", {x = 4.5, y = 12.5}, {}},
    {"fast-inserter", {x = 7.5, y = 13.5}, {}},
    {"steel-chest", {x = 7.5, y = 12.5}, {}},
    {"steel-chest", {x = 6.5, y = 12.5}, {}},
    {"fast-inserter-remnants", {x = 6.5, y = 13.5}, {}},
    {"lamp-remnants", {x = 9.5, y = 12.5}, {}},
    {"fast-inserter", {x = 8.5, y = 13.5}, {}},
    {"steel-chest-remnants", {x = 8.5, y = 12.5}, {dir = "east", }},
    {"medium-electric-pole-remnants", {x = 10.5, y = 12.5}, {dir = "east", }},
    {"stone-wall", {x = -14.5, y = 14.5}, {}},
    {"stone-wall", {x = -12.5, y = 14.5}, {}},
    {"stone-wall", {x = -13.5, y = 14.5}, {}},
    {"straight-rail", {x = -11, y = 15}, {dir = "east", }},
    {"straight-rail", {x = -9, y = 15}, {dir = "east", }},
    {"straight-rail", {x = -7, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = -5, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = -3, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = -1, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = 1, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = 3, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = 5, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = 7, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = 9, y = 15}, {dir = "east", }},
    {"straight-rail", {x = 11, y = 15}, {dir = "east", }},
    {"straight-rail", {x = 13, y = 15}, {dir = "east", }},
    {"straight-rail-remnants", {x = 15, y = 15}, {dir = "east", }},
  },
}
