flib = require("__flib__.data-util")
require("__automated-utility-protocol__.util.main")
require("resources")
require("basic-technologies")
require("items")
require("entities")
require("recipes")
require("copying-for-modes.copy-to-normal-expensive-mode-data")
require("crash-site-spaceship-entries")
flib = nil
