return
{
  entities =
  {
    {"big-electric-pole-remnants", {x = -6, y = -13}, {dir = "east", }},
    {"stone-wall", {x = -8.5, y = -4.5}, {}},
    {"stone-wall", {x = -7.5, y = -4.5}, {}},
    {"stone-wall", {x = -6.5, y = -4.5}, {}},
    {"stone-wall", {x = -5.5, y = -4.5}, {}},
    {"stone-wall", {x = -4.5, y = -4.5}, {}},
    {"wall-remnants", {x = -3.5, y = -4.5}, {dir = "east", }},
    {"stone-wall", {x = -2.5, y = -4.5}, {}},
    {"stone-wall", {x = -1.5, y = -4.5}, {}},
    {"stone-wall", {x = -0.5, y = -4.5}, {}},
    {"wall-remnants", {x = 1.5, y = -4.5}, {dir = "east", }},
    {"wall-remnants", {x = 0.5, y = -4.5}, {dir = "east", }},
    {"stone-wall", {x = 2.5, y = -4.5}, {}},
    {"stone-wall", {x = 3.5, y = -4.5}, {}},
    {"wall-remnants", {x = 4.5, y = -4.5}, {dir = "east", }},
    {"stone-wall", {x = 5.5, y = -4.5}, {}},
    {"stone-wall", {x = 7.5, y = -4.5}, {}},
    {"stone-wall", {x = 6.5, y = -4.5}, {}},
    {"wall-remnants", {x = 9.5, y = -4.5}, {dir = "east", }},
    {"stone-wall", {x = 8.5, y = -4.5}, {}},
    {"stone-wall", {x = -8.5, y = -2.5}, {}},
    {"stone-wall", {x = -8.5, y = -3.5}, {}},
    {"laser-turret-remnants", {x = -6, y = -3}, {dir = "east", }},
    {"laser-turret-remnants", {x = -2, y = -3}, {dir = "east", }},
    {"laser-turret-remnants", {x = 7, y = -3}, {dir = "east", }},
    {"wall-remnants", {x = 9.5, y = -2.5}, {dir = "east", }},
    {"stone-wall", {x = 9.5, y = -3.5}, {}},
    {"wall-remnants", {x = -8.5, y = -0.5}, {dir = "east", }},
    {"stone-wall", {x = -8.5, y = -1.5}, {}},
    {"big-electric-pole-remnants", {x = -4, y = -1}, {dir = "east", }},
    {"radar", {x = -0.5, y = -0.5}, {}},
    {"radar-remnants", {x = 2.5, y = -0.5}, {dir = "east", }},
    {"radar", {x = 5.5, y = -0.5}, {}},
    {"medium-electric-pole-remnants", {x = 7.5, y = -1.5}, {}},
    {"stone-wall", {x = 9.5, y = -1.5}, {}},
    {"stone-wall", {x = 9.5, y = -0.5}, {}},
    {"stone-wall", {x = -8.5, y = 1.5}, {}},
    {"stone-wall", {x = -8.5, y = 0.5}, {}},
    {"medium-electric-pole-remnants", {x = -3.5, y = 1.5}, {}},
    {"medium-electric-pole-remnants", {x = 5.5, y = 1.5}, {}},
    {"stone-wall", {x = 9.5, y = 0.5}, {}},
    {"stone-wall", {x = 9.5, y = 1.5}, {}},
    {"stone-wall", {x = -8.5, y = 3.5}, {}},
    {"stone-wall", {x = -8.5, y = 2.5}, {}},
    {"gun-turret", {x = -7, y = 3}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"laser-turret-remnants", {x = -2, y = 3}, {dir = "east", }},
    {"laser-turret-remnants", {x = 3, y = 3}, {dir = "east", }},
    {"gun-turret", {x = 8, y = 3}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"wall-remnants", {x = 9.5, y = 2.5}, {dir = "east", }},
    {"stone-wall", {x = 9.5, y = 3.5}, {}},
    {"stone-wall", {x = -8.5, y = 4.5}, {}},
    {"stone-wall", {x = -6.5, y = 4.5}, {}},
    {"stone-wall", {x = -7.5, y = 4.5}, {}},
    {"stone-wall", {x = -4.5, y = 4.5}, {}},
    {"stone-wall", {x = -5.5, y = 4.5}, {}},
    {"wall-remnants", {x = -3.5, y = 4.5}, {dir = "east", }},
    {"stone-wall", {x = -2.5, y = 4.5}, {}},
    {"gate", {x = -0.5, y = 4.5}, {dir = "east", }},
    {"stone-wall", {x = -1.5, y = 4.5}, {}},
    {"gate-remnants", {x = 1.5, y = 4.5}, {dir = "east", }},
    {"gate", {x = 0.5, y = 4.5}, {dir = "east", }},
    {"gate", {x = 2.5, y = 4.5}, {dir = "east", }},
    {"stone-wall", {x = 3.5, y = 4.5}, {}},
    {"stone-wall", {x = 5.5, y = 4.5}, {}},
    {"stone-wall", {x = 4.5, y = 4.5}, {}},
    {"wall-remnants", {x = 6.5, y = 4.5}, {dir = "east", }},
    {"stone-wall", {x = 7.5, y = 4.5}, {}},
    {"stone-wall", {x = 9.5, y = 4.5}, {}},
    {"stone-wall", {x = 8.5, y = 4.5}, {}},
    {"big-electric-pole-remnants", {x = 13, y = 14}, {dir = "east", }},
  },
}
