return {
	info = '[img=virtual-signal/signal-info]',
	sig_yellow = '[img=virtual-signal/signal-yellow]',
	sig_red = '[img=virtual-signal/signal-red]',
	sig_any = '[img=virtual-signal/signal-anything]',
	radar = '[img=item/radar]',
	locomotive = '[img=item/locomotive]',
	sm_gun = '[img=item/submachine-gun]',
	shotgun= '[img=item/shotgun]',	
	lab= '[img=item/lab]',	
	silo =  '[img=item/rocket-silo]',
	reactor =  '[img=item/nuclear-reactor]',
	nest =  '[img=entity/biter-spawner]',
	beacon =  '[img=entity/beacon]',
	assembler =  '[img=item/assembling-machine-2]',	
	speaker = '[img=item/programmable-speaker]',
	coin = '[img=item/coin]',
	tank = '[img=item/tank]',
	pick = '[img=technology/steel-axe]',
	player = '[img=entity/character]',
	compilatron = '[img=entity/compilatron]',
	spitter = '[img=entity/big-spitter]',
	furnace= '[img=item/steel-furnace]',	
	efurnace= '[img=item/electric-furnace]',
	engine2= '[img=item/electric-engine-unit]',
	repair= '[img=item/repair-pack]',
	clock= '[img=utility/time_editor_icon]',
	close='[img=utility/close]',
	rocketpart= '[img=item/rocket-part]',
	station= '[img=item/train-stop]',	
	arrow_right = '[img=utility/hint_arrow_right]',
	steam_e = '[img=item/steam-engine]',	
	accumulator= '[img=item/accumulator]',	
	satellite= '[img=item/satellite]',	
	nuke = '[img=technology/atomic-bomb]',
	market= '[img=entity/market]',
    exoskeleton= '[img=item/exoskeleton-equipment]',
	check_green= '[img=utility/check_mark_green]',
	check_red= '[img=utility/too_far]',
	go_arrow= '[img=utility/go_to_arrow]',
	warning = '[img=utility/warning_icon]',
	warning_w = '[img=utility/warning_white]',
	gps_map= '[img=utility/gps_map_icon]',	
	}

