data:extend({{
		type = "recipe",
		name = "w93-scattergun-turret",
		category = "crafting",
		enabled = false,
		energy_required = 20,
		ingredients = {{type="item", name="stone-brick", amount=10},
				{type="item", name="steel-plate", amount=5},
				{type="item", name="copper-plate", amount=15},
				{type="item", name="iron-gear-wheel", amount=10}},
    		results = {{type="item", name="w93-scattergun-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/scattergun-turret.png",
    		icon_size = 32,
	},
	{
		type = "recipe",
		name = "w93-hmg-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-hmg", amount=1}},
    		results = {{type="item", name="w93-hmg-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/hmg-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-hmg-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-hmg", amount=1}},
    		results = {{type="item", name="w93-hmg-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/hmg-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-gatling-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-gatling", amount=1}},
    		results = {{type="item", name="w93-gatling-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/gatling-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-gatling-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-gatling", amount=1}},
    		results = {{type="item", name="w93-gatling-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/gatling-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-lcannon-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-lcannon", amount=1}},
    		results = {{type="item", name="w93-lcannon-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/lcannon-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-lcannon-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-lcannon", amount=1}},
    		results = {{type="item", name="w93-lcannon-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/lcannon-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-dcannon-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-dcannon", amount=1}},
    		results = {{type="item", name="w93-dcannon-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/dcannon-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-dcannon-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-dcannon", amount=1}},
    		results = {{type="item", name="w93-dcannon-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/dcannon-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-hcannon-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-hcannon", amount=1}},
    		results = {{type="item", name="w93-hcannon-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/hcannon-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-hcannon-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-hcannon", amount=1}},
    		results = {{type="item", name="w93-hcannon-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/hcannon-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-rocket-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-rocket", amount=1}},
    		results = {{type="item", name="w93-rocket-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/rocket-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-rocket-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-rocket", amount=1}},
    		results = {{type="item", name="w93-rocket-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/rocket-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-plaser-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-plaser", amount=1}},
    		results = {{type="item", name="w93-plaser-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/plaser-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-plaser-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-plaser", amount=1}},
    		results = {{type="item", name="w93-plaser-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/plaser-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-tlaser-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-tlaser", amount=1}},
    		results = {{type="item", name="w93-tlaser-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/tlaser-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-tlaser-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-tlaser", amount=1}},
    		results = {{type="item", name="w93-tlaser-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/tlaser-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-beam-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret-base", amount=1},
				{type="item", name="w93-modular-gun-beam", amount=1}},
    		results = {{type="item", name="w93-beam-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/beam-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-beam-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-beam", amount=1}},
    		results = {{type="item", name="w93-beam-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/beam-turret2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-radar-turret",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-radar", amount=1}},
    		results = {{type="item", name="w93-radar-turret", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/radar-turret.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-radar-turret2",
		category = "crafting",
		enabled = false,
		energy_required = 5,
		ingredients = {{type="item", name="w93-modular-turret2-base", amount=1},
				{type="item", name="w93-modular-gun-radar2", amount=1}},
    		results = {{type="item", name="w93-radar-turret2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/radar-turret2.png",
    		icon_size = 64,
	},

	{
		type = "recipe",
		name = "w93-modular-turret-base",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="concrete", amount=20},
				{type="item", name="steel-plate", amount=8},
				{type="item", name="engine-unit", amount=1}},
    		results = {{type="item", name="w93-modular-turret-base", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-turret-base.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-turret2-base",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="low-density-structure", amount=2},
				{type="item", name="plastic-bar", amount=20},
				{type="item", name="electric-engine-unit", amount=1},
				{type="item", name="advanced-circuit", amount=4}},
    		results = {{type="item", name="w93-modular-turret2-base", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-turret2-base.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-hmg",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="iron-plate", amount=6},
				{type="item", name="electronic-circuit", amount=3},
				{type="item", name="iron-gear-wheel", amount=3}},
    		results = {{type="item", name="w93-modular-gun-hmg", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-hmg.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-gatling",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="iron-stick", amount=12},
				{type="item", name="copper-plate", amount=8},
				{type="item", name="advanced-circuit", amount=2},
				{type="item", name="electric-engine-unit", amount=1}},
    		results = {{type="item", name="w93-modular-gun-gatling", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-gatling.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-lcannon",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="copper-plate", amount=5},
				{type="item", name="steel-plate", amount=4},
				{type="item", name="electronic-circuit", amount=2},
				{type="item", name="iron-gear-wheel", amount=4}},
    		results = {{type="item", name="w93-modular-gun-lcannon", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-lcannon.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-dcannon",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="w93-modular-gun-lcannon", amount=2},
				{type="item", name="speed-module", amount=1}},
    		results = {{type="item", name="w93-modular-gun-dcannon", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-dcannon.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-hcannon",
		category = "crafting-with-fluid",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="low-density-structure", amount=2},
				{type="item", name="steel-plate", amount=5},
				{type="item", name="advanced-circuit", amount=2},
				{type="fluid", name="lubricant", amount=50}
},
    		results = {{type="item", name="w93-modular-gun-hcannon", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-hcannon.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-rocket",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="steel-plate", amount=5},
				{type="item", name="advanced-circuit", amount=2},
				{type="item", name="rocket-launcher", amount=2}},
    		results = {{type="item", name="w93-modular-gun-rocket", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-rocket.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-plaser",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="plastic-bar", amount=10},
				{type="item", name="battery", amount=10},
				{type="item", name="electronic-circuit", amount=5},
				{type="item", name="speed-module", amount=1}},
    		results = {{type="item", name="w93-modular-gun-plaser", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-plaser.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-tlaser",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="plastic-bar", amount=10},
				{type="item", name="battery", amount=10},
				{type="item", name="efficiency-module-2", amount=1}},
    		results = {{type="item", name="w93-modular-gun-tlaser", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-tlaser.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-beam",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="plastic-bar", amount=10},
				{type="item", name="battery", amount=10},
				{type="item", name="processing-unit", amount=2},
				{type="item", name="uranium-fuel-cell", amount=2}},
    		results = {{type="item", name="w93-modular-gun-beam", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-beam.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-radar",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="copper-plate", amount=10},
				{type="item", name="efficiency-module-2", amount=1},
				{type="item", name="iron-gear-wheel", amount=10}},
		results = {{type="item", name="w93-modular-gun-radar", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-radar.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-modular-gun-radar2",
		category = "crafting",
		enabled = false,
		energy_required = 10,
		ingredients = {{type="item", name="copper-plate", amount=15},
				{type="item", name="iron-stick", amount=20},
				{type="item", name="speed-module-2", amount=1},
				{type="item", name="iron-gear-wheel", amount=5}},
		results = {{type="item", name="w93-modular-gun-radar2", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/modular-gun-radar2.png",
    		icon_size = 64,
	},
	{
		type = "recipe",
		name = "w93-hardened-inserter",
		category = "crafting",
		enabled = false,
		energy_required = 0.5,
		ingredients = {{type="item", name="long-handed-inserter", amount=1},
				{type="item", name="steel-plate", amount=1},
				{type="item", name="stone-brick", amount=1}},
    		results = {{type="item", name="w93-hardened-inserter", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/hardened-inserter.png",
    		icon_size = 64,
		icon_mipmaps = 4,
	}
})

for k, v in pairs(data.raw.module) do
	if v.name:find("productivity%-module") and v.limitation then
		table.insert(v.limitation, "w93-modular-turret-base")
		table.insert(v.limitation, "w93-modular-turret2-base")
		table.insert(v.limitation, "w93-modular-gun-hmg")
		table.insert(v.limitation, "w93-modular-gun-gatling")
		table.insert(v.limitation, "w93-modular-gun-lcannon")
		table.insert(v.limitation, "w93-modular-gun-dcannon")
		table.insert(v.limitation, "w93-modular-gun-hcannon")
		table.insert(v.limitation, "w93-modular-gun-rocket")
		table.insert(v.limitation, "w93-modular-gun-plaser")
		table.insert(v.limitation, "w93-modular-gun-tlaser")
		table.insert(v.limitation, "w93-modular-gun-beam")
		table.insert(v.limitation, "w93-modular-gun-radar")
		table.insert(v.limitation, "w93-modular-gun-radar2")
	end
end