data:extend({
	{
		type = "recipe",
		name = "w93-slowdown-magazine",
		category = "crafting",
		enabled = false,
		energy_required = 8,
		ingredients = {{type="item", name="piercing-rounds-magazine", amount=9},
				{type="item", name="slowdown-capsule", amount=1}},
		results = {{type="item", name="w93-slowdown-magazine", amount=9}},
		icon = "__scattergun_turret__/graphics/icons/slowdown-magazine.png",
    		icon_size = 64,
		icon_mipmaps = 4,
	},
	{
		type = "recipe",
		name = "w93-uranium-shotgun-shell",
		category = "crafting",
		enabled = false,
		energy_required = 12,
		ingredients = {{type="item", name="piercing-shotgun-shell", amount=1},
				{type="item", name="uranium-238", amount=1}},
		results = {{type="item", name="w93-uranium-shotgun-shell", amount=1}},
		icon = "__scattergun_turret__/graphics/icons/uranium-shotgun-shell.png",
    		icon_size = 64,
		icon_mipmaps = 4,
	},
	{
		type = "recipe",
		name = "w93-fragmentation-cannon-shell",
		category = "crafting",
		enabled = false,
		energy_required = 8,
		ingredients = {{type="item", name="iron-stick", amount=8},
				{type="item", name="steel-plate", amount=2},
				{type="item", name="explosives", amount=1}},
		results = {{type="item", name="w93-fragmentation-cannon-shell", amount=2}},
		icon = "__scattergun_turret__/graphics/icons/fragmentation-cannon-shell.png",
    		icon_size = 64,
		icon_mipmaps = 4,
	},
	{
		type = "recipe",
		name = "w93-turret-slowdown-rocket",
		category = "crafting",
		enabled = false,
		energy_required = 32,
		ingredients = {{type="item", name="rocket", amount=8},
				{type="item", name="slowdown-capsule", amount=1}},
		results = {{type="item", name="w93-turret-slowdown-rocket", amount=8}},
		icon = "__scattergun_turret__/graphics/icons/slowdown-turret-rocket.png",
    		icon_size = 64,
		icon_mipmaps = 4,
	}
})