return
{
  entities =
  {
    {"stone-wall", {x = -5, y = -6.5}, {}},
    {"stone-wall", {x = -6, y = -6.5}, {}},
    {"tree-05", {x = -3, y = -6.5}, {}},
    {"stone-wall", {x = -4, y = -6.5}, {}},
    {"tree-05", {x = -1, y = -6.5}, {}},
    {"stone-wall", {x = 1, y = -6.5}, {}},
    {"tree-05", {x = 2, y = -6.5}, {}},
    {"tree-05", {x = 5, y = -6.5}, {}},
    {"wall-remnants", {x = 4, y = -6.5}, {dir = "south", }},
    {"tree-05", {x = -6, y = -5.5}, {}},
    {"medium-electric-pole", {x = -4, y = -4.5}, {}},
    {"fast-transport-belt", {x = -2, y = -4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -1, y = -4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 0, y = -4.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 1, y = -4.5}, {dir = "south", }},
    {"tree-05", {x = 5, y = -4.5}, {}},
    {"tree-05", {x = -6, y = -3.5}, {}},
    {"bulk-inserter-remnants", {x = -4, y = -2.5}, {dir = "east", }},
    {"requester-chest-remnants", {x = -3, y = -2.5}, {}},
    {"buffer-chest-remnants", {x = -2, y = -2.5}, {}},
    {"buffer-chest-remnants", {x = -1, y = -2.5}, {}},
    {"bulk-inserter-remnants", {x = -2, y = -3.5}, {dir = "east", }},
    {"bulk-inserter-remnants", {x = -1, y = -3.5}, {dir = "east", }},
    {"buffer-chest-remnants", {x = 0, y = -2.5}, {}},
    {"buffer-chest-remnants", {x = 1, y = -2.5}, {}},
    {"bulk-inserter-remnants", {x = 0, y = -3.5}, {dir = "east", }},
    {"bulk-inserter-remnants", {x = 1, y = -3.5}, {dir = "east", }},
    {"passive-provider-chest-remnants", {x = 2, y = -2.5}, {}},
    {"bulk-inserter-remnants", {x = 3, y = -2.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 4, y = -2.5}, {dir = "west", }},
    {"stone-wall", {x = 6, y = -2.5}, {}},
    {"stone-wall", {x = -6, y = -1.5}, {}},
    {"stone-wall", {x = -6, y = -0.5}, {}},
    {"bulk-inserter-remnants", {x = -4, y = -1.5}, {dir = "east", }},
    {"bulk-inserter-remnants", {x = -4, y = -0.5}, {dir = "east", }},
    {"requester-chest-remnants", {x = -3, y = -1.5}, {}},
    {"requester-chest-remnants", {x = -3, y = -0.5}, {}},
    {"storage-chest-remnants", {x = -2, y = -1.5}, {}},
    {"storage-chest-remnants", {x = -1, y = -1.5}, {}},
    {"storage-chest-remnants", {x = -2, y = -0.5}, {}},
    {"storage-chest-remnants", {x = -1, y = -0.5}, {}},
    {"storage-chest-remnants", {x = 0, y = -1.5}, {}},
    {"storage-chest-remnants", {x = 1, y = -1.5}, {}},
    {"storage-chest-remnants", {x = 0, y = -0.5}, {}},
    {"storage-chest-remnants", {x = 1, y = -0.5}, {}},
    {"passive-provider-chest-remnants", {x = 2, y = -1.5}, {}},
    {"passive-provider-chest-remnants", {x = 2, y = -0.5}, {}},
    {"bulk-inserter-remnants", {x = 3, y = -1.5}, {dir = "east", }},
    {"bulk-inserter-remnants", {x = 3, y = -0.5}, {dir = "east", }},
    {"tree-05", {x = 5, y = -1.5}, {}},
    {"fast-transport-belt", {x = 4, y = -1.5}, {dir = "west", }},
    {"fast-transport-belt", {x = 4, y = -0.5}, {dir = "west", }},
    {"stone-wall", {x = -6, y = 0.5}, {}},
    {"wall-remnants", {x = -6, y = 1.5}, {}},
    {"bulk-inserter-remnants", {x = -4, y = 0.5}, {dir = "east", }},
    {"requester-chest-remnants", {x = -3, y = 0.5}, {}},
    {"active-provider-chest-remnants", {x = -2, y = 0.5}, {}},
    {"active-provider-chest-remnants", {x = -1, y = 0.5}, {}},
    {"bulk-inserter-remnants", {x = -2, y = 1.5}, {dir = "east", }},
    {"bulk-inserter-remnants", {x = -1, y = 1.5}, {dir = "east", }},
    {"active-provider-chest", {x = 1, y = 0.5}, {}},
    {"bulk-inserter", {x = 1, y = 1.5}, {dir = "south", }},
    {"active-provider-chest-remnants", {x = 0, y = 0.5}, {}},
    {"bulk-inserter-remnants", {x = 0, y = 1.5}, {dir = "east", }},
    {"passive-provider-chest-remnants", {x = 2, y = 0.5}, {}},
    {"bulk-inserter-remnants", {x = 3, y = 0.5}, {dir = "east", }},
    {"tree-05", {x = 5, y = 1.5}, {}},
    {"fast-transport-belt", {x = 4, y = 0.5}, {dir = "west", }},
    {"wall-remnants", {x = 6, y = 0.5}, {dir = "south", }},
    {"tree-05", {x = -6, y = 2.5}, {}},
    {"gun-turret", {x = -2.5, y = 4}, {force = "enemy", items = {["piercing-rounds-magazine"] = 5}, }},
    {"fast-transport-belt", {x = -1, y = 2.5}, {}},
    {"fast-transport-belt", {x = -2, y = 2.5}, {}},
    {"fast-transport-belt", {x = 1, y = 2.5}, {}},
    {"fast-transport-belt", {x = 0, y = 2.5}, {}},
    {"land-mine", {x = 4.36, y = 3.17}, {force = "enemy", }},
    {"gate-remnants", {x = 6, y = 3.5}, {}},
    {"tree-05", {x = -6, y = 4.5}, {}},
    {"tree-05", {x = -2, y = 5.5}, {}},
    {"tree-05", {x = 1, y = 5.5}, {}},
    {"tree-05", {x = 4, y = 5.5}, {}},
    {"gate-remnants", {x = 6, y = 4.5}, {}},
    {"stone-wall", {x = 6, y = 5.5}, {}},
    {"stone-wall", {x = -6, y = 6.5}, {}},
    {"stone-wall", {x = -5, y = 6.5}, {}},
    {"wall-remnants", {x = -4, y = 6.5}, {dir = "south", }},
    {"stone-wall", {x = -3, y = 6.5}, {}},
    {"stone-wall", {x = 0, y = 6.5}, {}},
    {"stone-wall", {x = 3, y = 6.5}, {}},
    {"stone-wall", {x = 6, y = 6.5}, {}},
  },
}
