return
{
  entities =
  {
    {"stone-wall", {x = -6, y = -6}, {}},
    {"stone-wall", {x = -4, y = -6}, {}},
    {"stone-wall", {x = -5, y = -6}, {}},
    {"tree-05", {x = -3, y = -6}, {}},
    {"tree-05", {x = -1, y = -6}, {}},
    {"tree-05", {x = 2, y = -6}, {}},
    {"stone-wall", {x = 1, y = -6}, {}},
    {"wall-remnants", {x = 4, y = -6}, {dir = "south", }},
    {"tree-05", {x = 5, y = -6}, {}},
    {"tree-05", {x = -6, y = -5}, {}},
    {"medium-electric-pole", {x = -4, y = -4}, {}},
    {"tree-05", {x = 5, y = -4}, {}},
    {"tree-05", {x = -6, y = -3}, {}},
    {"steel-chest", {x = -3, y = -2}, {dead = 0.5, items = {["droid-smg"] = {type = "random", min = 10, max = 20}}, }},
    {"steel-chest", {x = 0, y = -3}, {dead = 0.5, items = {["droid-rifle"] = {type = "random", min = 20, max = 40}}, }},
    {"gun-turret", {x = 2.5, y = -2.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 5}, }},
    {"stone-wall", {x = 6, y = -2}, {}},
    {"stone-wall", {x = -6, y = 0}, {}},
    {"stone-wall", {x = -6, y = -1}, {}},
    {"steel-chest", {x = -1, y = 0}, {dead = 0.5, items = {["droid-flame"] = {type = "random", min = 5, max = 15}}, }},
    {"tree-05", {x = 5, y = -1}, {}},
    {"wall-remnants", {x = -6, y = 2}, {}},
    {"stone-wall", {x = -6, y = 1}, {}},
    {"medium-electric-pole", {x = 1, y = 2}, {}},
    {"steel-chest", {x = 3, y = 2}, {dead = 0.5, items = {["droid-rocket"] = {type = "random", min = 5, max = 15}}, }},
    {"tree-05", {x = 5, y = 2}, {}},
    {"wall-remnants", {x = 6, y = 1}, {dir = "south", }},
    {"tree-05", {x = -6, y = 3}, {}},
    {"steel-chest", {x = -3, y = 3}, {dead = 0.5, items = {terminator = {type = "random", min = 3, max = 10}}, }},
    {"gun-turret", {x = -2.5, y = 4.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 5}, }},
    {"land-mine", {x = 4.36, y = 3.67}, {force = "enemy", }},
    {"gate-remnants", {x = 6, y = 4}, {}},
    {"tree-05", {x = -6, y = 5}, {}},
    {"tree-05", {x = -2, y = 6}, {}},
    {"tree-05", {x = 1, y = 6}, {}},
    {"tree-05", {x = 4, y = 6}, {}},
    {"stone-wall", {x = 6, y = 6}, {}},
    {"gate-remnants", {x = 6, y = 5}, {}},
    {"stone-wall", {x = -6, y = 7}, {}},
    {"wall-remnants", {x = -4, y = 7}, {dir = "south", }},
    {"stone-wall", {x = -5, y = 7}, {}},
    {"stone-wall", {x = -3, y = 7}, {}},
    {"stone-wall", {x = 0, y = 7}, {}},
    {"stone-wall", {x = 3, y = 7}, {}},
    {"stone-wall", {x = 6, y = 7}, {}},
  },
}
