return
{
  entities =
  {
    {"big-electric-pole-remnants", {x = -7, y = -13.5}, {dir = "east", }},
    {"stone-wall", {x = -8.5, y = -5}, {}},
    {"stone-wall", {x = -9.5, y = -5}, {}},
    {"stone-wall", {x = -6.5, y = -5}, {}},
    {"stone-wall", {x = -7.5, y = -5}, {}},
    {"wall-remnants", {x = -4.5, y = -5}, {dir = "east", }},
    {"stone-wall", {x = -5.5, y = -5}, {}},
    {"stone-wall", {x = -2.5, y = -5}, {}},
    {"stone-wall", {x = -3.5, y = -5}, {}},
    {"wall-remnants", {x = -0.5, y = -5}, {dir = "east", }},
    {"stone-wall", {x = -1.5, y = -5}, {}},
    {"stone-wall", {x = 1.5, y = -5}, {}},
    {"wall-remnants", {x = 0.5, y = -5}, {dir = "east", }},
    {"wall-remnants", {x = 3.5, y = -5}, {dir = "east", }},
    {"stone-wall", {x = 2.5, y = -5}, {}},
    {"stone-wall", {x = 5.5, y = -5}, {}},
    {"stone-wall", {x = 4.5, y = -5}, {}},
    {"stone-wall", {x = 7.5, y = -5}, {}},
    {"stone-wall", {x = 6.5, y = -5}, {}},
    {"wall-remnants", {x = 8.5, y = -5}, {dir = "east", }},
    {"gun-turret", {x = -8, y = -3.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 5}, }},
    {"stone-wall", {x = -9.5, y = -3}, {}},
    {"stone-wall", {x = -9.5, y = -4}, {}},
    {"laser-turret-remnants", {x = -3, y = -3.5}, {dir = "east", }},
    {"gun-turret", {x = 7, y = -3.5}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"wall-remnants", {x = 8.5, y = -3}, {dir = "east", }},
    {"stone-wall", {x = 8.5, y = -4}, {}},
    {"wall-remnants", {x = -9.5, y = -1}, {dir = "east", }},
    {"stone-wall", {x = -9.5, y = -2}, {}},
    {"big-electric-pole-remnants", {x = -5, y = -1.5}, {dir = "east", }},
    {"steel-chest", {x = -2.5, y = -1}, {dead = 0.5, items = {["personal-laser-defense-equipment"] = 1}, }},
    {"steel-chest", {x = -3.5, y = -1}, {dead = 0.9, items = {["fission-reactor-equipment"] = 1}, }},
    {"steel-chest", {x = -2.5, y = -2}, {items = {["solar-panel-equipment"] = {type = "random", min = 2, max = 8}}, }},
    {"steel-chest", {x = -3.5, y = -2}, {dead = 0.75, items = {["power-armor"] = 1}, }},
    {"steel-chest", {x = -0.5, y = -2}, {dead = 0.67, items = {["exoskeleton-equipment"] = {type = "random", min = 1, max = 2}}, }},
    {"steel-chest", {x = -0.5, y = -1}, {dead = 0.5, items = {["energy-shield-equipment"] = {type = "random", min = 1, max = 3}}, }},
    {"steel-chest", {x = -1.5, y = -1}, {items = {["battery-equipment"] = {type = "random", min = 1, max = 4}}, }},
    {"steel-chest", {x = -1.5, y = -2}, {items = {["personal-roboport-equipment"] = 1}, }},
    {"radar-remnants", {x = 1.5, y = -1}, {dir = "east", }},
    {"radar", {x = 4.5, y = -1}, {}},
    {"medium-electric-pole", {x = 6.5, y = -2}, {}},
    {"stone-wall", {x = 8.5, y = -2}, {}},
    {"stone-wall", {x = 8.5, y = -1}, {}},
    {"stone-wall", {x = -9.5, y = 1}, {}},
    {"stone-wall", {x = -9.5, y = 0}, {}},
    {"medium-electric-pole", {x = -4.5, y = 1}, {}},
    {"steel-chest", {x = -2.5, y = 0}, {dead = 0.67, items = {["battery-mk2-equipment"] = 1}, }},
    {"steel-chest", {x = -3.5, y = 0}, {dead = 0.8, items = {["personal-roboport-mk2-equipment"] = 1}, }},
    {"steel-chest", {x = -0.5, y = 0}, {dead = 0.5, items = {["discharge-defense-equipment"] = 1, ["discharge-defense-remote"] = 1}, }},
    {"steel-chest", {x = -1.5, y = 0}, {dead = 0.7, items = {["energy-shield-mk2-equipment"] = 1}, }},
    {"medium-electric-pole-remnants", {x = 4.5, y = 1}, {}},
    {"stone-wall", {x = 8.5, y = 0}, {}},
    {"stone-wall", {x = 8.5, y = 1}, {}},
    {"gun-turret", {x = -8, y = 2.5}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"stone-wall", {x = -9.5, y = 3}, {}},
    {"stone-wall", {x = -9.5, y = 2}, {}},
    {"laser-turret-remnants", {x = -3, y = 2.5}, {dir = "east", }},
    {"laser-turret-remnants", {x = 2, y = 2.5}, {dir = "east", }},
    {"gun-turret", {x = 7, y = 2.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 5}, }},
    {"wall-remnants", {x = 8.5, y = 2}, {dir = "east", }},
    {"stone-wall", {x = 8.5, y = 3}, {}},
    {"stone-wall", {x = -8.5, y = 4}, {}},
    {"stone-wall", {x = -9.5, y = 4}, {}},
    {"stone-wall", {x = -6.5, y = 4}, {}},
    {"stone-wall", {x = -7.5, y = 4}, {}},
    {"wall-remnants", {x = -4.5, y = 4}, {dir = "east", }},
    {"stone-wall", {x = -5.5, y = 4}, {}},
    {"stone-wall", {x = -2.5, y = 4}, {}},
    {"stone-wall", {x = -3.5, y = 4}, {}},
    {"gate", {x = -0.5, y = 4}, {dir = "east", }},
    {"gate", {x = -1.5, y = 4}, {dir = "east", }},
    {"gate", {x = 1.5, y = 4}, {dir = "east", }},
    {"gate-remnants", {x = 0.5, y = 4}, {dir = "east", }},
    {"stone-wall", {x = 3.5, y = 4}, {}},
    {"stone-wall", {x = 2.5, y = 4}, {}},
    {"wall-remnants", {x = 5.5, y = 4}, {dir = "east", }},
    {"stone-wall", {x = 4.5, y = 4}, {}},
    {"stone-wall", {x = 7.5, y = 4}, {}},
    {"stone-wall", {x = 6.5, y = 4}, {}},
    {"stone-wall", {x = 8.5, y = 4}, {}},
    {"big-electric-pole-remnants", {x = 12, y = 13.5}, {dir = "east", }},
  },
}
