return
{
  entities =
  {
    {"stone-wall", {x = -4, y = -3.5}, {}},
    {"wall-remnants", {x = -5, y = -2.5}, {}},
    {"stone-wall", {x = -5, y = -3.5}, {}},
    {"wall-remnants", {x = -2, y = -3.5}, {dir = "south", }},
    {"wall-remnants", {x = -3, y = -3.5}, {dir = "south", }},
    {"stone-wall", {x = 0, y = -3.5}, {}},
    {"stone-wall", {x = -1, y = -3.5}, {}},
    {"stone-wall", {x = 2, y = -2.5}, {}},
    {"stone-wall", {x = 2, y = -3.5}, {}},
    {"stone-wall", {x = 1, y = -3.5}, {}},
    {"stone-wall", {x = 4, y = -2.5}, {}},
    {"stone-wall", {x = 3, y = -2.5}, {}},
    {"stone-wall", {x = 5, y = -2.5}, {}},
    {"stone-wall", {x = -5, y = -0.5}, {}},
    {"stone-wall", {x = -5, y = -1.5}, {}},
    {"gun-turret", {x = -2.5, y = 0}, {force = "enemy", items = {["firearm-magazine"] = 5}, }},
    {"radar", {x = 1, y = -0.5}, {}},
    {"medium-electric-pole", {x = -1, y = -0.5}, {}},
    {"steel-chest", {x = 4, y = -0.5}, {dead = 0.5, items = {["military-science-pack"] = {type = "random", min = 10, max = 30}}, }},
    {"gate", {x = 5, y = -0.5}, {}},
    {"gate", {x = 5, y = -1.5}, {}},
    {"wall-remnants", {x = -5, y = 1.5}, {dir = "south", }},
    {"wall-remnants", {x = -5, y = 0.5}, {dir = "south", }},
    {"steel-chest", {x = -1, y = 0.5}, {dead = 0.8, items = {["modular-armor"] = 1}, }},
    {"stone-wall", {x = 4, y = 1.5}, {}},
    {"stone-wall", {x = 5, y = 1.5}, {}},
    {"stone-wall", {x = 5, y = 0.5}, {}},
    {"wall-remnants", {x = -4, y = 2.5}, {dir = "south", }},
    {"wall-remnants", {x = -5, y = 2.5}, {dir = "south", }},
    {"wall-remnants", {x = -2, y = 2.5}, {dir = "south", }},
    {"stone-wall", {x = -3, y = 2.5}, {}},
    {"stone-wall", {x = 0, y = 2.5}, {}},
    {"wall-remnants", {x = -1, y = 2.5}, {dir = "south", }},
    {"wall-remnants", {x = 2, y = 2.5}, {dir = "south", }},
    {"stone-wall", {x = 1, y = 2.5}, {}},
    {"wall-remnants", {x = 4, y = 2.5}, {}},
    {"stone-wall", {x = 3, y = 2.5}, {}},
    {"medium-electric-pole", {x = 5, y = 2.5}, {}},
  },
}
