return
{
  entities =
  {
    {"stone-wall", {x = -5, y = -3}, {}},
    {"wall-remnants", {x = -5, y = -2}, {}},
    {"wall-remnants", {x = -3, y = -3}, {dir = "south", }},
    {"stone-wall", {x = -4, y = -3}, {}},
    {"stone-wall", {x = -1, y = -3}, {}},
    {"wall-remnants", {x = -2, y = -3}, {dir = "south", }},
    {"stone-wall", {x = 1, y = -3}, {}},
    {"stone-wall", {x = 0, y = -3}, {}},
    {"stone-wall", {x = 3, y = -2}, {}},
    {"stone-wall", {x = 2, y = -3}, {}},
    {"stone-wall", {x = 2, y = -2}, {}},
    {"stone-wall", {x = 5, y = -2}, {}},
    {"stone-wall", {x = 4, y = -2}, {}},
    {"stone-wall", {x = -5, y = -1}, {}},
    {"stone-wall", {x = -5, y = 0}, {}},
    {"gun-turret", {x = -2.5, y = 0.5}, {force = "enemy", items = {["firearm-magazine"] = 5}, }},
    {"medium-electric-pole", {x = -1, y = 0}, {}},
    {"radar", {x = 1, y = 0}, {}},
    {"gate", {x = 5, y = -1}, {}},
    {"gate", {x = 5, y = 0}, {}},
    {"steel-chest", {x = 4, y = 0}, {dead = 0.5, items = {["military-science-pack"] = {type = "random", min = 10, max = 30}}, }},
    {"wall-remnants", {x = -5, y = 1}, {dir = "south", }},
    {"wall-remnants", {x = -5, y = 2}, {dir = "south", }},
    {"steel-chest", {x = -1, y = 1}, {items = {["battery-equipment"] = 1}, }},
    {"stone-wall", {x = 5, y = 1}, {}},
    {"stone-wall", {x = 5, y = 2}, {}},
    {"stone-wall", {x = 4, y = 2}, {}},
    {"wall-remnants", {x = -5, y = 3}, {dir = "south", }},
    {"stone-wall", {x = -3, y = 3}, {}},
    {"wall-remnants", {x = -4, y = 3}, {dir = "south", }},
    {"wall-remnants", {x = -1, y = 3}, {dir = "south", }},
    {"wall-remnants", {x = -2, y = 3}, {dir = "south", }},
    {"stone-wall", {x = 1, y = 3}, {}},
    {"stone-wall", {x = 0, y = 3}, {}},
    {"stone-wall", {x = 3, y = 3}, {}},
    {"wall-remnants", {x = 2, y = 3}, {dir = "south", }},
    {"medium-electric-pole", {x = 5, y = 3}, {}},
    {"wall-remnants", {x = 4, y = 3}, {}},
  },
}
