return
{
  entities =
  {
    {"stone-wall", {x = -14.5, y = -14.5}, {}},
    {"stone-wall", {x = -14.5, y = -13.5}, {}},
    {"stone-wall", {x = -13.5, y = -14.5}, {}},
    {"stone-wall", {x = -10.5, y = -14.5}, {}},
    {"stone-wall", {x = -11.5, y = -14.5}, {}},
    {"stone-wall", {x = -8.5, y = -14.5}, {}},
    {"stone-wall", {x = -7.5, y = -14.5}, {}},
    {"stone-wall", {x = -4.5, y = -14.5}, {}},
    {"stone-wall", {x = -5.5, y = -14.5}, {}},
    {"stone-wall", {x = -2.5, y = -14.5}, {}},
    {"laser-turret", {x = -1, y = -13}, {dir = "west", force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -14.5}, {}},
    {"stone-wall", {x = 1.5, y = -14.5}, {}},
    {"stone-wall", {x = 0.5, y = -14.5}, {}},
    {"stone-wall", {x = 2.5, y = -14.5}, {}},
    {"storage-tank", {x = 6.5, y = -12.5}, {dir = "east", }},
    {"stone-wall", {x = 5.5, y = -14.5}, {}},
    {"stone-wall", {x = 4.5, y = -14.5}, {}},
    {"stone-wall", {x = 6.5, y = -14.5}, {}},
    {"storage-tank", {x = 9.5, y = -12.5}, {}},
    {"stone-wall", {x = 9.5, y = -14.5}, {}},
    {"stone-wall", {x = 8.5, y = -14.5}, {}},
    {"stone-wall", {x = 13.5, y = -14.5}, {}},
    {"stone-wall", {x = 14.5, y = -14.5}, {}},
    {"stone-wall", {x = 14.5, y = -13.5}, {}},
    {"stone-wall", {x = -14.5, y = -12.5}, {}},
    {"stone-wall", {x = -14.5, y = -11.5}, {}},
    {"steam-engine-remnants", {x = -2.5, y = -11.5}, {dir = "west", }},
    {"steam-engine", {x = 2.5, y = -11.5}, {dir = "east", }},
    {"stone-wall", {x = 14.5, y = -11.5}, {}},
    {"stone-wall", {x = -14.5, y = -10.5}, {}},
    {"tree-04", {x = -7.5, y = -10.5}, {}},
    {"tree-04", {x = -1.5, y = -10.5}, {}},
    {"medium-electric-pole", {x = 1.5, y = -9.5}, {}},
    {"laser-turret", {x = 5, y = -9}, {dir = "west", force = "enemy", }},
    {"big-remnants", {x = 8.5, y = -9.5}, {dir = "east", }},
    {"pipe", {x = 10.5, y = -10.5}, {}},
    {"pipe", {x = 10.5, y = -9.5}, {}},
    {"angels-electric-boiler-3", {x = 12.5, y = -9.5}, {dir = "east", fluids = {water = 200}, recipe = "angels-steam-water", }},
    {"stone-wall", {x = 14.5, y = -10.5}, {}},
    {"stone-wall", {x = 14.5, y = -9.5}, {}},
    {"stone-wall", {x = -14.5, y = -8.5}, {}},
    {"stone-wall", {x = -14.5, y = -7.5}, {}},
    {"tree-04", {x = 1.5, y = -8.5}, {}},
    {"pipe", {x = 12.5, y = -7.5}, {fluids = {water = 100}, }},
    {"stone-wall", {x = 14.5, y = -7.5}, {}},
    {"stone-wall", {x = -14.5, y = -5.5}, {}},
    {"tree-04", {x = -5.5, y = -5.5}, {}},
    {"steel-chest", {x = 5.5, y = -6.5}, {items = {["laser-turret"] = {type = "random", min = 3, max = 7}, rpg_big_healing_potion = {type = "random", min = 3, max = 7}, rpg_small_xp_potion = {type = "random", min = 2, max = 5}, rpg_speed_potion = {type = "random", min = 3, max = 7}}, }},
    {"tree-04", {x = 8.5, y = -6.5}, {}},
    {"medium-electric-pole", {x = 10.5, y = -5.5}, {}},
    {"tree-04-stump", {x = 11.5, y = -5.5}, {}},
    {"pipe", {x = 12.5, y = -6.5}, {fluids = {water = 100}, }},
    {"pipe", {x = 12.5, y = -5.5}, {fluids = {water = 100}, }},
    {"stone-wall", {x = 14.5, y = -6.5}, {}},
    {"stone-wall", {x = 14.5, y = -5.5}, {}},
    {"stone-wall", {x = -14.5, y = -4.5}, {}},
    {"stone-wall", {x = -14.5, y = -3.5}, {}},
    {"tree-04", {x = -12.5, y = -3.5}, {}},
    {"stone-wall", {x = 14.5, y = -3.5}, {}},
    {"stone-wall", {x = -14.5, y = -1.5}, {}},
    {"tree-04", {x = 8.5, y = -1.5}, {}},
    {"stone-wall", {x = 14.5, y = -2.5}, {}},
    {"stone-wall", {x = 14.5, y = -1.5}, {}},
    {"stone-wall", {x = -14.5, y = -0.5}, {}},
    {"stone-wall", {x = -14.5, y = 0.5}, {}},
    {"tree-04", {x = -11.5, y = -0.5}, {}},
    {"tree-04", {x = 10.5, y = 0.5}, {}},
    {"stone-wall", {x = 14.5, y = -0.5}, {}},
    {"stone-wall", {x = -14.5, y = 2.5}, {}},
    {"tree-04", {x = 8.5, y = 2.5}, {}},
    {"stone-wall", {x = 14.5, y = 2.5}, {}},
    {"stone-wall", {x = -14.5, y = 3.5}, {}},
    {"tree-04", {x = -12.5, y = 4.5}, {}},
    {"tree-04", {x = -6.5, y = 4.5}, {}},
    {"solar-panel", {x = 12.5, y = 5.5}, {}},
    {"medium-electric-pole", {x = 10.5, y = 3.5}, {}},
    {"tree-04", {x = 11.5, y = 3.5}, {}},
    {"stone-wall", {x = 14.5, y = 3.5}, {}},
    {"stone-wall", {x = 14.5, y = 4.5}, {}},
    {"stone-wall", {x = -14.5, y = 5.5}, {}},
    {"stone-wall", {x = -14.5, y = 6.5}, {}},
    {"tree-04", {x = -0.5, y = 6.5}, {}},
    {"tree-04", {x = 9.5, y = 5.5}, {}},
    {"stone-wall", {x = 14.5, y = 5.5}, {}},
    {"stone-wall", {x = -14.5, y = 7.5}, {}},
    {"tree-04", {x = 5.5, y = 7.5}, {}},
    {"solar-panel", {x = 8.5, y = 9.5}, {}},
    {"stone-wall", {x = 14.5, y = 7.5}, {}},
    {"stone-wall", {x = 14.5, y = 8.5}, {}},
    {"stone-wall", {x = -14.5, y = 9.5}, {}},
    {"tree-04", {x = -10.5, y = 10.5}, {}},
    {"tree-04", {x = -4.5, y = 9.5}, {}},
    {"tree-04", {x = 1.5, y = 10.5}, {}},
    {"stone-wall", {x = 14.5, y = 9.5}, {}},
    {"stone-wall", {x = 14.5, y = 10.5}, {}},
    {"stone-wall", {x = -14.5, y = 11.5}, {}},
    {"stone-wall", {x = -14.5, y = 12.5}, {}},
    {"tree-04", {x = -4.5, y = 12.5}, {}},
    {"tree-04", {x = 5.5, y = 11.5}, {}},
    {"tree-04", {x = 8.5, y = 12.5}, {}},
    {"solar-panel", {x = 12.5, y = 12.5}, {}},
    {"medium-electric-pole", {x = 10.5, y = 11.5}, {}},
    {"stone-wall", {x = 14.5, y = 11.5}, {}},
    {"stone-wall", {x = 14.5, y = 12.5}, {}},
    {"stone-wall", {x = -14.5, y = 13.5}, {}},
    {"stone-wall", {x = -14.5, y = 14.5}, {}},
    {"stone-wall", {x = -12.5, y = 14.5}, {}},
    {"stone-wall", {x = -13.5, y = 14.5}, {}},
    {"stone-wall", {x = -11.5, y = 14.5}, {}},
    {"stone-wall", {x = -8.5, y = 14.5}, {}},
    {"stone-wall", {x = -7.5, y = 14.5}, {}},
    {"stone-wall", {x = -4.5, y = 14.5}, {}},
    {"stone-wall", {x = -5.5, y = 14.5}, {}},
    {"stone-wall", {x = -3.5, y = 14.5}, {}},
    {"stone-wall", {x = -1.5, y = 14.5}, {}},
    {"stone-wall", {x = 0.5, y = 14.5}, {}},
    {"stone-wall", {x = 3.5, y = 14.5}, {}},
    {"stone-wall", {x = 2.5, y = 14.5}, {}},
    {"stone-wall", {x = 5.5, y = 14.5}, {}},
    {"stone-wall", {x = 4.5, y = 14.5}, {}},
    {"stone-wall", {x = 7.5, y = 14.5}, {}},
    {"stone-wall", {x = 6.5, y = 14.5}, {}},
    {"stone-wall", {x = 9.5, y = 14.5}, {}},
    {"stone-wall", {x = 8.5, y = 14.5}, {}},
    {"stone-wall", {x = 11.5, y = 14.5}, {}},
    {"stone-wall", {x = 10.5, y = 14.5}, {}},
    {"stone-wall", {x = 13.5, y = 14.5}, {}},
    {"stone-wall", {x = 12.5, y = 14.5}, {}},
    {"stone-wall", {x = 14.5, y = 13.5}, {}},
    {"stone-wall", {x = 14.5, y = 14.5}, {}},
  },
  tiles =
  {
    {"water", {x = -4, y = -2}},
    {"water", {x = -3, y = -2}},
    {"water", {x = -3, y = 0}},
    {"water", {x = -2, y = -3}},
    {"water", {x = -2, y = -2}},
    {"water", {x = -2, y = -1}},
    {"water", {x = -2, y = 0}},
    {"water", {x = -2, y = 1}},
    {"water", {x = -2, y = 2}},
    {"water", {x = -1, y = -3}},
    {"water", {x = -1, y = -2}},
    {"water", {x = -1, y = -1}},
    {"water", {x = -1, y = 0}},
    {"water", {x = -1, y = 1}},
    {"water", {x = -1, y = 2}},
    {"water", {x = 0, y = -3}},
    {"water", {x = 0, y = -2}},
    {"water", {x = 0, y = -1}},
    {"water", {x = 0, y = 0}},
    {"water", {x = 0, y = 1}},
    {"water", {x = 0, y = 2}},
    {"water", {x = 0, y = 3}},
    {"water", {x = 1, y = -3}},
    {"water", {x = 1, y = -2}},
    {"water", {x = 1, y = -1}},
    {"water", {x = 1, y = 0}},
    {"water", {x = 1, y = 1}},
    {"water", {x = 1, y = 2}},
    {"water", {x = 2, y = -3}},
    {"water", {x = 2, y = -2}},
    {"water", {x = 2, y = -1}},
    {"water", {x = 2, y = 0}},
    {"water", {x = 2, y = 1}},
    {"water", {x = 2, y = 2}},
    {"water", {x = 2, y = 3}},
    {"water", {x = 3, y = -5}},
    {"water", {x = 3, y = -4}},
    {"water", {x = 3, y = -3}},
    {"water", {x = 3, y = -2}},
    {"water", {x = 3, y = -1}},
    {"water", {x = 3, y = 0}},
    {"water", {x = 3, y = 1}},
    {"water", {x = 3, y = 2}},
    {"water", {x = 3, y = 3}},
    {"water", {x = 3, y = 4}},
    {"water", {x = 4, y = -4}},
    {"water", {x = 4, y = -3}},
    {"water", {x = 4, y = -2}},
    {"water", {x = 4, y = -1}},
    {"water", {x = 4, y = 0}},
    {"water", {x = 4, y = 1}},
    {"water", {x = 4, y = 2}},
    {"water", {x = 5, y = -4}},
    {"water", {x = 5, y = -3}},
    {"water", {x = 5, y = -2}},
    {"water", {x = 5, y = -1}},
    {"water", {x = 6, y = -4}},
    {"water", {x = 6, y = -3}},
    {"water", {x = 6, y = -2}},
    {"water", {x = 7, y = -4}},
    {"water", {x = 7, y = -3}},
    {"water", {x = 8, y = -4}},
    {"water", {x = 8, y = -3}},
    {"water", {x = 9, y = -4}},
    {"water", {x = 9, y = -3}},
    {"water", {x = 10, y = -4}},
    {"water", {x = 10, y = -3}},
    {"water", {x = 11, y = -4}},
    {"water", {x = 11, y = -3}},
    {"water", {x = 12, y = -4}},
    {"water", {x = 12, y = -3}},
    {"water", {x = 13, y = -4}},
    {"water", {x = 13, y = -3}},
  }
}
