return
{
  entities =
  {
    {"tree-05", {x = -5.5, y = -4.5}, {}},
    {"stone-wall", {x = -4.5, y = -5.5}, {}},
    {"stone-wall", {x = -5.5, y = -5.5}, {}},
    {"tree-05", {x = -2.5, y = -5.5}, {}},
    {"stone-wall", {x = -3.5, y = -5.5}, {}},
    {"tree-05", {x = -0.5, y = -5.5}, {}},
    {"stone-wall", {x = 1.5, y = -5.5}, {}},
    {"tree-05", {x = 2.5, y = -5.5}, {}},
    {"tree-05", {x = 5.5, y = -5.5}, {}},
    {"wall-remnants", {x = 4.5, y = -5.5}, {dir = "south", }},
    {"tree-05", {x = -5.5, y = -2.5}, {}},
    {"medium-electric-pole", {x = -3.5, y = -3.5}, {}},
    {"gun-turret", {x = 3, y = -2}, {force = "enemy", items = {["piercing-rounds-magazine"] = 5}, }},
    {"tree-05", {x = 5.5, y = -3.5}, {}},
    {"stone-wall", {x = -5.5, y = -0.5}, {}},
    {"tree-05", {x = 5.5, y = -0.5}, {}},
    {"stone-wall", {x = 6.5, y = -1.5}, {}},
    {"stone-wall", {x = -5.5, y = 0.5}, {}},
    {"stone-wall", {x = -5.5, y = 1.5}, {}},
    {"steel-chest", {x = -0.5, y = 0.5}, {items = {["uranium-fuel-cell"] = {type = "random", min = 2, max = 5}}, }},
    {"wall-remnants", {x = 6.5, y = 1.5}, {dir = "south", }},
    {"tree-05", {x = -5.5, y = 3.5}, {}},
    {"wall-remnants", {x = -5.5, y = 2.5}, {}},
    {"medium-electric-pole", {x = 1.5, y = 2.5}, {}},
    {"land-mine", {x = 4.86, y = 4.17}, {force = "enemy", }},
    {"tree-05", {x = 5.5, y = 2.5}, {}},
    {"tree-05", {x = -5.5, y = 5.5}, {}},
    {"gun-turret", {x = -2, y = 5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 5}, }},
    {"gate-remnants", {x = 6.5, y = 4.5}, {}},
    {"gate-remnants", {x = 6.5, y = 5.5}, {}},
    {"stone-wall", {x = -5.5, y = 7.5}, {}},
    {"stone-wall", {x = -4.5, y = 7.5}, {}},
    {"wall-remnants", {x = -3.5, y = 7.5}, {dir = "south", }},
    {"stone-wall", {x = -2.5, y = 7.5}, {}},
    {"tree-05", {x = -1.5, y = 6.5}, {}},
    {"tree-05", {x = 1.5, y = 6.5}, {}},
    {"stone-wall", {x = 0.5, y = 7.5}, {}},
    {"stone-wall", {x = 3.5, y = 7.5}, {}},
    {"tree-05", {x = 4.5, y = 6.5}, {}},
    {"stone-wall", {x = 6.5, y = 7.5}, {}},
    {"stone-wall", {x = 6.5, y = 6.5}, {}},
  },
}
