return
{
  entities =
  {
    {"stone-wall", {x = -6, y = -6}, {}},
    {"stone-wall", {x = -4, y = -6}, {}},
    {"stone-wall", {x = -5, y = -6}, {}},
    {"tree-05", {x = -3, y = -6}, {}},
    {"tree-05", {x = -1, y = -6}, {}},
    {"tree-05", {x = 2, y = -6}, {}},
    {"stone-wall", {x = 1, y = -6}, {}},
    {"wall-remnants", {x = 4, y = -6}, {dir = "south", }},
    {"tree-05", {x = 5, y = -6}, {}},
    {"tree-05", {x = -6, y = -5}, {}},
    {"medium-electric-pole", {x = -4, y = -4}, {}},
    {"fast-transport-belt", {x = -2, y = -4}, {dir = "south", }},
    {"fast-transport-belt", {x = 0, y = -4}, {dir = "south", }},
    {"fast-transport-belt", {x = -1, y = -4}, {dir = "south", }},
    {"fast-transport-belt", {x = 1, y = -4}, {dir = "south", }},
    {"tree-05", {x = 5, y = -4}, {}},
    {"tree-05", {x = -6, y = -3}, {}},
    {"bulk-inserter-remnants", {x = -4, y = -2}, {dir = "east", }},
    {"buffer-chest-remnants", {x = -2, y = -2}, {}},
    {"bulk-inserter-remnants", {x = -2, y = -3}, {dir = "east", }},
    {"requester-chest-remnants", {x = -3, y = -2}, {}},
    {"buffer-chest-remnants", {x = 0, y = -2}, {}},
    {"bulk-inserter-remnants", {x = 0, y = -3}, {dir = "east", }},
    {"buffer-chest-remnants", {x = -1, y = -2}, {}},
    {"bulk-inserter-remnants", {x = -1, y = -3}, {dir = "east", }},
    {"passive-provider-chest-remnants", {x = 2, y = -2}, {}},
    {"buffer-chest-remnants", {x = 1, y = -2}, {}},
    {"bulk-inserter-remnants", {x = 1, y = -3}, {dir = "east", }},
    {"fast-transport-belt", {x = 4, y = -2}, {dir = "west", }},
    {"bulk-inserter-remnants", {x = 3, y = -2}, {dir = "east", }},
    {"stone-wall", {x = 6, y = -2}, {}},
    {"stone-wall", {x = -6, y = -1}, {}},
    {"stone-wall", {x = -6, y = 0}, {}},
    {"bulk-inserter-remnants", {x = -4, y = -1}, {dir = "east", }},
    {"bulk-inserter-remnants", {x = -4, y = 0}, {dir = "east", }},
    {"storage-chest-remnants", {x = -2, y = -1}, {}},
    {"storage-chest-remnants", {x = -2, y = 0}, {}},
    {"requester-chest-remnants", {x = -3, y = -1}, {}},
    {"requester-chest-remnants", {x = -3, y = 0}, {}},
    {"storage-chest-remnants", {x = 0, y = -1}, {}},
    {"storage-chest-remnants", {x = 0, y = 0}, {}},
    {"storage-chest-remnants", {x = -1, y = -1}, {}},
    {"storage-chest-remnants", {x = -1, y = 0}, {}},
    {"passive-provider-chest-remnants", {x = 2, y = -1}, {}},
    {"passive-provider-chest-remnants", {x = 2, y = 0}, {}},
    {"storage-chest-remnants", {x = 1, y = -1}, {}},
    {"storage-chest-remnants", {x = 1, y = 0}, {}},
    {"fast-transport-belt", {x = 4, y = -1}, {dir = "west", }},
    {"fast-transport-belt", {x = 4, y = 0}, {dir = "west", }},
    {"bulk-inserter-remnants", {x = 3, y = -1}, {dir = "east", }},
    {"bulk-inserter-remnants", {x = 3, y = 0}, {dir = "east", }},
    {"tree-05", {x = 5, y = -1}, {}},
    {"stone-wall", {x = -6, y = 1}, {}},
    {"wall-remnants", {x = -6, y = 2}, {}},
    {"bulk-inserter", {x = -4, y = 1}, {dir = "east", }},
    {"requester-chest", {x = -3, y = 1}, {}},
    {"active-provider-chest-remnants", {x = -2, y = 1}, {}},
    {"bulk-inserter-remnants", {x = -2, y = 2}, {dir = "east", }},
    {"active-provider-chest-remnants", {x = 0, y = 1}, {}},
    {"bulk-inserter-remnants", {x = 0, y = 2}, {dir = "east", }},
    {"active-provider-chest-remnants", {x = -1, y = 1}, {}},
    {"bulk-inserter-remnants", {x = -1, y = 2}, {dir = "east", }},
    {"passive-provider-chest-remnants", {x = 2, y = 1}, {}},
    {"active-provider-chest-remnants", {x = 1, y = 1}, {}},
    {"bulk-inserter-remnants", {x = 1, y = 2}, {dir = "east", }},
    {"fast-transport-belt", {x = 4, y = 1}, {dir = "west", }},
    {"bulk-inserter-remnants", {x = 3, y = 1}, {dir = "east", }},
    {"wall-remnants", {x = 6, y = 1}, {dir = "south", }},
    {"tree-05", {x = 5, y = 2}, {}},
    {"tree-05", {x = -6, y = 3}, {}},
    {"fast-transport-belt", {x = -2, y = 3}, {}},
    {"gun-turret", {x = -2.5, y = 4.5}, {force = "enemy", items = {["piercing-rounds-magazine"] = 5}, }},
    {"fast-transport-belt", {x = 0, y = 3}, {}},
    {"fast-transport-belt", {x = -1, y = 3}, {}},
    {"fast-transport-belt", {x = 1, y = 3}, {}},
    {"land-mine", {x = 4.36, y = 3.67}, {force = "enemy", }},
    {"gate-remnants", {x = 6, y = 4}, {}},
    {"tree-05", {x = -6, y = 5}, {}},
    {"tree-05", {x = -2, y = 6}, {}},
    {"tree-05", {x = 1, y = 6}, {}},
    {"tree-05", {x = 4, y = 6}, {}},
    {"gate-remnants", {x = 6, y = 5}, {}},
    {"stone-wall", {x = 6, y = 6}, {}},
    {"stone-wall", {x = -6, y = 7}, {}},
    {"wall-remnants", {x = -4, y = 7}, {dir = "south", }},
    {"stone-wall", {x = -5, y = 7}, {}},
    {"stone-wall", {x = -3, y = 7}, {}},
    {"stone-wall", {x = 0, y = 7}, {}},
    {"stone-wall", {x = 3, y = 7}, {}},
    {"stone-wall", {x = 6, y = 7}, {}},
  },
}
