function hide_setting(setting_type, setting_name, forced_setting_value)
    if data.raw[setting_type] and data.raw[setting_type][setting_name] then
        data.raw[setting_type][setting_name].hidden = true
    else
        log("Could not find setting '" .. setting_name .. "'.")
    end
end
-- ########################################################################################################################
-- Настройки запуска

hide_setting("bool-setting", "extangels-adjust-ordering")
hide_setting("bool-setting", "extangels-legacy-inventory-sizes")

hide_setting("bool-setting", "Warehousing-icon-scaling")
hide_setting("bool-setting", "Warehousing-copy-logistic-system")
hide_setting("bool-setting", "Warehousing-sixteen-mode")

hide_setting("double-setting", "baa-arrow-scale")
hide_setting("string-setting", "baa-arrow-tint")
hide_setting("bool-setting", "fitolamps")
hide_setting("bool-setting", "stone-path-concrete")
hide_setting("bool-setting", "res_loc_1")
hide_setting("bool-setting", "res_loc_2")
hide_setting("bool-setting", "res_loc_3")
hide_setting("bool-setting", "res_loc_e")

hide_setting("bool-setting", "crash-sequence")
hide_setting("int-setting", "aai-burner-turbine-efficiency")

hide_setting("bool-setting", "aircraft-sound-setting")
hide_setting("bool-setting", "aircraft-hardmode")
hide_setting("bool-setting", "aircraft-belt-immunity")
hide_setting("bool-setting", "helicopter-tech")
hide_setting("bool-setting", "heli-equipment-grid")
hide_setting("bool-setting", "raven-tech")
hide_setting("bool-setting", "non-combat-mode")
hide_setting("bool-setting", "inserter-immunity")
hide_setting("bool-setting", "disable-acid-splash")

hide_setting("double-setting", "angels-bio-tile-pollution-absorbtion-multiplier")

hide_setting("bool-setting", "remelting-smooth-integration")

hide_setting("bool-setting", "ASE-angels-coil-icons")
hide_setting("bool-setting", "ASE-angels-molten-recipes")

hide_setting("int-setting", "angels-infinite-yield")
hide_setting("double-setting", "angels-lower-infinite-yield")
hide_setting("bool-setting", "angels-enablefluidreq")
hide_setting("bool-setting", "angels-keepuranacid")

hide_setting("bool-setting", "angels-enable-converter")
hide_setting("bool-setting", "angels-hide-converter")
hide_setting("bool-setting", "angels-enable-acids")
hide_setting("bool-setting", "angels-disable-bobs-electrolysers")
hide_setting("bool-setting", "angels-disable-bobs-chemical-plants")
hide_setting("bool-setting", "angels-show-chemical-formula")

hide_setting("string-setting", "angels-enable-auto-barreling")
hide_setting("bool-setting", "angels-enable-hide-void")
hide_setting("bool-setting", "angels-tryptophobia-friendly-stiratite")
hide_setting("bool-setting", "angels-hq-graphics")
hide_setting("double-setting", "angels-marathon-buildingmulti")
hide_setting("double-setting", "angels-marathon-buildingtime")
hide_setting("double-setting", "angels-marathon-rawmulti")
hide_setting("double-setting", "angels-marathon-intermediatemulti")
hide_setting("bool-setting", "angels-starting-resource-ore1")
hide_setting("bool-setting", "angels-starting-resource-ore2")
hide_setting("bool-setting", "angels-starting-resource-ore3")
hide_setting("bool-setting", "angels-starting-resource-ore4")
hide_setting("bool-setting", "angels-starting-resource-ore5")
hide_setting("bool-setting", "angels-starting-resource-ore6")
hide_setting("double-setting", "angels-starting-resource-base")
hide_setting("int-setting", "angels-pavement-stack-size")

hide_setting("bool-setting", "reskins-lib-scope-entities")
hide_setting("bool-setting", "reskins-lib-scope-equipment")
hide_setting("bool-setting", "reskins-lib-scope-items-and-fluids")
hide_setting("bool-setting", "reskins-lib-scope-technologies")
hide_setting("bool-setting", "reskins-lib-icon-tier-labeling")
hide_setting("string-setting", "reskins-lib-icon-tier-labeling-style")
hide_setting("string-setting", "reskins-lib-tier-mapping")
hide_setting("bool-setting", "reskins-lib-customize-tier-colors")
hide_setting("string-setting", "reskins-lib-custom-colors-tier-0")
hide_setting("string-setting", "reskins-lib-custom-colors-tier-1")
hide_setting("string-setting", "reskins-lib-custom-colors-tier-2")
hide_setting("string-setting", "reskins-lib-custom-colors-tier-3")
hide_setting("string-setting", "reskins-lib-custom-colors-tier-4")
hide_setting("string-setting", "reskins-lib-custom-colors-tier-5")
hide_setting("string-setting", "reskins-lib-custom-colors-tier-6")

hide_setting("bool-setting", "reskins-compatibility-extendedangels-warehouse-tiering")

hide_setting("bool-setting", "reskins-angels-do-angelsbioprocessing")
hide_setting("bool-setting", "reskins-angels-do-angelspetrochem")
hide_setting("bool-setting", "reskins-angels-do-angelsrefining")
hide_setting("bool-setting", "reskins-angels-do-angelssmelting")
hide_setting("bool-setting", "reskins-angels-use-vanilla-chemical-plant-sprites")
hide_setting("bool-setting", "reskins-angels-use-angels-material-colors")
hide_setting("bool-setting", "reskins-angels-use-angels-material-colors-pipes")
hide_setting("bool-setting", "reskins-angels-use-item-variations")

hide_setting("bool-setting", "reskins-bobs-do-bobassembly")
hide_setting("bool-setting", "reskins-bobs-do-bobelectronics")
hide_setting("string-setting", "reskins-bobs-do-bobelectronics-circuit-style")
hide_setting("bool-setting", "reskins-bobs-do-bobenemies")
hide_setting("bool-setting", "reskins-bobs-do-bobequipment")
hide_setting("bool-setting", "reskins-bobs-do-boblogistics")
hide_setting("bool-setting", "reskins-bobs-do-bobmining")
hide_setting("bool-setting", "reskins-bobs-do-bobmodules")
hide_setting("bool-setting", "reskins-bobs-do-bobores")
hide_setting("bool-setting", "reskins-bobs-do-bobplates")
hide_setting("bool-setting", "reskins-bobs-do-bobpower")
hide_setting("bool-setting", "reskins-bobs-do-bobrevamp")
hide_setting("bool-setting", "reskins-bobs-do-bobrevamp-reactor-color")
hide_setting("bool-setting", "reskins-bobs-do-bobtech")
hide_setting("bool-setting", "reskins-bobs-do-bobvehicleequipment")
hide_setting("bool-setting", "reskins-bobs-do-bobwarfare")
hide_setting("bool-setting", "reskins-bobs-hydrazine-is-blue")
hide_setting("bool-setting", "reskins-bobs-do-belt-entity-tier-labeling")
hide_setting("bool-setting", "reskins-bobs-do-furnace-tier-labeling")
hide_setting("bool-setting", "reskins-bobs-do-pipe-tier-labeling")
hide_setting("bool-setting", "reskins-bobs-do-inserter-filter-symbol")
hide_setting("bool-setting", "reskins-bobs-do-inserter-tier-labeling")
hide_setting("bool-setting", "reskins-bobs-flip-bulk-inserter-icons")
hide_setting("bool-setting", "reskins-bobs-do-basic-belts-separately")
hide_setting("string-setting", "reskins-bobs-basic-belts-color")
hide_setting("bool-setting", "reskins-bobs-do-progression-based-robots")
hide_setting("string-setting", "reskins-bobs-fusion-robot-color")
hide_setting("bool-setting", "reskins-bobs-do-custom-furnace-variants")
hide_setting("string-setting", "reskins-bobs-standard-furnace-color")
hide_setting("string-setting", "reskins-bobs-mixing-furnace-color")

hide_setting("bool-setting", "bet-cheatsy-locs")
hide_setting("bool-setting", "bet-cheatsy-wagons")
hide_setting("double-setting", "bet-cheatsy-speed")
hide_setting("int-setting", "bet-cheatsy-power")
hide_setting("double-setting", "bet-cheatsy-braking")
hide_setting("bool-setting", "bet-recycling")
hide_setting("string-setting", "bet-equipment-gridtype")

hide_setting("bool-setting", "betterCargoPlanes-MilitaryEquipment")
hide_setting("int-setting", "betterCargoPlanes-inventorySizeT1")
hide_setting("int-setting", "betterCargoPlanes-inventorySizeT2")
hide_setting("int-setting", "betterCargoPlanes-inventorySizeT3")
hide_setting("double-setting", "betterCargoPlanes-rotationSpeedT1")
hide_setting("double-setting", "betterCargoPlanes-rotationSpeedT2")
hide_setting("double-setting", "betterCargoPlanes-rotationSpeedT3")

hide_setting("int-setting", "ritnmods-bl-01")

hide_setting("double-setting", "bm-enemy-hp-multiplier")
hide_setting("double-setting", "bm-big-enemy-hp-multiplier")
hide_setting("double-setting", "bm-big-enemy-hp-variant")
hide_setting("double-setting", "bm-worm-enemy-hp-multiplier")
hide_setting("double-setting", "bm-enemy-damage-multiplier")

hide_setting("bool-setting", "BI_Solar_Additions")
hide_setting("bool-setting", "BI_Bigger_Wooden_Chests")
hide_setting("bool-setting", "BI_Bio_Fuel")
hide_setting("bool-setting", "BI_Game_Tweaks_Emissions_Multiplier")
hide_setting("bool-setting", "BI_Game_Tweaks_Stack_Size")
hide_setting("bool-setting", "BI_Game_Tweaks_Recipe")
hide_setting("bool-setting", "BI_Game_Tweaks_Production_Science")
hide_setting("bool-setting", "BI_Game_Tweaks_Tree")
hide_setting("bool-setting", "BI_Game_Tweaks_Small_Tree_Collisionbox")
hide_setting("bool-setting", "BI_Game_Tweaks_Player")

hide_setting("bool-setting", "bpsb-labs-absorb-pollution")

hide_setting("bool-setting", "baraws-all-made-in")
hide_setting("bool-setting", "baraws-all-products")

hide_setting("double-setting", "BPT-base")
hide_setting("double-setting", "BPT-per-tier")

hide_setting("bool-setting", "bobmods-inserters-long1")
hide_setting("bool-setting", "bobmods-inserters-long2")
hide_setting("bool-setting", "bobmods-inserters-more2")

hide_setting("bool-setting", "bobmods-assembly-burner")
hide_setting("bool-setting", "bobmods-assembly-centrifuge")
hide_setting("bool-setting", "bobmods-assembly-chemicalplants")
hide_setting("bool-setting", "bobmods-assembly-distilleries")
hide_setting("bool-setting", "bobmods-assembly-electrolysers")
hide_setting("bool-setting", "bobmods-assembly-electronicmachines")
hide_setting("bool-setting", "bobmods-assembly-furnaces")
hide_setting("bool-setting", "bobmods-assembly-limits")
hide_setting("bool-setting", "bobmods-assembly-multipurposefurnaces")
hide_setting("bool-setting", "bobmods-assembly-oilfurnaces")
hide_setting("bool-setting", "bobmods-assembly-oilrefineries")

hide_setting("bool-setting", "bobmods-enemies-aliensdropartifacts")
hide_setting("bool-setting", "bobmods-enemies-biggersooner")
hide_setting("bool-setting", "bobmods-enemies-enableartifacts")
hide_setting("bool-setting", "bobmods-enemies-healthincrease")
hide_setting("double-setting", "bobmods-enemies-leviathanfrequency")
hide_setting("bool-setting", "bobmods-enemies-superspawner")

hide_setting("bool-setting", "bobmods-library-recipe-cleanup")
hide_setting("bool-setting", "bobmods-library-technology-cleanup")

hide_setting("bool-setting", "bobmods-logistics-beltoverhaul")
hide_setting("bool-setting", "bobmods-logistics-beltoverhaulspeed")
hide_setting("int-setting", "bobmods-logistics-beltperlevel")
hide_setting("bool-setting", "bobmods-logistics-beltrequireprevious")
hide_setting("double-setting", "bobmods-logistics-beltspeedperlevel")
hide_setting("int-setting", "bobmods-logistics-beltstarting")
hide_setting("bool-setting", "bobmods-logistics-disableroboports")
hide_setting("bool-setting", "bobmods-logistics-drainlessinserters")
hide_setting("int-setting", "bobmods-logistics-fluidwagonbase")
hide_setting("bool-setting", "bobmods-logistics-flyingrobotframes")
hide_setting("bool-setting", "bobmods-logistics-highpipes")
hide_setting("bool-setting", "bobmods-logistics-inserteroverhaul")
hide_setting("bool-setting", "bobmods-logistics-inserterrequireprevious")
hide_setting("int-setting", "bobmods-logistics-pipeperlevel")
hide_setting("int-setting", "bobmods-logistics-pipestarting")
hide_setting("bool-setting", "bobmods-logistics-roboportrecipeupdate")
hide_setting("bool-setting", "bobmods-logistics-robotparts")
hide_setting("bool-setting", "bobmods-logistics-robotrequireprevious")
hide_setting("int-setting", "bobmods-logistics-storagetankbase")
hide_setting("bool-setting", "bobmods-logistics-trains")
hide_setting("bool-setting", "bobmods-logistics-ugdistanceoverhaul")

hide_setting("bool-setting", "bobmods-colorupdate")
hide_setting("bool-setting", "bobmods-plates-batteryupdate")
hide_setting("bool-setting", "bobmods-plates-bluedeuterium")
hide_setting("bool-setting", "bobmods-plates-cheapersteel")
hide_setting("bool-setting", "bobmods-plates-expensive-electrolysis")
hide_setting("int-setting", "bobmods-plates-inventorysize")
hide_setting("bool-setting", "bobmods-plates-nuclearupdate")

hide_setting("bool-setting", "bobmods-mining-areadrills")
hide_setting("bool-setting", "bobmods-mining-miningaxes")
hide_setting("bool-setting", "bobmods-mining-miningdrills")
hide_setting("bool-setting", "bobmods-mining-pumpjacks")
hide_setting("bool-setting", "bobmods-mining-steamminingdrills")
hide_setting("bool-setting", "bobmods-mining-waterminers")

hide_setting("bool-setting", "bobmods-modules-enable-modules-lab")
hide_setting("bool-setting", "bobmods-modules-enablegodmodules")
hide_setting("bool-setting", "bobmods-modules-enablegreenmodules")
hide_setting("bool-setting", "bobmods-modules-enableproductivitylimitation")
hide_setting("bool-setting", "bobmods-modules-enablerawproductivitymodules")
hide_setting("bool-setting", "bobmods-modules-enablerawspeedmodules")
hide_setting("double-setting", "bobmods-modules-perlevel-bonus-consumption")
hide_setting("double-setting", "bobmods-modules-perlevel-bonus-pollution")
hide_setting("double-setting", "bobmods-modules-perlevel-bonus-pollutioncreate")
hide_setting("double-setting", "bobmods-modules-perlevel-bonus-productivity")
hide_setting("double-setting", "bobmods-modules-perlevel-bonus-speed")
hide_setting("double-setting", "bobmods-modules-perlevel-penalty-consumption")
hide_setting("double-setting", "bobmods-modules-perlevel-penalty-pollution")
hide_setting("double-setting", "bobmods-modules-perlevel-penalty-pollution")
hide_setting("double-setting", "bobmods-modules-perlevel-penalty-speed")
hide_setting("bool-setting", "bobmods-modules-productivityhasspeed")
hide_setting("double-setting", "bobmods-modules-start-bonus-consumption")
hide_setting("double-setting", "bobmods-modules-start-bonus-pollution")
hide_setting("double-setting", "bobmods-modules-start-bonus-pollutioncreate")
hide_setting("double-setting", "bobmods-modules-start-bonus-productivity")
hide_setting("double-setting", "bobmods-modules-start-bonus-speed")
hide_setting("double-setting", "bobmods-modules-start-penalty-consumption")
hide_setting("double-setting", "bobmods-modules-start-penalty-pollution")
hide_setting("double-setting", "bobmods-modules-start-penalty-speed")

hide_setting("bool-setting", "bobmods-ores-enablewaterores")
hide_setting("bool-setting", "bobmods-ores-infiniteore")

hide_setting("bool-setting", "bobmods-power-accumulators")
hide_setting("bool-setting", "bobmods-power-burnergenerator")
hide_setting("bool-setting", "bobmods-power-fluidgenerator")
hide_setting("bool-setting", "bobmods-power-heatsources")
hide_setting("bool-setting", "bobmods-power-nuclear")
hide_setting("bool-setting", "bobmods-power-poles")
hide_setting("bool-setting", "bobmods-power-solar")
hide_setting("bool-setting", "bobmods-power-steam")

hide_setting("bool-setting", "bobmods-revamp-hardmode")
hide_setting("bool-setting", "bobmods-revamp-nuclear")
hide_setting("bool-setting", "bobmods-revamp-oil")
hide_setting("bool-setting", "bobmods-revamp-old-oil")
hide_setting("bool-setting", "bobmods-revamp-rtg")

hide_setting("bool-setting", "bobmods-burnerphase")
hide_setting("bool-setting", "bobmods-tech-colorupdate")

hide_setting("bool-setting", "bobmods-vehicleequipment-enablevehiclegrids")

hide_setting("bool-setting", "bobmods-warfare-drainlesslaserturrets")
hide_setting("bool-setting", "bobmods-warfare-robotupdate")
hide_setting("string-setting", "bobmods-warfare-spidertron-needsfuel")
hide_setting("bool-setting", "bobmods-warfare-spidertron-overhaul")
hide_setting("bool-setting", "bobmods-warfare-vehicleflamethrowerstartsfires")

hide_setting("bool-setting", "bnl-enable")
hide_setting("bool-setting", "bnl-glow")
hide_setting("bool-setting", "bnl-include-mining-drills")
hide_setting("string-setting", "bnl-indicator-size")
hide_setting("color-setting", "bnl-color-disabled")
hide_setting("color-setting", "bnl-color-full_output")
hide_setting("color-setting", "bnl-color-idle")
hide_setting("color-setting", "bnl-color-insufficient_input")
hide_setting("color-setting", "bnl-color-low_power")
hide_setting("color-setting", "bnl-color-no_minable_resources")
hide_setting("color-setting", "bnl-color-no_power")
hide_setting("color-setting", "bnl-color-working")

hide_setting("int-setting", "railloader-capacity")

hide_setting("bool-setting", "coppermine-bob-module-expensive-beacons")
hide_setting("bool-setting", "coppermine-bob-module-expensive-module-combination")
hide_setting("bool-setting", "coppermine-bob-module-exponential-modules")
hide_setting("double-setting", "coppermine-bob-module-god-module-research-multiplier")
hide_setting("bool-setting", "coppermine-bob-module-god-modules-in-space-ex")
hide_setting("bool-setting", "coppermine-bob-module-modules-in-rocket")
hide_setting("bool-setting", "coppermine-bob-module-nerfed-beacons")
hide_setting("bool-setting", "coppermine-bob-module-nerfed-modules")
hide_setting("bool-setting", "coppermine-bob-module-space-packs-for-god-modules")

hide_setting("bool-setting", "deadlock-force-research-queue")

hide_setting("bool-setting", "Use-Mod-Color-for-steam-generators")

hide_setting("int-setting", "electric-resistance-power-consumption")

hide_setting("bool-setting", "Use-Mod-Color-for-heat-pipes")
hide_setting("bool-setting", "Use-Mod-Color-for-pipes")
hide_setting("bool-setting", "Use-Mod-Color-for-roboports")
hide_setting("bool-setting", "Use-Mod-Color-for-roboports")

hide_setting("bool-setting", "ERPTbaAB-give-refining-ores")
hide_setting("bool-setting", "ERPTbaAB-integrate-spacex")
hide_setting("double-setting", "ERPTbaAB-refurbish-chance")
hide_setting("bool-setting", "ERPTbaAB-refurbish-not-guaranteed")
hide_setting("bool-setting", "ERPTbaAB-use-bobinserters")
hide_setting("bool-setting", "ERPTbaAB-use-heat-shield-tile")
hide_setting("bool-setting", "ERPTbaAB-use-petrochem-buildings")
hide_setting("bool-setting", "ERPTbaAB-use-titanium-concrete")

hide_setting("bool-setting", "ed-allowed-modules")
hide_setting("bool-setting", "ed-building-size")
hide_setting("bool-setting", "ed-fluid-colors")
hide_setting("bool-setting", "ed-heat")
hide_setting("bool-setting", "ed-inserter-stats")
hide_setting("bool-setting", "ed-inserter-stats")
hide_setting("bool-setting", "ed-military-resistances")
hide_setting("bool-setting", "ed-radar-stats")
hide_setting("bool-setting", "ed-solar-ratios")
hide_setting("bool-setting", "ed-tank-size")
hide_setting("bool-setting", "ed-voiding")

hide_setting("bool-setting", "flow-control-new-group")
hide_setting("bool-setting", "flow-control-revert-to-normal-pipe")

hide_setting("bool-setting", "fmf-enable-duct-auto-join")
hide_setting("int-setting", "fmf-underground-duct-max-length")

hide_setting("bool-setting", "fluid-permutations-simple-mode")
hide_setting("int-setting", "fluid-permutations-threshold")

hide_setting("bool-setting", "laserfix-doubletint")
hide_setting("double-setting", "laserfix-r")
hide_setting("double-setting", "laserfix-g")
hide_setting("double-setting", "laserfix-b")
hide_setting("double-setting", "laserfix-glow-r")
hide_setting("double-setting", "laserfix-glow-g")
hide_setting("double-setting", "laserfix-glow-b")

hide_setting("int-setting", "heroturrets-setting-level-up-modifier")
hide_setting("int-setting", "heroturrets-setting-level-buff-modifier")
hide_setting("int-setting", "heroturrets-setting-ammo-turret-kill-multiplier")
hide_setting("int-setting", "heroturrets-setting-fluid-turret-kill-multiplier")
hide_setting("int-setting", "heroturrets-setting-electric-turret-kill-multiplier")
hide_setting("int-setting", "heroturrets-setting-artillery-turret-kill-multiplier")
hide_setting("bool-setting", "heroturrets-allow-ghost-rank")
hide_setting("bool-setting", "heroturrets-allow-artillery-turrets")
hide_setting("string-setting", "heroturrets-kill-counter")
hide_setting("string-setting", "heroturrets-damage-counter")
hide_setting("string-setting", "heroturrets-allow-damage")
hide_setting("bool-setting", "heroturrets-use-csv")
hide_setting("string-setting", "heroturrets-csv-names")

hide_setting("bool-setting", "inf-tech-mining-productivity-log-formula")
hide_setting("bool-setting", "inf-tech-follower-count-log-formula")
hide_setting("int-setting", "inf-tech-follower-count-time")

hide_setting("string-setting", "max_stack_size_bonus")

hide_setting("bool-setting", "kaoextended-overide")

hide_setting("double-setting", "lepp_light_size_factor")
hide_setting("int-setting", "lepp_light_max_size")
hide_setting("string-setting", "lepp_pole_whitelist")
hide_setting("string-setting", "lepp_pole_blacklist")
hide_setting("string-setting", "lepp_tech_blacklist")
hide_setting("string-setting", "lepp_tech_fallback")

hide_setting("bool-setting", "ltnc-upgradable")

hide_setting("bool-setting", "reprocessing-overhaul")

hide_setting("bool-setting", "MCP_enable_centrifuges")
hide_setting("bool-setting", "depleted-uranium")
hide_setting("bool-setting", "equipment-group")
hide_setting("bool-setting", "fluid-cleanup")

hide_setting("bool-setting", "artillery-shells")

hide_setting("bool-setting", "miniloader-double-recipes")
hide_setting("bool-setting", "miniloader-enable-chute")
hide_setting("bool-setting", "miniloader-enable-filter")
hide_setting("bool-setting", "miniloader-enable-standard")
hide_setting("bool-setting", "miniloader-lock-stack-sizes")
hide_setting("bool-setting", "miniloader-energy-usage")
hide_setting("bool-setting", "miniloader-snapping")

hide_setting("bool-setting", "enable-radars")
hide_setting("bool-setting", "enable-hardened-inserter")
hide_setting("bool-setting", "enable-extra-ammo")
hide_setting("bool-setting", "cannon-ammo-range-disable")
hide_setting("bool-setting", "enable-pretargeting")

hide_setting("int-setting", "minime_character-size")
hide_setting("bool-setting", "minime_scale-reach_resource_distance")
hide_setting("bool-setting", "minime_scale-tool-attack-distance")
hide_setting("bool-setting", "minime_character-selector")
hide_setting("bool-setting", "minime_close-gui-on-selection")

hide_setting("bool-setting", "mprd-amount-display")
hide_setting("bool-setting", "mprd-vertical-display")

hide_setting("bool-setting", "angels-ores-only")
hide_setting("bool-setting", "belt-speed-change")
hide_setting("bool-setting", "bob-simple-logistics")
hide_setting("bool-setting", "bobs-military-simplify")
hide_setting("bool-setting", "bobs-module-nerf")
hide_setting("bool-setting", "bobs-solar-multiply")
hide_setting("bool-setting", "electrolyser-merge")
hide_setting("bool-setting", "gem-liquifaction")
hide_setting("bool-setting", "module-cost-multiply")
hide_setting("bool-setting", "module-slot-nerf")
hide_setting("bool-setting", "modules-use-circuits")
hide_setting("bool-setting", "petrochem-change")
hide_setting("bool-setting", "science-oberhaul")
hide_setting("bool-setting", "simple-cordite")
hide_setting("bool-setting", "train-wagon-nerf")

hide_setting("bool-setting", "OSM-debug-mode")

hide_setting("string-setting", "nb_black_night_darkness")

hide_setting("double-setting", "Noxys_Trees-tree_dying_factor")
hide_setting("double-setting", "Noxys_Trees-tree_fire_spread_speed_factor")
hide_setting("double-setting", "Noxys_Trees-emission_multiplier")

hide_setting("bool-setting", "pcp-glass-sink")
hide_setting("bool-setting", "pcp-replace-phenol-oxygen")

hide_setting("bool-setting", "picker-tool-tape-measure")

hide_setting("bool-setting", "picker-debug")

hide_setting("bool-setting", "picker-bp-prioritizer")
hide_setting("bool-setting", "picker-bp-snap")
hide_setting("bool-setting", "picker-tool-bp-updater")

hide_setting("bool-setting", "picker-tool-camera")
hide_setting("bool-setting", "picker-tool-ore-eraser")
hide_setting("bool-setting", "picker-tool-pipe-clamps")

hide_setting("bool-setting", "picker-moveable-chests")

hide_setting("bool-setting", "picker-tool-pipe-clamps")

hide_setting("bool-setting", "picker-legacy-belt-fast-replace")
hide_setting("bool-setting", "picker-underground-lengths")
hide_setting("int-setting", "picker-underground-bus-gap")
hide_setting("string-setting", "picker-enhanced-lights")
hide_setting("bool-setting", "picker-brighter-lights-player")
hide_setting("bool-setting", "picker-brighter-lights-vehicles")
-- hide_setting("int-setting", "picker-corpse-time") --время трупов оставим
-- hide_setting("bool-setting", "picker-player-corpse-time")
hide_setting("bool-setting", "picker-clean-tree-burning")
hide_setting("bool-setting", "picker-fireproof-rail-signals")
hide_setting("bool-setting", "picker-generic-vehicle-grids")
hide_setting("bool-setting", "picker-fireproof-rolling-stock")
hide_setting("string-setting", "picker-ghost-tint")
hide_setting("bool-setting", "picker-small-unplugged-icon")
hide_setting("bool-setting", "picker-return-ingredients")
hide_setting("bool-setting", "picker-replace-wood")
hide_setting("bool-setting", "picker-free-circuit-wires")
hide_setting("int-setting", "picker-tile-stack")
hide_setting("string-setting", "picker-iondicators-line")
hide_setting("string-setting", "picker-iondicators-arrow")
hide_setting("bool-setting", "picker-no-artillery-reveal")
hide_setting("bool-setting", "picker-unminable-logistic-robots")
hide_setting("bool-setting", "picker-unminable-construction-robots")
hide_setting("bool-setting", "picker-fireproof-construction-robots")
hide_setting("bool-setting", "picker-noalt-logistic-robots")
-- hide_setting("bool-setting", "picker-noalt-construction-robots") --альт для роботов
-- hide_setting("bool-setting", "picker-noalt-logistic-robots")
hide_setting("double-setting", "picker-adjustable-bot-scale")
hide_setting("bool-setting", "picker-roundup")
hide_setting("bool-setting", "picker-roundup-resources")
hide_setting("double-setting", "picker-belt-sounds")
hide_setting("bool-setting", "picker-smaller-tree-box")
hide_setting("bool-setting", "picker-squeak-through")
hide_setting("bool-setting", "picker-multi-concrete")

hide_setting("int-setting", "picker-manual-withplayer-penalty")
hide_setting("int-setting", "picker-manual-noplayer-penalty")
hide_setting("int-setting", "picker-circuit-penalty")
hide_setting("int-setting", "picker-trainstop-penalty")
hide_setting("int-setting", "picker-arriving-stop-penalty")
hide_setting("int-setting", "picker-train-waitstation-penalty")
hide_setting("int-setting", "picker-train-waitstation-nostops-penalty")
hide_setting("int-setting", "picker-arriving-signal-penalty")
hide_setting("int-setting", "picker-waiting-signal-penalty")
hide_setting("double-setting", "picker-waiting-at-signal-multiplier")
hide_setting("int-setting", "picker-no-path-penalty")
hide_setting("double-setting", "picker-temporary-stop-wait-time")
hide_setting("double-setting", "picker-wait-condition-default")
hide_setting("double-setting", "picker-inactivity-wait-condition-default")
hide_setting("bool-setting", "picker-manual-train-keys")
hide_setting("bool-setting", "picker-get-out-of-the-way")
hide_setting("bool-setting", "picker-better-lights-cars")
hide_setting("bool-setting", "picker-better-lights-trains")
hide_setting("bool-setting", "picker-naked-rails")
hide_setting("bool-setting", "picker-unstoppable-trains")
hide_setting("bool-setting", "picker-auto-manual-train")
hide_setting("bool-setting", "picker-train-honk")
hide_setting("string-setting", "picker-train-honk-type")
hide_setting("bool-setting", "picker-train-honk-attract")

hide_setting("int-setting", "alerts-list-refresh-rate")

hide_setting("double-setting", "qol-crafting-speed-flat-bonus")
hide_setting("bool-setting", "qol-modpack-compatibility-enabled")
hide_setting("bool-setting", "qol-infinite-research-enabled")
hide_setting("bool-setting", "qol-crafting-speed-research-enabled")
hide_setting("double-setting", "qol-crafting-speed-multiplier")
hide_setting("bool-setting", "qol-inventory-size-research-enabled")
hide_setting("bool-setting", "qol-mining-speed-research-enabled")
hide_setting("bool-setting", "qol-movement-speed-research-enabled")
hide_setting("bool-setting", "qol-player-reach-research-enabled")
hide_setting("string-setting", "qol-custom-config")
hide_setting("int-setting", "qol-inventory-size-flat-bonus")
hide_setting("double-setting", "qol-inventory-size-multiplier")
hide_setting("double-setting", "qol-mining-speed-flat-bonus")
hide_setting("double-setting", "qol-mining-speed-multiplier")
hide_setting("double-setting", "qol-movement-speed-flat-bonus")
hide_setting("double-setting", "qol-movement-speed-multiplier")
hide_setting("int-setting", "qol-player-reach-flat-bonus")
hide_setting("double-setting", "qol-player-reach-multiplier")
hide_setting("bool-setting", "qol-player-reach-field-item-drop-distance")
hide_setting("bool-setting", "qol-player-reach-field-resource-reach-distance")

hide_setting("bool-setting", "research-evolution-factor-ignore-inf")
hide_setting("bool-setting", "research-evolution-factor-ignore-qol")

hide_setting("bool-setting", "rso-vanilla-biter-generation")

hide_setting("int-setting", "rsc-st-cost-mp")
hide_setting("bool-setting", "rsc-st-dont-place-tiles")
hide_setting("bool-setting", "rsc-st-not-removable-silo")
hide_setting("bool-setting", "rsc-st-not-removable-site")
hide_setting("int-setting", "rsc-st-work-for-insert-material")
hide_setting("int-setting", "rsc-st-work-for-remove-stone")
hide_setting("bool-setting", "rsc-only-in-alt-mode")

hide_setting("bool-setting", "tankplatoon-tank-to-recipe-keep")
hide_setting("bool-setting", "tankplatoon-tank-t1-enable")
hide_setting("bool-setting", "tankplatoon-tank-t2-enable")
hide_setting("bool-setting", "tankplatoon-ht-RA-enable")
hide_setting("bool-setting", "tankplatoon-repair-pack-enable")
hide_setting("bool-setting", "tankplatoon-concrete-walls-enable")
hide_setting("bool-setting", "tankplatoon-vehicle-energy-shield-enable")
hide_setting("bool-setting", "tankplatoon-vehicle-battery-enable")
hide_setting("bool-setting", "tankplatoon-vehicle-fuel-cell-enable")
hide_setting("bool-setting", "tankplatoon-vehicle-nuclear-reactor-enable")
hide_setting("bool-setting", "tankplatoon-night-vision-enable")
hide_setting("string-setting", "tankplatoon-personal-laser-defense-equipment-energy-consumption")
hide_setting("bool-setting", "tankplatoon-discharge-defense-equipment-automatic")
hide_setting("bool-setting", "tankplatoon-tank-flamethrower-fire-stream-incendiary")
hide_setting("bool-setting", "tankplatoon-ammo-colour-rearrange")
hide_setting("bool-setting", "tankplatoon-chemical-weapon-chemical-recipes")
hide_setting("bool-setting", "tankplatoon-bullet-projectile-enable")
hide_setting("string-setting", "tankplatoon-tank-t0-grid")
hide_setting("string-setting", "tankplatoon-tank-t1-grid")
hide_setting("string-setting", "tankplatoon-tank-t2-grid")
hide_setting("string-setting", "tankplatoon-bullet-force-condition")
hide_setting("string-setting", "tankplatoon-tank-cannon-force-condition")
hide_setting("string-setting", "tankplatoon-tank-autocannon-force-condition")
hide_setting("bool-setting", "tankplatoon-vehicle-hide-resistances")
hide_setting("bool-setting", "tankplatoon-tiered-military-vehicles-subgroups")
hide_setting("string-setting", "tankplatoon-minimap-representation")
hide_setting("bool-setting", "tankplatoon-vehicle-clone-placement-built-enable")
hide_setting("bool-setting", "tankplatoon-vehicle-clone-placement-pasted-enable")
hide_setting("bool-setting", "tankplatoon-tank-to-recipe-force-enable")

hide_setting("bool-setting", "SpaceX-no-popup")
hide_setting("int-setting", "SpaceX-research")
hide_setting("bool-setting", "SpaceX-auto-continue")
hide_setting("int-setting", "SpaceX-production")
hide_setting("string-setting", "SpaceX-launch-profile")
hide_setting("bool-setting", "SpaceX-ignore-tech-multiplier")
hide_setting("bool-setting", "SpaceX-no-space-sci")
hide_setting("bool-setting", "SpaceX-cheaper-fusion-reactor")
hide_setting("bool-setting", "SpaceX-no-bob")

hide_setting("bool-setting", "what-fish-toggle")

hide_setting("bool-setting", "wire-shortcuts-is-retain-wire-crafting")

-- ########################################################################################################################
-- Настройки карты
hide_setting("bool-setting", "paranoidal-disable-vanilla-evolution")

