return
{
  entities =
  {
    {"transport-belt-remnants", {x = -2.5, y = -5.5}, {}},
    {"small-electric-pole-remnants", {x = -0.5, y = -5.5}, {}},
    {"assembling-machine-2-remnants", {x = 4.5, y = -6.5}, {}},
    {"transport-belt", {x = 6.5, y = -5.5}, {dir = "south", dead = 0.3, }},
    {"wooden-chest", {x = -6.5, y = -4.5}, {dead = 0.3, items = {["copper-cable"] = {type = "random", min = 59, max = 140}}, }},
    {"inserter", {x = -6.5, y = -3.5}, {dir = "south", dead = 0.3, }},
    {"small-electric-pole-remnants", {x = -4.5, y = -3.5}, {}},
    {"transport-belt", {x = -2.5, y = -4.5}, {dead = 0.3, }},
    {"transport-belt", {x = -2.5, y = -3.5}, {}},
    {"fast-inserter", {x = -1.5, y = -3.5}, {dir = "east", dead = 0.3, }},
    {"assembling-machine-2", {x = 0.5, y = -3.5}, {recipe = "electronic-circuit", }},
    {"transport-belt", {x = 3.5, y = -3.5}, {dir = "west", }},
    {"fast-inserter", {x = 2.5, y = -3.5}, {dir = "east", }},
    {"fast-inserter", {x = 4.5, y = -4.5}, {dir = "south", dead = 0.3, }},
    {"transport-belt", {x = 4.5, y = -3.5}, {dir = "west", }},
    {"transport-belt", {x = 5.5, y = -3.5}, {dir = "west", dead = 0.3, }},
    {"transport-belt-remnants", {x = 7.5, y = -4.5}, {dir = "south", }},
    {"transport-belt-remnants", {x = 7.5, y = -3.5}, {dir = "south", }},
    {"transport-belt", {x = 6.5, y = -3.5}, {dir = "west", dead = 0.3, }},
    {"transport-belt", {x = 6.5, y = -4.5}, {dir = "south", dead = 0.3, }},
    {"assembling-machine-2", {x = -5.5, y = -1.5}, {dead = 0.3, recipe = "copper-cable", }},
    {"transport-belt", {x = -2.5, y = -2.5}, {dead = 0.3, }},
    {"transport-belt", {x = -2.5, y = -1.5}, {dead = 0.3, }},
    {"fast-inserter", {x = -0.5, y = -1.5}, {dir = "south", }},
    {"small-electric-pole-remnants", {x = 2.5, y = -1.5}, {}},
    {"assembling-machine-2", {x = 6.5, y = -0.5}, {dead = 0.6, }},
    {"inserter-remnants", {x = 7.5, y = -2.5}, {}},
    {"inserter", {x = -5.5, y = 0.5}, {dir = "south", dead = 0.3, }},
    {"transport-belt", {x = -2.5, y = -0.5}, {}},
    {"transport-belt", {x = -2.5, y = 0.5}, {}},
    {"fast-inserter", {x = -1.5, y = 0.5}, {dir = "west", }},
    {"assembling-machine-2", {x = 0.5, y = 0.5}, {recipe = "copper-cable", }},
    {"long-handed-inserter", {x = 3.5, y = -0.5}, {dir = "west", dead = 0.3, }},
    {"assembling-machine-2", {x = 3.5, y = 1.5}, {recipe = "iron-gear-wheel", }},
    {"small-electric-pole-remnants", {x = -7.5, y = 2.5}, {}},
    {"transport-belt-remnants", {x = -7.5, y = 1.5}, {dir = "east", }},
    {"inserter", {x = -6.5, y = 2.5}, {dir = "south", dead = 0.3, }},
    {"transport-belt", {x = -6.5, y = 1.5}, {dir = "east", dead = 0.3, }},
    {"inserter", {x = -5.5, y = 2.5}, {dir = "south", }},
    {"transport-belt", {x = -4.5, y = 1.5}, {dir = "east", }},
    {"transport-belt", {x = -5.5, y = 1.5}, {dir = "east", }},
    {"transport-belt", {x = -2.5, y = 1.5}, {}},
    {"transport-belt", {x = -3.5, y = 1.5}, {dir = "east", dead = 0.3, }},
    {"medium-electric-pole-remnants", {x = -0.5, y = 2.5}, {}},
    {"fast-inserter", {x = 5.5, y = 1.5}, {dir = "east", dead = 0.3, }},
    {"transport-belt-remnants", {x = 7.5, y = 1.5}, {dir = "west", }},
    {"fast-inserter-remnants", {x = 7.5, y = 2.5}, {}},
    {"transport-belt", {x = 6.5, y = 1.5}, {dir = "west", dead = 0.3, }},
    {"steel-furnace", {x = -7, y = 4}, {dead = 0.3, }},
    {"steel-furnace", {x = -5, y = 4}, {}},
    {"assembling-machine-2", {x = -2.5, y = 4.5}, {dead = 0.6, }},
    {"assembling-machine-2", {x = 1.5, y = 4.5}, {}},
    {"transport-belt", {x = 3.5, y = 4.5}, {dir = "south", }},
    {"inserter", {x = 3.5, y = 3.5}, {}},
    {"assembling-machine-2", {x = 6.5, y = 4.5}, {dead = 0.3, recipe = "pipe", }},
    {"transport-belt-remnants", {x = -6.5, y = 6.5}, {dir = "east", }},
    {"inserter", {x = -6.5, y = 5.5}, {dir = "south", dead = 0.3, }},
    {"transport-belt-remnants", {x = -5.5, y = 6.5}, {dir = "east", }},
    {"inserter", {x = -5.5, y = 5.5}, {dir = "south", dead = 0.3, }},
    {"inserter", {x = -2.5, y = 6.5}, {}},
    {"small-electric-pole-remnants", {x = -0.5, y = 6.5}, {}},
    {"inserter", {x = -0.5, y = 5.5}, {dir = "east", }},
    {"inserter", {x = 2.5, y = 6.5}, {dir = "south", dead = 0.3, }},
    {"transport-belt", {x = 3.5, y = 6.5}, {dir = "south", dead = 0.3, }},
    {"transport-belt", {x = 3.5, y = 5.5}, {dir = "south", dead = 0.3, }},
    {"small-electric-pole-remnants", {x = 5.5, y = 6.5}, {}},
    {"long-handed-inserter", {x = 4.5, y = 5.5}, {dir = "east", dead = 0.3, }},
    {"wooden-chest", {x = -2.5, y = 7.5}, {dead = 0.3, items = {car = 1}, }},
    {"transport-belt", {x = 2.5, y = 7.5}, {dir = "west", dead = 0.3, }},
    {"transport-belt", {x = 3.5, y = 7.5}, {dir = "west", dead = 0.3, }},
  },
}
