return
{
  entities =
  {
    {"steel-chest", {x = 5.5, y = -6.5}, {items = {["copper-plate"] = {type = "random", min = 25, max = 100}}}},
    {"steel-chest-remnants", {x = 4.5, y = -6.5}, {dir = "east", }},
    {"steel-chest-remnants", {x = 6.5, y = -6.5}, {dir = "east", }},
    {"inserter", {x = 5.5, y = -5.5}, {dir = "south", }},
    {"inserter", {x = 4.5, y = -5.5}, {dir = "south", }},
    {"inserter", {x = 6.5, y = -5.5}, {dir = "south", }},
    {"transport-belt-remnants", {x = -2.5, y = -3.5}, {dir = "east", }},
    {"car", {x = -2.57, y = -2.02}, {}},
    {"transport-belt-remnants", {x = -0.5, y = -3.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = -1.5, y = -3.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 1.5, y = -3.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 0.5, y = -3.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 2.5, y = -3.5}, {dir = "east", }},
    {"car-remnants", {x = 3.5, y = -3.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 5.5, y = -3.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 4.5, y = -3.5}, {dir = "east", }},
    {"transport-belt", {x = -2.5, y = -0.5}, {}},
    {"transport-belt", {x = -2.5, y = -1.5}, {}},
    {"steel-chest-remnants", {x = 4.5, y = -0.5}, {dir = "east", }},
    {"steel-chest", {x = 5.5, y = -0.5}, {items = {["copper-plate"] = {type = "random", min = 25, max = 100}}}},
    {"inserter", {x = 4.5, y = -1.5}, {}},
    {"inserter", {x = 5.5, y = -1.5}, {}},
    {"medium-electric-pole-remnants", {x = 7.5, y = -1.5}, {}},
    {"steel-chest-remnants", {x = 6.5, y = -0.5}, {dir = "east", }},
    {"inserter", {x = 6.5, y = -1.5}, {}},
    {"transport-belt-remnants", {x = -2.5, y = 1.5}, {}},
    {"transport-belt", {x = -2.5, y = 0.5}, {}},
    {"medium-electric-pole-remnants", {x = -5.5, y = 2.5}, {}},
    {"steel-chest", {x = -5.5, y = 3.5}, {}},
    {"inserter", {x = -4.5, y = 3.5}, {dir = "west", }},
    {"transport-belt-remnants", {x = -2.5, y = 2.5}, {}},
    {"transport-belt-remnants", {x = -2.5, y = 3.5}, {}},
    {"steel-chest", {x = -5.5, y = 4.5}, {items = {["iron-plate"] = {type = "random", min = 25, max = 100}}}},
    {"steel-chest-remnants", {x = -5.5, y = 5.5}, {dir = "east", }},
    {"inserter", {x = -4.5, y = 5.5}, {dir = "west", }},
    {"inserter", {x = -4.5, y = 4.5}, {dir = "west", }},
    {"transport-belt-remnants", {x = -2.5, y = 4.5}, {}},
    {"transport-belt-remnants", {x = -2.5, y = 5.5}, {}},
    {"inserter", {x = -0.5, y = 4.5}, {dir = "east", }},
    {"inserter", {x = -0.5, y = 5.5}, {dir = "east", }},
    {"medium-electric-pole-remnants", {x = 1.5, y = 5.5}, {}},
    {"steel-chest", {x = 0.5, y = 5.5}, {items = {["iron-plate"] = {type = "random", min = 50, max = 200}}}},
    {"steel-chest-remnants", {x = 0.5, y = 4.5}, {dir = "east", }},
    {"steel-chest-remnants", {x = -5.5, y = 6.5}, {dir = "east", }},
    {"inserter", {x = -4.5, y = 6.5}, {dir = "west", }},
    {"car-remnants", {x = -2.5, y = 6.5}, {dir = "east", }},
    {"inserter", {x = -0.5, y = 6.5}, {dir = "east", }},
    {"steel-chest", {x = 0.5, y = 6.5}, {}},
  }
}
