return
{
  entities =
  {
    {"stone-wall", {x = -1.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = -0.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = 0.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = 1.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = 2.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = 3.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = 4.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = 5.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = 6.5, y = -7.5}, {dead = 0.4}},
    {"stone-wall", {x = 6.5, y = -6.5}, {dead = 0.4}},
    {"stone-wall", {x = 6.5, y = -4.5}, {dead = 0.4}},
    {"stone-wall", {x = 6.5, y = -5.5}, {dead = 0.4}},
    {"stone-wall", {x = 6.5, y = -3.5}, {dead = 0.4}},
    {"stone-wall", {x = 6.5, y = -2.5}, {dead = 0.4}},
    {"stone-wall", {x = 6.5, y = -1.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = -1.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = -0.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = 0.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = 1.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = 2.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = 3.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = 4.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = 5.5}, {dead = 0.4}},
    {"stone-wall", {x = -0.5, y = 7.5}, {dead = 0.4}},
    {"stone-wall", {x = -1.5, y = 7.5}, {dead = 0.4}},
    {"gate", {x = 1.5, y = 7.5}, {dir = "east", dead = 0.4}},
    {"stone-wall", {x = 0.5, y = 7.5}, {dead = 0.4}},
    {"gate", {x = 3.5, y = 7.5}, {dir = "east", dead = 0.4}},
    {"gate", {x = 2.5, y = 7.5}, {dir = "east", dead = 0.4}},
    {"gate", {x = 4.5, y = 7.5}, {dir = "east", dead = 0.4}},
    {"stone-wall", {x = 5.5, y = 7.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = 6.5}, {dead = 0.4}},
    {"stone-wall", {x = 7.5, y = 7.5}, {dead = 0.4}},
    {"stone-wall", {x = 6.5, y = 7.5}, {dead = 0.4}},
  },
  tiles =
  {
    {"stone-path", {x = -5, y = -7}},
    {"stone-path", {x = -5, y = -6}},
    {"stone-path", {x = -5, y = -5}},
    {"stone-path", {x = -5, y = -4}},
    {"stone-path", {x = -5, y = -3}},
    {"stone-path", {x = -5, y = -2}},
    {"concrete", {x = -5, y = -1}},
    {"concrete", {x = -5, y = 0}},
    {"concrete", {x = -5, y = 1}},
    {"concrete", {x = -5, y = 2}},
    {"concrete", {x = -5, y = 3}},
    {"concrete", {x = -5, y = 4}},
    {"stone-path", {x = -5, y = 5}},
    {"stone-path", {x = -5, y = 6}},
    {"stone-path", {x = -4, y = -7}},
    {"hazard-concrete-left", {x = -4, y = -6}},
    {"stone-path", {x = -4, y = -5}},
    {"stone-path", {x = -4, y = -4}},
    {"hazard-concrete-left", {x = -4, y = -3}},
    {"hazard-concrete-left", {x = -4, y = -2}},
    {"hazard-concrete-left", {x = -4, y = -1}},
    {"hazard-concrete-left", {x = -4, y = 0}},
    {"hazard-concrete-left", {x = -4, y = 1}},
    {"hazard-concrete-left", {x = -4, y = 2}},
    {"hazard-concrete-left", {x = -4, y = 3}},
    {"stone-path", {x = -4, y = 4}},
    {"stone-path", {x = -4, y = 5}},
    {"stone-path", {x = -4, y = 6}},
    {"stone-path", {x = -3, y = -7}},
    {"stone-path", {x = -3, y = -6}},
    {"stone-path", {x = -3, y = -5}},
    {"hazard-concrete-left", {x = -3, y = -4}},
    {"hazard-concrete-left", {x = -3, y = -3}},
    {"hazard-concrete-left", {x = -3, y = -2}},
    {"hazard-concrete-left", {x = -3, y = -1}},
    {"hazard-concrete-left", {x = -3, y = 0}},
    {"hazard-concrete-left", {x = -3, y = 1}},
    {"hazard-concrete-left", {x = -3, y = 2}},
    {"hazard-concrete-left", {x = -3, y = 3}},
    {"stone-path", {x = -3, y = 4}},
    {"hazard-concrete-left", {x = -3, y = 5}},
    {"concrete", {x = -3, y = 6}},
    {"concrete", {x = -2, y = -7}},
    {"concrete", {x = -2, y = -6}},
    {"concrete", {x = -2, y = -5}},
    {"stone-path", {x = -2, y = -4}},
    {"concrete", {x = -2, y = -3}},
    {"concrete", {x = -2, y = -2}},
    {"hazard-concrete-right", {x = -2, y = -1}},
    {"hazard-concrete-right", {x = -2, y = 0}},
    {"concrete", {x = -2, y = 1}},
    {"concrete", {x = -2, y = 2}},
    {"concrete", {x = -2, y = 3}},
    {"concrete", {x = -2, y = 4}},
    {"concrete", {x = -2, y = 5}},
    {"concrete", {x = -2, y = 6}},
    {"concrete", {x = -1, y = -7}},
    {"stone-path", {x = -1, y = -6}},
    {"concrete", {x = -1, y = -5}},
    {"stone-path", {x = -1, y = -4}},
    {"stone-path", {x = -1, y = -3}},
    {"concrete", {x = -1, y = -2}},
    {"hazard-concrete-right", {x = -1, y = -1}},
    {"hazard-concrete-right", {x = -1, y = 0}},
    {"concrete", {x = -1, y = 1}},
    {"concrete", {x = -1, y = 2}},
    {"stone-path", {x = -1, y = 3}},
    {"stone-path", {x = -1, y = 4}},
    {"stone-path", {x = -1, y = 5}},
    {"concrete", {x = -1, y = 6}},
    {"concrete", {x = 0, y = -7}},
    {"stone-path", {x = 0, y = -6}},
    {"stone-path", {x = 0, y = -5}},
    {"stone-path", {x = 0, y = -4}},
    {"stone-path", {x = 0, y = -3}},
    {"concrete", {x = 0, y = -2}},
    {"hazard-concrete-right", {x = 0, y = -1}},
    {"hazard-concrete-right", {x = 0, y = 0}},
    {"concrete", {x = 0, y = 1}},
    {"concrete", {x = 0, y = 2}},
    {"stone-path", {x = 0, y = 3}},
    {"stone-path", {x = 0, y = 4}},
    {"stone-path", {x = 0, y = 5}},
    {"concrete", {x = 0, y = 6}},
    {"concrete", {x = 1, y = -7}},
    {"stone-path", {x = 1, y = -6}},
    {"stone-path", {x = 1, y = -5}},
    {"concrete", {x = 1, y = -4}},
    {"stone-path", {x = 1, y = -3}},
    {"concrete", {x = 1, y = -2}},
    {"hazard-concrete-right", {x = 1, y = -1}},
    {"hazard-concrete-right", {x = 1, y = 0}},
    {"concrete", {x = 1, y = 1}},
    {"concrete", {x = 1, y = 2}},
    {"concrete", {x = 1, y = 3}},
    {"concrete", {x = 1, y = 4}},
    {"stone-path", {x = 1, y = 5}},
    {"concrete", {x = 1, y = 6}},
    {"concrete", {x = 2, y = -7}},
    {"hazard-concrete-left", {x = 2, y = -6}},
    {"hazard-concrete-left", {x = 2, y = -5}},
    {"hazard-concrete-left", {x = 2, y = -4}},
    {"hazard-concrete-left", {x = 2, y = -3}},
    {"hazard-concrete-left", {x = 2, y = -2}},
    {"hazard-concrete-left", {x = 2, y = -1}},
    {"hazard-concrete-left", {x = 2, y = 0}},
    {"hazard-concrete-left", {x = 2, y = 1}},
    {"hazard-concrete-left", {x = 2, y = 2}},
    {"hazard-concrete-left", {x = 2, y = 3}},
    {"hazard-concrete-left", {x = 2, y = 4}},
    {"hazard-concrete-left", {x = 2, y = 5}},
    {"concrete", {x = 2, y = 6}},
    {"concrete", {x = 3, y = -7}},
    {"hazard-concrete-left", {x = 3, y = -6}},
    {"hazard-concrete-left", {x = 3, y = -5}},
    {"concrete", {x = 3, y = -4}},
    {"concrete", {x = 3, y = -3}},
    {"concrete", {x = 3, y = -2}},
    {"hazard-concrete-left", {x = 3, y = -1}},
    {"hazard-concrete-left", {x = 3, y = 0}},
    {"stone-path", {x = 3, y = 1}},
    {"stone-path", {x = 3, y = 2}},
    {"hazard-concrete-left", {x = 3, y = 3}},
    {"hazard-concrete-left", {x = 3, y = 4}},
    {"hazard-concrete-left", {x = 3, y = 5}},
    {"concrete", {x = 3, y = 6}},
    {"concrete", {x = 4, y = -7}},
    {"concrete", {x = 4, y = -6}},
    {"concrete", {x = 4, y = -5}},
    {"concrete", {x = 4, y = -4}},
    {"concrete", {x = 4, y = -3}},
    {"stone-path", {x = 4, y = -2}},
    {"stone-path", {x = 4, y = -1}},
    {"stone-path", {x = 4, y = 0}},
    {"stone-path", {x = 4, y = 1}},
    {"stone-path", {x = 4, y = 2}},
    {"concrete", {x = 4, y = 3}},
    {"concrete", {x = 4, y = 4}},
    {"concrete", {x = 4, y = 5}},
    {"concrete", {x = 4, y = 6}},
  }
}
