return
{
  entities =
  {
    {"stone-wall", {x = -2.5, y = -4.5}, {}},
    {"stone-wall", {x = -1.5, y = -4.5}, {}},
    {"land-mine", {x = 1.94, y = -4.02}, {force = "enemy", }},
    {"stone-wall", {x = 1.5, y = -5.5}, {}},
    {"stone-wall", {x = -6.5, y = -3.5}, {}},
    {"land-mine", {x = -2.79, y = -3.04}, {force = "enemy", }},
    {"stone-wall", {x = -1.5, y = -3.5}, {}},
    {"stone-wall", {x = 3.5, y = -3.5}, {}},
    {"stone-wall", {x = 3.5, y = -2.5}, {}},
    {"stone-wall", {x = 2.5, y = -2.5}, {}},
    {"stone-wall", {x = 6.5, y = -2.5}, {}},
    {"stone-wall", {x = -2.5, y = -0.5}, {}},
    {"stone-wall", {x = -3.5, y = -0.5}, {}},
    {"stone-wall", {x = 0.5, y = -1.5}, {}},
    {"stone-wall", {x = 5.5, y = -0.5}, {}},
    {"land-mine", {x = 6.35, y = -0.34}, {force = "enemy", }},
    {"stone-wall", {x = -2.5, y = 0.5}, {}},
    {"stone-wall", {x = -1.5, y = 0.5}, {}},
    {"stone-wall", {x = 1.5, y = 1.5}, {}},
    {"stone-wall", {x = 3.5, y = 0.5}, {}},
    {"stone-wall", {x = 2.5, y = 0.5}, {}},
    {"stone-wall", {x = 5.5, y = 1.5}, {}},
    {"stone-wall", {x = -5.5, y = 2.5}, {}},
    {"stone-wall", {x = -2.5, y = 3.5}, {}},
    {"stone-wall", {x = -0.5, y = 3.5}, {}},
    {"stone-wall", {x = -1.5, y = 3.5}, {}},
    {"stone-wall", {x = 0.5, y = 3.5}, {}},
    {"stone-wall", {x = 2.5, y = 3.5}, {}},
    {"stone-wall", {x = -5.5, y = 5.5}, {}},
    {"land-mine", {x = -2.84, y = 4.43}, {force = "enemy", }},
    {"stone-wall", {x = -3.5, y = 4.5}, {}},
    {"stone-wall", {x = 2.5, y = 4.5}, {}},
    {"stone-wall", {x = 2.5, y = 5.5}, {}},
    {"stone-wall", {x = 5.5, y = 4.5}, {}},
  },
  tiles =
  {
    {"concrete", {x = -7, y = -6}},
    {"concrete", {x = -7, y = -5}},
    {"concrete", {x = -7, y = -4}},
    {"concrete", {x = -7, y = -3}},
    {"concrete", {x = -7, y = -2}},
    {"concrete", {x = -7, y = -1}},
    {"concrete", {x = -7, y = 0}},
    {"concrete", {x = -7, y = 1}},
    {"concrete", {x = -7, y = 2}},
    {"concrete", {x = -7, y = 3}},
    {"concrete", {x = -7, y = 4}},
    {"concrete", {x = -7, y = 5}},
    {"concrete", {x = -7, y = 6}},
    {"concrete", {x = -6, y = -6}},
    {"concrete", {x = -6, y = -5}},
    {"concrete", {x = -6, y = -4}},
    {"concrete", {x = -6, y = -3}},
    {"concrete", {x = -6, y = -2}},
    {"concrete", {x = -6, y = -1}},
    {"concrete", {x = -6, y = 0}},
    {"concrete", {x = -6, y = 1}},
    {"concrete", {x = -6, y = 2}},
    {"concrete", {x = -6, y = 3}},
    {"concrete", {x = -6, y = 4}},
    {"concrete", {x = -6, y = 5}},
    {"concrete", {x = -6, y = 6}},
    {"concrete", {x = -5, y = -6}},
    {"concrete", {x = -5, y = -5}},
    {"concrete", {x = -5, y = -4}},
    {"concrete", {x = -5, y = -3}},
    {"concrete", {x = -5, y = -2}},
    {"concrete", {x = -5, y = -1}},
    {"concrete", {x = -5, y = 0}},
    {"concrete", {x = -5, y = 1}},
    {"concrete", {x = -5, y = 2}},
    {"concrete", {x = -5, y = 3}},
    {"concrete", {x = -5, y = 4}},
    {"concrete", {x = -5, y = 5}},
    {"concrete", {x = -5, y = 6}},
    {"concrete", {x = -4, y = -6}},
    {"concrete", {x = -4, y = -5}},
    {"concrete", {x = -4, y = -4}},
    {"concrete", {x = -4, y = -3}},
    {"concrete", {x = -4, y = -2}},
    {"concrete", {x = -4, y = -1}},
    {"concrete", {x = -4, y = 0}},
    {"concrete", {x = -4, y = 1}},
    {"concrete", {x = -4, y = 2}},
    {"concrete", {x = -4, y = 3}},
    {"concrete", {x = -4, y = 4}},
    {"concrete", {x = -4, y = 5}},
    {"concrete", {x = -4, y = 6}},
    {"concrete", {x = -3, y = -6}},
    {"concrete", {x = -3, y = -5}},
    {"concrete", {x = -3, y = -4}},
    {"concrete", {x = -3, y = -3}},
    {"concrete", {x = -3, y = -2}},
    {"concrete", {x = -3, y = -1}},
    {"concrete", {x = -3, y = 0}},
    {"concrete", {x = -3, y = 1}},
    {"concrete", {x = -3, y = 2}},
    {"concrete", {x = -3, y = 3}},
    {"concrete", {x = -3, y = 4}},
    {"concrete", {x = -3, y = 5}},
    {"concrete", {x = -3, y = 6}},
    {"concrete", {x = -2, y = -6}},
    {"concrete", {x = -2, y = -5}},
    {"concrete", {x = -2, y = -4}},
    {"concrete", {x = -2, y = -3}},
    {"concrete", {x = -2, y = -2}},
    {"concrete", {x = -2, y = -1}},
    {"concrete", {x = -2, y = 0}},
    {"concrete", {x = -2, y = 1}},
    {"concrete", {x = -2, y = 2}},
    {"concrete", {x = -2, y = 3}},
    {"concrete", {x = -2, y = 4}},
    {"concrete", {x = -2, y = 5}},
    {"concrete", {x = -2, y = 6}},
    {"concrete", {x = -1, y = -6}},
    {"concrete", {x = -1, y = -5}},
    {"concrete", {x = -1, y = -4}},
    {"concrete", {x = -1, y = -3}},
    {"concrete", {x = -1, y = -2}},
    {"concrete", {x = -1, y = -1}},
    {"concrete", {x = -1, y = 0}},
    {"concrete", {x = -1, y = 1}},
    {"concrete", {x = -1, y = 2}},
    {"concrete", {x = -1, y = 3}},
    {"concrete", {x = -1, y = 4}},
    {"concrete", {x = -1, y = 5}},
    {"concrete", {x = -1, y = 6}},
    {"concrete", {x = 0, y = -6}},
    {"concrete", {x = 0, y = -5}},
    {"concrete", {x = 0, y = -4}},
    {"concrete", {x = 0, y = -3}},
    {"concrete", {x = 0, y = -2}},
    {"concrete", {x = 0, y = -1}},
    {"concrete", {x = 0, y = 0}},
    {"concrete", {x = 0, y = 1}},
    {"concrete", {x = 0, y = 2}},
    {"concrete", {x = 0, y = 3}},
    {"concrete", {x = 0, y = 4}},
    {"concrete", {x = 0, y = 5}},
    {"concrete", {x = 0, y = 6}},
    {"concrete", {x = 1, y = -6}},
    {"concrete", {x = 1, y = -5}},
    {"concrete", {x = 1, y = -4}},
    {"concrete", {x = 1, y = -3}},
    {"concrete", {x = 1, y = -2}},
    {"concrete", {x = 1, y = -1}},
    {"concrete", {x = 1, y = 0}},
    {"concrete", {x = 1, y = 1}},
    {"concrete", {x = 1, y = 2}},
    {"concrete", {x = 1, y = 3}},
    {"concrete", {x = 1, y = 4}},
    {"concrete", {x = 1, y = 5}},
    {"concrete", {x = 1, y = 6}},
    {"concrete", {x = 2, y = -6}},
    {"concrete", {x = 2, y = -5}},
    {"concrete", {x = 2, y = -4}},
    {"concrete", {x = 2, y = -3}},
    {"concrete", {x = 2, y = -2}},
    {"concrete", {x = 2, y = -1}},
    {"concrete", {x = 2, y = 0}},
    {"concrete", {x = 2, y = 1}},
    {"concrete", {x = 2, y = 2}},
    {"concrete", {x = 2, y = 3}},
    {"concrete", {x = 2, y = 4}},
    {"concrete", {x = 2, y = 5}},
    {"concrete", {x = 2, y = 6}},
    {"concrete", {x = 3, y = -6}},
    {"concrete", {x = 3, y = -5}},
    {"concrete", {x = 3, y = -4}},
    {"concrete", {x = 3, y = -3}},
    {"concrete", {x = 3, y = -2}},
    {"concrete", {x = 3, y = -1}},
    {"concrete", {x = 3, y = 0}},
    {"concrete", {x = 3, y = 1}},
    {"concrete", {x = 3, y = 2}},
    {"concrete", {x = 3, y = 3}},
    {"concrete", {x = 3, y = 4}},
    {"concrete", {x = 3, y = 5}},
    {"concrete", {x = 3, y = 6}},
    {"concrete", {x = 4, y = -6}},
    {"concrete", {x = 4, y = -5}},
    {"concrete", {x = 4, y = -4}},
    {"concrete", {x = 4, y = -3}},
    {"concrete", {x = 4, y = -2}},
    {"concrete", {x = 4, y = -1}},
    {"concrete", {x = 4, y = 0}},
    {"concrete", {x = 4, y = 1}},
    {"concrete", {x = 4, y = 2}},
    {"concrete", {x = 4, y = 3}},
    {"concrete", {x = 4, y = 4}},
    {"concrete", {x = 4, y = 5}},
    {"concrete", {x = 4, y = 6}},
    {"concrete", {x = 5, y = -6}},
    {"concrete", {x = 5, y = -5}},
    {"concrete", {x = 5, y = -4}},
    {"concrete", {x = 5, y = -3}},
    {"concrete", {x = 5, y = -2}},
    {"concrete", {x = 5, y = -1}},
    {"concrete", {x = 5, y = 0}},
    {"concrete", {x = 5, y = 1}},
    {"concrete", {x = 5, y = 2}},
    {"concrete", {x = 5, y = 3}},
    {"concrete", {x = 5, y = 4}},
    {"concrete", {x = 5, y = 5}},
    {"concrete", {x = 5, y = 6}},
    {"concrete", {x = 6, y = -6}},
    {"concrete", {x = 6, y = -5}},
    {"concrete", {x = 6, y = -4}},
    {"concrete", {x = 6, y = -3}},
    {"concrete", {x = 6, y = -2}},
    {"concrete", {x = 6, y = -1}},
    {"concrete", {x = 6, y = 0}},
    {"concrete", {x = 6, y = 1}},
    {"concrete", {x = 6, y = 2}},
    {"concrete", {x = 6, y = 3}},
    {"concrete", {x = 6, y = 4}},
    {"concrete", {x = 6, y = 5}},
    {"concrete", {x = 6, y = 6}},
    {"concrete", {x = 7, y = -6}},
    {"concrete", {x = 7, y = -5}},
    {"concrete", {x = 7, y = -4}},
    {"concrete", {x = 7, y = -3}},
    {"concrete", {x = 7, y = -2}},
    {"concrete", {x = 7, y = -1}},
    {"concrete", {x = 7, y = 0}},
    {"concrete", {x = 7, y = 1}},
    {"concrete", {x = 7, y = 2}},
    {"concrete", {x = 7, y = 3}},
    {"concrete", {x = 7, y = 4}},
    {"concrete", {x = 7, y = 5}},
    {"concrete", {x = 7, y = 6}},
  }
}
