return
{
  entities =
  {
    {"storage-tank-remnants", {x = -6.5, y = -6.5}, {dir = "east", }},
    {"fish", {x = -3.05, y = -4.86}, {}},
    {"fish", {x = -2.09, y = -4.65}, {}},
    {"pipe", {x = 1.5, y = -6.5}, {}},
    {"pipe-remnants", {x = 3.5, y = -7.5}, {}},
    {"pipe", {x = 3.5, y = -6.5}, {}},
    {"pipe", {x = 2.5, y = -6.5}, {}},
    {"pipe-remnants", {x = -7.5, y = -4.5}, {}},
    {"pipe-to-ground", {x = 1.5, y = -5.5}, {}},
    {"pipe-to-ground-remnants", {x = -7.5, y = -3.5}, {dir = "west", }},
    {"fish", {x = 2.95, y = 0.37}, {}},
    {"pipe-to-ground", {x = -7.5, y = -0.5}, {dir = "south", }},
    {"heat-exchanger", {x = -6, y = 0.5}, {dir = "west", }},
    {"medium-electric-pole-remnants", {x = -4.5, y = -1.5}, {dir = "east", }},
    {"fish", {x = -3.25, y = 2.88}, {}},
    {"pipe-to-ground-remnants", {x = 1.5, y = -1.5}, {dir = "south", }},
    {"centrifuge-remnants", {x = 0.5, y = -0.5}, {dir = "east", }},
    {"fish", {x = 4.48, y = 1.51}, {}},
    {"pipe", {x = -7.5, y = 0.5}, {}},
    {"heat-pipe", {x = -4.5, y = 1.5}, {}},
    {"heat-pipe", {x = -4.5, y = 0.5}, {}},
    {"heat-pipe", {x = -4.5, y = 2.5}, {}},
    {"heat-pipe", {x = -5.5, y = 3.5}, {}},
    {"heat-pipe", {x = -4.5, y = 3.5}, {}},
    {"fish", {x = 3.87, y = 6.25}, {}},
    {"heat-pipe", {x = -5.5, y = 5.5}, {}},
    {"heat-pipe-remnants", {x = -5.5, y = 4.5}, {}},
    {"heat-pipe-remnants", {x = -5.5, y = 6.5}, {}},
    {"heat-pipe-remnants", {x = -4.5, y = 6.5}, {dir = "south", }},
    {"heat-pipe-remnants", {x = -3.5, y = 6.5}, {dir = "south", }},
  },
  tiles =
  {
    {"water-green", {x = -7, y = -5}},
    {"water-green", {x = -7, y = -4}},
    {"water-green", {x = -7, y = -3}},
    {"stone-path", {x = -7, y = -2}},
    {"stone-path", {x = -7, y = -1}},
    {"stone-path", {x = -7, y = 0}},
    {"water-green", {x = -6, y = -5}},
    {"water-green", {x = -6, y = -4}},
    {"water-green", {x = -6, y = -3}},
    {"stone-path", {x = -6, y = -2}},
    {"stone-path", {x = -6, y = -1}},
    {"water-green", {x = -5, y = -8}},
    {"water-green", {x = -5, y = -7}},
    {"water-green", {x = -5, y = -6}},
    {"water-green", {x = -5, y = -5}},
    {"water-green", {x = -5, y = -4}},
    {"water-green", {x = -5, y = -3}},
    {"stone-path", {x = -5, y = -2}},
    {"water-green", {x = -4, y = -8}},
    {"water-green", {x = -4, y = -7}},
    {"water-green", {x = -4, y = -6}},
    {"water-green", {x = -4, y = -5}},
    {"water-green", {x = -4, y = -4}},
    {"water-green", {x = -4, y = -3}},
    {"deepwater-green", {x = -4, y = -2}},
    {"deepwater-green", {x = -4, y = -1}},
    {"water-green", {x = -4, y = 0}},
    {"water-green", {x = -4, y = 1}},
    {"water-green", {x = -4, y = 2}},
    {"water-green", {x = -4, y = 3}},
    {"water-green", {x = -3, y = -8}},
    {"water-green", {x = -3, y = -7}},
    {"water-green", {x = -3, y = -6}},
    {"water-green", {x = -3, y = -5}},
    {"water-green", {x = -3, y = -4}},
    {"water-green", {x = -3, y = -3}},
    {"deepwater-green", {x = -3, y = -2}},
    {"deepwater-green", {x = -3, y = -1}},
    {"deepwater-green", {x = -3, y = 0}},
    {"deepwater-green", {x = -3, y = 1}},
    {"deepwater-green", {x = -3, y = 2}},
    {"water-green", {x = -3, y = 3}},
    {"water-green", {x = -3, y = 4}},
    {"water-green", {x = -2, y = -7}},
    {"water-green", {x = -2, y = -6}},
    {"water-green", {x = -2, y = -5}},
    {"water-green", {x = -2, y = -4}},
    {"deepwater-green", {x = -2, y = -3}},
    {"deepwater-green", {x = -2, y = -2}},
    {"deepwater-green", {x = -2, y = -1}},
    {"deepwater-green", {x = -2, y = 0}},
    {"deepwater-green", {x = -2, y = 1}},
    {"deepwater-green", {x = -2, y = 2}},
    {"deepwater-green", {x = -2, y = 3}},
    {"water-green", {x = -2, y = 4}},
    {"water-green", {x = -1, y = -7}},
    {"water-green", {x = -1, y = -6}},
    {"water-green", {x = -1, y = -5}},
    {"deepwater-green", {x = -1, y = -4}},
    {"deepwater-green", {x = -1, y = -3}},
    {"stone-path", {x = -1, y = -2}},
    {"stone-path", {x = -1, y = -1}},
    {"stone-path", {x = -1, y = 0}},
    {"deepwater-green", {x = -1, y = 1}},
    {"deepwater-green", {x = -1, y = 2}},
    {"water-green", {x = -1, y = 3}},
    {"water-green", {x = -1, y = 4}},
    {"water-green", {x = -1, y = 5}},
    {"water-green", {x = -1, y = 6}},
    {"water-green", {x = -1, y = 7}},
    {"water-green", {x = 0, y = -8}},
    {"water-green", {x = 0, y = -7}},
    {"water-green", {x = 0, y = -6}},
    {"water-green", {x = 0, y = -5}},
    {"deepwater-green", {x = 0, y = -4}},
    {"deepwater-green", {x = 0, y = -3}},
    {"stone-path", {x = 0, y = -2}},
    {"stone-path", {x = 0, y = -1}},
    {"stone-path", {x = 0, y = 0}},
    {"deepwater-green", {x = 0, y = 1}},
    {"deepwater-green", {x = 0, y = 2}},
    {"water-green", {x = 0, y = 3}},
    {"water-green", {x = 0, y = 4}},
    {"water-green", {x = 0, y = 5}},
    {"water-green", {x = 0, y = 6}},
    {"water-green", {x = 0, y = 7}},
    {"water-green", {x = 1, y = -8}},
    {"stone-path", {x = 1, y = -7}},
    {"stone-path", {x = 1, y = -6}},
    {"water-green", {x = 1, y = -5}},
    {"water-green", {x = 1, y = -4}},
    {"deepwater-green", {x = 1, y = -3}},
    {"stone-path", {x = 1, y = -2}},
    {"stone-path", {x = 1, y = -1}},
    {"stone-path", {x = 1, y = 0}},
    {"deepwater-green", {x = 1, y = 1}},
    {"deepwater-green", {x = 1, y = 2}},
    {"water-green", {x = 1, y = 3}},
    {"water-green", {x = 1, y = 4}},
    {"water-green", {x = 1, y = 5}},
    {"water-green", {x = 1, y = 6}},
    {"water-green", {x = 1, y = 7}},
    {"water-green", {x = 2, y = -8}},
    {"stone-path", {x = 2, y = -7}},
    {"stone-path", {x = 2, y = -6}},
    {"water-green", {x = 2, y = -5}},
    {"water-green", {x = 2, y = -4}},
    {"deepwater-green", {x = 2, y = -3}},
    {"deepwater-green", {x = 2, y = -2}},
    {"deepwater-green", {x = 2, y = -1}},
    {"deepwater-green", {x = 2, y = 0}},
    {"deepwater-green", {x = 2, y = 1}},
    {"deepwater-green", {x = 2, y = 2}},
    {"water-green", {x = 2, y = 3}},
    {"water-green", {x = 2, y = 4}},
    {"water-green", {x = 2, y = 5}},
    {"water-green", {x = 2, y = 6}},
    {"water-green", {x = 2, y = 7}},
    {"stone-path", {x = 3, y = -7}},
    {"stone-path", {x = 3, y = -6}},
    {"water-green", {x = 3, y = -5}},
    {"water-green", {x = 3, y = -4}},
    {"water-green", {x = 3, y = -3}},
    {"water-green", {x = 3, y = -2}},
    {"deepwater-green", {x = 3, y = -1}},
    {"deepwater-green", {x = 3, y = 0}},
    {"deepwater-green", {x = 3, y = 1}},
    {"deepwater-green", {x = 3, y = 2}},
    {"water-green", {x = 3, y = 3}},
    {"water-green", {x = 3, y = 4}},
    {"water-green", {x = 3, y = 5}},
    {"water-green", {x = 3, y = 6}},
    {"water-green", {x = 4, y = -7}},
    {"water-green", {x = 4, y = -6}},
    {"water-green", {x = 4, y = -5}},
    {"water-green", {x = 4, y = -4}},
    {"water-green", {x = 4, y = -3}},
    {"water-green", {x = 4, y = -2}},
    {"water-green", {x = 4, y = -1}},
    {"deepwater-green", {x = 4, y = 0}},
    {"water-green", {x = 4, y = 1}},
    {"water-green", {x = 4, y = 2}},
    {"water-green", {x = 4, y = 3}},
    {"water-green", {x = 4, y = 4}},
    {"water-green", {x = 4, y = 5}},
    {"water-green", {x = 4, y = 6}},
    {"water-green", {x = 5, y = -7}},
    {"water-green", {x = 5, y = -6}},
    {"water-green", {x = 5, y = -5}},
    {"water-green", {x = 5, y = -4}},
    {"water-green", {x = 5, y = -3}},
    {"water-green", {x = 5, y = -2}},
    {"water-green", {x = 5, y = -1}},
    {"water-green", {x = 5, y = 0}},
    {"water-green", {x = 5, y = 1}},
    {"water-green", {x = 5, y = 2}},
    {"water-green", {x = 5, y = 3}},
    {"water-green", {x = 5, y = 4}},
    {"water-green", {x = 5, y = 5}},
    {"water-green", {x = 5, y = 6}},
    {"water-green", {x = 6, y = -5}},
    {"water-green", {x = 6, y = -4}},
    {"water-green", {x = 6, y = -2}},
    {"water-green", {x = 6, y = -1}},
    {"water-green", {x = 6, y = 0}},
    {"water-green", {x = 6, y = 1}},
    {"water-green", {x = 6, y = 2}},
    {"water-green", {x = 6, y = 4}},
    {"water-green", {x = 6, y = 5}},
  }
}
