-- Approved thematic Components menu; recipe placement/icons only.
return {
    rows = {
        {subgroup = "paranoidal-components-mechanics", order = "a-01", recipes = {
            {["name"] = "iron-gear-wheel", ["order"] = "01"},
            {["name"] = "motor", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/00ec0cffebec2ffa866e.png", ["icon_size"] = 64}},
            {["name"] = "electric-motor", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/184f829f74ef5c5d13ce.png", ["icon_size"] = 64}},
            {["name"] = "engine-unit", ["order"] = "04"},
            {["name"] = "electric-engine-unit", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/6a8b0a6f881b156d672a.png", ["icon_size"] = 256}},
        }},
        {subgroup = "paranoidal-components-gears", order = "a-02", recipes = {
            {["name"] = "bob-steel-gear-wheel", ["order"] = "01"},
            {["name"] = "bob-cobalt-steel-gear-wheel", ["order"] = "02"},
            {["name"] = "bob-brass-gear-wheel", ["order"] = "03"},
            {["name"] = "bob-titanium-gear-wheel", ["order"] = "04"},
            {["name"] = "bob-tungsten-gear-wheel", ["order"] = "05"},
            {["name"] = "bob-nitinol-gear-wheel", ["order"] = "06"},
        }},
        {subgroup = "paranoidal-components-bearings", order = "a-03", recipes = {
            {["name"] = "bob-steel-bearing-ball", ["order"] = "01"},
            {["name"] = "bob-brass-bearing-ball", ["order"] = "02"},
            {["name"] = "bob-cobalt-steel-bearing-ball", ["order"] = "03"},
            {["name"] = "bob-titanium-bearing-ball", ["order"] = "04"},
            {["name"] = "bob-nitinol-bearing-ball", ["order"] = "05"},
            {["name"] = "bob-steel-bearing", ["order"] = "06"},
            {["name"] = "bob-brass-bearing", ["order"] = "07"},
            {["name"] = "bob-cobalt-steel-bearing", ["order"] = "08"},
            {["name"] = "bob-titanium-bearing", ["order"] = "09"},
            {["name"] = "bob-nitinol-bearing", ["order"] = "10"},
        }},
        {subgroup = "paranoidal-components-pressed-wood", order = "a-04", recipes = {
            {["name"] = "bi-press-wood", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/779a60a95a76ca7a70ae.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-board-bases", order = "a-05", recipes = {
            {["name"] = "bob-wooden-board", ["order"] = "01"},
            {["name"] = "bob-phenolic-board", ["order"] = "02"},
            {["name"] = "angels-glass-fiber-board", ["order"] = "03", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/2709ca12883b0d1c3776.png", ["icon_size"] = 64, ["scale"] = 0.5, ["shift"] = {0, 0}}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/f86e071b33bd0efdcf54.png", ["icon_size"] = 64, ["scale"] = 0.21875, ["shift"] = {-10, -10}}}}},
        }},
        {subgroup = "paranoidal-components-circuit-boards", order = "a-06", recipes = {
            {["name"] = "bob-circuit-board", ["order"] = "01"},
            {["name"] = "bob-superior-circuit-board", ["order"] = "02"},
            {["name"] = "bob-multi-layer-circuit-board", ["order"] = "03"},
        }},
        {subgroup = "paranoidal-components-electronics", order = "a-07", recipes = {
            {["name"] = "bob-basic-electronic-components", ["order"] = "01"},
            {["name"] = "bob-electronic-components", ["order"] = "02"},
            {["name"] = "bob-integrated-electronics", ["order"] = "03"},
            {["name"] = "bob-processing-electronics", ["order"] = "04"},
        }},
        {subgroup = "paranoidal-components-capacitors", order = "a-08", recipes = {
            {["name"] = "condensator", ["order"] = "01"},
            {["name"] = "condensator2", ["order"] = "02"},
            {["name"] = "condensator3", ["order"] = "03"},
        }},
        {subgroup = "paranoidal-components-circuits", order = "a-09", recipes = {
            {["name"] = "bob-basic-circuit-board", ["order"] = "01"},
            {["name"] = "electronic-circuit-wood", ["order"] = "02"},
            {["name"] = "advanced-circuit", ["order"] = "03"},
            {["name"] = "processing-unit", ["order"] = "04"},
            {["name"] = "bob-advanced-processing-unit", ["order"] = "05"},
        }},
        {subgroup = "paranoidal-components-space-parts", order = "a-10", recipes = {
            {["name"] = "bob-heat-shield-tile", ["order"] = "01"},
            {["name"] = "rocket-control-circuit", ["order"] = "02"},
        }},
        {subgroup = "paranoidal-components-structures", order = "a-11", recipes = {
            {["name"] = "basic-structure-components", ["order"] = "01"},
            {["name"] = "intermediate-structure-components", ["order"] = "02"},
            {["name"] = "advanced-structure-components", ["order"] = "03"},
            {["name"] = "anotherworld-structure-components", ["order"] = "04"},
        }},
        {subgroup = "paranoidal-components-drill-bits", order = "a-12", recipes = {
            {["name"] = "mining-drill-bit-mk0", ["order"] = "01"},
            {["name"] = "mining-drill-bit-mk1", ["order"] = "02"},
            {["name"] = "mining-drill-bit-mk2", ["order"] = "03"},
            {["name"] = "mining-drill-bit-mk3", ["order"] = "04"},
            {["name"] = "mining-drill-bit-mk4", ["order"] = "05"},
            {["name"] = "mining-drill-bit-mk5", ["order"] = "06"},
        }},
        {subgroup = "paranoidal-components-batteries", order = "a-13", recipes = {
            {["name"] = "battery", ["order"] = "01", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a68887654b3402e42253.png", ["icon_size"] = 64}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a8bfdf24295dd8331487.png", ["tint"] = {["r"] = 1, ["g"] = 0.7176470588235294, ["b"] = 0.14901960784313725}, ["icon_size"] = 64}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/710fff5e2119e0afc4ea.png", ["tint"] = {1, 1, 1, 0}, ["icon_size"] = 64}}}},
            {["name"] = "bob-battery-2", ["order"] = "02", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a68887654b3402e42253.png", ["icon_size"] = 64}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a8bfdf24295dd8331487.png", ["tint"] = {["r"] = 0.9490196078431372, ["g"] = 0.13725490196078433, ["b"] = 0.09411764705882353}, ["icon_size"] = 64}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/710fff5e2119e0afc4ea.png", ["tint"] = {1, 1, 1, 0}, ["icon_size"] = 64}}}},
            {["name"] = "bob-battery-3", ["order"] = "03", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a68887654b3402e42253.png", ["icon_size"] = 64}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a8bfdf24295dd8331487.png", ["tint"] = {["r"] = 0.2, ["g"] = 0.7058823529411765, ["b"] = 1}, ["icon_size"] = 64}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/710fff5e2119e0afc4ea.png", ["tint"] = {1, 1, 1, 0}, ["icon_size"] = 64}}}},
            {["name"] = "bob-rtg", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/032bbb9ff468bd1522de.png", ["icon_size"] = 128}},
        }},
        {subgroup = "paranoidal-components-train-batteries", order = "a-14", recipes = {
            {["name"] = "bet-fuel-1-empty", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a23378df33942d81cd0f.png", ["icon_size"] = 64}},
            {["name"] = "bet-fuel-2-empty", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/c9730450e080f917f04a.png", ["icon_size"] = 64}},
            {["name"] = "bet-fuel-3-empty", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/d6527d64ba621cc07d3c.png", ["icon_size"] = 64}},
            {["name"] = "bet-fuel-4-empty", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/316dc14bcb23f788ed76.png", ["icon_size"] = 64}},
            {["name"] = "bet-fuel-1-full", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/75b7b3a53d8ea89a610c.png", ["icon_size"] = 64}},
            {["name"] = "bet-fuel-2-full", ["order"] = "06", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/e0375bc9be01d368e9bb.png", ["icon_size"] = 64}},
            {["name"] = "bet-fuel-3-full", ["order"] = "07", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/ceb061b3cbd84b5cd023.png", ["icon_size"] = 64}},
            {["name"] = "bet-fuel-4-full", ["order"] = "08", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/149e2c2e7fede55b02ce.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-filters", order = "a-15", recipes = {
            {["name"] = "CW-air-filter", ["order"] = "01"},
            {["name"] = "CW-air-filter-cleaning-1", ["order"] = "02"},
            {["name"] = "CW-air-filter-cleaning-2", ["order"] = "03"},
            {["name"] = "CW-air-filter-cleaning-3", ["order"] = "04"},
            {["name"] = "CW-air-filter-cleaning-4", ["order"] = "05"},
            {["name"] = "CW-empty-air-filter", ["order"] = "06"},
        }},
        {subgroup = "paranoidal-components-diesel", order = "a-16", recipes = {
            {["name"] = "diesel-fuel", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/ebb045be7aeff4b951f1.png", ["icon_size"] = 32}},
        }},
        {subgroup = "paranoidal-components-ore-processing", order = "a-17", recipes = {
            {["name"] = "uranium-processing", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/bcbb5a28c7e28a75111e.png", ["icon_size"] = 64}},
            {["name"] = "thorium-processing", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/9d3f6e25ea1e46283e6d.png", ["icon_size"] = 32}},
        }},
        {subgroup = "paranoidal-components-enrichment", order = "a-18", recipes = {
            {["name"] = "depleted-uranium-reprocessing", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/609eab21b337a5b6e78c.png", ["icon_size"] = 32}},
            {["name"] = "clowns-centrifuging-20pc-ore", ["order"] = "02", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/da2a4bf3173c20b4b995.png", ["scale"] = 1, ["shift"] = {0, 0}, ["icon_size"] = 32}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/95bbe2b67acc7fac3142.png", ["icon_size"] = 64, ["scale"] = 0.25, ["shift"] = {-8, -8}}}}},
            {["name"] = "clowns-centrifuging-20pc-hexafluoride", ["order"] = "03", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/da2a4bf3173c20b4b995.png", ["scale"] = 1, ["shift"] = {0, 0}, ["icon_size"] = 32}, {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a9b1894222cfbc24f2af.png", ["scale"] = 0.5, ["shift"] = {-8, -8}, ["icon_size"] = 32}}}},
            {["name"] = "clowns-centrifuging-35pc", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/097b2d36d52e5c429fde.png", ["icon_size"] = 32}},
            {["name"] = "clowns-centrifuging-45pc", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/0145292b3a8c41a14430.png", ["icon_size"] = 32}},
            {["name"] = "clowns-centrifuging-55pc", ["order"] = "06", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/7f684789cbeac633c1a4.png", ["icon_size"] = 32}},
            {["name"] = "clowns-centrifuging-65pc", ["order"] = "07", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/f5add3266774b560401e.png", ["icon_size"] = 32}},
            {["name"] = "clowns-centrifuging-70pc", ["order"] = "08", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/454988cf101517fdf11f.png", ["icon_size"] = 32}},
            {["name"] = "clowns-centrifuging-75pc", ["order"] = "09", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/c164f428d6039699539e.png", ["icon_size"] = 32}},
            {["name"] = "clowns-centrifuging-80pc", ["order"] = "10", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/468fdacaff601998a3f4.png", ["icon_size"] = 32}},
        }},
        {subgroup = "paranoidal-components-fuel-cells", order = "a-19", recipes = {
            {["name"] = "uranium-fuel-cell", ["order"] = "01"},
            {["name"] = "mixed-oxide", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/0ee26640e9bf092a012c.png", ["icon_size"] = 32}},
            {["name"] = "angels-uranium-fuel-cell", ["order"] = "03"},
            {["name"] = "angels-mixed-oxide-cell", ["order"] = "04"},
            {["name"] = "clowns-thorium-fuel-cell", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/1e576b13d308c889e716.png", ["icon_size"] = 64}},
            {["name"] = "clowns-thorium-mixed-oxide", ["order"] = "06", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/bcf08453af925640839f.png", ["icon_size"] = 32}},
            {["name"] = "angels-thorium-fuel-cell", ["order"] = "07"},
            {["name"] = "angels-deuterium-fuel-cell", ["order"] = "08"},
        }},
        {subgroup = "paranoidal-components-uranium-reprocessing", order = "a-20", recipes = {
            {["name"] = "nuclear-fuel-reprocessing", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/24ec5f37dc14655514de.png", ["icon_size"] = 64}},
            {["name"] = "advanced-nuclear-fuel-reprocessing", ["order"] = "02", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/dbdb05bfe2fa15cdb9e1.png", ["icon_size"] = 32}}}},
            {["name"] = "advanced-nuclear-fuel-reprocessing-2", ["order"] = "03", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/dbdb05bfe2fa15cdb9e1.png", ["icon_size"] = 32}}}},
            {["name"] = "advanced-nuclear-fuel-reprocessing-b", ["order"] = "04", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/dbdb05bfe2fa15cdb9e1.png", ["icon_size"] = 32}}}},
            {["name"] = "angels-advanced-uranium-reprocessing", ["order"] = "05"},
        }},
        {subgroup = "paranoidal-components-plutonium", order = "a-21", recipes = {
            {["name"] = "angels-plutonium-synthesis", ["order"] = "01"},
            {["name"] = "angels-mixed-oxide-reprocessing", ["order"] = "02"},
            {["name"] = "angels-plutonium-breeding", ["order"] = "03"},
            {["name"] = "angels-advanced-mixed-oxide-reprocessing", ["order"] = "04"},
            {["name"] = "angels-americium-regeneration", ["order"] = "05"},
        }},
        {subgroup = "paranoidal-components-thorium-deuterium-reprocessing", order = "a-22", recipes = {
            {["name"] = "thorium-nuclear-fuel-reprocessing", ["order"] = "01", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/e70c6145779fb30906a6.png", ["icon_size"] = 32}}}},
            {["name"] = "advanced-thorium-nuclear-fuel-reprocessing", ["order"] = "02", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/e70c6145779fb30906a6.png", ["icon_size"] = 32}}}},
            {["name"] = "advanced-thorium-nuclear-fuel-reprocessing-b", ["order"] = "03", ["icon"] = {["icons"] = {{["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/e70c6145779fb30906a6.png", ["icon_size"] = 32}}}},
            {["name"] = "angels-thorium-fuel-cell-reprocessing", ["order"] = "04"},
            {["name"] = "angels-advanced-thorium-fuel-cell-reprocessing", ["order"] = "05"},
            {["name"] = "angels-deuterium-fuel-cell-reprocessing", ["order"] = "06"},
        }},
        {subgroup = "paranoidal-components-nuclear-fuels", order = "a-23", recipes = {
            {["name"] = "clowns-hypernuclear-fuel", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/03c906665b9b09317fbc.png", ["icon_size"] = 32}},
            {["name"] = "clowns-turbonuclear-fuel", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/63a3fa6536856376f1f9.png", ["icon_size"] = 32}},
            {["name"] = "clowns-radiothermal-fuel", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/d6d116d68f0dabed061d.png", ["icon_size"] = 32}},
            {["name"] = "clowns-superradiothermal-fuel", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/92b6108356fd7fa9c155.png", ["icon_size"] = 32}},
            {["name"] = "clowns-ultraradiothermal-fuel", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/33533aee6c8eb6239529.png", ["icon_size"] = 32}},
        }},
        {subgroup = "paranoidal-components-mech-parts", order = "a-24", recipes = {
            {["name"] = "bob-mech-armor-plate", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/bc97da9446b90d1c835b.png", ["icon_size"] = 64}},
            {["name"] = "bob-mech-brain", ["order"] = "02"},
            {["name"] = "bob-mech-frame", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a56a60a7ff744fc31047.png", ["icon_size"] = 64}},
            {["name"] = "bob-mech-leg", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/f7bfb9c04042a5a4ae24.png", ["icon_size"] = 64}},
            {["name"] = "bob-mech-foot", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a11166db770f98cb5879.png", ["icon_size"] = 64}},
            {["name"] = "bob-mech-hip", ["order"] = "06", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/9002a2f4f117f1d58eb5.png", ["icon_size"] = 64}},
            {["name"] = "bob-mech-knee", ["order"] = "07", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/932fd7f5d510df948e12.png", ["icon_size"] = 64}},
            {["name"] = "bob-mech-leg-segment", ["order"] = "08", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/aa803557bf6b5480de22.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-w93", order = "a-25", recipes = {
            {["name"] = "w93-modular-turret-base", ["order"] = "01"},
            {["name"] = "w93-modular-turret2-base", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/7d7d8c1c55c9095504ac.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-hmg", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/c2b44bbae10bc26a53fe.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-gatling", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/4b05597d295c41048921.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-lcannon", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/cb553da2ffebe40b9353.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-dcannon", ["order"] = "06"},
            {["name"] = "w93-modular-gun-hcannon", ["order"] = "07", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/50e355d68652edc2f13c.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-rocket", ["order"] = "08", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/cd34d885e458962bb716.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-plaser", ["order"] = "09", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/2d0f78937d375e62432f.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-tlaser", ["order"] = "10"},
            {["name"] = "w93-modular-gun-beam", ["order"] = "11", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/22f598b50ff7377e59ab.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-radar", ["order"] = "12", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a18d1ef335d594f83b9b.png", ["icon_size"] = 64}},
            {["name"] = "w93-modular-gun-radar2", ["order"] = "13", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/9a9a4248cb678192dae0.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-projectiles", order = "a-26", recipes = {
            {["name"] = "bob-bullet-projectile", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/bc4b3e4d73808900b6a8.png", ["icon_size"] = 64}},
            {["name"] = "bob-ap-bullet-projectile", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/6a0461fcaf2cc8455188.png", ["icon_size"] = 64}},
            {["name"] = "bob-he-bullet-projectile", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/602c3b9bbad1f04b2e51.png", ["icon_size"] = 64}},
            {["name"] = "bob-flame-bullet-projectile", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/b7db75d42bdd23b73923.png", ["icon_size"] = 64}},
            {["name"] = "bob-acid-bullet-projectile", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/cf2cf3882c3bc95fe6a9.png", ["icon_size"] = 64}},
            {["name"] = "bob-poison-bullet-projectile", ["order"] = "06", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/bd757c267e5aa1c053c1.png", ["icon_size"] = 64}},
            {["name"] = "bob-electric-bullet-projectile", ["order"] = "07", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a668fd870d78173b3dc2.png", ["icon_size"] = 64}},
            {["name"] = "bob-plasma-bullet-projectile", ["order"] = "08", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/5ae08ac14cd455614166.png", ["icon_size"] = 64}},
            {["name"] = "bob-uranium-bullet-projectile", ["order"] = "09", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/b6727a0efffcc06601b2.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-bullets", order = "a-27", recipes = {
            {["name"] = "bob-bullet", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/56a3d5b422f9a49c465d.png", ["icon_size"] = 64}},
            {["name"] = "bob-ap-bullet", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/edd87973bb269b60e7fc.png", ["icon_size"] = 64}},
            {["name"] = "bob-he-bullet", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/9af056e6aaf264459a1f.png", ["icon_size"] = 64}},
            {["name"] = "bob-flame-bullet", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/c11f737d301cdff261f7.png", ["icon_size"] = 64}},
            {["name"] = "bob-acid-bullet", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a4e356aa71a8b2f92921.png", ["icon_size"] = 64}},
            {["name"] = "bob-poison-bullet", ["order"] = "06", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/a06a661ed330d42b5366.png", ["icon_size"] = 64}},
            {["name"] = "bob-electric-bullet", ["order"] = "07", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/2a48ad887b58530b66d2.png", ["icon_size"] = 64}},
            {["name"] = "bob-plasma-bullet", ["order"] = "08", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/86dfa6666f266b1ccf36.png", ["icon_size"] = 64}},
            {["name"] = "bob-uranium-bullet", ["order"] = "09", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/93ba718c9e650ec79c66.png", ["icon_size"] = 64}},
            {["name"] = "bob-bullet-casing", ["order"] = "10", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/d41f1de6a7fe1942f104.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-rockets", order = "a-28", recipes = {
            {["name"] = "bob-rocket-warhead", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/41390e472d3a0ef65030.png", ["icon_size"] = 64}},
            {["name"] = "bob-piercing-rocket-warhead", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/86519f831c1079704979.png", ["icon_size"] = 64}},
            {["name"] = "bob-explosive-rocket-warhead", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/bc80c51898832b6beed1.png", ["icon_size"] = 64}},
            {["name"] = "bob-flame-rocket-warhead", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/2468c725f25a0c0678fb.png", ["icon_size"] = 64}},
            {["name"] = "bob-acid-rocket-warhead", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/002b33ab82e30e4507be.png", ["icon_size"] = 64}},
            {["name"] = "bob-poison-rocket-warhead", ["order"] = "06", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/dc7d42df31d0f767e27c.png", ["icon_size"] = 64}},
            {["name"] = "bob-electric-rocket-warhead", ["order"] = "07", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/505336240a0e93fe9f41.png", ["icon_size"] = 64}},
            {["name"] = "bob-plasma-rocket-warhead", ["order"] = "08", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/b3b5f66ae066e7c23cae.png", ["icon_size"] = 64}},
            {["name"] = "bob-rocket-engine", ["order"] = "09"},
            {["name"] = "bob-rocket-body", ["order"] = "10", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/ffaca91bc19832ba7527.png", ["icon_size"] = 32}},
        }},
        {subgroup = "paranoidal-components-ammo-parts", order = "a-29", recipes = {
            {["name"] = "bob-magazine", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/6b3827c4daff1c049cbe.png", ["icon_size"] = 64}},
            {["name"] = "bob-shot", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/ca9b8e0dd3bd7e581161.png", ["icon_size"] = 64}},
            {["name"] = "bob-shotgun-shell-casing", ["order"] = "03", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/9bce605184d0d0478677.png", ["icon_size"] = 64}},
            {["name"] = "bob-laser-rifle-battery-case", ["order"] = "04", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/ea97296b36f64400eeab.png", ["icon_size"] = 64}},
            {["name"] = "bob-cordite", ["order"] = "05", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/1a0dee384a2160a576e7.png", ["icon_size"] = 64}},
            {["name"] = "bob-gun-cotton", ["order"] = "06", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/631796392b2c3986a908.png", ["icon_size"] = 32}},
            {["name"] = "bob-petroleum-jelly", ["order"] = "07", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/908c023405cb3d587ae7.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-drone-frames", order = "a-30", recipes = {
            {["name"] = "bob-robot-drone-frame", ["order"] = "01", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/b097efaa791f2d640578.png", ["icon_size"] = 64}},
            {["name"] = "bob-robot-drone-frame-large", ["order"] = "02", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/74d057eecbaa3271e2fe.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-flask", order = "a-31", recipes = {
            {["name"] = "flask", ["order"] = "01"},
        }},
        {subgroup = "paranoidal-components-science-packs", order = "a-32", recipes = {
            {["name"] = "automation-science-pack", ["order"] = "01"},
            {["name"] = "logistic-science-pack", ["order"] = "02"},
            {["name"] = "military-science-pack", ["order"] = "03"},
            {["name"] = "chemical-science-pack", ["order"] = "04"},
            {["name"] = "bob-advanced-logistic-science-pack", ["order"] = "05"},
            {["name"] = "bi-production-science-pack", ["order"] = "06"},
            {["name"] = "production-science-pack", ["order"] = "07"},
            {["name"] = "utility-science-pack", ["order"] = "08"},
            {["name"] = "bob-science-pack-gold", ["order"] = "09", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/d5d7e77117ea4c97a47b.png", ["icon_size"] = 64}},
            {["name"] = "bob-alien-science-pack", ["order"] = "10", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/ab91f0b6778e5b4b575b.png", ["icon_size"] = 64}},
            {["name"] = "bob-alien-science-pack-blue", ["order"] = "11", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/0bdeb8ea0f440772e7b3.png", ["icon_size"] = 64}},
            {["name"] = "bob-alien-science-pack-orange", ["order"] = "12", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/4384e2110ad4e1912aa6.png", ["icon_size"] = 64}},
            {["name"] = "bob-alien-science-pack-purple", ["order"] = "13", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/054084afd4949790e625.png", ["icon_size"] = 64}},
            {["name"] = "bob-alien-science-pack-yellow", ["order"] = "14", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/836b7f198c15c844450f.png", ["icon_size"] = 64}},
            {["name"] = "bob-alien-science-pack-green", ["order"] = "15", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/bb802ee28d60e7ed9aaf.png", ["icon_size"] = 64}},
            {["name"] = "bob-alien-science-pack-red", ["order"] = "16", ["icon"] = {["icon"] = "__zzzparanoidal__/graphics/components-menu-beta8/54ed9d63a03be52fd28d.png", ["icon_size"] = 64}},
        }},
        {subgroup = "paranoidal-components-science-components", order = "a-33", recipes = {
            {["name"] = "sci-component-1", ["order"] = "01"},
            {["name"] = "sci-component-2", ["order"] = "02"},
            {["name"] = "sci-component-3", ["order"] = "03"},
            {["name"] = "sci-component-4", ["order"] = "04"},
            {["name"] = "sci-component-m", ["order"] = "05"},
            {["name"] = "sci-component-l", ["order"] = "06"},
            {["name"] = "sci-component-5", ["order"] = "07"},
            {["name"] = "sci-component-o", ["order"] = "08"},
        }},
        {subgroup = "paranoidal-components-advanced-science-components", order = "a-34", recipes = {
            {["name"] = "advsci-component-3", ["order"] = "01"},
            {["name"] = "advsci-component-4", ["order"] = "02"},
        }},
        {subgroup = "paranoidal-components-io", order = "a-35", recipes = {
            {["name"] = "simple-io", ["order"] = "01"},
            {["name"] = "standart-io", ["order"] = "02"},
            {["name"] = "advanced-io", ["order"] = "03"},
            {["name"] = "predictive-io", ["order"] = "04"},
            {["name"] = "intelligent-io", ["order"] = "05"},
        }},
    },
}
