-- Approved layout only: retain every recipe and all current icons/gameplay.
return { rows = {
    {group = "production", subgroup = "paranoidal-organized-production-repair", order = "a-01", recipes = {
        {["name"] = "repair-pack", ["order"] = "01"},
        {["name"] = "bob-repair-pack-2", ["order"] = "02"},
        {["name"] = "bob-repair-pack-3", ["order"] = "03"},
        {["name"] = "bob-repair-pack-4", ["order"] = "04"},
        {["name"] = "bob-repair-pack-5", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-nanobots", order = "a-02", recipes = {
        {["name"] = "gun-nano-emitter", ["order"] = "01"},
        {["name"] = "ammo-nano-constructors", ["order"] = "02"},
        {["name"] = "ammo-nano-levelers", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-drills", order = "a-03", recipes = {
        {["name"] = "burner-mining-drill", ["order"] = "01"},
        {["name"] = "electric-mining-drill", ["order"] = "02"},
        {["name"] = "bob-mining-drill-1", ["order"] = "03"},
        {["name"] = "bob-mining-drill-2", ["order"] = "04"},
        {["name"] = "bob-mining-drill-3", ["order"] = "05"},
        {["name"] = "bob-mining-drill-4", ["order"] = "06"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-area-drills", order = "a-04", recipes = {
        {["name"] = "bob-area-mining-drill-1", ["order"] = "01"},
        {["name"] = "bob-area-mining-drill-2", ["order"] = "02"},
        {["name"] = "bob-area-mining-drill-3", ["order"] = "03"},
        {["name"] = "bob-area-mining-drill-4", ["order"] = "04"},
        {["name"] = "area-mining-drill", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-pumpjacks", order = "a-05", recipes = {
        {["name"] = "pumpjack", ["order"] = "01"},
        {["name"] = "bob-pumpjack-1", ["order"] = "02"},
        {["name"] = "bob-pumpjack-2", ["order"] = "03"},
        {["name"] = "paranoidal-pumpjack-4", ["order"] = "04"},
        {["name"] = "bob-pumpjack-3", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-water-pumps", order = "a-06", recipes = {
        {["name"] = "offshore-mk0-pump", ["order"] = "01"},
        {["name"] = "offshore-pump", ["order"] = "02"},
        {["name"] = "offshore-mk2-pump", ["order"] = "03"},
        {["name"] = "offshore-mk3-pump", ["order"] = "04"},
        {["name"] = "offshore-mk4-pump", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-furnaces", order = "a-07", recipes = {
        {["name"] = "stone-furnace", ["order"] = "01"},
        {["name"] = "steel-furnace", ["order"] = "02"},
        {["name"] = "electric-steel-furnace", ["order"] = "03"},
        {["name"] = "electric-furnace", ["order"] = "04"},
        {["name"] = "bob-electric-furnace-2", ["order"] = "05"},
        {["name"] = "bob-electric-furnace-3", ["order"] = "06"},
        {["name"] = "industrial-furnace", ["order"] = "07"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-mixing-furnaces", order = "a-08", recipes = {
        {["name"] = "bob-stone-mixing-furnace", ["order"] = "01"},
        {["name"] = "bob-steel-mixing-furnace", ["order"] = "02"},
        {["name"] = "bob-electric-mixing-furnace", ["order"] = "03"},
        {["name"] = "bob-electric-chemical-mixing-furnace", ["order"] = "04"},
        {["name"] = "bob-electric-chemical-mixing-furnace-2", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-assemblers", order = "a-09", recipes = {
        {["name"] = "burner-assembling-machine", ["order"] = "01"},
        {["name"] = "assembling-machine-1", ["order"] = "02"},
        {["name"] = "assembling-machine-2", ["order"] = "03"},
        {["name"] = "assembling-machine-3", ["order"] = "04"},
        {["name"] = "bob-assembling-machine-4", ["order"] = "05"},
        {["name"] = "bob-assembling-machine-5", ["order"] = "06"},
        {["name"] = "bob-assembling-machine-6", ["order"] = "07"},
        {["name"] = "assembling-machine-7", ["order"] = "08"},
        {["name"] = "assembling-machine-8", ["order"] = "09"},
        {["name"] = "assembling-machine-9", ["order"] = "10"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-electronics-assemblers", order = "a-10", recipes = {
        {["name"] = "bob-electronics-machine-1", ["order"] = "01"},
        {["name"] = "bob-electronics-machine-2", ["order"] = "02"},
        {["name"] = "bob-electronics-machine-3", ["order"] = "03"},
        {["name"] = "electronics-machine-4", ["order"] = "04"},
        {["name"] = "electronics-machine-5", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-centrifuges", order = "a-11", recipes = {
        {["name"] = "centrifuge", ["order"] = "01"},
        {["name"] = "bob-centrifuge-2", ["order"] = "02"},
        {["name"] = "bob-centrifuge-3", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-labs", order = "a-12", recipes = {
        {["name"] = "bob-burner-lab", ["order"] = "01"},
        {["name"] = "burner-lab", ["order"] = "02"},
        {["name"] = "lab", ["order"] = "03"},
        {["name"] = "bob-lab-2", ["order"] = "04"},
        {["name"] = "big-lab", ["order"] = "05"},
        {["name"] = "paranoidal-beta8-big-lab", ["order"] = "06"},
        {["name"] = "paranoidal-beta8-hyper-lab", ["order"] = "07"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-special-labs", order = "a-13", recipes = {
        {["name"] = "bob-lab-alien", ["order"] = "01"},
        {["name"] = "lab-module", ["order"] = "02"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-generators", order = "a-14", recipes = {
        {["name"] = "burner-turbine", ["order"] = "01"},
        {["name"] = "petroleum-generator", ["order"] = "02"},
        {["name"] = "big-burner-generator", ["order"] = "03"},
        {["name"] = "bob-burner-generator", ["order"] = "04"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-boilers", order = "a-15", recipes = {
        {["name"] = "boiler", ["order"] = "01"},
        {["name"] = "bob-boiler-2", ["order"] = "02"},
        {["name"] = "bob-boiler-3", ["order"] = "03"},
        {["name"] = "bob-boiler-4", ["order"] = "04"},
        {["name"] = "bob-boiler-5", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-fluid-boilers", order = "a-16", recipes = {
        {["name"] = "oil-steam-boiler", ["order"] = "01"},
        {["name"] = "oil-steam-boiler-2", ["order"] = "02"},
        {["name"] = "oil-steam-boiler-3", ["order"] = "03"},
        {["name"] = "oil-steam-boiler-4", ["order"] = "04"},
        {["name"] = "oil-steam-boiler-5", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-special-boilers", order = "a-17", recipes = {
        {["name"] = "bi-bio-boiler", ["order"] = "01"},
        {["name"] = "bi-solar-boiler-hidden-panel", ["order"] = "02"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-steam-engines", order = "a-18", recipes = {
        {["name"] = "steam-engine", ["order"] = "01"},
        {["name"] = "bob-steam-engine-2", ["order"] = "02"},
        {["name"] = "bob-steam-engine-3", ["order"] = "03"},
        {["name"] = "bob-steam-engine-4", ["order"] = "04"},
        {["name"] = "bob-steam-engine-5", ["order"] = "05"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-steam-turbines", order = "a-19", recipes = {
        {["name"] = "steam-turbine", ["order"] = "01"},
        {["name"] = "bob-steam-turbine-2", ["order"] = "02"},
        {["name"] = "bob-steam-turbine-3", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-wind", order = "a-20", recipes = {
        {["name"] = "texugo-wind-turbine", ["order"] = "01"},
        {["name"] = "texugo-wind-turbine2", ["order"] = "02"},
        {["name"] = "texugo-wind-turbine3", ["order"] = "03"},
        {["name"] = "wind-turbine-2", ["order"] = "04"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-solar-1", order = "a-21", recipes = {
        {["name"] = "bob-solar-panel-small", ["order"] = "01"},
        {["name"] = "solar-panel", ["order"] = "02"},
        {["name"] = "bob-solar-panel-large", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-solar-2", order = "a-22", recipes = {
        {["name"] = "bob-solar-panel-small-2", ["order"] = "01"},
        {["name"] = "bob-solar-panel-2", ["order"] = "02"},
        {["name"] = "bob-solar-panel-large-2", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-solar-3", order = "a-23", recipes = {
        {["name"] = "bob-solar-panel-small-3", ["order"] = "01"},
        {["name"] = "bob-solar-panel-3", ["order"] = "02"},
        {["name"] = "bob-solar-panel-large-3", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-special-solar", order = "a-24", recipes = {
        {["name"] = "bi-bio-solar-farm", ["order"] = "01"},
        {["name"] = "bi-solar-mat", ["order"] = "02"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-accumulators-1", order = "a-25", recipes = {
        {["name"] = "bob-fast-accumulator", ["order"] = "01"},
        {["name"] = "accumulator", ["order"] = "02"},
        {["name"] = "bob-slow-accumulator", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-accumulators-2", order = "a-26", recipes = {
        {["name"] = "bob-fast-accumulator-2", ["order"] = "01"},
        {["name"] = "bob-large-accumulator-2", ["order"] = "02"},
        {["name"] = "bob-slow-accumulator-2", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-accumulators-3", order = "a-27", recipes = {
        {["name"] = "bob-fast-accumulator-3", ["order"] = "01"},
        {["name"] = "bob-large-accumulator-3", ["order"] = "02"},
        {["name"] = "bob-slow-accumulator-3", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-special-accumulators", order = "a-28", recipes = {
        {["name"] = "bi-bio-accumulator", ["order"] = "01"},
        {["name"] = "fe-c-accumulator", ["order"] = "02"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-reactors", order = "a-29", recipes = {
        {["name"] = "nuclear-reactor", ["order"] = "01"},
        {["name"] = "bob-nuclear-reactor-2", ["order"] = "02"},
        {["name"] = "bob-nuclear-reactor-3", ["order"] = "03"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-angels-reactor", order = "a-30", recipes = {
        {["name"] = "angels-burner-reactor", ["order"] = "01"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-heat-exchangers", order = "a-31", recipes = {
        {["name"] = "heat-exchanger", ["order"] = "01"},
        {["name"] = "bob-heat-exchanger-2", ["order"] = "02"},
        {["name"] = "bob-heat-exchanger-3", ["order"] = "03"},
        {["name"] = "bob-heat-exchanger-4", ["order"] = "04"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-heat-pipes", order = "a-32", recipes = {
        {["name"] = "heat-pipe", ["order"] = "01"},
        {["name"] = "bob-heat-pipe-2", ["order"] = "02"},
        {["name"] = "bob-heat-pipe-3", ["order"] = "03"},
        {["name"] = "bob-heat-pipe-4", ["order"] = "04"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-rtg", order = "a-33", recipes = {
        {["name"] = "RITEG-1", ["order"] = "01"},
        {["name"] = "RITEG-1-from-used-up-RITEG-1", ["order"] = "02"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-air-filters", order = "a-34", recipes = {
        {["name"] = "CW-air-filter-machine-1", ["order"] = "01"},
        {["name"] = "CW-air-filter-machine-2", ["order"] = "02"},
        {["name"] = "CW-air-filter-machine-3", ["order"] = "03"},
        {["name"] = "CW-air-filter-machine-4", ["order"] = "04"},
        {["name"] = "CW-air-filter-machine-5", ["order"] = "05"},
        {["name"] = "CW-air-filter-machine-6", ["order"] = "06"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-torch", order = "a-35", recipes = {
        {["name"] = "torch", ["order"] = "01"},
    }},
    {group = "production", subgroup = "paranoidal-organized-production-space-sites", order = "a-36", recipes = {
        {["name"] = "rsc-excavation-site", ["order"] = "01"},
        {["name"] = "cargo-landing-pad", ["order"] = "02"},
    }},
    {group = "logistics", subgroup = "paranoidal-organized-logistics-iron-poles", order = "a-03-a", recipes = {
        {["name"] = "small-iron-electric-pole", ["order"] = "01"},
        {["name"] = "lighted-small-iron-electric-pole", ["order"] = "02"},
    }},
    {group = "intermediate-products", subgroup = "paranoidal-organized-intermediate-products-nuclear-processing", order = "a-17-a", recipes = {
        {["name"] = "clowns-thorium-purification", ["order"] = "01"},
        {["name"] = "advanced-uranium-processing", ["order"] = "02"},
    }},
    {group = "intermediate-products", subgroup = "paranoidal-organized-intermediate-products-spider-cannon", order = "a-24-a", recipes = {
        {["name"] = "bob-spidertron-cannon", ["order"] = "01"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-solar", order = "z-01", recipes = {
        {["name"] = "bob-vehicle-solar-panel-equipment-1", ["order"] = "01"},
        {["name"] = "bob-vehicle-solar-panel-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-solar-panel-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-solar-panel-equipment-4", ["order"] = "04"},
        {["name"] = "bob-vehicle-solar-panel-equipment-5", ["order"] = "05"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-fission-cells", order = "z-02", recipes = {
        {["name"] = "bob-vehicle-fission-cell-equipment-1", ["order"] = "01"},
        {["name"] = "bob-vehicle-fission-cell-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-fission-cell-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-fission-cell-equipment-4", ["order"] = "04"},
        {["name"] = "bob-vehicle-fission-cell-equipment-5", ["order"] = "05"},
        {["name"] = "bob-vehicle-fission-cell-equipment-6", ["order"] = "06"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-extra-fuel-cells", order = "z-03", recipes = {
        {["name"] = "vehicle-fuel-cell-2-equipment", ["order"] = "01"},
        {["name"] = "vehicle-fuel-cell-3-equipment", ["order"] = "02"},
        {["name"] = "vehicle-fuel-cell-4-equipment", ["order"] = "03"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-fission-reactors", order = "z-04", recipes = {
        {["name"] = "bob-vehicle-fission-reactor-equipment-1", ["order"] = "01"},
        {["name"] = "bob-vehicle-fission-reactor-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-fission-reactor-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-fission-reactor-equipment-4", ["order"] = "04"},
        {["name"] = "bob-vehicle-fission-reactor-equipment-5", ["order"] = "05"},
        {["name"] = "bob-vehicle-fission-reactor-equipment-6", ["order"] = "06"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-extra-reactor", order = "z-05", recipes = {
        {["name"] = "vehicle-nuclear-reactor-equipment", ["order"] = "01"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-batteries", order = "z-06", recipes = {
        {["name"] = "bob-vehicle-battery-equipment-1", ["order"] = "01"},
        {["name"] = "bob-vehicle-battery-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-battery-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-battery-equipment-4", ["order"] = "04"},
        {["name"] = "bob-vehicle-battery-equipment-5", ["order"] = "05"},
        {["name"] = "bob-vehicle-battery-equipment-6", ["order"] = "06"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-extra-batteries", order = "z-07", recipes = {
        {["name"] = "vehicle-battery-equipment", ["order"] = "01"},
        {["name"] = "vehicle-battery-mk2-equipment", ["order"] = "02"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-motors", order = "z-08", recipes = {
        {["name"] = "bob-vehicle-motor-equipment", ["order"] = "01"},
        {["name"] = "bob-vehicle-engine-equipment", ["order"] = "02"},
        {["name"] = "bob-vehicle-belt-immunity-equipment", ["order"] = "03"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-roboports", order = "z-09", recipes = {
        {["name"] = "bob-vehicle-roboport-equipment-1", ["order"] = "01"},
        {["name"] = "bob-vehicle-roboport-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-roboport-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-roboport-equipment-4", ["order"] = "04"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-robot-capacity", order = "z-10", recipes = {
        {["name"] = "bob-vehicle-roboport-robot-equipment", ["order"] = "01"},
        {["name"] = "bob-vehicle-roboport-robot-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-roboport-robot-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-roboport-robot-equipment-4", ["order"] = "04"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-robot-charging", order = "z-11", recipes = {
        {["name"] = "bob-vehicle-roboport-chargepad-equipment", ["order"] = "01"},
        {["name"] = "bob-vehicle-roboport-chargepad-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-roboport-chargepad-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-roboport-chargepad-equipment-4", ["order"] = "04"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-robot-antennas", order = "z-12", recipes = {
        {["name"] = "bob-vehicle-roboport-antenna-equipment", ["order"] = "01"},
        {["name"] = "bob-vehicle-roboport-antenna-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-roboport-antenna-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-roboport-antenna-equipment-4", ["order"] = "04"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-shields", order = "z-13", recipes = {
        {["name"] = "bob-vehicle-shield-equipment-1", ["order"] = "01"},
        {["name"] = "bob-vehicle-shield-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-shield-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-shield-equipment-4", ["order"] = "04"},
        {["name"] = "bob-vehicle-shield-equipment-5", ["order"] = "05"},
        {["name"] = "bob-vehicle-shield-equipment-6", ["order"] = "06"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-extra-shields", order = "z-14", recipes = {
        {["name"] = "vehicle-energy-shield-equipment", ["order"] = "01"},
        {["name"] = "vehicle-energy-shield-mk2-equipment", ["order"] = "02"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-laser-defense", order = "z-15", recipes = {
        {["name"] = "bob-vehicle-laser-defense-equipment-1", ["order"] = "01"},
        {["name"] = "bob-vehicle-laser-defense-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-laser-defense-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-laser-defense-equipment-4", ["order"] = "04"},
        {["name"] = "bob-vehicle-laser-defense-equipment-5", ["order"] = "05"},
        {["name"] = "bob-vehicle-laser-defense-equipment-6", ["order"] = "06"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-plasma-defense", order = "z-16", recipes = {
        {["name"] = "bob-vehicle-big-turret-equipment-1", ["order"] = "01"},
        {["name"] = "bob-vehicle-big-turret-equipment-2", ["order"] = "02"},
        {["name"] = "bob-vehicle-big-turret-equipment-3", ["order"] = "03"},
        {["name"] = "bob-vehicle-big-turret-equipment-4", ["order"] = "04"},
    }},
    {group = "transport", subgroup = "paranoidal-organized-transport-equipment-aircraft", order = "z-17", recipes = {
        {["name"] = "aircraft-energy-shield", ["order"] = "01"},
        {["name"] = "aircraft-afterburner", ["order"] = "02"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-ground", order = "a-01", recipes = {
        {["name"] = "advanced-assembler", ["order"] = "01"},
        {["name"] = "ground-auto-fabricator", ["order"] = "02"},
        {["name"] = "erp-lab", ["order"] = "03"},
        {["name"] = "ground-telescope", ["order"] = "04"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-rocket-components", order = "a-02", recipes = {
        {["name"] = "rocket-control-unit", ["order"] = "01"},
        {["name"] = "low-density-structure", ["order"] = "02"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-control-optics", order = "a-03", recipes = {
        {["name"] = "satellite-flight-computer", ["order"] = "01"},
        {["name"] = "satellite-radar", ["order"] = "02"},
        {["name"] = "satellite-communications", ["order"] = "03"},
        {["name"] = "telescope-components", ["order"] = "04"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-power", order = "a-04", recipes = {
        {["name"] = "radioisotope-thermoelectric-generator", ["order"] = "01"},
        {["name"] = "radioisotope-thermoelectric-generator-thorium", ["order"] = "02"},
        {["name"] = "satellite-battery", ["order"] = "03"},
        {["name"] = "satellite-solar-array", ["order"] = "04"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-platform", order = "a-05", recipes = {
        {["name"] = "satellite-bus", ["order"] = "01"},
        {["name"] = "satellite-thruster", ["order"] = "02"},
        {["name"] = "space-lab-payload", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-satellites", order = "a-06", recipes = {
        {["name"] = "satellite", ["order"] = "01"},
        {["name"] = "advanced-probe", ["order"] = "02"},
        {["name"] = "space-telescope", ["order"] = "03"},
        {["name"] = "observation-satellite", ["order"] = "04"},
        {["name"] = "orbital-solar-collector", ["order"] = "05"},
        {["name"] = "space-lab", ["order"] = "06"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-shuttle-hull", order = "a-07", recipes = {
        {["name"] = "shuttle-hull-recipe", ["order"] = "01"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-fabricator-shuttle", order = "a-08", recipes = {
        {["name"] = "fabricator-shuttle", ["order"] = "01"},
        {["name"] = "refurbish-fabricator-shuttle", ["order"] = "02"},
        {["name"] = "repurpose-fabricator-shuttle", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-mining-shuttle", order = "a-09", recipes = {
        {["name"] = "mining-shuttle", ["order"] = "01"},
        {["name"] = "refurbish-mining-shuttle", ["order"] = "02"},
        {["name"] = "repurpose-mining-shuttle", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-space-shuttle", order = "a-10", recipes = {
        {["name"] = "space-shuttle", ["order"] = "01"},
        {["name"] = "refurbish-space-shuttle", ["order"] = "02"},
        {["name"] = "repurpose-space-shuttle", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-spy-shuttle", order = "a-11", recipes = {
        {["name"] = "spy-shuttle", ["order"] = "01"},
        {["name"] = "refurbish-spy-shuttle", ["order"] = "02"},
        {["name"] = "repurpose-spy-shuttle", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-mining-fabrication", order = "a-12", recipes = {
        {["name"] = "autonomous-space-mining-drone", ["order"] = "01"},
        {["name"] = "orbital-fabricator-component", ["order"] = "02"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-unboxing", order = "a-13", recipes = {
        {["name"] = "random-dropship-unboxing", ["order"] = "01"},
        {["name"] = "copper-dropship-unboxing", ["order"] = "02"},
        {["name"] = "iron-dropship-unboxing", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-delivery-basic", order = "a-14", recipes = {
        {["name"] = "coal-delivery", ["order"] = "01"},
        {["name"] = "stone-delivery", ["order"] = "02"},
        {["name"] = "iron-delivery", ["order"] = "03"},
        {["name"] = "copper-delivery", ["order"] = "04"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-delivery-advanced", order = "a-15", recipes = {
        {["name"] = "steel-delivery", ["order"] = "01"},
        {["name"] = "aluminium-plate-delivery", ["order"] = "02"},
        {["name"] = "titanium-plate-delivery", ["order"] = "03"},
        {["name"] = "uranium-delivery", ["order"] = "04"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-research", order = "a-16", recipes = {
        {["name"] = "space-study-the-stars", ["order"] = "01"},
        {["name"] = "study-the-stars", ["order"] = "02"},
        {["name"] = "study-the-planet", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-probe-data", order = "a-17", recipes = {
        {["name"] = "probe-data-processing", ["order"] = "01"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-ship-construction", order = "a-18", recipes = {
        {["name"] = "spacex-combinator", ["order"] = "01"},
        {["name"] = "assembly-robot", ["order"] = "02"},
        {["name"] = "drydock-assembly", ["order"] = "03"},
        {["name"] = "drydock-structural", ["order"] = "04"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-ship-hull", order = "a-19", recipes = {
        {["name"] = "hull-component", ["order"] = "01"},
        {["name"] = "protection-field", ["order"] = "02"},
        {["name"] = "protection-field-goopless", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-ship-power", order = "a-20", recipes = {
        {["name"] = "fusion-reactor", ["order"] = "01"},
        {["name"] = "space-thruster", ["order"] = "02"},
        {["name"] = "fuel-cell", ["order"] = "03"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-ship-life", order = "a-21", recipes = {
        {["name"] = "habitation", ["order"] = "01"},
        {["name"] = "life-support", ["order"] = "02"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-ship-command", order = "a-22", recipes = {
        {["name"] = "command", ["order"] = "01"},
        {["name"] = "astrometrics", ["order"] = "02"},
    }},
    {group = "space-exploration", subgroup = "paranoidal-organized-space-exploration-ship-ftl", order = "a-23", recipes = {
        {["name"] = "ftl-drive", ["order"] = "01"},
    }},
}}
