data:extend{
  {
    type="custom-input",
    name="ltnc-escape",
    key_sequence="",
    linked_game_control="toggle-menu",
  },
  {
    type="custom-input",
    name="ltnc-close",
    key_sequence="",
    linked_game_control="confirm-gui",
  },
}