require("__core__/lualib/sound-util")
require("__base__/prototypes/entity/rail-pictures")

local locomotive_reflection = function()
	return {
		pictures = {
			filename = "__base__/graphics/entity/locomotive/reflection/locomotive-reflection.png",
			priority = "extra-high",
			width = 20,
			height = 52,
			shift = util.by_pixel(0, 40),
			variation_count = 1,
			scale = 5,
		},
		rotate = true,
		orientation_to_variation = false,
	}
end

local drive_over_tie = function()
	return {
		type = "play-sound",
		sound = {
			category = "environment",
			variations = sound_variations("__base__/sound/train-tie", 6, 0.4, {
				volume_multiplier("main-menu", 2.4),
				volume_multiplier("driving", 1.3),
			}),
		},
	}
end

local rolling_stock_stand_by_light = function()
	return {
		{
			minimum_darkness = 0.3,
			color = { 0.05, 0.2, 1, 0 },
			shift = { -0.6, -3.5 },
			size = 2,
			intensity = 0.5,
			add_perspective = true,
		},
		{
			minimum_darkness = 0.3,
			color = { 0.05, 0.2, 1, 0 },
			shift = { 0.6, -3.5 },
			size = 2,
			intensity = 0.5,
			add_perspective = true,
		},
	}
end

local sounds = require("__base__/prototypes/entity/sounds")

-- super charger
local super_charger = table.deepcopy(data.raw.furnace["bet-charger-3"])
super_charger.name = "super_charger"
super_charger.icon = "__zzzparanoidal__/graphics/train/electric/charger_icon.png"
super_charger.minable = { mining_time = 1, result = "super_charger" }
super_charger.crafting_speed = 50
super_charger.energy_usage = "100MW"
super_charger.energy_source = { type = "electric", drain = "50kW", usage_priority = "secondary-input" }
super_charger.working_visualisations = {
	filename = "__zzzparanoidal__/graphics/train/electric/charger_sheet.png",
	priority = "medium",
	width = 256,
	height = 256,
	frame_count = 16,
	line_length = 4,
	shift = { 0.5, -0.5 },
	scale = 0.5,
	animation_speed = 0.01,
}
super_charger.animation = {
	filename = "__zzzparanoidal__/graphics/train/electric/charger_sheet.png",
	priority = "medium",
	width = 256,
	height = 256,
	frame_count = 16,
	line_length = 4,
	shift = { 0.5, -0.5 },
	scale = 0.5,
	animation_speed = 0.01,
}

data:extend({
	super_charger,
	-- locomotive
	{
		type = "locomotive",
		name = "hiend_loco",
		icon = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive.png",
		icon_size = 64,
		flags = { "placeable-neutral", "player-creation", "placeable-off-grid" },
		minable = { mining_time = 0.5, result = "hiend_loco" },
		mined_sound = { filename = "__core__/sound/deconstruct-large.ogg", volume = 0.8 },
		max_health = 5000,
		corpse = "locomotive-remnants",
		dying_explosion = "locomotive-explosion",
		collision_box = { { -0.6, -2.6 }, { 0.6, 2.6 } },
		selection_box = { { -1, -3 }, { 1, 3 } },
		damaged_trigger_effect = {
			type = "create-entity",
			entity_name = "spark-explosion",
			offset_deviation = { { -0.5, -0.5 }, { 0.5, 0.5 } },
			offsets = { { 0, 1 } },
			damage_type_filters = "fire",
		},
		drawing_box = { { -1, -4 }, { 1, 3 } },
		alert_icon_shift = util.by_pixel(0, -24),
		weight = 1000,
		max_speed = 2,
		5,
		max_power = "1800kW",
		reversing_power_modifier = 1,
		braking_force = 40,
		friction_force = 0.50,
		vertical_selection_shift = -0.5,
		air_resistance = 0.0030, -- this is a percentage of current speed that will be subtracted
		connection_distance = 3.7,
		joint_distance = 3.7,
		energy_per_hit_point = 5,
		resistances = {
			{ type = "fire", decrease = 15, percent = 90 },
			{ type = "physical", decrease = 15, percent = 20 },
			{ type = "impact", decrease = 50, percent = 40 },
			{ type = "explosion", decrease = 15, percent = 30 },
			{ type = "acid", decrease = 50, percent = 90 },
		},
		energy_source = {
			type = "burner",
			fuel_categories = { "bet-fuel-battery" },
			effectivity = 2,
			fuel_inventory_size = 2,
			burnt_inventory_size = 2,
		},
		front_light = {
			{
				type = "oriented",
				minimum_darkness = 0.3,
				picture = {
					filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/light-cone.png",
					priority = "extra-high",
					flags = { "light" },
					scale = 2,
					width = 235,
					height = 235,
				},
				shift = util.by_pixel(0, -360),
				size = 1.0,
				intensity = 1.2,
				color = { r = 0.333, g = 0.768, b = 0.913 },
			},
			{
				type = "oriented",
				minimum_darkness = 0.3,
				picture = {
					filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/spot.png",
					priority = "extra-high",
					flags = { "light" },
					scale = 1,
					width = 200,
					height = 200,
				},
				shift = util.by_pixel(0, -125),
				size = 1.0,
				intensity = 1.0,
				color = { r = 0.333, g = 0.828, b = 1.0 },
			},
		},
		stand_by_light = rolling_stock_stand_by_light(),
		color = { r = 0.333, g = 0.768, b = 0.913 },
		pictures = {
			rotated = {
				layers = {
					{
						dice = 4,
						priority = "very-low",
						width = 240,
						height = 224,
						direction_count = 256,
						allow_low_quality_rotation = true,
						filenames = {
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-1.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-2.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-3.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-4.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-5.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-6.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-7.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-8.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-9.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-10.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-11.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-12.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-13.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-14.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-15.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/pyloco-16.png",
						},
						line_length = 4,
						lines_per_file = 4,
						shift = util.by_pixel(0, -5),
					},

					{
						priority = "very-low",
						dice = 4,
						flags = { "shadow" },
						width = 240,
						height = 224,
						direction_count = 256,
						draw_as_shadow = true,
						allow_low_quality_rotation = true,
						filenames = {
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-1.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-2.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-3.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-4.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-5.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-6.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-7.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-8.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-9.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-10.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-11.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-12.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-13.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-14.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-15.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-locomotive/sh-16.png",
						},
						line_length = 4,
						lines_per_file = 4,
						shift = util.by_pixel(48, 12),
					},
				},
			},
		},
		minimap_representation = {
			filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/icon-map.png",
			flags = { "icon" },
			size = { 20, 44 },
			scale = 0.4,
		},
		selected_minimap_representation = {
			filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/icon-map-selected.png",
			flags = { "icon" },
			size = { 20, 44 },
			scale = 0.4,
		},
		--wheels = standard_train_wheels,
		stop_trigger = {
			-- left side
			{
				type = "create-trivial-smoke",
				repeat_count = 5,
				smoke_name = "smoke-train-stop",
				initial_height = 0,
				-- smoke goes to the left
				speed = { -0.03, -0.4 },
				speed_multiplier = 0.75,
				speed_multiplier_deviation = 1.1,
				color = { r = 0.333, g = 0.768, b = 0.913 },
				offset_deviation = { { -0.75, -2.7 }, { -0.3, 2.7 } },
			},
			-- right side
			{
				type = "create-trivial-smoke",
				repeat_count = 5,
				smoke_name = "smoke-train-stop",
				initial_height = 0,
				-- smoke goes to the right
				speed = { 0.03, -0.4 },
				speed_multiplier = 0.75,
				speed_multiplier_deviation = 1.1,
				color = { r = 0.333, g = 0.768, b = 0.913 },
				offset_deviation = { { 0.3, -2.7 }, { 0.75, 2.7 } },
			},
			{
				type = "play-sound",
				sound = {
					filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/ht-locomotive-break.ogg",
					volume = 0.4,
				},
			},
			{
				type = "play-sound",
				sound = { filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/bonk.ogg", volume = 0.5 },
			},
		},
		drive_over_tie_trigger = drive_over_tie(),
		tie_distance = 50,
		vehicle_impact_sound = {
			{ filename = "__base__/sound/car-metal-impact-2.ogg", volume = 0.5 },
			{ filename = "__base__/sound/car-metal-impact-3.ogg", volume = 0.5 },
			{ filename = "__base__/sound/car-metal-impact-4.ogg", volume = 0.5 },
			{ filename = "__base__/sound/car-metal-impact-5.ogg", volume = 0.5 },
			{ filename = "__base__/sound/car-metal-impact-6.ogg", volume = 0.5 },
		},
		working_sound = {
			sound = {
				filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/ht-locomotive-engine.ogg",
				volume = 0.63,
			},
			deactivate_sound = {
				filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/ht-locomotive-end-engine.ogg",
				volume = 0.40,
			},
			match_speed_to_activity = true,
			max_sounds_per_type = 2,
			-- use_doppler_shift = false
		},
		open_sound = {
			filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/ht-locomotive-open.ogg",
			volume = 0.5,
		},
		close_sound = {
			filename = "__zzzparanoidal__/graphics/train/hiend/ht-locomotive/ht-locomotive-close.ogg",
			volume = 0.4,
		},
		sound_minimum_speed = 0.5,
		sound_scaling_ratio = 0.35,
		equipment_grid = "large-equipment-grid",
		water_reflection = locomotive_reflection(),
	},
	{
		type = "cargo-wagon",
		name = "hiend_wagon",
		icon = "__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon.png",
		icon_size = 64,
		flags = { "placeable-neutral", "player-creation", "placeable-off-grid" },
		minable = { mining_time = 0.5, result = "hiend_wagon" },
		mined_sound = { filename = "__core__/sound/deconstruct-large.ogg", volume = 0.8 },
		max_health = 1000,
		corpse = "cargo-wagon-remnants",
		dying_explosion = "cargo-wagon-explosion",
		collision_box = { { -0.6, -2.4 }, { 0.6, 2.4 } },
		selection_box = { { -1, -2.7 }, { 1, 3.3 } },
		--damaged_trigger_effect = hit_effects.entity(),
		vertical_selection_shift = -0.5,
		weight = 500,
		max_speed = 3,
		braking_force = 30,
		friction_force = 0.50,
		air_resistance = 0.0030,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
		inventory_size = 60,
		resistances = {
			{ type = "fire", decrease = 15, percent = 90 },
			{ type = "physical", decrease = 15, percent = 20 },
			{ type = "impact", decrease = 50, percent = 40 },
			{ type = "explosion", decrease = 15, percent = 30 },
			{ type = "acid", decrease = 3, percent = 90 },
		},
		--back_light = rolling_stock_back_light(),
		stand_by_light = rolling_stock_stand_by_light(),
		color = { r = 0.333, g = 0.768, b = 0.913 },
		pictures = {
			rotated = {
				layers = {
					{
						dice = 4,
						priority = "very-low",
						width = 240,
						height = 224,
						back_equals_front = true,
						direction_count = 128,
						allow_low_quality_rotation = true,
						filenames = {
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/generic-wagon-1.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/generic-wagon-2.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/generic-wagon-3.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/generic-wagon-4.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/generic-wagon-5.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/generic-wagon-6.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/generic-wagon-7.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/generic-wagon-8.png",
						},
						line_length = 4,
						lines_per_file = 4,
						shift = util.by_pixel(0, -5),
					},

					{
						priority = "very-low",
						dice = 4,
						flags = { "shadow" },
						width = 240,
						height = 224,
						back_equals_front = true,
						direction_count = 128,
						draw_as_shadow = true,
						allow_low_quality_rotation = true,
						filenames = {
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/sh-generic-wagon-1.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/sh-generic-wagon-2.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/sh-generic-wagon-3.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/sh-generic-wagon-4.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/sh-generic-wagon-5.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/sh-generic-wagon-6.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/sh-generic-wagon-7.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/sh-generic-wagon-8.png",
						},
						line_length = 4,
						lines_per_file = 4,
						shift = util.by_pixel(48, 12),
					},
				},
			},
		},
		minimap_representation = {
			filename = "__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/icon-map.png",
			flags = { "icon" },
			size = { 20, 44 },
			scale = 0.4,
		},
		selected_minimap_representation = {
			filename = "__zzzparanoidal__/graphics/train/hiend/ht-generic-wagon/icon-map-selected.png",
			flags = { "icon" },
			size = { 20, 44 },
			scale = 0.4,
		},
		--wheels = standard_train_wheels,
		drive_over_tie_trigger = drive_over_tie(),
		tie_distance = 50,
		crash_trigger = crash_trigger(),
		open_sound = sounds.cargo_wagon_open,
		close_sound = sounds.cargo_wagon_close,
		sound_minimum_speed = 1,
		vehicle_impact_sound = sounds.generic_impact,
		equipment_grid = "large-equipment-grid",
		water_reflection = locomotive_reflection(),
	},
	{
		type = "fluid-wagon",
		name = "hiend_fluid_wagon",
		icon = "__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon.png",
		icon_size = 64,
		flags = { "placeable-neutral", "player-creation", "placeable-off-grid" },
		minable = { mining_time = 0.5, result = "hiend_fluid_wagon" },
		mined_sound = { filename = "__core__/sound/deconstruct-large.ogg", volume = 0.8 },
		max_health = 600,
		corpse = "fluid-wagon-remnants",
		dying_explosion = "fluid-wagon-explosion",
		collision_box = { { -0.6, -2.4 }, { 0.6, 2.4 } },
		selection_box = { { -1, -2.7 }, { 1, 3.3 } },
		--damaged_trigger_effect = hit_effects.entity(),
		vertical_selection_shift = -0.5,
		weight = 500,
		max_speed = 1.7,
		braking_force = 25,
		friction_force = 0.40,
		air_resistance = 0.0050,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
		capacity = 50000,
		resistances = {
			{ type = "fire", decrease = 15, percent = 90 },
			{ type = "physical", decrease = 15, percent = 20 },
			{ type = "impact", decrease = 50, percent = 40 },
			{ type = "explosion", decrease = 15, percent = 30 },
			{ type = "acid", decrease = 3, percent = 90 },
		},
		--back_light = rolling_stock_back_light(),
		stand_by_light = rolling_stock_stand_by_light(),
		color = { r = 0.333, g = 0.768, b = 0.913 },
		pictures = {
			rotated = {
				layers = {
					{
						dice = 4,
						priority = "very-low",
						width = 240,
						height = 224,
						direction_count = 256,
						allow_low_quality_rotation = true,
						filenames = {
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-1.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-2.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-3.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-4.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-5.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-6.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-7.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-8.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-9.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-10.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-11.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-12.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-13.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-14.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-15.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/generic-fluid-wagon-16.png",
						},
						line_length = 4,
						lines_per_file = 4,
						shift = util.by_pixel(0, -5),
					},

					{
						priority = "very-low",
						dice = 4,
						flags = { "shadow" },
						width = 480,
						height = 448,
						direction_count = 256,
						draw_as_shadow = true,
						allow_low_quality_rotation = true,
						filenames = {
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-1.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-2.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-3.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-4.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-5.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-6.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-7.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-8.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-9.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-10.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-11.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-12.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-13.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-14.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-15.png",
							"__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/sh-16.png",
						},
						line_length = 4,
						lines_per_file = 4,
						scale = 0.55,
						shift = util.by_pixel(48, 12),
					},
				},
			},
		},
		minimap_representation = {
			filename = "__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/icon-map.png",
			flags = { "icon" },
			size = { 20, 44 },
			scale = 0.4,
		},
		selected_minimap_representation = {
			filename = "__zzzparanoidal__/graphics/train/hiend/ht-generic-fluid-wagon/icon-map-selected.png",
			flags = { "icon" },
			size = { 20, 44 },
			scale = 0.4,
		},
		--wheels = standard_train_wheels,
		drive_over_tie_trigger = drive_over_tie(),
		tie_distance = 50,
		crash_trigger = crash_trigger(),
		open_sound = sounds.cargo_wagon_open,
		close_sound = sounds.cargo_wagon_close,
		sound_minimum_speed = 1,
		vehicle_impact_sound = sounds.generic_impact,
		water_reflection = locomotive_reflection(),
		equipment_grid = "large-equipment-grid",
	},
})
