Settings = require("scripts.settings")

data:extend({
  {
    type = "string-setting",
    name = Settings.PollutionLayer,
    setting_type = "runtime-global",
    order = "a",
    default_value = "arrow",
    allowed_values = {
      "smoke",
      "air-object",
      "air-entity-info-icon",
      "light-effect",
      "selection-box",
      "higher-selection-box",
      "collision-selection-box",
      "arrow",
      "cursor",
    },
  },
  {
    type = "double-setting",
    name = Settings.PollutionOpacity,
    setting_type = "runtime-global",
    order = "b",
    default_value = 0.75,
    minimum_value = 0.01,
    maximum_value = 1.0,
  },
  {
    type = "double-setting",
    name = Settings.PollutionSeeThroughMaxOpacity,
    setting_type = "runtime-global",
    order = "c",
    default_value = 0.25,
    minimum_value = 0.01,
    maximum_value = 1.0,
  },
  {
    type = "int-setting",
    name = Settings.MinConsideredPollution,
    setting_type = "runtime-global",
    order = "d",
    default_value = 2,
    minimum_value = 1,
    maximum_value = 1000,
  },
  {
    type = "int-setting",
    name = Settings.MaxConsideredPollution,
    setting_type = "runtime-global",
    order = "e",
    default_value = 900,
    minimum_value = 20,
  },
  {
    type = "double-setting",
    name = Settings.PollutionRangeExponent,
    setting_type = "runtime-global",
    order = "f",
    default_value = 0.4,
    minimum_value = 0.01,
    maximum_value = 2.0,
  },
  {
    type = "double-setting",
    name = Settings.BlendInAmount,
    setting_type = "runtime-global",
    order = "g",
    default_value = 0.15,
    minimum_value = 0.01,
    maximum_value = 1.0,
  },
  {
    type = "int-setting",
    name = Settings.MaxLifetimeMinutes,
    setting_type = "runtime-global",
    order = "h",
    default_value = 10,
    minimum_value = 1,
  },
  {
    type = "int-setting",
    name = Settings.MaxSpriteUpdatesPerTick,
    setting_type = "runtime-global",
    order = "i",
    default_value = 20,
    minimum_value = 5,
  },
  {
    type = "bool-setting",
    name = Settings.UpdateChartColors,
    setting_type = "startup",
    order = "j",
    default_value = true,
  },
  {
    type = "string-setting",
    name = Settings.AddToPlanets,
    setting_type = "startup",
    order = "k",
    default_value = "",
    allow_blank = true,
  },
  {
    type = "bool-setting",
    name = Settings.EnableSolarOcclusion,
    setting_type = "runtime-global",
    order = "l",
    default_value = true,
  },
  {
    type = "double-setting",
    name = Settings.SolarEfficiencyReduction,
    setting_type = "runtime-global",
    order = "m",
    default_value = 0.5,
    minimum_value = 0.01,
    maximum_value = 3.0,
  },
  {
    type = "int-setting",
    name = Settings.MaxSolarUpdatesPerTick,
    setting_type = "runtime-global",
    order = "n",
    default_value = 10,
    minimum_value = 5,
  },
})
