return
{
  entities =
  {
    {"assembling-machine-1", {x = -2.5, y = -5.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 1.5, y = -6.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 0.5, y = -6.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 3.5, y = -6.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 2.5, y = -6.5}, {dir = "east", dead = 0.3}},
    {"transport-belt", {x = 5.5, y = -6.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 4.5, y = -6.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"small-electric-pole-remnants", {x = -0.5, y = -5.5}, {}},
    {"inserter", {x = -0.5, y = -4.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 0.5, y = -5.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"underground-belt", {x = 0.5, y = -4.5}, {dead = 1, dir = "south"}},
    {"wooden-chest", {x = 4.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"assembling-machine-1", {x = -2.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"inserter", {x = -1.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"inserter", {x = 0.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"assembling-machine-1", {x = 1.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"small-electric-pole-remnants", {x = 5.5, y = -3.5}, {}},
    {"inserter", {x = 4.5, y = -3.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"assembling-machine-1", {x = 5.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"inserter", {x = -0.5, y = -1.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"small-electric-pole-remnants", {x = -0.5, y = -0.5}, {}},
    {"inserter", {x = 3.5, y = -1.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = -4.5, y = 1.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = -5.5, y = 1.5}, {dir = "east", dead = 0.3}},
    {"inserter", {x = -2.5, y = 0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = -2.5, y = 1.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = -3.5, y = 1.5}, {dir = "east", dead = 0.3}},
    {"underground-belt", {x = 0.5, y = 0.5}, {dead = 1}},
    {"transport-belt", {x = 0.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"small-electric-pole-remnants", {x = 3.5, y = 0.5}, {}},
    {"inserter", {x = 5.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"assembling-machine-1", {x = 5.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"small-electric-pole-remnants", {x = -1.5, y = 2.5}, {}},
    {"transport-belt", {x = 0.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 0.5, y = 3.5}, {dead = 0.3}},
    {"transport-belt", {x = 1.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 2.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 3.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"iron-chest", {x = 2.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"inserter", {x = 3.5, y = 2.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = -4.5, y = 4.5}, {dir = "east", dead = 0.3}},
    {"transport-belt", {x = -5.5, y = 4.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"assembling-machine-1", {x = -1.5, y = 6.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = -2.5, y = 4.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = -3.5, y = 4.5}, {dir = "east", dead = 0.3}},
    {"transport-belt", {x = -0.5, y = 4.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = -1.5, y = 4.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 1.5, y = 4.5}, {dir = "east", dead = 0.3}},
    {"transport-belt", {x = 0.5, y = 4.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 3.5, y = 4.5}, {dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 2.5, y = 5.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 2.5, y = 4.5}, {dir = "south", dead = 0.3}},
    {"transport-belt", {x = 4.5, y = 4.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
    {"transport-belt", {x = 5.5, y = 4.5}, {dir = "west", dead = 0.3}},
    {"small-electric-pole-remnants", {x = -3.5, y = 7.5}, {}},
    {"transport-belt", {x = 2.5, y = 6.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 100}}, dead = 0.3}},
  },
}
