return
{
  entities =
  {
    {"nuclear-reactor-remnants", {x = 3.5, y = -4.5}, {}},
    {"medium-electric-pole-remnants", {x = 6.5, y = -7.5}, {}},
    {"pipe", {x = -6.5, y = -4.5}, {dead = 0.4}},
    {"steam-turbine", {x = -3.5, y = -4.5}, {dir = "east", dead = 0.6}},
    {"heat-exchanger", {x = 0, y = -4.5}, {dir = "west", dead = 0.6}},
    {"inserter", {x = 6.5, y = -5.5}, {dir = "east", dead = 0.4}},
    {"inserter", {x = 6.5, y = -4.5}, {dir = "west", dead = 0.4}},
    {"iron-chest", {x = 7.5, y = -4.5}, {items = {["used-up-uranium-fuel-cell"] = {type = "random", min = 1, max = 3}}, dead = 0.1}},
    {"iron-chest", {x = 7.5, y = -5.5}, {items = {["uranium-ore"] = {type = "random", min = 4, max = 13}}, dead = 0.1}},
    {"pipe", {x = -5.5, y = -2.5}, {dead = 0.4}},
    {"pipe", {x = -6.5, y = -2.5}, {dead = 0.4}},
    {"pipe", {x = -6.5, y = -3.5}, {dead = 0.4}},
    {"pipe", {x = -4.5, y = -2.5}, {dead = 0.4}},
    {"pipe", {x = -0.5, y = -2.5}, {dead = 0.4}},
    {"pipe", {x = 0.5, y = -2.5}, {dead = 0.4}},
    {"pipe-to-ground", {x = -7.5, y = -1.5}, {dir = "west", dead = 0.4}},
    {"steam-turbine", {x = -4.5, y = 0.5}, {dead = 0.6}},
    {"pipe-to-ground", {x = -1.5, y = -1.5}, {dir = "east", dead = 0.4}},
    {"pipe", {x = -0.5, y = -1.5}, {dead = 0.4}},
    {"heat-exchanger", {x = 1.5, y = -1}, {dir = "south", dead = 0.6}},
    {"pipe", {x = 3.5, y = -1.5}, {dead = 0.4}},
    {"heat-exchanger", {x = 5.5, y = -1}, {dir = "south", dead = 0.6}},
    {"substation-remnants", {x = -2, y = 2}, {}},
    {"steam-turbine", {x = 1.5, y = 2.5}, {dead = 0.6}},
    {"steam-turbine", {x = 5.5, y = 2.5}, {dead = 0.6}},
    {"steam-turbine", {x = -1.5, y = 6.5}, {dir = "east", dead = 0.6}},
    {"pipe", {x = 2.5, y = 5.5}, {dead = 0.4}},
    {"pipe", {x = 1.5, y = 5.5}, {dead = 0.4}},
    {"pipe", {x = 4.5, y = 5.5}, {dead = 0.4}},
    {"pipe", {x = 3.5, y = 5.5}, {dead = 0.4}},
    {"pipe", {x = 5.5, y = 5.5}, {dead = 0.4}},
    {"pipe", {x = 1.5, y = 6.5}, {dead = 0.4}},
  },
}
