return
{
  entities =
  {
    {"small-biter-corpse", {x = -4.26, y = -5.59}, {dir = "south", }},
    {"land-mine-remnants", {x = -2.61, y = -4.84}, {}},
    {"medium-biter-corpse", {x = -0.13, y = -5.74}, {dir = "south", }},
    {"medium-scorchmark", {x = 4.02, y = -2.04}, {dir = "south", }},
    {"small-biter-corpse", {x = 2.56, y = -4.2}, {dir = "south", }},
    {"land-mine-remnants", {x = 3.08, y = -4.72}, {}},
    {"small-biter-corpse", {x = 4.03, y = -5.61}, {dir = "south", }},
    {"small-biter-corpse", {x = -5.77, y = -3.45}, {dir = "south", }},
    {"land-mine-remnants", {x = -0.13, y = -3.77}, {}},
    {"land-mine-remnants", {x = -0.98, y = -2.46}, {}},
    {"small-biter-corpse", {x = 1.95, y = -2.54}, {dir = "south", }},
    {"medium-biter-corpse", {x = 4.89, y = -3.46}, {dir = "south", }},
    {"land-mine-remnants", {x = 4.86, y = -2.54}, {}},
    {"medium-biter-corpse", {x = -4.8, y = -1.49}, {dir = "south", }},
    {"land-mine-remnants", {x = -5.93, y = -1.65}, {}},
    {"small-biter-corpse", {x = -2.45, y = -1.43}, {dir = "south", }},
    {"land-mine-remnants", {x = -3.93, y = -1.07}, {}},
    {"land-mine-remnants", {x = 3.5, y = -0.96}, {}},
    {"wall-remnants", {x = -6.5, y = 1.5}, {dir = "south", }},
    {"wall-remnants", {x = -4.5, y = 1.5}, {dir = "south", }},
    {"wall-remnants", {x = -5.5, y = 1.5}, {dir = "south", }},
    {"small-biter-corpse", {x = -2.96, y = 1.61}, {dir = "south", }},
    {"wall-remnants", {x = -2.5, y = 0.5}, {dir = "south", }},
    {"wall-remnants", {x = -3.5, y = 0.5}, {dir = "south", }},
    {"wall-remnants", {x = -3.5, y = 1.5}, {}},
    {"stone-wall", {x = -1.5, y = 0.5}, {}},
    {"stone-wall", {x = -0.5, y = 0.5}, {}},
    {"small-scorchmark", {x = 3.37, y = 2.96}, {dir = "south", }},
    {"wall-remnants", {x = 1.5, y = 0.5}, {dir = "south", }},
    {"stone-wall", {x = 0.5, y = 0.5}, {}},
    {"wall-remnants", {x = 3.5, y = 0.5}, {dir = "south", }},
    {"wall-remnants", {x = 2.5, y = 0.5}, {dir = "south", }},
    {"wall-remnants", {x = 5.5, y = 0.5}, {dir = "south", }},
    {"wall-remnants", {x = 4.5, y = 0.5}, {dir = "south", }},
    {"wall-remnants", {x = 6.5, y = 0.5}, {dir = "south", }},
    {"small-scorchmark", {x = -2.98, y = 5.35}, {dir = "south", }},
    {"flamethrower-turret-remnants", {x = 3, y = 3.5}, {}},
    {"medium-biter-corpse", {x = 5.04, y = 2.15}, {dir = "south", }},
    {"pipe-remnants", {x = -5.5, y = 5.5}, {dir = "south", }},
    {"pipe-remnants", {x = -4.5, y = 5.5}, {dir = "south", }},
    {"flamethrower-turret-remnants", {x = -3, y = 4.5}, {}},
    {"pipe-remnants", {x = -1.5, y = 5.5}, {dir = "south", }},
    {"pipe", {x = -0.5, y = 5.5}, {}},
    {"pipe-remnants", {x = 1.5, y = 5.5}, {dir = "south", }},
    {"pipe-remnants", {x = 1.5, y = 4.5}, {}},
    {"pipe", {x = 0.5, y = 5.5}, {}},
    {"pipe-remnants", {x = 4.5, y = 5.5}, {}},
    {"pipe-remnants", {x = 4.5, y = 4.5}, {}},
    {"flamethrower-turret-remnants", {x = 6, y = 4.5}, {}},
    {"pipe-remnants", {x = 4.5, y = 7.5}, {}},
    {"pipe-remnants", {x = 4.5, y = 6.5}, {}},
  },
}
