return
{
  entities =
  {
    {"wall-remnants", {x = -2.5, y = -7.5}, {dir = "south", }},
    {"wall-remnants", {x = -2.5, y = -6.5}, {}},
    {"wall-remnants", {x = -1.5, y = -6.5}, {dir = "south", }},
    {"land-mine-remnants", {x = 1.5, y = -6.5}, {dir = "west", }},
    {"medium-biter-corpse", {x = 1.68, y = -6.21}, {dir = "west", }},
    {"gun-turret-remnants", {x = -6, y = -6}, {dir = "east", }},
    {"stone-wall", {x = -0.5, y = -4.5}, {}},
    {"stone-wall", {x = -0.5, y = -5.5}, {}},
    {"stone-wall", {x = 0.5, y = -4.5}, {}},
    {"small-biter-corpse", {x = 4.45, y = -4.24}, {dir = "west", }},
    {"iron-chest-remnants", {x = -6.5, y = -2.5}, {dir = "east", }},
    {"inserter-remnants", {x = -5.5, y = -2.5}, {dir = "west", }},
    {"stone-wall", {x = 0.5, y = -2.5}, {}},
    {"stone-wall", {x = 0.5, y = -3.5}, {}},
    {"small-biter-corpse", {x = 2.71, y = -2.81}, {dir = "west", }},
    {"land-mine-remnants", {x = 6.5, y = -3.5}, {dir = "west", }},
    {"gun-turret-remnants", {x = -4, y = -2}, {dir = "east", }},
    {"wall-remnants", {x = -0.5, y = -0.5}, {dir = "south", }},
    {"medium-biter-corpse", {x = -1.73, y = -0.07}, {dir = "east", }},
    {"wall-remnants", {x = 0.5, y = -1.5}, {}},
    {"land-mine-remnants", {x = 1.5, y = -0.5}, {dir = "west", }},
    {"medium-biter-corpse", {x = 4.85, y = -0.3}, {dir = "east", }},
    {"wall-remnants", {x = -1.5, y = 0.5}, {dir = "south", }},
    {"wall-remnants", {x = -1.5, y = 1.5}, {}},
    {"wall-remnants", {x = -1.5, y = 2.5}, {}},
    {"stone-wall", {x = -1.5, y = 3.5}, {}},
    {"small-biter-corpse", {x = 0.14, y = 2.39}, {dir = "west", }},
    {"small-biter-corpse", {x = 2.1, y = 3.27}, {dir = "west", }},
    {"big-biter-corpse", {x = 4.94, y = 2.01}, {dir = "west", }},
    {"gun-turret-remnants", {x = -6, y = 4}, {dir = "east", }},
    {"wall-remnants", {x = -0.5, y = 5.5}, {}},
    {"stone-wall", {x = -1.5, y = 4.5}, {}},
    {"land-mine-remnants", {x = 1.5, y = 4.5}, {dir = "west", }},
    {"medium-biter-corpse", {x = 3.17, y = 5.94}, {dir = "west", }},
    {"land-mine-remnants", {x = 4.5, y = 5.5}, {dir = "west", }},
    {"gun-turret-remnants", {x = -4, y = 7}, {dir = "east", }},
    {"stone-wall", {x = -0.5, y = 6.5}, {}},
    {"wall-remnants", {x = 0.5, y = 7.5}, {}},
    {"stone-wall", {x = 0.5, y = 6.5}, {}},
  },
}
