return
{
  entities =
  {
    {"tree-05", {x = -1.5, y = -2.5}, {}},
    {"tree-05", {x = 0.5, y = -2.5}, {}},
  },
  tiles =
  {
    {"water", {x = -5, y = -5}},
    {"water", {x = -5, y = -4}},
    {"water", {x = -5, y = -3}},
    {"water", {x = -5, y = -2}},
    {"water", {x = -5, y = -1}},
    {"water", {x = -5, y = 0}},
    {"water", {x = -5, y = 1}},
    {"water", {x = -5, y = 2}},
    {"water", {x = -5, y = 3}},
    {"water", {x = -5, y = 4}},
    {"water", {x = -4, y = -5}},
    {"water", {x = -4, y = -4}},
    {"water", {x = -4, y = -3}},
    {"water", {x = -4, y = -2}},
    {"water", {x = -4, y = -1}},
    {"water", {x = -4, y = 0}},
    {"water", {x = -4, y = 1}},
    {"water", {x = -4, y = 2}},
    {"water", {x = -4, y = 3}},
    {"water", {x = -4, y = 4}},
    {"water", {x = -3, y = -5}},
    {"water", {x = -3, y = -4}},
    {"water", {x = -3, y = 0}},
    {"water", {x = -3, y = 1}},
    {"water", {x = -3, y = 2}},
    {"water", {x = -3, y = 3}},
    {"water", {x = -3, y = 4}},
    {"water", {x = -2, y = -5}},
    {"water", {x = -2, y = -4}},
    {"water", {x = -2, y = 0}},
    {"water", {x = -2, y = 1}},
    {"water", {x = -2, y = 2}},
    {"water", {x = -2, y = 3}},
    {"water", {x = -2, y = 4}},
    {"water", {x = -1, y = -5}},
    {"water", {x = -1, y = -4}},
    {"water", {x = 0, y = -5}},
    {"water", {x = 0, y = -4}},
    {"water", {x = 1, y = -5}},
    {"water", {x = 1, y = -4}},
    {"water", {x = 1, y = 0}},
    {"water", {x = 1, y = 1}},
    {"water", {x = 1, y = 2}},
    {"water", {x = 1, y = 3}},
    {"water", {x = 1, y = 4}},
    {"water", {x = 2, y = -5}},
    {"water", {x = 2, y = -4}},
    {"water", {x = 2, y = 0}},
    {"water", {x = 2, y = 1}},
    {"water", {x = 2, y = 2}},
    {"water", {x = 2, y = 3}},
    {"water", {x = 2, y = 4}},
    {"water", {x = 3, y = -5}},
    {"water", {x = 3, y = -4}},
    {"water", {x = 3, y = -3}},
    {"water", {x = 3, y = -2}},
    {"water", {x = 3, y = -1}},
    {"water", {x = 3, y = 0}},
    {"water", {x = 3, y = 1}},
    {"water", {x = 3, y = 2}},
    {"water", {x = 3, y = 3}},
    {"water", {x = 3, y = 4}},
    {"water", {x = 4, y = -5}},
    {"water", {x = 4, y = -4}},
    {"water", {x = 4, y = -3}},
    {"water", {x = 4, y = -2}},
    {"water", {x = 4, y = -1}},
    {"water", {x = 4, y = 0}},
    {"water", {x = 4, y = 1}},
    {"water", {x = 4, y = 2}},
    {"water", {x = 4, y = 3}},
    {"water", {x = 4, y = 4}},
  }
}
