return
{
  entities =
  {
    {"pipe-remnants", {x = -4.5, y = -6.5}, {dir = "south", }},
    {"pipe", {x = -5.5, y = -6.5}, {}},
    {"medium-electric-pole-remnants", {x = -2.5, y = -6.5}, {}},
    {"chemical-plant", {x = -6.5, y = -4.5}, {recipe = "sulfuric-acid", }},
    {"transport-belt-remnants", {x = -2.5, y = -5.5}, {dir = "east", }},
    {"electric-mining-drill", {x = -1.5, y = -3.5}, {dmg = {dmg = {type="random", min = 39, max = 120}}, }},
    {"transport-belt-remnants", {x = -1.5, y = -5.5}, {dir = "east", }},
    {"transport-belt", {x = -0.5, y = -5.5}, {dir = "east", }},
    {"transport-belt", {x = 1.5, y = -5.5}, {dir = "east", }},
    {"transport-belt", {x = 0.5, y = -5.5}, {dir = "east", }},
    {"electric-mining-drill", {x = 3.5, y = -3.5}, {}},
    {"transport-belt", {x = 2.5, y = -5.5}, {dir = "east", }},
    {"long-handed-inserter", {x = 4.5, y = -5.5}, {dir = "west", }},
    {"centrifuge", {x = 6.5, y = -4.5}, {recipe = "uranium-processing", }},
    {"pipe", {x = -5.5, y = -2.5}, {}},
    {"pipe", {x = 0.5, y = -3.5}, {}},
    {"pipe", {x = 1.5, y = -3.5}, {}},
    {"pipe", {x = -4.5, y = -1.5}, {}},
    {"pipe", {x = -5.5, y = -1.5}, {}},
    {"electric-mining-drill", {x = -3.5, y = 0.5}, {dir = "south", }},
    {"pipe", {x = -3.5, y = -1.5}, {}},
    {"pipe", {x = -2.5, y = -1.5}, {}},
    {"medium-electric-pole-remnants", {x = -1.5, y = -0.5}, {}},
    {"pipe", {x = -1.5, y = -1.5}, {}},
    {"pipe", {x = -0.5, y = -1.5}, {}},
    {"pipe", {x = 0.5, y = -1.5}, {}},
    {"pipe", {x = 1.5, y = -1.5}, {}},
    {"pipe", {x = 2.5, y = -0.5}, {}},
    {"pipe", {x = 2.5, y = -1.5}, {}},
    {"pipe", {x = 3.5, y = -1.5}, {}},
    {"transport-belt", {x = 5.5, y = -0.5}, {}},
    {"medium-electric-pole-remnants", {x = 7.5, y = -1.5}, {}},
    {"pipe", {x = -1.5, y = 0.5}, {}},
    {"electric-mining-drill-remnants", {x = 0.5, y = 0.5}, {dir = "south", }},
    {"pipe-remnants", {x = 2.5, y = 0.5}, {}},
    {"transport-belt", {x = 5.5, y = 0.5}, {}},
    {"transport-belt", {x = 5.5, y = 1.5}, {}},
    {"transport-belt", {x = -2.5, y = 2.5}, {dir = "east", }},
    {"transport-belt", {x = -3.5, y = 2.5}, {dir = "east", }},
    {"medium-electric-pole-remnants", {x = -0.5, y = 3.5}, {}},
    {"transport-belt", {x = -0.5, y = 2.5}, {dir = "east", }},
    {"transport-belt", {x = -1.5, y = 2.5}, {dir = "east", }},
    {"transport-belt", {x = 1.5, y = 2.5}, {dir = "east", }},
    {"transport-belt", {x = 0.5, y = 2.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 2.5, y = 2.5}, {dir = "east", }},
    {"inserter", {x = 2.5, y = 3.5}, {}},
    {"transport-belt", {x = 3.5, y = 2.5}, {dir = "east", }},
    {"inserter-remnants", {x = 5.5, y = 3.5}, {}},
    {"transport-belt-remnants", {x = 5.5, y = 2.5}, {}},
    {"transport-belt-remnants", {x = 4.5, y = 2.5}, {dir = "east", }},
    {"wooden-chest", {x = -2.5, y = 4.5}, {items = {["uranium-ore"] = {type="random", min = 3, max = 30}}, }},
    {"centrifuge", {x = 1.5, y = 5.5}, {dead = 0.5}},
    {"centrifuge-remnants", {x = 5.5, y = 5.5}, {}},
  },
}
