local function remove_utility_sound(name)
    data.raw["utility-sounds"]["default"][name] =
        {{filename = "__1000sounds__/sound/silence.ogg"}}
end

remove_utility_sound("console_message");
remove_utility_sound("game_lost");
remove_utility_sound("research_completed");

data:extend({{
    type="explosion",
    name="sfx_debug",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/debug.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_debug",
    filename="__1000sounds__/sound/debug.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_doom_death1",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/doom/death1.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_doom_death1",
    filename="__1000sounds__/sound/doom/death1.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_doom_death2",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/doom/death2.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_doom_death2",
    filename="__1000sounds__/sound/doom/death2.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_doom_injured",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/doom/injured.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_doom_injured",
    filename="__1000sounds__/sound/doom/injured.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_doom_teleport",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/doom/teleport.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_doom_teleport",
    filename="__1000sounds__/sound/doom/teleport.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_balls_of_steel",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/balls_of_steel.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_balls_of_steel",
    filename="__1000sounds__/sound/dukenukem/balls_of_steel.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_birth_control",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/birth_control.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_birth_control",
    filename="__1000sounds__/sound/dukenukem/birth_control.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_have_a_taste_of_my_ball",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/have_a_taste_of_my_ball.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_have_a_taste_of_my_ball",
    filename="__1000sounds__/sound/dukenukem/have_a_taste_of_my_ball.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_holy_cow",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/holy_cow.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_holy_cow",
    filename="__1000sounds__/sound/dukenukem/holy_cow.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_holy_shit",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/holy_shit.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_holy_shit",
    filename="__1000sounds__/sound/dukenukem/holy_shit.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_i_like_big_guns",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/i_like_big_guns.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_i_like_big_guns",
    filename="__1000sounds__/sound/dukenukem/i_like_big_guns.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_ive_got_balls_of_steel",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/ive_got_balls_of_steel.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_ive_got_balls_of_steel",
    filename="__1000sounds__/sound/dukenukem/ive_got_balls_of_steel.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_looks_like_youre_fd",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/looks_like_youre_fd.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_looks_like_youre_fd",
    filename="__1000sounds__/sound/dukenukem/looks_like_youre_fd.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_now_im_really_pissed_off",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/now_im_really_pissed_off.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_now_im_really_pissed_off",
    filename="__1000sounds__/sound/dukenukem/now_im_really_pissed_off.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_ooooh_thats_gotta_hurt",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/ooooh_thats_gotta_hurt.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_ooooh_thats_gotta_hurt",
    filename="__1000sounds__/sound/dukenukem/ooooh_thats_gotta_hurt.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_restinpeaces",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/restinpeaces.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_restinpeaces",
    filename="__1000sounds__/sound/dukenukem/restinpeaces.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_shit_happens",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/shit_happens.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_shit_happens",
    filename="__1000sounds__/sound/dukenukem/shit_happens.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_something_smells_rotten",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/something_smells_rotten.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_something_smells_rotten",
    filename="__1000sounds__/sound/dukenukem/something_smells_rotten.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_dukenukem_wasted",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/dukenukem/wasted.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_dukenukem_wasted",
    filename="__1000sounds__/sound/dukenukem/wasted.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_other_locomotive",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/other/locomotive.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_other_locomotive",
    filename="__1000sounds__/sound/other/locomotive.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_other_manlyscream",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/other/manlyscream.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_other_manlyscream",
    filename="__1000sounds__/sound/other/manlyscream.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_other_roadrunner",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/other/roadrunner.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_other_roadrunner",
    filename="__1000sounds__/sound/other/roadrunner.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_other_sadtrombone",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/other/sadtrombone.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_other_sadtrombone",
    filename="__1000sounds__/sound/other/sadtrombone.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_other_wilhelm_scream",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/other/wilhelm_scream.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_other_wilhelm_scream",
    filename="__1000sounds__/sound/other/wilhelm_scream.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_feedback_accuracy",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/feedback/accuracy.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_feedback_accuracy",
    filename="__1000sounds__/sound/quake3/feedback/accuracy.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_feedback_denied",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/feedback/denied.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_feedback_denied",
    filename="__1000sounds__/sound/quake3/feedback/denied.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_feedback_excellent",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/feedback/excellent.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_feedback_excellent",
    filename="__1000sounds__/sound/quake3/feedback/excellent.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_feedback_fight",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/feedback/fight.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_feedback_fight",
    filename="__1000sounds__/sound/quake3/feedback/fight.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_feedback_humiliation",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/feedback/humiliation.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_feedback_humiliation",
    filename="__1000sounds__/sound/quake3/feedback/humiliation.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_feedback_impressive",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/feedback/impressive.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_feedback_impressive",
    filename="__1000sounds__/sound/quake3/feedback/impressive.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_feedback_perfect",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/feedback/perfect.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_feedback_perfect",
    filename="__1000sounds__/sound/quake3/feedback/perfect.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_feedback_prepare",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/feedback/prepare.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_feedback_prepare",
    filename="__1000sounds__/sound/quake3/feedback/prepare.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_player_talk",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/player/talk.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_player_talk",
    filename="__1000sounds__/sound/quake3/player/talk.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_world_telein",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/world/telein.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_world_telein",
    filename="__1000sounds__/sound/quake3/world/telein.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_quake3_world_teleout",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/quake3/world/teleout.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_quake3_world_teleout",
    filename="__1000sounds__/sound/quake3/world/teleout.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_silence",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__1000sounds__/sound/silence.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_silence",
    filename="__1000sounds__/sound/silence.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_factorio_core_console-message",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__core__/sound/console-message.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_factorio_core_console-message",
    filename="__core__/sound/console-message.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_factorio_core_game-lost",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__core__/sound/game-lost.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_factorio_core_game-lost",
    filename="__core__/sound/game-lost.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_factorio_core_message",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__core__/sound/message.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_factorio_core_message",
    filename="__core__/sound/message.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_factorio_core_research-completed",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__core__/sound/research-completed.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_factorio_core_research-completed",
    filename="__core__/sound/research-completed.ogg",
    volume=1.0
}})
data:extend({{
    type="explosion",
    name="sfx_factorio_core_scenario-message",
    flags={"not-on-map"},
    animations={{filename="__core__/graphics/empty.png",priority="low",width=1,height=1,frame_count=1,line_length=1,animation_speed=1}},
    light={intensity=0,size=0},
    sound={{filename="__core__/sound/scenario-message.ogg",volume=1.0}}
}})
data:extend({{
    type="sound",
    name="sound_sfx_factorio_core_scenario-message",
    filename="__core__/sound/scenario-message.ogg",
    volume=1.0
}})
