TechnologyCycleRemovingBean = {}
TechnologyCycleRemovingBean.technology_datas = data.raw["technology"]
TechnologyCycleRemovingBean.removePrerequisitesForCycleNormal = function(mode)
    --[[techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['gas-steam-cracking-2'],
        { 'angels-advanced-chemistry-2' },
        mode)
    techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['resin-1'],
        { 'resins' },
        mode)]]

    --[[techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['advanced-electronics'],
        {
            "offshore-pump-2"
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['angels-invar-smelting-1'],
        {
            "angels-metallurgy-2",
            "water-treatment-2"
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['angels-nickel-smelting-1'],
        {
            "angels-metallurgy-2"
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['angels-zinc-smelting-1'],
        {
            "angels-metallurgy-2"
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['angels-sulfur-processing-1'],
        {
            "water-treatment-2"
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['zinc-processing'],
        {
            "water-treatment-2"
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['titanium-processing'],
        {
            'angels-metallurgy-3'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['angels-titanium-smelting-1'],
        {
            'angels-metallurgy-3'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(TechnologyCycleRemovingBean.technology_datas['geode-crystallization-1'],
        {
            'geode-processing-2'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['bio-temperate-farm'],
        {
            'bio-processing-paste'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['bio-farm-alien'],
        {
            'bio-processing-paste'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['bio-desert-farm'],
        {
            'bio-processing-paste'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['bio-processing-alien-1'],
        {
            'bio-processing-paste'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['bio-temperate-farm'],
        {
            'bio-processing-alien-1'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['bio-farm-alien'],
        {
            'bio-processing-alien-1'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['bio-desert-farm'],
        {
            'bio-processing-alien-1'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['bio-processing-crystal-splinter-2'],
        {
            'bio-processing-alien-1'
        },
        mode)
    techUtil.removePrerequisitesFromTechnology(
        TechnologyCycleRemovingBean.technology_datas['modules'],
        {
            'bio-processing-alien-1'
        },
        mode)]]
end
