ColorTIER_path = "__ColorTIERHR__"
require('prototypes/functions/function')
require('prototypes/functions/accumulatorsfunc')
require('prototypes/functions/dataraw_furnacefans')


require('prototypes/accumulators')
require('prototypes/assemblers')
--require('prototypes/electrolysers')
--require('prototypes/steam-engines')
--require('prototypes/steam-turbines')
require('prototypes/beacons')
--require('prototypes/boilers')
require('prototypes/heat-exchangers')
--require('prototypes/storage-tank')
require('prototypes/medium-poles')
require('prototypes/big-poles')
require('prototypes/substations')
require('prototypes/airpumps')
require('prototypes/pumps')
--require('prototypes/oil-refineries')
--require('prototypes/chemical-plants')
require('prototypes/artillery-turrets')
--require('prototypes/roboports')
require('prototypes/furnaces')
require('prototypes/logistic-chests')
require('prototypes/mining-drills')
require('prototypes/solor-panels')
require('prototypes/labs')
--require('prototypes/radars')