return {
    --modname                   --sprite                        button                                  tooltip                     dontreplacesprite   buttonpath (array)  windowtocheck (array)
    {"helmod",                  "helmod_button",                "helmod_planner-command",               {'guiu.helmod_button'},             nil,        nil,                {"screen", "HMProductionPanel"}},
    {"factoryplanner",          "factoryplanner_button",        "fp_button_toggle_interface",           {'guiu.factoryplanner_button'},     nil,        nil,                {"screen", "factoryplanner_mainframe"}},
    {"ModuleInserter",          "moduleinserter_button",        "module_inserter_config_button",        {'guiu.moduleinserter_button'},     nil,        nil,                {"screen", "moduleinserter_mainframe"}},
    {"Placeables",              "placeables_button",            "buttonPlaceablesVisible",              nil,                                nil,        nil,                {"screen", "framePlaceablesOuter"}},
    {"BeastFinder",             "beastfinder_button",           "beastfinder-menu-button",              {'guiu.beastfinder_button'},        nil,        nil,                {"screen", "frame_BeastFinder_main"}},
    {"bobclasses",              "bobclasses_button",            "bob_avatar_toggle_gui",                nil,                                nil,        nil,                {"left", "bob_avatar_gui"}},
    {"bobinserters",            "bobinserters_button",          "bob_logistics_inserter_button",        nil,                                nil,        nil,                {"left", "bob_logistics_inserter_gui"}},
    {"boblogistics",            "bobinserters_button",          "bob_logistics_inserter_button",        nil,                                nil,        nil,                {"left", "bob_logistics_inserter_gui"}},
    {"CleanMap",                "cleanmap_button",              "CleanMap",                             nil,                                nil,        nil,                nil},
    {"DeleteEmptyChunks",       "cleanmap_button",              "DeleteEmptyChunks",                    nil,                                nil,        nil,                nil},
    {"Death_Counter",           "deathcounter_button",          "DeathCounterMainButton",               {'guiu.deathcounter_button'},       nil,        nil,                {"left", "DeathCounterMain"}},
    {"ingteb",                  "ingteb_button",                "ingteb",                               nil,                                nil,        nil,                {"screen", "Selector"}},
    {"OutpostPlanner",          "outpostplanner_button",        "OutpostBuilder",                       nil,                                nil,        nil,                {"left", "mod_gui_frame_flow", "OutpostBuilderWindow"}},
    {"OutpostPlanner1-1",       "outpostplanner_button",        "OutpostBuilder",                       nil,                                nil,        nil,                {"left", "mod_gui_frame_flow", "OutpostBuilderWindow"}},
    {"rocket-silo-stats",       "rocketsilostats_button",       "rocket-silo-stats-toggle",             {'guiu.rocketsilostats_button'},    nil,        nil,                {"left", "mod_gui_frame_flow", "rocket-silo-stats"}},
    {"SchallSatelliteController","schall_sc_button",            "Schall-SC-mod-button",                 nil,                                nil,        nil,                {"screen", "Schall-SC-frame-main"}},
    {"actual-craft-times-remade","actr_button",                 "ACTR_mod_button",                      nil,                                nil,        nil,                {"left", "ACTR_Calculator_Frame"}},
    {"BetterBotsFixed",         "betterbotsfixed_button",       "betterbots_top_btn",                   {'guiu.betterbotsfixed_button'},    nil,        nil,                {"left", "mod_gui_frame_flow", "betterbots_left"}},
    {"ChangeMapSettings",       "changemapsettings_button",     "change-map-settings-toggle-config",    {'guiu.changemapsettings_button'},  nil,        nil,                {"screen", "change-map-settings-main-flow"}},
    {"DoingThingsByHand",       "doingthingsbyhand_button",     "DoingThingsByHandMainButton",          {'guiu.doingthingsbyhand_button'},  nil,        nil,                {"left", "DoingThingsByHandMain"}},
    {"FacAutoScreenshot",       "facautoscreenshot_button",     "togglegui",                            {'guiu.facautoscreenshot_button'},  nil,        nil,                {"screen", "guiFrame", "content_frame", "auto_frame"}},
    {"KillLostBots",            "killlostbots_button",          "KillLostBots",                         nil,                                nil,        nil,                nil},
    {"kraskaska-total-raw-resources-calc","kttrrc_button",      "ttrrc_main_frame_button",              {'guiu.kttrrc_button'},             nil,        nil,                {"left", "mod_gui_frame_flow", "ttrrc_main_frame"}},
    {"Kux-CraftingTools",       "kuxcraftingtools_button",      "CraftNearbyGhostItemsButton",          nil,                                nil,        nil,                nil},
    {"Kux-OrbitalIonCannon",    "kuxorbitalioncannon_button",   "ion-cannon-button",                    {'guiu.kuxorbitalioncannon_button'},nil,        nil,                {"left", "ion-cannon-stats"}},
    {"markers",                 "markers_button",               "markers_gui_toggle",                   {'guiu.markers_button'},            nil,        nil,                {"left", "mod_gui_frame_flow", "markers_gui"}},
    {"Not_Enough_Todo",         "notenoughtodo_button",         "TODO_CLICK01_",                        {'guiu.notenoughtodo_button'},      nil,        nil,                {"screen", "notenoughtodo_mainframe"}},
    {"osha_hot_swap",           "oshahotswap_button",           "hotswap-menu-button",                  {'guiu.oshahotswap_button'},        nil,        nil,                {"left", "hotswap-main-container"}},
    {"Powered_Entities",        "poweredentities_button",       "poweredEntitiesRecalculateButton",     {'guiu.poweredentities_button'},    nil,        nil,                nil},
    {"research-counter",        "researchcounter_button",       "research-counter-button",              {'guiu.researchcounter_button'},    nil,        nil,                {"screen", "research-counter-base"}},
    {"Rich_Text_Helper",        "richtexthelper_button",        "RICH_CLICK_20_player01",               {'guiu.richtexthelper_button'},     nil,        nil,                {"screen", "richtexthelper_mainframe"}},
    {"RitnTeleportation",       "ritnteleportation_button",     "ritn-button-main",                     {'guiu.ritnteleportation_button'},  nil,        nil,                {"left", "mod_gui_frame_flow", "menu-flow-common", "main_menu-frame-menu"}},
    {"solar-calc",              "solarcalc_button",             "kaktusbot-sc-open-calc-button",        {'guiu.solarcalc_button'},          nil,        nil,                {"screen", "kaktusbot-sc-main-gui"}},
    {"SolarRatio",              "solarcalc_button",             "niet-sr-guibutton",                    nil,                                nil,        nil,                {"center", "niet-sr-guiframe"}},
    {"SpaceMod",                "spacemod_button",              "space_toggle_button",                  {'guiu.spacemod_button'},           nil,        nil,                {"left", "mod_gui_frame_flow", "space_progress_frame"}},
    {"train-log",               "trainlog_button",              "train_log",                            nil,                                nil,        nil,                {"screen", "trainlog_mainframe"}},
    {"train-pubsub",            "trainpubsub_button",           "tm_sprite_button",                     nil,                                nil,        nil,                {"left", "mod_gui_frame_flow", "tm_button_frame"}},
    {"upgrade-planner-next",    "upgradeplannernext_button",    "upgrade_planner_config_button",        nil,                                nil,        nil,                {"left", "mod_gui_frame_flow", "upgrade_planner_config_frame"}},
    {"whats-missing",           "whatsmissing_button",          "whats-missing-button",                 nil,                                nil,        nil,                {"screen", "whats-missing-gui"}},
    {"PicksRocketStats",        "picksrocketstats_button",      "pi_rss_but_toggle",                    {'guiu.picksrocketstats_button'},   nil,        nil,                {"left", "mod_gui_frame_flow", "pi_rss_rocket-silo-stats"}},
    {"SchallRailwayController", "schall_rc_button",             "Schall-RC-mod-button",                 {'guiu.schall_rc_button'},          nil,        nil,                {"screen", "Schall-RC-frame-main"}},
    {"BlackMarket2",            "blackmarket1_button",          "but_blkmkt_main",                      {'guiu.blackmarket1_button'},       nil,        {"flw_blkmkt"},     {"left", "mod_gui_frame_flow", "frm_blkmkt_gen"}},
    {"BlackMarket2",            "blackmarket2_button",          "but_blkmkt_credits",                   nil,                                nil,        {"flw_blkmkt"},     {"left", "mod_gui_frame_flow", "frm_blkmkt_itml"}},
    {"AutoTrash",               "autotrash_button",             "at_config_button",                     nil,                                1,          nil,                nil},
    {"TogglePeacefulMode",      "togglepeacefulmode_button",    "tpm-button",                           {'guiu.togglepeacefulmode_button'}, 1,          nil,                nil},
    {"what-is-it-really-used-for","wiiuf_button",               "looking-glass",                        {'guiu.wiiuf_button'},              nil, {"wiiuf_flow", "search_flow"},{"screen", "wiiuf_center_frame"}},
    {"TheFatController",        "thefatcontroller_button",      "toggleTrainInfo",                      {'guiu.thefatcontroller_button'},   nil, {"fatControllerButtons"},  {"left", "fatController", "trainInfo"}},
    {"quickbarimportexport",    "quickbarimportexport_button",  "qbie_button_show_options",             nil,                                nil, {"qbie_flow_choose_action"},{"left", "mod_gui_frame_flow", "qbie_frame_main_window"}},
    {"quickbarimportexport",    "quickbarimport_button",        "qbie_button_import",                   nil,                                nil, {"qbie_flow_choose_action"},nil},
    {"quickbarimportexport",    "quickbarexport_button",        "qbie_button_export",                   nil,                                nil, {"qbie_flow_choose_action"},nil},
    {"informatron",             "informatron_button",           "informatron_overhead",                 nil,                                1,          nil,                {"screen", "informatron_main"}},
    {"space-exploration",       "se_interstellar_button",       "se-overhead_interstellar",             nil,                                1,          nil,                {"left", "se-remote-view", "system_toggles_table", "map_view_toggles", "show_danger_zones"}},
    {"space-exploration",       "se_satellite_button",          "se-overhead_satellite",                nil,                                1,          nil,                {"left", "se-remote-view"}},
    {"space-exploration",       "se_explorer_button",           "se-overhead_explorer",                 nil,                                1,          nil,                {"screen", "se-zonelist_main"}},
    {"CommuGuideMod",           "commuguidemod_guide_button",   "main_menu_guide_button",               {'guiu.commuguidemod_guide_button'},nil,        nil,                nil},
    {"CommuGuideMod",           "commuguidemod_pupil_button",   "main_menu_player_button",              {'guiu.commuguidemod_pupil_button'},nil,        nil,                nil},
    {"FJEI",                    "fjei_toggle_button",           "fjei_toggle_button",                   nil,                                1,          nil,                {"left", "fjei_main_window","fjei_main_window_control_table"}}, -- {"", ""}
    {"ToggleSpeedBoost",        "togglespeedboost_button",      "togglespeedboost_button",              nil,                                1,          nil,                nil},
    {"248k",                    "248k_button",                  "top248kbutton",                        {'guiu.248k_button'},               nil,        nil,                {"left", "main248kframe"}},
    {"BlueprintAlignment",      "blueprintalignment_button",    "BlueprintAlignment_Button",            nil,                                nil,        nil,                nil},
    {"CargoTrainManager",       "cargotrainmanager_button",     "ctm_toolbutton",                       nil,                                nil,        nil,                {"screen", "ctm_main_dialog"}},
    {"clusterio",               "clusterio_button",             "clusterio-main-config-gui-toggle-button",{'guiu.clusterio_button'},        nil,        nil,                {"top", "clusterio-main-config-gui"}},
    {"Cursed-Exp",              "cursedexp_button",             "openMain",                             {'guiu.cursedexp_button'},          nil,        {"openMainFlow"},   {"left", "flowMainOut", "frameMain"}},
    {"default-wait-conditions", "defaultwaitconditions_button", "default-wait-conditions-main-button",  nil,                                nil,        nil,                {"screen", "default-wait-conditions-main-frame"}},
    {"diplomacy",               "diplomacy_button",             "diplomacy_button",                     nil,                                nil,        nil,                {"screen", "diplomacy_frame"}},
    {"Electronic_Locomotives",  "electronic_locomotives_button","ELECTRONIC_CLICK01",                   {'guiu.electronic_locomotives_button'},nil,     nil,                {"screen", "ELECTRONIC_LOCATION"}},
    {"forces",                  "forces_button",                "forcesMenu",                           nil,                                nil,        nil,                {"center", "inviteDialogue"}},
    {"Hive_Mind",               "hive_mind_button1",            "join-hive-button",                     nil,                                nil,        nil,                nil},
    {"Hive_Mind",               "hive_mind_button2",            "leave-hive-button",                    nil,                                nil,        nil,                nil},
    {"Hive_Mind_Remastered",    "hive_mind_button1",            "join-hive-button",                     nil,                                nil,        nil,                nil},
    {"Hive_Mind_Remastered",    "hive_mind_button2",            "leave-hive-button",                    nil,                                nil,        nil,                nil},
    {"howfardiditgo",           "howfardiditgo_button",         "train_distance_button",                {'guiu.howfardiditgo_button'},      nil,        nil,                {"top", "mod_gui_top_frame", "mod_gui_inner_frame", "train_filtertextbox"}},
    {"Kux-BlueprintEditor",     "kuxblueprinteditor_button",    "mod-blueprint-editor-toolbar-button",  nil,                                nil,        nil,                {"screen", "blueprint-editor-modal"}},
    {"Kux-HandcraftGhosts",     "kuxcraftingtools_button",      "PlayerGhostCraft",                     nil,                                nil,        nil,                nil},
    {"Logistic-Machines",       "logisticmachines_button",      "lm_default_circuit_button",            {'guiu.logisticmachines_button'},   nil,        nil,                {"left", "mod_gui_frame_flow", "ld_default_circuit_window"}},
    {"LogisticRequestManager",  "logisticrequestmanager_button","logistic-request-manager-gui-button",  {'guiu.logisticrequestmanager_button'},nil,     nil,                {"screen", "logistic-request-manager-gui-master"}},
    {"region-cloner",           "regioncloner_button",          "region-cloner_main-button",            nil,                                nil,        nil,                {"left", "mod_gui_frame_flow", "region-cloner_control-window"}},
    {"ResetEvolutionPollution", "resetevolpol_button",          "ResetEvolutionPollution",              nil,                                nil,        nil,                nil},
    {"Shuttle_Train_Continued", "shuttle_train_button",         "shuttle_lite_button",                  nil,                                nil,        nil,                {"left", "mod_gui_frame_flow", "shuttle_lite_frame"}},
    {"Simple_Circuit_Trains",   "simple_circuit_trains_button", "SIMPLE_CLICK_01",                      {'guiu.simple_circuit_trains_button'},nil,      nil,                {"screen", "SIMPLE_LOCATION"}},
    {"TeamCoop",                "teamcoop_button1",             "spwn_ctrls",                           {'guiu.teamcoop_button1'},          nil,        nil,                {"left", "spwn_ctrl_panel"}},
    {"TeamCoop",                "teamcoop_button2",             "spwn_admin_ctrls",                     {'guiu.teamcoop_button2'},          nil,        nil,                {"left", "spwn_admin_ctrl_panel"}},
    {"smartchest",              "smartchest_button",            "sc_button",                            nil,                                nil,        nil,                {"left", "sc_filter_panel"}},
    {"homeworld_redux",         "homeworld_redux_button",       "Homeworld_btn",                        {'guiu.homeworld_redux_button'},    nil,        nil,                {"left", "homeworld"}},
    {"m-lawful-evil",           "mlawfulevil_button",           "lawful_evil_button",                   {'guiu.mlawfulevil_button'},        nil,        nil,                {"center", "lawful_evil_gui"}},
    {"Trashcan",                "trashcan_button",              "trashbinguibutton",                    {'guiu.trashcan_button'},           nil,        nil,                nil},
    {"pycoalprocessing",        "pycoalprocessing_button",      "pywiki",                               {'guiu.pycoalprocessing_button'},   nil,        nil,                {"screen", "wiki_frame"}},
    {"usage-detector",          "usagedetector_button",         "usage_detector",                       {'guiu.usagedetector_button'},      nil,        nil,                {"center", "usage_detector_center"}},
    {"RPG",                     "rpg_button",                   "104",                                  {'guiu.rpg_button'},                nil,        nil,                {"screen", "105"}},
    {"SpawnControl",            "spawncontrol_button",          "spawn",                                {'guiu.spawncontrol_button'},       nil,        nil,                nil},
    {"TimedSpawnControl",       "spawncontrol_button",          "spawn",                                {'guiu.spawncontrol_button'},       nil,        nil,                nil},
    {"TimedSpawnControl",       "spawncontrol_random_button",   "random",                               {'guiu.spawncontrol_random_button'},nil,        nil,                nil},
    {"what-is-missing",         "whatsmissing_button",          "what_is_missing",                      {'guiu.whatismissing_button'},      nil,        nil,                {"left", "what_is_missing"}},
    {"advanced-logistics-system-fork","logisticssystemfork_button","logistics-view-button",             {'guiu.logisticssystemfork_button'},nil,        nil,                {"center", "logisticsFrame"}},
    {"some-zoom",               "somezoom_out_button",          "but_zoom_zout",                        {'guiu.somezoom_out_button'},       nil,        nil,                nil},
    {"some-zoom",               "somezoom_in_button",           "but_zoom_zin",                         {'guiu.somezoom_in_button'},        nil,        nil,                nil},
    {"production-monitor",      "productionmonitor_button",     "stats_show_settings",                  {'guiu.productionmonitor_button'},  nil,        nil,                {"center", "stats_center"}},
    {"Teleportation_Redux",     "teleportation_button",         "teleportation_main_button",            {'guiu.teleportation_button'},      nil,        nil,                {"left", "teleportation_main_window"}},
    {"PersonalTeleporter",      "teleportation_button",         "personalTeleporter_PersonalTeleportTool",{'guiu.teleportation_button'},    nil,        nil,                {"left", "personlaTeleportWindow"}},
    {"SchallEndgameEvolution",  "schallendgameevolution_button","Schall-EE-mod-button",                 nil,                                1,          nil,                {"screen", "Schall-EE-frame-main"}},
    {"NewGamePlus",             "newgameplus_button",           "new-game-plus-toggle-config",          nil,                                nil,        nil,                {"left", "mod_gui_frame_flow", "new-game-plus-config-frame"}},
    {"Nullius",                 "nullius_button",               "nullius_mission_button",               nil,                                nil,        nil,                {"left", "nullius_mission_panel"}},
    {"RecExplo",                "recexplo_button",              "b_recexplo",                           {'guiu.recexplo_button'},           nil,        nil,                {"left", "recexplo_flow", "recexplo_gui_frame", "recexplo_gui_table"}},
    {"BlueprintLab_design",     "blueprintlabdesign_button",    "BPL_LabButton",                        {'guiu.blueprintlabdesign_button'}, nil,        nil,                {"left", "BPL_Flow", "BPL_ClearButton"}},
    {"NonWaveDefense2",         "nonwavedefense2_button",       "nwd2_main_gui_button",                 {'guiu.nonwavedefense2_button'},    nil,        nil,                nil},
    {"SkyWaveDefense",          "nonwavedefense2_button",       "swd3_main_gui_button",                 nil,                                nil,        nil,                nil},
    {"dana",                    "dana_button",                  "dana_main_gui_button",                 nil,                                nil,        nil,                nil},
    {"billbo99_factorio_tweaks","factorio_tweaks_button",       "admin_button",                         {'guiu.factorio_tweaks_button'},    nil,        nil,                {"left", "admin_panel", "tabbed_pane"}},
    {"remote-switch",           "remoteswitch_button",          "toggle_remote_switch_popup",           {'guiu.remoteswitch_button'},       nil,        nil,                {"screen", "switch_gui_panel", "mainframe"}},
    {"TSM-outpost-builder",     "tsmoutpostbuilder_button",     "crane_sprite_button",                  {'guiu.tsmoutpostbuilder_button'},  nil,        nil,                {"left", "mod_gui_frame_flow", "crane_button_frame"}},
    {"CredoTimeLapseModByGalapagon","credotimelapse_button",    "CTLM_mainbutton",                      {'guiu.credotimelapse_button'},     nil,        nil,                {"center", "CTLM_settings_main"}},
    {"spidersentinel",          "spidersentinel_button",        "spidersentinel_onoff",                 nil,                                nil,        nil,                {"left", "spidersentinel_frame"}},
    {"CitiesOfEarth",           "citiesofearth_button",         "coe_button_show_targets",              {'guiu.citiesofearth_button'},      nil,        nil,                {"center", "coe_choose_target"}},
    {"enemyracemanager",        "enemyracemanager_button",      "erm_toggle",                           {'guiu.enemyracemanager_button'},   nil,        nil,                {"left", "mod_gui_frame_flow", "races_manager"}},
    {"oarc-mod",                "oarcmod_button",               "oarc_button",                          {'guiu.oarcmod_button'},            nil,        nil,                {"left", "mod_gui_frame_flow", "oarc_gui"}},
    {"Decu",                    "decu_button",                  "market_button",                        {'guiu.decu_button'},               nil,        nil,                {"center", "market"}},
    {"rd-se-multiplayer-compat","forces_button",                "toggle_forces",                        {'guiu.compatforce_button'},        nil,        nil,                {"screen", "rd_forces_ui"}},
    {"rd-se-multiplayer-compat","spawncontrol_button",          "toggle_spawn_gui",                     {'guiu.compatspawn_button'},        nil,        nil,                {"screen", "spawn_gui"}},
    {"base",                    "leaderboard_button",           "toggle_leaderboard_button",            {'guiu.leaderboard_button'},        nil,        nil,                {"screen", "leaderboard", "inner"}},
    {"base",                    "teamcoop_button1",             "base_pvp_teams_button",                {'guiu.base_pvp_teams_button'},     nil,        nil,                nil},
    {"base",                    "picksrocketstats_button",      "base_pvp_space_race_button",           {'guiu.base_pvp_space_race_button'},nil,        nil,                nil},
    {"base",                    "factorio_tweaks_button",       "base_pvp_admin_button",                {'guiu.base_pvp_admin_button'},     nil,        nil,                nil},
    {"Spiderissmo",             "item/spidertron",              "108",                                  {'guiu.Spiderissmo_spider_button'}, nil,        nil,                {"screen", "105"}},
    {"Spiderissmo",             "credotimelapse_button",        "minimap_button",                       {'guiu.Spiderissmo_minimap_button'},nil,        nil,                {"left", "minimap_toggle_frame"}},
    {"automatic-belt-direction","abd_on_button",                "abdgui",                               nil,                                1,          nil,                nil},
    {"Bluegistics",             "bluegistics_button",           "toggle_saved_logistics_layouts",       nil,                                1,          nil,                nil},
    {"Avatars",                 "avatars_button",               "avatar_disc",                          nil,                                nil,        nil,                nil},
    {"modmashsplinternewworlds","newworlds_button",             "planets-toggle-button",                nil,                                nil,        nil,                {"screen", "planets-main-frame"}},


    --{"",      "", "",                     nil,        nil,        nil,                nil},
    --{"trainschedulesignals_button", "TSS=open-close",                     nil,                                nil,        nil},       ??
    --{"attachnotes_button",            "attach-note-button",                   nil,                                1,          nil}    -- too complex
    --{"avatars_button", ""},                                                                                                               ??
    --{"modmashsplinterboom_button", "landmine-toggle-button"},                                                                             ??
    --timeline                          timeline                hard
    --controllinator                ["controllinator-toggle"]           button created from
    --RPGsystem                     205992
    --Bluegistics
}