-- not connected

result:

data.raw["offshore-pump"]["offshore-pump"].graphics_set.underwater_layer_offset = 30
data.raw["offshore-pump"]["offshore-pump"].graphics_set.base_render_layer = "ground-patch"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].filename = "__base__/graphics/entity/offshore-pump/offshore-pump_North.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].width = 48
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].height = 84
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].shift = {-0.0625, -0.5}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.filename = "__base__/graphics/entity/offshore-pump/hr-offshore-pump_North.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.width = 90
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.height = 162
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.shift = {-0.03125, -0.46875}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[1].hr_version.scale = 0.5
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].filename = "__base__/graphics/entity/offshore-pump/offshore-pump_North-shadow.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].width = 78
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].height = 70
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].shift = {0.375, -0.25}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].draw_as_shadow = true
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.filename = "__base__/graphics/entity/offshore-pump/hr-offshore-pump_North-shadow.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.width = 150
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.height = 134
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.shift = {0.40625, -0.21875}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.draw_as_shadow = true
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.north.layers[2].hr_version.scale = 0.5
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].filename = "__base__/graphics/entity/offshore-pump/offshore-pump_East.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].width = 64
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].height = 52
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].shift = {0.4375, -0.0625}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.filename = "__base__/graphics/entity/offshore-pump/hr-offshore-pump_East.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.width = 124
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.height = 102
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.shift = {0.46875, -0.0625}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[1].hr_version.scale = 0.5
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].filename = "__base__/graphics/entity/offshore-pump/offshore-pump_East-shadow.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].width = 88
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].height = 34
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].shift = {0.875, 0.25}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].draw_as_shadow = true
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.filename = "__base__/graphics/entity/offshore-pump/hr-offshore-pump_East-shadow.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.width = 180
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.height = 66
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.shift = {0.84375, 0.25}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.draw_as_shadow = true
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.east.layers[2].hr_version.scale = 0.5
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].filename = "__base__/graphics/entity/offshore-pump/offshore-pump_South.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].width = 48
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].height = 96
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].shift = {-0.0625, 0}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.filename = "__base__/graphics/entity/offshore-pump/hr-offshore-pump_South.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.width = 92
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.height = 192
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.shift = {-0.03125, 0}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[1].hr_version.scale = 0.5
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].filename = "__base__/graphics/entity/offshore-pump/offshore-pump_South-shadow.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].width = 80
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].height = 66
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].shift = {0.5, 0.6875}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].draw_as_shadow = true
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.filename = "__base__/graphics/entity/offshore-pump/hr-offshore-pump_South-shadow.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.width = 164
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.height = 128
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.shift = {0.46875, 0.71875}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.draw_as_shadow = true
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.south.layers[2].hr_version.scale = 0.5
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].filename = "__base__/graphics/entity/offshore-pump/offshore-pump_West.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].width = 64
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].height = 52
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].shift = {-0.5, -0.0625}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.filename = "__base__/graphics/entity/offshore-pump/hr-offshore-pump_West.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.width = 124
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.height = 102
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.shift = {-0.46875, -0.0625}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[1].hr_version.scale = 0.5
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].filename = "__base__/graphics/entity/offshore-pump/offshore-pump_West-shadow.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].width = 88
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].height = 34
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].shift = {-0.125, 0.25}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].draw_as_shadow = true
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.filename = "__base__/graphics/entity/offshore-pump/hr-offshore-pump_West-shadow.png"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.priority = "high"
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.line_length = 8
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.frame_count = 32
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.animation_speed = 0.25
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.width = 172
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.height = 66
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.shift = {-0.09375, 0.25}
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.draw_as_shadow = true
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.west.layers[2].hr_version.scale = 0.5
data.raw["offshore-pump"]["offshore-pump"].graphics_set.animation.ignore = true