-- from KaoExtended
data:extend({
	{
		type = "item-subgroup",
		name = "techrow1",
		group = "intermediate-products",
		order = "z-z",
	},
	{
		type = "item-subgroup",
		name = "techrow2",
		group = "intermediate-products",
		order = "zz-z",
	},
	{
		type = "item-subgroup",
		name = "techrow3",
		group = "intermediate-products",
		order = "zzz-z",
	},
	{
		type = "item",
		name = "sci-component-1",
		icon = "__zzzparanoidal__/graphics/sci-component-1-128.png",
		icon_size = 128,
		icon_mipmaps = 4,
		subgroup = "techrow1",
		order = "a[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "sci-component-2",
		icon = "__zzzparanoidal__/graphics/sci-component-2-128.png",
		icon_size = 128,
		icon_mipmaps = 4,
		subgroup = "techrow1",
		order = "b[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "condensator",
		icon = "__zzzparanoidal__/graphics/condensator.png",
		icon_size = 32,
		subgroup = "bob-electronic-components",
		order = "b[tech]",
		stack_size = 400,
	},
	{
		type = "item",
		name = "condensator2",
		icon = "__zzzparanoidal__/graphics/condensator2.png",
		icon_size = 32,
		subgroup = "bob-electronic-components",
		order = "c[tech]",
		stack_size = 300,
	},
	{
		type = "item",
		name = "condensator3",
		icon = "__zzzparanoidal__/graphics/condensator3.png",
		icon_size = 32,
		subgroup = "bob-electronic-components",
		order = "d[tech]",
		stack_size = 200,
	},
	{
		type = "item",
		name = "sci-component-3",
		icon = "__zzzparanoidal__/graphics/sci-component-3-128.png",
		icon_size = 128,
		icon_mipmaps = 4,
		subgroup = "techrow1",
		order = "c[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "advsci-component-3",
		icon = "__zzzparanoidal__/graphics/advsci-component-3.png",
		icon_size = 32,
		subgroup = "techrow2",
		order = "c1[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "sci-component-4",
		icon = "__zzzparanoidal__/graphics/sci-component-4-128.png",
		icon_size = 128,
		icon_mipmaps = 4,
		subgroup = "techrow1",
		order = "d[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "advsci-component-4",
		icon = "__zzzparanoidal__/graphics/advsci-component-4.png",
		icon_size = 32,
		subgroup = "techrow2",
		order = "e[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "sci-component-5",
		icon = "__zzzparanoidal__/graphics/sci-component-5-128.png",
		icon_size = 128,
		icon_mipmaps = 4,
		subgroup = "techrow1",
		order = "g[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "sci-component-l",
		icon = "__zzzparanoidal__/graphics/sci-component-L-128.png",
		icon_size = 128,
		icon_mipmaps = 4,
		subgroup = "techrow1",
		order = "f[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "sci-component-m",
		icon = "__zzzparanoidal__/graphics/sci-component-M-128.png",
		icon_size = 128,
		icon_mipmaps = 4,
		subgroup = "techrow1",
		order = "e1[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "sci-component-o",
		icon = "__zzzparanoidal__/graphics/sci-component-O-128.png",
		icon_size = 128,
		icon_mipmaps = 4,
		subgroup = "techrow1",
		order = "h[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "simple-io",
		icon = "__zzzparanoidal__/graphics/simple-io.png",
		icon_size = 32,
		subgroup = "techrow3",
		order = "a[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "standart-io",
		icon = "__zzzparanoidal__/graphics/standart-io.png",
		icon_size = 32,
		subgroup = "techrow3",
		order = "b[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "advanced-io",
		icon = "__zzzparanoidal__/graphics/advanced-io.png",
		icon_size = 32,
		subgroup = "techrow3",
		order = "c[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "predictive-io",
		icon = "__zzzparanoidal__/graphics/predictive-io.png",
		icon_size = 32,
		subgroup = "techrow3",
		order = "d[tech]",
		stack_size = 100,
	},
	{
		type = "item",
		name = "intelligent-io",
		icon = "__zzzparanoidal__/graphics/intelligent-io-32.png",
		icon_size = 32,
		subgroup = "techrow3",
		order = "h[tech]",
		stack_size = 50,
	},
	{
		type = "item",
		name = "angels-iron-gear-wheel-stack",
		icon = "__zzzparanoidal__/graphics/smelting/iron-gear-wheel-stack.png",
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "angels-iron-casting",
		order = "s",
		stack_size = 200,
	},
	{
		type = "item",
		name = "angels-steel-gear-wheel-stack",
		icon = "__zzzparanoidal__/graphics/smelting/steel-gear-wheel-stack.png",
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "angels-steel-casting",
		order = "s",
		stack_size = 200,
	},
})
