return
{
  entities =
  {
    {"wall-remnants", {x = -6, y = -5}, {dir = "south", }},
    {"wall-remnants", {x = -6, y = -6}, {dir = "south", }},
    {"stone-wall", {x = -4, y = -6}, {}},
    {"stone-wall", {x = -5, y = -6}, {}},
    {"wooden-chest", {x = -3, y = -5}, {items = {["thermal-water-barrel"] = 5}, }},
    {"stone-wall", {x = -2, y = -6}, {}},
    {"stone-wall", {x = -3, y = -6}, {}},
    {"gate", {x = 0, y = -6}, {dir = "east", }},
    {"gate-remnants", {x = -1, y = -6}, {dir = "east", }},
    {"wooden-chest", {x = 1, y = -5}, {}},
    {"stone-wall", {x = 2, y = -6}, {}},
    {"stone-wall", {x = 1, y = -6}, {}},
    {"wall-remnants", {x = 4, y = -6}, {dir = "south", }},
    {"stone-wall", {x = 3, y = -6}, {}},
    {"wall-remnants", {x = 6, y = -5}, {dir = "south", }},
    {"wall-remnants", {x = 6, y = -6}, {dir = "south", }},
    {"wall-remnants", {x = 5, y = -6}, {dir = "south", }},
    {"wall-remnants", {x = -6, y = -3}, {dir = "south", }},
    {"stone-wall", {x = -6, y = -4}, {}},
    {"wooden-chest-remnants", {x = -4, y = -4}, {}},
    {"wooden-chest-remnants", {x = -5, y = -4}, {}},
    {"iron-chest", {x = 0, y = -3}, {}},
    {"wooden-chest-remnants", {x = 2, y = -3}, {}},
    {"wooden-chest", {x = 3, y = -4}, {}},
    {"stone-wall", {x = 6, y = -3}, {}},
    {"stone-wall", {x = 6, y = -4}, {}},
    {"gate", {x = -6, y = -1}, {}},
    {"stone-wall", {x = -6, y = -2}, {}},
    {"wooden-chest", {x = 0, y = -1}, {items = {["slag-slurry-barrel"] = 5}, }},
    {"iron-chest", {x = 4, y = -2}, {items = {["mineral-sludge-barrel"] = 5}, }},
    {"gate", {x = 6, y = -1}, {}},
    {"gate", {x = 6, y = -2}, {}},
    {"wall-remnants", {x = -6, y = 1}, {dir = "south", }},
    {"gate", {x = -6, y = 0}, {}},
    {"wooden-chest-remnants", {x = -4, y = 0}, {}},
    {"iron-chest", {x = -2, y = 1}, {}},
    {"wooden-chest-remnants", {x = -2, y = 0}, {}},
    {"wooden-chest", {x = 2, y = 1}, {}},
    {"iron-chest", {x = 4, y = 0}, {}},
    {"stone-wall", {x = 6, y = 1}, {}},
    {"wall-remnants", {x = 6, y = 0}, {}},
    {"stone-wall", {x = -6, y = 3}, {}},
    {"stone-wall", {x = -6, y = 2}, {}},
    {"wooden-chest", {x = -4, y = 2}, {items = {["water-yellow-waste-barrel"] = 5}, }},
    {"wooden-chest-remnants", {x = -2, y = 3}, {}},
    {"wooden-chest", {x = -3, y = 2}, {}},
    {"wooden-chest-remnants", {x = -1, y = 3}, {}},
    {"wooden-chest", {x = 2, y = 2}, {items = {["crystal-slurry-barrel"] = 5}, }},
    {"stone-wall", {x = 6, y = 3}, {}},
    {"stone-wall", {x = 6, y = 2}, {}},
    {"stone-wall", {x = -6, y = 5}, {}},
    {"stone-wall", {x = -6, y = 4}, {}},
    {"iron-chest-remnants", {x = -3, y = 4}, {}},
    {"iron-chest", {x = 0, y = 4}, {}},
    {"stone-wall", {x = 6, y = 5}, {}},
    {"wall-remnants", {x = 6, y = 4}, {}},
    {"stone-wall", {x = -6, y = 6}, {}},
    {"wall-remnants", {x = -4, y = 6}, {dir = "south", }},
    {"stone-wall", {x = -5, y = 6}, {}},
    {"stone-wall", {x = -2, y = 6}, {}},
    {"wall-remnants", {x = -3, y = 6}, {dir = "south", }},
    {"gate", {x = 0, y = 6}, {dir = "east", }},
    {"stone-wall", {x = -1, y = 6}, {}},
    {"wall-remnants", {x = 2, y = 6}, {dir = "south", }},
    {"gate", {x = 1, y = 6}, {dir = "east", }},
    {"wall-remnants", {x = 4, y = 6}, {dir = "south", }},
    {"stone-wall", {x = 3, y = 6}, {}},
    {"wall-remnants", {x = 6, y = 6}, {}},
    {"stone-wall", {x = 5, y = 6}, {}},
  },
}
