return
{
  entities =
  {
    {"stone-wall", {x = -4.5, y = -5.5}, {}},
    {"stone-wall", {x = -5.5, y = -5.5}, {}},
    {"stone-wall", {x = -2.5, y = -5.5}, {}},
    {"stone-wall", {x = -3.5, y = -5.5}, {}},
    {"stone-wall", {x = -0.5, y = -5.5}, {}},
    {"wall-remnants", {x = -1.5, y = -5.5}, {dir = "south", }},
    {"gate", {x = 1.5, y = -5.5}, {dir = "east", }},
    {"stone-wall", {x = 0.5, y = -5.5}, {}},
    {"stone-wall", {x = 3.5, y = -5.5}, {}},
    {"stone-wall", {x = 2.5, y = -5.5}, {}},
    {"stone-wall", {x = 5.5, y = -5.5}, {}},
    {"stone-wall", {x = 4.5, y = -5.5}, {}},
    {"wall-remnants", {x = 6.5, y = -5.5}, {dir = "south", }},
    {"stone-wall", {x = -5.5, y = -4.5}, {}},
    {"stone-wall", {x = -5.5, y = -3.5}, {}},
    {"stone-wall", {x = 0.5, y = -4.5}, {}},
    {"land-mine", {x = 1.27, y = -4.29}, {force = "enemy", }},
    {"stone-wall", {x = 0.5, y = -3.5}, {}},
    {"stone-wall", {x = 6.5, y = -4.5}, {}},
    {"stone-wall", {x = 6.5, y = -3.5}, {}},
    {"wall-remnants", {x = -5.5, y = -2.5}, {dir = "south", }},
    {"stone-wall", {x = -5.5, y = -1.5}, {}},
    {"stone-wall", {x = 1.5, y = -1.5}, {}},
    {"stone-wall", {x = 0.5, y = -1.5}, {}},
    {"stone-wall", {x = 3.5, y = -1.5}, {}},
    {"wall-remnants", {x = 2.5, y = -1.5}, {dir = "south", }},
    {"wall-remnants", {x = 4.5, y = -1.5}, {dir = "south", }},
    {"stone-wall", {x = 6.5, y = -2.5}, {}},
    {"wall-remnants", {x = 6.5, y = -1.5}, {}},
    {"wall-remnants", {x = -6.5, y = 0.5}, {dir = "south", }},
    {"wall-remnants", {x = -5.5, y = -0.5}, {dir = "south", }},
    {"stone-wall", {x = -5.5, y = 0.5}, {}},
    {"wall-remnants", {x = -2.5, y = 0.5}, {dir = "south", }},
    {"stone-wall", {x = -0.5, y = 0.5}, {}},
    {"stone-wall", {x = -1.5, y = 0.5}, {}},
    {"stone-wall", {x = 0.5, y = -0.5}, {}},
    {"stone-wall", {x = 0.5, y = 0.5}, {}},
    {"wall-remnants", {x = 3.5, y = 0.5}, {dir = "south", }},
    {"stone-wall", {x = 2.5, y = 0.5}, {}},
    {"stone-wall", {x = 5.5, y = 0.5}, {}},
    {"stone-wall", {x = 4.5, y = 0.5}, {}},
    {"stone-wall", {x = 6.5, y = -0.5}, {}},
    {"stone-wall", {x = 6.5, y = 0.5}, {}},
    {"stone-wall", {x = -6.5, y = 1.5}, {}},
    {"wall-remnants", {x = -6.5, y = 2.5}, {}},
    {"wooden-chest", {x = -0.5, y = 1.5}, {items = {["advanced-circuit"] = {type = "random", min = 10, max = 15}, ["processing-unit"] = {type = "random", min = 3, max = 7}}, }},
    {"stone-wall", {x = 0.5, y = 1.5}, {}},
    {"stone-wall", {x = 0.5, y = 2.5}, {}},
    {"stone-wall", {x = 6.5, y = 1.5}, {}},
    {"wall-remnants", {x = 6.5, y = 2.5}, {}},
    {"stone-wall", {x = -6.5, y = 3.5}, {}},
    {"stone-wall", {x = -6.5, y = 4.5}, {}},
    {"wall-remnants", {x = 0.5, y = 3.5}, {}},
    {"wall-remnants", {x = 0.5, y = 4.5}, {dir = "south", }},
    {"wall-remnants", {x = 6.5, y = 3.5}, {dir = "south", }},
    {"wall-remnants", {x = 6.5, y = 4.5}, {dir = "south", }},
    {"stone-wall", {x = -6.5, y = 5.5}, {}},
    {"stone-wall", {x = -4.5, y = 5.5}, {}},
    {"wall-remnants", {x = -5.5, y = 5.5}, {dir = "south", }},
    {"stone-wall", {x = -2.5, y = 5.5}, {}},
    {"wall-remnants", {x = -3.5, y = 5.5}, {dir = "south", }},
    {"stone-wall", {x = -0.5, y = 5.5}, {}},
    {"wall-remnants", {x = -1.5, y = 5.5}, {dir = "south", }},
    {"stone-wall", {x = 1.5, y = 5.5}, {}},
    {"wall-remnants", {x = 0.5, y = 5.5}, {dir = "south", }},
    {"stone-wall", {x = 3.5, y = 5.5}, {}},
    {"stone-wall", {x = 2.5, y = 5.5}, {}},
    {"wall-remnants", {x = 5.5, y = 5.5}, {dir = "south", }},
    {"wall-remnants", {x = 4.5, y = 5.5}, {dir = "south", }},
    {"wall-remnants", {x = 6.5, y = 5.5}, {dir = "south", }},
  },
}
