return
{
  entities =
  {
    {"wall-remnants", {x = -2.5, y = -7.5}, {dir = "south", }},
    {"stone-wall", {x = -1.5, y = -7.5}, {}},
    {"stone-wall", {x = -0.5, y = -7.5}, {}},
    {"stone-wall", {x = 0.5, y = -7.5}, {}},
    {"wall-remnants", {x = 1.5, y = -7.5}, {dir = "south", }},
    {"wall-remnants", {x = 2.5, y = -7.5}, {dir = "south", }},
    {"stone-wall", {x = 3.5, y = -7.5}, {}},
    {"wall-remnants", {x = 4.5, y = -7.5}, {dir = "south", }},
    {"stone-wall", {x = 5.5, y = -7.5}, {}},
    {"stone-wall", {x = 5.5, y = -5.5}, {}},
    {"wall-remnants", {x = 5.5, y = -6.5}, {}},
    {"stone-wall", {x = 5.5, y = -3.5}, {}},
    {"stone-wall", {x = 5.5, y = -4.5}, {}},
    {"cargo-plane", {x = -0.25, y = -0.31}, {dead = 0.5,}},
    {"wall-remnants", {x = 5.5, y = -1.5}, {dir = "south", }},
    {"wall-remnants", {x = 6.5, y = -1.5}, {dir = "south", }},
    {"wall-remnants", {x = 5.5, y = -2.5}, {}},
    {"stone-wall", {x = 6.5, y = 0.5}, {}},
    {"wall-remnants", {x = 6.5, y = -0.5}, {dir = "south", }},
    {"steel-chest", {x = 1.5, y = 2.5}, {items = {["solid-fuel"] = 50}, }},
    {"stone-wall", {x = 6.5, y = 2.5}, {}},
    {"stone-wall", {x = 6.5, y = 1.5}, {}},
    {"stone-wall", {x = 6.5, y = 4.5}, {}},
    {"wall-remnants", {x = 6.5, y = 3.5}, {}},
    {"stone-wall", {x = 6.5, y = 6.5}, {}},
    {"stone-wall", {x = 6.5, y = 5.5}, {}},
    {"stone-wall", {x = -1.5, y = 7.5}, {}},
    {"wall-remnants", {x = -2.5, y = 7.5}, {dir = "south", }},
    {"gate", {x = 0.5, y = 7.5}, {dir = "east", }},
    {"stone-wall", {x = -0.5, y = 7.5}, {}},
    {"gate", {x = 2.5, y = 7.5}, {dir = "east", }},
    {"gate", {x = 1.5, y = 7.5}, {dir = "east", }},
    {"gate-remnants", {x = 3.5, y = 7.5}, {dir = "east", }},
    {"stone-wall", {x = 4.5, y = 7.5}, {}},
    {"wall-remnants", {x = 6.5, y = 7.5}, {}},
    {"stone-wall", {x = 5.5, y = 7.5}, {}},
  },
  tiles =
  {
    {"stone-path", {x = -6, y = -7}},
    {"stone-path", {x = -6, y = -6}},
    {"stone-path", {x = -6, y = -5}},
    {"stone-path", {x = -6, y = -4}},
    {"stone-path", {x = -6, y = -3}},
    {"stone-path", {x = -6, y = -2}},
    {"concrete", {x = -6, y = -1}},
    {"concrete", {x = -6, y = 0}},
    {"concrete", {x = -6, y = 1}},
    {"concrete", {x = -6, y = 2}},
    {"concrete", {x = -6, y = 3}},
    {"concrete", {x = -6, y = 4}},
    {"stone-path", {x = -6, y = 5}},
    {"stone-path", {x = -6, y = 6}},
    {"stone-path", {x = -5, y = -7}},
    {"hazard-concrete-left", {x = -5, y = -6}},
    {"stone-path", {x = -5, y = -5}},
    {"stone-path", {x = -5, y = -4}},
    {"hazard-concrete-left", {x = -5, y = -3}},
    {"hazard-concrete-left", {x = -5, y = -2}},
    {"hazard-concrete-left", {x = -5, y = -1}},
    {"hazard-concrete-left", {x = -5, y = 0}},
    {"hazard-concrete-left", {x = -5, y = 1}},
    {"hazard-concrete-left", {x = -5, y = 2}},
    {"hazard-concrete-left", {x = -5, y = 3}},
    {"stone-path", {x = -5, y = 4}},
    {"stone-path", {x = -5, y = 5}},
    {"stone-path", {x = -5, y = 6}},
    {"stone-path", {x = -4, y = -7}},
    {"stone-path", {x = -4, y = -6}},
    {"stone-path", {x = -4, y = -5}},
    {"hazard-concrete-left", {x = -4, y = -4}},
    {"hazard-concrete-left", {x = -4, y = -3}},
    {"hazard-concrete-left", {x = -4, y = -2}},
    {"hazard-concrete-left", {x = -4, y = -1}},
    {"hazard-concrete-left", {x = -4, y = 0}},
    {"hazard-concrete-left", {x = -4, y = 1}},
    {"hazard-concrete-left", {x = -4, y = 2}},
    {"hazard-concrete-left", {x = -4, y = 3}},
    {"stone-path", {x = -4, y = 4}},
    {"hazard-concrete-left", {x = -4, y = 5}},
    {"concrete", {x = -4, y = 6}},
    {"concrete", {x = -3, y = -7}},
    {"concrete", {x = -3, y = -6}},
    {"concrete", {x = -3, y = -5}},
    {"stone-path", {x = -3, y = -4}},
    {"concrete", {x = -3, y = -3}},
    {"concrete", {x = -3, y = -2}},
    {"hazard-concrete-right", {x = -3, y = -1}},
    {"hazard-concrete-right", {x = -3, y = 0}},
    {"concrete", {x = -3, y = 1}},
    {"concrete", {x = -3, y = 2}},
    {"concrete", {x = -3, y = 3}},
    {"concrete", {x = -3, y = 4}},
    {"concrete", {x = -3, y = 5}},
    {"concrete", {x = -3, y = 6}},
    {"concrete", {x = -2, y = -7}},
    {"stone-path", {x = -2, y = -6}},
    {"concrete", {x = -2, y = -5}},
    {"stone-path", {x = -2, y = -4}},
    {"stone-path", {x = -2, y = -3}},
    {"concrete", {x = -2, y = -2}},
    {"hazard-concrete-right", {x = -2, y = -1}},
    {"hazard-concrete-right", {x = -2, y = 0}},
    {"concrete", {x = -2, y = 1}},
    {"concrete", {x = -2, y = 2}},
    {"stone-path", {x = -2, y = 3}},
    {"stone-path", {x = -2, y = 4}},
    {"stone-path", {x = -2, y = 5}},
    {"concrete", {x = -2, y = 6}},
    {"concrete", {x = -1, y = -7}},
    {"stone-path", {x = -1, y = -6}},
    {"stone-path", {x = -1, y = -5}},
    {"stone-path", {x = -1, y = -4}},
    {"stone-path", {x = -1, y = -3}},
    {"concrete", {x = -1, y = -2}},
    {"hazard-concrete-right", {x = -1, y = -1}},
    {"hazard-concrete-right", {x = -1, y = 0}},
    {"concrete", {x = -1, y = 1}},
    {"concrete", {x = -1, y = 2}},
    {"stone-path", {x = -1, y = 3}},
    {"stone-path", {x = -1, y = 4}},
    {"stone-path", {x = -1, y = 5}},
    {"concrete", {x = -1, y = 6}},
    {"concrete", {x = 0, y = -7}},
    {"stone-path", {x = 0, y = -6}},
    {"stone-path", {x = 0, y = -5}},
    {"concrete", {x = 0, y = -4}},
    {"stone-path", {x = 0, y = -3}},
    {"concrete", {x = 0, y = -2}},
    {"hazard-concrete-right", {x = 0, y = -1}},
    {"hazard-concrete-right", {x = 0, y = 0}},
    {"concrete", {x = 0, y = 1}},
    {"concrete", {x = 0, y = 2}},
    {"concrete", {x = 0, y = 3}},
    {"concrete", {x = 0, y = 4}},
    {"stone-path", {x = 0, y = 5}},
    {"concrete", {x = 0, y = 6}},
    {"concrete", {x = 1, y = -7}},
    {"hazard-concrete-left", {x = 1, y = -6}},
    {"hazard-concrete-left", {x = 1, y = -5}},
    {"hazard-concrete-left", {x = 1, y = -4}},
    {"hazard-concrete-left", {x = 1, y = -3}},
    {"hazard-concrete-left", {x = 1, y = -2}},
    {"hazard-concrete-left", {x = 1, y = -1}},
    {"hazard-concrete-left", {x = 1, y = 0}},
    {"hazard-concrete-left", {x = 1, y = 1}},
    {"hazard-concrete-left", {x = 1, y = 2}},
    {"hazard-concrete-left", {x = 1, y = 3}},
    {"hazard-concrete-left", {x = 1, y = 4}},
    {"hazard-concrete-left", {x = 1, y = 5}},
    {"concrete", {x = 1, y = 6}},
    {"concrete", {x = 2, y = -7}},
    {"hazard-concrete-left", {x = 2, y = -6}},
    {"hazard-concrete-left", {x = 2, y = -5}},
    {"concrete", {x = 2, y = -4}},
    {"concrete", {x = 2, y = -3}},
    {"concrete", {x = 2, y = -2}},
    {"hazard-concrete-left", {x = 2, y = -1}},
    {"hazard-concrete-left", {x = 2, y = 0}},
    {"stone-path", {x = 2, y = 1}},
    {"stone-path", {x = 2, y = 2}},
    {"hazard-concrete-left", {x = 2, y = 3}},
    {"hazard-concrete-left", {x = 2, y = 4}},
    {"hazard-concrete-left", {x = 2, y = 5}},
    {"concrete", {x = 2, y = 6}},
    {"concrete", {x = 3, y = -7}},
    {"concrete", {x = 3, y = -6}},
    {"concrete", {x = 3, y = -5}},
    {"concrete", {x = 3, y = -4}},
    {"concrete", {x = 3, y = -3}},
    {"stone-path", {x = 3, y = -2}},
    {"stone-path", {x = 3, y = -1}},
    {"stone-path", {x = 3, y = 0}},
    {"stone-path", {x = 3, y = 1}},
    {"stone-path", {x = 3, y = 2}},
    {"concrete", {x = 3, y = 3}},
    {"concrete", {x = 3, y = 4}},
    {"concrete", {x = 3, y = 5}},
    {"concrete", {x = 3, y = 6}},
  }
}
