return
{
  entities =
  {
    {"stone-wall", {x = -6, y = -5.5}, {}},
    {"stone-wall", {x = -5, y = -5.5}, {}},
    {"stone-wall", {x = -3, y = -5.5}, {}},
    {"gate", {x = -4, y = -5.5}, {dir = "east", }},
    {"stone-wall", {x = -2, y = -5.5}, {}},
    {"stone-wall", {x = -1, y = -5.5}, {}},
    {"stone-wall", {x = 0, y = -5.5}, {}},
    {"stone-wall", {x = 3, y = -5.5}, {}},
    {"stone-wall", {x = 6, y = -5.5}, {}},
    {"stone-wall", {x = -6, y = -3.5}, {}},
    {"stone-wall", {x = -6, y = -4.5}, {}},
    {"tree-05", {x = -5, y = -4.5}, {}},
    {"pipe-to-ground", {x = -1, y = -3.5}, {dir = "south", }},
    {"stone-wall", {x = 2, y = -3.5}, {}},
    {"stone-wall", {x = 6, y = -4.5}, {}},
    {"stone-wall", {x = -6, y = -2.5}, {}},
    {"stone-wall", {x = -5, y = -2.5}, {}},
    {"stone-wall", {x = -4, y = -2.5}, {}},
    {"stone-wall", {x = -3, y = -2.5}, {}},
    {"tree-05", {x = -2, y = -1.5}, {}},
    {"pipe-to-ground", {x = -1, y = -2.5}, {}},
    {"stone-wall", {x = 0, y = -2.5}, {}},
    {"stone-wall", {x = 1, y = -2.5}, {}},
    {"stone-wall", {x = 2, y = -2.5}, {}},
    {"stone-wall", {x = 3, y = -2.5}, {}},
    {"land-mine", {x = 1.95, y = -1.72}, {force = "enemy", }},
    {"tree-05", {x = 4, y = -1.5}, {}},
    {"stone-wall", {x = 4, y = -2.5}, {}},
    {"stone-wall", {x = 6, y = -1.5}, {}},
    {"stone-wall", {x = -6, y = 0.5}, {}},
    {"steel-chest", {x = -1, y = -0.5}, {items = {["logistic-robot"] = {type = "random", min = 2, max = 5}}, }},
    {"stone-wall", {x = -2, y = 0.5}, {}},
    {"stone-wall", {x = 4, y = 0.5}, {}},
    {"stone-wall", {x = 6, y = 0.5}, {}},
    {"stone-wall", {x = 6, y = -0.5}, {}},
    {"stone-wall", {x = -6, y = 2.5}, {}},
    {"land-mine", {x = -4.84, y = 2.5}, {force = "enemy", }},
    {"stone-wall", {x = -6, y = 1.5}, {}},
    {"stone-wall", {x = -5, y = 1.5}, {}},
    {"stone-wall", {x = -3, y = 1.5}, {}},
    {"stone-wall", {x = -2, y = 1.5}, {}},
    {"gate", {x = -1, y = 1.5}, {dir = "east", }},
    {"stone-wall", {x = 0, y = 2.5}, {}},
    {"stone-wall", {x = 0, y = 1.5}, {}},
    {"stone-wall", {x = 1, y = 1.5}, {}},
    {"tree-05", {x = 2, y = 2.5}, {}},
    {"stone-wall", {x = 2, y = 1.5}, {}},
    {"stone-wall", {x = 3, y = 1.5}, {}},
    {"stone-wall", {x = 4, y = 2.5}, {}},
    {"stone-wall", {x = 4, y = 1.5}, {}},
    {"stone-wall", {x = -6, y = 4.5}, {}},
    {"stone-wall", {x = -6, y = 3.5}, {}},
    {"stone-wall", {x = 0, y = 4.5}, {}},
    {"stone-wall", {x = 4, y = 4.5}, {}},
    {"stone-wall", {x = 4, y = 3.5}, {}},
    {"stone-wall", {x = 6, y = 4.5}, {}},
    {"stone-wall", {x = 6, y = 3.5}, {}},
    {"stone-wall", {x = -5, y = 5.5}, {}},
    {"stone-wall", {x = -3, y = 5.5}, {}},
    {"stone-wall", {x = -2, y = 5.5}, {}},
    {"stone-wall", {x = -1, y = 5.5}, {}},
    {"stone-wall", {x = 0, y = 5.5}, {}},
    {"gate", {x = 1, y = 5.5}, {dir = "east", }},
    {"stone-wall", {x = 3, y = 5.5}, {}},
    {"stone-wall", {x = 2, y = 5.5}, {}},
    {"stone-wall", {x = 4, y = 5.5}, {}},
    {"gate", {x = 5, y = 5.5}, {dir = "east", }},
    {"stone-wall", {x = 6, y = 5.5}, {}},
  },
}
