return
{
  entities =
  {
    {"steam-turbine-remnants", {x = -5.5, y = -12}, {}},
    {"steam-turbine-remnants", {x = -0.5, y = -12}, {}},
    {"steam-turbine-remnants", {x = 6.5, y = -12}, {}},
    {"substation", {x = 9, y = -7.5}, {}},
    {"steam-turbine-remnants", {x = -8.5, y = -7}, {}},
    {"steam-turbine-remnants", {x = -5.5, y = -7}, {}},
    {"substation-remnants", {x = -3, y = -5.5}, {}},
    {"steam-turbine-remnants", {x = -0.5, y = -7}, {}},
    {"steam-turbine-remnants", {x = 3.5, y = -7}, {}},
    {"steam-turbine-remnants", {x = 6.5, y = -7}, {}},
    {"pipe-remnants", {x = -13.5, y = -3}, {}},
    {"pipe-remnants", {x = -12.5, y = -3}, {}},
    {"pipe", {x = -11.5, y = -3}, {}},
    {"pipe", {x = -10.5, y = -3}, {}},
    {"pipe", {x = -10.5, y = -2}, {}},
    {"pipe", {x = -9.5, y = -2}, {}},
    {"heat-exchanger-remnants", {x = -8.5, y = -3.5}, {}},
    {"pipe-remnants", {x = -8.5, y = -2}, {dir = "south", }},
    {"pipe-remnants", {x = -7.5, y = -2}, {}},
    {"heat-exchanger-remnants", {x = -5.5, y = -3.5}, {dir = "south", }},
    {"medium-electric-pole", {x = -6.5, y = -2}, {}},
    {"pipe", {x = -3.5, y = -3}, {fluids = {water = 33.332920074462891}, }},
    {"pipe", {x = -2.5, y = -3}, {fluids = {water = 33.333526611328125}, }},
    {"nuclear-reactor", {x = 1.5, y = 0}, {dead = 0.5, }},
    {"heat-exchanger-remnants", {x = -0.5, y = -3.5}, {}},
    {"pipe-remnants", {x = 1.5, y = -3}, {}},
    {"heat-exchanger-remnants", {x = 3.5, y = -3.5}, {}},
    {"heat-pipe-remnants", {x = 4.5, y = -2}, {}},
    {"heat-exchanger-remnants", {x = 6.5, y = -3.5}, {}},
    {"heat-pipe", {x = 6.5, y = -2}, {}},
    {"heat-pipe-remnants", {x = 5.5, y = -2}, {dir = "south", }},
    {"pipe-remnants", {x = 8.5, y = -2}, {}},
    {"pipe", {x = 8.5, y = -3}, {fluids = {water = 100}, }},
    {"pipe", {x = 10.5, y = -2}, {fluids = {water = 100}, }},
    {"pipe-remnants", {x = 9.5, y = -2}, {dir = "south", }},
    {"pipe-remnants", {x = 12.5, y = -2}, {}},
    {"pipe", {x = 11.5, y = -2}, {fluids = {water = 100}, }},
    {"pipe", {x = 14.5, y = -2}, {fluids = {water = 100}, }},
    {"pipe", {x = 13.5, y = -2}, {fluids = {water = 100}, }},
    {"active-provider-chest-remnants", {x = -8.5, y = 0}, {}},
    {"requester-chest-remnants", {x = -8.5, y = -1}, {}},
    {"pipe-remnants", {x = -7.5, y = -1}, {}},
    {"pipe-remnants", {x = -7.5, y = 0}, {}},
    {"long-handed-inserter", {x = -6.5, y = 0}, {dir = "east", }},
    {"long-handed-inserter-remnants", {x = -6.5, y = -1}, {dir = "west", }},
    {"nuclear-reactor-remnants", {x = -3.5, y = 0}, {}},
    {"inserter-remnants", {x = 4.5, y = -1}, {dir = "east", }},
    {"pipe", {x = 4.5, y = 0}, {}},
    {"requester-chest-remnants", {x = 5.5, y = -1}, {}},
    {"pipe", {x = 5.5, y = 0}, {}},
    {"pipe-remnants", {x = 6.5, y = 0}, {dir = "south", }},
    {"medium-electric-pole", {x = 7.5, y = -1}, {}},
    {"pipe-remnants", {x = 7.5, y = 0}, {}},
    {"pipe", {x = 8.5, y = 0}, {}},
    {"pipe-remnants", {x = 8.5, y = -1}, {}},
    {"pipe", {x = -13.5, y = 1}, {}},
    {"storage-tank", {x = -12.5, y = 3}, {}},
    {"pipe-remnants", {x = -12.5, y = 1}, {dir = "south", }},
    {"pipe", {x = -11.5, y = 1}, {}},
    {"storage-tank", {x = -9.5, y = 3}, {dir = "east", }},
    {"pipe", {x = -10.5, y = 1}, {}},
    {"pipe", {x = -9.5, y = 1}, {}},
    {"pipe", {x = -8.5, y = 1}, {}},
    {"pipe", {x = -7.5, y = 1}, {}},
    {"pipe", {x = -7.5, y = 2}, {}},
    {"heat-exchanger-remnants", {x = 5, y = 2}, {dir = "east", }},
    {"steam-turbine-remnants", {x = 8.5, y = 2}, {dir = "east", }},
    {"steam-turbine-remnants", {x = 13.5, y = 2}, {dir = "east", }},
    {"pipe", {x = -7.5, y = 3}, {}},
    {"heat-exchanger-remnants", {x = -5.5, y = 3.5}, {dir = "south", }},
    {"pipe", {x = -3.5, y = 3}, {}},
    {"heat-exchanger-remnants", {x = -1.5, y = 3.5}, {dir = "south", }},
    {"heat-exchanger-remnants", {x = 1.5, y = 3.5}, {dir = "south", }},
    {"heat-pipe-remnants", {x = 3.5, y = 3}, {}},
    {"heat-pipe", {x = 3.5, y = 4}, {}},
    {"heat-pipe-remnants", {x = 3.5, y = 5}, {}},
    {"heat-exchanger-remnants", {x = 5, y = 5}, {dir = "east", }},
    {"steam-turbine-remnants", {x = 13.5, y = 5}, {dir = "east", }},
    {"substation", {x = -9, y = 8.5}, {}},
    {"steam-turbine-remnants", {x = -5.5, y = 7}, {}},
    {"steam-turbine-remnants", {x = -1.5, y = 7}, {}},
    {"steam-turbine-remnants", {x = 1.5, y = 7}, {}},
    {"substation-remnants", {x = 7, y = 8.5}, {}},
    {"steam-turbine-remnants", {x = -1.5, y = 12}, {}},
    {"steam-turbine-remnants", {x = 1.5, y = 12}, {}},
  },
}
