return
{
  entities =
  {
    {"big-electric-pole-remnants", {x = -8.5, y = -13.5}, {dir = "east", }},
    {"stone-wall", {x = -11, y = -4}, {}},
    {"stone-wall", {x = -11, y = -5}, {}},
    {"stone-wall", {x = -10, y = -5}, {}},
    {"stone-wall", {x = -9, y = -5}, {}},
    {"stone-wall", {x = -8, y = -5}, {}},
    {"stone-wall", {x = -7, y = -5}, {}},
    {"wall-remnants", {x = -6, y = -5}, {dir = "east", }},
    {"stone-wall", {x = -5, y = -5}, {}},
    {"stone-wall", {x = -4, y = -5}, {}},
    {"stone-wall", {x = -3, y = -5}, {}},
    {"wall-remnants", {x = -1, y = -5}, {dir = "east", }},
    {"wall-remnants", {x = -2, y = -5}, {dir = "east", }},
    {"stone-wall", {x = 0, y = -5}, {}},
    {"stone-wall", {x = 1, y = -5}, {}},
    {"wall-remnants", {x = 2, y = -5}, {dir = "east", }},
    {"stone-wall", {x = 3, y = -5}, {}},
    {"stone-wall", {x = 5, y = -5}, {}},
    {"stone-wall", {x = 4, y = -5}, {}},
    {"stone-wall", {x = 7, y = -4}, {}},
    {"wall-remnants", {x = 7, y = -5}, {dir = "east", }},
    {"stone-wall", {x = 6, y = -5}, {}},
    {"stone-wall", {x = -11, y = -2}, {}},
    {"stone-wall", {x = -11, y = -3}, {}},
    {"big-electric-pole-remnants", {x = -6.5, y = -1.5}, {dir = "east", }},
    {"laser-turret-remnants", {x = -8.5, y = -3.5}, {dir = "east", }},
    {"roboport", {x = -3.5, y = -1.5}, {}},
    {"laser-turret-remnants", {x = -4.5, y = -3.5}, {dir = "east", }},
    {"medium-electric-pole", {x = 5, y = -2}, {}},
    {"laser-turret-remnants", {x = 4.5, y = -3.5}, {dir = "east", }},
    {"stone-wall", {x = 7, y = -2}, {}},
    {"wall-remnants", {x = 7, y = -3}, {dir = "east", }},
    {"stone-wall", {x = -11, y = 0}, {}},
    {"wall-remnants", {x = -11, y = -1}, {dir = "east", }},
    {"radar-remnants", {x = 0, y = -1}, {dir = "east", }},
    {"stone-wall", {x = 7, y = 0}, {}},
    {"stone-wall", {x = 7, y = -1}, {}},
    {"stone-wall", {x = -11, y = 2}, {}},
    {"stone-wall", {x = -11, y = 1}, {}},
    {"gun-turret", {x = -9.5, y = 2.5}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"medium-electric-pole", {x = -6, y = 1}, {}},
    {"medium-electric-pole-remnants", {x = 3, y = 1}, {}},
    {"gun-turret", {x = 5.5, y = 2.5}, {force = "enemy", items = {["firearm-magazine"] = 2}, }},
    {"wall-remnants", {x = 7, y = 2}, {dir = "east", }},
    {"stone-wall", {x = 7, y = 1}, {}},
    {"stone-wall", {x = -11, y = 4}, {}},
    {"stone-wall", {x = -11, y = 3}, {}},
    {"stone-wall", {x = -9, y = 4}, {}},
    {"stone-wall", {x = -10, y = 4}, {}},
    {"stone-wall", {x = -7, y = 4}, {}},
    {"stone-wall", {x = -8, y = 4}, {}},
    {"wall-remnants", {x = -6, y = 4}, {dir = "east", }},
    {"stone-wall", {x = -5, y = 4}, {}},
    {"gate", {x = -3, y = 4}, {dir = "east", }},
    {"stone-wall", {x = -4, y = 4}, {}},
    {"laser-turret-remnants", {x = -4.5, y = 2.5}, {dir = "east", }},
    {"gate-remnants", {x = -1, y = 4}, {dir = "east", }},
    {"gate", {x = -2, y = 4}, {dir = "east", }},
    {"gate", {x = 0, y = 4}, {dir = "east", }},
    {"stone-wall", {x = 1, y = 4}, {}},
    {"laser-turret-remnants", {x = 0.5, y = 2.5}, {dir = "east", }},
    {"stone-wall", {x = 3, y = 4}, {}},
    {"stone-wall", {x = 2, y = 4}, {}},
    {"wall-remnants", {x = 4, y = 4}, {dir = "east", }},
    {"stone-wall", {x = 5, y = 4}, {}},
    {"stone-wall", {x = 7, y = 4}, {}},
    {"stone-wall", {x = 6, y = 4}, {}},
    {"stone-wall", {x = 7, y = 3}, {}},
    {"big-electric-pole-remnants", {x = 10.5, y = 13.5}, {dir = "east", }},
  },
}
