return
{
  entities =
  {
    {"stone-wall", {x = -4.5, y = -5.5}, {}},
    {"stone-wall", {x = -5.5, y = -5.5}, {}},
    {"stone-wall", {x = -5.5, y = -4.5}, {}},
    {"stone-wall", {x = -2.5, y = -5.5}, {}},
    {"stone-wall", {x = -3.5, y = -5.5}, {}},
    {"stone-wall", {x = -0.5, y = -5.5}, {}},
    {"gate", {x = 1.5, y = -5.5}, {dir = "east", }},
    {"stone-wall", {x = 0.5, y = -5.5}, {}},
    {"stone-wall", {x = 0.5, y = -4.5}, {}},
    {"stone-wall", {x = 3.5, y = -5.5}, {}},
    {"stone-wall", {x = 2.5, y = -5.5}, {}},
    {"stone-wall", {x = 5.5, y = -5.5}, {}},
    {"stone-wall", {x = 4.5, y = -5.5}, {}},
    {"stone-wall", {x = 6.5, y = -4.5}, {}},
    {"stone-wall", {x = -5.5, y = -3.5}, {}},
    {"stone-wall", {x = 0.5, y = -3.5}, {}},
    {"stone-wall", {x = 6.5, y = -2.5}, {}},
    {"stone-wall", {x = 6.5, y = -3.5}, {}},
    {"stone-wall", {x = -5.5, y = -1.5}, {}},
    {"stone-wall", {x = 1.5, y = -1.5}, {}},
    {"stone-wall", {x = 0.5, y = -1.5}, {}},
    {"stone-wall", {x = 0.5, y = -0.5}, {}},
    {"stone-wall", {x = 3.5, y = -1.5}, {}},
    {"stone-wall", {x = 6.5, y = -0.5}, {}},
    {"stone-wall", {x = -6.5, y = 1.5}, {}},
    {"stone-wall", {x = -5.5, y = 0.5}, {}},
    {"stone-wall", {x = -0.5, y = 0.5}, {}},
    {"wooden-chest", {x = -0.5, y = 1.5}, {items = {["liquid-sulfuric-acid-barrel"] = {type = "random", min = 2, max = 5}}, }},
    {"stone-wall", {x = -1.5, y = 0.5}, {}},
    {"stone-wall", {x = 0.5, y = 0.5}, {}},
    {"stone-wall", {x = 0.5, y = 1.5}, {}},
    {"stone-wall", {x = 2.5, y = 0.5}, {}},
    {"stone-wall", {x = 5.5, y = 0.5}, {}},
    {"stone-wall", {x = 4.5, y = 0.5}, {}},
    {"stone-wall", {x = 6.5, y = 0.5}, {}},
    {"stone-wall", {x = 6.5, y = 1.5}, {}},
    {"stone-wall", {x = -6.5, y = 3.5}, {}},
    {"stone-wall", {x = 0.5, y = 2.5}, {}},
    {"stone-wall", {x = -6.5, y = 4.5}, {}},
    {"stone-wall", {x = -6.5, y = 5.5}, {}},
    {"stone-wall", {x = -4.5, y = 5.5}, {}},
    {"stone-wall", {x = -2.5, y = 5.5}, {}},
    {"stone-wall", {x = -0.5, y = 5.5}, {}},
    {"stone-wall", {x = 1.5, y = 5.5}, {}},
    {"stone-wall", {x = 3.5, y = 5.5}, {}},
    {"stone-wall", {x = 2.5, y = 5.5}, {}},
  },
}
