require("__zzzparanoidal__.paralib")
--#####################
--Удаление лишних рыб из сборки
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-fish-1", "angels-fish-keeping-0")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-fish-1", "angels-fish-keeping-1")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-fish-1", "angels-fish-keeping-2")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-fish-2", "angels-alien-fish-0-raw")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-fish-2", "angels-alien-fish-1-raw")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-fish-2", "angels-alien-fish-2-raw")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-butchery-1", "angels-fish-butchery-0")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-butchery-1", "angels-fish-butchery-1")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-refugium-butchery-1", "angels-fish-butchery-2")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-pressing-fish-1", "angels-fish-pressing-0")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-pressing-fish-1", "angels-fish-pressing-1")
paralib.bobmods.lib.tech.remove_recipe_unlock("angels-bio-pressing-fish-1", "angels-fish-pressing-2")

paralib.bobmods.lib.recipe.hide("angels-fish-keeping-0")
paralib.bobmods.lib.recipe.hide("angels-fish-keeping-1")
paralib.bobmods.lib.recipe.hide("angels-fish-keeping-2")
paralib.bobmods.lib.recipe.hide("angels-alien-fish-0-raw")
paralib.bobmods.lib.recipe.hide("angels-alien-fish-1-raw")
paralib.bobmods.lib.recipe.hide("angels-alien-fish-2-raw")
paralib.bobmods.lib.recipe.hide("angels-fish-butchery-0")
paralib.bobmods.lib.recipe.hide("angels-fish-butchery-1")
paralib.bobmods.lib.recipe.hide("angels-fish-butchery-2")
paralib.bobmods.lib.recipe.hide("angels-fish-pressing-0")
paralib.bobmods.lib.recipe.hide("angels-fish-pressing-1")
paralib.bobmods.lib.recipe.hide("angels-fish-pressing-2")
