-- A "list" of ruins, including their names
--- @type Ruin[]
local ruins = {}

-- Insert all ruins
for _, name in pairs({
	"artyOutpost",
	"artyOutpost2",
	"beaconedAssembler",
	"buffer",
	"chemicalPlant",
	"circuitLamp",
	"combinators",
	"concreteStumps",
	"crashedTank",
	"crossOfPipes",
	"crossOfPipes2",
	"crossOfPipes3",
	"crossOfPipes4",
	"diagonalWall",
	"diagonalWall2",
	"diagonalWall3",
	"fishHole",
	"flamerOutpost",
	"garage",
	"gateWall",
	"gateWall2",
	"gears",
	"gears2",
	"harmlessTurret",
	"harmlessTurret2",
	"harmlessTurret3",
	"heart",
	"labChain",
	"landMineBunker",
	"landMineBunker2",
	"landMineBunker3",
	"loggingArea",
	"miningSetup",
	"miningSetup2",
	"miningSetup3",
	"miningSetup4",
	"nuclearAccident",
	"offshorePump",
	"oilPumpjack",
	"oilPumpjack2",
	"oilRefinery",
	"oilRefinery2",
	"overwhelmedTurrets",
	"pipeline",
	"pollutedWater",
	"railSection",
	"railSection2",
	"railSection3",
	"railSection4",
	"randomWalls",
	"randomWalls2",
	"randomWalls3",
	"researchStation",
	"researchStation2",
	"researchStation3",
	"researchStation4",
	"researchStation5",
	"robotCraft",
	"robots",
	"rocketFuel",
	"rockStash",
	"rockStash2",
	"rockStash3",
	"rockStash4",
	"rockStash5",
	"rockStash6",
	"rockStash7",
	"shipwreck",
	"smallDestroyedSetup",
	"smallDestroyedSetup2",
	"smallDestroyedSetup3",
	"smallDestroyedSetup4",
	"smallDualSplitter",
	"smallDualSplitter2",
	"smallDualSplitter3",
	"smallMining",
	"smallMining2",
	"smallMining3",
	"smallMining4",
	"smallMountain",
	"smallMountain2",
	"smallMountain3",
	"smallMountain4",
	"smallSmelting",
	"smallSmelting2",
	"smallSmelting3",
	"smallSmelting4",
	"smeltery",
	"smeltery2",
	"smeltery3",
	"solarAccu",
	"solarAccu2",
	"spidertronCorpse",
	"splitterI",
	"splitterI2",
	"splitterI3",
	"steamPower",
	"swamp",
	"twinLasers",
	"twinTurrets"
}) do
	if debug_log then log(string.format("Loading name='%s' ...", name)) end

	---@type Ruin Individual ruin, file' name becomes ruin's name
	local ruin = require(name)
	ruin.name = name
	ruins[#ruins + 1] = ruin
end

return ruins
