return
{
  entities =
  {
    {"tree-05-stump", {x = -3.13, y = -2.85}, {dir = "south", }},
    {"tree-05-stump", {x = 0.54, y = -3.23}, {dir = "south", }},
    {"tree-05-stump", {x = 3.3, y = -3.59}, {dir = "south", }},
    {"tree-05-stump", {x = -1.45, y = -0.54}, {dir = "south", }},
    {"tree-05-stump", {x = 1.53, y = -1.54}, {dir = "south", }},
    {"tree-05-stump", {x = -3.5, y = 1.89}, {dir = "south", }},
    {"tree-05-stump", {x = -3, y = 3.27}, {dir = "south", }},
    {"tree-05-stump", {x = 1.7, y = 2.48}, {dir = "south", }},
    {"tree-05-stump", {x = 3.2, y = 3.39}, {dir = "south", }},
  },
  tiles =
  {
    {"stone-path", {x = -4, y = -1}},
    {"stone-path", {x = -3, y = -2}},
    {"stone-path", {x = -3, y = -1}},
    {"stone-path", {x = -3, y = 0}},
    {"stone-path", {x = -2, y = -4}},
    {"stone-path", {x = -2, y = -3}},
    {"stone-path", {x = -2, y = -2}},
    {"stone-path", {x = -2, y = 0}},
    {"stone-path", {x = -2, y = 1}},
    {"stone-path", {x = -2, y = 2}},
    {"stone-path", {x = -1, y = -3}},
    {"stone-path", {x = -1, y = -2}},
    {"stone-path", {x = -1, y = -1}},
    {"concrete", {x = -1, y = 0}},
    {"stone-path", {x = -1, y = 1}},
    {"stone-path", {x = -1, y = 2}},
    {"stone-path", {x = 0, y = -3}},
    {"stone-path", {x = 0, y = -2}},
    {"concrete", {x = 0, y = -1}},
    {"concrete", {x = 0, y = 0}},
    {"stone-path", {x = 0, y = 1}},
    {"stone-path", {x = 0, y = 2}},
    {"stone-path", {x = 0, y = 3}},
    {"stone-path", {x = 1, y = -3}},
    {"stone-path", {x = 1, y = -1}},
    {"stone-path", {x = 1, y = 0}},
    {"stone-path", {x = 1, y = 1}},
    {"stone-path", {x = 1, y = 3}},
    {"stone-path", {x = 2, y = -3}},
    {"stone-path", {x = 2, y = -2}},
    {"stone-path", {x = 2, y = -1}},
    {"stone-path", {x = 2, y = 0}},
    {"stone-path", {x = 2, y = 1}},
    {"stone-path", {x = 3, y = -3}},
    {"stone-path", {x = 3, y = -2}},
    {"stone-path", {x = 3, y = -1}},
  }
}
