return
{
  entities =
  {
    {"tree-06", {x = -0.44, y = -0.59}, {}},
    {"tree-06", {x = 3.18, y = 0.39}, {}},
    {"tree-06", {x = -0.49, y = 3.05}, {}},
  },
  tiles =
  {
    {"water-shallow", {x = -4, y = -2}},
    {"water-shallow", {x = -4, y = -1}},
    {"water-shallow", {x = -4, y = 0}},
    {"water-shallow", {x = -3, y = -3}},
    {"water-shallow", {x = -3, y = -2}},
    {"water-shallow", {x = -3, y = -1}},
    {"water-shallow", {x = -3, y = 0}},
    {"water-shallow", {x = -2, y = -3}},
    {"water-shallow", {x = -2, y = -2}},
    {"water-shallow", {x = -2, y = -1}},
    {"water-shallow", {x = -2, y = 0}},
    {"water-shallow", {x = -2, y = 1}},
    {"water-shallow", {x = -1, y = -4}},
    {"water-shallow", {x = -1, y = -3}},
    {"water-shallow", {x = -1, y = -2}},
    {"water-shallow", {x = -1, y = 0}},
    {"water-shallow", {x = -1, y = 1}},
    {"water-shallow", {x = 0, y = -4}},
    {"water-shallow", {x = 0, y = -3}},
    {"water-shallow", {x = 0, y = -2}},
    {"water-shallow", {x = 0, y = -1}},
    {"water-shallow", {x = 0, y = 0}},
    {"water-shallow", {x = 0, y = 1}},
    {"water-shallow", {x = 0, y = 3}},
    {"water-shallow", {x = 1, y = -4}},
    {"water-shallow", {x = 1, y = -3}},
    {"water-shallow", {x = 1, y = -2}},
    {"water-shallow", {x = 1, y = -1}},
    {"water-shallow", {x = 1, y = 0}},
    {"water-shallow", {x = 1, y = 2}},
    {"water-shallow", {x = 1, y = 3}},
    {"water-shallow", {x = 2, y = -4}},
    {"water-shallow", {x = 2, y = -3}},
    {"water-shallow", {x = 2, y = -2}},
    {"water-shallow", {x = 2, y = 1}},
    {"water-shallow", {x = 2, y = 2}},
    {"water-shallow", {x = 2, y = 3}},
    {"water-shallow", {x = 3, y = -3}},
    {"water-shallow", {x = 3, y = -2}},
    {"water-shallow", {x = 3, y = 1}},
    {"water-shallow", {x = 3, y = 2}},
    {"water-shallow", {x = 3, y = 3}},
  }
}
