data:extend({
    {
        type = "bool-setting",
        name = "science-oberhaul",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "modules-use-circuits",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "angels-ores-only",
        setting_type = "startup",
        default_value = false,
    },
    {
        type = "bool-setting",
        name = "belt-speed-change",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "petrochem-change",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "bobs-module-nerf",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "module-slot-nerf",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "beacon-removal-mk2",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "beacon-removal-mk3",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "module-cost-multiply",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "bobs-solar-multiply",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "train-wagon-nerf",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "bobs-military-simplify",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "simple-cordite",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "gem-liquifaction",
        setting_type = "startup",
        default_value = true,
    },
    {
        type = "bool-setting",
        name = "bob-simple-logistics",
        setting_type = "startup",
        default_value = false,
    },
    {
        type = "bool-setting",
        name = "electrolyser-merge",
        setting_type = "startup",
        default_value = true,
    },
})