data:extend({
  {
    type = "bool-setting",
    name = "bnl-enable",
    setting_type = "startup",
    default_value = true,
    order = "a",
  },
  {
    type = "bool-setting",
    name = "bnl-glow",
    setting_type = "startup",
    default_value = true,
    order = "a",
  },
  {
    type = "bool-setting",
    name = "bnl-include-mining-drills",
    setting_type = "startup",
    default_value = true,
    order = "a",
  },
  {
    type = "string-setting",
    name = "bnl-indicator-size",
    setting_type = "startup",
    default_value = "small",
    allowed_values = { "small", "medium", "large", "huge" },
    order = "a",
  },
  {
    type = "color-setting",
    name = "bnl-color-disabled",
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-full_output",
    setting_type = "startup",
    default_value = { r = 1, g = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-idle",
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-insufficient_input",
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-low_power",
    setting_type = "startup",
    default_value = { r = 1, g = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-no_minable_resources",
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-no_power",
    setting_type = "startup",
    default_value = { r = 1 },
    order = "b",
  },
  {
    type = "color-setting",
    name = "bnl-color-working",
    setting_type = "startup",
    default_value = { g = 1 },
    order = "b",
  },
})
