-- Материалы должны быть доступны из предков технологии, открывающей их потребителей.
-- После OV.execute и восстановления дерева; рецептуры и цены не меняются.
local prerequisites = {
    { "basic-logistics", "steam-power" },
    { "angels-coal-processing", "steam-power" },
    { "angels-ore-crushing", "steam-power" },
    { "bob-alloy-processing", "angels-basic-chemistry-2" },
    { "electronics", "bi-tech-timber" },
    { "remelting-alloy-mixer-1", "steel-processing" },
    { "angels-cooling", "angels-stone-smelting-1" },
    { "bob-oil-boiler-1", "OilBurning" },
    { "angels-water-washing-2", "concrete" },
    { "angels-slag-processing-1", "bi-tech-ash" },
    { "angels-advanced-ore-refining-1", "engine" },
    { "angels-aluminium-smelting-1", "angels-sulfur-processing-1" },
    { "bi-tech-depollution-1", "bi-tech-fertilizer" },
    { "artillery-prototype", "concrete" },
    { "artillery-prototype", "engine" },
    { "automated-rail-transportation", "automated-scrap-rail-transportation" },
    { "angels-bio-farm-2", "concrete" },
    { "robotics", "angels-aluminium-smelting-1" },
    { "w93-modular-turrets2", "concrete" },
    { "advanced-circuit", "angels-bio-paper-1" },
    { "advanced-circuit", "angels-resin-1" },
    { "angels-water-treatment-3", "angels-metallurgy-3" },
    { "big-burner-generator", "bob-heat-exchanger-1" },
    { "big-burner-generator", "concrete" },
    { "petroleum-generator", "angels-metallurgy-3" },
    { "petroleum-generator", "bob-steam-engine-3" },
    { "bob-robo-modular-1", "concrete" },
    { "bob-vehicle-roboport-equipment-1", "concrete" },
    { "angels-bio-refugium-fish-2", "concrete" },
    { "angels-bio-refugium-fish-2", "angels-bio-temperate-farming-1" },
    { "roboport-interface", "bob-robo-modular-1" },
    { "Fuel-Additive", "angels-advanced-chemistry-3" },
    { "angels-sodium-processing-3", "angels-lead-smelting-3" },
    { "cargo-planes", "military" },
    { "angels-advanced-ore-refining-2", "electric-engine" },
    { "battery-mk2-equipment", "processing-unit" },
    { "angels-advanced-chemistry-3", "mercury-processing-1" },
    { "offshore-mk3-pump", "bob-titanium-processing" },
    { "angels-water-washing-3", "bob-drills-2" },
    { "processing-unit", "angels-rubber" },
    { "bob-boiler-4", "angels-tungsten-smelting-1" },
    { "texugo-wind-turbine3", "electric-energy-distribution-2" },
    { "angels-coolant-2", "angels-steel-smelting-3" },
    { "angels-bio-refugium-butchery-3", "bob-titanium-processing" },
    { "angels-advanced-chemistry-4", "angels-ore-refining" },
    { "angels-advanced-chemistry-4", "bob-titanium-processing" },
    { "bob-turbo-inserter", "bob-cobalt-processing" },
    { "CW-air-filtering-5", "angels-nitinol-smelting-1" },
    { "bob-advanced-research", "electric-lab" },
    { "angels-advanced-chemistry-5", "k-angels-advanced-chemistry-5" },
    { "angels-advanced-chemistry-5", "bob-tungsten-processing" },
    { "bob-nuclear-power-3", "angels-thorium-power" },
    { "module-merging", "angels-gunmetal-smelting-1" },
    { "bob-plasma-rocket", "bob-rocket" },
    { "fuel-cells", "advanced-osmium-smelting" },
    { "habitation", "advanced-osmium-smelting" },
    { "space-casings", "advanced-osmium-smelting" },
    -- Согласованное исключение ПР-040: только предки плазменных турелей II–IV.
    { "bob-plasma-turrets-2", "bob-laser-turrets-2" },
    { "bob-plasma-turrets-3", "bob-laser-turrets-3" },
    { "bob-plasma-turrets-4", "bob-laser-turrets-4" },
    -- Буры IV намеренно ждут жёлтую науку через нитиноловые шестерни.
    { "bob-drills-4", "angels-tungsten-carbide-smelting-1" },
    { "bob-drills-4", "bob-nitinol-processing" },
    { "bob-area-drills-4", "bob-drills-4" },
    -- Растительный корм и пульпа для цепочки полных биокристаллов.
    { "angels-bio-refugium-puffer-2", "angels-bio-temperate-farming-1" },
}
for _, pair in ipairs(prerequisites) do
    if data.raw.technology[pair[1]] and data.raw.technology[pair[2]] then
        paralib.bobmods.lib.tech.add_prerequisite(pair[1], pair[2])
    end
end
