-- Технология -> маркер (level: уровень, "inf" = ∞; corner = "left": уровень слева; badge: значок ветки, badge_type = "recipe": иконка рецепта).
-- badge_from_unlocks: значок первого отличающегося открываемого продукта. Основа таблицы — отчёт v2 (Factorio 2.0.77, 029f07531f).
return {
    ["Schall-pickup-tower-1"] = { level = 1 },
    ["Schall-pickup-tower-2"] = { level = 2 },
    ["Schall-pickup-tower-3"] = { level = 3 },
    ["Schall-pickup-tower-4"] = { level = 4 },
    ["Schall-tank-1"] = { level = 1, corner = "left" },
    ["Schall-tank-2"] = { level = 2, corner = "left" },
    ["Schall-tank-F-0"] = { level = 0, corner = "left" },
    ["Schall-tank-F-1"] = { level = 1, corner = "left" },
    ["Schall-tank-F-2"] = { level = 2, corner = "left" },
    ["Schall-tank-H-0"] = { level = 0, corner = "left" },
    ["Schall-tank-H-1"] = { level = 1, corner = "left" },
    ["Schall-tank-H-2"] = { level = 2, corner = "left" },
    ["Schall-tank-SH-0"] = { level = 0, corner = "left" },
    ["Schall-tank-SH-1"] = { level = 1, corner = "left" },
    ["Schall-tank-SH-2"] = { level = 2, corner = "left" },
    ["Space-Lab-Research-1"] = { level = 1 },
    ["Space-Lab-Research-21"] = { level = 2 },
    ["Space-Lab-Research-41"] = { level = 3 },
    ["Space-Lab-Research-61"] = { level = "inf" },
    ["advanced-battery-research-1"] = { level = 1 },
    ["advanced-battery-research-11"] = { level = 2 },
    ["advanced-battery-research-21"] = { level = "inf" },
    ["advanced-depleted-uranium-smelting-1"] = { level = 1 },
    ["advanced-depleted-uranium-smelting-2"] = { level = 2 },
    ["advanced-fan-research-1"] = { level = 1 },
    ["advanced-fan-research-11"] = { level = 2 },
    ["advanced-fan-research-21"] = { level = "inf" },
    ["advanced-radiation-protection"] = { badge = "radiation-absorption-equipment-mk2", badge_type = "item" },
    ["advanced-uranium-processing-1"] = { level = 1 },
    ["advanced-uranium-processing-2"] = { level = 2 },
    ["angels-advanced-bio-processing"] = { badge = "production-science-pack", badge_type = "item" },
    ["angels-advanced-chemistry-1"] = { level = 1 },
    ["angels-advanced-chemistry-2"] = { level = 2 },
    ["angels-advanced-chemistry-3"] = { level = 3 },
    ["angels-advanced-chemistry-4"] = { level = 4 },
    ["angels-advanced-chemistry-5"] = { level = 5 },
    ["angels-advanced-oil-processing"] = { badge = "angels-gas-hydrogen", badge_type = "fluid" },
    ["angels-aluminium-casting-2"] = { level = 2 },
    ["angels-aluminium-casting-3"] = { level = 3 },
    ["angels-aluminium-smelting-1"] = { level = 1 },
    ["angels-aluminium-smelting-2"] = { level = 2 },
    ["angels-aluminium-smelting-3"] = { level = 3 },
    ["angels-basic-chemistry"] = { level = 1 },
    ["angels-basic-chemistry-2"] = { level = 2 },
    ["angels-basic-chemistry-3"] = { level = 3 },
    ["angels-bio-arboretum-1"] = { level = 1 },
    ["angels-bio-arboretum-2"] = { level = 2 },
    ["angels-bio-arboretum-3"] = { level = 3 },
    ["angels-bio-arboretum-desert-1"] = { level = 1 },
    ["angels-bio-arboretum-desert-2"] = { level = 2 },
    ["angels-bio-arboretum-desert-3"] = { level = 3 },
    ["angels-bio-arboretum-swamp-1"] = { level = 1 },
    ["angels-bio-arboretum-swamp-2"] = { level = 2 },
    ["angels-bio-arboretum-swamp-3"] = { level = 3 },
    ["angels-bio-arboretum-temperate-1"] = { level = 1 },
    ["angels-bio-arboretum-temperate-2"] = { level = 2 },
    ["angels-bio-arboretum-temperate-3"] = { level = 3 },
    ["angels-bio-desert-farm"] = { badge = "angels-desert-farm", badge_type = "item" },
    ["angels-bio-desert-farming-1"] = { level = 1 },
    ["angels-bio-desert-farming-2"] = { level = 2 },
    ["angels-bio-farm-1"] = { level = 1 },
    ["angels-bio-farm-2"] = { level = 2 },
    ["angels-bio-farm-3"] = { level = 3 },
    ["angels-bio-farm-advanced-upgrade-1"] = { level = 1, badge = "angels-desert-farm-2", badge_type = "item" },
    ["angels-bio-farm-advanced-upgrade-2"] = { level = 2, badge = "angels-desert-farm-2", badge_type = "item" },
    ["angels-bio-farm-alien"] = { badge = "angels-solid-alienated-fertilizer", badge_type = "item" },
    ["angels-bio-fermentation"] = { badge = "angels-liquid-fermentation-raw", badge_type = "fluid" },
    ["angels-bio-nutrient-paste"] = { level = 1 },
    ["angels-bio-nutrient-paste-2"] = { level = 2 },
    ["angels-bio-paper-1"] = { level = 1 },
    ["angels-bio-paper-2"] = { level = 2 },
    ["angels-bio-paper-3"] = { level = 3 },
    ["angels-bio-plastic-1"] = { level = 1 },
    ["angels-bio-plastic-2"] = { level = 2 },
    ["angels-bio-pressing-1"] = { level = 1 },
    ["angels-bio-pressing-2"] = { level = 2 },
    ["angels-bio-pressing-fish-1"] = { level = 1, badge = "angels-fish-pulp", badge_type = "item" },
    ["angels-bio-pressing-fish-2"] = { level = 2, badge = "angels-fish-pulp", badge_type = "item" },
    ["angels-bio-processing-alien-1"] = { level = 1 },
    ["angels-bio-processing-alien-2"] = { level = 2 },
    ["angels-bio-processing-alien-3"] = { level = 3 },
    ["angels-bio-processing-blue"] = { badge = "angels-algae-blue", badge_type = "item" },
    ["angels-bio-processing-brown"] = { badge = "angels-algae-brown", badge_type = "item" },
    ["angels-bio-processing-crystal-full"] = { badge = "angels-crystal-full-raw", badge_type = "item" },
    ["angels-bio-processing-crystal-shard-1"] = { level = 1, badge = "angels-crystal-shard-raw", badge_type = "item" },
    ["angels-bio-processing-crystal-shard-2"] = { level = 2, badge = "angels-crystal-shard-raw", badge_type = "item" },
    ["angels-bio-processing-crystal-splinter-1"] = { level = 1, badge = "angels-crystal-splinter-raw", badge_type = "item" },
    ["angels-bio-processing-crystal-splinter-2"] = { level = 2, badge = "angels-crystal-splinter-raw", badge_type = "item" },
    ["angels-bio-processing-crystal-splinter-3"] = { level = 3, badge = "angels-crystal-splinter-raw", badge_type = "item" },
    ["angels-bio-processing-green"] = { badge = "angels-algae-green", badge_type = "item" },
    ["angels-bio-processing-red"] = { badge = "angels-algae-red", badge_type = "item" },
    ["angels-bio-refugium-biter-1"] = { level = 1 },
    ["angels-bio-refugium-biter-2"] = { level = 2 },
    ["angels-bio-refugium-biter-3"] = { level = 3 },
    ["angels-bio-refugium-butchery-1"] = { level = 1 },
    ["angels-bio-refugium-butchery-2"] = { level = 2 },
    ["angels-bio-refugium-butchery-3"] = { level = 3 },
    ["angels-bio-refugium-fish-1"] = { level = 1 },
    ["angels-bio-refugium-fish-2"] = { level = 2 },
    ["angels-bio-refugium-fish-4"] = { level = 3 },
    ["angels-bio-refugium-hatchery"] = { level = 1 },
    ["angels-bio-refugium-hatchery-2"] = { level = 2 },
    ["angels-bio-refugium-puffer-1"] = { level = 1 },
    ["angels-bio-refugium-puffer-2"] = { level = 2 },
    ["angels-bio-refugium-puffer-3"] = { level = 3 },
    ["angels-bio-refugium-puffer-4"] = { level = 4 },
    ["angels-bio-swamp-farm"] = { badge = "angels-swamp-farm", badge_type = "item" },
    ["angels-bio-swamp-farming-1"] = { level = 1 },
    ["angels-bio-swamp-farming-2"] = { level = 2 },
    ["angels-bio-temperate-farm"] = { badge = "angels-temperate-farm", badge_type = "item" },
    ["angels-bio-temperate-farming-1"] = { level = 1 },
    ["angels-bio-temperate-farming-2"] = { level = 2 },
    ["angels-bio-wood-processing"] = { level = 1 },
    ["angels-bio-wood-processing-2"] = { level = 2 },
    ["angels-bio-wood-processing-3"] = { level = 3 },
    ["angels-brass-smelting-1"] = { level = 1 },
    ["angels-brass-smelting-2"] = { level = 2 },
    ["angels-brass-smelting-3"] = { level = 3 },
    ["angels-bronze-smelting-1"] = { level = 1 },
    ["angels-bronze-smelting-2"] = { level = 2 },
    ["angels-bronze-smelting-3"] = { level = 3 },
    ["angels-chlorine-processing-1"] = { level = 1 },
    ["angels-chlorine-processing-2"] = { level = 2 },
    ["angels-chlorine-processing-3"] = { level = 3 },
    ["angels-chlorine-processing-4"] = { level = 4 },
    ["angels-chrome-smelting-1"] = { level = 1 },
    ["angels-chrome-smelting-2"] = { level = 2 },
    ["angels-chrome-smelting-3"] = { level = 3 },
    ["angels-coal-cracking"] = { badge = "angels-gas-hydrogen-sulfide", badge_type = "fluid" },
    ["angels-coal-processing"] = { level = 1 },
    ["angels-coal-processing-2"] = { level = 2 },
    ["angels-coal-processing-3"] = { level = 3 },
    ["angels-cobalt-casting-2"] = { level = 2 },
    ["angels-cobalt-casting-3"] = { level = 3 },
    ["angels-cobalt-smelting-1"] = { level = 1 },
    ["angels-cobalt-smelting-2"] = { level = 2 },
    ["angels-cobalt-smelting-3"] = { level = 3 },
    ["angels-cobalt-steel-smelting-1"] = { level = 1, badge = "bob-cobalt-steel-alloy", badge_type = "item" },
    ["angels-composting"] = { badge = "angels-solid-compost", badge_type = "item" },
    ["angels-coolant-1"] = { level = 1 },
    ["angels-coolant-2"] = { level = 2 },
    ["angels-cooling"] = { badge = "angels-cooling-tower", badge_type = "item" },
    ["angels-copper-casting-2"] = { level = 2 },
    ["angels-copper-casting-3"] = { level = 3 },
    ["angels-copper-smelting-1"] = { level = 1 },
    ["angels-copper-smelting-2"] = { level = 2 },
    ["angels-copper-smelting-3"] = { level = 3 },
    ["angels-copper-tungsten-smelting-1"] = { level = 1 },
    ["angels-copper-tungsten-smelting-2"] = { level = 2 },
    ["angels-electric-boiler"] = { level = 1 },
    ["angels-electric-boiler-2"] = { level = 2 },
    ["angels-electric-boiler-3"] = { level = 3 },
    ["angels-explosives-1"] = { level = 1 },
    ["angels-explosives-2"] = { level = 2 },
    ["angels-gardens"] = { level = 1 },
    ["angels-gardens-2"] = { level = 2 },
    ["angels-gardens-3"] = { level = 3 },
    ["angels-geode-crystallization-1"] = { level = 1 },
    ["angels-geode-crystallization-2"] = { level = 2 },
    ["angels-glass-smelting-1"] = { level = 1 },
    ["angels-glass-smelting-2"] = { level = 2 },
    ["angels-glass-smelting-3"] = { level = 3 },
    ["angels-gold-casting-2"] = { level = 2 },
    ["angels-gold-casting-3"] = { level = 3 },
    ["angels-gold-smelting-1"] = { level = 1 },
    ["angels-gold-smelting-2"] = { level = 2 },
    ["angels-gold-smelting-3"] = { level = 3 },
    ["angels-iron-casting-2"] = { level = 2 },
    ["angels-iron-casting-3"] = { level = 3 },
    ["angels-iron-casting-4"] = { level = 4 },
    ["angels-iron-smelting-1"] = { level = 1 },
    ["angels-iron-smelting-2"] = { level = 2 },
    ["angels-iron-smelting-3"] = { level = 3 },
    ["angels-lead-casting-2"] = { level = 2 },
    ["angels-lead-casting-3"] = { level = 3 },
    ["angels-lead-smelting-1"] = { level = 1 },
    ["angels-lead-smelting-2"] = { level = 2 },
    ["angels-lead-smelting-3"] = { level = 3 },
    ["angels-manganese-smelting-1"] = { level = 1 },
    ["angels-manganese-smelting-2"] = { level = 2 },
    ["angels-manganese-smelting-3"] = { level = 3 },
    ["angels-nickel-casting-2"] = { level = 2 },
    ["angels-nickel-casting-3"] = { level = 3 },
    ["angels-nickel-smelting-1"] = { level = 1 },
    ["angels-nickel-smelting-2"] = { level = 2 },
    ["angels-nickel-smelting-3"] = { level = 3 },
    ["angels-nitrogen-processing-1"] = { level = 1 },
    ["angels-nitrogen-processing-2"] = { level = 2 },
    ["angels-nitrogen-processing-3"] = { level = 3 },
    ["angels-nitrogen-processing-4"] = { level = 4 },
    ["angels-oil-steam-cracking-2"] = { level = 2, badge = "angels-liquid-naphtha", badge_type = "fluid" },
    ["angels-ore-advanced-crushing"] = { badge = "angels-ore8-crushed", badge_type = "item" },
    ["angels-ore-advanced-floatation"] = { badge = "angels-ore8-sludge", badge_type = "fluid" },
    ["angels-ore-powderizer"] = { badge = "angels-milling-drum", badge_type = "item" },
    ["angels-platinum-casting-2"] = { level = 2 },
    ["angels-platinum-casting-3"] = { level = 3 },
    ["angels-platinum-smelting-1"] = { level = 1 },
    ["angels-platinum-smelting-2"] = { level = 2 },
    ["angels-platinum-smelting-3"] = { level = 3 },
    ["angels-resin-1"] = { level = 1 },
    ["angels-resin-2"] = { level = 2 },
    ["angels-resin-3"] = { level = 3 },
    ["angels-rocket-booster-1"] = { level = 1 },
    ["angels-rocket-booster-2"] = { level = 2 },
    ["angels-silicon-casting-2"] = { level = 2 },
    ["angels-silicon-smelting-1"] = { level = 1 },
    ["angels-silicon-smelting-2"] = { level = 2 },
    ["angels-silicon-smelting-3"] = { level = 3 },
    ["angels-silver-casting-2"] = { level = 2 },
    ["angels-silver-casting-3"] = { level = 3 },
    ["angels-silver-smelting-1"] = { level = 1 },
    ["angels-silver-smelting-2"] = { level = 2 },
    ["angels-silver-smelting-3"] = { level = 3 },
    ["angels-slag-processing-1"] = { level = 1 },
    ["angels-slag-processing-2"] = { level = 2 },
    ["angels-slag-processing-3"] = { level = 3 },
    ["angels-sodium-processing-1"] = { level = 1 },
    ["angels-sodium-processing-3"] = { level = 2 },
    ["angels-solder-smelting-1"] = { level = 1 },
    ["angels-solder-smelting-2"] = { level = 2 },
    ["angels-solder-smelting-3"] = { level = 3 },
    ["angels-steam-cracking-1"] = { level = 1 },
    ["angels-steam-cracking-2"] = { level = 2 },
    ["angels-steel-smelting-1"] = { level = 1 },
    ["angels-steel-smelting-2"] = { level = 2 },
    ["angels-steel-smelting-3"] = { level = 3 },
    ["angels-steel-smelting-4"] = { level = 4 },
    ["angels-stone-smelting-1"] = { level = 1 },
    ["angels-stone-smelting-2"] = { level = 2 },
    ["angels-stone-smelting-3"] = { level = 3 },
    ["angels-stone-smelting-4"] = { level = 4 },
    ["angels-sulfur-processing-1"] = { level = 1 },
    ["angels-sulfur-processing-2"] = { level = 2 },
    ["angels-sulfur-processing-3"] = { level = 3 },
    ["angels-thermal-water-extraction"] = { level = 1 },
    ["angels-thermal-water-extraction-2"] = { level = 2 },
    ["angels-tin-casting-2"] = { level = 2 },
    ["angels-tin-casting-3"] = { level = 3 },
    ["angels-tin-smelting-1"] = { level = 1 },
    ["angels-tin-smelting-2"] = { level = 2 },
    ["angels-tin-smelting-3"] = { level = 3 },
    ["angels-titanium-casting-2"] = { level = 2 },
    ["angels-titanium-casting-3"] = { level = 3 },
    ["angels-titanium-smelting-1"] = { level = 1 },
    ["angels-titanium-smelting-2"] = { level = 2 },
    ["angels-titanium-smelting-3"] = { level = 3 },
    ["angels-tungsten-carbide-smelting-1"] = { level = 1 },
    ["angels-tungsten-carbide-smelting-2"] = { level = 2 },
    ["angels-tungsten-carbide-smelting-3"] = { level = 3 },
    ["angels-tungsten-smelting-1"] = { level = 1 },
    ["angels-tungsten-smelting-2"] = { level = 2 },
    ["angels-tungsten-smelting-3"] = { level = 3 },
    ["angels-water-chemistry-1"] = { level = 1 },
    ["angels-water-chemistry-2"] = { level = 2 },
    ["angels-water-washing-1"] = { level = 1 },
    ["angels-water-washing-2"] = { level = 2 },
    ["angels-water-washing-3"] = { level = 3 },
    ["angels-water-washing-4"] = { level = 4 },
    ["angels-zinc-casting-2"] = { level = 2 },
    ["angels-zinc-casting-3"] = { level = 3 },
    ["angels-zinc-smelting-1"] = { level = 1 },
    ["angels-zinc-smelting-2"] = { level = 2 },
    ["angels-zinc-smelting-3"] = { level = 3 },
    ["armor-absorb-1"] = { level = 1 },
    ["armor-absorb-10"] = { level = 10 },
    ["armor-absorb-11"] = { level = 11 },
    ["armor-absorb-12"] = { level = 12 },
    ["armor-absorb-13"] = { level = 13 },
    ["armor-absorb-14"] = { level = 14 },
    ["armor-absorb-15"] = { level = 15 },
    ["armor-absorb-16"] = { level = 16 },
    ["armor-absorb-17"] = { level = 17 },
    ["armor-absorb-18"] = { level = 18 },
    ["armor-absorb-19"] = { level = 19 },
    ["armor-absorb-2"] = { level = 2 },
    ["armor-absorb-20"] = { level = 20 },
    ["armor-absorb-21"] = { level = 21 },
    ["armor-absorb-22"] = { level = 22 },
    ["armor-absorb-23"] = { level = 23 },
    ["armor-absorb-24"] = { level = 24 },
    ["armor-absorb-25"] = { level = 25 },
    ["armor-absorb-3"] = { level = 3 },
    ["armor-absorb-4"] = { level = 4 },
    ["armor-absorb-5"] = { level = 5 },
    ["armor-absorb-6"] = { level = 6 },
    ["armor-absorb-7"] = { level = 7 },
    ["armor-absorb-8"] = { level = 8 },
    ["armor-absorb-9"] = { level = 9 },
    ["automated-scrap-rail-transportation"] = { badge = "train-stop-scrap", badge_type = "item" },
    ["bi-tech-ash"] = { badge = "bi-ash", badge_type = "item" },
    ["bi-tech-cellulose-1"] = { level = 1 },
    ["bi-tech-cellulose-2"] = { level = 2 },
    ["bi-tech-coal-processing-1"] = { level = 1 },
    ["bi-tech-coal-processing-2"] = { level = 2 },
    ["bi-tech-coal-processing-3"] = { level = 3 },
    ["bi-tech-depollution-1"] = { level = 1, badge = "bi-purified-air", badge_type = "item" },
    ["bi-tech-depollution-2"] = { level = 2, badge = "bi-purified-air", badge_type = "item" },
    ["bi-tech-fertilizer"] = { badge = "bi-fertilizer-2", badge_type = "recipe" },
    ["bi-tech-garden-1"] = { level = 1 },
    ["bi-tech-garden-2"] = { level = 2 },
    ["bi-tech-garden-3"] = { level = 3 },
    ["bi-tech-organic-plastic"] = { badge = "plastic-bar", badge_type = "item" },
    ["bob-armoured-fluid-wagon"] = { level = 1, badge = "bob-armoured-fluid-wagon", badge_type = "item" },
    ["bob-armoured-fluid-wagon-2"] = { level = 2, badge = "bob-armoured-fluid-wagon", badge_type = "item" },
    ["bob-armoured-railway"] = { level = 1, badge = "bob-armoured-locomotive", badge_type = "item" },
    ["bob-armoured-railway-2"] = { level = 2, badge = "bob-armoured-locomotive", badge_type = "item" },
    ["bob-electronics-machine-1"] = { level = 1 },
    ["bob-electronics-machine-2"] = { level = 2 },
    ["bob-electronics-machine-3"] = { level = 3 },
    ["bob-fluid-wagon-2"] = { level = 2 },
    ["bob-fluid-wagon-3"] = { level = 3 },
    ["bob-heat-pipe-1"] = { level = 1 },
    ["bob-heat-pipe-2"] = { level = 2 },
    ["bob-heat-pipe-3"] = { level = 3 },
    ["bob-heat-pipe-4"] = { level = 4 },
    ["bob-more-inserters-1"] = { level = 1 },
    ["bob-more-inserters-2"] = { level = 2 },
    ["bob-railway-2"] = { level = 2 },
    ["bob-railway-3"] = { level = 3 },
    ["bob-steel-axe-2"] = { level = 2 },
    ["bob-steel-axe-3"] = { level = 3 },
    ["bob-steel-axe-4"] = { level = 4 },
    ["bob-steel-axe-5"] = { level = 5 },
    ["braking-force-1"] = { level = 1 },
    ["braking-force-2"] = { level = 2 },
    ["braking-force-3"] = { level = 3 },
    ["braking-force-4"] = { level = 4 },
    ["braking-force-5"] = { level = 5 },
    ["braking-force-6"] = { level = 6 },
    ["braking-force-7"] = { level = 7 },
    ["braking-force-8"] = { level = "inf" },
    ["chrome-ore-refining"] = { badge = "angels-chrome-ore", badge_type = "item" },
    ["clowns-ore-electro-whinning-cell"] = { badge_from_unlocks = true },
    ["clowns-ore-leaching"] = { badge_from_unlocks = true },
    ["concrete-gates"] = { badge = "concrete", badge_type = "item" },
    ["concrete-walls"] = { badge = "concrete", badge_type = "item" },
    ["electronics-machine-4"] = { level = 4 },
    ["electronics-machine-5"] = { level = 5 },
    ["fluid-wagon"] = { level = 1 },
    ["follower-robot-count-1"] = { level = 1 },
    ["follower-robot-count-2"] = { level = 2 },
    ["follower-robot-count-3"] = { level = 3 },
    ["follower-robot-count-4"] = { level = 4 },
    ["follower-robot-count-5"] = { level = "inf" },
    ["ftl-propulsion"] = { badge = "ftl-drive", badge_type = "item" },
    ["ftl-theory-A"] = { badge = "automation-science-pack", badge_type = "item" },
    ["ftl-theory-B"] = { badge = "logistic-science-pack", badge_type = "item" },
    ["ftl-theory-C"] = { badge = "chemical-science-pack", badge_type = "item" },
    ["ftl-theory-D"] = { badge = "military-science-pack", badge_type = "item" },
    ["ftl-theory-D1"] = { badge = "production-science-pack", badge_type = "item" },
    ["ftl-theory-D2"] = { badge = "utility-science-pack", badge_type = "item" },
    ["inserter-capacity-bonus-1"] = { level = 1 },
    ["inserter-capacity-bonus-2"] = { level = 2 },
    ["inserter-capacity-bonus-3"] = { level = 3 },
    ["inserter-capacity-bonus-4"] = { level = 4 },
    ["inserter-capacity-bonus-5"] = { level = 5 },
    ["inserter-capacity-bonus-6"] = { level = 6 },
    ["inserter-capacity-bonus-7"] = { level = 7 },
    ["inserter-capacity-bonus-8"] = { level = "inf" },
    ["inserter-stack-size-bonus-1"] = { level = 1 },
    ["inserter-stack-size-bonus-2"] = { level = 2 },
    ["inserter-stack-size-bonus-3"] = { level = 3 },
    ["inserter-stack-size-bonus-4"] = { level = 4 },
    ["k-angels-advanced-chemistry-5"] = { badge = "angels-liquid-phenol", badge_type = "fluid" },
    ["laboratory-productivity-1"] = { level = 1 },
    ["laboratory-productivity-2"] = { level = 2 },
    ["laboratory-productivity-3"] = { level = 3 },
    ["laboratory-productivity-4"] = { level = 4 },
    ["laboratory-productivity-5"] = { level = 5 },
    ["laboratory-productivity-6"] = { level = 6 },
    ["laboratory-productivity-7"] = { level = 7 },
    ["laboratory-productivity-8"] = { level = "inf" },
    ["laser-shooting-speed-1"] = { level = 1 },
    ["laser-shooting-speed-2"] = { level = 2 },
    ["laser-shooting-speed-3"] = { level = 3 },
    ["laser-shooting-speed-4"] = { level = 4 },
    ["laser-shooting-speed-5"] = { level = 5 },
    ["laser-shooting-speed-6"] = { level = 6 },
    ["laser-shooting-speed-7"] = { level = 7 },
    ["laser-weapons-damage-1"] = { level = 1 },
    ["laser-weapons-damage-2"] = { level = 2 },
    ["laser-weapons-damage-3"] = { level = 3 },
    ["laser-weapons-damage-4"] = { level = 4 },
    ["laser-weapons-damage-5"] = { level = 5 },
    ["laser-weapons-damage-6"] = { level = 6 },
    ["laser-weapons-damage-7"] = { level = "inf" },
    ["logistic-system"] = { level = 1 },
    ["logistic-system-2"] = { level = 2 },
    ["logistic-system-3"] = { level = 3 },
    ["manganese-ore-refining"] = { badge = "angels-manganese-ore", badge_type = "item" },
    ["mercury-processing-1"] = { level = 1 },
    ["mercury-processing-2"] = { level = 2 },
    ["mining-productivity-1"] = { level = 1 },
    ["mining-productivity-2"] = { level = 2 },
    ["mining-productivity-3"] = { level = 3 },
    ["mining-productivity-4"] = { level = "inf" },
    ["nano-range-1"] = { level = 1 },
    ["nano-range-2"] = { level = 2 },
    ["nano-range-3"] = { level = 3 },
    ["nano-range-4"] = { level = 4 },
    ["nano-speed-1"] = { level = 1 },
    ["nano-speed-2"] = { level = 2 },
    ["nano-speed-3"] = { level = 3 },
    ["nano-speed-4"] = { level = 4 },
    ["near-total-radiation-protection"] = { badge = "radiation-suit", badge_type = "item" },
    ["nuclear-fuel-1"] = { level = 1 },
    ["nuclear-fuel-2"] = { level = 2 },
    ["nuclear-fuel-3"] = { level = 3 },
    ["orbital-artillery-rangefinding-1"] = { level = 1 },
    ["orbital-artillery-rangefinding-26"] = { level = 2 },
    ["orbital-artillery-rangefinding-51"] = { level = "inf" },
    ["orbital-prospecting-1"] = { level = 1 },
    ["orbital-prospecting-51"] = { level = "inf" },
    ["phosphorus-processing-1"] = { level = 1 },
    ["phosphorus-processing-2"] = { level = 2 },
    ["physical-projectile-damage-1"] = { level = 1 },
    ["physical-projectile-damage-2"] = { level = 2 },
    ["physical-projectile-damage-3"] = { level = 3 },
    ["physical-projectile-damage-4"] = { level = 4 },
    ["physical-projectile-damage-5"] = { level = 5 },
    ["physical-projectile-damage-6"] = { level = 6 },
    ["physical-projectile-damage-7"] = { level = "inf" },
    ["plastic-abs"] = { badge = "liquid-acrylonitrile", badge_type = "fluid" },
    ["plastic-pc"] = { badge = "solid-pc", badge_type = "item" },
    ["plastic-pmma"] = { badge = "solid-pmma", badge_type = "item" },
    ["plastic-pvc"] = { badge = "gas-vinyl-chloride", badge_type = "fluid" },
    ["platinum-ore-refining"] = { badge = "angels-platinum-ore", badge_type = "item" },
    ["qol-crafting-speed-1-1"] = { level = 1, badge = "automation-science-pack", badge_type = "item" },
    ["qol-crafting-speed-1-2"] = { level = 2, badge = "automation-science-pack", badge_type = "item" },
    ["qol-crafting-speed-1-3"] = { level = 3, badge = "automation-science-pack", badge_type = "item" },
    ["qol-crafting-speed-1-4"] = { level = 4, badge = "automation-science-pack", badge_type = "item" },
    ["qol-crafting-speed-1-5"] = { level = 5, badge = "automation-science-pack", badge_type = "item" },
    ["qol-crafting-speed-2-1"] = { level = 1, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-crafting-speed-2-2"] = { level = 2, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-crafting-speed-2-3"] = { level = 3, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-crafting-speed-2-4"] = { level = 4, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-crafting-speed-2-5"] = { level = 5, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-crafting-speed-3-1"] = { level = 1, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-crafting-speed-3-2"] = { level = 2, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-crafting-speed-3-3"] = { level = 3, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-crafting-speed-3-4"] = { level = 4, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-crafting-speed-3-5"] = { level = 5, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-crafting-speed-4-1"] = { level = 1, badge = "production-science-pack", badge_type = "item" },
    ["qol-crafting-speed-4-2"] = { level = 2, badge = "production-science-pack", badge_type = "item" },
    ["qol-crafting-speed-4-3"] = { level = 3, badge = "production-science-pack", badge_type = "item" },
    ["qol-crafting-speed-4-4"] = { level = 4, badge = "production-science-pack", badge_type = "item" },
    ["qol-crafting-speed-4-5"] = { level = 5, badge = "production-science-pack", badge_type = "item" },
    ["qol-crafting-speed-5-1"] = { level = "inf", badge = "space-science-pack", badge_type = "item" },
    ["qol-inventory-size-1-1"] = { level = 1, badge = "automation-science-pack", badge_type = "item" },
    ["qol-inventory-size-1-2"] = { level = 2, badge = "automation-science-pack", badge_type = "item" },
    ["qol-inventory-size-2-1"] = { level = 1, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-inventory-size-2-2"] = { level = 2, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-inventory-size-3-1"] = { level = 1, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-inventory-size-3-2"] = { level = 2, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-inventory-size-3-3"] = { level = 3, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-inventory-size-3-4"] = { level = 4, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-inventory-size-4-1"] = { level = 1, badge = "utility-science-pack", badge_type = "item" },
    ["qol-inventory-size-4-2"] = { level = 2, badge = "utility-science-pack", badge_type = "item" },
    ["qol-inventory-size-4-3"] = { level = 3, badge = "utility-science-pack", badge_type = "item" },
    ["qol-inventory-size-4-4"] = { level = 4, badge = "utility-science-pack", badge_type = "item" },
    ["qol-inventory-size-5-1"] = { level = "inf", badge = "space-science-pack", badge_type = "item" },
    ["qol-mining-speed-1-1"] = { level = 1, badge = "automation-science-pack", badge_type = "item" },
    ["qol-mining-speed-1-2"] = { level = 2, badge = "automation-science-pack", badge_type = "item" },
    ["qol-mining-speed-1-3"] = { level = 3, badge = "automation-science-pack", badge_type = "item" },
    ["qol-mining-speed-1-4"] = { level = 4, badge = "automation-science-pack", badge_type = "item" },
    ["qol-mining-speed-1-5"] = { level = 5, badge = "automation-science-pack", badge_type = "item" },
    ["qol-mining-speed-2-1"] = { level = 1, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-mining-speed-2-2"] = { level = 2, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-mining-speed-2-3"] = { level = 3, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-mining-speed-2-4"] = { level = 4, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-mining-speed-2-5"] = { level = 5, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-mining-speed-3-1"] = { level = 1, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-mining-speed-3-2"] = { level = 2, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-mining-speed-3-3"] = { level = 3, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-mining-speed-3-4"] = { level = 4, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-mining-speed-3-5"] = { level = 5, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-mining-speed-4-1"] = { level = 1, badge = "production-science-pack", badge_type = "item" },
    ["qol-mining-speed-4-2"] = { level = 2, badge = "production-science-pack", badge_type = "item" },
    ["qol-mining-speed-4-3"] = { level = 3, badge = "production-science-pack", badge_type = "item" },
    ["qol-mining-speed-4-4"] = { level = 4, badge = "production-science-pack", badge_type = "item" },
    ["qol-mining-speed-4-5"] = { level = 5, badge = "production-science-pack", badge_type = "item" },
    ["qol-mining-speed-5-1"] = { level = "inf", badge = "space-science-pack", badge_type = "item" },
    ["qol-movement-speed-1-1"] = { level = 1, badge = "automation-science-pack", badge_type = "item" },
    ["qol-movement-speed-1-2"] = { level = 2, badge = "automation-science-pack", badge_type = "item" },
    ["qol-movement-speed-1-3"] = { level = 3, badge = "automation-science-pack", badge_type = "item" },
    ["qol-movement-speed-1-4"] = { level = 4, badge = "automation-science-pack", badge_type = "item" },
    ["qol-movement-speed-2-1"] = { level = 1, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-movement-speed-2-2"] = { level = 2, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-movement-speed-2-3"] = { level = 3, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-movement-speed-2-4"] = { level = 4, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-movement-speed-3-1"] = { level = 1, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-movement-speed-3-2"] = { level = 2, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-movement-speed-3-3"] = { level = 3, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-movement-speed-3-4"] = { level = 4, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-movement-speed-4-1"] = { level = 1, badge = "utility-science-pack", badge_type = "item" },
    ["qol-movement-speed-4-2"] = { level = 2, badge = "utility-science-pack", badge_type = "item" },
    ["qol-movement-speed-4-3"] = { level = 3, badge = "utility-science-pack", badge_type = "item" },
    ["qol-movement-speed-4-4"] = { level = 4, badge = "utility-science-pack", badge_type = "item" },
    ["qol-movement-speed-5-1"] = { level = "inf", badge = "space-science-pack", badge_type = "item" },
    ["qol-player-reach-1-1"] = { level = 1, badge = "automation-science-pack", badge_type = "item" },
    ["qol-player-reach-1-2"] = { level = 2, badge = "automation-science-pack", badge_type = "item" },
    ["qol-player-reach-1-3"] = { level = 3, badge = "automation-science-pack", badge_type = "item" },
    ["qol-player-reach-2-1"] = { level = 1, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-player-reach-2-2"] = { level = 2, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-player-reach-2-3"] = { level = 3, badge = "logistic-science-pack", badge_type = "item" },
    ["qol-player-reach-3-1"] = { level = 1, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-player-reach-3-2"] = { level = 2, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-player-reach-3-3"] = { level = 3, badge = "chemical-science-pack", badge_type = "item" },
    ["qol-player-reach-4-1"] = { level = 1, badge = "production-science-pack", badge_type = "item" },
    ["qol-player-reach-4-2"] = { level = 2, badge = "production-science-pack", badge_type = "item" },
    ["qol-player-reach-4-3"] = { level = 3, badge = "production-science-pack", badge_type = "item" },
    ["qol-player-reach-5-1"] = { level = "inf", badge = "space-science-pack", badge_type = "item" },
    ["radiothermal-fuel-1"] = { level = 1 },
    ["radiothermal-fuel-2"] = { level = 2 },
    ["radiothermal-fuel-3"] = { level = 3 },
    ["railway"] = { level = 1 },
    ["refined-flammables-1"] = { level = 1 },
    ["refined-flammables-2"] = { level = 2 },
    ["refined-flammables-3"] = { level = 3 },
    ["refined-flammables-4"] = { level = 4 },
    ["refined-flammables-5"] = { level = 5 },
    ["refined-flammables-6"] = { level = 6 },
    ["refined-flammables-7"] = { level = "inf" },
    ["remelting-alloy-mixer-1"] = { level = 1 },
    ["remelting-alloy-mixer-2"] = { level = 2 },
    ["remelting-alloy-mixer-3"] = { level = 3 },
    ["remelting-alloy-mixer-4"] = { level = 4 },
    ["research-speed-1"] = { level = 1 },
    ["research-speed-2"] = { level = 2 },
    ["research-speed-3"] = { level = 3 },
    ["research-speed-4"] = { level = 4 },
    ["research-speed-5"] = { level = 5 },
    ["research-speed-6"] = { level = 6 },
    ["research-speed-7"] = { level = 7 },
    ["research-speed-8"] = { level = "inf" },
    ["robot-global-positioning-system-1"] = { level = 1 },
    ["robot-global-positioning-system-11"] = { level = 2 },
    ["robot-global-positioning-system-21"] = { level = "inf" },
    ["rocket-failure-revision"] = { level = 1 },
    ["rocket-failure-revision-2"] = { level = 2 },
    ["rocket-failure-revision-3"] = { level = 3 },
    ["rocket-failure-revision-4"] = { level = 4 },
    ["rocket-failure-revision-5"] = { level = 5 },
    ["rocket-failure-revision-6"] = { level = 6 },
    ["rocket-failure-revision-7"] = { level = "inf" },
    ["rubber-processing"] = { badge = "solid-rubber-block", badge_type = "item" },
    ["space-telescope-research-1"] = { level = 1 },
    ["space-telescope-research-11"] = { level = 2 },
    ["space-telescope-research-21"] = { level = "inf" },
    ["stack-inserter-research-1"] = { level = 1 },
    ["stack-inserter-research-10"] = { level = 3 },
    ["stack-inserter-research-15"] = { level = "inf" },
    ["stack-inserter-research-5"] = { level = 2 },
    ["steel-axe"] = { level = 1 },
    ["steel-gates"] = { badge = "steel-plate", badge_type = "item" },
    ["steel-walls"] = { badge = "steel-plate", badge_type = "item" },
    ["stronger-explosives-1"] = { level = 1 },
    ["stronger-explosives-2"] = { level = 2 },
    ["stronger-explosives-3"] = { level = 3 },
    ["stronger-explosives-4"] = { level = 4 },
    ["stronger-explosives-5"] = { level = 5 },
    ["stronger-explosives-6"] = { level = 6 },
    ["stronger-explosives-7"] = { level = "inf" },
    ["subterranean-logistics-1"] = { level = 1 },
    ["subterranean-logistics-2"] = { level = 2 },
    ["subterranean-logistics-3"] = { level = 3 },
    ["toolbelt"] = { level = 1 },
    ["toolbelt-2"] = { level = 2 },
    ["toolbelt-3"] = { level = 3 },
    ["toolbelt-4"] = { level = 4 },
    ["toolbelt-5"] = { level = 5 },
    ["toolbelt-6"] = { level = 6 },
    ["weapon-shooting-speed-1"] = { level = 1 },
    ["weapon-shooting-speed-2"] = { level = 2 },
    ["weapon-shooting-speed-3"] = { level = 3 },
    ["weapon-shooting-speed-4"] = { level = 4 },
    ["weapon-shooting-speed-5"] = { level = 5 },
    ["weapon-shooting-speed-6"] = { level = 6 },
    ["worker-robots-battery-1"] = { level = 1 },
    ["worker-robots-battery-2"] = { level = 2 },
    ["worker-robots-battery-3"] = { level = 3 },
    ["worker-robots-battery-4"] = { level = 4 },
    ["worker-robots-battery-5"] = { level = 5 },
    ["worker-robots-battery-6"] = { level = 6 },
    ["worker-robots-battery-7"] = { level = 7 },
    ["worker-robots-battery-8"] = { level = "inf" },
    ["worker-robots-speed-1"] = { level = 1 },
    ["worker-robots-speed-2"] = { level = 2 },
    ["worker-robots-speed-3"] = { level = 3 },
    ["worker-robots-speed-4"] = { level = 4 },
    ["worker-robots-speed-5"] = { level = 5 },
    ["worker-robots-speed-6"] = { level = "inf" },
    ["worker-robots-storage-1"] = { level = 1 },
    ["worker-robots-storage-2"] = { level = 2 },
    ["worker-robots-storage-3"] = { level = 3 },
    ["worker-robots-storage-4"] = { level = 4 },
    ["worker-robots-storage-5"] = { level = 5 },
    ["worker-robots-storage-6"] = { level = 6 },
    ["worker-robots-storage-7"] = { level = 7 },
    ["worker-robots-storage-8"] = { level = "inf" },
}
