------------------------------------------------------------------------
-- Represents a single, open gui, loosely inspired by flib
------------------------------------------------------------------------
assert(script)

local Is = require('stdlib.utils.is')
local table = require('stdlib.utils.table')

require('stdlib.utils.string')

------------------------------------------------------------------------
-- types
------------------------------------------------------------------------


---@alias framework.gui.element_definitions framework.gui.element_definition|framework.gui.element_definition[]

---@class framework.gui.element_extras
---@field children framework.gui.element_definition[]? Children to add to this element.
---@field elem_mods table<string, any>? Post-creation modifications to the element itself.
---@field style_mods table<string, any>? Post-creation modifications to the element's style.
---@field elem_tags table<string, any>? Post-creation modifications to the element tags.
---@field handler table<defines.events, string>? Handlers to assign to this element.
---@field drag_target string? Set the element's drag target to the element whose name matches this string. The drag target must be present in the UI component tree before assigning it.

--- A GUI element definition. This extends `LuaGuiElement.add_param` with several new attributes.
---@class framework.gui.element_definition: LuaGuiElement.add_param.base
---@field style_mods table<string, any>? Post-creation modifications to make to the element's style.
---@field elem_mods table<string, any>? Post-creation modifications to make to the element itself.
---@field drag_target string? Set the element's drag target to the element whose name matches this string. The drag target must be present in the UI component tree before assigning it.
---@field handler table<defines.events, string>? Handlers to assign to this element.
---@field children framework.gui.element_definition[]? Children to add to this element.
---@field tab framework.gui.element_definition? To add a tab, specify `tab` and `content` and leave all other fields unset.
---@field content framework.gui.element_definition? To add a tab, specify `tab` and `content` and leave all other fields unset.

---@class framework.gui.create
---@field type string GUI type
---@field prefix string
---@field gui_events framework.gui_events All known events for this GUI.
---@field context framework.gui.context? Context element
---@field entity_id number? The entity for which a gui is created
---@field player_index number

---@class framework.gui
---@field type string The GUI type for dispatching events.
---@field prefix string The internal prefix for all names.
---@field gui_events framework.gui_events All known events for this GUI.
---@field count number A running count for autogenerated names.
---@field ui_elements table<string, LuaGuiElement> All known elements in the UI.
---@field root LuaGuiElement? Root element of the tree.
---@field event_handlers table<defines.events, table<string, string>> -- map from the event to the handler name. The handler can not be stored here because it is not serializable
---@field entity_id number? The entity for which the Gui has been opened
---@field player_index number
---@field context framework.gui.context
local FrameworkGui = {
    count = 0,
}

local FrameworkGui_MT = {
    __index = FrameworkGui
}

local event_handler_template = {
}

-- predefine arrays for all supported events
for name, id in pairs(defines.events) do
    if name:starts_with('on_gui_') then
        event_handler_template[id] = {}
    end
end

------------------------------------------------------------------------
-- helper methods
------------------------------------------------------------------------

---@return string gui_name
function FrameworkGui:generate_name()
    self.count = self.count + 1
    return tostring(self.count)
end

--- Adds the internal prefix to the given name unless it is already prefixed.
---@param name string
---@return string prefixed name
function FrameworkGui:generate_gui_name(name)
    if name.sub(1, #self.prefix) == self.prefix then
        return name
    else
        return self.prefix .. name
    end
end

--- Registers all defined handlers after a LuaGuiElement has been created.
---@param gui_element LuaGuiElement
---@param extras framework.gui.element_extras
function FrameworkGui:register_handlers(gui_element, extras)
    if not extras.handler then return end

    local handlers = extras.handler
    local handler_name = gui_element.name

    for event, handler in pairs(handlers) do
        local event_handlers = self.event_handlers[event]
        assert(event_handlers, 'Handler for event ' .. tostring(event) .. ' is not supported!')
        assert(not event_handlers[handler_name], 'Already registered a handler for ' .. handler_name)
        event_handlers[handler_name] = handler
    end
end

------------------------------------------------------------------------

local extra_fields = {
    'children',    -- gui elements attached as children to this element
    'elem_mods',   -- set of attributes that should be set on the created LuaGuiElement
    'style_mods',  -- set of attributes that should be set on the LuaStyle field of the LuaGuiElement
    'elem_tags',   -- add an extra tag to the gui element
    'handler',     -- event handlers for this element
    'drag_target', -- drag target reference (must be another Gui element) when dragging an element
}

--- Creates a new LuaGuiElement from a Framework element definition. Any defined children will recursively created and attached.
---@param parent LuaGuiElement The parent element that this child will be attached to.
---@param child framework.gui.element_definition A gui element definition. May have additional children.
---@return LuaGuiElement gui_element The new gui element
function FrameworkGui:create_child_element(parent, child)
    ---@type framework.gui.element_extras
    local extras = {}

    for _, key in pairs(extra_fields) do
        extras[key] = child[key]
        child[key] = nil
    end

    child.name = self:generate_gui_name(child.name or self:generate_name())
    assert(not self.ui_elements[child.name], "A UI element named '" .. child.name .. "' was already defined!")

    local gui_element = parent.add(child)

    -- register with the framework.gui object
    self.ui_elements[child.name] = gui_element

    -- add tag for event dispatching
    local tags = gui_element.tags

    if extras.elem_tags then
        for key, value in pairs(extras.elem_tags) do
            tags[key] = value
        end
    end

    gui_element.tags = tags

    -- process additional attributes

    if extras.style_mods then
        for key, value in pairs(extras.style_mods) do
            gui_element.style[key] = value
        end
    end

    if extras.elem_mods then
        for key, value in pairs(extras.elem_mods) do
            gui_element[key] = value
        end
    end

    if extras.drag_target then
        local drag_name = self:generate_gui_name(extras.drag_target)
        local target = self.ui_elements[drag_name]
        assert(target, "Drag target '" .. extras.drag_target .. "' not found.")

        gui_element.drag_target = target
    end

    if extras.handler then
        self:register_handlers(gui_element, extras)
    end

    if extras.children then
        self:add_child_elements(gui_element, extras.children)
    end

    return gui_element
end

--- Adds a child in a new tab to an existing tab group.
---@param parent LuaGuiElement
---@param child framework.gui.element_definition The elements that are added to the tab.
---@return LuaGuiElement gui_element The content of the tab.
function FrameworkGui:add_tab(parent, child)
    local tab = self:create_child_element(parent, child.tab)
    local gui_element = self:create_child_element(parent, child.content)
    parent.add_tab(tab, gui_element)

    return gui_element
end

------------------------------------------------------------------------

--- Add a new child or children to the given GUI element.
---@param parent LuaGuiElement
---@param children framework.gui.element_definitions The element definition, or an array of element definitions.
---@param existing_elements table<string, LuaGuiElement>? Optional set of existing GUI elements.
function FrameworkGui:add_child_elements(parent, children, existing_elements)
    assert(Is.Valid(parent), 'Parent element is missing or invalid')
    assert(children, 'new_elements can not be empty')

    if existing_elements then
        -- validate and move existing elements into the internal ui_elements array
        for _, element in pairs(existing_elements) do
            assert(Is.Valid(element))
            assert(element.name, 'Can not add an external element without name: ' .. serpent.line(element))
            local gui_name = self:generate_gui_name(element.name)

            assert(not self.ui_elements[gui_name], "A UI element named '" .. gui_name .. "' was already defined!")
            self.ui_elements[gui_name] = element
        end
    end

    -- If a single def was passed, wrap it in an array
    children = #children > 0 and children or { children } --[[@as table<string, framework.gui.element_definition>]]

    local root
    for _, child in pairs(children) do
        assert(not child[1], 'children as arrays are not supported, use the children attribute!')

        local gui_element
        if child.type then
            gui_element = self:create_child_element(parent, child)
        elseif child.tab and child.content then
            gui_element = self:add_tab(parent, child)
        else
            error('Invalid element: ' .. serpent.line(child))
        end
        root = root or gui_element
    end

    return root
end

------------------------------------------------------------------------

--- Creates a new framework.gui instance and registers it with the manager.
---@param map framework.gui.create parameters
---@return framework.gui gui A FrameworkGui instance that can be used for creating a Gui.
function FrameworkGui.create(map)
    local gui = {
        -- elements
        count = 1,
        type = map.type,
        prefix = map.prefix,
        gui_events = map.gui_events,
        entity_id = map.entity_id,
        player_index = map.player_index,
        context = map.context,
        ui_elements = {},
        root = nil,
        event_handlers = util.copy(event_handler_template),
    }

    setmetatable(gui, FrameworkGui_MT)
    return gui
end

--- Finds a registered element in this Gui by name.
---@param name string
---@return LuaGuiElement? gui_element A registered gui element or nil.
function FrameworkGui:find_element(name)
    local ui_name = self:generate_gui_name(name)
    return self.ui_elements[ui_name]
end

------------------------------------------------------------------------

--- Removes all children from an UI element
---@param name string The name of the UI element
---@return LuaGuiElement? ui_element The GUI element without children or nil.
function FrameworkGui:remove_children(name)
    local ui_element = self:find_element(name)

    if ui_element then
        local child_names = util.copy(ui_element.children_names)
        ui_element.clear()
        table.remove_keys(self.ui_elements, child_names)
    end

    return ui_element
end

--- Replace the children of an UI element with a new set of children.
---@param name string The name of the UI element.
---@param children framework.gui.element_definitions
---@return LuaGuiElement? ui_element The GUI element with new children or nil.
function FrameworkGui:replace_children(name, children)
    local parent = self:remove_children(name)
    if parent then
        self:add_child_elements(parent, children)
    end

    return parent
end

script.register_metatable('framework_gui', FrameworkGui_MT)

return FrameworkGui
