return
{
  entities =
  {
    {"tree-05", {x = 5.5, y = -6.5}, {}},
    {"tree-05", {x = -5.5, y = -4.5}, {}},
    {"stone-wall", {x = -5.5, y = -5.5}, {}},
    {"stone-wall", {x = -4.5, y = -5.5}, {}},
    {"stone-wall", {x = -3.5, y = -5.5}, {}},
    {"stone-wall", {x = -0.5, y = -5.5}, {}},
    {"stone-wall", {x = -1.5, y = -5.5}, {}},
    {"gate", {x = 0.5, y = -5.5}, {dir = "east", }},
    {"gate", {x = 1.5, y = -5.5}, {dir = "east", }},
    {"stone-wall", {x = 3.5, y = -5.5}, {}},
    {"stone-wall", {x = 2.5, y = -5.5}, {}},
    {"stone-wall", {x = 4.5, y = -5.5}, {}},
    {"stone-wall", {x = 6.5, y = -4.5}, {}},
    {"stone-wall", {x = -5.5, y = -2.5}, {}},
    {"stone-wall", {x = -3.5, y = -3.5}, {}},
    {"stone-wall", {x = -2.5, y = -3.5}, {}},
    {"tree-05", {x = -0.5, y = -3.5}, {}},
    {"stone-wall", {x = 2.5, y = -3.5}, {}},
    {"stone-wall", {x = 3.5, y = -3.5}, {}},
    {"stone-wall", {x = 4.5, y = -2.5}, {}},
    {"stone-wall", {x = 4.5, y = -3.5}, {}},
    {"stone-wall", {x = 6.5, y = -2.5}, {}},
    {"stone-wall", {x = -5.5, y = -0.5}, {}},
    {"stone-wall", {x = -5.5, y = -1.5}, {}},
    {"stone-wall", {x = -4.5, y = -1.5}, {}},
    {"stone-wall", {x = -1.5, y = -1.5}, {}},
    {"stone-wall", {x = 1.5, y = -0.5}, {}},
    {"wooden-chest", {x = 0.5, y = -0.5}, {items = {["copper-plate"] = {type= "random", min = 10, max = 200}, ["iron-plate"] = {type= "random", min = 10, max = 200}}, }},
    {"tree-05", {x = 2.5, y = -0.5}, {}},
    {"tree-05", {x = 4.5, y = -1.5}, {}},
    {"gate", {x = 6.5, y = -0.5}, {}},
    {"stone-wall", {x = 6.5, y = -1.5}, {}},
    {"gate", {x = -5.5, y = 1.5}, {}},
    {"gate", {x = -5.5, y = 0.5}, {}},
    {"tree-05", {x = -1.5, y = 1.5}, {}},
    {"stone-wall", {x = -0.5, y = 0.5}, {}},
    {"stone-wall", {x = 0.5, y = 1.5}, {}},
    {"gun-turret", {x = 2, y = 2}, {dir = "east", force = "enemy", items = {["firearm-magazine"] = 5}, }},
    {"stone-wall", {x = 1.5, y = 0.5}, {}},
    {"stone-wall", {x = 0.5, y = 0.5}, {}},
    {"stone-wall", {x = 6.5, y = 1.5}, {}},
    {"gate", {x = 6.5, y = 0.5}, {}},
    {"stone-wall", {x = -5.5, y = 3.5}, {}},
    {"stone-wall", {x = -5.5, y = 2.5}, {}},
    {"tree-05", {x = -4.5, y = 2.5}, {}},
    {"stone-wall", {x = 0.5, y = 2.5}, {}},
    {"stone-wall", {x = 2.5, y = 3.5}, {}},
    {"tree-05", {x = 4.5, y = 2.5}, {}},
    {"stone-wall", {x = 6.5, y = 3.5}, {}},
    {"stone-wall", {x = 6.5, y = 2.5}, {}},
    {"stone-wall", {x = -5.5, y = 5.5}, {}},
    {"stone-wall", {x = -5.5, y = 4.5}, {}},
    {"tree-05", {x = -0.5, y = 4.5}, {}},
    {"stone-wall", {x = 2.5, y = 5.5}, {}},
    {"stone-wall", {x = 6.5, y = 5.5}, {}},
    {"stone-wall", {x = -4.5, y = 6.5}, {}},
    {"stone-wall", {x = -3.5, y = 6.5}, {}},
    {"stone-wall", {x = -2.5, y = 6.5}, {}},
    {"gate", {x = -1.5, y = 6.5}, {dir = "east", }},
    {"stone-wall", {x = 0.5, y = 6.5}, {}},
    {"stone-wall", {x = 1.5, y = 6.5}, {}},
    {"stone-wall", {x = 2.5, y = 6.5}, {}},
    {"stone-wall", {x = 3.5, y = 6.5}, {}},
    {"stone-wall", {x = 5.5, y = 6.5}, {}},
    {"stone-wall", {x = 6.5, y = 6.5}, {}},
  },
}
