return
{
  entities =
  {
    {"small-electric-pole", {x = 3.5, y = -5.5}, {}},
    {"small-electric-pole", {x = -4.5, y = -2.5}, {}},
    {"small-electric-pole", {x = -0.5, y = -2.5}, {}},
    {"steam-engine", {x = -3.5, y = 0.5}, {}},
    {"steam-engine", {x = -0.5, y = 0.5}, {}},
    {"steam-engine", {x = 2.5, y = 0.5}, {}},
    {"steam-engine-remnants", {x = 5.5, y = 0.5}, {}},
    {"small-electric-pole-remnants", {x = 7.5, y = 0.5}, {}},
    {"small-electric-pole", {x = -6.5, y = 2.5}, {}},
    {"boiler", {x = -3.5, y = 4}, {}},
    {"boiler", {x = 2.5, y = 4}, {}},
    {"burner-inserter", {x = -3.5, y = 5.5}, {dir = "south", }},
    {"boiler-remnants", {x = -0.5, y = 4}, {}},
    {"burner-inserter", {x = -0.5, y = 5.5}, {dir = "south", }},
    {"burner-inserter", {x = 2.5, y = 5.5}, {dir = "south", }},
    {"boiler-remnants", {x = 5.5, y = 4}, {}},
    {"burner-inserter-remnants", {x = 6.5, y = 5.5}, {dir = "south", }},
    {"transport-belt-remnants", {x = -6.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = -7.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = -5.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = -4.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = -2.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = -3.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = -1.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = -0.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = 1.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = 0.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 3.5, y = 6.5}, {dir = "east", }},
    {"transport-belt", {x = 2.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 4.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 5.5, y = 6.5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 6.5, y = 6.5}, {dir = "east", }},
  }
}
