require("__hardcore-mode-for-playing__.prototypes.resource-detected-technology-creating.main")
require("link-basic-technologies-to-regular-tree")
require("__hardcore-mode-for-playing__.prototypes.fuel-category.fuel-category-prototype-updates")
require("__hardcore-mode-for-playing__.prototypes.steam-processing.main")
require("__hardcore-mode-for-playing__.prototypes.burner-prototypes.main")
require(
	"__make-moded-technology-tree-mods-protocol__.prototypes.copying-for-modes.copy-to-normal-expensive-mode-recipe-data"
)
require("recipe-final-fixes-after-technology-linking.main")
