require("prototypes/entity/entity-update")
require("prototypes/item/item-update")
require("prototypes/recipe/recipe-update")
require("prototypes/technology/technology-update")
--log( serpent.block( data.raw["recipe"], {comment = false, numformat = '%1.8g' } ) )
