return
{
  entities =
  {
    {"bi-wooden-fence", {x = -5, y = -4}, {}},
    {"bi-wooden-fence", {x = -4, y = -4}, {}},
    {"bi-wooden-fence", {x = -3, y = -3}, {}},
    {"bi-wooden-fence", {x = -3, y = -4}, {}},
    {"small-lamp", {x = -2, y = -3}, {}},
    {"bi-wooden-fence", {x = -1, y = -4}, {}},
    {"bi-wooden-fence", {x = -2, y = -4}, {}},
    {"bi-wooden-fence", {x = 1, y = -4}, {}},
    {"bi-wooden-fence", {x = 0, y = -4}, {}},
    {"burner-turbine", {x = 1.5, y = -1.5}, {dmg = {dmg = 149}, }},
    {"bi-wooden-fence", {x = 2, y = -4}, {}},
    {"plaswall", {x = 4, y = -3}, {}},
    {"bi-wooden-fence", {x = -3, y = -2}, {}},
    {"lighted-small-electric-pole", {x = -2, y = -1}, {}},
    {"plaswall", {x = 4, y = -1}, {}},
    {"plaswall", {x = 4, y = -2}, {}},
    {"wooden-chest", {x = -1, y = 1}, {items = {["pollution-clean-module-2"] = 1}, }},
    {"burner-inserter", {x = 2, y = 1}, {dir = "south", }},
    {"plaswall", {x = 5, y = 1}, {}},
    {"plaswall", {x = 4, y = 1}, {}},
    {"plaswall", {x = 4, y = 0}, {}},
    {"bi-wooden-fence", {x = -3, y = 3}, {}},
    {"bi-wooden-fence", {x = 3, y = 3}, {}},
    {"wooden-chest", {x = 2, y = 2}, {dmg = {dmg = 24}, items = {coal = 166}, }},
    {"plaswall", {x = 5, y = 3}, {}},
    {"plaswall", {x = 4, y = 3}, {}},
    {"bi-wooden-fence", {x = -3, y = 5}, {}},
    {"bi-wooden-fence", {x = -3, y = 4}, {}},
    {"bi-wooden-fence", {x = -1, y = 5}, {}},
    {"bi-wooden-fence", {x = -2, y = 5}, {}},
    {"bi-wooden-fence", {x = 0, y = 5}, {}},
    {"bi-wooden-fence", {x = 3, y = 5}, {}},
    {"bi-wooden-fence", {x = 3, y = 4}, {}},
    {"bi-wooden-fence", {x = 2, y = 5}, {}},
    {"plaswall", {x = 4, y = 5}, {}},
    {"plaswall", {x = 4, y = 4}, {}},
    {"bi-wooden-fence", {x = 2, y = 6}, {}},
  },
}
