return
{
  entities =
  {
    {"entity-ghost", {x = -5.5, y = -7.5}, {}},
    {"plaswall", {x = -5.5, y = -8.5}, {}},
    {"plaswall", {x = -4.5, y = -8.5}, {}},
    {"plaswall", {x = -3.5, y = -8.5}, {}},
    {"plaswall", {x = -2.5, y = -8.5}, {dmg = {dmg = 432}, }},
    {"entity-ghost", {x = -0.5, y = -8.5}, {}},
    {"plaswall", {x = -1.5, y = -8.5}, {dmg = {dmg = 648}, }},
    {"entity-ghost", {x = 0.5, y = -8.5}, {}},
    {"plaswall", {x = 1.5, y = -8.5}, {dmg = {dmg = 432}, }},
    {"plaswall", {x = 2.5, y = -8.5}, {dmg = {dmg = 216}, }},
    {"plaswall", {x = 3.5, y = -8.5}, {}},
    {"plaswall", {x = 4.5, y = -8.5}, {}},
    {"entity-ghost", {x = -5.5, y = -5.5}, {}},
    {"plaswall", {x = -5.5, y = -6.5}, {dmg = {dmg = 282}, }},
    {"gun-turret", {x = -3, y = -6}, {force = "enemy", items = {["firearm-magazine"] = 53}, }},
    {"plaswall", {x = -5.5, y = -4.5}, {dmg = {dmg = 26}, }},
    {"plaswall", {x = -5.5, y = -3.5}, {dmg = {dmg = 66}, }},
    {"yellow-filter-inserter", {x = -1.5, y = -3.5}, {dir = "south", }},
    {"yellow-filter-inserter", {x = -0.5, y = -3.5}, {dir = "south", }},
    {"yellow-filter-inserter", {x = 0.5, y = -3.5}, {dir = "south", }},
    {"yellow-filter-inserter", {x = 1.5, y = -3.5}, {dir = "south", }},
    {"plaswall", {x = -5.5, y = -1.5}, {dmg = {dmg = 448}, }},
    {"plaswall", {x = -5.5, y = -2.5}, {dmg = {dmg = 66}, }},
    {"ore-sorting-facility", {x = 0.5, y = 0.5}, {}},
    {"entity-ghost", {x = -5.5, y = 0.5}, {}},
    {"plaswall", {x = -5.5, y = -0.5}, {dmg = {dmg = 52}, }},
    {"plaswall", {x = -5.5, y = 2.5}, {dmg = {dmg = 26}, }},
    {"plaswall", {x = -5.5, y = 1.5}, {dmg = {dmg = 229}, }},
    {"entity-ghost", {x = -5.5, y = 4.5}, {}},
    {"plaswall", {x = -5.5, y = 3.5}, {dmg = {dmg = 242}, }},
    {"plaswall", {x = -5.5, y = 6.5}, {}},
    {"plaswall", {x = -5.5, y = 5.5}, {dmg = {dmg = 216}, }},
    {"entity-ghost", {x = -5.5, y = 7.5}, {}},
    {"plaswall", {x = -5.5, y = 8.5}, {}},
    {"gun-turret", {x = -2, y = 8}, {force = "enemy", items = {["firearm-magazine"] = 54}, }},
    {"plaswall", {x = -4.5, y = 9.5}, {}},
    {"plaswall", {x = -5.5, y = 9.5}, {}},
    {"entity-ghost", {x = -3.5, y = 9.5}, {}},
    {"plaswall", {x = -2.5, y = 9.5}, {}},
    {"plaswall", {x = -1.5, y = 9.5}, {}},
    {"plaswall", {x = -0.5, y = 9.5}, {}},
    {"entity-ghost", {x = 0.5, y = 9.5}, {}},
    {"plaswall", {x = 1.5, y = 9.5}, {}},
    {"plaswall", {x = 3.5, y = 9.5}, {}},
    {"plaswall", {x = 2.5, y = 9.5}, {}},
    {"plaswall", {x = 5.5, y = 9.5}, {}},
    {"plaswall", {x = 4.5, y = 9.5}, {}},
  },
}
