return
{
  entities =
  {
    {"bob-gun-turret-5", {x = -4, y = -3}, {force = "enemy", dir = "south", items = {["firearm-magazine"] = 600}, }},
    {"bob-gun-turret-5", {x = 2, y = -3}, {force = "enemy", dir = "east", items = {["firearm-magazine"] = 600}, }},
    {"reinforced-wall", {x = 4.5, y = -3.5}, {}},
    {"reinforced-wall", {x = 3.5, y = -3.5}, {}},
    {"reinforced-wall", {x = 3.5, y = -2.5}, {}},
    {"reinforced-wall", {x = 4.5, y = -1.5}, {}},
    {"reinforced-wall", {x = 4.5, y = -2.5}, {}},
    {"bi-wooden-chest-large", {x = -4, y = 0}, {items = {["diamond-5"] = 5, ["modular-armor"] = 1, ["productivity-module-4"] = 1, ["superradiothermal-fuel"] = 2, ["utility-science-pack"] = 20}, }},
    {"reinforced-wall", {x = 0.5, y = 0.5}, {}},
    {"reinforced-wall", {x = 0.5, y = -0.5}, {}},
    {"bi-wooden-chest-large", {x = 2, y = 0}, {items = {["bob-construction-robot-5"] = 2, ["express-miniloader"] = 1, ["gold-plate"] = 19, ["ground-water-pump"] = 1, ["laser-turret"] = 1}, }},
    {"reinforced-gate", {x = 4.5, y = 0.5}, {}},
    {"reinforced-gate", {x = 4.5, y = -0.5}, {}},
    {"bob-gun-turret-5", {x = -4, y = 3}, {force = "enemy", dir = "south", items = {["firearm-magazine"] = 600}, }},
    {"bob-gun-turret-5", {x = 2, y = 3}, {force = "enemy", dir = "east", items = {["firearm-magazine"] = 600}, }},
    {"reinforced-wall", {x = 3.5, y = 2.5}, {}},
    {"reinforced-wall", {x = 4.5, y = 2.5}, {}},
    {"reinforced-wall", {x = 4.5, y = 1.5}, {}},
    {"reinforced-wall", {x = 4.5, y = 3.5}, {}},
    {"reinforced-wall", {x = 3.5, y = 3.5}, {}},
  },
  tiles =
  {
    {"hazard-concrete-right", {x = 0, y = -3}},
    {"hazard-concrete-right", {x = 0, y = -2}},
    {"hazard-concrete-right", {x = 1, y = -3}},
    {"hazard-concrete-right", {x = 1, y = -2}},
    {"hazard-concrete-right", {x = 1, y = -1}},
    {"hazard-concrete-right", {x = 1, y = 0}},
    {"hazard-concrete-right", {x = 1, y = 1}},
    {"hazard-concrete-right", {x = 1, y = 2}},
    {"hazard-concrete-right", {x = 2, y = -3}},
    {"hazard-concrete-right", {x = 2, y = -2}},
    {"hazard-concrete-right", {x = 2, y = -1}},
    {"hazard-concrete-right", {x = 2, y = 0}},
    {"hazard-concrete-right", {x = 2, y = 1}},
    {"hazard-concrete-right", {x = 2, y = 2}},
    {"hazard-concrete-right", {x = 3, y = -3}},
    {"hazard-concrete-right", {x = 3, y = -2}},
    {"hazard-concrete-right", {x = 3, y = -1}},
    {"hazard-concrete-right", {x = 3, y = 0}},
    {"hazard-concrete-right", {x = 3, y = 1}},
    {"hazard-concrete-right", {x = 3, y = 2}},
  }
}
