require("prototypes.shortcuts-basic")
require("prototypes.shortcuts-blueprint")
require("prototypes.shortcuts-equipment")
require("prototypes.shortcuts-artillery")
require("prototypes.shortcuts-vehicle")
