MOD_NAME = "automated-train-transport-protocol"
ATTP_1_TECHNOLOGY_NAME = "automated-train-transport-protocol-t1"
ATTP_2_TECHNOLOGY_NAME = "automated-train-transport-protocol-t2"
ATTP_3_TECHNOLOGY_NAME = "automated-train-transport-protocol-t3"
ATTP_4_TECHNOLOGY_NAME = "automated-train-transport-protocol-t4"
