return
{
  entities =
  {
    {"wall-remnants", {x = -2.5, y = -3.5}, {}},
    {"wall-remnants", {x = -3.5, y = -3.5}, {}},
    {"wall-remnants", {x = -3.5, y = -2.5}, {}},
    {"wall-remnants", {x = -0.5, y = -3.5}, {}},
    {"wall-remnants", {x = -1.5, y = -3.5}, {}},
    {"stone-wall", {x = 1.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 150}}}},
    {"stone-wall", {x = 0.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 150}}}},
    {"stone-wall", {x = 3.5, y = -2.5}, {dmg = {dmg = {type = "random", min = 0, max = 150}}}},
    {"stone-wall", {x = 3.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 150}}}},
    {"stone-wall", {x = 2.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 150}}}},
    {"iron-chest", {x = -2.5, y = -0.5}, {items = {["artillery-shell"] = {type = "random", min = 1, max = 4}}}},
    {"wall-remnants", {x = -3.5, y = -1.5}, {}},
    {"wall-remnants", {x = -3.5, y = -0.5}, {}},
    {"fast-inserter", {x = -1.5, y = -0.5}, {dir = "west", dead = 0.6}},
    {"artillery-turret", {x = 0.5, y = -1.5}, {dir = "east", }},
    {"gate", {x = 3.5, y = -0.5}, {}},
    {"stone-wall", {x = 3.5, y = -1.5}, {}},
    {"iron-chest", {x = -2.5, y = 0.5}, {items = {["artillery-shell"] = {type = "random", min = 1, max = 4}}}},
    {"wall-remnants", {x = -3.5, y = 0.5}, {}},
    {"wall-remnants", {x = -3.5, y = 1.5}, {}},
    {"medium-electric-pole-remnants", {x = -1.5, y = 1.5}, {}},
    {"fast-inserter", {x = -1.5, y = 0.5}, {dir = "west", dead = 0.6}},
    {"artillery-turret-remnants", {x = 0.5, y = 1.5}, {dir = "south", }},
    {"gate", {x = 3.5, y = 0.5}, {}},
    {"stone-wall", {x = 3.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 150}}}},
    {"wall-remnants", {x = -2.5, y = 3.5}, {}},
    {"wall-remnants", {x = -3.5, y = 2.5}, {}},
    {"wall-remnants", {x = -3.5, y = 3.5}, {}},
    {"wall-remnants", {x = -0.5, y = 3.5}, {}},
    {"wall-remnants", {x = -1.5, y = 3.5}, {}},
    {"wall-remnants", {x = 1.5, y = 3.5}, {}},
    {"wall-remnants", {x = 0.5, y = 3.5}, {}},
    {"stone-wall", {x = 3.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 150}}}},
    {"wall-remnants", {x = 3.5, y = 3.5}, {}},
    {"wall-remnants", {x = 2.5, y = 3.5}, {}},
  },
}
