-- Beta 8 normal: строительство биологических установок; свойства/категории 2.0 неизменны.
if not mods["angelsbioprocessing"] then return end
local ingredients = {
	["angels-bio-butchery-2"] = { { ["type"] = "item", ["name"] = "angels-bio-butchery", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-aluminium-plate", ["amount"] = 12 }, { ["type"] = "item", ["name"] = "advanced-circuit", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "concrete", ["amount"] = 10 }, { ["type"] = "item", ["name"] = "bob-brass-gear-wheel", ["amount"] = 6 } },
	["angels-bio-butchery-3"] = { { ["type"] = "item", ["name"] = "angels-bio-butchery-2", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-titanium-plate", ["amount"] = 12 }, { ["type"] = "item", ["name"] = "processing-unit", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 10 }, { ["type"] = "item", ["name"] = "bob-titanium-gear-wheel", ["amount"] = 6 } },
	["angels-bio-hatchery"] = { { ["type"] = "item", ["name"] = "small-lamp", ["amount"] = 3 }, { ["type"] = "item", ["name"] = "bob-aluminium-plate", ["amount"] = 8 }, { ["type"] = "item", ["name"] = "advanced-circuit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "concrete", ["amount"] = 10 } },
	["angels-bio-hatchery-2"] = { { ["type"] = "item", ["name"] = "angels-bio-hatchery", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-titanium-plate", ["amount"] = 8 }, { ["type"] = "item", ["name"] = "processing-unit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 10 } },
	["angels-bio-hatchery-3"] = { { ["type"] = "item", ["name"] = "angels-bio-hatchery-2", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "tungsten-plate", ["amount"] = 8 }, { ["type"] = "item", ["name"] = "bob-advanced-processing-unit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 10 } },
	["angels-bio-press-2"] = { { ["type"] = "item", ["name"] = "angels-bio-press", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-aluminium-plate", ["amount"] = 8 }, { ["type"] = "item", ["name"] = "advanced-circuit", ["amount"] = 2 }, { ["type"] = "item", ["name"] = "concrete", ["amount"] = 5 }, { ["type"] = "item", ["name"] = "bob-brass-pipe", ["amount"] = 3 }, { ["type"] = "item", ["name"] = "bob-brass-gear-wheel", ["amount"] = 6 } },
	["angels-bio-press-3"] = { { ["type"] = "item", ["name"] = "angels-bio-press-2", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-titanium-plate", ["amount"] = 8 }, { ["type"] = "item", ["name"] = "processing-unit", ["amount"] = 2 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 5 }, { ["type"] = "item", ["name"] = "bob-titanium-pipe", ["amount"] = 3 }, { ["type"] = "item", ["name"] = "bob-titanium-gear-wheel", ["amount"] = 6 } },
	["angels-bio-refugium-biter"] = { { ["type"] = "item", ["name"] = "stone-wall", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "bob-titanium-plate", ["amount"] = 40 }, { ["type"] = "item", ["name"] = "processing-unit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 95 }, { ["type"] = "item", ["name"] = "bob-titanium-pipe", ["amount"] = 33 } },
	["angels-bio-refugium-biter-2"] = { { ["type"] = "item", ["name"] = "angels-bio-refugium-biter", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "tungsten-plate", ["amount"] = 40 }, { ["type"] = "item", ["name"] = "bob-advanced-processing-unit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 95 }, { ["type"] = "item", ["name"] = "bob-tungsten-pipe", ["amount"] = 33 } },
	["angels-bio-refugium-biter-3"] = { { ["type"] = "item", ["name"] = "angels-bio-refugium-biter-2", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-copper-tungsten-alloy", ["amount"] = 40 }, { ["type"] = "item", ["name"] = "bob-advanced-processing-unit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "angels-titanium-concrete-brick", ["amount"] = 95 }, { ["type"] = "item", ["name"] = "bob-copper-tungsten-pipe", ["amount"] = 33 } },
	["angels-bio-refugium-puffer"] = { { ["type"] = "item", ["name"] = "bob-glass", ["amount"] = 5 }, { ["type"] = "item", ["name"] = "bob-aluminium-plate", ["amount"] = 16 }, { ["type"] = "item", ["name"] = "advanced-circuit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "concrete", ["amount"] = 15 }, { ["type"] = "item", ["name"] = "bob-brass-pipe", ["amount"] = 33 } },
	["angels-bio-refugium-puffer-2"] = { { ["type"] = "item", ["name"] = "angels-bio-refugium-puffer", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-titanium-plate", ["amount"] = 16 }, { ["type"] = "item", ["name"] = "processing-unit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 15 }, { ["type"] = "item", ["name"] = "bob-titanium-pipe", ["amount"] = 33 } },
	["angels-bio-refugium-puffer-3"] = { { ["type"] = "item", ["name"] = "angels-bio-refugium-puffer-2", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "tungsten-plate", ["amount"] = 16 }, { ["type"] = "item", ["name"] = "bob-advanced-processing-unit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 15 }, { ["type"] = "item", ["name"] = "bob-tungsten-pipe", ["amount"] = 33 } },
	["angels-nutrient-extractor-2"] = { { ["type"] = "item", ["name"] = "angels-nutrient-extractor", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-aluminium-plate", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "advanced-circuit", ["amount"] = 2 }, { ["type"] = "item", ["name"] = "concrete", ["amount"] = 5 }, { ["type"] = "item", ["name"] = "bob-brass-pipe", ["amount"] = 6 }, { ["type"] = "item", ["name"] = "bob-brass-gear-wheel", ["amount"] = 6 } },
	["angels-nutrient-extractor-3"] = { { ["type"] = "item", ["name"] = "angels-nutrient-extractor-2", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-titanium-plate", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "processing-unit", ["amount"] = 2 }, { ["type"] = "item", ["name"] = "refined-concrete", ["amount"] = 5 }, { ["type"] = "item", ["name"] = "bob-titanium-pipe", ["amount"] = 6 }, { ["type"] = "item", ["name"] = "bob-titanium-gear-wheel", ["amount"] = 6 } },
	["angels-seed-extractor-3"] = { { ["type"] = "item", ["name"] = "angels-seed-extractor-2", ["amount"] = 1 }, { ["type"] = "item", ["name"] = "bob-aluminium-plate", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "advanced-circuit", ["amount"] = 4 }, { ["type"] = "item", ["name"] = "concrete", ["amount"] = 5 }, { ["type"] = "item", ["name"] = "bob-brass-gear-wheel", ["amount"] = 6 } },
}
for name, list in pairs(ingredients) do
	local recipe = data.raw.recipe[name]
	if recipe then recipe.ingredients = list end
end

-- Финал Beta 8 и API 1.1: только 100 атмосферы, без добавленного в 2.0 возврата 20 кислого газа.
local puffing = data.raw.recipe["angels-puffer-puffing-23"]
if puffing then
	for index = #(puffing.results or {}), 1, -1 do
		local product = puffing.results[index]
		if product.type == "fluid" and product.name == "angels-gas-acid" then table.remove(puffing.results, index) end
	end
end
