data:extend(
{   {
    type = "double-setting",
    name = "TS_energy_consumption_multiplier",
    setting_type = "startup",
    default_value = 2,
    maximum_value = 100,
    minimum_value = 0.01,
	order = "a",
    per_user = false,
	},
    {
    type = "int-setting",
    name = "TS_max_shield",
    setting_type = "runtime-global",
    default_value = 200,
    maximum_value = 10000,
    minimum_value = 0,
	order = "a",
    per_user = false,
	},    
    {
    type = "int-setting",
    name = "TS_charging_speed",
    setting_type = "runtime-global",
    default_value = 15,
    maximum_value = 1000,
    minimum_value = 0,
	order = "b",
    per_user = false,
	},
	 {
    type = "double-setting",
    name = "TS_penalty",
    setting_type = "runtime-global",
    default_value = 37.5,
    maximum_value = 100.0,
    minimum_value = 0,
	order = "c",
    per_user = false,
	},
	{
    type = "double-setting",
    name = "TS_power_usage",
    setting_type = "runtime-global",
    default_value = 0.1,
    maximum_value = 10.0,
    minimum_value = 0,
	order = "ca",
    per_user = false,
	},
    {
    type = "bool-setting",
    name = "TS_energy_consumption",
    setting_type = "runtime-global",
    default_value = true,
	order = "d",
    per_user = false,
	},   
	 {
    type = "bool-setting",
    name = "TS_alternate_effect",
    setting_type = "runtime-global",
    default_value = true,
	order = "e",
    per_user = false,
	},   
	{
    type = "bool-setting",
    name = "TS_research_enabled",
    setting_type = "runtime-global",
    default_value = true,
	order = "f",
    per_user = false,
	},   
    {
    type = "double-setting",
    name = "TS_research_size",
    setting_type = "runtime-global",
    default_value = 1.0,
    maximum_value = 100.0,
    minimum_value = 0.01,
	order = "g",
    per_user = false,
	},
	{
    type = "double-setting",
    name = "TS_research_speed",
    setting_type = "runtime-global",
    default_value = 1.0,
    maximum_value = 100.0,
    minimum_value = 0.01,
	order = "h",
    per_user = false,
	},

})


