return
{
  entities =
  {
    {"stone-wall", {x = -3.5, y = -2.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -3.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"gate", {x = -2.5, y = -3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -1.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -0.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"wall-remnants", {x = 0.5, y = -3.5}, {}},
    {"wall-remnants", {x = 2.5, y = -3.5}, {}},
    {"wall-remnants", {x = 1.5, y = -3.5}, {}},
    {"wall-remnants", {x = 3.5, y = -2.5}, {}},
    {"wall-remnants", {x = 3.5, y = -3.5}, {}},
    {"wall-remnants", {x = -3.5, y = -0.5}, {}},
    {"wall-remnants", {x = -3.5, y = -1.5}, {}},
    {"medium-electric-pole", {x = -1.5, y = -1.5}, {}},
    {"inserter-remnants", {x = -1.5, y = -0.5}, {}},
    {"requester-chest-remnants", {x = -2.5, y = -0.5}, {dir = "south", }},
    {"artillery-turret-remnants", {x = 0.5, y = -1.5}, {dir = "south", }},
    {"wall-remnants", {x = 3.5, y = -0.5}, {}},
    {"wall-remnants", {x = 3.5, y = -1.5}, {}},
    {"wall-remnants", {x = -3.5, y = 1.5}, {}},
    {"wall-remnants", {x = -3.5, y = 0.5}, {}},
    {"requester-chest-remnants", {x = -2.5, y = 0.5}, {dir = "south", }},
    {"inserter-remnants", {x = -1.5, y = 0.5}, {}},
    {"artillery-turret-remnants", {x = 0.5, y = 1.5}, {dir = "south", }},
    {"wall-remnants", {x = 3.5, y = 1.5}, {}},
    {"wall-remnants", {x = 3.5, y = 0.5}, {}},
    {"wall-remnants", {x = -3.5, y = 3.5}, {}},
    {"wall-remnants", {x = -3.5, y = 2.5}, {}},
    {"wall-remnants", {x = -1.5, y = 3.5}, {}},
    {"wall-remnants", {x = -2.5, y = 3.5}, {}},
    {"wall-remnants", {x = 0.5, y = 3.5}, {}},
    {"wall-remnants", {x = -0.5, y = 3.5}, {}},
    {"wall-remnants", {x = 2.5, y = 3.5}, {}},
    {"wall-remnants", {x = 1.5, y = 3.5}, {}},
    {"wall-remnants", {x = 3.5, y = 3.5}, {}},
    {"wall-remnants", {x = 3.5, y = 2.5}, {}},
  },
}
