return
{
  entities =
  {
    {"centrifuge-remnants", {x = 1.5, y = -1.5}, {}},
    {"offshore-pump-remnants", {x = -3.5, y = 0.5}, {dir = "east", }},
    {"wooden-chest", {x = 1.5, y = 0.5}, {items = {["uranium-238"] = {type = "random", min = 3, max = 16}}, dmg = {dmg = {type = "random", min = 0, max = 26}}}},
  },
  tiles =
  {
    {"nuclear-ground", {x = -4, y = -1}},
    {"nuclear-ground", {x = -4, y = 0}},
    {"nuclear-ground", {x = -4, y = 1}},
    {"nuclear-ground", {x = -3, y = -2}},
    {"water-green", {x = -3, y = -1}},
    {"water-green", {x = -3, y = 0}},
    {"water-green", {x = -3, y = 1}},
    {"nuclear-ground", {x = -3, y = 2}},
    {"nuclear-ground", {x = -3, y = 3}},
    {"nuclear-ground", {x = -2, y = -3}},
    {"water-green", {x = -2, y = -2}},
    {"water-green", {x = -2, y = -1}},
    {"water-green", {x = -2, y = 0}},
    {"water-green", {x = -2, y = 1}},
    {"water-green", {x = -2, y = 2}},
    {"nuclear-ground", {x = -2, y = 3}},
    {"nuclear-ground", {x = -1, y = -3}},
    {"nuclear-ground", {x = -1, y = -2}},
    {"water-green", {x = -1, y = -1}},
    {"water-green", {x = -1, y = 0}},
    {"water-green", {x = -1, y = 1}},
    {"water-green", {x = -1, y = 2}},
    {"nuclear-ground", {x = -1, y = 3}},
    {"nuclear-ground", {x = 0, y = -3}},
    {"nuclear-ground", {x = 0, y = -2}},
    {"nuclear-ground", {x = 0, y = -1}},
    {"water-green", {x = 0, y = 0}},
    {"water-green", {x = 0, y = 1}},
    {"water-green", {x = 0, y = 2}},
    {"nuclear-ground", {x = 0, y = 3}},
    {"nuclear-ground", {x = 1, y = -4}},
    {"nuclear-ground", {x = 1, y = -3}},
    {"nuclear-ground", {x = 1, y = -2}},
    {"nuclear-ground", {x = 1, y = 0}},
    {"water-green", {x = 1, y = 1}},
    {"water-green", {x = 1, y = 2}},
    {"nuclear-ground", {x = 1, y = 3}},
    {"nuclear-ground", {x = 2, y = -4}},
    {"nuclear-ground", {x = 2, y = -3}},
    {"nuclear-ground", {x = 2, y = -1}},
    {"nuclear-ground", {x = 2, y = 0}},
    {"nuclear-ground", {x = 2, y = 1}},
    {"nuclear-ground", {x = 2, y = 2}},
    {"nuclear-ground", {x = 3, y = -3}},
    {"nuclear-ground", {x = 3, y = -2}},
    {"nuclear-ground", {x = 3, y = -1}},
  }
}
