return
{
  entities =
  {
    {"accumulator", {x = 1, y = -3}, {dead = 0.4}},
    {"accumulator", {x = 3, y = -3}, {dead = 0.4}},
    {"accumulator", {x = -3, y = -2}, {dead = 0.4}},
    {"medium-electric-pole", {x = -0.5, y = -1.5}, {dead = 0.4}},
    {"laser-turret-remnants", {x = -2, y = 1}, {dir = "south", }},
    {"laser-turret-remnants", {x = 1, y = 1}, {dir = "south", }},
    {"stone-wall", {x = -2.5, y = 3.5}, {dead = 0.4}},
    {"stone-wall", {x = -0.5, y = 3.5}, {dead = 0.4}},
    {"stone-wall", {x = -1.5, y = 3.5}, {dead = 0.4}},
    {"stone-wall", {x = 1.5, y = 3.5}, {dead = 0.4}},
    {"stone-wall", {x = 0.5, y = 3.5}, {dead = 0.4}},
    {"stone-wall", {x = 3.5, y = 3.5}, {dead = 0.4}},
  },
  tiles =
  {
    {"refined-hazard-concrete-right", {x = -4, y = -1}},
    {"refined-hazard-concrete-right", {x = -4, y = 0}},
    {"refined-hazard-concrete-right", {x = -4, y = 1}},
    {"refined-hazard-concrete-right", {x = -4, y = 2}},
    {"refined-hazard-concrete-right", {x = -3, y = -1}},
    {"refined-concrete", {x = -3, y = 0}},
    {"refined-hazard-concrete-right", {x = -3, y = 1}},
    {"refined-hazard-concrete-right", {x = -3, y = 2}},
    {"stone-path", {x = -2, y = -1}},
    {"refined-concrete", {x = -2, y = 0}},
    {"refined-hazard-concrete-right", {x = -2, y = 1}},
    {"refined-hazard-concrete-right", {x = -2, y = 2}},
    {"stone-path", {x = -1, y = -1}},
    {"refined-hazard-concrete-right", {x = -1, y = 0}},
    {"refined-hazard-concrete-right", {x = -1, y = 1}},
    {"refined-hazard-concrete-right", {x = -1, y = 2}},
    {"stone-path", {x = 0, y = -1}},
    {"refined-hazard-concrete-right", {x = 0, y = 0}},
    {"refined-hazard-concrete-right", {x = 0, y = 1}},
    {"refined-concrete", {x = 0, y = 2}},
    {"refined-concrete", {x = 1, y = -1}},
    {"refined-hazard-concrete-right", {x = 1, y = 0}},
    {"refined-hazard-concrete-right", {x = 1, y = 1}},
    {"stone-path", {x = 1, y = 2}},
    {"refined-hazard-concrete-right", {x = 2, y = -1}},
    {"refined-hazard-concrete-right", {x = 2, y = 0}},
    {"refined-hazard-concrete-right", {x = 2, y = 1}},
    {"stone-path", {x = 2, y = 2}},
  }
}
