return
{
  entities =
  {
    {"stone-wall", {x = -4.5, y = -4.5}, {dead = 0.4, }},
    {"stone-wall", {x = -2.5, y = -4.5}, {dead = 0.4, }},
    {"stone-wall", {x = -3.5, y = -4.5}, {dead = 0.4, }},
    {"stone-wall", {x = -1.5, y = -4.5}, {dead = 0.4, }},
    {"stone-wall", {x = -0.5, y = -4.5}, {}},
    {"stone-wall", {x = 0.5, y = -4.5}, {dead = 0.4, }},
    {"stone-wall", {x = 1.5, y = -4.5}, {}},
    {"stone-wall", {x = 2.5, y = -4.5}, {}},
    {"stone-wall", {x = 3.5, y = -4.5}, {}},
    {"stone-wall", {x = 4.5, y = -4.5}, {dead = 0.4, }},
    {"stone-wall", {x = -4.5, y = -3.5}, {}},
    {"stone-wall", {x = -4.5, y = -2.5}, {dead = 0.4, }},
    {"storage-tank", {x = -1.5, y = -1.5}, {dead = 0.4, }},
    {"storage-tank", {x = 1.5, y = -2.5}, {dead = 0.4, }},
    {"stone-wall", {x = 3.5, y = -3.5}, {}},
    {"stone-wall", {x = 3.5, y = -2.5}, {dead = 0.4, }},
    {"stone-wall", {x = 4.5, y = -3.5}, {dead = 0.4, }},
    {"stone-wall", {x = 4.5, y = -2.5}, {dead = 0.4, }},
    {"stone-wall", {x = -4.5, y = -1.5}, {}},
    {"stone-wall", {x = -4.5, y = -0.5}, {}},
    {"pipe", {x = 0.5, y = -0.5}, {}},
    {"pipe", {x = 1.5, y = -0.5}, {dead = 0.4, }},
    {"stone-wall", {x = 3.5, y = -0.5}, {}},
    {"stone-wall", {x = 3.5, y = -1.5}, {}},
    {"pipe", {x = 2.5, y = -0.5}, {dead = 0.4, }},
    {"stone-wall", {x = 4.5, y = -0.5}, {dead = 0.4, }},
    {"stone-wall", {x = 4.5, y = -1.5}, {}},
    {"stone-wall", {x = -4.5, y = 0.5}, {}},
    {"stone-wall", {x = -4.5, y = 1.5}, {}},
    {"storage-tank", {x = -1.5, y = 1.5}, {dir = "east", dead = 0.4, }},
    {"pipe-to-ground", {x = 1.5, y = 0.5}, {}},
    {"stone-wall", {x = 4.5, y = 0.5}, {}},
    {"stone-wall", {x = 4.5, y = 1.5}, {dead = 0.4, }},
    {"stone-wall", {x = -4.5, y = 2.5}, {dead = 0.4, }},
    {"stone-wall", {x = -4.5, y = 3.5}, {dead = 0.4, }},
    {"stone-wall", {x = -2.5, y = 3.5}, {dead = 0.4, }},
    {"stone-wall", {x = -3.5, y = 3.5}, {dead = 0.4, }},
    {"stone-wall", {x = -1.5, y = 3.5}, {dead = 0.4, }},
    {"stone-wall", {x = -0.5, y = 3.5}, {dead = 0.4, }},
    {"stone-wall", {x = 1.5, y = 3.5}, {dead = 0.4, }},
    {"stone-wall", {x = 0.5, y = 3.5}, {}},
    {"stone-wall", {x = 3.5, y = 3.5}, {dead = 0.4, }},
    {"stone-wall", {x = 2.5, y = 3.5}, {}},
    {"stone-wall", {x = 4.5, y = 2.5}, {}},
    {"stone-wall", {x = 4.5, y = 3.5}, {dead = 0.4, }},
    {"pipe", {x = 1.5, y = 5.5}, {}},
    {"pipe-to-ground", {x = 1.5, y = 4.5}, {dir = "south", dead = 0.4, }},
    {"pipe", {x = -0.5, y = 6.5}, {}},
    {"pipe", {x = 0.5, y = 6.5}, {dead = 0.4, }},
    {"pipe", {x = 1.5, y = 6.5}, {dead = 0.4, }},
  },
}
