--list of all of the mod's item, recipes, techs, category and entity files
--planing to amalgamate some of the items and recipes and techs into single files to clean this up a bit

if mods["space-age"] then
    require("prototypes.item.intermediates.multiore-dropship-item")
    require("prototypes.recipe.intermediates.multiore-dropship-unboxing-recipe")
end

require("prototypes.item.advanced-probe")
require("prototypes.item.space-lab")
require("prototypes.item.station-science")
require("prototypes.item.observation-satellite")
require("prototypes.item.planetary-data")
require("prototypes.item.space-telescope")
require("prototypes.item.orbital-solar-collector-item")
require("prototypes.item.orbital-power-reciver-item")
require("prototypes.item.space-shuttle-item")
require("prototypes.item.ground-telescope-item")
require("prototypes.item.space-telescope-uplink-station-item")
require("prototypes.item.advanced-assembler-item")
require("prototypes.item.mining-shuttle-item")
require("prototypes.item.orbital-fabricator-items")
require("prototypes.item.erp-lab-item")


require("prototypes.item.intermediates.telescope-components")
require("prototypes.item.intermediates.radioisotope-thermoelectric-generator-item")
require("prototypes.item.intermediates.satellite-battery-item")
require("prototypes.item.intermediates.satellite-bus-item")
require("prototypes.item.intermediates.satellite-communications-item")
require("prototypes.item.intermediates.satellite-flight-computer-item")
require("prototypes.item.intermediates.satellite-radar-item")
require("prototypes.item.intermediates.satellite-solar-array-item")
require("prototypes.item.intermediates.satellite-thruster-item")
require("prototypes.item.intermediates.space-lab-payload-item")
require("prototypes.item.intermediates.landed-shuttle-item")
require("prototypes.item.intermediates.shuttle-hull-item")
require("prototypes.item.intermediates.probe-data-item")
require("prototypes.item.intermediates.autonomous-space-mining-drone-item")
require("prototypes.item.intermediates.copper-dropship-item")
require("prototypes.item.intermediates.iron-dropship-item")
require("prototypes.item.intermediates.landed-mining-shuttle-item")

require("prototypes.recipe.advanced-probe-recipe")
require("prototypes.recipe.space-lab-recipe")
require("prototypes.recipe.observation-satellite-recipe")
require("prototypes.recipe.space-telescope-recipe")
require("prototypes.recipe.orbital-solar-collector-recipe")
require("prototypes.recipe.space-shuttle-recipe")
require("prototypes.recipe.ground-telescope-recipe")
require("prototypes.recipe.study-the-stars-recipe")
require("prototypes.recipe.advanced-assembler-recipe")
require("prototypes.recipe.autonomous-fabricator-recipies-recipe")
require("prototypes.recipe.erp-lab-recipe")

require("prototypes.recipe.intermediates.telescope-components-recipe")
require("prototypes.recipe.intermediates.radioisotope thermoelectric generator-recipe")
require("prototypes.recipe.intermediates.satellite-battery-recipe")
require("prototypes.recipe.intermediates.satellite-bus-recipe")
require("prototypes.recipe.intermediates.satellite-communications-recipe")
require("prototypes.recipe.intermediates.satellite-flight-computer-recipe")
require("prototypes.recipe.intermediates.satellite-radar-recipe")
require("prototypes.recipe.intermediates.satellite-solar-array-recipe")
require("prototypes.recipe.intermediates.satellite-thruster-recipe")
require("prototypes.recipe.intermediates.space-lab-payload-recipe")
require("prototypes.recipe.intermediates.refurbish-shuttle-recipe")
require("prototypes.recipe.intermediates.shuttle-hull-recipe")
require("prototypes.recipe.intermediates.probe-data-processing-recipe")
require("prototypes.recipe.intermediates.copper-dropship-unboxing-recipe")
require("prototypes.recipe.intermediates.iron-dropship-unboxing-recipe")
require("prototypes.recipe.intermediates.landed-mining-shuttle-refurbishment-recipe")
require("prototypes.recipe.intermediates.autonomous-space-mining-drone-recipe")
require("prototypes.recipe.intermediates.space-shuttle-repurposing-recipe")

require("prototypes.technology.advanced-probe-tech")
require("prototypes.technology.space-lab-tech")
require("prototypes.technology.observation-satellite-tech")
require("prototypes.technology.space-telescope-tech")
require("prototypes.technology.space-telescope-research-tech")
require("prototypes.technology.drone-gps-tech")
require("prototypes.technology.advanced-battery-research-tech")
require("prototypes.technology.advanced-fan-research-tech")
require("prototypes.technology.extremely-advanced-material-processing-tech")
require("prototypes.technology.space-lab-research-tech")
require("prototypes.technology.orbital-solar-collector-tech")
require("prototypes.technology.space-shuttle-tech")
require("prototypes.technology.extremely-advanced-rocket-payloads-tech")
require("prototypes.technology.ground-telescope-tech")
require("prototypes.technology.advanced-machining-tech")
require("prototypes.technology.improved-space-program-theory-tech")
require("prototypes.technology.space-mining-tech")
require("prototypes.technology.space-mining-theory-tech")
require("prototypes.technology.shuttle-repurposing-tech")
require("prototypes.technology.orbital-fabricators-tech")
require("prototypes.technology.stack-inserter-research-tech")
require("prototypes.technology.space-station-assembly-tech")
require("prototypes.technology.satellite-tracking-tech")
require("prototypes.technology.erp-lab-tech")


require("prototypes.entity.orbital-power-reciver-entity")
require("prototypes.entity.ground-telescope-entity")
require("prototypes.entity.space-telescope-uplink-station-entity")
require("prototypes.entity.advanced-assembler-entity")
require("prototypes.entity.orbital-fabricator-ground-entity")
require("prototypes.entity.erp-lab-entity")

require("prototypes.category")
