return
{
  entities =
  {
    {"substation", {x = -1, y = -7}, {dmg = {dmg = {type = "random", min = 0, max = 80}}}},
    {"fast-inserter", {x = 1.5, y = -7.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"assembling-machine-3", {x = 1.5, y = -5.5}, {dead = 1}},
    {"solar-panel", {x = 6.5, y = -6.5}, {dead = 0.4}},
    {"transport-belt", {x = 4.5, y = -6.5}, {dead = 0.4}},
    {"fast-inserter", {x = 3.5, y = -5.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 4.5, y = -5.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 4.5, y = -4.5}, {dead = 0.4}},
    {"solar-panel", {x = -5.5, y = -2.5}, {dead = 0.4}},
    {"transport-belt", {x = -3.5, y = -2.5}, {dir = "west", dead = 0.4}},
    {"transport-belt", {x = -2.5, y = -2.5}, {dir = "west", dead = 0.4}},
    {"transport-belt", {x = -1.5, y = -2.5}, {dir = "west", dead = 0.4}},
    {"transport-belt", {x = -0.5, y = -2.5}, {dir = "west", dead = 0.4}},
    {"transport-belt", {x = 0.5, y = -2.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 1.5, y = -2.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = -2.5}, {dir = "west", dead = 0.4}},
    {"transport-belt", {x = 3.5, y = -2.5}, {dir = "west", dead = 0.4}},
    {"transport-belt", {x = 4.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"splitter", {x = 5.5, y = -3}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 4.5, y = -2.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 6.5, y = -2.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"centrifuge", {x = -4.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 50, max = 150}}, dead = 0.7}},
    {"fast-inserter", {x = -3.5, y = -1.5}, {dead = 0.4}},
    {"fast-inserter", {x = -2.5, y = -1.5}, {dead = 0.4}},
    {"centrifuge", {x = -1.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 50, max = 150}}, dead = 0.7}},
    {"centrifuge", {x = 1.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 50, max = 150}}, dead = 0.7}},
    {"fast-inserter", {x = 2.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"fast-inserter", {x = 3.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"centrifuge", {x = 4.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 50, max = 150}}, dead = 0.7}},
    {"transport-belt", {x = -6.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = -5.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = -4.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"fast-inserter", {x = -3.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"fast-inserter", {x = -2.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = -2.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = -3.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = -0.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = -1.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 1.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 0.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"fast-inserter", {x = 2.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"fast-inserter", {x = 3.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 3.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 5.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 4.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"transport-belt", {x = 6.5, y = 3.5}, {dir = "west", dmg = {dmg = {type = "random", min = 0, max = 80}}, dead = 0.4}},
    {"accumulator", {x = -4, y = 6}, {dead = 0.4}},
    {"substation", {x = 0, y = 5}, {dmg = {dmg = {type = "random", min = 0, max = 80}}}},
    {"accumulator", {x = 6, y = 7}, {dead = 0.4}},
  },
}
