return
{
  entities =
  {
    {"wall-remnants", {x = -7, y = -6.5}, {}},
    {"wall-remnants", {x = -6, y = -6.5}, {}},
    {"wall-remnants", {x = -7, y = -5.5}, {}},
    {"stone-wall", {x = -5, y = -6.5}, {}},
    {"stone-wall", {x = -4, y = -6.5}, {}},
    {"medium-electric-pole-remnants", {x = -3, y = -5.5}, {}},
    {"stone-wall", {x = -2, y = -6.5}, {}},
    {"stone-wall", {x = -3, y = -6.5}, {}},
    {"solar-panel", {x = -1, y = -4.5}, {dead = 0.4}},
    {"stone-wall", {x = 0, y = -6.5}, {}},
    {"stone-wall", {x = -1, y = -6.5}, {}},
    {"stone-wall", {x = 2, y = -6.5}, {}},
    {"stone-wall", {x = 1, y = -6.5}, {}},
    {"medium-electric-pole-remnants", {x = 3, y = -5.5}, {}},
    {"stone-wall", {x = 3, y = -6.5}, {}},
    {"stone-wall", {x = 4, y = -6.5}, {}},
    {"stone-wall", {x = 5, y = -6.5}, {}},
    {"stone-wall", {x = 6, y = -6.5}, {}},
    {"wall-remnants", {x = 7, y = -5.5}, {}},
    {"stone-wall", {x = 7, y = -6.5}, {}},
    {"wall-remnants", {x = -7, y = -3.5}, {}},
    {"wall-remnants", {x = -7, y = -4.5}, {}},
    {"stone-wall", {x = -7, y = -3.5}, {}},
    {"solar-panel-remnants", {x = -5, y = -4.5}, {dir = "south", }},
    {"small-lamp", {x = -3, y = -4.5}, {}},
    {"lamp-remnants", {x = 3, y = -4.5}, {}},
    {"solar-panel-remnants", {x = 5, y = -4.5}, {dir = "south", }},
    {"wall-remnants", {x = 7, y = -4.5}, {}},
    {"stone-wall", {x = 7, y = -3.5}, {}},
    {"stone-wall", {x = -7, y = -2.5}, {}},
    {"stone-wall", {x = -7, y = -1.5}, {}},
    {"solar-panel", {x = -4, y = -1.5}, {dead = 0.4}},
    {"solar-panel", {x = -1, y = -1.5}, {dead = 0.4}},
    {"solar-panel", {x = 2, y = -1.5}, {dead = 0.4}},
    {"solar-panel", {x = 5, y = -1.5}, {dead = 0.4}},
    {"stone-wall", {x = 7, y = -2.5}, {}},
    {"stone-wall", {x = 7, y = -1.5}, {}},
    {"stone-wall", {x = -7, y = -0.5}, {}},
    {"wall-remnants", {x = -7, y = 0.5}, {}},
    {"solar-panel", {x = -4, y = 1.5}, {dead = 0.4}},
    {"solar-panel", {x = -1, y = 1.5}, {dead = 0.4}},
    {"solar-panel", {x = 2, y = 1.5}, {dead = 0.4}},
    {"solar-panel", {x = 5, y = 1.5}, {dead = 0.4}},
    {"stone-wall", {x = 7, y = -0.5}, {}},
    {"stone-wall", {x = 7, y = 0.5}, {}},
    {"wall-remnants", {x = -7, y = 1.5}, {}},
    {"wall-remnants", {x = -7, y = 2.5}, {}},
    {"stone-wall", {x = 7, y = 1.5}, {}},
    {"stone-wall", {x = 7, y = 2.5}, {}},
    {"stone-wall", {x = -7, y = 3.5}, {}},
    {"stone-wall", {x = -7, y = 4.5}, {}},
    {"solar-panel", {x = -5, y = 4.5}, {dead = 0.4}},
    {"medium-electric-pole-remnants", {x = -3, y = 3.5}, {}},
    {"small-lamp", {x = -3, y = 4.5}, {}},
    {"solar-panel", {x = -1, y = 4.5}, {dead = 0.4}},
    {"medium-electric-pole-remnants", {x = 3, y = 3.5}, {}},
    {"lamp-remnants", {x = 3, y = 4.5}, {}},
    {"solar-panel-remnants", {x = 5, y = 4.5}, {dir = "south", }},
    {"wall-remnants", {x = 7, y = 4.5}, {}},
    {"wall-remnants", {x = 7, y = 3.5}, {}},
    {"stone-wall", {x = -7, y = 5.5}, {}},
    {"stone-wall", {x = -7, y = 6.5}, {}},
    {"stone-wall", {x = -6, y = 6.5}, {}},
    {"stone-wall", {x = -4, y = 6.5}, {}},
    {"stone-wall", {x = -5, y = 6.5}, {}},
    {"stone-wall", {x = -2, y = 6.5}, {}},
    {"stone-wall", {x = -3, y = 6.5}, {}},
    {"wall-remnants", {x = -1, y = 6.5}, {}},
    {"wall-remnants", {x = 0, y = 6.5}, {}},
    {"stone-wall", {x = 2, y = 6.5}, {}},
    {"stone-wall", {x = 1, y = 6.5}, {}},
    {"stone-wall", {x = 4, y = 6.5}, {}},
    {"stone-wall", {x = 3, y = 6.5}, {}},
    {"wall-remnants", {x = 6, y = 6.5}, {}},
    {"stone-wall", {x = 5, y = 6.5}, {}},
    {"wall-remnants", {x = 7, y = 6.5}, {}},
    {"wall-remnants", {x = 7, y = 5.5}, {}},
  },
}
