-- размер по одному из измерений мал, пока закомментирую
-------------------------------------------------------------------------------------------------
--подмена графики стандартного кирпича
-- if settings.startup["stone-path-concrete"].value then
-- 	local stone_variants = util.table.deepcopy(data.raw.tile["refined-concrete"].variants)
-- 	stone_variants.material_background.picture = "__zzzparanoidal__/graphics/patches/concrete.png"
-- 	data.raw.tile["stone-path"].variants = stone_variants
-- end
-------------------------------------------------------------------------------------------------
--замена текстуры для "бетон с разметкой опасности"
-- data.raw.tile["hazard-concrete-left"].variants.material_background.picture =
-- 	"__zzzparanoidal__/graphics/grid/hazard-concrete-left.png"
-- data.raw.tile["hazard-concrete-right"].variants.material_background.picture =
-- 	"__zzzparanoidal__/graphics/grid/hazard-concrete-right.png"
-------------------------------------------------------------------------------------------------

