require("interfaces.constants")
require("prototypes.final-fixes.from-update.basics.resources")
require("prototypes.final-fixes.from-update.recipes")
require("prototypes.final-fixes.from-update.items")
require("prototypes.final-fixes.from-update.entities")
require("prototypes.final-fixes.from-update.technologies")
require("prototypes.final-fixes.from-update.crash-site-spaceship-entries")
