return
{
  entities =
  {
    {"tree-04-stump", {x = -14.8, y = -12.62}, {dir = "west", }},
    {"tree-04-stump", {x = 8.01, y = -12.65}, {dir = "east", }},
    {"tree-04-stump", {x = -14.13, y = -12.09}, {dir = "west", }},
    {"tree-04-stump", {x = -13.8, y = -10.11}, {dir = "east", }},
    {"tree-04-stump", {x = -13.48, y = -11.98}, {}},
    {"tree-04-stump", {x = -12.48, y = -10.34}, {dir = "west", }},
    {"tree-04-stump", {x = -12.38, y = -10.9}, {}},
    {"tree-04-stump", {x = -8.26, y = -11.44}, {dir = "south", }},
    {"tree-04-stump", {x = -8.56, y = -11.43}, {dir = "east", }},
    {"tree-04-stump", {x = -7.46, y = -10.13}, {dir = "south", }},
    {"tree-04-stump", {x = -7.82, y = -10.16}, {dir = "east", }},
    {"tree-04-stump", {x = -2.48, y = -10.46}, {dir = "south", }},
    {"tree-04-stump", {x = -3.62, y = -10.83}, {}},
    {"tree-04-stump", {x = 1.91, y = -10.11}, {dir = "south", }},
    {"tree-04-stump", {x = 4.45, y = -11.72}, {dir = "west", }},
    {"tree-04-stump", {x = 8.52, y = -11.2}, {}},
    {"tree-04-stump", {x = 11, y = -11.56}, {dir = "west", }},
    {"tree-04-stump", {x = -12.6, y = -9.4}, {dir = "south", }},
    {"tree-04-stump", {x = -8.44, y = -8.28}, {dir = "south", }},
    {"tree-04-stump", {x = -9.91, y = -8.29}, {dir = "west", }},
    {"tree-04-stump", {x = -8.39, y = -8.76}, {dir = "east", }},
    {"tree-04-stump", {x = -8.04, y = -8.62}, {dir = "west", }},
    {"wall-remnants", {x = 0, y = -10}, {dir = "east", }},
    {"tree-04-stump", {x = 9.15, y = -8.21}, {}},
    {"tree-04-stump", {x = 9.05, y = -10.09}, {dir = "south", }},
    {"wall-remnants", {x = 15, y = -9}, {dir = "east", }},
    {"tree-03", {x = 14.07, y = -10.04}, {}},
    {"tree-04-stump", {x = -14.45, y = -7.99}, {dir = "south", }},
    {"tree-04-stump", {x = -13.02, y = -7.05}, {dir = "south", }},
    {"tree-04-stump", {x = -6.79, y = -7.66}, {dir = "south", }},
    {"tree-04-stump", {x = -7.4, y = -7.84}, {dir = "east", }},
    {"tree-04-stump", {x = -1.18, y = -6.71}, {dir = "west", }},
    {"wall-remnants", {x = 0, y = -7}, {dir = "east", }},
    {"tree-04-stump", {x = 5.13, y = -6.95}, {dir = "west", }},
    {"tree-04-stump", {x = 4.15, y = -7.95}, {}},
    {"tree-04-stump", {x = 7.37, y = -7.86}, {dir = "east", }},
    {"tree-04-stump", {x = 8.28, y = -6.29}, {dir = "east", }},
    {"tree-04-stump", {x = 13.55, y = -8.05}, {dir = "south", }},
    {"wall-remnants", {x = 15, y = -7}, {dir = "east", }},
    {"tree-04-stump", {x = 14.1, y = -6.84}, {dir = "east", }},
    {"tree-04-stump", {x = -10.21, y = -4.64}, {}},
    {"tree-04-stump", {x = -11.12, y = -5.84}, {dir = "west", }},
    {"dead-dry-hairy-tree", {x = -7.12, y = -5.55}, {}},
    {"tree-04-stump", {x = -2.93, y = -4.34}, {dir = "south", }},
    {"tree-04-stump", {x = -1.72, y = -5.18}, {dir = "south", }},
    {"wall-remnants", {x = 0, y = -5}, {dir = "east", }},
    {"transport-belt-remnants", {x = 1, y = -5}, {}},
    {"tree-04-stump", {x = 0.72, y = -6.08}, {dir = "south", }},
    {"tree-04-stump", {x = 1.98, y = -5.38}, {}},
    {"tree-03-stump", {x = 7.17, y = -4.89}, {}},
    {"wall-remnants", {x = 15, y = -5}, {dir = "east", }},
    {"tree-04-stump", {x = -14.4, y = -2.6}, {dir = "west", }},
    {"tree-04-stump", {x = -11.02, y = -2.79}, {}},
    {"tree-04-stump", {x = -6.16, y = -2.75}, {}},
    {"tree-04-stump", {x = -4.39, y = -2.39}, {dir = "east", }},
    {"tree-04-stump", {x = -5.38, y = -3.77}, {dir = "west", }},
    {"tree-04-stump", {x = -5.5, y = -3.75}, {}},
    {"tree-04-stump", {x = -3.66, y = -2.93}, {}},
    {"wall-remnants", {x = 0, y = -4}, {dir = "east", }},
    {"transport-belt-remnants", {x = 1, y = -4}, {}},
    {"transport-belt-remnants", {x = 1, y = -3}, {}},
    {"stone-wall", {x = 0, y = -3}, {}},
    {"boiler-remnants", {x = 3.5, y = -4}, {dir = "east", }},
    {"small-electric-pole-remnants", {x = 10, y = -3}, {dir = "west", }},
    {"wall-remnants", {x = 15, y = -4}, {dir = "east", }},
    {"stone-wall", {x = 15, y = -3}, {}},
    {"tree-04-stump", {x = -12.64, y = -1.72}, {dir = "west", }},
    {"tree-04-stump", {x = -9.64, y = -0.89}, {dir = "south", }},
    {"tree-04-stump", {x = -9.91, y = -1.86}, {dir = "south", }},
    {"tree-04-stump", {x = -7.66, y = -1.05}, {dir = "south", }},
    {"stone-wall", {x = 0, y = -2}, {}},
    {"stone-wall", {x = 0, y = -1}, {}},
    {"transport-belt-remnants", {x = 1, y = -2}, {}},
    {"transport-belt-remnants", {x = 1, y = -1}, {}},
    {"burner-inserter-remnants", {x = 2, y = -1}, {dir = "east", }},
    {"boiler-remnants", {x = 3.5, y = -1}, {dir = "east", }},
    {"steam-engine-remnants", {x = 7, y = -1}, {dir = "east", }},
    {"steam-engine-remnants", {x = 12, y = -1}, {dir = "east", }},
    {"stone-wall", {x = 15, y = -1}, {}},
    {"stone-wall", {x = 15, y = -2}, {}},
    {"tree-04-stump", {x = -7.86, y = 0.25}, {dir = "east", }},
    {"stone-wall", {x = 0, y = 0}, {}},
    {"stone-wall", {x = 0, y = 1}, {}},
    {"transport-belt-remnants", {x = 1, y = 0}, {}},
    {"transport-belt-remnants", {x = 1, y = 1}, {}},
    {"boiler", {x = 3.5, y = 2}, {dir = "east", }},
    {"steam-engine", {x = 7, y = 2}, {dir = "east", }},
    {"steam-engine", {x = 12, y = 2}, {dir = "east", }},
    {"stone-wall", {x = 15, y = 0}, {}},
    {"stone-wall", {x = 15, y = 1}, {}},
    {"tree-04-stump", {x = -14.11, y = 3.47}, {dir = "east", }},
    {"tree-04-stump", {x = -15.06, y = 2.45}, {}},
    {"tree-04-stump", {x = -12.07, y = 3.4}, {dir = "east", }},
    {"tree-04-stump", {x = -10.59, y = 3.2}, {dir = "east", }},
    {"stone-wall", {x = 0, y = 2}, {}},
    {"stone-wall", {x = 0, y = 3}, {}},
    {"transport-belt-remnants", {x = 1, y = 2}, {}},
    {"transport-belt-remnants", {x = 1, y = 3}, {}},
    {"burner-inserter", {x = 2, y = 2}, {dir = "west", }},
    {"stone-wall", {x = 15, y = 2}, {}},
    {"stone-wall", {x = 15, y = 3}, {}},
    {"tree-04-stump", {x = -13.92, y = 5.7}, {dir = "west", }},
    {"tree-04-stump", {x = -14.04, y = 4.76}, {}},
    {"tree-04-stump", {x = -13.62, y = 3.96}, {dir = "south", }},
    {"tree-04-stump", {x = -11.87, y = 5.49}, {}},
    {"tree-04-stump", {x = -8.95, y = 4.25}, {}},
    {"tree-04-stump", {x = -6.88, y = 5.41}, {dir = "south", }},
    {"stone-wall", {x = 0, y = 4}, {}},
    {"stone-wall", {x = 0, y = 5}, {}},
    {"transport-belt-remnants", {x = 1, y = 4}, {}},
    {"transport-belt", {x = 1, y = 5}, {}},
    {"small-electric-pole", {x = 10, y = 4}, {}},
    {"stone-wall", {x = 15, y = 5}, {}},
    {"stone-wall", {x = 15, y = 4}, {}},
    {"tree-04-stump", {x = -11.96, y = 7.6}, {dir = "south", }},
    {"tree-04-stump", {x = -7.17, y = 7.03}, {dir = "west", }},
    {"tree-04-stump", {x = -4.65, y = 6.95}, {dir = "west", }},
    {"tree-04-stump", {x = -3.9, y = 7.75}, {dir = "south", }},
    {"stone-wall", {x = 0, y = 6}, {}},
    {"stone-wall", {x = 0, y = 7}, {}},
    {"transport-belt", {x = 1, y = 6}, {}},
    {"transport-belt", {x = 2, y = 6}, {dir = "west", }},
    {"transport-belt", {x = 3, y = 6}, {dir = "west", }},
    {"transport-belt", {x = 3, y = 7}, {}},
    {"gun-turret", {x = 12.5, y = 6.5}, {dir = "south", force = "enemy", items = {["firearm-magazine"] = 5}, }},
    {"stone-wall", {x = 15, y = 7}, {}},
    {"stone-wall", {x = 15, y = 6}, {}},
    {"tree-04-stump", {x = -10.85, y = 9.64}, {dir = "east", }},
    {"tree-04-stump", {x = -3.02, y = 9.83}, {dir = "west", }},
    {"tree-04-stump", {x = -3.42, y = 8.65}, {dir = "south", }},
    {"stone-wall", {x = 0, y = 8}, {}},
    {"stone-wall", {x = 0, y = 9}, {}},
    {"wooden-chest-remnants", {x = 1, y = 9}, {dir = "east", }},
    {"wooden-chest-remnants", {x = 1, y = 8}, {dir = "east", }},
    {"burner-inserter-remnants", {x = 2, y = 9}, {dir = "east", }},
    {"burner-inserter-remnants", {x = 2, y = 8}, {dir = "east", }},
    {"transport-belt-remnants", {x = 3, y = 9}, {}},
    {"transport-belt", {x = 3, y = 8}, {}},
    {"wooden-chest-remnants", {x = 5, y = 9}, {dir = "east", }},
    {"wooden-chest-remnants", {x = 5, y = 8}, {dir = "east", }},
    {"burner-inserter-remnants", {x = 4, y = 8}, {dir = "east", }},
    {"burner-inserter-remnants", {x = 4, y = 9}, {dir = "east", }},
    {"small-electric-pole-remnants", {x = 9, y = 8}, {dir = "west", }},
    {"stone-wall", {x = 15, y = 9}, {}},
    {"stone-wall", {x = 15, y = 8}, {}},
    {"tree-04-stump", {x = -14.43, y = 11.82}, {dir = "east", }},
    {"tree-04-stump", {x = -8.3, y = 10.81}, {dir = "south", }},
    {"tree-04-stump", {x = -4.09, y = 10.85}, {dir = "south", }},
    {"tree-04-stump", {x = -3.65, y = 9.98}, {dir = "west", }},
    {"stone-wall", {x = 0, y = 10}, {}},
    {"stone-wall", {x = 0, y = 11}, {}},
    {"wooden-chest", {x = 1, y = 11}, {items = {wood = {type = "random", min = 120, max = 300}}, }},
    {"wooden-chest", {x = 1, y = 10}, {items = {wood = {type = "random", min = 120, max = 300}}, }},
    {"burner-inserter-remnants", {x = 2, y = 10}, {dir = "east", }},
    {"burner-inserter-remnants", {x = 2, y = 11}, {dir = "east", }},
    {"transport-belt-remnants", {x = 3, y = 11}, {}},
    {"transport-belt-remnants", {x = 3, y = 10}, {}},
    {"wooden-chest", {x = 5, y = 11}, {items = {wood = {type = "random", min = 120, max = 300}}, }},
    {"wooden-chest", {x = 5, y = 10}, {items = {wood = {type = "random", min = 120, max = 300}}, }},
    {"burner-inserter", {x = 4, y = 11}, {dir = "east", }},
    {"burner-inserter-remnants", {x = 4, y = 10}, {dir = "east", }},
    {"radar-remnants", {x = 8, y = 10}, {dir = "west", }},
    {"gun-turret", {x = 12.5, y = 10.5}, {dir = "east", force = "enemy", dmg = {dmg = {type = "random", min = 80, max = 150}}, items = {["firearm-magazine"] = 3}, }},
    {"stone-wall", {x = 15, y = 10}, {}},
    {"stone-wall", {x = 15, y = 11}, {}},
    {"tree-04-stump", {x = -13.3, y = 13.24}, {dir = "south", }},
    {"tree-04-stump", {x = -11.72, y = 13.06}, {dir = "south", }},
    {"tree-04-stump", {x = -11.94, y = 11.9}, {dir = "west", }},
    {"tree-04-stump", {x = -9.9, y = 12.48}, {}},
    {"tree-04-stump", {x = -7.73, y = 12.75}, {dir = "east", }},
    {"tree-04-stump", {x = -6.81, y = 13.33}, {dir = "east", }},
    {"tree-04-stump", {x = -2.02, y = 12.27}, {dir = "west", }},
    {"tree-04-stump", {x = -1.69, y = 13.39}, {dir = "south", }},
    {"stone-wall", {x = 0, y = 12}, {}},
    {"stone-wall", {x = 0, y = 13}, {}},
    {"stone-wall", {x = 1, y = 13}, {}},
    {"wooden-chest", {x = 1, y = 12}, {items = {wood = {type = "random", min = 100, max = 250}}, }},
    {"stone-wall", {x = 2, y = 13}, {}},
    {"stone-wall", {x = 3, y = 13}, {}},
    {"transport-belt-remnants", {x = 3, y = 12}, {}},
    {"burner-inserter", {x = 2, y = 12}, {dir = "west", }},
    {"stone-wall", {x = 4, y = 13}, {}},
    {"stone-wall", {x = 5, y = 13}, {}},
    {"burner-inserter", {x = 4, y = 12}, {dir = "east", }},
    {"wooden-chest", {x = 5, y = 12}, {items = {wood = {type = "random", min = 120, max = 300}}, }},
    {"gate", {x = 6, y = 13}, {dir = "east", }},
    {"gate-remnants", {x = 7, y = 13}, {dir = "west", }},
    {"wall-remnants", {x = 9, y = 13}, {dir = "west", }},
    {"gate-remnants", {x = 8, y = 13}, {dir = "west", }},
    {"wall-remnants", {x = 10, y = 13}, {dir = "west", }},
    {"stone-wall", {x = 11, y = 13}, {}},
    {"stone-wall", {x = 13, y = 13}, {}},
    {"stone-wall", {x = 12, y = 13}, {}},
    {"stone-wall", {x = 15, y = 12}, {}},
    {"stone-wall", {x = 15, y = 13}, {}},
    {"stone-wall", {x = 14, y = 13}, {}},
  },
  tiles =
  {
    {"concrete", {x = 0.5, y = -2.5}},
    {"concrete", {x = 0.5, y = -1.5}},
    {"concrete", {x = 0.5, y = -0.5}},
    {"concrete", {x = 0.5, y = 0.5}},
    {"concrete", {x = 0.5, y = 1.5}},
    {"concrete", {x = 0.5, y = 2.5}},
    {"concrete", {x = 0.5, y = 3.5}},
    {"concrete", {x = 0.5, y = 4.5}},
    {"concrete", {x = 0.5, y = 5.5}},
    {"concrete", {x = 0.5, y = 6.5}},
    {"concrete", {x = 0.5, y = 7.5}},
    {"concrete", {x = 0.5, y = 8.5}},
    {"concrete", {x = 0.5, y = 9.5}},
    {"concrete", {x = 0.5, y = 10.5}},
    {"concrete", {x = 0.5, y = 11.5}},
    {"concrete", {x = 1.5, y = -3.5}},
    {"concrete", {x = 1.5, y = -2.5}},
    {"concrete", {x = 1.5, y = -1.5}},
    {"concrete", {x = 1.5, y = -0.5}},
    {"concrete", {x = 1.5, y = 1.5}},
    {"concrete", {x = 1.5, y = 2.5}},
    {"concrete", {x = 1.5, y = 3.5}},
    {"concrete", {x = 1.5, y = 4.5}},
    {"concrete", {x = 1.5, y = 5.5}},
    {"concrete", {x = 1.5, y = 6.5}},
    {"concrete", {x = 1.5, y = 7.5}},
    {"concrete", {x = 1.5, y = 8.5}},
    {"concrete", {x = 1.5, y = 9.5}},
    {"concrete", {x = 1.5, y = 10.5}},
    {"concrete", {x = 1.5, y = 11.5}},
    {"concrete", {x = 2.5, y = -3.5}},
    {"concrete", {x = 2.5, y = -2.5}},
    {"concrete", {x = 2.5, y = -1.5}},
    {"concrete", {x = 2.5, y = -0.5}},
    {"concrete", {x = 2.5, y = 0.5}},
    {"concrete", {x = 2.5, y = 1.5}},
    {"concrete", {x = 2.5, y = 2.5}},
    {"concrete", {x = 2.5, y = 3.5}},
    {"concrete", {x = 2.5, y = 4.5}},
    {"concrete", {x = 2.5, y = 5.5}},
    {"concrete", {x = 2.5, y = 6.5}},
    {"concrete", {x = 2.5, y = 7.5}},
    {"concrete", {x = 2.5, y = 8.5}},
    {"concrete", {x = 2.5, y = 9.5}},
    {"concrete", {x = 2.5, y = 10.5}},
    {"concrete", {x = 2.5, y = 11.5}},
    {"concrete", {x = 3.5, y = -3.5}},
    {"concrete", {x = 3.5, y = -2.5}},
    {"concrete", {x = 3.5, y = -1.5}},
    {"concrete", {x = 3.5, y = -0.5}},
    {"concrete", {x = 3.5, y = 0.5}},
    {"concrete", {x = 3.5, y = 1.5}},
    {"concrete", {x = 3.5, y = 2.5}},
    {"concrete", {x = 3.5, y = 3.5}},
    {"concrete", {x = 3.5, y = 4.5}},
    {"concrete", {x = 3.5, y = 5.5}},
    {"concrete", {x = 3.5, y = 6.5}},
    {"concrete", {x = 3.5, y = 7.5}},
    {"concrete", {x = 3.5, y = 8.5}},
    {"concrete", {x = 3.5, y = 9.5}},
    {"concrete", {x = 3.5, y = 10.5}},
    {"concrete", {x = 3.5, y = 11.5}},
    {"concrete", {x = 4.5, y = -4.5}},
    {"concrete", {x = 4.5, y = -3.5}},
    {"concrete", {x = 4.5, y = -2.5}},
    {"concrete", {x = 4.5, y = -1.5}},
    {"concrete", {x = 4.5, y = -0.5}},
    {"concrete", {x = 4.5, y = 0.5}},
    {"concrete", {x = 4.5, y = 1.5}},
    {"concrete", {x = 4.5, y = 2.5}},
    {"concrete", {x = 4.5, y = 3.5}},
    {"concrete", {x = 4.5, y = 4.5}},
    {"concrete", {x = 4.5, y = 5.5}},
    {"concrete", {x = 4.5, y = 6.5}},
    {"concrete", {x = 4.5, y = 7.5}},
    {"concrete", {x = 4.5, y = 8.5}},
    {"concrete", {x = 4.5, y = 9.5}},
    {"concrete", {x = 4.5, y = 10.5}},
    {"concrete", {x = 4.5, y = 11.5}},
    {"concrete", {x = 5.5, y = -5.5}},
    {"concrete", {x = 5.5, y = -4.5}},
    {"concrete", {x = 5.5, y = -3.5}},
    {"concrete", {x = 5.5, y = -2.5}},
    {"concrete", {x = 5.5, y = -1.5}},
    {"concrete", {x = 5.5, y = -0.5}},
    {"concrete", {x = 5.5, y = 0.5}},
    {"concrete", {x = 5.5, y = 1.5}},
    {"concrete", {x = 5.5, y = 2.5}},
    {"concrete", {x = 5.5, y = 3.5}},
    {"concrete", {x = 5.5, y = 4.5}},
    {"concrete", {x = 5.5, y = 5.5}},
    {"concrete", {x = 5.5, y = 6.5}},
    {"concrete", {x = 5.5, y = 7.5}},
    {"concrete", {x = 5.5, y = 8.5}},
    {"concrete", {x = 5.5, y = 9.5}},
    {"concrete", {x = 5.5, y = 10.5}},
    {"concrete", {x = 5.5, y = 11.5}},
    {"concrete", {x = 6.5, y = -4.5}},
    {"concrete", {x = 6.5, y = -3.5}},
    {"concrete", {x = 6.5, y = -2.5}},
    {"concrete", {x = 6.5, y = -1.5}},
    {"concrete", {x = 6.5, y = -0.5}},
    {"concrete", {x = 6.5, y = 0.5}},
    {"concrete", {x = 6.5, y = 1.5}},
    {"concrete", {x = 6.5, y = 2.5}},
    {"concrete", {x = 6.5, y = 3.5}},
    {"concrete", {x = 6.5, y = 4.5}},
    {"concrete", {x = 6.5, y = 6.5}},
    {"concrete", {x = 6.5, y = 7.5}},
    {"concrete", {x = 6.5, y = 8.5}},
    {"concrete", {x = 6.5, y = 9.5}},
    {"concrete", {x = 6.5, y = 10.5}},
    {"concrete", {x = 6.5, y = 11.5}},
    {"concrete", {x = 7.5, y = -4.5}},
    {"concrete", {x = 7.5, y = -3.5}},
    {"concrete", {x = 7.5, y = -2.5}},
    {"concrete", {x = 7.5, y = -1.5}},
    {"concrete", {x = 7.5, y = -0.5}},
    {"concrete", {x = 7.5, y = 0.5}},
    {"concrete", {x = 7.5, y = 1.5}},
    {"concrete", {x = 7.5, y = 2.5}},
    {"concrete", {x = 7.5, y = 3.5}},
    {"concrete", {x = 7.5, y = 4.5}},
    {"concrete", {x = 7.5, y = 5.5}},
    {"concrete", {x = 7.5, y = 6.5}},
    {"concrete", {x = 7.5, y = 7.5}},
    {"concrete", {x = 7.5, y = 8.5}},
    {"concrete", {x = 7.5, y = 9.5}},
    {"concrete", {x = 7.5, y = 10.5}},
    {"concrete", {x = 8.5, y = -4.5}},
    {"concrete", {x = 8.5, y = -2.5}},
    {"concrete", {x = 8.5, y = -1.5}},
    {"concrete", {x = 8.5, y = -0.5}},
    {"concrete", {x = 8.5, y = 0.5}},
    {"concrete", {x = 8.5, y = 1.5}},
    {"concrete", {x = 8.5, y = 2.5}},
    {"concrete", {x = 8.5, y = 3.5}},
    {"concrete", {x = 8.5, y = 4.5}},
    {"concrete", {x = 8.5, y = 5.5}},
    {"concrete", {x = 8.5, y = 6.5}},
    {"concrete", {x = 8.5, y = 7.5}},
    {"concrete", {x = 8.5, y = 8.5}},
    {"concrete", {x = 8.5, y = 9.5}},
    {"concrete", {x = 8.5, y = 10.5}},
    {"concrete", {x = 9.5, y = -4.5}},
    {"concrete", {x = 9.5, y = -3.5}},
    {"concrete", {x = 9.5, y = -2.5}},
    {"concrete", {x = 9.5, y = -1.5}},
    {"concrete", {x = 9.5, y = -0.5}},
    {"concrete", {x = 9.5, y = 0.5}},
    {"concrete", {x = 9.5, y = 1.5}},
    {"concrete", {x = 9.5, y = 2.5}},
    {"stone-path", {x = 9.5, y = 3.5}},
    {"stone-path", {x = 9.5, y = 4.5}},
    {"stone-path", {x = 9.5, y = 5.5}},
    {"stone-path", {x = 9.5, y = 6.5}},
    {"stone-path", {x = 9.5, y = 7.5}},
    {"stone-path", {x = 9.5, y = 8.5}},
    {"stone-path", {x = 9.5, y = 9.5}},
    {"stone-path", {x = 9.5, y = 10.5}},
    {"concrete", {x = 10.5, y = -4.5}},
    {"concrete", {x = 10.5, y = -3.5}},
    {"concrete", {x = 10.5, y = -2.5}},
    {"concrete", {x = 10.5, y = -1.5}},
    {"concrete", {x = 10.5, y = -0.5}},
    {"concrete", {x = 10.5, y = 0.5}},
    {"concrete", {x = 10.5, y = 1.5}},
    {"concrete", {x = 10.5, y = 2.5}},
    {"stone-path", {x = 10.5, y = 3.5}},
    {"refined-hazard-concrete-left", {x = 10.5, y = 4.5}},
    {"refined-hazard-concrete-left", {x = 10.5, y = 5.5}},
    {"refined-hazard-concrete-left", {x = 10.5, y = 6.5}},
    {"refined-hazard-concrete-left", {x = 10.5, y = 7.5}},
    {"refined-hazard-concrete-right", {x = 10.5, y = 8.5}},
    {"refined-hazard-concrete-right", {x = 10.5, y = 9.5}},
    {"refined-hazard-concrete-right", {x = 10.5, y = 10.5}},
    {"concrete", {x = 11.5, y = -3.5}},
    {"concrete", {x = 11.5, y = -2.5}},
    {"concrete", {x = 11.5, y = -1.5}},
    {"concrete", {x = 11.5, y = -0.5}},
    {"concrete", {x = 11.5, y = 0.5}},
    {"concrete", {x = 11.5, y = 1.5}},
    {"concrete", {x = 11.5, y = 2.5}},
    {"stone-path", {x = 11.5, y = 3.5}},
    {"refined-hazard-concrete-left", {x = 11.5, y = 4.5}},
    {"refined-hazard-concrete-left", {x = 11.5, y = 5.5}},
    {"refined-hazard-concrete-left", {x = 11.5, y = 6.5}},
    {"refined-hazard-concrete-left", {x = 11.5, y = 7.5}},
    {"refined-hazard-concrete-right", {x = 11.5, y = 8.5}},
    {"refined-hazard-concrete-right", {x = 11.5, y = 9.5}},
    {"refined-hazard-concrete-right", {x = 11.5, y = 10.5}},
    {"refined-hazard-concrete-right", {x = 11.5, y = 11.5}},
    {"concrete", {x = 12.5, y = -4.5}},
    {"concrete", {x = 12.5, y = -3.5}},
    {"concrete", {x = 12.5, y = -2.5}},
    {"concrete", {x = 12.5, y = -1.5}},
    {"concrete", {x = 12.5, y = -0.5}},
    {"concrete", {x = 12.5, y = 0.5}},
    {"concrete", {x = 12.5, y = 1.5}},
    {"concrete", {x = 12.5, y = 2.5}},
    {"stone-path", {x = 12.5, y = 3.5}},
    {"refined-hazard-concrete-left", {x = 12.5, y = 4.5}},
    {"refined-hazard-concrete-left", {x = 12.5, y = 5.5}},
    {"refined-hazard-concrete-left", {x = 12.5, y = 6.5}},
    {"refined-hazard-concrete-left", {x = 12.5, y = 7.5}},
    {"refined-hazard-concrete-right", {x = 12.5, y = 8.5}},
    {"refined-hazard-concrete-right", {x = 12.5, y = 9.5}},
    {"refined-hazard-concrete-right", {x = 12.5, y = 10.5}},
    {"refined-hazard-concrete-right", {x = 12.5, y = 11.5}},
    {"concrete", {x = 13.5, y = -2.5}},
    {"concrete", {x = 13.5, y = -1.5}},
    {"concrete", {x = 13.5, y = -0.5}},
    {"concrete", {x = 13.5, y = 0.5}},
    {"concrete", {x = 13.5, y = 1.5}},
    {"concrete", {x = 13.5, y = 2.5}},
    {"stone-path", {x = 13.5, y = 3.5}},
    {"refined-hazard-concrete-left", {x = 13.5, y = 4.5}},
    {"refined-hazard-concrete-left", {x = 13.5, y = 5.5}},
    {"refined-hazard-concrete-left", {x = 13.5, y = 6.5}},
    {"refined-hazard-concrete-left", {x = 13.5, y = 7.5}},
    {"refined-hazard-concrete-right", {x = 13.5, y = 8.5}},
    {"refined-hazard-concrete-right", {x = 13.5, y = 9.5}},
    {"refined-hazard-concrete-right", {x = 13.5, y = 10.5}},
    {"refined-hazard-concrete-right", {x = 13.5, y = 11.5}},
  }
}
