require("__hardcore-mode-for-playing__.prototypes.fluid-in-container-processing")
require(
	"prototypes.final-fixes.from-update.technologies.fluid-in-container-processing.fluid-barrel-processing-technology-fixes"
)
require(
	"prototypes.final-fixes.from-update.technologies.fluid-in-container-processing.fluid-canister-processing-technology-fixes"
)
require(
	"prototypes.final-fixes.from-update.technologies.fluid-in-container-processing.gas-canister-proccessing-technology-fixes"
)
