require('__stdlib__/stdlib/event/event').set_protected_mode(true)
require('__stdlib__/stdlib/event/player').register_events(true)
require('__stdlib__/stdlib/event/force').register_events(true)

require('scripts/auto-deconstruct')
require('scripts/chest-limit')
require('scripts/copy-chests')
require('scripts/cursor-carousel')
require('scripts/filter-fill')
require('scripts/inventory-sort')
require('scripts/inventory-tools')
require('scripts/item-count')
require('scripts/item-zapper')
require('scripts/packing-tape')
require('scripts/switch-gun')
require('scripts/toggle-groups')
require('scripts/toggle-equipment')
require('scripts/toggle-flashlight')
require('scripts/toggle-minimap')

remote.add_interface(script.mod_name, require('__stdlib__/stdlib/scripts/interface'))
