local l_ruins = {}

table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/destroyedEnemyFort"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/destroyedFort"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/earlyGame"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/eFurnaceRail"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/fishingLake"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/loggingOutpost"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/mainBus"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/nuclearPower"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/orchard"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/overwhelmedLasers"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/shipwreck"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/solarField"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/SOS"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/swamp"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/trainMining"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/trainMining2"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/walledOrchard"))
table.insert(l_ruins, require("__AbandonedRuins__/ruins/largeRuins/walledGrotto"))

table.insert(l_ruins, require("drdLarge/burner1"))
table.insert(l_ruins, require("drdLarge/dump"))
table.insert(l_ruins, require("drdLarge/heater1"))
table.insert(l_ruins, require("drdLarge/laser1-1"))
table.insert(l_ruins, require("drdLarge/ore-comb1"))
table.insert(l_ruins, require("drdLarge/orecrusher1"))
table.insert(l_ruins, require("drdLarge/sniper1-1"))
table.insert(l_ruins, require("drdLarge/traindepo1"))
table.insert(l_ruins, require("drdLarge/turret4-1"))
table.insert(l_ruins, require("drdLarge/turret4-2"))
table.insert(l_ruins, require("drdLarge/turret5-1"))
table.insert(l_ruins, require("drdLarge/turret5-2"))
table.insert(l_ruins, require("drdLarge/turret5-3"))
table.insert(l_ruins, require("drdLarge/turret5-4"))
table.insert(l_ruins, require("drdLarge/wind1"))
table.insert(l_ruins, require("drdLarge/woodfarm1"))

return l_ruins
