data:extend(
{ 	{
		type = "bool-setting",
		name = "laserfix-doubletint", 
		setting_type = "startup",
		default_value = true,
		order="a",
		per_user = false,
	},
	--{
	--	type = "string-setting",
	--	name = "laserfix-color", 
	--	setting_type = "startup",
	--	default_value = "Red",
	--	allowed_values = {"Red", "'Disco'", "Custom"},
	--	order="a0",
	--	per_user = false,
	--},
	{
		type = "double-setting",
		name = "laserfix-r", 
		setting_type = "startup",
		default_value = 1,
		maximum_value = 1,
		minimum_value = 0,
		order="a2",
		per_user = false,
	},	
	{
		type = "double-setting",
		name = "laserfix-g", 
		setting_type = "startup",
		default_value = 0,
		maximum_value = 1,
		minimum_value = 0,
		order="a3",
		per_user = false,
	},	
		{
		type = "double-setting",
		name = "laserfix-b", 
		setting_type = "startup",
		default_value = 0,
		maximum_value = 1,
		minimum_value = 0,
		order="a4",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "laserfix-glow-r", 
		setting_type = "startup",
		default_value = 0.5,
		maximum_value = 1,
		minimum_value = 0,
		order="a5",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "laserfix-glow-g", 
		setting_type = "startup",
		default_value = 0.05,
		maximum_value = 1,
		minimum_value = 0,
		order="a6",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "laserfix-glow-b", 
		setting_type = "startup",
		default_value = 0.05,
		maximum_value = 1,
		minimum_value = 0,
		order="a7",
		per_user = false,
	},	
}   
)

