return
{
  variables =
  {
    {name = "random-tree-1", type = "entity-expression", value = {type = "random-of-entity-type", entity_type = "tree"}},
    {name = "random-tree-2", type = "entity-expression", value = {type = "random-of-entity-type", entity_type = "tree"}}
  },
  entities =
  {
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -12.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -10.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -8.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -6.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -4.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -2.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -0.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 1.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 3.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 5.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 7.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 9.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 11.5, y = -12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -12.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -10.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -8.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -6.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -4.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -2.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -0.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 1.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 3.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 5.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 7.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 9.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 11.5, y = -7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -12.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -10.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -8.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -6.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -4.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -2.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -0.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 1.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 3.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 5.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 7.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 9.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 11.5, y = -2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -12.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -10.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -8.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -6.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -4.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -2.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -0.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 1.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 3.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 5.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 7.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 9.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 11.5, y = 2.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -12.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -10.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -8.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -6.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -4.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -2.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -0.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 1.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 3.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 5.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 7.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 9.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 11.5, y = 7.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -12.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -10.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -8.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -6.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -4.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -2.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = -0.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 1.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 3.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 5.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 7.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 9.5, y = 12.5}, {}},
    {{type = "random-variable", variables = {"random-tree-1", "random-tree-2"}}, {x = 11.5, y = 12.5}, {}},
  },
}
