return
{
  entities =
  {
    {"straight-rail-remnants", {x = -13, y = -9.5}, {dir = "east", }},
    {"straight-rail-remnants", {x = -11, y = -9.5}, {dir = "east", }},
    {"straight-rail-remnants", {x = -9, y = -9.5}, {dir = "east", }},
    {"straight-rail-remnants", {x = -7, y = -9.5}, {dir = "east", }},
    {"straight-rail-remnants", {x = -5, y = -9.5}, {dir = "east", }},
    {"straight-rail-remnants", {x = -3, y = -9.5}, {dir = "east", }},
    {"straight-rail-remnants", {x = -1, y = -9.5}, {dir = "east", }},
    {"straight-rail-remnants", {x = 1, y = -9.5}, {dir = "east", }},
    {"straight-rail-remnants", {x = 3, y = -9.5}, {dir = "east", }},
    {"straight-rail", {x = 5, y = -9.5}, {dir = "east", }},
    {"straight-rail", {x = 7, y = -9.5}, {dir = "east", }},
    {"medium-electric-pole-remnants", {x = -13.5, y = -7}, {}},
    {"lamp-remnants", {x = -12.5, y = -7}, {}},
    {"steel-chest-remnants", {x = -10.5, y = -7}, {}},
    {"fast-inserter", {x = -10.5, y = -8}, {dir = "south", dmg = {dmg = 48}, }},
    {"fast-inserter", {x = -11.5, y = -8}, {dir = "south", dmg = {dmg = 48}, }},
    {"steel-chest", {x = -11.5, y = -7}, {items = {["copper-ore"] = {type = "random", min = 20, max = 50}}, }},
    {"fast-inserter-remnants", {x = -8.5, y = -8}, {dir = "south", }},
    {"fast-inserter-remnants", {x = -9.5, y = -8}, {dir = "south", }},
    {"steel-chest-remnants", {x = -9.5, y = -7}, {}},
    {"steel-chest-remnants", {x = -8.5, y = -7}, {}},
    {"medium-electric-pole-remnants", {x = -6.5, y = -7}, {}},
    {"lamp-remnants", {x = -7.5, y = -7}, {}},
    {"steel-chest-remnants", {x = -4.5, y = -7}, {}},
    {"fast-inserter-remnants", {x = -4.5, y = -8}, {dir = "south", }},
    {"lamp-remnants", {x = -5.5, y = -7}, {}},
    {"steel-chest-remnants", {x = -2.5, y = -7}, {}},
    {"steel-chest-remnants", {x = -3.5, y = -7}, {}},
    {"fast-inserter", {x = -2.5, y = -8}, {dir = "south", }},
    {"fast-inserter", {x = -3.5, y = -8}, {dir = "south", }},
    {"small-lamp", {x = -0.5, y = -7}, {}},
    {"fast-inserter", {x = -1.5, y = -8}, {dir = "south", }},
    {"steel-chest", {x = -1.5, y = -7}, {items = {["copper-ore"] = {type = "random", min = 20, max = 50}}, }},
    {"medium-electric-pole", {x = 0.5, y = -7}, {}},
    {"train-stop-remnants", {x = 7, y = -7.5}, {dir = "east", }},
    {"stone-wall", {x = 9.5, y = -7}, {}},
    {"laser-turret", {x = 12, y = -6.5}, {dir = "south", dmg = {dmg = {type = "random", min = 250, max = 500}}, }},
    {"stone-wall", {x = 10.5, y = -8}, {}},
    {"stone-wall", {x = 11.5, y = -8}, {}},
    {"stone-wall", {x = 10.5, y = -7}, {}},
    {"wall-remnants", {x = 12.5, y = -8}, {}},
    {"stone-wall", {x = 13.5, y = -7}, {dmg = {dmg = 215}, }},
    {"stone-wall", {x = 13.5, y = -8}, {dmg = {dmg = 135}, }},
    {"fast-inserter-remnants", {x = -10.5, y = -6}, {dir = "south", }},
    {"fast-inserter-remnants", {x = -11.5, y = -6}, {dir = "south", }},
    {"fast-transport-belt", {x = -11.5, y = -5}, {}},
    {"fast-transport-belt", {x = -10.5, y = -5}, {dir = "west", dmg = {dmg = 8}, }},
    {"fast-inserter-remnants", {x = -9.5, y = -6}, {dir = "south", }},
    {"fast-inserter-remnants", {x = -8.5, y = -6}, {dir = "south", }},
    {"fast-transport-belt", {x = -9.5, y = -5}, {dir = "west", }},
    {"fast-transport-belt", {x = -8.5, y = -5}, {dir = "west", }},
    {"fast-transport-belt", {x = -7.5, y = -5}, {dir = "west", }},
    {"fast-transport-belt", {x = -6.5, y = -5}, {dir = "west", }},
    {"fast-transport-belt-remnants", {x = -4.5, y = -5}, {}},
    {"fast-inserter-remnants", {x = -4.5, y = -6}, {dir = "south", }},
    {"fast-inserter-remnants", {x = -2.5, y = -6}, {dir = "south", }},
    {"fast-transport-belt-remnants", {x = -2.5, y = -5}, {dir = "west", }},
    {"fast-transport-belt-remnants", {x = -3.5, y = -5}, {dir = "west", }},
    {"fast-inserter-remnants", {x = -3.5, y = -6}, {dir = "south", }},
    {"fast-inserter", {x = -1.5, y = -6}, {dir = "south", }},
    {"fast-transport-belt", {x = -0.5, y = -5}, {dir = "west", }},
    {"fast-transport-belt", {x = -1.5, y = -5}, {dir = "west", }},
    {"fast-transport-belt", {x = 1.5, y = -5}, {dir = "west", }},
    {"fast-transport-belt", {x = 0.5, y = -5}, {dir = "west", }},
    {"stone-wall", {x = 9.5, y = -5}, {}},
    {"stone-wall", {x = 9.5, y = -6}, {}},
    {"medium-electric-pole", {x = 10.5, y = -6}, {}},
    {"laser-turret", {x = 12, y = -4.5}, {dir = "south", dmg = {dmg = 266}, }},
    {"stone-wall", {x = 10.5, y = -5}, {}},
    {"wall-remnants", {x = 13.5, y = -5}, {}},
    {"wall-remnants", {x = 13.5, y = -6}, {}},
    {"medium-electric-pole", {x = -10.5, y = -3}, {}},
    {"electric-mining-drill", {x = -8.5, y = -3}, {dir = "east", }},
    {"fast-transport-belt", {x = -6.5, y = -3}, {}},
    {"fast-transport-belt", {x = -6.5, y = -4}, {}},
    {"electric-mining-drill", {x = -4.5, y = -3}, {dir = "west", }},
    {"electric-mining-drill", {x = -0.5, y = -3}, {dir = "east", }},
    {"fast-transport-belt", {x = 1.5, y = -3}, {}},
    {"fast-transport-belt", {x = 1.5, y = -4}, {}},
    {"electric-mining-drill-remnants", {x = 3.5, y = -3}, {dir = "south", }},
    {"medium-electric-pole", {x = 5.5, y = -3}, {}},
    {"wall-remnants", {x = 11.5, y = -3}, {}},
    {"stone-wall", {x = 10.5, y = -3}, {}},
    {"stone-wall", {x = 10.5, y = -4}, {}},
    {"wall-remnants", {x = 13.5, y = -3}, {}},
    {"stone-wall", {x = 13.5, y = -4}, {dmg = {dmg = 170}, }},
    {"stone-wall", {x = 12.5, y = -3}, {}},
    {"electric-mining-drill", {x = -8.5, y = 0}, {dir = "east", }},
    {"fast-transport-belt", {x = -6.5, y = -2}, {}},
    {"fast-transport-belt", {x = -6.5, y = -1}, {}},
    {"medium-electric-pole", {x = -2.5, y = -2}, {}},
    {"electric-mining-drill", {x = -0.5, y = 0}, {dir = "east", }},
    {"fast-transport-belt", {x = 1.5, y = -1}, {}},
    {"fast-transport-belt", {x = 1.5, y = -2}, {}},
    {"electric-mining-drill", {x = 3.5, y = 0}, {dir = "west", }},
    {"fast-transport-belt", {x = -6.5, y = 0}, {}},
    {"fast-transport-belt", {x = -6.5, y = 1}, {}},
    {"electric-mining-drill-remnants", {x = -4.5, y = 0}, {dir = "south", }},
    {"fast-transport-belt", {x = 1.5, y = 1}, {}},
    {"fast-transport-belt", {x = 1.5, y = 0}, {}},
    {"electric-mining-drill-remnants", {x = -8.5, y = 3}, {dir = "south", }},
    {"fast-transport-belt", {x = -6.5, y = 2}, {}},
    {"fast-transport-belt", {x = -6.5, y = 3}, {}},
    {"electric-mining-drill", {x = -4.5, y = 3}, {dir = "west", }},
    {"electric-mining-drill-remnants", {x = -0.5, y = 3}, {dir = "south", }},
    {"fast-transport-belt", {x = 1.5, y = 3}, {}},
    {"fast-transport-belt", {x = 1.5, y = 2}, {}},
    {"electric-mining-drill", {x = 3.5, y = 3}, {dir = "west", }},
    {"medium-electric-pole", {x = -10.5, y = 5}, {}},
    {"electric-mining-drill", {x = -8.5, y = 6}, {dir = "east", }},
    {"fast-transport-belt", {x = -6.5, y = 4}, {}},
    {"fast-transport-belt", {x = -6.5, y = 5}, {}},
    {"electric-mining-drill", {x = -4.5, y = 6}, {dir = "west", }},
    {"medium-electric-pole", {x = -2.5, y = 5}, {}},
    {"fast-transport-belt", {x = 1.5, y = 5}, {}},
    {"fast-transport-belt", {x = 1.5, y = 4}, {}},
    {"electric-mining-drill", {x = 3.5, y = 6}, {dir = "west", }},
    {"medium-electric-pole", {x = 5.5, y = 5}, {}},
    {"fast-transport-belt", {x = -6.5, y = 6}, {}},
    {"electric-mining-drill-remnants", {x = -0.5, y = 6}, {dir = "south", }},
    {"fast-transport-belt", {x = 1.5, y = 7}, {}},
    {"fast-transport-belt", {x = 1.5, y = 6}, {}},
    {"electric-mining-drill-remnants", {x = -0.5, y = 9}, {dir = "south", }},
    {"fast-transport-belt", {x = 1.5, y = 9}, {}},
    {"fast-transport-belt", {x = 1.5, y = 8}, {}},
    {"electric-mining-drill", {x = 3.5, y = 9}, {dir = "west", }},
  },
}
