return
{
  entities =
  {
    {"straight-scrap-rail", {x = -5.5, y = -11.5}, {dir = "northwest", }},
    {"curved-scrap-rail", {x = -8.5, y = -8.5}, {dir = "northeast", }},
    {"entity-ghost", {x = -8.5, y = -0.5}, {dir = "south", }},
    {"gun-turret", {x = -12.5, y = 0.5}, {force = "enemy", items = {["firearm-magazine"] = 50}, }},
    {"straight-scrap-rail", {x = -5.5, y = 2.5}, {dir = "southwest", }},
    {"curved-scrap-rail", {x = -2.5, y = 5.5}, {dir = "northwest", }},
    {"ScrapTrailer", {x = 2.5, y = 6.48}, {dmg = {dmg = 2}, }},
    {"straight-scrap-rail", {x = 2.5, y = 6.5}, {dir = "east", }},
    {"straight-scrap-rail", {x = 4.5, y = 6.5}, {dir = "east", }},
    {"JunkTrain", {x = 9.5, y = 6.5}, {}},
    {"straight-scrap-rail", {x = 6.5, y = 6.5}, {dir = "east", }},
    {"straight-scrap-rail", {x = 8.5, y = 6.5}, {dir = "east", }},
    {"straight-scrap-rail", {x = 10.5, y = 6.5}, {dir = "east", }},
    {"straight-scrap-rail", {x = 12.5, y = 6.5}, {dir = "east", }},
    {"entity-ghost", {x = 1, y = 8}, {dir = "south", }},
    {"entity-ghost", {x = 0, y = 8}, {dir = "south", }},
    {"basic-transport-belt", {x = 0, y = 9}, {dir = "east", dmg = {dmg = 2}, }},
    {"basic-transport-belt", {x = 1, y = 9}, {dir = "east", dmg = {dmg = 2}, }},
    {"entity-ghost", {x = 2, y = 9}, {dir = "east", }},
    {"inserter", {x = 3, y = 8}, {dir = "south", }},
    {"basic-transport-belt", {x = 3, y = 9}, {dir = "east", dmg = {dmg = 39}, }},
    {"inserter", {x = 2, y = 8}, {dir = "south", dmg = {dmg = 0}, }},
    {"basic-transport-belt", {x = 5, y = 9}, {dir = "east", }},
    {"basic-transport-belt", {x = 4, y = 9}, {dir = "east", }},
    {"inserter", {x = 4, y = 8}, {dir = "south", }},
    {"inserter", {x = 5, y = 8}, {dir = "south", }},
    {"train-stop-scrap", {x = 12.5, y = 8.5}, {dir = "east", }},
    {"gun-turret", {x = 11.5, y = 12.5}, {force = "enemy", items = {["firearm-magazine"] = 50}, }},
  },
}
