return
{
  entities =
  {
    {"inserter", {x = -2.5, y = -2.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = -2.5, y = -3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -1.5, y = -2.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -0.5, y = -2.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = -0.5, y = -3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = -1.5, y = -3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 1.5, y = -3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = 0.5, y = -2.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 0.5, y = -3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = -2.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = -3.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"small-electric-pole", {x = -3.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -2.5, y = -0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"iron-chest", {x = -2.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -1.5, y = -0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -0.5, y = -0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"iron-chest", {x = -1.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"iron-chest", {x = -0.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"small-electric-pole", {x = 1.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = 0.5, y = -0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"iron-chest", {x = 0.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = -0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = -1.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -2.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = -2.5, y = 0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = -3.5, y = 0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -1.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -0.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = -0.5, y = 0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = -1.5, y = 0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = 0.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 1.5, y = 0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 0.5, y = 0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 3.5, y = 0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = 0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"small-electric-pole", {x = -3.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"iron-chest", {x = -2.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -1.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = -0.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"iron-chest", {x = -0.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"iron-chest", {x = -1.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"small-electric-pole", {x = 1.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"inserter", {x = 0.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"iron-chest", {x = 0.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
    {"transport-belt", {x = 2.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 50}}, dead = 0.4}},
  },
}
