return
{
  entities =
  {
    {"tree-05", {x = 1.51, y = -2.53}, {}},
    {"stone-wall", {x = -3.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = 3.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -3.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -3.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"car", {x = 1.22, y = 1.11}, {dmg = {dmg = {type = "random", min = 250, max = 340}}, }},
    {"stone-wall", {x = 3.5, y = 0.5}, {}},
    {"stone-wall", {x = 3.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -2.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -3.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -3.5, y = 2.5}, {}},
    {"stone-wall", {x = -0.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = -1.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"wooden-chest", {x = 0.5, y = 2.5}, {items = {["solid-fuel"] = {type = "random", min = 10, max = 70}}, }},
    {"stone-wall", {x = 1.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = 0.5, y = 3.5}, {}},
    {"stone-wall", {x = 3.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = 3.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 20, max = 150}}, }},
    {"stone-wall", {x = 2.5, y = 3.5}, {}},
  },
  tiles =
  {
    {"concrete", {x = -3, y = -1}},
    {"concrete", {x = -3, y = 0}},
    {"concrete", {x = -3, y = 1}},
    {"concrete", {x = -3, y = 2}},
    {"hazard-concrete-left", {x = -2, y = -4}},
    {"hazard-concrete-left", {x = -2, y = -3}},
    {"concrete", {x = -2, y = -1}},
    {"concrete", {x = -2, y = 0}},
    {"concrete", {x = -2, y = 1}},
    {"concrete", {x = -2, y = 2}},
    {"hazard-concrete-left", {x = -1, y = -4}},
    {"hazard-concrete-left", {x = -1, y = -3}},
    {"hazard-concrete-left", {x = -1, y = -2}},
    {"stone-path", {x = -1, y = -1}},
    {"stone-path", {x = -1, y = 0}},
    {"stone-path", {x = -1, y = 1}},
    {"stone-path", {x = -1, y = 2}},
    {"hazard-concrete-left", {x = 0, y = -4}},
    {"hazard-concrete-left", {x = 0, y = -3}},
    {"hazard-concrete-left", {x = 0, y = -2}},
    {"stone-path", {x = 0, y = -1}},
    {"stone-path", {x = 0, y = 0}},
    {"stone-path", {x = 0, y = 1}},
    {"stone-path", {x = 0, y = 2}},
    {"hazard-concrete-left", {x = 1, y = -4}},
    {"hazard-concrete-left", {x = 1, y = -2}},
    {"concrete", {x = 1, y = -1}},
    {"stone-path", {x = 1, y = 0}},
    {"concrete", {x = 1, y = 2}},
    {"hazard-concrete-left", {x = 2, y = -4}},
    {"hazard-concrete-left", {x = 2, y = -3}},
    {"hazard-concrete-left", {x = 2, y = -2}},
    {"concrete", {x = 2, y = -1}},
    {"concrete", {x = 2, y = 0}},
    {"concrete", {x = 2, y = 1}},
    {"concrete", {x = 2, y = 2}},
    {"hazard-concrete-left", {x = 3, y = -3}},
    {"hazard-concrete-left", {x = 3, y = -2}},
  }
}
