require('prototypes.final-fixes.from-update.basics.basic-technologies')
require('prototypes.final-fixes.from-update.copying-for-modes.copy-to-normal-expensive-mode-data')
require('prototypes.final-fixes.from-update.technologies.mod_updating.normal-techologies-tree-update')
require('prototypes.final-fixes.from-update.technologies.link-basic-technologies-to-regular-tree')
require('prototypes.final-fixes.from-update.technologies.technology-unit-add-bean')
require('prototypes.final-fixes.from-update.technologies.technology-cycle-removing-bean')
require('prototypes.final-fixes.from-update.technologies.update-and-fix-technology-tree-ingredient-requirement')
