require('prototypes.final-fixes.from-update.technologies.basic-technologies')
require('prototypes.final-fixes.from-update.technologies.normal-techologies-tree-update')
require('prototypes.final-fixes.from-update.technologies.link-basic-technologies-to-regular-tree')
require('prototypes.final-fixes.from-update.technologies.technology-unit-add-bean')
require('prototypes.final-fixes.from-update.technologies.technology-cycle-removing-bean')
require('prototypes.final-fixes.from-update.technologies.update-and-fix-technology-tree-ingredient-requirement')
