require('prototypes.final-fixes.from-update.basics.basic-technologies')
require('prototypes.final-fixes.from-update.technologies.link-basic-technologies-to-regular-tree')
require('prototypes.final-fixes.from-update.copying-for-modes.copy-to-normal-expensive-mode-data')
require('prototypes.final-fixes.from-update.technologies.mod_updating.normal-techologies-tree-update')
require('prototypes.final-fixes.from-update.technologies.fluid-in-container-processing.main')
require('prototypes.final-fixes.from-update.technologies.tree-ingredients-requirements.technology-unit-add-bean')
require('prototypes.final-fixes.from-update.technologies.tree-ingredients-requirements.technology-cycle-removing-bean')
require(
    'prototypes.final-fixes.from-update.technologies.tree-ingredients-requirements.update-and-fix-technology-tree-ingredient-requirement')
