return
{
  entities =
  {
    {"dry-tree", {x = -3.41, y = -5.43}, {}},
    {"dry-tree", {x = 3.74, y = -5.5}, {}},
    {"crash-site-spaceship-wreck-small-3", {x = -1.25, y = -4.76}, {}},
    {"small-remnants", {x = 1.5, y = -4.5}, {dir = "east", }},
    {"crash-site-spaceship-wreck-big-1", {x = 2.07, y = -4.2}, {items = {stone = {type = "random", min = 25, max = 90}}, }},
    {"sand-rock-big", {x = 4.27, y = -3.81}, {}},
    {"crash-site-spaceship-wreck-medium-1", {x = -3.45, y = -1.33}, {items = {explosives = {type = "random", min = 7, max = 23}}, }},
    {"tree-02-stump", {x = -0.58, y = -1.61}, {}},
    {"crash-site-spaceship-wreck-big-2", {x = 4.91, y = -0.53}, {items = {["processing-unit"] = {type = "random", min = 0, max = 5}}, }},
    {"tree-01-stump", {x = -1.92, y = 0.75}, {dir = "east", }},
    {"small-remnants", {x = -3.5, y = 1.5}, {dir = "east", }},
    {"1x2-remnants", {x = 0.5, y = 0}, {dir = "east", }},
    {"small-remnants", {x = 4.5, y = 1.5}, {dir = "east", }},
    {"tree-08-stump", {x = -4.76, y = 3.21}, {}},
    {"crash-site-spaceship-wreck-small-6", {x = -0.15, y = 2.84}, {}},
    {"dry-tree", {x = 2.9, y = 3.32}, {}},
  },
  tiles =
  {
    {"nuclear-ground", {x = -4, y = -2}},
    {"nuclear-ground", {x = -4, y = -1}},
    {"nuclear-ground", {x = -4, y = 0}},
    {"nuclear-ground", {x = -4, y = 1}},
    {"nuclear-ground", {x = -4, y = 2}},
    {"nuclear-ground", {x = -3, y = -2}},
    {"nuclear-ground", {x = -3, y = -1}},
    {"nuclear-ground", {x = -3, y = 0}},
    {"nuclear-ground", {x = -3, y = 1}},
    {"nuclear-ground", {x = -3, y = 2}},
    {"nuclear-ground", {x = -2, y = -5}},
    {"nuclear-ground", {x = -2, y = -4}},
    {"nuclear-ground", {x = -2, y = -3}},
    {"nuclear-ground", {x = -2, y = -2}},
    {"nuclear-ground", {x = -2, y = -1}},
    {"nuclear-ground", {x = -2, y = 0}},
    {"nuclear-ground", {x = -2, y = 1}},
    {"nuclear-ground", {x = -2, y = 2}},
    {"nuclear-ground", {x = -1, y = -5}},
    {"nuclear-ground", {x = -1, y = -4}},
    {"nuclear-ground", {x = -1, y = -1}},
    {"nuclear-ground", {x = -1, y = 0}},
    {"nuclear-ground", {x = -1, y = 1}},
    {"nuclear-ground", {x = -1, y = 2}},
    {"nuclear-ground", {x = 0, y = -5}},
    {"nuclear-ground", {x = 0, y = -4}},
    {"nuclear-ground", {x = 0, y = -3}},
    {"nuclear-ground", {x = 0, y = -2}},
    {"nuclear-ground", {x = 0, y = -1}},
    {"nuclear-ground", {x = 0, y = 0}},
    {"nuclear-ground", {x = 0, y = 1}},
    {"nuclear-ground", {x = 0, y = 2}},
    {"nuclear-ground", {x = 1, y = -5}},
    {"nuclear-ground", {x = 1, y = -4}},
    {"nuclear-ground", {x = 1, y = -3}},
    {"nuclear-ground", {x = 1, y = -2}},
    {"nuclear-ground", {x = 1, y = -1}},
    {"nuclear-ground", {x = 1, y = 0}},
    {"nuclear-ground", {x = 1, y = 1}},
    {"nuclear-ground", {x = 1, y = 2}},
    {"nuclear-ground", {x = 2, y = -4}},
    {"nuclear-ground", {x = 2, y = -3}},
    {"nuclear-ground", {x = 2, y = -2}},
    {"nuclear-ground", {x = 2, y = -1}},
    {"nuclear-ground", {x = 2, y = 0}},
    {"nuclear-ground", {x = 2, y = 1}},
    {"nuclear-ground", {x = 3, y = -3}},
    {"nuclear-ground", {x = 3, y = -2}},
    {"nuclear-ground", {x = 3, y = -1}},
    {"nuclear-ground", {x = 3, y = 0}},
    {"nuclear-ground", {x = 3, y = 1}},
    {"nuclear-ground", {x = 4, y = -2}},
    {"nuclear-ground", {x = 4, y = -1}},
    {"nuclear-ground", {x = 4, y = 0}},
    {"nuclear-ground", {x = 4, y = 1}},
    {"nuclear-ground", {x = 5, y = -1}},
    {"nuclear-ground", {x = 5, y = 0}},
  }
}
