return
{
  entities =
  {
    {"rock-big", {x = 5.98, y = -5.34}, {}},
    {"rock-big", {x = -4.88, y = -4.87}, {}},
    {"rock-big", {x = -1.18, y = -4.48}, {}},
    {"stone-wall", {x = -3.5, y = -4.5}, {}},
    {"stone-wall", {x = -2.5, y = -4.5}, {}},
    {"stone-wall", {x = 0.5, y = -4.5}, {}},
    {"stone-wall", {x = 1.5, y = -4.5}, {}},
    {"rock-big", {x = 3.02, y = -4.46}, {}},
    {"stone-wall", {x = 4.5, y = -4.5}, {}},
    {"stone-wall", {x = -4.5, y = -2.5}, {}},
    {"stone-wall", {x = -4.5, y = -3.5}, {}},
    {"stone-wall", {x = 6.5, y = -2.5}, {}},
    {"stone-wall", {x = 6.5, y = -3.5}, {}},
    {"gate", {x = -4.5, y = -0.5}, {}},
    {"gate", {x = -4.5, y = -1.5}, {}},
    {"rock-big", {x = 6.66, y = -0.16}, {}},
    {"stone-wall", {x = 6.5, y = -1.5}, {}},
    {"stone-wall", {x = -4.5, y = 1.5}, {}},
    {"stone-wall", {x = -4.5, y = 0.5}, {}},
    {"stone-wall", {x = 6.5, y = 1.5}, {}},
    {"rock-big", {x = -4.5, y = 3.78}, {}},
    {"stone-wall", {x = -4.5, y = 2.5}, {}},
    {"gate", {x = 6.5, y = 3.5}, {}},
    {"gate", {x = 6.5, y = 2.5}, {}},
    {"stone-wall", {x = -4.5, y = 5.5}, {}},
    {"rock-big", {x = 0.05, y = 6.39}, {}},
    {"stone-wall", {x = 1.5, y = 5.5}, {}},
    {"rock-big", {x = 4.04, y = 4.91}, {}},
    {"stone-wall", {x = 2.5, y = 5.5}, {}},
    {"stone-wall", {x = 5.5, y = 5.5}, {}},
    {"stone-wall", {x = 6.5, y = 5.5}, {}},
    {"stone-wall", {x = 6.5, y = 4.5}, {}},
    {"stone-wall", {x = -4.5, y = 6.5}, {}},
    {"stone-wall", {x = -2.5, y = 6.5}, {}},
    {"stone-wall", {x = -3.5, y = 6.5}, {}},
    {"stone-wall", {x = -1.5, y = 6.5}, {}},
    {"stone-wall", {x = 1.5, y = 6.5}, {}},
  },
}
