return
{
  entities =
  {
    {"dead-tree-desert", {x = -13.84, y = -13.62}, {}},
    {"dry-tree", {x = -0.66, y = -13.42}, {}},
    {"tree-09-brown", {x = 12.8, y = -14.61}, {}},
    {"dry-tree", {x = 14.8, y = -15.09}, {}},
    {"tree-06", {x = -6.94, y = -12.66}, {}},
    {"tree-02-red", {x = -2.07, y = -12.87}, {}},
    {"tree-07", {x = 4.1, y = -12.59}, {}},
    {"tree-04", {x = 7.8, y = -13.19}, {}},
    {"dry-tree", {x = 13.36, y = -12.58}, {}},
    {"dry-tree", {x = -13.3, y = -10.1}, {}},
    {"dead-grey-trunk", {x = -9.22, y = -10.92}, {}},
    {"tree-02-red", {x = -1.99, y = -10.65}, {}},
    {"dry-tree", {x = -3.17, y = -9.81}, {}},
    {"tree-01", {x = 2.88, y = -10.19}, {}},
    {"tree-04", {x = 5.68, y = -10.78}, {}},
    {"dead-grey-trunk", {x = 14.29, y = -9.61}, {}},
    {"tree-09-red", {x = -6, y = -8.36}, {}},
    {"tree-02", {x = 0.59, y = -8.28}, {}},
    {"tree-03", {x = 8.71, y = -7.83}, {}},
    {"dry-tree", {x = -10.84, y = -7.05}, {}},
    {"dry-tree", {x = -6.68, y = -5.26}, {}},
    {"tree-08", {x = -0.48, y = -6.14}, {}},
    {"tree-07", {x = 2.84, y = -7.34}, {}},
    {"tree-03", {x = 10.07, y = -6.87}, {}},
    {"tree-06", {x = 10.87, y = -6.14}, {}},
    {"tree-08", {x = 12.11, y = -7.04}, {}},
    {"tree-09-brown", {x = -9.5, y = -4.27}, {}},
    {"dry-tree", {x = -6.01, y = -3.49}, {}},
    {"tree-07", {x = -4.31, y = -3.72}, {}},
    {"tree-01", {x = -0.04, y = -4.84}, {}},
    {"tree-03", {x = 3.33, y = -4.41}, {}},
    {"tree-02", {x = 11.14, y = -5.34}, {}},
    {"tree-06", {x = -14.07, y = -2.21}, {}},
    {"tree-02-red", {x = -8.65, y = -2.24}, {}},
    {"tree-02", {x = -1.99, y = -2.37}, {}},
    {"dead-dry-hairy-tree", {x = 14.49, y = -2.4}, {}},
    {"dry-tree", {x = -11.57, y = -0.31}, {}},
    {"dead-dry-hairy-tree", {x = -8.79, y = -0.15}, {}},
    {"tree-02-red", {x = -7.52, y = -1.21}, {}},
    {"tree-01", {x = -5.02, y = -0.91}, {}},
    {"tree-03", {x = -3.24, y = -0.75}, {}},
    {"tree-04", {x = -0.12, y = 0.04}, {}},
    {"tree-02", {x = 7.41, y = 0.13}, {}},
    {"tree-04", {x = 7.77, y = -1.58}, {}},
    {"tree-09-red", {x = 14.26, y = -0.24}, {}},
    {"dry-tree", {x = -14.14, y = 2.52}, {}},
    {"tree-08", {x = -11.04, y = 1.55}, {}},
    {"tree-03", {x = -3.95, y = 0.58}, {}},
    {"fish", {x = 2.3, y = 1.62}, {}},
    {"rock-big", {x = 5.87, y = 1.91}, {}},
    {"tree-06", {x = 10.13, y = 1.01}, {}},
    {"tree-09-brown", {x = -13.75, y = 3.7}, {}},
    {"tree-02", {x = -5.61, y = 3.72}, {}},
    {"tree-08", {x = -1.09, y = 2.49}, {}},
    {"tree-08", {x = 7.59, y = 3.89}, {}},
    {"dry-tree", {x = 7.65, y = 3.27}, {}},
    {"tree-01", {x = 9.36, y = 3.66}, {}},
    {"tree-02-red", {x = 12.2, y = 3.39}, {}},
    {"tree-01", {x = -8.47, y = 5.29}, {}},
    {"tree-03", {x = -6.75, y = 6.01}, {}},
    {"fish", {x = -1.75, y = 6.94}, {}},
    {"fish", {x = -1.75, y = 5.94}, {}},
    {"tree-07", {x = 2.93, y = 6.24}, {}},
    {"dead-dry-hairy-tree", {x = 9.27, y = 5.84}, {}},
    {"tree-02-red", {x = 10.79, y = 5.19}, {}},
    {"tree-02-red", {x = -12.98, y = 7.84}, {}},
    {"tree-07", {x = -9.75, y = 7.57}, {}},
    {"dry-tree", {x = -10.67, y = 7.68}, {}},
    {"tree-07", {x = -4.95, y = 7.21}, {}},
    {"tree-06", {x = 7.41, y = 8.06}, {}},
    {"tree-06", {x = -12.86, y = 9.38}, {}},
    {"tree-04", {x = 0.45, y = 9.86}, {}},
    {"tree-01", {x = 4.89, y = 10.11}, {}},
    {"dry-tree", {x = 7.59, y = 9.86}, {}},
    {"tree-09-red", {x = 12.37, y = 10.03}, {}},
    {"dry-tree", {x = 14.13, y = 9.5}, {}},
    {"tree-01", {x = -13.65, y = 12.1}, {}},
    {"tree-02", {x = -10.45, y = 12.21}, {}},
    {"tree-03", {x = -2.53, y = 11.56}, {}},
    {"tree-02-red", {x = 8.47, y = 11.26}, {}},
    {"tree-02", {x = -5.56, y = 14.39}, {}},
    {"tree-08", {x = -1.45, y = 13.94}, {}},
    {"tree-06", {x = 1.44, y = 12.89}, {}},
    {"dead-grey-trunk", {x = 11.46, y = 13.44}, {}},
    {"dead-dry-hairy-tree", {x = -2.61, y = 14.7}, {}},
    {"dry-tree", {x = 14.89, y = 15.09}, {}},
  },
  tiles =
  {
    {"dirt-4", {x = -16, y = 4}},
    {"grass-4", {x = -16, y = 5}},
    {"grass-4", {x = -16, y = 6}},
    {"dirt-4", {x = -15, y = 1}},
    {"dirt-4", {x = -15, y = 3}},
    {"dirt-4", {x = -15, y = 5}},
    {"dirt-4", {x = -15, y = 6}},
    {"grass-4", {x = -15, y = 9}},
    {"grass-4", {x = -15, y = 10}},
    {"grass-3", {x = -15, y = 11}},
    {"grass-4", {x = -15, y = 12}},
    {"grass-4", {x = -15, y = 13}},
    {"dirt-4", {x = -14, y = 0}},
    {"dirt-7", {x = -14, y = 1}},
    {"dirt-7", {x = -14, y = 2}},
    {"dirt-7", {x = -14, y = 3}},
    {"dirt-4", {x = -14, y = 4}},
    {"dirt-4", {x = -14, y = 5}},
    {"grass-4", {x = -14, y = 6}},
    {"grass-4", {x = -14, y = 7}},
    {"grass-4", {x = -14, y = 8}},
    {"grass-4", {x = -14, y = 9}},
    {"grass-4", {x = -14, y = 10}},
    {"grass-3", {x = -14, y = 11}},
    {"grass-3", {x = -14, y = 12}},
    {"grass-3", {x = -14, y = 13}},
    {"grass-4", {x = -14, y = 14}},
    {"dry-dirt", {x = -13, y = 0}},
    {"dirt-7", {x = -13, y = 1}},
    {"dirt-4", {x = -13, y = 2}},
    {"dirt-4", {x = -13, y = 3}},
    {"grass-4", {x = -13, y = 4}},
    {"grass-4", {x = -13, y = 5}},
    {"grass-4", {x = -13, y = 6}},
    {"grass-3", {x = -13, y = 7}},
    {"grass-3", {x = -13, y = 8}},
    {"grass-3", {x = -13, y = 9}},
    {"grass-3", {x = -13, y = 10}},
    {"grass-3", {x = -13, y = 11}},
    {"grass-3", {x = -13, y = 12}},
    {"grass-3", {x = -13, y = 13}},
    {"grass-4", {x = -13, y = 14}},
    {"grass-4", {x = -13, y = 15}},
    {"dry-dirt", {x = -12, y = -2}},
    {"dry-dirt", {x = -12, y = -1}},
    {"dirt-4", {x = -12, y = 0}},
    {"dirt-4", {x = -12, y = 1}},
    {"grass-4", {x = -12, y = 2}},
    {"grass-4", {x = -12, y = 3}},
    {"grass-4", {x = -12, y = 4}},
    {"grass-4", {x = -12, y = 5}},
    {"grass-3", {x = -12, y = 6}},
    {"grass-3", {x = -12, y = 7}},
    {"grass-3", {x = -12, y = 8}},
    {"grass-3", {x = -12, y = 9}},
    {"grass-1", {x = -12, y = 10}},
    {"grass-1", {x = -12, y = 11}},
    {"grass-3", {x = -12, y = 12}},
    {"grass-3", {x = -12, y = 13}},
    {"grass-3", {x = -12, y = 14}},
    {"grass-4", {x = -12, y = 15}},
    {"dry-dirt", {x = -11, y = -3}},
    {"dry-dirt", {x = -11, y = -2}},
    {"dry-dirt", {x = -11, y = -1}},
    {"grass-4", {x = -11, y = 0}},
    {"grass-4", {x = -11, y = 1}},
    {"grass-4", {x = -11, y = 2}},
    {"grass-4", {x = -11, y = 3}},
    {"grass-4", {x = -11, y = 4}},
    {"grass-4", {x = -11, y = 5}},
    {"grass-3", {x = -11, y = 6}},
    {"grass-3", {x = -11, y = 7}},
    {"grass-3", {x = -11, y = 8}},
    {"grass-1", {x = -11, y = 9}},
    {"grass-1", {x = -11, y = 10}},
    {"grass-1", {x = -11, y = 11}},
    {"grass-1", {x = -11, y = 12}},
    {"grass-3", {x = -11, y = 13}},
    {"grass-3", {x = -11, y = 14}},
    {"grass-4", {x = -11, y = 15}},
    {"dry-dirt", {x = -10, y = -3}},
    {"grass-4", {x = -10, y = -2}},
    {"grass-4", {x = -10, y = -1}},
    {"grass-4", {x = -10, y = 0}},
    {"grass-4", {x = -10, y = 1}},
    {"grass-4", {x = -10, y = 2}},
    {"grass-4", {x = -10, y = 3}},
    {"grass-4", {x = -10, y = 4}},
    {"grass-3", {x = -10, y = 5}},
    {"grass-3", {x = -10, y = 6}},
    {"grass-3", {x = -10, y = 7}},
    {"grass-1", {x = -10, y = 8}},
    {"grass-1", {x = -10, y = 9}},
    {"grass-2", {x = -10, y = 10}},
    {"grass-1", {x = -10, y = 11}},
    {"grass-1", {x = -10, y = 12}},
    {"grass-1", {x = -10, y = 13}},
    {"grass-3", {x = -10, y = 14}},
    {"grass-3", {x = -10, y = 15}},
    {"dry-dirt", {x = -9, y = -5}},
    {"dry-dirt", {x = -9, y = -4}},
    {"dry-dirt", {x = -9, y = -3}},
    {"dry-dirt", {x = -9, y = -2}},
    {"dry-dirt", {x = -9, y = -1}},
    {"grass-4", {x = -9, y = 0}},
    {"grass-4", {x = -9, y = 1}},
    {"grass-4", {x = -9, y = 2}},
    {"grass-4", {x = -9, y = 3}},
    {"grass-3", {x = -9, y = 4}},
    {"grass-3", {x = -9, y = 5}},
    {"grass-3", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-2", {x = -9, y = 9}},
    {"grass-2", {x = -9, y = 10}},
    {"water-mud", {x = -9, y = 11}},
    {"grass-1", {x = -9, y = 12}},
    {"grass-1", {x = -9, y = 13}},
    {"grass-3", {x = -9, y = 14}},
    {"grass-4", {x = -9, y = 15}},
    {"dry-dirt", {x = -8, y = -6}},
    {"dry-dirt", {x = -8, y = -5}},
    {"dry-dirt", {x = -8, y = -4}},
    {"dry-dirt", {x = -8, y = -3}},
    {"grass-4", {x = -8, y = -1}},
    {"grass-4", {x = -8, y = 0}},
    {"grass-4", {x = -8, y = 1}},
    {"grass-4", {x = -8, y = 2}},
    {"grass-4", {x = -8, y = 3}},
    {"grass-3", {x = -8, y = 4}},
    {"grass-3", {x = -8, y = 5}},
    {"grass-3", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-2", {x = -8, y = 8}},
    {"grass-2", {x = -8, y = 9}},
    {"water-shallow", {x = -8, y = 10}},
    {"water-mud", {x = -8, y = 11}},
    {"grass-1", {x = -8, y = 12}},
    {"grass-1", {x = -8, y = 13}},
    {"grass-3", {x = -8, y = 14}},
    {"grass-4", {x = -8, y = 15}},
    {"dry-dirt", {x = -7, y = -6}},
    {"dry-dirt", {x = -7, y = -5}},
    {"dry-dirt", {x = -7, y = -4}},
    {"dry-dirt", {x = -7, y = -3}},
    {"grass-4", {x = -7, y = -1}},
    {"grass-4", {x = -7, y = 0}},
    {"grass-4", {x = -7, y = 1}},
    {"grass-3", {x = -7, y = 2}},
    {"grass-3", {x = -7, y = 3}},
    {"grass-3", {x = -7, y = 4}},
    {"grass-3", {x = -7, y = 5}},
    {"grass-1", {x = -7, y = 6}},
    {"grass-1", {x = -7, y = 7}},
    {"grass-2", {x = -7, y = 8}},
    {"grass-1", {x = -7, y = 9}},
    {"water-shallow", {x = -7, y = 10}},
    {"water-shallow", {x = -7, y = 11}},
    {"grass-1", {x = -7, y = 12}},
    {"grass-3", {x = -7, y = 13}},
    {"grass-3", {x = -7, y = 14}},
    {"grass-4", {x = -7, y = 15}},
    {"dry-dirt", {x = -6, y = -7}},
    {"dry-dirt", {x = -6, y = -6}},
    {"dry-dirt", {x = -6, y = -5}},
    {"dry-dirt", {x = -6, y = -4}},
    {"grass-4", {x = -6, y = -3}},
    {"grass-4", {x = -6, y = -2}},
    {"grass-4", {x = -6, y = -1}},
    {"grass-4", {x = -6, y = 0}},
    {"grass-3", {x = -6, y = 1}},
    {"grass-3", {x = -6, y = 2}},
    {"grass-3", {x = -6, y = 3}},
    {"grass-3", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -6, y = 6}},
    {"grass-1", {x = -6, y = 7}},
    {"grass-1", {x = -6, y = 8}},
    {"water-shallow", {x = -6, y = 9}},
    {"water-shallow", {x = -6, y = 10}},
    {"water-shallow", {x = -6, y = 11}},
    {"grass-1", {x = -6, y = 12}},
    {"grass-3", {x = -6, y = 13}},
    {"grass-4", {x = -6, y = 14}},
    {"grass-4", {x = -6, y = 15}},
    {"grass-4", {x = -5, y = -13}},
    {"dry-dirt", {x = -5, y = -11}},
    {"dry-dirt", {x = -5, y = -10}},
    {"dry-dirt", {x = -5, y = -9}},
    {"dry-dirt", {x = -5, y = -8}},
    {"dry-dirt", {x = -5, y = -7}},
    {"dry-dirt", {x = -5, y = -6}},
    {"dry-dirt", {x = -5, y = -5}},
    {"grass-4", {x = -5, y = -4}},
    {"grass-4", {x = -5, y = -3}},
    {"grass-4", {x = -5, y = -2}},
    {"grass-4", {x = -5, y = -1}},
    {"grass-3", {x = -5, y = 0}},
    {"grass-3", {x = -5, y = 1}},
    {"grass-3", {x = -5, y = 2}},
    {"grass-3", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -5, y = 6}},
    {"grass-1", {x = -5, y = 7}},
    {"water-shallow", {x = -5, y = 8}},
    {"water-shallow", {x = -5, y = 9}},
    {"water-shallow", {x = -5, y = 10}},
    {"water-shallow", {x = -5, y = 11}},
    {"grass-3", {x = -5, y = 12}},
    {"grass-3", {x = -5, y = 13}},
    {"grass-4", {x = -5, y = 14}},
    {"grass-4", {x = -4, y = -13}},
    {"dry-dirt", {x = -4, y = -12}},
    {"dry-dirt", {x = -4, y = -11}},
    {"dry-dirt", {x = -4, y = -10}},
    {"dry-dirt", {x = -4, y = -9}},
    {"grass-4", {x = -4, y = -7}},
    {"grass-4", {x = -4, y = -6}},
    {"grass-4", {x = -4, y = -5}},
    {"grass-4", {x = -4, y = -4}},
    {"grass-4", {x = -4, y = -3}},
    {"grass-4", {x = -4, y = -2}},
    {"grass-4", {x = -4, y = -1}},
    {"grass-3", {x = -4, y = 0}},
    {"grass-3", {x = -4, y = 1}},
    {"grass-3", {x = -4, y = 2}},
    {"grass-3", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-2", {x = -4, y = 5}},
    {"grass-1", {x = -4, y = 6}},
    {"water-shallow", {x = -4, y = 7}},
    {"water-shallow", {x = -4, y = 8}},
    {"water-shallow", {x = -4, y = 9}},
    {"water-mud", {x = -4, y = 10}},
    {"grass-1", {x = -4, y = 11}},
    {"grass-3", {x = -4, y = 12}},
    {"grass-3", {x = -4, y = 13}},
    {"grass-4", {x = -4, y = 14}},
    {"grass-4", {x = -4, y = 15}},
    {"grass-4", {x = -3, y = -13}},
    {"grass-4", {x = -3, y = -12}},
    {"grass-4", {x = -3, y = -11}},
    {"grass-4", {x = -3, y = -10}},
    {"grass-4", {x = -3, y = -9}},
    {"grass-4", {x = -3, y = -8}},
    {"grass-4", {x = -3, y = -7}},
    {"grass-4", {x = -3, y = -6}},
    {"grass-4", {x = -3, y = -5}},
    {"grass-4", {x = -3, y = -4}},
    {"grass-4", {x = -3, y = -3}},
    {"grass-3", {x = -3, y = -2}},
    {"grass-3", {x = -3, y = -1}},
    {"grass-3", {x = -3, y = 0}},
    {"grass-3", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"water-shallow", {x = -3, y = 5}},
    {"water-shallow", {x = -3, y = 6}},
    {"water-shallow", {x = -3, y = 7}},
    {"water-shallow", {x = -3, y = 8}},
    {"water-mud", {x = -3, y = 9}},
    {"grass-1", {x = -3, y = 10}},
    {"grass-1", {x = -3, y = 11}},
    {"grass-3", {x = -3, y = 12}},
    {"grass-4", {x = -3, y = 13}},
    {"grass-4", {x = -3, y = 14}},
    {"grass-4", {x = -2, y = -15}},
    {"grass-4", {x = -2, y = -14}},
    {"grass-4", {x = -2, y = -13}},
    {"grass-4", {x = -2, y = -12}},
    {"grass-4", {x = -2, y = -11}},
    {"grass-4", {x = -2, y = -10}},
    {"grass-4", {x = -2, y = -9}},
    {"grass-4", {x = -2, y = -8}},
    {"grass-4", {x = -2, y = -7}},
    {"grass-4", {x = -2, y = -6}},
    {"grass-4", {x = -2, y = -5}},
    {"grass-3", {x = -2, y = -4}},
    {"grass-3", {x = -2, y = -3}},
    {"grass-3", {x = -2, y = -2}},
    {"grass-3", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"water-shallow", {x = -2, y = 4}},
    {"water-shallow", {x = -2, y = 5}},
    {"water-shallow", {x = -2, y = 6}},
    {"water-shallow", {x = -2, y = 7}},
    {"water-mud", {x = -2, y = 8}},
    {"water-mud", {x = -2, y = 9}},
    {"grass-1", {x = -2, y = 10}},
    {"grass-3", {x = -2, y = 11}},
    {"grass-3", {x = -2, y = 12}},
    {"grass-4", {x = -2, y = 13}},
    {"grass-4", {x = -2, y = 14}},
    {"grass-4", {x = -1, y = -16}},
    {"grass-4", {x = -1, y = -15}},
    {"grass-4", {x = -1, y = -14}},
    {"grass-4", {x = -1, y = -13}},
    {"grass-4", {x = -1, y = -12}},
    {"grass-4", {x = -1, y = -11}},
    {"grass-4", {x = -1, y = -10}},
    {"grass-4", {x = -1, y = -9}},
    {"grass-4", {x = -1, y = -8}},
    {"grass-4", {x = -1, y = -7}},
    {"grass-3", {x = -1, y = -6}},
    {"grass-3", {x = -1, y = -5}},
    {"grass-3", {x = -1, y = -4}},
    {"grass-3", {x = -1, y = -3}},
    {"grass-3", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"water-shallow", {x = -1, y = 3}},
    {"water-shallow", {x = -1, y = 4}},
    {"water-shallow", {x = -1, y = 5}},
    {"water-shallow", {x = -1, y = 6}},
    {"water-mud", {x = -1, y = 7}},
    {"grass-1", {x = -1, y = 8}},
    {"grass-1", {x = -1, y = 9}},
    {"grass-3", {x = -1, y = 10}},
    {"grass-3", {x = -1, y = 11}},
    {"grass-4", {x = -1, y = 12}},
    {"grass-4", {x = -1, y = 13}},
    {"grass-4", {x = -1, y = 14}},
    {"grass-4", {x = 0, y = -15}},
    {"grass-4", {x = 0, y = -14}},
    {"grass-4", {x = 0, y = -13}},
    {"grass-4", {x = 0, y = -12}},
    {"grass-4", {x = 0, y = -11}},
    {"grass-4", {x = 0, y = -10}},
    {"grass-4", {x = 0, y = -9}},
    {"grass-3", {x = 0, y = -8}},
    {"grass-3", {x = 0, y = -7}},
    {"grass-3", {x = 0, y = -6}},
    {"grass-3", {x = 0, y = -5}},
    {"grass-3", {x = 0, y = -4}},
    {"grass-3", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-2", {x = 0, y = 0}},
    {"grass-2", {x = 0, y = 1}},
    {"water-shallow", {x = 0, y = 2}},
    {"water-shallow", {x = 0, y = 3}},
    {"water-shallow", {x = 0, y = 4}},
    {"water-mud", {x = 0, y = 5}},
    {"water-mud", {x = 0, y = 6}},
    {"water-mud", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-1", {x = 0, y = 9}},
    {"grass-3", {x = 0, y = 10}},
    {"grass-4", {x = 0, y = 11}},
    {"grass-4", {x = 0, y = 12}},
    {"grass-4", {x = 0, y = 13}},
    {"grass-4", {x = 0, y = 14}},
    {"grass-4", {x = 1, y = -16}},
    {"grass-4", {x = 1, y = -15}},
    {"grass-4", {x = 1, y = -14}},
    {"grass-4", {x = 1, y = -13}},
    {"grass-3", {x = 1, y = -12}},
    {"grass-3", {x = 1, y = -11}},
    {"grass-3", {x = 1, y = -10}},
    {"grass-3", {x = 1, y = -9}},
    {"grass-3", {x = 1, y = -8}},
    {"grass-3", {x = 1, y = -7}},
    {"grass-3", {x = 1, y = -6}},
    {"grass-3", {x = 1, y = -5}},
    {"grass-3", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"water-shallow", {x = 1, y = -2}},
    {"water-shallow", {x = 1, y = -1}},
    {"water-shallow", {x = 1, y = 0}},
    {"water-shallow", {x = 1, y = 1}},
    {"water-shallow", {x = 1, y = 2}},
    {"water-mud", {x = 1, y = 3}},
    {"water-shallow", {x = 1, y = 4}},
    {"water-mud", {x = 1, y = 5}},
    {"water-mud", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-3", {x = 1, y = 9}},
    {"grass-3", {x = 1, y = 10}},
    {"grass-4", {x = 1, y = 11}},
    {"grass-4", {x = 1, y = 12}},
    {"grass-4", {x = 1, y = 13}},
    {"grass-4", {x = 1, y = 14}},
    {"grass-4", {x = 2, y = -16}},
    {"grass-4", {x = 2, y = -15}},
    {"grass-3", {x = 2, y = -14}},
    {"grass-3", {x = 2, y = -13}},
    {"grass-3", {x = 2, y = -12}},
    {"grass-3", {x = 2, y = -11}},
    {"grass-3", {x = 2, y = -10}},
    {"grass-3", {x = 2, y = -9}},
    {"grass-3", {x = 2, y = -8}},
    {"grass-3", {x = 2, y = -7}},
    {"grass-3", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"water-shallow", {x = 2, y = -3}},
    {"water-shallow", {x = 2, y = -2}},
    {"water-shallow", {x = 2, y = -1}},
    {"water-shallow", {x = 2, y = 0}},
    {"water-mud", {x = 2, y = 1}},
    {"water-mud", {x = 2, y = 2}},
    {"water-mud", {x = 2, y = 3}},
    {"water-mud", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-1", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-3", {x = 2, y = 9}},
    {"grass-4", {x = 2, y = 10}},
    {"grass-4", {x = 2, y = 11}},
    {"grass-4", {x = 2, y = 12}},
    {"grass-4", {x = 2, y = 13}},
    {"grass-4", {x = 3, y = -16}},
    {"grass-3", {x = 3, y = -15}},
    {"grass-3", {x = 3, y = -14}},
    {"grass-3", {x = 3, y = -13}},
    {"grass-3", {x = 3, y = -12}},
    {"grass-3", {x = 3, y = -11}},
    {"grass-1", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-2", {x = 3, y = -6}},
    {"grass-2", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"water-shallow", {x = 3, y = -3}},
    {"water-shallow", {x = 3, y = -2}},
    {"water-shallow", {x = 3, y = -1}},
    {"water-shallow", {x = 3, y = 0}},
    {"water-mud", {x = 3, y = 1}},
    {"water-mud", {x = 3, y = 2}},
    {"water-mud", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 3, y = 6}},
    {"grass-1", {x = 3, y = 7}},
    {"grass-3", {x = 3, y = 8}},
    {"grass-3", {x = 3, y = 9}},
    {"grass-4", {x = 3, y = 10}},
    {"grass-4", {x = 3, y = 11}},
    {"grass-4", {x = 3, y = 12}},
    {"grass-3", {x = 4, y = -16}},
    {"grass-4", {x = 4, y = -15}},
    {"grass-3", {x = 4, y = -14}},
    {"grass-3", {x = 4, y = -13}},
    {"grass-1", {x = 4, y = -12}},
    {"grass-1", {x = 4, y = -11}},
    {"grass-1", {x = 4, y = -10}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"water-shallow", {x = 4, y = -4}},
    {"water-shallow", {x = 4, y = -3}},
    {"water-shallow", {x = 4, y = -2}},
    {"water-shallow", {x = 4, y = -1}},
    {"water-mud", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-3", {x = 4, y = 6}},
    {"grass-3", {x = 4, y = 7}},
    {"grass-3", {x = 4, y = 8}},
    {"grass-4", {x = 4, y = 9}},
    {"grass-4", {x = 4, y = 10}},
    {"grass-4", {x = 4, y = 11}},
    {"grass-3", {x = 5, y = -16}},
    {"grass-3", {x = 5, y = -15}},
    {"grass-3", {x = 5, y = -14}},
    {"grass-1", {x = 5, y = -13}},
    {"grass-1", {x = 5, y = -12}},
    {"grass-1", {x = 5, y = -11}},
    {"grass-2", {x = 5, y = -10}},
    {"grass-2", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"water-shallow", {x = 5, y = -7}},
    {"water-shallow", {x = 5, y = -6}},
    {"water-shallow", {x = 5, y = -5}},
    {"water-shallow", {x = 5, y = -4}},
    {"water-shallow", {x = 5, y = -3}},
    {"water-mud", {x = 5, y = -2}},
    {"water-mud", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-3", {x = 5, y = 4}},
    {"grass-3", {x = 5, y = 5}},
    {"grass-3", {x = 5, y = 6}},
    {"grass-4", {x = 5, y = 7}},
    {"grass-4", {x = 5, y = 8}},
    {"grass-4", {x = 5, y = 9}},
    {"grass-4", {x = 5, y = 10}},
    {"grass-3", {x = 6, y = -16}},
    {"grass-3", {x = 6, y = -15}},
    {"grass-1", {x = 6, y = -14}},
    {"grass-1", {x = 6, y = -13}},
    {"grass-1", {x = 6, y = -12}},
    {"grass-1", {x = 6, y = -11}},
    {"grass-1", {x = 6, y = -10}},
    {"water-shallow", {x = 6, y = -9}},
    {"water-shallow", {x = 6, y = -8}},
    {"water-shallow", {x = 6, y = -7}},
    {"water-shallow", {x = 6, y = -6}},
    {"water-shallow", {x = 6, y = -5}},
    {"water-shallow", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-3", {x = 6, y = 1}},
    {"grass-3", {x = 6, y = 2}},
    {"grass-3", {x = 6, y = 3}},
    {"grass-4", {x = 6, y = 4}},
    {"grass-3", {x = 6, y = 5}},
    {"grass-3", {x = 6, y = 6}},
    {"grass-4", {x = 6, y = 7}},
    {"grass-4", {x = 6, y = 8}},
    {"grass-4", {x = 6, y = 9}},
    {"grass-3", {x = 7, y = -16}},
    {"grass-3", {x = 7, y = -15}},
    {"grass-3", {x = 7, y = -14}},
    {"grass-1", {x = 7, y = -13}},
    {"grass-1", {x = 7, y = -12}},
    {"water-mud", {x = 7, y = -11}},
    {"water-mud", {x = 7, y = -10}},
    {"water-shallow", {x = 7, y = -9}},
    {"water-shallow", {x = 7, y = -8}},
    {"water-shallow", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-3", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-3", {x = 7, y = 0}},
    {"grass-3", {x = 7, y = 1}},
    {"grass-4", {x = 7, y = 2}},
    {"grass-4", {x = 7, y = 3}},
    {"grass-3", {x = 7, y = 4}},
    {"grass-4", {x = 7, y = 5}},
    {"grass-4", {x = 7, y = 6}},
    {"grass-4", {x = 7, y = 7}},
    {"grass-4", {x = 7, y = 8}},
    {"grass-4", {x = 7, y = 9}},
    {"grass-4", {x = 7, y = 10}},
    {"grass-4", {x = 7, y = 11}},
    {"grass-4", {x = 7, y = 12}},
    {"grass-4", {x = 7, y = 13}},
    {"grass-3", {x = 8, y = -16}},
    {"grass-3", {x = 8, y = -15}},
    {"grass-3", {x = 8, y = -14}},
    {"grass-3", {x = 8, y = -13}},
    {"grass-1", {x = 8, y = -12}},
    {"grass-1", {x = 8, y = -11}},
    {"water-mud", {x = 8, y = -10}},
    {"grass-3", {x = 8, y = -9}},
    {"grass-3", {x = 8, y = -8}},
    {"grass-1", {x = 8, y = -7}},
    {"grass-1", {x = 8, y = -6}},
    {"grass-1", {x = 8, y = -5}},
    {"grass-3", {x = 8, y = -4}},
    {"grass-3", {x = 8, y = -3}},
    {"grass-3", {x = 8, y = -2}},
    {"grass-3", {x = 8, y = -1}},
    {"grass-3", {x = 8, y = 0}},
    {"grass-4", {x = 8, y = 1}},
    {"grass-4", {x = 8, y = 2}},
    {"grass-4", {x = 8, y = 3}},
    {"grass-4", {x = 8, y = 4}},
    {"grass-4", {x = 8, y = 5}},
    {"grass-4", {x = 8, y = 6}},
    {"grass-4", {x = 8, y = 7}},
    {"grass-4", {x = 8, y = 8}},
    {"grass-4", {x = 8, y = 9}},
    {"grass-4", {x = 8, y = 10}},
    {"grass-4", {x = 8, y = 11}},
    {"grass-4", {x = 9, y = -16}},
    {"grass-3", {x = 9, y = -15}},
    {"grass-3", {x = 9, y = -14}},
    {"grass-3", {x = 9, y = -13}},
    {"grass-1", {x = 9, y = -12}},
    {"grass-1", {x = 9, y = -11}},
    {"grass-1", {x = 9, y = -10}},
    {"grass-1", {x = 9, y = -9}},
    {"grass-3", {x = 9, y = -8}},
    {"grass-3", {x = 9, y = -7}},
    {"grass-3", {x = 9, y = -6}},
    {"grass-3", {x = 9, y = -5}},
    {"grass-3", {x = 9, y = -4}},
    {"grass-3", {x = 9, y = -3}},
    {"grass-3", {x = 9, y = -2}},
    {"grass-3", {x = 9, y = -1}},
    {"grass-4", {x = 9, y = 0}},
    {"grass-4", {x = 9, y = 1}},
    {"grass-4", {x = 9, y = 2}},
    {"grass-4", {x = 9, y = 3}},
    {"grass-4", {x = 9, y = 4}},
    {"dirt-7", {x = 9, y = 5}},
    {"dirt-7", {x = 9, y = 6}},
    {"grass-4", {x = 9, y = 8}},
    {"grass-4", {x = 10, y = -15}},
    {"grass-4", {x = 10, y = -14}},
    {"grass-3", {x = 10, y = -13}},
    {"grass-4", {x = 10, y = -12}},
    {"grass-4", {x = 10, y = -11}},
    {"grass-4", {x = 10, y = -10}},
    {"grass-4", {x = 10, y = -9}},
    {"grass-4", {x = 10, y = -8}},
    {"grass-4", {x = 10, y = -7}},
    {"grass-3", {x = 10, y = -6}},
    {"grass-3", {x = 10, y = -5}},
    {"grass-3", {x = 10, y = -4}},
    {"grass-4", {x = 10, y = -3}},
    {"grass-4", {x = 10, y = -2}},
    {"grass-4", {x = 10, y = -1}},
    {"grass-4", {x = 10, y = 0}},
    {"grass-4", {x = 10, y = 1}},
    {"grass-4", {x = 10, y = 2}},
    {"grass-4", {x = 10, y = 3}},
    {"grass-4", {x = 10, y = 4}},
    {"grass-4", {x = 10, y = 8}},
    {"grass-4", {x = 11, y = -13}},
    {"grass-4", {x = 11, y = -12}},
    {"grass-4", {x = 11, y = -11}},
    {"grass-4", {x = 11, y = -10}},
    {"grass-4", {x = 11, y = -9}},
    {"grass-4", {x = 11, y = -8}},
    {"grass-4", {x = 11, y = -7}},
    {"grass-4", {x = 11, y = -6}},
    {"grass-4", {x = 11, y = -5}},
    {"grass-4", {x = 11, y = -4}},
    {"grass-4", {x = 11, y = -3}},
    {"grass-4", {x = 11, y = -2}},
    {"grass-4", {x = 11, y = -1}},
    {"grass-4", {x = 11, y = 0}},
    {"grass-4", {x = 11, y = 1}},
    {"grass-4", {x = 11, y = 2}},
    {"grass-4", {x = 11, y = 3}},
    {"dirt-7", {x = 11, y = 4}},
    {"dirt-7", {x = 11, y = 5}},
    {"grass-4", {x = 12, y = -8}},
    {"grass-4", {x = 12, y = -7}},
    {"grass-4", {x = 12, y = -6}},
    {"dry-dirt", {x = 12, y = -4}},
    {"dry-dirt", {x = 12, y = -3}},
    {"dry-dirt", {x = 12, y = -2}},
    {"grass-4", {x = 12, y = 0}},
    {"dirt-7", {x = 12, y = 2}},
    {"dirt-7", {x = 12, y = 3}},
    {"dirt-7", {x = 12, y = 4}},
    {"dirt-7", {x = 12, y = 5}},
    {"grass-4", {x = 13, y = -6}},
    {"grass-4", {x = 13, y = -5}},
    {"grass-4", {x = 13, y = 0}},
    {"grass-4", {x = 14, y = -6}},
    {"grass-4", {x = 15, y = -7}},
  },
  decoratives =
  {
    {"red-asterisk", {x = -10, y = -15}, 4},
    {"brown-hairy-grass", {x = -7, y = -15}, 1},
    {"brown-asterisk", {x = -4, y = -15}, 3},
    {"brown-hairy-grass", {x = -3, y = -15}, 1},
    {"brown-asterisk", {x = 1, y = -16}, 1},
    {"rock-small", {x = 0, y = -15}, 1},
    {"brown-hairy-grass", {x = 1, y = -15}, 1},
    {"brown-hairy-grass", {x = 2, y = -16}, 1},
    {"brown-hairy-grass", {x = 2, y = -15}, 5},
    {"green-carpet-grass", {x = 4, y = -15}, 1},
    {"green-asterisk-mini", {x = 4, y = -15}, 3},
    {"green-small-grass", {x = 6, y = -15}, 3},
    {"green-carpet-grass", {x = 7, y = -15}, 7},
    {"green-hairy-grass", {x = 8, y = -15}, 2},
    {"brown-asterisk-mini", {x = 8, y = -15}, 4},
    {"green-desert-bush", {x = 8, y = -15}, 1},
    {"brown-fluff", {x = 9, y = -15}, 6},
    {"brown-hairy-grass", {x = 10, y = -16}, 1},
    {"brown-hairy-grass", {x = 10, y = -15}, 1},
    {"brown-hairy-grass", {x = 11, y = -15}, 1},
    {"brown-asterisk", {x = -9, y = -13}, 1},
    {"brown-hairy-grass", {x = -7, y = -14}, 2},
    {"brown-hairy-grass", {x = -8, y = -13}, 2},
    {"brown-hairy-grass", {x = -7, y = -13}, 1},
    {"brown-asterisk", {x = -5, y = -14}, 3},
    {"rock-small", {x = -5, y = -13}, 1},
    {"brown-asterisk", {x = -4, y = -14}, 1},
    {"brown-hairy-grass", {x = -3, y = -14}, 4},
    {"brown-hairy-grass", {x = -4, y = -13}, 1},
    {"brown-asterisk", {x = -4, y = -13}, 1},
    {"brown-hairy-grass", {x = -3, y = -13}, 1},
    {"brown-hairy-grass", {x = -1, y = -13}, 2},
    {"red-pita", {x = -1, y = -13}, 2},
    {"green-desert-bush", {x = -1, y = -13}, 4},
    {"brown-hairy-grass", {x = 1, y = -14}, 2},
    {"brown-asterisk-mini", {x = 2, y = -14}, 2},
    {"brown-fluff", {x = 2, y = -14}, 3},
    {"muddy-stump", {x = 3, y = -14}, 1},
    {"green-carpet-grass", {x = 2, y = -13}, 1},
    {"brown-asterisk-mini", {x = 2, y = -13}, 2},
    {"green-pita-mini", {x = 2, y = -13}, 4},
    {"green-carpet-grass", {x = 3, y = -13}, 3},
    {"green-carpet-grass", {x = 4, y = -14}, 6},
    {"green-carpet-grass", {x = 5, y = -14}, 1},
    {"green-asterisk-mini", {x = 4, y = -13}, 1},
    {"green-small-grass", {x = 5, y = -13}, 5},
    {"green-asterisk-mini", {x = 5, y = -13}, 2},
    {"green-small-grass", {x = 6, y = -14}, 4},
    {"green-asterisk-mini", {x = 6, y = -13}, 2},
    {"green-asterisk-mini", {x = 7, y = -13}, 2},
    {"green-hairy-grass", {x = 8, y = -14}, 4},
    {"brown-asterisk-mini", {x = 8, y = -14}, 2},
    {"green-desert-bush", {x = 8, y = -14}, 1},
    {"brown-asterisk-mini", {x = 9, y = -14}, 1},
    {"green-pita-mini", {x = 9, y = -14}, 5},
    {"green-hairy-grass", {x = 8, y = -13}, 7},
    {"red-pita", {x = 10, y = -14}, 3},
    {"green-pita-mini", {x = 10, y = -14}, 1},
    {"brown-fluff", {x = 10, y = -14}, 1},
    {"brown-hairy-grass", {x = 11, y = -14}, 1},
    {"green-pita-mini", {x = 10, y = -13}, 1},
    {"brown-hairy-grass", {x = 11, y = -13}, 2},
    {"brown-fluff", {x = 14, y = -14}, 2},
    {"red-pita", {x = -12, y = -12}, 2},
    {"brown-hairy-grass", {x = -12, y = -11}, 2},
    {"brown-hairy-grass", {x = -9, y = -11}, 1},
    {"rock-small", {x = -9, y = -11}, 2},
    {"brown-hairy-grass", {x = -8, y = -12}, 2},
    {"brown-hairy-grass", {x = -7, y = -12}, 1},
    {"brown-hairy-grass", {x = -8, y = -11}, 3},
    {"brown-hairy-grass", {x = -5, y = -12}, 1},
    {"brown-asterisk-mini", {x = -5, y = -12}, 1},
    {"brown-hairy-grass", {x = -6, y = -11}, 5},
    {"brown-hairy-grass", {x = -5, y = -11}, 1},
    {"brown-asterisk-mini", {x = -4, y = -12}, 2},
    {"brown-asterisk-mini", {x = -3, y = -12}, 3},
    {"brown-asterisk-mini", {x = -3, y = -11}, 2},
    {"brown-hairy-grass", {x = -2, y = -12}, 2},
    {"brown-asterisk-mini", {x = -2, y = -12}, 4},
    {"brown-hairy-grass", {x = -1, y = -12}, 3},
    {"brown-asterisk-mini", {x = -1, y = -12}, 4},
    {"green-desert-bush", {x = -1, y = -12}, 1},
    {"brown-hairy-grass", {x = -2, y = -11}, 2},
    {"brown-asterisk-mini", {x = -2, y = -11}, 1},
    {"brown-asterisk", {x = -2, y = -11}, 3},
    {"brown-hairy-grass", {x = -1, y = -11}, 2},
    {"green-small-grass", {x = 0, y = -12}, 1},
    {"brown-asterisk-mini", {x = 0, y = -12}, 1},
    {"brown-asterisk-mini", {x = 1, y = -12}, 1},
    {"green-pita-mini", {x = 1, y = -12}, 2},
    {"brown-asterisk-mini", {x = 0, y = -11}, 1},
    {"brown-asterisk-mini", {x = 1, y = -11}, 5},
    {"brown-asterisk-mini", {x = 2, y = -12}, 1},
    {"green-small-grass", {x = 3, y = -11}, 3},
    {"green-asterisk-mini", {x = 3, y = -11}, 1},
    {"green-small-grass", {x = 4, y = -12}, 2},
    {"green-asterisk-mini", {x = 4, y = -12}, 2},
    {"green-desert-bush", {x = 5, y = -12}, 3},
    {"green-asterisk-mini", {x = 4, y = -11}, 3},
    {"green-carpet-grass", {x = 6, y = -12}, 1},
    {"green-small-grass", {x = 6, y = -12}, 1},
    {"green-desert-bush", {x = 6, y = -12}, 1},
    {"green-carpet-grass", {x = 7, y = -12}, 1},
    {"green-desert-bush", {x = 7, y = -12}, 1},
    {"green-hairy-grass", {x = 7, y = -11}, 2},
    {"green-hairy-grass", {x = 8, y = -12}, 7},
    {"green-desert-bush", {x = 8, y = -12}, 1},
    {"green-hairy-grass", {x = 9, y = -12}, 3},
    {"green-desert-bush", {x = 9, y = -12}, 2},
    {"green-hairy-grass", {x = 8, y = -11}, 3},
    {"green-desert-bush", {x = 10, y = -12}, 2},
    {"brown-hairy-grass", {x = 11, y = -12}, 1},
    {"brown-asterisk-mini", {x = 11, y = -12}, 3},
    {"muddy-stump", {x = 10, y = -11}, 1},
    {"brown-asterisk-mini", {x = 11, y = -11}, 1},
    {"brown-hairy-grass", {x = 12, y = -12}, 1},
    {"brown-asterisk-mini", {x = 13, y = -12}, 1},
    {"brown-hairy-grass", {x = 12, y = -11}, 3},
    {"brown-fluff", {x = 12, y = -11}, 2},
    {"brown-asterisk-mini", {x = 13, y = -11}, 3},
    {"red-asterisk", {x = 14, y = -12}, 2},
    {"red-asterisk", {x = -14, y = -10}, 2},
    {"red-asterisk", {x = -13, y = -10}, 1},
    {"red-asterisk", {x = -14, y = -9}, 3},
    {"brown-fluff", {x = -14, y = -9}, 3},
    {"brown-fluff", {x = -13, y = -9}, 2},
    {"brown-hairy-grass", {x = -12, y = -10}, 3},
    {"red-asterisk", {x = -10, y = -10}, 2},
    {"brown-hairy-grass", {x = -9, y = -9}, 1},
    {"brown-hairy-grass", {x = -8, y = -10}, 1},
    {"brown-asterisk-mini", {x = -6, y = -9}, 1},
    {"brown-asterisk-mini", {x = -5, y = -9}, 1},
    {"brown-asterisk-mini", {x = -4, y = -10}, 2},
    {"brown-hairy-grass", {x = -3, y = -10}, 1},
    {"brown-hairy-grass", {x = -4, y = -9}, 2},
    {"brown-asterisk-mini", {x = -4, y = -9}, 3},
    {"brown-hairy-grass", {x = -3, y = -9}, 1},
    {"brown-asterisk-mini", {x = -3, y = -9}, 2},
    {"brown-hairy-grass", {x = -2, y = -10}, 1},
    {"green-pita-mini", {x = -1, y = -10}, 1},
    {"brown-asterisk-mini", {x = -1, y = -9}, 1},
    {"green-pita-mini", {x = -1, y = -9}, 5},
    {"brown-asterisk-mini", {x = 0, y = -10}, 3},
    {"green-carpet-grass", {x = 1, y = -9}, 3},
    {"green-small-grass", {x = 2, y = -10}, 4},
    {"green-croton", {x = 3, y = -10}, 1},
    {"muddy-stump", {x = 3, y = -9}, 1},
    {"green-croton", {x = 3, y = -9}, 3},
    {"green-croton", {x = 4, y = -10}, 4},
    {"green-hairy-grass", {x = 5, y = -10}, 2},
    {"muddy-stump", {x = 4, y = -9}, 2},
    {"green-pita-mini", {x = 4, y = -9}, 6},
    {"green-hairy-grass", {x = 5, y = -9}, 3},
    {"green-hairy-grass", {x = 6, y = -10}, 1},
    {"green-hairy-grass", {x = 7, y = -10}, 4},
    {"green-hairy-grass", {x = 6, y = -9}, 4},
    {"green-hairy-grass", {x = 8, y = -10}, 1},
    {"green-small-grass", {x = 9, y = -10}, 2},
    {"green-hairy-grass", {x = 8, y = -9}, 1},
    {"green-small-grass", {x = 9, y = -9}, 3},
    {"brown-asterisk-mini", {x = 11, y = -10}, 1},
    {"green-asterisk-mini", {x = 10, y = -9}, 1},
    {"brown-asterisk-mini", {x = 11, y = -9}, 1},
    {"brown-hairy-grass", {x = 12, y = -10}, 4},
    {"brown-fluff", {x = 12, y = -10}, 2},
    {"brown-asterisk-mini", {x = 13, y = -10}, 5},
    {"brown-hairy-grass", {x = 12, y = -9}, 4},
    {"brown-fluff", {x = 12, y = -9}, 1},
    {"rock-small", {x = -13, y = -8}, 2},
    {"brown-hairy-grass", {x = -13, y = -7}, 4},
    {"brown-hairy-grass", {x = -10, y = -8}, 1},
    {"brown-hairy-grass", {x = -9, y = -8}, 1},
    {"brown-hairy-grass", {x = -10, y = -7}, 1},
    {"green-desert-bush", {x = -8, y = -8}, 1},
    {"brown-asterisk-mini", {x = -7, y = -8}, 1},
    {"brown-asterisk", {x = -7, y = -8}, 2},
    {"brown-fluff", {x = -7, y = -8}, 3},
    {"brown-asterisk", {x = -8, y = -7}, 3},
    {"green-desert-bush", {x = -8, y = -7}, 3},
    {"brown-asterisk-mini", {x = -7, y = -7}, 1},
    {"brown-asterisk", {x = -7, y = -7}, 1},
    {"brown-hairy-grass", {x = -6, y = -7}, 2},
    {"brown-hairy-grass", {x = -4, y = -8}, 3},
    {"brown-asterisk-mini", {x = -4, y = -8}, 4},
    {"green-small-grass", {x = -2, y = -8}, 4},
    {"brown-asterisk-mini", {x = -2, y = -8}, 1},
    {"green-small-grass", {x = -1, y = -8}, 4},
    {"brown-asterisk-mini", {x = -1, y = -8}, 1},
    {"brown-hairy-grass", {x = -2, y = -7}, 1},
    {"brown-asterisk-mini", {x = -2, y = -7}, 1},
    {"green-small-grass", {x = -1, y = -7}, 1},
    {"green-desert-bush", {x = 1, y = -8}, 2},
    {"green-asterisk-mini", {x = 3, y = -8}, 5},
    {"green-hairy-grass", {x = 2, y = -7}, 3},
    {"green-croton", {x = 2, y = -7}, 1},
    {"green-hairy-grass", {x = 3, y = -7}, 2},
    {"green-hairy-grass", {x = 5, y = -8}, 4},
    {"green-hairy-grass", {x = 4, y = -7}, 4},
    {"green-hairy-grass", {x = 5, y = -7}, 1},
    {"green-small-grass", {x = 6, y = -8}, 1},
    {"green-small-grass", {x = 7, y = -7}, 6},
    {"green-hairy-grass", {x = 8, y = -8}, 1},
    {"green-hairy-grass", {x = 8, y = -7}, 2},
    {"green-asterisk-mini", {x = 10, y = -8}, 4},
    {"brown-asterisk-mini", {x = 11, y = -8}, 1},
    {"green-carpet-grass", {x = 10, y = -7}, 2},
    {"brown-asterisk-mini", {x = 11, y = -7}, 1},
    {"brown-hairy-grass", {x = 12, y = -8}, 3},
    {"brown-asterisk-mini", {x = 12, y = -8}, 1},
    {"brown-hairy-grass", {x = 12, y = -7}, 1},
    {"brown-asterisk-mini", {x = 12, y = -7}, 2},
    {"brown-fluff", {x = 14, y = -7}, 1},
    {"red-asterisk", {x = -15, y = -6}, 2},
    {"red-asterisk", {x = -15, y = -5}, 5},
    {"green-desert-bush", {x = -14, y = -5}, 4},
    {"brown-hairy-grass", {x = -11, y = -6}, 2},
    {"brown-fluff", {x = -11, y = -5}, 2},
    {"brown-asterisk-mini", {x = -9, y = -6}, 2},
    {"brown-fluff", {x = -10, y = -5}, 1},
    {"brown-asterisk-mini", {x = -9, y = -5}, 2},
    {"brown-hairy-grass", {x = -7, y = -6}, 6},
    {"brown-hairy-grass", {x = -8, y = -5}, 1},
    {"brown-hairy-grass", {x = -7, y = -5}, 5},
    {"brown-hairy-grass", {x = -6, y = -6}, 4},
    {"brown-asterisk-mini", {x = -6, y = -5}, 1},
    {"brown-hairy-grass", {x = -3, y = -6}, 3},
    {"brown-asterisk-mini", {x = -3, y = -6}, 5},
    {"brown-hairy-grass", {x = -4, y = -5}, 2},
    {"green-carpet-grass", {x = -4, y = -5}, 1},
    {"brown-asterisk-mini", {x = -4, y = -5}, 1},
    {"brown-hairy-grass", {x = -3, y = -5}, 1},
    {"green-carpet-grass", {x = -1, y = -6}, 1},
    {"green-small-grass", {x = -1, y = -6}, 3},
    {"green-small-grass", {x = -2, y = -5}, 2},
    {"green-carpet-grass", {x = 0, y = -6}, 3},
    {"green-croton", {x = 0, y = -6}, 6},
    {"green-small-grass", {x = 0, y = -5}, 1},
    {"green-hairy-grass", {x = 1, y = -5}, 1},
    {"green-small-grass", {x = 1, y = -5}, 4},
    {"green-pita-mini", {x = 1, y = -5}, 1},
    {"green-hairy-grass", {x = 2, y = -6}, 1},
    {"green-small-grass", {x = 2, y = -5}, 1},
    {"green-hairy-grass", {x = 3, y = -5}, 2},
    {"green-hairy-grass", {x = 5, y = -6}, 3},
    {"green-hairy-grass", {x = 4, y = -5}, 3},
    {"green-hairy-grass", {x = 5, y = -5}, 1},
    {"green-small-grass", {x = 7, y = -6}, 3},
    {"green-hairy-grass", {x = 7, y = -5}, 1},
    {"green-hairy-grass", {x = 8, y = -6}, 1},
    {"green-small-grass", {x = 8, y = -6}, 1},
    {"green-carpet-grass", {x = 9, y = -6}, 3},
    {"green-hairy-grass", {x = 8, y = -5}, 1},
    {"green-small-grass", {x = 8, y = -5}, 3},
    {"green-asterisk-mini", {x = 9, y = -5}, 3},
    {"green-carpet-grass", {x = 10, y = -6}, 2},
    {"brown-asterisk-mini", {x = 10, y = -6}, 2},
    {"green-pita-mini", {x = 10, y = -6}, 2},
    {"brown-asterisk-mini", {x = 10, y = -5}, 2},
    {"green-pita-mini", {x = 10, y = -5}, 5},
    {"brown-asterisk-mini", {x = 12, y = -6}, 1},
    {"brown-asterisk-mini", {x = 13, y = -6}, 3},
    {"red-pita", {x = 13, y = -6}, 1},
    {"green-desert-bush", {x = 13, y = -6}, 2},
    {"brown-asterisk-mini", {x = 12, y = -5}, 1},
    {"brown-asterisk-mini", {x = 13, y = -5}, 1},
    {"green-desert-bush", {x = 13, y = -5}, 1},
    {"brown-fluff", {x = 14, y = -6}, 3},
    {"brown-fluff", {x = 14, y = -5}, 2},
    {"green-desert-bush", {x = 14, y = -5}, 2},
    {"green-desert-bush", {x = -14, y = -4}, 3},
    {"brown-asterisk", {x = -13, y = -3}, 3},
    {"brown-asterisk", {x = -12, y = -4}, 1},
    {"brown-asterisk-mini", {x = -11, y = -4}, 2},
    {"brown-asterisk", {x = -11, y = -4}, 1},
    {"brown-hairy-grass", {x = -12, y = -3}, 2},
    {"brown-asterisk-mini", {x = -12, y = -3}, 2},
    {"brown-asterisk", {x = -12, y = -3}, 1},
    {"brown-asterisk-mini", {x = -11, y = -3}, 1},
    {"brown-hairy-grass", {x = -9, y = -3}, 4},
    {"brown-hairy-grass", {x = -8, y = -4}, 5},
    {"brown-hairy-grass", {x = -7, y = -4}, 1},
    {"brown-asterisk-mini", {x = -7, y = -4}, 1},
    {"brown-hairy-grass", {x = -8, y = -3}, 2},
    {"brown-asterisk-mini", {x = -7, y = -3}, 2},
    {"brown-asterisk-mini", {x = -6, y = -4}, 1},
    {"brown-asterisk-mini", {x = -5, y = -4}, 3},
    {"brown-asterisk-mini", {x = -6, y = -3}, 2},
    {"brown-asterisk-mini", {x = -5, y = -3}, 2},
    {"brown-hairy-grass", {x = -4, y = -4}, 3},
    {"green-carpet-grass", {x = -4, y = -4}, 3},
    {"brown-asterisk-mini", {x = -4, y = -4}, 4},
    {"green-small-grass", {x = -3, y = -4}, 2},
    {"green-carpet-grass", {x = -4, y = -3}, 1},
    {"green-asterisk-mini", {x = -4, y = -3}, 1},
    {"green-small-grass", {x = -3, y = -3}, 1},
    {"green-asterisk-mini", {x = -1, y = -4}, 5},
    {"green-small-grass", {x = -2, y = -3}, 2},
    {"green-asterisk-mini", {x = -2, y = -3}, 1},
    {"green-hairy-grass", {x = -1, y = -3}, 4},
    {"muddy-stump", {x = -1, y = -3}, 1},
    {"green-asterisk-mini", {x = -1, y = -3}, 2},
    {"green-hairy-grass", {x = 0, y = -4}, 2},
    {"green-small-grass", {x = 0, y = -4}, 1},
    {"muddy-stump", {x = 0, y = -4}, 1},
    {"green-hairy-grass", {x = 1, y = -4}, 2},
    {"green-asterisk-mini", {x = 1, y = -4}, 1},
    {"green-pita-mini", {x = 1, y = -4}, 4},
    {"green-hairy-grass", {x = 1, y = -3}, 2},
    {"green-asterisk-mini", {x = 1, y = -3}, 3},
    {"green-hairy-grass", {x = 3, y = -4}, 5},
    {"green-hairy-grass", {x = 2, y = -3}, 3},
    {"green-hairy-grass", {x = 7, y = -4}, 2},
    {"green-hairy-grass", {x = 6, y = -3}, 1},
    {"green-hairy-grass", {x = 7, y = -3}, 3},
    {"green-pita-mini", {x = 7, y = -3}, 3},
    {"green-hairy-grass", {x = 8, y = -4}, 2},
    {"green-small-grass", {x = 8, y = -4}, 3},
    {"muddy-stump", {x = 8, y = -4}, 1},
    {"green-asterisk-mini", {x = 9, y = -4}, 3},
    {"brown-fluff", {x = 9, y = -4}, 5},
    {"muddy-stump", {x = 8, y = -3}, 1},
    {"brown-fluff", {x = 9, y = -3}, 1},
    {"green-small-grass", {x = 10, y = -4}, 1},
    {"brown-asterisk-mini", {x = 10, y = -4}, 1},
    {"rock-small", {x = 10, y = -4}, 1},
    {"green-small-grass", {x = 11, y = -4}, 1},
    {"green-small-grass", {x = 10, y = -3}, 2},
    {"brown-asterisk-mini", {x = 10, y = -3}, 1},
    {"brown-asterisk-mini", {x = 13, y = -4}, 1},
    {"green-desert-bush", {x = 13, y = -4}, 1},
    {"brown-asterisk-mini", {x = 12, y = -3}, 1},
    {"brown-asterisk-mini", {x = 13, y = -3}, 1},
    {"green-desert-bush", {x = 14, y = -4}, 1},
    {"brown-hairy-grass", {x = -15, y = -2}, 3},
    {"brown-hairy-grass", {x = -16, y = -1}, 2},
    {"brown-hairy-grass", {x = -15, y = -1}, 1},
    {"brown-asterisk-mini", {x = -13, y = -2}, 3},
    {"brown-asterisk", {x = -13, y = -2}, 3},
    {"brown-asterisk-mini", {x = -12, y = -2}, 1},
    {"brown-hairy-grass", {x = -12, y = -1}, 1},
    {"brown-hairy-grass", {x = -11, y = -1}, 2},
    {"brown-hairy-grass", {x = -10, y = -2}, 3},
    {"brown-asterisk-mini", {x = -10, y = -1}, 1},
    {"green-small-grass", {x = -8, y = -2}, 2},
    {"brown-asterisk-mini", {x = -8, y = -2}, 2},
    {"green-small-grass", {x = -7, y = -2}, 3},
    {"brown-asterisk-mini", {x = -7, y = -2}, 2},
    {"green-small-grass", {x = -8, y = -1}, 1},
    {"brown-asterisk-mini", {x = -8, y = -1}, 2},
    {"brown-hairy-grass", {x = -7, y = -1}, 2},
    {"brown-asterisk-mini", {x = -7, y = -1}, 1},
    {"brown-asterisk-mini", {x = -6, y = -2}, 1},
    {"brown-asterisk", {x = -6, y = -2}, 1},
    {"brown-asterisk", {x = -6, y = -1}, 4},
    {"green-small-grass", {x = -5, y = -1}, 1},
    {"green-small-grass", {x = -4, y = -2}, 4},
    {"green-asterisk-mini", {x = -4, y = -2}, 3},
    {"green-pita-mini", {x = -4, y = -2}, 2},
    {"green-asterisk-mini", {x = -3, y = -2}, 4},
    {"green-croton", {x = -3, y = -2}, 2},
    {"green-small-grass", {x = -4, y = -1}, 2},
    {"green-asterisk-mini", {x = -4, y = -1}, 1},
    {"green-pita-mini", {x = -4, y = -1}, 4},
    {"green-asterisk-mini", {x = -3, y = -1}, 4},
    {"green-croton", {x = -3, y = -1}, 4},
    {"green-small-grass", {x = -2, y = -2}, 2},
    {"green-hairy-grass", {x = -1, y = -2}, 1},
    {"green-asterisk-mini", {x = -1, y = -2}, 1},
    {"green-small-grass", {x = -2, y = -1}, 1},
    {"green-asterisk-mini", {x = -2, y = -1}, 1},
    {"green-hairy-grass", {x = -1, y = -1}, 3},
    {"green-asterisk-mini", {x = -1, y = -1}, 2},
    {"green-hairy-grass", {x = 0, y = -2}, 4},
    {"green-asterisk-mini", {x = 0, y = -2}, 2},
    {"green-hairy-grass", {x = 1, y = -2}, 2},
    {"green-hairy-grass", {x = 0, y = -1}, 6},
    {"rock-small", {x = 3, y = -2}, 1},
    {"green-hairy-grass", {x = 5, y = -1}, 3},
    {"green-hairy-grass", {x = 6, y = -2}, 4},
    {"green-hairy-grass", {x = 7, y = -2}, 2},
    {"green-pita-mini", {x = 7, y = -2}, 3},
    {"green-hairy-grass", {x = 6, y = -1}, 5},
    {"green-hairy-grass", {x = 7, y = -1}, 6},
    {"green-asterisk-mini", {x = 7, y = -1}, 1},
    {"green-asterisk-mini", {x = 9, y = -2}, 2},
    {"green-carpet-grass", {x = 8, y = -1}, 2},
    {"green-asterisk-mini", {x = 8, y = -1}, 2},
    {"green-asterisk-mini", {x = 9, y = -1}, 1},
    {"brown-asterisk-mini", {x = 10, y = -2}, 1},
    {"brown-asterisk", {x = 11, y = -2}, 2},
    {"brown-asterisk-mini", {x = 10, y = -1}, 2},
    {"brown-asterisk", {x = 11, y = -1}, 1},
    {"brown-asterisk-mini", {x = 12, y = -2}, 2},
    {"brown-asterisk-mini", {x = 12, y = -1}, 1},
    {"red-pita", {x = -14, y = 0}, 5},
    {"brown-hairy-grass", {x = -13, y = 1}, 3},
    {"brown-asterisk", {x = -12, y = 1}, 7},
    {"brown-asterisk", {x = -11, y = 1}, 1},
    {"brown-asterisk-mini", {x = -10, y = 0}, 3},
    {"brown-asterisk-mini", {x = -9, y = 0}, 2},
    {"green-carpet-grass", {x = -10, y = 1}, 3},
    {"brown-asterisk-mini", {x = -10, y = 1}, 1},
    {"brown-asterisk-mini", {x = -9, y = 1}, 2},
    {"brown-asterisk-mini", {x = -8, y = 0}, 2},
    {"brown-hairy-grass", {x = -7, y = 0}, 3},
    {"brown-hairy-grass", {x = -8, y = 1}, 2},
    {"brown-asterisk-mini", {x = -7, y = 1}, 2},
    {"green-asterisk-mini", {x = -7, y = 1}, 1},
    {"rock-small", {x = -7, y = 1}, 1},
    {"green-small-grass", {x = -6, y = 0}, 1},
    {"green-small-grass", {x = -5, y = 0}, 2},
    {"brown-asterisk-mini", {x = -6, y = 1}, 3},
    {"green-asterisk-mini", {x = -6, y = 1}, 3},
    {"green-croton", {x = -6, y = 1}, 3},
    {"green-small-grass", {x = -5, y = 1}, 1},
    {"green-asterisk-mini", {x = -5, y = 1}, 2},
    {"green-asterisk-mini", {x = -4, y = 0}, 2},
    {"green-hairy-grass", {x = -3, y = 0}, 2},
    {"green-small-grass", {x = -3, y = 0}, 2},
    {"green-croton", {x = -3, y = 0}, 2},
    {"green-hairy-grass", {x = -4, y = 1}, 1},
    {"green-hairy-grass", {x = -1, y = 0}, 2},
    {"green-pita-mini", {x = -1, y = 0}, 3},
    {"green-hairy-grass", {x = -1, y = 1}, 1},
    {"green-pita-mini", {x = -1, y = 1}, 2},
    {"green-hairy-grass", {x = 0, y = 0}, 2},
    {"green-hairy-grass", {x = 0, y = 1}, 3},
    {"green-hairy-grass", {x = 4, y = 0}, 6},
    {"green-hairy-grass", {x = 5, y = 0}, 1},
    {"green-hairy-grass", {x = 4, y = 1}, 6},
    {"green-hairy-grass", {x = 5, y = 1}, 2},
    {"green-carpet-grass", {x = 7, y = 0}, 3},
    {"green-small-grass", {x = 7, y = 0}, 4},
    {"green-asterisk-mini", {x = 7, y = 0}, 4},
    {"green-small-grass", {x = 7, y = 1}, 2},
    {"green-asterisk-mini", {x = 7, y = 1}, 3},
    {"green-carpet-grass", {x = 8, y = 0}, 1},
    {"green-asterisk-mini", {x = 8, y = 0}, 3},
    {"brown-asterisk-mini", {x = 9, y = 0}, 1},
    {"green-asterisk-mini", {x = 8, y = 1}, 1},
    {"brown-asterisk-mini", {x = 9, y = 1}, 1},
    {"rock-small", {x = 9, y = 1}, 1},
    {"brown-asterisk-mini", {x = 10, y = 0}, 2},
    {"brown-asterisk", {x = 11, y = 0}, 3},
    {"brown-asterisk-mini", {x = 10, y = 1}, 1},
    {"brown-asterisk-mini", {x = 11, y = 1}, 1},
    {"brown-asterisk-mini", {x = 12, y = 0}, 3},
    {"brown-fluff", {x = 12, y = 0}, 1},
    {"red-pita", {x = 13, y = 1}, 2},
    {"brown-hairy-grass", {x = -14, y = 2}, 2},
    {"brown-hairy-grass", {x = -13, y = 2}, 3},
    {"brown-hairy-grass", {x = -14, y = 3}, 2},
    {"brown-asterisk", {x = -13, y = 3}, 3},
    {"brown-asterisk-mini", {x = -12, y = 3}, 6},
    {"green-carpet-grass", {x = -10, y = 2}, 1},
    {"brown-asterisk-mini", {x = -10, y = 2}, 4},
    {"brown-hairy-grass", {x = -9, y = 2}, 3},
    {"brown-asterisk-mini", {x = -9, y = 2}, 2},
    {"brown-hairy-grass", {x = -9, y = 3}, 1},
    {"green-pita-mini", {x = -9, y = 3}, 2},
    {"rock-small", {x = -9, y = 3}, 1},
    {"green-small-grass", {x = -8, y = 3}, 3},
    {"green-small-grass", {x = -7, y = 3}, 2},
    {"green-asterisk-mini", {x = -7, y = 3}, 4},
    {"green-small-grass", {x = -6, y = 2}, 1},
    {"green-croton", {x = -6, y = 2}, 5},
    {"green-hairy-grass", {x = -5, y = 2}, 3},
    {"green-small-grass", {x = -5, y = 2}, 5},
    {"green-asterisk-mini", {x = -5, y = 2}, 1},
    {"green-hairy-grass", {x = -6, y = 3}, 4},
    {"green-small-grass", {x = -6, y = 3}, 2},
    {"green-asterisk-mini", {x = -6, y = 3}, 1},
    {"green-small-grass", {x = -5, y = 3}, 1},
    {"green-small-grass", {x = -3, y = 2}, 4},
    {"green-small-grass", {x = -4, y = 3}, 3},
    {"muddy-stump", {x = -4, y = 3}, 2},
    {"green-hairy-grass", {x = -3, y = 3}, 4},
    {"green-small-grass", {x = -3, y = 3}, 4},
    {"green-hairy-grass", {x = -2, y = 2}, 7},
    {"green-pita-mini", {x = -2, y = 2}, 2},
    {"green-hairy-grass", {x = -1, y = 2}, 6},
    {"green-hairy-grass", {x = -2, y = 3}, 7},
    {"green-hairy-grass", {x = -1, y = 3}, 2},
    {"green-hairy-grass", {x = 0, y = 2}, 2},
    {"green-hairy-grass", {x = 3, y = 3}, 1},
    {"green-hairy-grass", {x = 4, y = 2}, 5},
    {"green-hairy-grass", {x = 5, y = 2}, 1},
    {"green-hairy-grass", {x = 4, y = 3}, 3},
    {"green-pita-mini", {x = 4, y = 3}, 1},
    {"green-hairy-grass", {x = 5, y = 3}, 1},
    {"green-small-grass", {x = 5, y = 3}, 2},
    {"green-asterisk-mini", {x = 7, y = 2}, 2},
    {"green-small-grass", {x = 6, y = 3}, 3},
    {"green-asterisk-mini", {x = 7, y = 3}, 4},
    {"green-asterisk-mini", {x = 8, y = 2}, 3},
    {"brown-hairy-grass", {x = 9, y = 2}, 2},
    {"brown-asterisk-mini", {x = 9, y = 2}, 2},
    {"brown-asterisk-mini", {x = 8, y = 3}, 1},
    {"green-pita-mini", {x = 8, y = 3}, 4},
    {"brown-hairy-grass", {x = 9, y = 3}, 2},
    {"brown-asterisk-mini", {x = 9, y = 3}, 1},
    {"brown-asterisk-mini", {x = 10, y = 2}, 2},
    {"brown-asterisk-mini", {x = 11, y = 2}, 2},
    {"green-asterisk-mini", {x = 11, y = 2}, 2},
    {"brown-asterisk-mini", {x = 10, y = 3}, 1},
    {"brown-asterisk-mini", {x = 11, y = 3}, 1},
    {"green-asterisk-mini", {x = 11, y = 3}, 3},
    {"red-pita", {x = 13, y = 2}, 1},
    {"red-pita", {x = -15, y = 5}, 3},
    {"brown-asterisk", {x = -14, y = 4}, 2},
    {"brown-asterisk-mini", {x = -13, y = 4}, 1},
    {"brown-asterisk-mini", {x = -13, y = 5}, 1},
    {"brown-asterisk-mini", {x = -12, y = 4}, 1},
    {"brown-asterisk-mini", {x = -12, y = 5}, 3},
    {"green-carpet-grass", {x = -11, y = 5}, 1},
    {"green-croton", {x = -11, y = 5}, 1},
    {"green-pita-mini", {x = -11, y = 5}, 2},
    {"green-carpet-grass", {x = -10, y = 4}, 5},
    {"green-pita-mini", {x = -10, y = 4}, 4},
    {"green-small-grass", {x = -9, y = 4}, 1},
    {"green-small-grass", {x = -9, y = 5}, 1},
    {"green-small-grass", {x = -8, y = 4}, 1},
    {"green-small-grass", {x = -7, y = 4}, 1},
    {"green-small-grass", {x = -8, y = 5}, 4},
    {"green-asterisk-mini", {x = -8, y = 5}, 2},
    {"green-hairy-grass", {x = -7, y = 5}, 1},
    {"green-small-grass", {x = -7, y = 5}, 1},
    {"green-asterisk-mini", {x = -7, y = 5}, 2},
    {"green-hairy-grass", {x = -6, y = 4}, 1},
    {"green-small-grass", {x = -6, y = 4}, 2},
    {"green-small-grass", {x = -5, y = 4}, 1},
    {"green-hairy-grass", {x = -6, y = 5}, 3},
    {"green-hairy-grass", {x = -5, y = 5}, 2},
    {"green-pita-mini", {x = -5, y = 5}, 1},
    {"green-hairy-grass", {x = -4, y = 4}, 1},
    {"green-pita-mini", {x = -4, y = 4}, 1},
    {"green-hairy-grass", {x = -3, y = 4}, 3},
    {"green-pita-mini", {x = -3, y = 4}, 1},
    {"green-hairy-grass", {x = -4, y = 5}, 1},
    {"green-pita-mini", {x = -4, y = 5}, 3},
    {"green-hairy-grass", {x = -3, y = 5}, 2},
    {"green-hairy-grass", {x = -2, y = 4}, 2},
    {"green-pita-mini", {x = 3, y = 4}, 4},
    {"green-hairy-grass", {x = 2, y = 5}, 6},
    {"green-hairy-grass", {x = 4, y = 4}, 2},
    {"green-pita-mini", {x = 4, y = 4}, 2},
    {"green-small-grass", {x = 5, y = 4}, 4},
    {"green-hairy-grass", {x = 4, y = 5}, 2},
    {"green-asterisk-mini", {x = 4, y = 5}, 3},
    {"green-carpet-grass", {x = 5, y = 5}, 1},
    {"green-carpet-grass", {x = 6, y = 4}, 2},
    {"green-asterisk-mini", {x = 6, y = 4}, 2},
    {"brown-asterisk-mini", {x = 7, y = 4}, 1},
    {"green-carpet-grass", {x = 6, y = 5}, 1},
    {"green-small-grass", {x = 6, y = 5}, 1},
    {"green-asterisk-mini", {x = 6, y = 5}, 3},
    {"brown-asterisk-mini", {x = 7, y = 5}, 1},
    {"brown-asterisk-mini", {x = 8, y = 4}, 1},
    {"green-pita-mini", {x = 8, y = 4}, 1},
    {"brown-hairy-grass", {x = 9, y = 4}, 2},
    {"brown-hairy-grass", {x = 9, y = 5}, 1},
    {"brown-asterisk-mini", {x = 9, y = 5}, 1},
    {"brown-asterisk-mini", {x = 10, y = 4}, 1},
    {"brown-asterisk", {x = 11, y = 4}, 1},
    {"brown-hairy-grass", {x = 10, y = 5}, 1},
    {"brown-hairy-grass", {x = 11, y = 5}, 1},
    {"brown-asterisk", {x = 12, y = 4}, 3},
    {"red-pita", {x = 13, y = 5}, 1},
    {"red-pita", {x = -15, y = 6}, 2},
    {"brown-asterisk-mini", {x = -13, y = 6}, 3},
    {"brown-asterisk-mini", {x = -14, y = 7}, 2},
    {"brown-asterisk-mini", {x = -13, y = 7}, 2},
    {"brown-asterisk-mini", {x = -12, y = 6}, 1},
    {"green-croton", {x = -12, y = 6}, 1},
    {"green-croton", {x = -11, y = 6}, 1},
    {"green-carpet-grass", {x = -12, y = 7}, 1},
    {"green-asterisk-mini", {x = -11, y = 7}, 2},
    {"green-asterisk-mini", {x = -9, y = 6}, 3},
    {"green-croton", {x = -9, y = 6}, 4},
    {"green-small-grass", {x = -10, y = 7}, 2},
    {"green-asterisk-mini", {x = -10, y = 7}, 1},
    {"green-hairy-grass", {x = -9, y = 7}, 2},
    {"green-asterisk-mini", {x = -9, y = 7}, 1},
    {"green-asterisk-mini", {x = -8, y = 6}, 3},
    {"green-hairy-grass", {x = -7, y = 6}, 1},
    {"green-asterisk-mini", {x = -7, y = 6}, 1},
    {"green-hairy-grass", {x = -8, y = 7}, 2},
    {"muddy-stump", {x = -8, y = 7}, 1},
    {"green-hairy-grass", {x = -6, y = 6}, 1},
    {"green-asterisk-mini", {x = -6, y = 6}, 5},
    {"green-hairy-grass", {x = -5, y = 6}, 3},
    {"green-asterisk-mini", {x = -5, y = 6}, 1},
    {"green-pita-mini", {x = -5, y = 6}, 2},
    {"green-hairy-grass", {x = -6, y = 7}, 1},
    {"green-asterisk-mini", {x = -6, y = 7}, 2},
    {"green-hairy-grass", {x = -5, y = 7}, 1},
    {"green-asterisk-mini", {x = -5, y = 7}, 3},
    {"green-hairy-grass", {x = -4, y = 6}, 7},
    {"green-asterisk-mini", {x = -4, y = 6}, 1},
    {"green-hairy-grass", {x = -4, y = 7}, 1},
    {"rock-medium", {x = -1, y = 6}, 1},
    {"green-hairy-grass", {x = 1, y = 6}, 2},
    {"green-hairy-grass", {x = 1, y = 7}, 5},
    {"green-pita-mini", {x = 1, y = 7}, 2},
    {"green-hairy-grass", {x = 2, y = 6}, 1},
    {"green-asterisk-mini", {x = 3, y = 6}, 7},
    {"green-hairy-grass", {x = 2, y = 7}, 1},
    {"green-asterisk-mini", {x = 2, y = 7}, 2},
    {"muddy-stump", {x = 3, y = 7}, 1},
    {"green-asterisk-mini", {x = 3, y = 7}, 6},
    {"green-carpet-grass", {x = 4, y = 6}, 1},
    {"green-asterisk-mini", {x = 4, y = 6}, 3},
    {"green-carpet-grass", {x = 5, y = 6}, 1},
    {"green-asterisk-mini", {x = 5, y = 6}, 2},
    {"green-asterisk-mini", {x = 5, y = 7}, 1},
    {"green-pita-mini", {x = 5, y = 7}, 1},
    {"green-asterisk-mini", {x = 6, y = 6}, 2},
    {"green-pita-mini", {x = 6, y = 6}, 1},
    {"brown-asterisk-mini", {x = 7, y = 6}, 1},
    {"green-asterisk-mini", {x = 7, y = 6}, 6},
    {"green-pita-mini", {x = 7, y = 6}, 1},
    {"green-asterisk-mini", {x = 6, y = 7}, 2},
    {"green-pita-mini", {x = 6, y = 7}, 4},
    {"brown-hairy-grass", {x = 7, y = 7}, 1},
    {"brown-asterisk-mini", {x = 7, y = 7}, 1},
    {"brown-asterisk-mini", {x = 9, y = 6}, 1},
    {"brown-hairy-grass", {x = 9, y = 7}, 1},
    {"brown-hairy-grass", {x = 10, y = 6}, 2},
    {"brown-asterisk-mini", {x = 10, y = 6}, 3},
    {"brown-hairy-grass", {x = 10, y = 7}, 1},
    {"red-pita", {x = 13, y = 6}, 6},
    {"brown-fluff", {x = 12, y = 7}, 1},
    {"red-asterisk", {x = -16, y = 9}, 1},
    {"brown-asterisk-mini", {x = -14, y = 8}, 5},
    {"brown-fluff", {x = -14, y = 8}, 1},
    {"green-small-grass", {x = -14, y = 9}, 2},
    {"green-small-grass", {x = -11, y = 8}, 3},
    {"green-asterisk-mini", {x = -11, y = 8}, 3},
    {"green-small-grass", {x = -12, y = 9}, 2},
    {"green-small-grass", {x = -11, y = 9}, 1},
    {"muddy-stump", {x = -11, y = 9}, 2},
    {"green-asterisk-mini", {x = -11, y = 9}, 1},
    {"green-hairy-grass", {x = -10, y = 8}, 1},
    {"green-asterisk-mini", {x = -10, y = 8}, 2},
    {"green-hairy-grass", {x = -9, y = 8}, 3},
    {"green-hairy-grass", {x = -9, y = 9}, 2},
    {"green-asterisk-mini", {x = -9, y = 9}, 2},
    {"green-hairy-grass", {x = -8, y = 9}, 2},
    {"green-pita-mini", {x = -8, y = 9}, 2},
    {"green-pita-mini", {x = -7, y = 9}, 3},
    {"green-hairy-grass", {x = -6, y = 8}, 1},
    {"green-asterisk-mini", {x = -6, y = 8}, 1},
    {"green-hairy-grass", {x = -5, y = 8}, 2},
    {"green-hairy-grass", {x = -6, y = 9}, 4},
    {"green-hairy-grass", {x = -1, y = 9}, 4},
    {"green-asterisk-mini", {x = -1, y = 9}, 1},
    {"green-hairy-grass", {x = 0, y = 8}, 5},
    {"green-pita-mini", {x = 0, y = 8}, 2},
    {"green-hairy-grass", {x = 1, y = 8}, 3},
    {"green-pita-mini", {x = 1, y = 8}, 1},
    {"green-hairy-grass", {x = 0, y = 9}, 1},
    {"green-small-grass", {x = 0, y = 9}, 1},
    {"green-small-grass", {x = 1, y = 9}, 4},
    {"green-asterisk-mini", {x = 2, y = 8}, 2},
    {"green-small-grass", {x = 2, y = 9}, 1},
    {"green-carpet-grass", {x = 4, y = 8}, 4},
    {"green-pita-mini", {x = 4, y = 8}, 1},
    {"green-pita-mini", {x = 5, y = 8}, 1},
    {"green-carpet-grass", {x = 4, y = 9}, 2},
    {"green-asterisk-mini", {x = 4, y = 9}, 4},
    {"brown-asterisk-mini", {x = 5, y = 9}, 1},
    {"brown-asterisk-mini", {x = 6, y = 8}, 2},
    {"brown-hairy-grass", {x = 7, y = 8}, 2},
    {"brown-hairy-grass", {x = 9, y = 8}, 1},
    {"brown-asterisk", {x = 9, y = 8}, 4},
    {"green-desert-bush", {x = 8, y = 9}, 1},
    {"green-desert-bush", {x = 9, y = 9}, 3},
    {"brown-fluff", {x = 11, y = 8}, 2},
    {"rock-small", {x = 10, y = 9}, 1},
    {"brown-fluff", {x = 12, y = 8}, 2},
    {"green-small-grass", {x = -14, y = 10}, 1},
    {"green-pita-mini", {x = -13, y = 11}, 1},
    {"green-small-grass", {x = -12, y = 10}, 3},
    {"green-asterisk-mini", {x = -11, y = 10}, 1},
    {"green-asterisk-mini", {x = -11, y = 11}, 5},
    {"green-hairy-grass", {x = -10, y = 10}, 4},
    {"green-asterisk-mini", {x = -10, y = 10}, 4},
    {"green-hairy-grass", {x = -9, y = 10}, 1},
    {"green-asterisk-mini", {x = -9, y = 10}, 1},
    {"green-hairy-grass", {x = -10, y = 11}, 2},
    {"green-pita-mini", {x = -8, y = 10}, 1},
    {"green-small-grass", {x = -7, y = 11}, 2},
    {"green-small-grass", {x = -6, y = 11}, 1},
    {"green-small-grass", {x = -5, y = 11}, 1},
    {"green-hairy-grass", {x = -3, y = 10}, 1},
    {"green-hairy-grass", {x = -4, y = 11}, 2},
    {"green-small-grass", {x = -4, y = 11}, 2},
    {"green-hairy-grass", {x = -3, y = 11}, 1},
    {"green-hairy-grass", {x = -2, y = 10}, 2},
    {"green-asterisk-mini", {x = -2, y = 10}, 1},
    {"green-asterisk-mini", {x = -1, y = 10}, 2},
    {"green-hairy-grass", {x = -2, y = 11}, 2},
    {"green-asterisk-mini", {x = -2, y = 11}, 3},
    {"green-small-grass", {x = -1, y = 11}, 2},
    {"green-pita-mini", {x = -1, y = 11}, 1},
    {"green-small-grass", {x = 0, y = 10}, 6},
    {"green-small-grass", {x = 1, y = 10}, 1},
    {"green-pita-mini", {x = 1, y = 10}, 1},
    {"green-small-grass", {x = 0, y = 11}, 1},
    {"green-pita-mini", {x = 0, y = 11}, 3},
    {"green-asterisk-mini", {x = 1, y = 11}, 4},
    {"green-pita-mini", {x = 1, y = 11}, 2},
    {"green-asterisk-mini", {x = 2, y = 10}, 1},
    {"green-asterisk-mini", {x = 3, y = 10}, 4},
    {"green-asterisk-mini", {x = 2, y = 11}, 2},
    {"brown-asterisk-mini", {x = 5, y = 10}, 2},
    {"brown-asterisk-mini", {x = 4, y = 11}, 3},
    {"brown-asterisk-mini", {x = 5, y = 11}, 6},
    {"green-desert-bush", {x = 8, y = 10}, 1},
    {"brown-asterisk-mini", {x = 8, y = 11}, 5},
    {"brown-hairy-grass", {x = 9, y = 11}, 2},
    {"brown-hairy-grass", {x = 10, y = 10}, 1},
    {"brown-hairy-grass", {x = 11, y = 10}, 1},
    {"brown-hairy-grass", {x = 10, y = 11}, 3},
    {"brown-asterisk-mini", {x = 11, y = 11}, 1},
    {"red-asterisk", {x = 13, y = 11}, 2},
    {"green-small-grass", {x = -15, y = 12}, 1},
    {"green-pita-mini", {x = -13, y = 12}, 5},
    {"green-hairy-grass", {x = -14, y = 13}, 1},
    {"green-desert-bush", {x = -14, y = 13}, 6},
    {"green-hairy-grass", {x = -13, y = 13}, 1},
    {"green-desert-bush", {x = -13, y = 13}, 2},
    {"green-hairy-grass", {x = -12, y = 12}, 4},
    {"green-hairy-grass", {x = -11, y = 12}, 4},
    {"green-hairy-grass", {x = -12, y = 13}, 3},
    {"green-carpet-grass", {x = -12, y = 13}, 7},
    {"green-desert-bush", {x = -12, y = 13}, 2},
    {"green-hairy-grass", {x = -11, y = 13}, 1},
    {"green-asterisk-mini", {x = -11, y = 13}, 5},
    {"green-desert-bush", {x = -11, y = 13}, 1},
    {"green-hairy-grass", {x = -10, y = 12}, 2},
    {"green-hairy-grass", {x = -9, y = 12}, 1},
    {"green-desert-bush", {x = -10, y = 13}, 1},
    {"green-hairy-grass", {x = -9, y = 13}, 2},
    {"green-carpet-grass", {x = -9, y = 13}, 1},
    {"green-small-grass", {x = -9, y = 13}, 3},
    {"green-hairy-grass", {x = -8, y = 12}, 2},
    {"green-pita-mini", {x = -8, y = 12}, 5},
    {"green-hairy-grass", {x = -7, y = 12}, 1},
    {"green-asterisk-mini", {x = -7, y = 12}, 5},
    {"green-hairy-grass", {x = -8, y = 13}, 1},
    {"green-hairy-grass", {x = -7, y = 13}, 1},
    {"green-hairy-grass", {x = -6, y = 12}, 3},
    {"green-asterisk-mini", {x = -6, y = 12}, 3},
    {"green-hairy-grass", {x = -5, y = 12}, 4},
    {"green-asterisk-mini", {x = -5, y = 12}, 4},
    {"green-asterisk-mini", {x = -6, y = 13}, 3},
    {"green-hairy-grass", {x = -4, y = 12}, 3},
    {"green-small-grass", {x = -4, y = 12}, 6},
    {"green-asterisk-mini", {x = -4, y = 12}, 2},
    {"green-asterisk-mini", {x = -3, y = 12}, 1},
    {"green-carpet-grass", {x = -3, y = 13}, 1},
    {"green-asterisk-mini", {x = -2, y = 12}, 1},
    {"green-asterisk-mini", {x = -1, y = 12}, 4},
    {"green-asterisk-mini", {x = -1, y = 13}, 5},
    {"green-desert-bush", {x = -1, y = 13}, 1},
    {"green-asterisk-mini", {x = 0, y = 12}, 3},
    {"green-asterisk-mini", {x = 1, y = 12}, 2},
    {"brown-hairy-grass", {x = 0, y = 13}, 1},
    {"green-asterisk-mini", {x = 0, y = 13}, 1},
    {"brown-hairy-grass", {x = 1, y = 13}, 2},
    {"brown-hairy-grass", {x = 2, y = 12}, 1},
    {"brown-asterisk-mini", {x = 2, y = 12}, 3},
    {"brown-hairy-grass", {x = 3, y = 12}, 3},
    {"brown-asterisk-mini", {x = 3, y = 12}, 1},
    {"red-pita", {x = 3, y = 12}, 1},
    {"brown-hairy-grass", {x = 2, y = 13}, 1},
    {"brown-asterisk", {x = 4, y = 13}, 3},
    {"red-pita", {x = 6, y = 13}, 3},
    {"red-pita", {x = 7, y = 13}, 2},
    {"red-pita", {x = 8, y = 13}, 2},
    {"green-hairy-grass", {x = -15, y = 14}, 3},
    {"green-small-grass", {x = -13, y = 15}, 1},
    {"green-asterisk-mini", {x = -12, y = 14}, 5},
    {"green-small-grass", {x = -11, y = 14}, 2},
    {"brown-fluff", {x = -11, y = 14}, 4},
    {"green-small-grass", {x = -12, y = 15}, 2},
    {"green-small-grass", {x = -9, y = 14}, 1},
    {"green-small-grass", {x = -8, y = 14}, 6},
    {"green-small-grass", {x = -7, y = 14}, 3},
    {"green-small-grass", {x = -6, y = 14}, 2},
    {"green-small-grass", {x = -5, y = 14}, 1},
    {"green-small-grass", {x = -4, y = 14}, 1},
    {"green-small-grass", {x = -3, y = 14}, 2},
    {"green-desert-bush", {x = -2, y = 14}, 4},
    {"green-desert-bush", {x = -1, y = 14}, 1},
    {"brown-asterisk", {x = 3, y = 14}, 1},
    {"brown-fluff", {x = 3, y = 14}, 3},
    {"brown-asterisk", {x = 4, y = 14}, 1},
    {"brown-hairy-grass", {x = 9, y = 14}, 1},
    {"red-pita", {x = 12, y = 14}, 1},
  },
}
