return
{
  entities =
  {
    {"dead-dry-hairy-tree", {x = -11.93, y = -12.71}, {}},
    {"dead-grey-trunk", {x = -8.48, y = -11.65}, {}},
    {"dry-tree", {x = -5.83, y = -12.48}, {}},
    {"tree-09-red", {x = 2.25, y = -12.4}, {}},
    {"dry-tree", {x = 5.59, y = -12.55}, {}},
    {"tree-09-red", {x = 14.05, y = -12.43}, {}},
    {"tree-08-red", {x = -2.52, y = -11.3}, {}},
    {"dry-hairy-tree", {x = 8.29, y = -10.75}, {}},
    {"dry-hairy-tree", {x = 9.49, y = -10.26}, {}},
    {"dry-tree", {x = -14.32, y = -8.58}, {}},
    {"tree-09-red", {x = -11.76, y = -9.5}, {}},
    {"tree-08-red", {x = -8.73, y = -9.43}, {}},
    {"tree-08", {x = -2.27, y = -8.68}, {}},
    {"tree-07", {x = 4.18, y = -8.52}, {}},
    {"dead-grey-trunk", {x = 9.7, y = -7.48}, {}},
    {"dry-tree", {x = 11.91, y = -7.93}, {}},
    {"dry-hairy-tree", {x = -13.83, y = -7.37}, {}},
    {"tree-01", {x = -5.73, y = -7.19}, {}},
    {"tree-04", {x = -3.76, y = -6.88}, {}},
    {"tree-07", {x = -3.48, y = -5.64}, {}},
    {"tree-02", {x = 0.48, y = -6.71}, {}},
    {"tree-04", {x = 2.25, y = -6.81}, {}},
    {"dry-tree", {x = -13.73, y = -4.13}, {}},
    {"dead-tree-desert", {x = -14.9, y = -4.42}, {}},
    {"tree-07", {x = -8.73, y = -4.22}, {}},
    {"tree-07", {x = 4.66, y = -4.57}, {}},
    {"tree-01", {x = 8.35, y = -4.15}, {}},
    {"tree-08", {x = 7.21, y = -5.29}, {}},
    {"tree-08-brown", {x = 12.56, y = -4.57}, {}},
    {"dry-hairy-tree", {x = 13.8, y = -5.02}, {}},
    {"tree-05", {x = -5.76, y = -3.6}, {}},
    {"tree-04", {x = 8.7, y = -1.7}, {}},
    {"tree-08-brown", {x = 15.6, y = -1.95}, {}},
    {"tree-08-red", {x = -13.28, y = -1.39}, {}},
    {"tree-08", {x = -10.45, y = -0.12}, {}},
    {"tree-05", {x = 3, y = -0.25}, {}},
    {"tree-05", {x = 9.94, y = -0.95}, {}},
    {"tree-09-red", {x = -13.66, y = 2.2}, {}},
    {"tree-04", {x = -9.62, y = 1.13}, {}},
    {"tree-05", {x = -2.17, y = 2.3}, {}},
    {"tree-07", {x = -0.65, y = 0.54}, {}},
    {"rock-big", {x = 14.67, y = 1.56}, {}},
    {"tree-05", {x = -9.42, y = 2.47}, {}},
    {"tree-08", {x = 1.52, y = 3.37}, {}},
    {"tree-08", {x = 5.18, y = 3.2}, {}},
    {"tree-07", {x = 12.36, y = 2.54}, {}},
    {"dead-tree-desert", {x = -13.35, y = 6.31}, {}},
    {"tree-07", {x = -9.28, y = 5.34}, {}},
    {"tree-02", {x = 0.63, y = 5.54}, {}},
    {"tree-01", {x = -8.76, y = 7.09}, {}},
    {"dry-tree", {x = -14.04, y = 9.98}, {}},
    {"tree-08", {x = -10.14, y = 10.13}, {}},
    {"tree-08-brown", {x = -2.07, y = 9.3}, {}},
    {"tree-01", {x = 3.59, y = 10.2}, {}},
    {"tree-08-brown", {x = 9.94, y = 9.47}, {}},
    {"tree-04", {x = -9.07, y = 10.51}, {}},
    {"tree-02", {x = -3.52, y = 11.48}, {}},
    {"tree-08-brown", {x = 12.46, y = 10.92}, {}},
    {"dead-dry-hairy-tree", {x = -10.76, y = 14.51}, {}},
    {"tree-08-brown", {x = -1.86, y = 12.79}, {}},
    {"tree-08-brown", {x = -1.76, y = 13.75}, {}},
    {"dead-dry-hairy-tree", {x = 7.94, y = 12.89}, {}},
    {"dead-grey-trunk", {x = 2.28, y = 14.88}, {}},
    {"tree-09-red", {x = 12.73, y = 14.71}, {}},
  },
  tiles =
  {
    {"grass-4", {x = -16, y = 1}},
    {"grass-4", {x = -16, y = 2}},
    {"grass-4", {x = -15, y = -3}},
    {"grass-4", {x = -15, y = 0}},
    {"grass-4", {x = -15, y = 1}},
    {"grass-4", {x = -15, y = 2}},
    {"grass-4", {x = -15, y = 3}},
    {"grass-4", {x = -14, y = -9}},
    {"grass-4", {x = -14, y = -4}},
    {"grass-4", {x = -14, y = -3}},
    {"grass-4", {x = -14, y = -2}},
    {"grass-4", {x = -14, y = -1}},
    {"grass-4", {x = -14, y = 0}},
    {"grass-4", {x = -14, y = 1}},
    {"grass-4", {x = -14, y = 2}},
    {"grass-4", {x = -14, y = 3}},
    {"grass-4", {x = -14, y = 4}},
    {"grass-4", {x = -13, y = -10}},
    {"grass-4", {x = -13, y = -9}},
    {"grass-4", {x = -13, y = -8}},
    {"grass-4", {x = -13, y = -5}},
    {"grass-4", {x = -13, y = -4}},
    {"grass-4", {x = -13, y = -3}},
    {"grass-4", {x = -13, y = -2}},
    {"grass-4", {x = -13, y = -1}},
    {"grass-4", {x = -13, y = 0}},
    {"grass-4", {x = -13, y = 1}},
    {"grass-4", {x = -13, y = 2}},
    {"grass-4", {x = -13, y = 3}},
    {"grass-4", {x = -12, y = -11}},
    {"grass-4", {x = -12, y = -10}},
    {"grass-4", {x = -12, y = -9}},
    {"grass-4", {x = -12, y = -8}},
    {"grass-4", {x = -12, y = -7}},
    {"grass-4", {x = -12, y = -5}},
    {"grass-4", {x = -12, y = -4}},
    {"grass-4", {x = -12, y = -3}},
    {"grass-4", {x = -12, y = -2}},
    {"grass-4", {x = -12, y = -1}},
    {"grass-4", {x = -12, y = 0}},
    {"grass-4", {x = -12, y = 1}},
    {"grass-4", {x = -12, y = 2}},
    {"grass-4", {x = -12, y = 3}},
    {"grass-4", {x = -12, y = 4}},
    {"grass-4", {x = -12, y = 7}},
    {"grass-4", {x = -12, y = 8}},
    {"grass-4", {x = -12, y = 9}},
    {"grass-4", {x = -12, y = 10}},
    {"grass-4", {x = -11, y = -12}},
    {"grass-4", {x = -11, y = -11}},
    {"grass-4", {x = -11, y = -10}},
    {"grass-4", {x = -11, y = -9}},
    {"grass-4", {x = -11, y = -8}},
    {"grass-4", {x = -11, y = -7}},
    {"grass-4", {x = -11, y = -6}},
    {"grass-4", {x = -11, y = -5}},
    {"grass-4", {x = -11, y = -4}},
    {"grass-4", {x = -11, y = -3}},
    {"grass-1", {x = -11, y = -2}},
    {"grass-1", {x = -11, y = -1}},
    {"grass-1", {x = -11, y = 0}},
    {"grass-1", {x = -11, y = 1}},
    {"grass-1", {x = -11, y = 2}},
    {"grass-1", {x = -11, y = 3}},
    {"grass-1", {x = -11, y = 4}},
    {"grass-4", {x = -11, y = 5}},
    {"grass-4", {x = -11, y = 6}},
    {"grass-4", {x = -11, y = 7}},
    {"grass-4", {x = -11, y = 8}},
    {"grass-4", {x = -11, y = 9}},
    {"grass-4", {x = -11, y = 10}},
    {"grass-4", {x = -11, y = 11}},
    {"grass-4", {x = -11, y = 12}},
    {"grass-4", {x = -10, y = -11}},
    {"grass-4", {x = -10, y = -10}},
    {"grass-4", {x = -10, y = -9}},
    {"grass-4", {x = -10, y = -8}},
    {"grass-4", {x = -10, y = -7}},
    {"grass-4", {x = -10, y = -6}},
    {"grass-4", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-1", {x = -10, y = -3}},
    {"grass-1", {x = -10, y = -2}},
    {"grass-1", {x = -10, y = -1}},
    {"grass-1", {x = -10, y = 0}},
    {"grass-1", {x = -10, y = 1}},
    {"grass-1", {x = -10, y = 2}},
    {"grass-1", {x = -10, y = 3}},
    {"grass-1", {x = -10, y = 4}},
    {"grass-1", {x = -10, y = 5}},
    {"grass-4", {x = -10, y = 6}},
    {"grass-4", {x = -10, y = 7}},
    {"grass-4", {x = -10, y = 8}},
    {"grass-4", {x = -10, y = 9}},
    {"grass-4", {x = -10, y = 10}},
    {"grass-4", {x = -10, y = 11}},
    {"grass-4", {x = -10, y = 12}},
    {"grass-4", {x = -10, y = 13}},
    {"grass-4", {x = -9, y = -10}},
    {"grass-4", {x = -9, y = -9}},
    {"grass-4", {x = -9, y = -8}},
    {"grass-4", {x = -9, y = -7}},
    {"grass-4", {x = -9, y = -6}},
    {"grass-1", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"grass-1", {x = -9, y = -2}},
    {"grass-1", {x = -9, y = -1}},
    {"grass-2", {x = -9, y = 0}},
    {"grass-2", {x = -9, y = 1}},
    {"grass-2", {x = -9, y = 2}},
    {"grass-1", {x = -9, y = 3}},
    {"grass-1", {x = -9, y = 4}},
    {"grass-1", {x = -9, y = 5}},
    {"grass-1", {x = -9, y = 6}},
    {"grass-1", {x = -9, y = 7}},
    {"grass-1", {x = -9, y = 8}},
    {"grass-1", {x = -9, y = 9}},
    {"grass-1", {x = -9, y = 10}},
    {"grass-1", {x = -9, y = 11}},
    {"grass-4", {x = -9, y = 12}},
    {"grass-4", {x = -9, y = 13}},
    {"grass-4", {x = -9, y = 14}},
    {"grass-4", {x = -8, y = -11}},
    {"grass-4", {x = -8, y = -10}},
    {"grass-4", {x = -8, y = -9}},
    {"grass-4", {x = -8, y = -8}},
    {"grass-4", {x = -8, y = -7}},
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-2", {x = -8, y = -2}},
    {"grass-2", {x = -8, y = -1}},
    {"grass-2", {x = -8, y = 0}},
    {"water-mud", {x = -8, y = 1}},
    {"water-mud", {x = -8, y = 2}},
    {"water-mud", {x = -8, y = 3}},
    {"grass-2", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -8, y = 6}},
    {"grass-1", {x = -8, y = 7}},
    {"grass-1", {x = -8, y = 8}},
    {"grass-1", {x = -8, y = 9}},
    {"grass-1", {x = -8, y = 10}},
    {"grass-1", {x = -8, y = 11}},
    {"grass-1", {x = -8, y = 12}},
    {"grass-1", {x = -8, y = 13}},
    {"grass-4", {x = -8, y = 14}},
    {"grass-4", {x = -7, y = -11}},
    {"grass-4", {x = -7, y = -10}},
    {"grass-4", {x = -7, y = -9}},
    {"grass-4", {x = -7, y = -8}},
    {"grass-1", {x = -7, y = -7}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-2", {x = -7, y = -2}},
    {"water-mud", {x = -7, y = -1}},
    {"water-mud", {x = -7, y = 0}},
    {"water-mud", {x = -7, y = 1}},
    {"water-mud", {x = -7, y = 2}},
    {"water-mud", {x = -7, y = 3}},
    {"water-mud", {x = -7, y = 4}},
    {"water-mud", {x = -7, y = 5}},
    {"water-mud", {x = -7, y = 6}},
    {"water-shallow", {x = -7, y = 7}},
    {"grass-2", {x = -7, y = 8}},
    {"water-shallow", {x = -7, y = 9}},
    {"grass-1", {x = -7, y = 10}},
    {"water-shallow", {x = -7, y = 11}},
    {"grass-1", {x = -7, y = 12}},
    {"grass-1", {x = -7, y = 13}},
    {"grass-4", {x = -7, y = 14}},
    {"grass-4", {x = -7, y = 15}},
    {"grass-4", {x = -6, y = -12}},
    {"grass-4", {x = -6, y = -11}},
    {"grass-4", {x = -6, y = -10}},
    {"grass-1", {x = -6, y = -9}},
    {"grass-1", {x = -6, y = -8}},
    {"grass-1", {x = -6, y = -7}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-2", {x = -6, y = -5}},
    {"grass-2", {x = -6, y = -4}},
    {"water-mud", {x = -6, y = -3}},
    {"water-mud", {x = -6, y = -2}},
    {"water-mud", {x = -6, y = -1}},
    {"water-shallow", {x = -6, y = 0}},
    {"water-shallow", {x = -6, y = 1}},
    {"water-shallow", {x = -6, y = 2}},
    {"water-shallow", {x = -6, y = 3}},
    {"water-shallow", {x = -6, y = 4}},
    {"water-shallow", {x = -6, y = 5}},
    {"water-shallow", {x = -6, y = 6}},
    {"water-shallow", {x = -6, y = 7}},
    {"grass-2", {x = -6, y = 8}},
    {"water-shallow", {x = -6, y = 9}},
    {"grass-1", {x = -6, y = 10}},
    {"grass-1", {x = -6, y = 11}},
    {"water-shallow", {x = -6, y = 12}},
    {"grass-1", {x = -6, y = 13}},
    {"grass-1", {x = -6, y = 14}},
    {"grass-4", {x = -6, y = 15}},
    {"grass-4", {x = -5, y = -12}},
    {"grass-4", {x = -5, y = -11}},
    {"grass-4", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-1", {x = -5, y = -8}},
    {"grass-1", {x = -5, y = -7}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"water-mud", {x = -5, y = -4}},
    {"water-shallow", {x = -5, y = -3}},
    {"water-shallow", {x = -5, y = -2}},
    {"water-shallow", {x = -5, y = -1}},
    {"water-shallow", {x = -5, y = 0}},
    {"water-shallow", {x = -5, y = 1}},
    {"water-shallow", {x = -5, y = 2}},
    {"water-shallow", {x = -5, y = 3}},
    {"water-shallow", {x = -5, y = 4}},
    {"water-shallow", {x = -5, y = 5}},
    {"water-shallow", {x = -5, y = 6}},
    {"water-shallow", {x = -5, y = 7}},
    {"water-shallow", {x = -5, y = 8}},
    {"grass-2", {x = -5, y = 9}},
    {"grass-2", {x = -5, y = 10}},
    {"grass-1", {x = -5, y = 11}},
    {"grass-1", {x = -5, y = 12}},
    {"grass-1", {x = -5, y = 13}},
    {"grass-4", {x = -5, y = 14}},
    {"grass-4", {x = -5, y = 15}},
    {"grass-4", {x = -4, y = -13}},
    {"grass-4", {x = -4, y = -12}},
    {"grass-4", {x = -4, y = -11}},
    {"grass-1", {x = -4, y = -10}},
    {"grass-1", {x = -4, y = -9}},
    {"grass-1", {x = -4, y = -8}},
    {"grass-2", {x = -4, y = -7}},
    {"grass-2", {x = -4, y = -6}},
    {"water-mud", {x = -4, y = -5}},
    {"water-mud", {x = -4, y = -4}},
    {"water-shallow", {x = -4, y = -3}},
    {"water-shallow", {x = -4, y = -2}},
    {"water-shallow", {x = -4, y = -1}},
    {"water-shallow", {x = -4, y = 0}},
    {"water-shallow", {x = -4, y = 1}},
    {"water-shallow", {x = -4, y = 2}},
    {"water-shallow", {x = -4, y = 3}},
    {"water-shallow", {x = -4, y = 4}},
    {"water-shallow", {x = -4, y = 5}},
    {"grass-2", {x = -4, y = 6}},
    {"grass-2", {x = -4, y = 7}},
    {"grass-2", {x = -4, y = 8}},
    {"water-shallow", {x = -4, y = 9}},
    {"grass-1", {x = -4, y = 10}},
    {"grass-1", {x = -4, y = 11}},
    {"grass-1", {x = -4, y = 12}},
    {"grass-1", {x = -4, y = 13}},
    {"grass-4", {x = -4, y = 14}},
    {"grass-4", {x = -3, y = -13}},
    {"grass-4", {x = -3, y = -12}},
    {"grass-4", {x = -3, y = -11}},
    {"grass-1", {x = -3, y = -10}},
    {"grass-1", {x = -3, y = -9}},
    {"grass-1", {x = -3, y = -8}},
    {"grass-1", {x = -3, y = -7}},
    {"grass-2", {x = -3, y = -6}},
    {"water-mud", {x = -3, y = -5}},
    {"water-mud", {x = -3, y = -4}},
    {"water-shallow", {x = -3, y = -3}},
    {"water-shallow", {x = -3, y = -2}},
    {"water-shallow", {x = -3, y = -1}},
    {"water-shallow", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-2", {x = -3, y = 4}},
    {"grass-2", {x = -3, y = 5}},
    {"water-shallow", {x = -3, y = 6}},
    {"grass-2", {x = -3, y = 7}},
    {"grass-2", {x = -3, y = 8}},
    {"grass-1", {x = -3, y = 9}},
    {"grass-1", {x = -3, y = 10}},
    {"grass-1", {x = -3, y = 11}},
    {"grass-4", {x = -3, y = 12}},
    {"grass-4", {x = -3, y = 13}},
    {"grass-4", {x = -3, y = 14}},
    {"grass-4", {x = -2, y = -13}},
    {"grass-4", {x = -2, y = -12}},
    {"grass-4", {x = -2, y = -11}},
    {"grass-1", {x = -2, y = -10}},
    {"grass-1", {x = -2, y = -9}},
    {"grass-1", {x = -2, y = -8}},
    {"grass-2", {x = -2, y = -7}},
    {"water-mud", {x = -2, y = -6}},
    {"water-mud", {x = -2, y = -5}},
    {"water-shallow", {x = -2, y = -4}},
    {"water-shallow", {x = -2, y = -3}},
    {"water-shallow", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-1", {x = -2, y = 8}},
    {"grass-1", {x = -2, y = 9}},
    {"grass-1", {x = -2, y = 10}},
    {"grass-4", {x = -2, y = 11}},
    {"grass-4", {x = -2, y = 12}},
    {"grass-4", {x = -2, y = 13}},
    {"grass-4", {x = -2, y = 14}},
    {"grass-4", {x = -1, y = -13}},
    {"grass-4", {x = -1, y = -12}},
    {"grass-4", {x = -1, y = -11}},
    {"grass-1", {x = -1, y = -10}},
    {"grass-1", {x = -1, y = -9}},
    {"grass-1", {x = -1, y = -8}},
    {"grass-1", {x = -1, y = -7}},
    {"water-mud", {x = -1, y = -6}},
    {"water-mud", {x = -1, y = -5}},
    {"water-shallow", {x = -1, y = -4}},
    {"water-shallow", {x = -1, y = -3}},
    {"water-shallow", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-1", {x = -1, y = 8}},
    {"grass-1", {x = -1, y = 9}},
    {"grass-1", {x = -1, y = 10}},
    {"grass-4", {x = -1, y = 11}},
    {"grass-4", {x = -1, y = 12}},
    {"grass-4", {x = -1, y = 13}},
    {"grass-4", {x = 0, y = -13}},
    {"grass-4", {x = 0, y = -12}},
    {"grass-4", {x = 0, y = -11}},
    {"grass-1", {x = 0, y = -10}},
    {"grass-1", {x = 0, y = -9}},
    {"grass-1", {x = 0, y = -8}},
    {"grass-2", {x = 0, y = -7}},
    {"water-mud", {x = 0, y = -6}},
    {"water-mud", {x = 0, y = -5}},
    {"water-shallow", {x = 0, y = -4}},
    {"water-shallow", {x = 0, y = -3}},
    {"water-shallow", {x = 0, y = -2}},
    {"grass-2", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-4", {x = 0, y = 9}},
    {"grass-4", {x = 0, y = 10}},
    {"grass-4", {x = 0, y = 11}},
    {"grass-4", {x = 0, y = 12}},
    {"grass-4", {x = 0, y = 13}},
    {"grass-4", {x = 1, y = -14}},
    {"grass-4", {x = 1, y = -13}},
    {"grass-4", {x = 1, y = -12}},
    {"grass-4", {x = 1, y = -11}},
    {"grass-4", {x = 1, y = -10}},
    {"grass-1", {x = 1, y = -9}},
    {"grass-1", {x = 1, y = -8}},
    {"grass-2", {x = 1, y = -7}},
    {"water-mud", {x = 1, y = -6}},
    {"water-mud", {x = 1, y = -5}},
    {"water-shallow", {x = 1, y = -4}},
    {"water-shallow", {x = 1, y = -3}},
    {"water-shallow", {x = 1, y = -2}},
    {"grass-2", {x = 1, y = -1}},
    {"grass-2", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-4", {x = 1, y = 9}},
    {"grass-4", {x = 1, y = 10}},
    {"grass-4", {x = 1, y = 11}},
    {"grass-4", {x = 1, y = 12}},
    {"grass-4", {x = 1, y = 13}},
    {"grass-4", {x = 2, y = -15}},
    {"grass-4", {x = 2, y = -14}},
    {"grass-4", {x = 2, y = -13}},
    {"grass-4", {x = 2, y = -12}},
    {"grass-4", {x = 2, y = -11}},
    {"grass-4", {x = 2, y = -10}},
    {"grass-1", {x = 2, y = -9}},
    {"grass-1", {x = 2, y = -8}},
    {"grass-1", {x = 2, y = -7}},
    {"grass-2", {x = 2, y = -6}},
    {"water-mud", {x = 2, y = -5}},
    {"water-shallow", {x = 2, y = -4}},
    {"water-shallow", {x = 2, y = -3}},
    {"water-shallow", {x = 2, y = -2}},
    {"grass-2", {x = 2, y = -1}},
    {"grass-2", {x = 2, y = 0}},
    {"water-shallow", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 2, y = 6}},
    {"grass-4", {x = 2, y = 7}},
    {"grass-4", {x = 2, y = 8}},
    {"grass-4", {x = 2, y = 9}},
    {"grass-4", {x = 2, y = 10}},
    {"grass-4", {x = 2, y = 11}},
    {"grass-4", {x = 2, y = 12}},
    {"grass-4", {x = 2, y = 13}},
    {"grass-4", {x = 3, y = -14}},
    {"grass-4", {x = 3, y = -13}},
    {"grass-4", {x = 3, y = -12}},
    {"grass-4", {x = 3, y = -11}},
    {"grass-4", {x = 3, y = -10}},
    {"grass-1", {x = 3, y = -9}},
    {"grass-1", {x = 3, y = -8}},
    {"grass-1", {x = 3, y = -7}},
    {"grass-2", {x = 3, y = -6}},
    {"water-mud", {x = 3, y = -5}},
    {"water-mud", {x = 3, y = -4}},
    {"water-shallow", {x = 3, y = -3}},
    {"water-shallow", {x = 3, y = -2}},
    {"grass-2", {x = 3, y = -1}},
    {"grass-2", {x = 3, y = 0}},
    {"grass-2", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-4", {x = 3, y = 6}},
    {"grass-4", {x = 3, y = 7}},
    {"grass-4", {x = 3, y = 8}},
    {"grass-4", {x = 3, y = 9}},
    {"grass-4", {x = 3, y = 10}},
    {"grass-4", {x = 3, y = 11}},
    {"grass-4", {x = 3, y = 12}},
    {"grass-4", {x = 4, y = -13}},
    {"grass-4", {x = 4, y = -12}},
    {"grass-4", {x = 4, y = -11}},
    {"grass-4", {x = 4, y = -10}},
    {"grass-1", {x = 4, y = -9}},
    {"grass-1", {x = 4, y = -8}},
    {"grass-1", {x = 4, y = -7}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-2", {x = 4, y = -5}},
    {"water-mud", {x = 4, y = -4}},
    {"water-shallow", {x = 4, y = -3}},
    {"water-shallow", {x = 4, y = -2}},
    {"water-shallow", {x = 4, y = -1}},
    {"grass-2", {x = 4, y = 0}},
    {"grass-2", {x = 4, y = 1}},
    {"grass-2", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-4", {x = 4, y = 6}},
    {"grass-4", {x = 4, y = 7}},
    {"grass-4", {x = 4, y = 8}},
    {"grass-4", {x = 4, y = 9}},
    {"grass-4", {x = 4, y = 10}},
    {"grass-4", {x = 4, y = 11}},
    {"grass-4", {x = 4, y = 12}},
    {"grass-4", {x = 5, y = -11}},
    {"grass-4", {x = 5, y = -10}},
    {"grass-4", {x = 5, y = -9}},
    {"grass-1", {x = 5, y = -8}},
    {"grass-1", {x = 5, y = -7}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-2", {x = 5, y = -4}},
    {"water-shallow", {x = 5, y = -3}},
    {"water-shallow", {x = 5, y = -2}},
    {"water-shallow", {x = 5, y = -1}},
    {"grass-2", {x = 5, y = 0}},
    {"grass-2", {x = 5, y = 1}},
    {"grass-2", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 5, y = 6}},
    {"grass-4", {x = 5, y = 7}},
    {"grass-4", {x = 5, y = 8}},
    {"grass-4", {x = 5, y = 9}},
    {"grass-4", {x = 5, y = 10}},
    {"grass-4", {x = 5, y = 11}},
    {"grass-4", {x = 6, y = -11}},
    {"grass-4", {x = 6, y = -10}},
    {"grass-4", {x = 6, y = -9}},
    {"grass-1", {x = 6, y = -8}},
    {"grass-1", {x = 6, y = -7}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-2", {x = 6, y = -4}},
    {"water-mud", {x = 6, y = -3}},
    {"water-shallow", {x = 6, y = -2}},
    {"water-shallow", {x = 6, y = -1}},
    {"water-shallow", {x = 6, y = 0}},
    {"water-shallow", {x = 6, y = 1}},
    {"grass-2", {x = 6, y = 2}},
    {"grass-2", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 6, y = 6}},
    {"grass-4", {x = 6, y = 7}},
    {"grass-4", {x = 6, y = 8}},
    {"grass-4", {x = 6, y = 9}},
    {"grass-4", {x = 6, y = 10}},
    {"grass-4", {x = 7, y = -10}},
    {"grass-4", {x = 7, y = -9}},
    {"grass-4", {x = 7, y = -8}},
    {"grass-1", {x = 7, y = -7}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-2", {x = 7, y = -3}},
    {"water-mud", {x = 7, y = -2}},
    {"water-shallow", {x = 7, y = -1}},
    {"water-shallow", {x = 7, y = 0}},
    {"water-shallow", {x = 7, y = 1}},
    {"grass-2", {x = 7, y = 2}},
    {"water-shallow", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
    {"grass-4", {x = 7, y = 6}},
    {"grass-4", {x = 7, y = 7}},
    {"grass-4", {x = 7, y = 8}},
    {"grass-4", {x = 8, y = -9}},
    {"grass-4", {x = 8, y = -8}},
    {"grass-4", {x = 8, y = -7}},
    {"grass-1", {x = 8, y = -6}},
    {"grass-1", {x = 8, y = -5}},
    {"grass-1", {x = 8, y = -4}},
    {"grass-1", {x = 8, y = -3}},
    {"grass-2", {x = 8, y = -2}},
    {"water-mud", {x = 8, y = -1}},
    {"water-shallow", {x = 8, y = 0}},
    {"water-shallow", {x = 8, y = 1}},
    {"water-shallow", {x = 8, y = 2}},
    {"grass-2", {x = 8, y = 3}},
    {"grass-2", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-1", {x = 8, y = 6}},
    {"grass-4", {x = 8, y = 7}},
    {"grass-4", {x = 8, y = 8}},
    {"grass-4", {x = 9, y = -9}},
    {"grass-4", {x = 9, y = -8}},
    {"grass-4", {x = 9, y = -7}},
    {"grass-4", {x = 9, y = -6}},
    {"grass-1", {x = 9, y = -5}},
    {"grass-1", {x = 9, y = -4}},
    {"grass-1", {x = 9, y = -3}},
    {"grass-1", {x = 9, y = -2}},
    {"grass-1", {x = 9, y = -1}},
    {"water-mud", {x = 9, y = 0}},
    {"water-shallow", {x = 9, y = 1}},
    {"grass-2", {x = 9, y = 2}},
    {"grass-2", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"grass-1", {x = 9, y = 5}},
    {"grass-1", {x = 9, y = 6}},
    {"grass-4", {x = 9, y = 7}},
    {"grass-4", {x = 9, y = 8}},
    {"grass-4", {x = 9, y = 9}},
    {"grass-4", {x = 9, y = 10}},
    {"grass-4", {x = 10, y = -8}},
    {"grass-4", {x = 10, y = -7}},
    {"grass-4", {x = 10, y = -6}},
    {"grass-4", {x = 10, y = -5}},
    {"grass-4", {x = 10, y = -4}},
    {"grass-1", {x = 10, y = -3}},
    {"grass-1", {x = 10, y = -2}},
    {"grass-1", {x = 10, y = -1}},
    {"grass-1", {x = 10, y = 0}},
    {"grass-2", {x = 10, y = 1}},
    {"grass-2", {x = 10, y = 2}},
    {"grass-1", {x = 10, y = 3}},
    {"water-shallow", {x = 10, y = 4}},
    {"grass-1", {x = 10, y = 5}},
    {"grass-1", {x = 10, y = 6}},
    {"grass-4", {x = 10, y = 7}},
    {"grass-4", {x = 10, y = 8}},
    {"grass-4", {x = 10, y = 9}},
    {"grass-4", {x = 10, y = 10}},
    {"grass-4", {x = 10, y = 11}},
    {"grass-4", {x = 11, y = -7}},
    {"grass-4", {x = 11, y = -6}},
    {"grass-4", {x = 11, y = -5}},
    {"grass-4", {x = 11, y = -4}},
    {"grass-4", {x = 11, y = -3}},
    {"grass-1", {x = 11, y = -2}},
    {"grass-1", {x = 11, y = -1}},
    {"grass-1", {x = 11, y = 0}},
    {"grass-1", {x = 11, y = 1}},
    {"grass-1", {x = 11, y = 2}},
    {"water-shallow", {x = 11, y = 3}},
    {"grass-1", {x = 11, y = 4}},
    {"water-shallow", {x = 11, y = 5}},
    {"grass-4", {x = 11, y = 6}},
    {"grass-4", {x = 11, y = 7}},
    {"grass-4", {x = 11, y = 8}},
    {"grass-4", {x = 11, y = 9}},
    {"grass-4", {x = 11, y = 10}},
    {"grass-4", {x = 11, y = 11}},
    {"grass-4", {x = 11, y = 12}},
    {"grass-4", {x = 12, y = -7}},
    {"grass-4", {x = 12, y = -6}},
    {"grass-4", {x = 12, y = -5}},
    {"grass-4", {x = 12, y = -4}},
    {"grass-4", {x = 12, y = -3}},
    {"grass-4", {x = 12, y = -2}},
    {"grass-4", {x = 12, y = -1}},
    {"grass-1", {x = 12, y = 0}},
    {"grass-1", {x = 12, y = 1}},
    {"grass-1", {x = 12, y = 2}},
    {"water-shallow", {x = 12, y = 3}},
    {"grass-1", {x = 12, y = 4}},
    {"grass-1", {x = 12, y = 5}},
    {"grass-4", {x = 12, y = 6}},
    {"grass-4", {x = 12, y = 7}},
    {"grass-4", {x = 12, y = 8}},
    {"grass-4", {x = 12, y = 9}},
    {"grass-4", {x = 12, y = 10}},
    {"grass-4", {x = 12, y = 11}},
    {"grass-4", {x = 13, y = -8}},
    {"grass-4", {x = 13, y = -7}},
    {"grass-4", {x = 13, y = -6}},
    {"grass-4", {x = 13, y = -5}},
    {"grass-4", {x = 13, y = -4}},
    {"grass-4", {x = 13, y = -3}},
    {"grass-4", {x = 13, y = -2}},
    {"grass-4", {x = 13, y = -1}},
    {"grass-1", {x = 13, y = 0}},
    {"grass-1", {x = 13, y = 1}},
    {"grass-1", {x = 13, y = 2}},
    {"grass-1", {x = 13, y = 3}},
    {"grass-1", {x = 13, y = 4}},
    {"grass-4", {x = 13, y = 5}},
    {"grass-4", {x = 13, y = 6}},
    {"grass-4", {x = 13, y = 7}},
    {"grass-4", {x = 13, y = 9}},
    {"grass-4", {x = 13, y = 10}},
    {"grass-4", {x = 14, y = -7}},
    {"grass-4", {x = 14, y = -6}},
    {"grass-4", {x = 14, y = -5}},
    {"grass-4", {x = 14, y = -2}},
    {"grass-4", {x = 14, y = -1}},
    {"grass-4", {x = 14, y = 0}},
    {"grass-4", {x = 14, y = 1}},
    {"grass-1", {x = 14, y = 2}},
    {"grass-4", {x = 14, y = 3}},
    {"grass-4", {x = 14, y = 4}},
    {"grass-4", {x = 14, y = 5}},
    {"grass-4", {x = 14, y = 6}},
    {"grass-4", {x = 15, y = -6}},
    {"grass-4", {x = 15, y = -1}},
    {"grass-4", {x = 15, y = 0}},
    {"grass-4", {x = 15, y = 1}},
    {"grass-4", {x = 15, y = 2}},
    {"grass-4", {x = 15, y = 3}},
    {"grass-4", {x = 15, y = 4}},
    {"grass-4", {x = 15, y = 5}},
  },
  decoratives =
  {
    {"sand-rock-medium", {x = -14, y = -15}, 1},
    {"brown-fluff-dry", {x = -5, y = -15}, 1},
    {"brown-fluff-dry", {x = -10, y = -13}, 1},
    {"green-desert-bush", {x = 0, y = -13}, 1},
    {"garballo-mini-dry", {x = 11, y = -13}, 1},
    {"brown-hairy-grass", {x = -8, y = -11}, 1},
    {"brown-hairy-grass", {x = -7, y = -11}, 3},
    {"brown-hairy-grass", {x = -6, y = -12}, 1},
    {"brown-hairy-grass", {x = -6, y = -11}, 1},
    {"brown-carpet-grass", {x = -5, y = -11}, 1},
    {"brown-hairy-grass", {x = -3, y = -12}, 4},
    {"brown-asterisk-mini", {x = -4, y = -11}, 1},
    {"brown-asterisk-mini", {x = -3, y = -11}, 3},
    {"brown-hairy-grass", {x = -2, y = -12}, 2},
    {"brown-asterisk-mini", {x = -2, y = -11}, 1},
    {"brown-asterisk-mini", {x = -1, y = -11}, 2},
    {"brown-carpet-grass", {x = 0, y = -12}, 1},
    {"red-asterisk", {x = 2, y = -12}, 1},
    {"brown-hairy-grass", {x = 2, y = -11}, 1},
    {"brown-fluff", {x = 2, y = -11}, 2},
    {"red-asterisk", {x = 3, y = -11}, 1},
    {"brown-hairy-grass", {x = 5, y = -11}, 3},
    {"brown-fluff", {x = 5, y = -11}, 1},
    {"brown-fluff-dry", {x = 13, y = -11}, 1},
    {"brown-hairy-grass", {x = -11, y = -9}, 2},
    {"green-small-grass", {x = -9, y = -10}, 1},
    {"brown-carpet-grass", {x = -9, y = -9}, 2},
    {"red-asterisk", {x = -9, y = -9}, 1},
    {"brown-fluff", {x = -7, y = -10}, 1},
    {"red-croton", {x = -7, y = -9}, 6},
    {"green-desert-bush", {x = -5, y = -10}, 1},
    {"green-asterisk-mini", {x = -6, y = -9}, 2},
    {"green-asterisk-mini", {x = -5, y = -9}, 1},
    {"muddy-stump", {x = -4, y = -9}, 1},
    {"green-pita-mini", {x = -4, y = -9}, 5},
    {"green-pita-mini", {x = -3, y = -9}, 2},
    {"red-croton", {x = -2, y = -10}, 6},
    {"green-hairy-grass", {x = -2, y = -9}, 4},
    {"green-hairy-grass", {x = -1, y = -9}, 1},
    {"green-pita-mini", {x = -1, y = -9}, 1},
    {"brown-asterisk-mini", {x = 1, y = -10}, 3},
    {"green-hairy-grass", {x = 0, y = -9}, 2},
    {"green-pita", {x = 0, y = -9}, 4},
    {"green-hairy-grass", {x = 1, y = -9}, 2},
    {"brown-asterisk-mini", {x = 2, y = -10}, 3},
    {"brown-fluff", {x = 2, y = -10}, 1},
    {"brown-asterisk-mini", {x = 3, y = -10}, 1},
    {"green-desert-bush", {x = 4, y = -10}, 1},
    {"brown-hairy-grass", {x = 6, y = -10}, 2},
    {"brown-carpet-grass", {x = 6, y = -10}, 1},
    {"red-croton", {x = 6, y = -9}, 3},
    {"brown-carpet-grass", {x = -12, y = -8}, 1},
    {"brown-hairy-grass", {x = -9, y = -8}, 2},
    {"brown-fluff", {x = -10, y = -7}, 1},
    {"brown-asterisk-mini", {x = -9, y = -7}, 7},
    {"green-small-grass", {x = -8, y = -8}, 1},
    {"green-pita", {x = -8, y = -7}, 2},
    {"green-asterisk-mini", {x = -7, y = -7}, 1},
    {"green-pita", {x = -7, y = -7}, 2},
    {"green-hairy-grass", {x = -6, y = -7}, 5},
    {"green-hairy-grass", {x = -3, y = -8}, 1},
    {"green-asterisk-mini", {x = -3, y = -8}, 7},
    {"green-small-grass", {x = -4, y = -7}, 1},
    {"green-pita", {x = -4, y = -7}, 1},
    {"green-small-grass", {x = -3, y = -7}, 1},
    {"green-hairy-grass", {x = -2, y = -8}, 1},
    {"green-small-grass", {x = -2, y = -8}, 6},
    {"green-carpet-grass", {x = -1, y = -8}, 1},
    {"green-hairy-grass", {x = -2, y = -7}, 5},
    {"green-hairy-grass", {x = -1, y = -7}, 1},
    {"green-croton", {x = -1, y = -7}, 4},
    {"green-small-grass", {x = 0, y = -8}, 1},
    {"green-hairy-grass", {x = 1, y = -8}, 1},
    {"green-small-grass", {x = 1, y = -8}, 2},
    {"green-hairy-grass", {x = 0, y = -7}, 1},
    {"green-asterisk", {x = 0, y = -7}, 2},
    {"green-hairy-grass", {x = 1, y = -7}, 4},
    {"green-small-grass", {x = 2, y = -8}, 1},
    {"green-pita", {x = 3, y = -8}, 6},
    {"green-hairy-grass", {x = 2, y = -7}, 2},
    {"green-small-grass", {x = 2, y = -7}, 1},
    {"green-hairy-grass", {x = 3, y = -7}, 1},
    {"green-small-grass", {x = 3, y = -7}, 5},
    {"green-small-grass", {x = 4, y = -7}, 2},
    {"muddy-stump", {x = 5, y = -7}, 1},
    {"brown-carpet-grass", {x = 8, y = -8}, 2},
    {"brown-carpet-grass", {x = 9, y = -8}, 1},
    {"brown-hairy-grass", {x = 10, y = -7}, 2},
    {"brown-hairy-grass", {x = -12, y = -5}, 3},
    {"brown-asterisk-mini", {x = -10, y = -6}, 2},
    {"red-croton", {x = -10, y = -6}, 1},
    {"brown-asterisk-mini", {x = -10, y = -5}, 1},
    {"green-asterisk-mini", {x = -8, y = -6}, 1},
    {"green-asterisk-mini", {x = -7, y = -6}, 2},
    {"green-asterisk-mini", {x = -8, y = -5}, 3},
    {"green-small-grass", {x = -7, y = -5}, 3},
    {"green-pita-mini", {x = -7, y = -5}, 5},
    {"green-carpet-grass", {x = -5, y = -6}, 1},
    {"green-asterisk", {x = -5, y = -6}, 2},
    {"green-small-grass", {x = -6, y = -5}, 2},
    {"green-croton", {x = -5, y = -5}, 1},
    {"green-hairy-grass", {x = -4, y = -6}, 7},
    {"green-croton", {x = -4, y = -6}, 2},
    {"green-hairy-grass", {x = -3, y = -6}, 5},
    {"rock-medium", {x = -3, y = -6}, 1},
    {"green-hairy-grass", {x = -4, y = -5}, 3},
    {"green-croton", {x = 0, y = -6}, 1},
    {"green-hairy-grass", {x = 1, y = -6}, 1},
    {"green-hairy-grass", {x = 2, y = -6}, 1},
    {"green-croton", {x = 2, y = -6}, 5},
    {"green-hairy-grass", {x = 3, y = -6}, 7},
    {"green-croton", {x = 3, y = -6}, 3},
    {"green-croton", {x = 3, y = -5}, 1},
    {"green-hairy-grass", {x = 4, y = -6}, 1},
    {"green-croton", {x = 4, y = -6}, 1},
    {"green-hairy-grass", {x = 5, y = -6}, 1},
    {"green-carpet-grass", {x = 5, y = -6}, 1},
    {"green-asterisk-mini", {x = 5, y = -6}, 3},
    {"green-pita-mini", {x = 5, y = -6}, 4},
    {"green-hairy-grass", {x = 4, y = -5}, 2},
    {"green-hairy-grass", {x = 5, y = -5}, 5},
    {"green-hairy-grass", {x = 6, y = -6}, 1},
    {"green-pita-mini", {x = 6, y = -6}, 3},
    {"green-pita-mini", {x = 7, y = -6}, 1},
    {"green-hairy-grass", {x = 6, y = -5}, 1},
    {"green-asterisk-mini", {x = 6, y = -5}, 3},
    {"green-hairy-grass", {x = 7, y = -5}, 3},
    {"green-carpet-grass", {x = 7, y = -5}, 1},
    {"green-asterisk-mini", {x = 7, y = -5}, 1},
    {"brown-asterisk-mini", {x = 8, y = -6}, 1},
    {"brown-asterisk-mini", {x = 9, y = -5}, 1},
    {"brown-hairy-grass", {x = 11, y = -6}, 3},
    {"red-asterisk", {x = 11, y = -6}, 1},
    {"brown-hairy-grass", {x = 12, y = -6}, 1},
    {"brown-hairy-grass", {x = -12, y = -4}, 2},
    {"brown-asterisk-mini", {x = -11, y = -4}, 3},
    {"brown-hairy-grass", {x = -12, y = -3}, 2},
    {"brown-fluff", {x = -12, y = -3}, 1},
    {"brown-asterisk-mini", {x = -11, y = -3}, 1},
    {"green-hairy-grass", {x = -9, y = -3}, 1},
    {"green-carpet-grass", {x = -9, y = -3}, 4},
    {"muddy-stump", {x = -9, y = -3}, 1},
    {"green-pita-mini", {x = -9, y = -3}, 4},
    {"green-hairy-grass", {x = -8, y = -4}, 1},
    {"green-asterisk-mini", {x = -8, y = -4}, 1},
    {"green-croton", {x = -7, y = -4}, 5},
    {"green-hairy-grass", {x = -8, y = -3}, 3},
    {"green-croton", {x = -7, y = -3}, 7},
    {"green-hairy-grass", {x = -6, y = -4}, 2},
    {"green-hairy-grass", {x = 5, y = -4}, 3},
    {"green-croton", {x = 5, y = -4}, 1},
    {"green-hairy-grass", {x = 6, y = -4}, 1},
    {"green-hairy-grass", {x = 7, y = -4}, 5},
    {"green-carpet-grass", {x = 7, y = -4}, 1},
    {"green-asterisk-mini", {x = 7, y = -4}, 1},
    {"green-pita-mini", {x = 7, y = -4}, 4},
    {"green-hairy-grass", {x = 7, y = -3}, 2},
    {"green-asterisk", {x = 7, y = -3}, 3},
    {"green-pita-mini", {x = 8, y = -4}, 1},
    {"green-hairy-grass", {x = 8, y = -3}, 5},
    {"green-croton", {x = 8, y = -3}, 1},
    {"green-pita-mini", {x = 8, y = -3}, 2},
    {"brown-fluff", {x = 11, y = -4}, 1},
    {"muddy-stump", {x = 10, y = -3}, 1},
    {"brown-asterisk-mini", {x = 11, y = -3}, 5},
    {"brown-carpet-grass", {x = 12, y = -4}, 1},
    {"green-small-grass", {x = 12, y = -4}, 3},
    {"green-small-grass", {x = 12, y = -3}, 2},
    {"brown-asterisk-mini", {x = 12, y = -3}, 1},
    {"brown-hairy-grass", {x = 13, y = -3}, 2},
    {"green-desert-bush", {x = -14, y = -2}, 1},
    {"brown-hairy-grass", {x = -12, y = -2}, 1},
    {"green-small-grass", {x = -12, y = -2}, 1},
    {"red-croton", {x = -12, y = -2}, 1},
    {"brown-hairy-grass", {x = -12, y = -1}, 2},
    {"brown-asterisk-mini", {x = -10, y = -2}, 2},
    {"green-hairy-grass", {x = -10, y = -1}, 4},
    {"brown-asterisk-mini", {x = -10, y = -1}, 1},
    {"green-small-grass", {x = -9, y = -1}, 4},
    {"green-pita", {x = -9, y = -1}, 1},
    {"green-croton", {x = -8, y = -2}, 2},
    {"green-hairy-grass", {x = -7, y = -2}, 3},
    {"green-hairy-grass", {x = -8, y = -1}, 6},
    {"green-asterisk", {x = -8, y = -1}, 3},
    {"green-pita-mini", {x = -8, y = -1}, 2},
    {"green-hairy-grass", {x = -1, y = -2}, 1},
    {"green-hairy-grass", {x = -2, y = -1}, 1},
    {"green-hairy-grass", {x = -1, y = -1}, 2},
    {"green-carpet-grass", {x = -1, y = -1}, 2},
    {"green-hairy-grass", {x = 0, y = -2}, 1},
    {"green-carpet-grass", {x = 0, y = -1}, 2},
    {"green-pita-mini", {x = 0, y = -1}, 1},
    {"green-hairy-grass", {x = 1, y = -1}, 2},
    {"green-hairy-grass", {x = 2, y = -1}, 1},
    {"green-hairy-grass", {x = 3, y = -1}, 2},
    {"green-croton", {x = 3, y = -1}, 1},
    {"green-hairy-grass", {x = 4, y = -1}, 1},
    {"green-hairy-grass", {x = 8, y = -2}, 2},
    {"green-croton", {x = 8, y = -2}, 1},
    {"green-hairy-grass", {x = 9, y = -2}, 1},
    {"green-carpet-grass", {x = 9, y = -2}, 2},
    {"green-croton", {x = 9, y = -2}, 3},
    {"green-croton", {x = 9, y = -1}, 1},
    {"green-croton", {x = 10, y = -2}, 2},
    {"green-pita", {x = 10, y = -1}, 1},
    {"green-asterisk-mini", {x = 11, y = -1}, 6},
    {"green-pita", {x = 11, y = -1}, 7},
    {"brown-asterisk-mini", {x = 12, y = -2}, 1},
    {"brown-hairy-grass", {x = 13, y = -2}, 1},
    {"brown-hairy-grass", {x = 14, y = -2}, 3},
    {"red-asterisk", {x = 15, y = -1}, 1},
    {"green-small-grass", {x = -13, y = 0}, 2},
    {"brown-hairy-grass", {x = -13, y = 1}, 1},
    {"garballo-mini-dry", {x = -13, y = 1}, 1},
    {"green-carpet-grass", {x = -11, y = 0}, 1},
    {"green-asterisk-mini", {x = -11, y = 1}, 5},
    {"brown-asterisk-mini", {x = -10, y = 0}, 2},
    {"green-hairy-grass", {x = -9, y = 0}, 2},
    {"green-hairy-grass", {x = -9, y = 1}, 4},
    {"green-hairy-grass", {x = -8, y = 0}, 3},
    {"green-croton", {x = -3, y = 1}, 1},
    {"green-hairy-grass", {x = -2, y = 0}, 1},
    {"green-hairy-grass", {x = -2, y = 1}, 2},
    {"green-small-grass", {x = -2, y = 1}, 6},
    {"green-pita", {x = -1, y = 1}, 1},
    {"green-pita-mini", {x = -1, y = 1}, 3},
    {"green-hairy-grass", {x = 0, y = 0}, 1},
    {"green-hairy-grass", {x = 1, y = 0}, 1},
    {"green-carpet-grass", {x = 0, y = 1}, 1},
    {"green-asterisk", {x = 0, y = 1}, 2},
    {"green-pita-mini", {x = 0, y = 1}, 3},
    {"green-carpet-grass", {x = 1, y = 1}, 1},
    {"green-asterisk", {x = 1, y = 1}, 2},
    {"green-small-grass", {x = 2, y = 0}, 4},
    {"green-pita", {x = 3, y = 0}, 3},
    {"green-carpet-grass", {x = 2, y = 1}, 1},
    {"green-pita-mini", {x = 2, y = 1}, 6},
    {"green-carpet-grass", {x = 3, y = 1}, 3},
    {"green-pita-mini", {x = 5, y = 0}, 3},
    {"green-carpet-grass", {x = 4, y = 1}, 1},
    {"green-hairy-grass", {x = 6, y = 1}, 4},
    {"green-hairy-grass", {x = 7, y = 1}, 4},
    {"green-hairy-grass", {x = 8, y = 0}, 7},
    {"green-hairy-grass", {x = 8, y = 1}, 1},
    {"green-hairy-grass", {x = 9, y = 1}, 1},
    {"green-carpet-grass", {x = 9, y = 1}, 3},
    {"green-carpet-grass", {x = 10, y = 0}, 2},
    {"green-asterisk-mini", {x = 11, y = 0}, 1},
    {"green-carpet-grass", {x = 10, y = 1}, 2},
    {"green-pita", {x = 11, y = 1}, 2},
    {"brown-asterisk-mini", {x = 13, y = 0}, 6},
    {"green-pita-mini", {x = 12, y = 1}, 3},
    {"brown-asterisk-mini", {x = 14, y = 0}, 1},
    {"brown-asterisk-mini", {x = 14, y = 1}, 6},
    {"brown-hairy-grass", {x = 15, y = 1}, 2},
    {"brown-hairy-grass", {x = -13, y = 3}, 2},
    {"green-small-grass", {x = -12, y = 3}, 2},
    {"brown-asterisk-mini", {x = -12, y = 3}, 1},
    {"green-asterisk", {x = -10, y = 2}, 2},
    {"green-pita", {x = -10, y = 2}, 4},
    {"green-hairy-grass", {x = -9, y = 2}, 2},
    {"green-hairy-grass", {x = -9, y = 3}, 7},
    {"green-hairy-grass", {x = -3, y = 2}, 2},
    {"green-small-grass", {x = -3, y = 2}, 1},
    {"green-hairy-grass", {x = -3, y = 3}, 5},
    {"green-small-grass", {x = -3, y = 3}, 5},
    {"green-hairy-grass", {x = -2, y = 2}, 1},
    {"green-carpet-grass", {x = -2, y = 2}, 1},
    {"green-small-grass", {x = -2, y = 2}, 1},
    {"green-croton", {x = -2, y = 2}, 1},
    {"green-carpet-grass", {x = -1, y = 2}, 3},
    {"green-pita", {x = -2, y = 3}, 2},
    {"green-carpet-grass", {x = -1, y = 3}, 4},
    {"muddy-stump", {x = -1, y = 3}, 1},
    {"green-carpet-grass", {x = 0, y = 2}, 2},
    {"green-pita", {x = 1, y = 3}, 2},
    {"muddy-stump", {x = 2, y = 2}, 1},
    {"green-pita", {x = 3, y = 2}, 1},
    {"green-asterisk", {x = 3, y = 3}, 3},
    {"green-carpet-grass", {x = 4, y = 2}, 5},
    {"green-asterisk", {x = 5, y = 3}, 2},
    {"green-hairy-grass", {x = 7, y = 2}, 1},
    {"green-carpet-grass", {x = 7, y = 2}, 2},
    {"green-hairy-grass", {x = 9, y = 2}, 1},
    {"green-carpet-grass", {x = 9, y = 2}, 1},
    {"green-hairy-grass", {x = 9, y = 3}, 2},
    {"green-croton", {x = 10, y = 2}, 1},
    {"green-hairy-grass", {x = 10, y = 3}, 3},
    {"green-hairy-grass", {x = 11, y = 3}, 2},
    {"green-carpet-grass", {x = 11, y = 3}, 3},
    {"green-asterisk-mini", {x = 12, y = 2}, 2},
    {"green-asterisk-mini", {x = 13, y = 2}, 2},
    {"brown-asterisk-mini", {x = 14, y = 2}, 1},
    {"brown-asterisk-mini", {x = -12, y = 4}, 1},
    {"brown-asterisk-mini", {x = -12, y = 5}, 4},
    {"green-hairy-grass", {x = -9, y = 4}, 3},
    {"green-small-grass", {x = -9, y = 4}, 1},
    {"green-croton", {x = -9, y = 4}, 1},
    {"green-pita-mini", {x = -9, y = 4}, 1},
    {"green-hairy-grass", {x = -9, y = 5}, 3},
    {"green-small-grass", {x = -9, y = 5}, 5},
    {"green-hairy-grass", {x = -8, y = 5}, 4},
    {"green-croton", {x = -8, y = 5}, 4},
    {"green-hairy-grass", {x = -3, y = 4}, 6},
    {"green-hairy-grass", {x = -4, y = 5}, 3},
    {"green-hairy-grass", {x = -3, y = 5}, 3},
    {"green-carpet-grass", {x = -1, y = 4}, 6},
    {"green-pita", {x = -2, y = 5}, 3},
    {"green-carpet-grass", {x = -1, y = 5}, 5},
    {"green-carpet-grass", {x = 0, y = 5}, 1},
    {"muddy-stump", {x = 2, y = 4}, 1},
    {"green-carpet-grass", {x = 3, y = 4}, 4},
    {"brown-carpet-grass", {x = 3, y = 5}, 1},
    {"green-carpet-grass", {x = 4, y = 4}, 3},
    {"green-pita", {x = 4, y = 4}, 4},
    {"muddy-stump", {x = 5, y = 4}, 1},
    {"green-pita", {x = 5, y = 4}, 1},
    {"muddy-stump", {x = 5, y = 5}, 1},
    {"green-pita-mini", {x = 7, y = 4}, 2},
    {"green-hairy-grass", {x = 6, y = 5}, 1},
    {"green-hairy-grass", {x = 8, y = 4}, 1},
    {"green-hairy-grass", {x = 9, y = 4}, 2},
    {"green-hairy-grass", {x = 10, y = 4}, 1},
    {"green-carpet-grass", {x = 11, y = 4}, 2},
    {"green-hairy-grass", {x = 10, y = 5}, 2},
    {"green-carpet-grass", {x = 12, y = 4}, 2},
    {"green-pita", {x = 13, y = 4}, 1},
    {"green-carpet-grass", {x = 13, y = 5}, 2},
    {"brown-asterisk-mini", {x = -16, y = 7}, 3},
    {"brown-asterisk-mini", {x = -12, y = 6}, 1},
    {"brown-carpet-grass", {x = -11, y = 6}, 1},
    {"brown-asterisk-mini", {x = -12, y = 7}, 2},
    {"brown-hairy-grass", {x = -11, y = 7}, 2},
    {"brown-hairy-grass", {x = -10, y = 6}, 3},
    {"green-hairy-grass", {x = -9, y = 6}, 2},
    {"green-carpet-grass", {x = -9, y = 6}, 1},
    {"green-asterisk-mini", {x = -10, y = 7}, 1},
    {"green-hairy-grass", {x = -9, y = 7}, 3},
    {"muddy-stump", {x = -9, y = 7}, 1},
    {"green-hairy-grass", {x = -6, y = 6}, 2},
    {"green-carpet-grass", {x = -6, y = 6}, 4},
    {"green-hairy-grass", {x = -5, y = 6}, 3},
    {"green-hairy-grass", {x = -6, y = 7}, 1},
    {"green-carpet-grass", {x = -6, y = 7}, 2},
    {"green-hairy-grass", {x = -4, y = 6}, 5},
    {"green-hairy-grass", {x = -3, y = 6}, 2},
    {"muddy-stump", {x = -2, y = 6}, 1},
    {"green-asterisk", {x = -2, y = 6}, 3},
    {"brown-carpet-grass", {x = 0, y = 6}, 4},
    {"green-pita", {x = 0, y = 6}, 4},
    {"brown-carpet-grass", {x = 1, y = 6}, 1},
    {"green-pita", {x = 1, y = 6}, 2},
    {"green-pita-mini", {x = 1, y = 6}, 1},
    {"brown-hairy-grass", {x = 3, y = 6}, 3},
    {"green-carpet-grass", {x = 2, y = 7}, 1},
    {"green-carpet-grass", {x = 3, y = 7}, 3},
    {"green-asterisk-mini", {x = 3, y = 7}, 1},
    {"green-carpet-grass", {x = 4, y = 6}, 1},
    {"brown-hairy-grass", {x = 5, y = 6}, 3},
    {"brown-hairy-grass", {x = 4, y = 7}, 3},
    {"brown-hairy-grass", {x = 5, y = 7}, 3},
    {"muddy-stump", {x = 5, y = 7}, 1},
    {"brown-hairy-grass", {x = 6, y = 6}, 3},
    {"green-carpet-grass", {x = 7, y = 6}, 1},
    {"brown-hairy-grass", {x = 6, y = 7}, 2},
    {"green-small-grass", {x = 6, y = 7}, 1},
    {"brown-hairy-grass", {x = 7, y = 7}, 3},
    {"brown-asterisk-mini", {x = 8, y = 6}, 1},
    {"brown-asterisk-mini", {x = 9, y = 6}, 4},
    {"brown-asterisk-mini", {x = 9, y = 7}, 1},
    {"brown-hairy-grass", {x = 10, y = 6}, 3},
    {"brown-asterisk-mini", {x = 10, y = 6}, 1},
    {"brown-hairy-grass", {x = 11, y = 6}, 2},
    {"brown-fluff", {x = 11, y = 6}, 2},
    {"brown-asterisk-mini", {x = 10, y = 7}, 3},
    {"brown-carpet-grass", {x = 11, y = 7}, 2},
    {"garballo-mini-dry", {x = -13, y = 8}, 1},
    {"brown-hairy-grass", {x = -11, y = 8}, 4},
    {"brown-asterisk-mini", {x = -11, y = 9}, 1},
    {"green-asterisk-mini", {x = -10, y = 8}, 2},
    {"green-hairy-grass", {x = -9, y = 8}, 1},
    {"green-asterisk-mini", {x = -9, y = 8}, 4},
    {"green-hairy-grass", {x = -8, y = 8}, 2},
    {"green-carpet-grass", {x = -7, y = 8}, 2},
    {"green-hairy-grass", {x = -8, y = 9}, 5},
    {"green-hairy-grass", {x = -6, y = 8}, 3},
    {"green-hairy-grass", {x = -5, y = 8}, 2},
    {"green-hairy-grass", {x = -6, y = 9}, 4},
    {"green-pita", {x = -6, y = 9}, 1},
    {"green-hairy-grass", {x = -5, y = 9}, 3},
    {"green-hairy-grass", {x = -4, y = 8}, 1},
    {"green-asterisk", {x = -3, y = 8}, 1},
    {"green-asterisk", {x = -3, y = 9}, 2},
    {"green-pita-mini", {x = -2, y = 9}, 3},
    {"green-asterisk-mini", {x = -1, y = 9}, 1},
    {"green-pita-mini", {x = -1, y = 9}, 4},
    {"muddy-stump", {x = 1, y = 8}, 1},
    {"brown-carpet-grass", {x = 0, y = 9}, 1},
    {"green-carpet-grass", {x = 0, y = 9}, 1},
    {"green-small-grass", {x = 1, y = 9}, 1},
    {"brown-hairy-grass", {x = 2, y = 8}, 2},
    {"green-carpet-grass", {x = 2, y = 8}, 2},
    {"green-asterisk-mini", {x = 2, y = 8}, 2},
    {"brown-hairy-grass", {x = 3, y = 8}, 2},
    {"green-asterisk-mini", {x = 3, y = 8}, 2},
    {"brown-hairy-grass", {x = 2, y = 9}, 4},
    {"green-small-grass", {x = 2, y = 9}, 4},
    {"green-asterisk-mini", {x = 2, y = 9}, 2},
    {"brown-fluff", {x = 2, y = 9}, 2},
    {"green-small-grass", {x = 5, y = 8}, 2},
    {"red-asterisk", {x = 4, y = 9}, 1},
    {"green-small-grass", {x = 6, y = 8}, 3},
    {"brown-asterisk-mini", {x = 7, y = 8}, 1},
    {"brown-asterisk-mini", {x = 6, y = 9}, 1},
    {"brown-asterisk-mini", {x = 7, y = 9}, 1},
    {"brown-asterisk-mini", {x = 8, y = 8}, 1},
    {"brown-carpet-grass", {x = 9, y = 9}, 5},
    {"brown-carpet-grass", {x = 10, y = 9}, 1},
    {"brown-fluff-dry", {x = -15, y = 11}, 1},
    {"brown-asterisk-mini", {x = -11, y = 10}, 2},
    {"red-croton", {x = -11, y = 10}, 2},
    {"brown-asterisk-mini", {x = -11, y = 11}, 4},
    {"brown-fluff", {x = -11, y = 11}, 1},
    {"brown-hairy-grass", {x = -10, y = 11}, 3},
    {"green-hairy-grass", {x = -6, y = 10}, 2},
    {"green-carpet-grass", {x = -6, y = 10}, 4},
    {"green-pita", {x = -5, y = 10}, 1},
    {"green-carpet-grass", {x = -6, y = 11}, 3},
    {"green-pita", {x = -6, y = 11}, 1},
    {"green-croton", {x = -4, y = 11}, 1},
    {"green-carpet-grass", {x = -1, y = 10}, 3},
    {"green-asterisk-mini", {x = -1, y = 10}, 1},
    {"brown-hairy-grass", {x = -2, y = 11}, 2},
    {"green-asterisk-mini", {x = -1, y = 11}, 7},
    {"brown-hairy-grass", {x = 0, y = 10}, 2},
    {"green-carpet-grass", {x = 0, y = 10}, 1},
    {"brown-hairy-grass", {x = 1, y = 10}, 3},
    {"green-small-grass", {x = 1, y = 10}, 2},
    {"brown-asterisk-mini", {x = 0, y = 11}, 1},
    {"brown-carpet-grass", {x = 1, y = 11}, 2},
    {"brown-asterisk-mini", {x = 1, y = 11}, 3},
    {"brown-asterisk-mini", {x = 2, y = 10}, 2},
    {"brown-asterisk-mini", {x = 3, y = 10}, 1},
    {"brown-asterisk-mini", {x = 2, y = 11}, 2},
    {"green-small-grass", {x = 3, y = 11}, 1},
    {"brown-asterisk-mini", {x = 4, y = 10}, 1},
    {"brown-carpet-grass", {x = 5, y = 10}, 2},
    {"brown-asterisk-mini", {x = 5, y = 10}, 2},
    {"brown-carpet-grass", {x = 5, y = 11}, 4},
    {"brown-carpet-grass", {x = -10, y = 12}, 3},
    {"brown-hairy-grass", {x = -9, y = 13}, 1},
    {"green-hairy-grass", {x = -7, y = 12}, 5},
    {"green-hairy-grass", {x = -6, y = 12}, 2},
    {"brown-asterisk-mini", {x = -6, y = 13}, 1},
    {"brown-asterisk-mini", {x = -5, y = 13}, 2},
    {"brown-asterisk-mini", {x = -4, y = 13}, 4},
    {"brown-asterisk-mini", {x = -3, y = 13}, 1},
    {"brown-hairy-grass", {x = -2, y = 12}, 4},
    {"brown-carpet-grass", {x = -2, y = 12}, 1},
    {"brown-asterisk-mini", {x = 0, y = 12}, 2},
    {"brown-asterisk-mini", {x = 1, y = 12}, 1},
    {"green-small-grass", {x = 2, y = 12}, 1},
    {"brown-asterisk-mini", {x = 2, y = 12}, 2},
    {"brown-asterisk-mini", {x = 2, y = 13}, 3},
    {"brown-carpet-grass", {x = -5, y = 14}, 1},
    {"garballo-mini-dry", {x = 10, y = 14}, 1},
  },
}
