return
{
  entities =
  {
    {"tree-08", {x = -10.75, y = -15.57}, {}},
    {"tree-05", {x = -7.03, y = -12.01}, {}},
    {"tree-08-red", {x = -3.89, y = -12.77}, {}},
    {"dead-tree-desert", {x = 12.98, y = -12.8}, {}},
    {"tree-01", {x = -12.86, y = -10.63}, {}},
    {"dead-grey-trunk", {x = 5.88, y = -10.98}, {}},
    {"tree-02", {x = -5.09, y = -8.73}, {}},
    {"tree-01", {x = -10.89, y = -5.98}, {}},
    {"tree-08-red", {x = -14.07, y = -3.63}, {}},
    {"tree-05", {x = -2.68, y = -4.32}, {}},
    {"dead-grey-trunk", {x = 10.5, y = -3.49}, {}},
    {"tree-07", {x = -8.79, y = -3.11}, {}},
    {"tree-07", {x = -1.06, y = -2.04}, {}},
    {"tree-08-red", {x = 5.22, y = -1.45}, {}},
    {"dead-grey-trunk", {x = -13.51, y = 1.58}, {}},
    {"tree-02", {x = -7.79, y = 0.65}, {}},
    {"tree-02", {x = 1.18, y = 0.55}, {}},
    {"tree-08", {x = 2.46, y = 3.24}, {}},
    {"tree-09-brown", {x = 11.33, y = 3.45}, {}},
    {"tree-08", {x = -3.54, y = 5.1}, {}},
    {"tree-05", {x = 5.6, y = 4.55}, {}},
    {"dead-grey-trunk", {x = 8.88, y = 4.96}, {}},
    {"dry-tree", {x = -13.65, y = 6.89}, {}},
    {"tree-09-brown", {x = -8.51, y = 7}, {}},
    {"tree-01", {x = -0.64, y = 8.38}, {}},
    {"tree-05", {x = 12.91, y = 8.14}, {}},
    {"tree-07", {x = 3.63, y = 9.62}, {}},
    {"dry-tree", {x = 1.98, y = 12.48}, {}},
    {"dry-tree", {x = -13.62, y = 13.66}, {}},
    {"dead-tree-desert", {x = -9.65, y = 12.79}, {}},
    {"tree-08", {x = 10.5, y = 12.83}, {}},
  },
  tiles =
  {
    {"grass-2", {x = -16, y = -16}},
    {"grass-1", {x = -16, y = -15}},
    {"grass-1", {x = -16, y = -14}},
    {"grass-1", {x = -16, y = -13}},
    {"grass-3", {x = -16, y = -12}},
    {"grass-3", {x = -16, y = -11}},
    {"grass-3", {x = -16, y = -10}},
    {"grass-1", {x = -16, y = -8}},
    {"grass-4", {x = -16, y = -7}},
    {"grass-4", {x = -16, y = -6}},
    {"grass-4", {x = -16, y = -5}},
    {"grass-2", {x = -15, y = -16}},
    {"water-shallow", {x = -15, y = -15}},
    {"grass-2", {x = -15, y = -14}},
    {"grass-1", {x = -15, y = -13}},
    {"grass-1", {x = -15, y = -12}},
    {"grass-3", {x = -15, y = -11}},
    {"grass-3", {x = -15, y = -10}},
    {"grass-3", {x = -15, y = -9}},
    {"grass-1", {x = -15, y = -8}},
    {"grass-4", {x = -15, y = -7}},
    {"grass-4", {x = -15, y = -6}},
    {"grass-4", {x = -15, y = -5}},
    {"grass-4", {x = -15, y = -4}},
    {"grass-4", {x = -15, y = -3}},
    {"water-shallow", {x = -14, y = -16}},
    {"water-shallow", {x = -14, y = -15}},
    {"water-shallow", {x = -14, y = -14}},
    {"grass-2", {x = -14, y = -13}},
    {"grass-1", {x = -14, y = -12}},
    {"grass-1", {x = -14, y = -11}},
    {"grass-3", {x = -14, y = -10}},
    {"grass-3", {x = -14, y = -9}},
    {"grass-3", {x = -14, y = -8}},
    {"grass-1", {x = -14, y = -7}},
    {"grass-4", {x = -14, y = -6}},
    {"grass-4", {x = -14, y = -5}},
    {"grass-4", {x = -14, y = -4}},
    {"grass-4", {x = -14, y = -3}},
    {"grass-4", {x = -14, y = -2}},
    {"grass-4", {x = -14, y = -1}},
    {"grass-4", {x = -14, y = 0}},
    {"grass-2", {x = -13, y = -16}},
    {"water-shallow", {x = -13, y = -15}},
    {"water-shallow", {x = -13, y = -14}},
    {"water-shallow", {x = -13, y = -13}},
    {"grass-2", {x = -13, y = -12}},
    {"grass-1", {x = -13, y = -11}},
    {"grass-1", {x = -13, y = -10}},
    {"grass-1", {x = -13, y = -9}},
    {"grass-3", {x = -13, y = -8}},
    {"grass-3", {x = -13, y = -7}},
    {"grass-3", {x = -13, y = -6}},
    {"grass-4", {x = -13, y = -5}},
    {"grass-4", {x = -13, y = -4}},
    {"grass-4", {x = -13, y = -3}},
    {"grass-4", {x = -13, y = -2}},
    {"grass-4", {x = -13, y = -1}},
    {"grass-4", {x = -13, y = 0}},
    {"grass-4", {x = -13, y = 1}},
    {"grass-2", {x = -12, y = -16}},
    {"grass-2", {x = -12, y = -15}},
    {"water-mud", {x = -12, y = -14}},
    {"water-shallow", {x = -12, y = -13}},
    {"water-shallow", {x = -12, y = -12}},
    {"water-shallow", {x = -12, y = -11}},
    {"grass-1", {x = -12, y = -10}},
    {"grass-1", {x = -12, y = -9}},
    {"grass-1", {x = -12, y = -8}},
    {"grass-1", {x = -12, y = -7}},
    {"grass-3", {x = -12, y = -6}},
    {"grass-3", {x = -12, y = -5}},
    {"grass-3", {x = -12, y = -4}},
    {"grass-4", {x = -12, y = -3}},
    {"grass-4", {x = -12, y = -2}},
    {"grass-4", {x = -12, y = -1}},
    {"grass-4", {x = -12, y = 0}},
    {"grass-4", {x = -12, y = 1}},
    {"grass-4", {x = -12, y = 2}},
    {"grass-4", {x = -12, y = 3}},
    {"grass-2", {x = -11, y = -16}},
    {"water-mud", {x = -11, y = -15}},
    {"water-shallow", {x = -11, y = -14}},
    {"water-mud", {x = -11, y = -13}},
    {"water-shallow", {x = -11, y = -12}},
    {"water-shallow", {x = -11, y = -11}},
    {"water-shallow", {x = -11, y = -10}},
    {"grass-1", {x = -11, y = -9}},
    {"grass-1", {x = -11, y = -8}},
    {"grass-1", {x = -11, y = -7}},
    {"grass-1", {x = -11, y = -6}},
    {"grass-3", {x = -11, y = -5}},
    {"grass-3", {x = -11, y = -4}},
    {"grass-3", {x = -11, y = -3}},
    {"grass-3", {x = -11, y = -2}},
    {"grass-3", {x = -11, y = -1}},
    {"grass-4", {x = -11, y = 0}},
    {"grass-4", {x = -11, y = 2}},
    {"grass-4", {x = -11, y = 3}},
    {"grass-4", {x = -11, y = 4}},
    {"grass-4", {x = -11, y = 6}},
    {"grass-2", {x = -10, y = -16}},
    {"grass-2", {x = -10, y = -15}},
    {"water-mud", {x = -10, y = -14}},
    {"water-mud", {x = -10, y = -13}},
    {"water-shallow", {x = -10, y = -12}},
    {"water-mud", {x = -10, y = -11}},
    {"water-shallow", {x = -10, y = -10}},
    {"water-shallow", {x = -10, y = -9}},
    {"grass-2", {x = -10, y = -8}},
    {"grass-1", {x = -10, y = -7}},
    {"grass-1", {x = -10, y = -6}},
    {"grass-1", {x = -10, y = -5}},
    {"grass-1", {x = -10, y = -4}},
    {"grass-3", {x = -10, y = -3}},
    {"grass-3", {x = -10, y = -2}},
    {"grass-3", {x = -10, y = -1}},
    {"grass-3", {x = -10, y = 0}},
    {"grass-3", {x = -10, y = 1}},
    {"grass-4", {x = -10, y = 2}},
    {"grass-4", {x = -10, y = 3}},
    {"grass-4", {x = -10, y = 4}},
    {"grass-4", {x = -10, y = 5}},
    {"grass-4", {x = -10, y = 6}},
    {"grass-4", {x = -10, y = 7}},
    {"grass-1", {x = -9, y = -16}},
    {"grass-1", {x = -9, y = -15}},
    {"grass-2", {x = -9, y = -14}},
    {"grass-2", {x = -9, y = -13}},
    {"water-shallow", {x = -9, y = -12}},
    {"water-shallow", {x = -9, y = -11}},
    {"water-shallow", {x = -9, y = -10}},
    {"water-shallow", {x = -9, y = -9}},
    {"water-mud", {x = -9, y = -8}},
    {"water-mud", {x = -9, y = -7}},
    {"water-shallow", {x = -9, y = -6}},
    {"water-shallow", {x = -9, y = -5}},
    {"grass-1", {x = -9, y = -4}},
    {"grass-1", {x = -9, y = -3}},
    {"grass-1", {x = -9, y = -2}},
    {"grass-1", {x = -9, y = -1}},
    {"grass-1", {x = -9, y = 0}},
    {"grass-3", {x = -9, y = 1}},
    {"grass-3", {x = -9, y = 2}},
    {"grass-3", {x = -9, y = 3}},
    {"grass-4", {x = -9, y = 4}},
    {"grass-4", {x = -9, y = 5}},
    {"grass-4", {x = -9, y = 6}},
    {"grass-4", {x = -9, y = 7}},
    {"grass-4", {x = -9, y = 8}},
    {"grass-3", {x = -8, y = -16}},
    {"grass-1", {x = -8, y = -15}},
    {"grass-1", {x = -8, y = -14}},
    {"grass-1", {x = -8, y = -13}},
    {"grass-2", {x = -8, y = -12}},
    {"water-mud", {x = -8, y = -11}},
    {"water-shallow", {x = -8, y = -10}},
    {"water-shallow", {x = -8, y = -9}},
    {"water-shallow", {x = -8, y = -8}},
    {"water-shallow", {x = -8, y = -7}},
    {"water-mud", {x = -8, y = -6}},
    {"water-shallow", {x = -8, y = -5}},
    {"water-shallow", {x = -8, y = -4}},
    {"water-shallow", {x = -8, y = -3}},
    {"water-shallow", {x = -8, y = -2}},
    {"grass-1", {x = -8, y = -1}},
    {"grass-1", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-3", {x = -8, y = 3}},
    {"grass-3", {x = -8, y = 4}},
    {"grass-3", {x = -8, y = 5}},
    {"grass-4", {x = -8, y = 6}},
    {"grass-4", {x = -8, y = 7}},
    {"grass-4", {x = -8, y = 8}},
    {"grass-3", {x = -7, y = -16}},
    {"grass-3", {x = -7, y = -15}},
    {"grass-3", {x = -7, y = -14}},
    {"grass-1", {x = -7, y = -13}},
    {"grass-1", {x = -7, y = -12}},
    {"grass-1", {x = -7, y = -11}},
    {"grass-2", {x = -7, y = -10}},
    {"water-mud", {x = -7, y = -9}},
    {"water-shallow", {x = -7, y = -8}},
    {"water-shallow", {x = -7, y = -7}},
    {"water-shallow", {x = -7, y = -6}},
    {"water-mud", {x = -7, y = -5}},
    {"water-mud", {x = -7, y = -4}},
    {"water-mud", {x = -7, y = -3}},
    {"water-shallow", {x = -7, y = -2}},
    {"water-shallow", {x = -7, y = -1}},
    {"grass-2", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-3", {x = -7, y = 4}},
    {"grass-3", {x = -7, y = 5}},
    {"grass-3", {x = -7, y = 6}},
    {"grass-4", {x = -7, y = 9}},
    {"grass-3", {x = -6, y = -15}},
    {"grass-3", {x = -6, y = -14}},
    {"grass-3", {x = -6, y = -13}},
    {"grass-1", {x = -6, y = -12}},
    {"grass-1", {x = -6, y = -11}},
    {"grass-1", {x = -6, y = -10}},
    {"grass-2", {x = -6, y = -9}},
    {"grass-2", {x = -6, y = -8}},
    {"grass-2", {x = -6, y = -7}},
    {"water-shallow", {x = -6, y = -6}},
    {"water-shallow", {x = -6, y = -5}},
    {"water-shallow", {x = -6, y = -4}},
    {"water-shallow", {x = -6, y = -3}},
    {"water-mud", {x = -6, y = -2}},
    {"water-mud", {x = -6, y = -1}},
    {"water-mud", {x = -6, y = 0}},
    {"water-shallow", {x = -6, y = 1}},
    {"grass-2", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-3", {x = -6, y = 5}},
    {"grass-3", {x = -6, y = 6}},
    {"grass-4", {x = -6, y = 7}},
    {"grass-4", {x = -6, y = 8}},
    {"grass-4", {x = -6, y = 9}},
    {"grass-4", {x = -6, y = 10}},
    {"grass-4", {x = -5, y = -16}},
    {"grass-4", {x = -5, y = -15}},
    {"grass-4", {x = -5, y = -14}},
    {"grass-3", {x = -5, y = -13}},
    {"grass-3", {x = -5, y = -12}},
    {"grass-3", {x = -5, y = -11}},
    {"grass-3", {x = -5, y = -10}},
    {"grass-1", {x = -5, y = -9}},
    {"grass-2", {x = -5, y = -8}},
    {"grass-2", {x = -5, y = -7}},
    {"grass-2", {x = -5, y = -6}},
    {"grass-2", {x = -5, y = -5}},
    {"grass-2", {x = -5, y = -4}},
    {"water-shallow", {x = -5, y = -3}},
    {"water-mud", {x = -5, y = -2}},
    {"water-shallow", {x = -5, y = -1}},
    {"water-shallow", {x = -5, y = 0}},
    {"water-shallow", {x = -5, y = 1}},
    {"grass-2", {x = -5, y = 2}},
    {"grass-2", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-3", {x = -5, y = 6}},
    {"grass-3", {x = -5, y = 7}},
    {"grass-4", {x = -5, y = 8}},
    {"grass-4", {x = -5, y = 9}},
    {"grass-4", {x = -5, y = 10}},
    {"grass-4", {x = -4, y = -16}},
    {"grass-4", {x = -4, y = -15}},
    {"grass-4", {x = -4, y = -14}},
    {"grass-4", {x = -4, y = -13}},
    {"grass-3", {x = -4, y = -12}},
    {"grass-3", {x = -4, y = -11}},
    {"grass-3", {x = -4, y = -10}},
    {"grass-3", {x = -4, y = -9}},
    {"grass-3", {x = -4, y = -8}},
    {"grass-3", {x = -4, y = -7}},
    {"grass-2", {x = -4, y = -6}},
    {"grass-2", {x = -4, y = -5}},
    {"grass-2", {x = -4, y = -4}},
    {"grass-2", {x = -4, y = -3}},
    {"water-shallow", {x = -4, y = -2}},
    {"water-shallow", {x = -4, y = -1}},
    {"water-shallow", {x = -4, y = 0}},
    {"water-shallow", {x = -4, y = 1}},
    {"water-shallow", {x = -4, y = 2}},
    {"water-shallow", {x = -4, y = 3}},
    {"grass-2", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-3", {x = -4, y = 6}},
    {"grass-3", {x = -4, y = 7}},
    {"grass-4", {x = -4, y = 8}},
    {"grass-4", {x = -4, y = 9}},
    {"grass-4", {x = -4, y = 10}},
    {"grass-4", {x = -4, y = 11}},
    {"grass-4", {x = -3, y = -15}},
    {"grass-4", {x = -3, y = -13}},
    {"grass-4", {x = -3, y = -12}},
    {"grass-3", {x = -3, y = -11}},
    {"grass-3", {x = -3, y = -10}},
    {"grass-3", {x = -3, y = -9}},
    {"grass-3", {x = -3, y = -8}},
    {"grass-3", {x = -3, y = -7}},
    {"grass-3", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-2", {x = -3, y = -3}},
    {"grass-2", {x = -3, y = -2}},
    {"grass-2", {x = -3, y = -1}},
    {"water-shallow", {x = -3, y = 0}},
    {"water-shallow", {x = -3, y = 1}},
    {"water-shallow", {x = -3, y = 2}},
    {"water-shallow", {x = -3, y = 3}},
    {"water-shallow", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -3, y = 6}},
    {"grass-3", {x = -3, y = 7}},
    {"grass-3", {x = -3, y = 8}},
    {"grass-4", {x = -3, y = 9}},
    {"grass-4", {x = -3, y = 10}},
    {"grass-4", {x = -3, y = 11}},
    {"grass-4", {x = -3, y = 12}},
    {"grass-4", {x = -2, y = -15}},
    {"grass-4", {x = -2, y = -14}},
    {"grass-4", {x = -2, y = -13}},
    {"grass-4", {x = -2, y = -12}},
    {"grass-4", {x = -2, y = -11}},
    {"grass-3", {x = -2, y = -10}},
    {"grass-3", {x = -2, y = -9}},
    {"grass-3", {x = -2, y = -8}},
    {"grass-3", {x = -2, y = -7}},
    {"grass-3", {x = -2, y = -6}},
    {"grass-3", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-2", {x = -2, y = 0}},
    {"water-mud", {x = -2, y = 1}},
    {"water-shallow", {x = -2, y = 2}},
    {"water-shallow", {x = -2, y = 3}},
    {"water-shallow", {x = -2, y = 4}},
    {"grass-2", {x = -2, y = 5}},
    {"grass-1", {x = -2, y = 6}},
    {"grass-1", {x = -2, y = 7}},
    {"grass-3", {x = -2, y = 8}},
    {"grass-3", {x = -2, y = 9}},
    {"grass-4", {x = -2, y = 10}},
    {"grass-4", {x = -2, y = 12}},
    {"grass-4", {x = -1, y = -14}},
    {"grass-4", {x = -1, y = -13}},
    {"grass-4", {x = -1, y = -12}},
    {"grass-4", {x = -1, y = -10}},
    {"grass-4", {x = -1, y = -9}},
    {"grass-3", {x = -1, y = -8}},
    {"grass-3", {x = -1, y = -7}},
    {"grass-3", {x = -1, y = -6}},
    {"grass-3", {x = -1, y = -5}},
    {"grass-3", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"water-shallow", {x = -1, y = 1}},
    {"water-mud", {x = -1, y = 2}},
    {"water-shallow", {x = -1, y = 3}},
    {"water-shallow", {x = -1, y = 4}},
    {"water-mud", {x = -1, y = 5}},
    {"grass-1", {x = -1, y = 6}},
    {"grass-1", {x = -1, y = 7}},
    {"grass-3", {x = -1, y = 8}},
    {"grass-3", {x = -1, y = 9}},
    {"grass-4", {x = -1, y = 10}},
    {"grass-4", {x = -1, y = 11}},
    {"grass-4", {x = -1, y = 12}},
    {"grass-4", {x = -1, y = 13}},
    {"grass-4", {x = 0, y = -10}},
    {"grass-4", {x = 0, y = -9}},
    {"grass-3", {x = 0, y = -7}},
    {"grass-3", {x = 0, y = -6}},
    {"grass-3", {x = 0, y = -5}},
    {"grass-3", {x = 0, y = -4}},
    {"grass-3", {x = 0, y = -3}},
    {"grass-3", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-2", {x = 0, y = 2}},
    {"water-mud", {x = 0, y = 3}},
    {"water-shallow", {x = 0, y = 4}},
    {"water-shallow", {x = 0, y = 5}},
    {"grass-2", {x = 0, y = 6}},
    {"grass-1", {x = 0, y = 7}},
    {"grass-1", {x = 0, y = 8}},
    {"grass-3", {x = 0, y = 9}},
    {"grass-3", {x = 0, y = 10}},
    {"grass-4", {x = 0, y = 11}},
    {"grass-4", {x = 0, y = 12}},
    {"grass-4", {x = 0, y = 13}},
    {"grass-4", {x = 1, y = -8}},
    {"grass-4", {x = 1, y = -7}},
    {"grass-3", {x = 1, y = -6}},
    {"grass-3", {x = 1, y = -5}},
    {"grass-3", {x = 1, y = -4}},
    {"grass-3", {x = 1, y = -3}},
    {"grass-3", {x = 1, y = -2}},
    {"grass-3", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-2", {x = 1, y = 2}},
    {"water-mud", {x = 1, y = 3}},
    {"water-shallow", {x = 1, y = 4}},
    {"water-shallow", {x = 1, y = 5}},
    {"water-shallow", {x = 1, y = 6}},
    {"grass-1", {x = 1, y = 7}},
    {"grass-1", {x = 1, y = 8}},
    {"grass-3", {x = 1, y = 9}},
    {"grass-3", {x = 1, y = 10}},
    {"grass-3", {x = 1, y = 11}},
    {"grass-4", {x = 1, y = 12}},
    {"grass-4", {x = 1, y = 13}},
    {"grass-4", {x = 1, y = 14}},
    {"grass-4", {x = 2, y = -7}},
    {"grass-4", {x = 2, y = -6}},
    {"grass-4", {x = 2, y = -5}},
    {"grass-4", {x = 2, y = -4}},
    {"grass-4", {x = 2, y = -3}},
    {"grass-3", {x = 2, y = -2}},
    {"grass-3", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-2", {x = 2, y = 3}},
    {"water-mud", {x = 2, y = 4}},
    {"water-shallow", {x = 2, y = 5}},
    {"water-shallow", {x = 2, y = 6}},
    {"grass-2", {x = 2, y = 7}},
    {"grass-1", {x = 2, y = 8}},
    {"grass-1", {x = 2, y = 9}},
    {"grass-3", {x = 2, y = 10}},
    {"grass-3", {x = 2, y = 11}},
    {"grass-4", {x = 2, y = 12}},
    {"grass-4", {x = 2, y = 13}},
    {"grass-4", {x = 2, y = 14}},
    {"grass-4", {x = 3, y = -5}},
    {"grass-4", {x = 3, y = -4}},
    {"grass-4", {x = 3, y = -2}},
    {"grass-3", {x = 3, y = -1}},
    {"grass-3", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-2", {x = 3, y = 3}},
    {"water-mud", {x = 3, y = 4}},
    {"water-shallow", {x = 3, y = 5}},
    {"water-shallow", {x = 3, y = 6}},
    {"water-mud", {x = 3, y = 7}},
    {"grass-1", {x = 3, y = 8}},
    {"grass-1", {x = 3, y = 9}},
    {"grass-3", {x = 3, y = 10}},
    {"grass-3", {x = 3, y = 11}},
    {"grass-3", {x = 3, y = 12}},
    {"grass-4", {x = 3, y = 13}},
    {"grass-4", {x = 3, y = 14}},
    {"grass-4", {x = 3, y = 15}},
    {"grass-4", {x = 4, y = -4}},
    {"grass-4", {x = 4, y = -3}},
    {"grass-4", {x = 4, y = -2}},
    {"grass-4", {x = 4, y = -1}},
    {"grass-3", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-2", {x = 4, y = 3}},
    {"grass-2", {x = 4, y = 4}},
    {"water-mud", {x = 4, y = 5}},
    {"water-shallow", {x = 4, y = 6}},
    {"water-shallow", {x = 4, y = 7}},
    {"grass-2", {x = 4, y = 8}},
    {"grass-1", {x = 4, y = 9}},
    {"grass-1", {x = 4, y = 10}},
    {"grass-3", {x = 4, y = 11}},
    {"grass-3", {x = 4, y = 12}},
    {"grass-4", {x = 4, y = 13}},
    {"grass-4", {x = 4, y = 15}},
    {"grass-4", {x = 5, y = -3}},
    {"grass-4", {x = 5, y = -2}},
    {"grass-4", {x = 5, y = -1}},
    {"grass-4", {x = 5, y = 0}},
    {"grass-3", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-2", {x = 5, y = 4}},
    {"water-mud", {x = 5, y = 5}},
    {"water-shallow", {x = 5, y = 6}},
    {"water-mud", {x = 5, y = 7}},
    {"water-mud", {x = 5, y = 8}},
    {"grass-2", {x = 5, y = 9}},
    {"grass-1", {x = 5, y = 10}},
    {"grass-1", {x = 5, y = 11}},
    {"grass-3", {x = 5, y = 12}},
    {"grass-3", {x = 5, y = 13}},
    {"grass-4", {x = 5, y = 14}},
    {"grass-4", {x = 5, y = 15}},
    {"grass-4", {x = 6, y = -2}},
    {"grass-4", {x = 6, y = -1}},
    {"grass-4", {x = 6, y = 0}},
    {"grass-3", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-2", {x = 6, y = 5}},
    {"water-mud", {x = 6, y = 6}},
    {"water-shallow", {x = 6, y = 7}},
    {"water-shallow", {x = 6, y = 8}},
    {"grass-2", {x = 6, y = 9}},
    {"grass-1", {x = 6, y = 10}},
    {"grass-1", {x = 6, y = 11}},
    {"grass-3", {x = 6, y = 12}},
    {"grass-3", {x = 6, y = 13}},
    {"grass-4", {x = 6, y = 14}},
    {"grass-4", {x = 6, y = 15}},
    {"grass-4", {x = 7, y = -2}},
    {"grass-4", {x = 7, y = -1}},
    {"grass-4", {x = 7, y = 0}},
    {"grass-3", {x = 7, y = 1}},
    {"grass-3", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-2", {x = 7, y = 5}},
    {"water-shallow", {x = 7, y = 6}},
    {"water-shallow", {x = 7, y = 7}},
    {"water-mud", {x = 7, y = 8}},
    {"water-mud", {x = 7, y = 9}},
    {"grass-2", {x = 7, y = 10}},
    {"grass-1", {x = 7, y = 11}},
    {"grass-1", {x = 7, y = 12}},
    {"grass-3", {x = 7, y = 13}},
    {"grass-3", {x = 7, y = 14}},
    {"grass-4", {x = 7, y = 15}},
    {"grass-4", {x = 8, y = -1}},
    {"grass-4", {x = 8, y = 1}},
    {"grass-3", {x = 8, y = 2}},
    {"grass-1", {x = 8, y = 3}},
    {"grass-1", {x = 8, y = 4}},
    {"grass-1", {x = 8, y = 5}},
    {"grass-2", {x = 8, y = 6}},
    {"water-shallow", {x = 8, y = 7}},
    {"water-shallow", {x = 8, y = 8}},
    {"water-mud", {x = 8, y = 9}},
    {"grass-2", {x = 8, y = 10}},
    {"grass-2", {x = 8, y = 11}},
    {"grass-1", {x = 8, y = 12}},
    {"grass-3", {x = 8, y = 13}},
    {"grass-3", {x = 8, y = 14}},
    {"grass-4", {x = 8, y = 15}},
    {"grass-4", {x = 9, y = -1}},
    {"grass-4", {x = 9, y = 0}},
    {"grass-4", {x = 9, y = 1}},
    {"grass-3", {x = 9, y = 2}},
    {"grass-3", {x = 9, y = 3}},
    {"grass-1", {x = 9, y = 4}},
    {"grass-1", {x = 9, y = 5}},
    {"grass-1", {x = 9, y = 6}},
    {"water-shallow", {x = 9, y = 7}},
    {"water-shallow", {x = 9, y = 8}},
    {"water-mud", {x = 9, y = 9}},
    {"water-mud", {x = 9, y = 10}},
    {"grass-2", {x = 9, y = 11}},
    {"water-shallow", {x = 9, y = 12}},
    {"grass-1", {x = 9, y = 13}},
    {"grass-3", {x = 9, y = 14}},
    {"grass-4", {x = 9, y = 15}},
    {"grass-4", {x = 10, y = 0}},
    {"grass-4", {x = 10, y = 1}},
    {"grass-4", {x = 10, y = 2}},
    {"grass-3", {x = 10, y = 3}},
    {"grass-3", {x = 10, y = 4}},
    {"grass-1", {x = 10, y = 5}},
    {"grass-1", {x = 10, y = 6}},
    {"grass-2", {x = 10, y = 7}},
    {"water-mud", {x = 10, y = 8}},
    {"water-mud", {x = 10, y = 9}},
    {"water-mud", {x = 10, y = 10}},
    {"grass-2", {x = 10, y = 11}},
    {"grass-2", {x = 10, y = 12}},
    {"grass-2", {x = 10, y = 13}},
    {"grass-3", {x = 10, y = 14}},
    {"grass-4", {x = 10, y = 15}},
    {"grass-4", {x = 11, y = 1}},
    {"grass-4", {x = 11, y = 2}},
    {"grass-4", {x = 11, y = 3}},
    {"grass-3", {x = 11, y = 4}},
    {"grass-3", {x = 11, y = 5}},
    {"grass-1", {x = 11, y = 6}},
    {"grass-1", {x = 11, y = 7}},
    {"grass-2", {x = 11, y = 8}},
    {"water-mud", {x = 11, y = 9}},
    {"water-mud", {x = 11, y = 10}},
    {"grass-2", {x = 11, y = 11}},
    {"grass-2", {x = 11, y = 12}},
    {"grass-2", {x = 11, y = 13}},
    {"grass-2", {x = 11, y = 14}},
    {"grass-4", {x = 11, y = 15}},
    {"grass-4", {x = 12, y = 1}},
    {"grass-4", {x = 12, y = 2}},
    {"grass-4", {x = 12, y = 3}},
    {"grass-3", {x = 12, y = 4}},
    {"grass-3", {x = 12, y = 5}},
    {"grass-1", {x = 12, y = 6}},
    {"grass-1", {x = 12, y = 7}},
    {"grass-1", {x = 12, y = 8}},
    {"grass-2", {x = 12, y = 9}},
    {"grass-2", {x = 12, y = 10}},
    {"grass-2", {x = 12, y = 11}},
    {"grass-2", {x = 12, y = 12}},
    {"grass-3", {x = 12, y = 13}},
    {"grass-2", {x = 12, y = 14}},
    {"grass-4", {x = 13, y = 1}},
    {"grass-4", {x = 13, y = 2}},
    {"grass-4", {x = 13, y = 3}},
    {"grass-4", {x = 13, y = 4}},
    {"grass-3", {x = 13, y = 5}},
    {"grass-3", {x = 13, y = 6}},
    {"grass-1", {x = 13, y = 7}},
    {"grass-1", {x = 13, y = 8}},
    {"water-shallow", {x = 13, y = 9}},
    {"grass-3", {x = 13, y = 10}},
    {"grass-3", {x = 13, y = 11}},
    {"grass-3", {x = 13, y = 12}},
    {"grass-3", {x = 13, y = 13}},
    {"water-shallow", {x = 13, y = 14}},
    {"grass-4", {x = 13, y = 15}},
    {"grass-4", {x = 14, y = 3}},
    {"grass-4", {x = 14, y = 4}},
    {"grass-3", {x = 14, y = 5}},
    {"grass-3", {x = 14, y = 6}},
    {"grass-3", {x = 14, y = 7}},
    {"grass-3", {x = 14, y = 8}},
    {"grass-3", {x = 14, y = 9}},
    {"grass-3", {x = 14, y = 10}},
    {"grass-3", {x = 14, y = 11}},
    {"grass-3", {x = 14, y = 12}},
    {"grass-2", {x = 14, y = 13}},
    {"grass-4", {x = 14, y = 14}},
    {"grass-4", {x = 14, y = 15}},
    {"grass-4", {x = 15, y = 2}},
    {"grass-4", {x = 15, y = 3}},
    {"grass-4", {x = 15, y = 4}},
    {"grass-4", {x = 15, y = 6}},
    {"grass-3", {x = 15, y = 7}},
    {"grass-3", {x = 15, y = 8}},
    {"grass-1", {x = 15, y = 9}},
    {"grass-4", {x = 15, y = 10}},
    {"grass-4", {x = 15, y = 11}},
    {"grass-2", {x = 15, y = 13}},
    {"grass-4", {x = 15, y = 14}},
    {"grass-2", {x = 15, y = 15}},
  },
  decoratives =
  {
    {"green-hairy-grass", {x = -15, y = -16}, 6},
    {"green-hairy-grass", {x = -15, y = -15}, 4},
    {"green-hairy-grass", {x = -13, y = -16}, 2},
    {"red-croton", {x = -13, y = -15}, 1},
    {"green-hairy-grass", {x = -12, y = -16}, 2},
    {"green-hairy-grass", {x = -12, y = -15}, 2},
    {"green-hairy-grass", {x = -11, y = -15}, 7},
    {"green-asterisk-mini", {x = -10, y = -15}, 6},
    {"green-bush-mini", {x = -9, y = -15}, 2},
    {"brown-asterisk-mini", {x = -8, y = -16}, 3},
    {"green-pita-mini", {x = -8, y = -15}, 3},
    {"brown-asterisk-mini", {x = -7, y = -15}, 2},
    {"green-pita-mini", {x = -7, y = -15}, 1},
    {"brown-asterisk-mini", {x = -6, y = -15}, 1},
    {"green-hairy-grass", {x = -15, y = -14}, 4},
    {"green-asterisk-mini", {x = -15, y = -14}, 1},
    {"brown-asterisk-mini", {x = -16, y = -13}, 4},
    {"green-pita-mini", {x = -16, y = -13}, 1},
    {"green-hairy-grass", {x = -15, y = -13}, 2},
    {"green-asterisk-mini", {x = -15, y = -13}, 3},
    {"green-hairy-grass", {x = -14, y = -13}, 7},
    {"green-asterisk-mini", {x = -14, y = -13}, 2},
    {"green-bush-mini", {x = -9, y = -14}, 1},
    {"green-asterisk-mini", {x = -9, y = -13}, 1},
    {"green-bush-mini", {x = -8, y = -14}, 5},
    {"green-asterisk-mini", {x = -8, y = -13}, 1},
    {"red-croton", {x = -7, y = -13}, 2},
    {"brown-asterisk-mini", {x = -5, y = -14}, 2},
    {"brown-asterisk-mini", {x = -4, y = -13}, 2},
    {"brown-asterisk-mini", {x = -16, y = -12}, 1},
    {"brown-asterisk-mini", {x = -15, y = -12}, 1},
    {"brown-asterisk-mini", {x = -15, y = -11}, 1},
    {"green-asterisk-mini", {x = -14, y = -12}, 3},
    {"green-asterisk-mini", {x = -13, y = -12}, 3},
    {"brown-asterisk-mini", {x = -14, y = -11}, 2},
    {"green-hairy-grass", {x = -13, y = -11}, 1},
    {"green-asterisk-mini", {x = -13, y = -11}, 2},
    {"red-pita", {x = -13, y = -11}, 1},
    {"green-hairy-grass", {x = -12, y = -11}, 2},
    {"red-pita", {x = -12, y = -11}, 2},
    {"green-hairy-grass", {x = -8, y = -12}, 4},
    {"green-asterisk-mini", {x = -8, y = -12}, 2},
    {"green-asterisk-mini", {x = -7, y = -12}, 1},
    {"green-hairy-grass", {x = -8, y = -11}, 2},
    {"green-hairy-grass", {x = -7, y = -11}, 5},
    {"green-asterisk-mini", {x = -7, y = -11}, 4},
    {"green-croton", {x = -6, y = -12}, 5},
    {"red-croton", {x = -5, y = -11}, 2},
    {"brown-asterisk-mini", {x = -3, y = -12}, 1},
    {"green-pita", {x = -4, y = -11}, 1},
    {"red-asterisk", {x = 0, y = -11}, 1},
    {"green-pita", {x = -15, y = -10}, 3},
    {"brown-asterisk-mini", {x = -14, y = -10}, 4},
    {"brown-asterisk-mini", {x = -14, y = -9}, 1},
    {"green-croton", {x = -13, y = -9}, 1},
    {"green-hairy-grass", {x = -12, y = -10}, 3},
    {"green-asterisk-mini", {x = -12, y = -10}, 3},
    {"red-pita", {x = -12, y = -10}, 1},
    {"red-pita", {x = -11, y = -10}, 1},
    {"green-pita-mini", {x = -12, y = -9}, 2},
    {"green-hairy-grass", {x = -11, y = -9}, 1},
    {"green-asterisk-mini", {x = -11, y = -9}, 1},
    {"red-pita", {x = -11, y = -9}, 1},
    {"green-hairy-grass", {x = -10, y = -9}, 1},
    {"green-hairy-grass", {x = -7, y = -10}, 1},
    {"green-asterisk-mini", {x = -5, y = -10}, 3},
    {"red-croton", {x = -5, y = -10}, 1},
    {"green-pita-mini", {x = -5, y = -10}, 1},
    {"green-asterisk-mini", {x = -6, y = -9}, 2},
    {"green-croton", {x = -5, y = -9}, 1},
    {"green-asterisk-mini", {x = -4, y = -10}, 2},
    {"green-asterisk-mini", {x = -3, y = -10}, 1},
    {"green-pita-mini", {x = -4, y = -9}, 5},
    {"brown-asterisk-mini", {x = -3, y = -9}, 3},
    {"green-pita", {x = -3, y = -9}, 2},
    {"green-asterisk-mini", {x = -2, y = -10}, 1},
    {"green-asterisk-mini", {x = -1, y = -9}, 2},
    {"red-asterisk", {x = 0, y = -10}, 1},
    {"red-asterisk", {x = 1, y = -10}, 3},
    {"red-asterisk", {x = -15, y = -7}, 1},
    {"green-croton", {x = -14, y = -8}, 3},
    {"green-pita-mini", {x = -13, y = -8}, 2},
    {"brown-asterisk-mini", {x = -12, y = -8}, 3},
    {"green-pita-mini", {x = -12, y = -8}, 1},
    {"green-asterisk-mini", {x = -11, y = -8}, 4},
    {"red-pita", {x = -11, y = -8}, 2},
    {"red-croton", {x = -12, y = -7}, 2},
    {"brown-asterisk-mini", {x = -11, y = -7}, 1},
    {"green-asterisk-mini", {x = -11, y = -7}, 1},
    {"red-pita", {x = -11, y = -7}, 1},
    {"green-hairy-grass", {x = -10, y = -8}, 5},
    {"green-hairy-grass", {x = -10, y = -7}, 6},
    {"green-asterisk-mini", {x = -10, y = -7}, 1},
    {"green-hairy-grass", {x = -6, y = -8}, 5},
    {"green-asterisk-mini", {x = -6, y = -8}, 3},
    {"green-hairy-grass", {x = -6, y = -7}, 5},
    {"green-asterisk-mini", {x = -6, y = -7}, 1},
    {"green-asterisk-mini", {x = -4, y = -7}, 2},
    {"green-pita-mini", {x = -4, y = -7}, 6},
    {"green-asterisk-mini", {x = -3, y = -7}, 1},
    {"brown-asterisk-mini", {x = -2, y = -8}, 2},
    {"green-asterisk-mini", {x = -1, y = -8}, 1},
    {"brown-asterisk-mini", {x = -2, y = -7}, 1},
    {"green-asterisk-mini", {x = 0, y = -7}, 4},
    {"red-asterisk", {x = -13, y = -5}, 2},
    {"brown-asterisk-mini", {x = -11, y = -6}, 2},
    {"green-bush-mini", {x = -11, y = -6}, 2},
    {"brown-asterisk-mini", {x = -11, y = -5}, 1},
    {"green-hairy-grass", {x = -10, y = -6}, 4},
    {"green-asterisk-mini", {x = -10, y = -6}, 2},
    {"green-bush-mini", {x = -10, y = -6}, 1},
    {"green-hairy-grass", {x = -10, y = -5}, 5},
    {"green-asterisk-mini", {x = -10, y = -5}, 1},
    {"green-bush-mini", {x = -10, y = -5}, 2},
    {"green-asterisk-mini", {x = -5, y = -6}, 3},
    {"green-hairy-grass", {x = -5, y = -5}, 3},
    {"green-asterisk-mini", {x = -5, y = -5}, 4},
    {"green-asterisk-mini", {x = -2, y = -6}, 2},
    {"green-bush-mini", {x = -2, y = -6}, 1},
    {"brown-asterisk-mini", {x = -1, y = -6}, 2},
    {"green-bush-mini", {x = -2, y = -5}, 1},
    {"brown-asterisk-mini", {x = -1, y = -5}, 1},
    {"green-asterisk-mini", {x = -1, y = -5}, 2},
    {"red-asterisk", {x = 4, y = -6}, 1},
    {"red-asterisk", {x = 4, y = -5}, 2},
    {"red-pita", {x = 8, y = -6}, 1},
    {"red-asterisk", {x = -13, y = -4}, 3},
    {"brown-asterisk-mini", {x = -11, y = -4}, 2},
    {"green-pita", {x = -12, y = -3}, 1},
    {"green-pita-mini", {x = -12, y = -3}, 3},
    {"brown-asterisk-mini", {x = -11, y = -3}, 2},
    {"green-pita-mini", {x = -11, y = -3}, 1},
    {"green-hairy-grass", {x = -10, y = -4}, 2},
    {"green-asterisk-mini", {x = -10, y = -4}, 2},
    {"green-bush-mini", {x = -9, y = -4}, 3},
    {"green-hairy-grass", {x = -10, y = -3}, 7},
    {"brown-asterisk-mini", {x = -10, y = -3}, 1},
    {"red-croton", {x = -10, y = -3}, 1},
    {"green-asterisk-mini", {x = -9, y = -3}, 2},
    {"green-bush-mini", {x = -9, y = -3}, 2},
    {"green-hairy-grass", {x = -5, y = -4}, 3},
    {"green-asterisk-mini", {x = -3, y = -4}, 3},
    {"green-asterisk-mini", {x = -3, y = -3}, 2},
    {"green-pita-mini", {x = -3, y = -3}, 1},
    {"brown-asterisk-mini", {x = -1, y = -4}, 1},
    {"green-bush-mini", {x = -1, y = -4}, 1},
    {"brown-asterisk-mini", {x = 0, y = -4}, 1},
    {"green-bush-mini", {x = 0, y = -4}, 1},
    {"green-bush-mini", {x = 1, y = -3}, 1},
    {"green-pita", {x = -12, y = -2}, 3},
    {"green-pita-mini", {x = -11, y = -2}, 2},
    {"brown-asterisk-mini", {x = -10, y = -2}, 2},
    {"green-asterisk-mini", {x = -9, y = -2}, 2},
    {"brown-asterisk-mini", {x = -10, y = -1}, 2},
    {"green-asterisk-mini", {x = -9, y = -1}, 2},
    {"green-pita-mini", {x = -9, y = -1}, 3},
    {"green-bush-mini", {x = -8, y = -2}, 3},
    {"green-hairy-grass", {x = -8, y = -1}, 5},
    {"green-hairy-grass", {x = -4, y = -2}, 6},
    {"green-asterisk-mini", {x = -4, y = -2}, 1},
    {"green-pita-mini", {x = -4, y = -2}, 2},
    {"green-asterisk-mini", {x = -3, y = -2}, 1},
    {"green-pita-mini", {x = -3, y = -2}, 1},
    {"green-hairy-grass", {x = -4, y = -1}, 5},
    {"green-hairy-grass", {x = -3, y = -1}, 3},
    {"green-asterisk-mini", {x = -2, y = -2}, 1},
    {"green-croton", {x = -2, y = -2}, 2},
    {"green-asterisk-mini", {x = -2, y = -1}, 2},
    {"green-croton", {x = -1, y = -1}, 1},
    {"green-hairy-grass", {x = 0, y = -1}, 2},
    {"green-croton", {x = 0, y = -1}, 3},
    {"brown-asterisk-mini", {x = 2, y = -2}, 2},
    {"green-bush-mini", {x = 2, y = -2}, 1},
    {"brown-asterisk-mini", {x = 3, y = -2}, 2},
    {"green-bush-mini", {x = 3, y = -1}, 1},
    {"brown-asterisk-mini", {x = 4, y = -1}, 1},
    {"brown-asterisk-mini", {x = 5, y = -1}, 1},
    {"green-croton", {x = -10, y = 0}, 1},
    {"green-pita-mini", {x = -10, y = 0}, 4},
    {"green-pita-mini", {x = -9, y = 0}, 1},
    {"green-croton", {x = -10, y = 1}, 4},
    {"green-pita-mini", {x = -8, y = 0}, 2},
    {"green-hairy-grass", {x = -7, y = 0}, 4},
    {"green-pita-mini", {x = -7, y = 0}, 1},
    {"green-asterisk-mini", {x = -7, y = 1}, 3},
    {"green-hairy-grass", {x = -6, y = 1}, 1},
    {"green-asterisk-mini", {x = -6, y = 1}, 1},
    {"green-hairy-grass", {x = -3, y = 0}, 2},
    {"green-asterisk-mini", {x = -2, y = 0}, 1},
    {"green-asterisk-mini", {x = -1, y = 0}, 6},
    {"green-pita-mini", {x = -1, y = 0}, 4},
    {"green-hairy-grass", {x = -1, y = 1}, 4},
    {"green-hairy-grass", {x = 0, y = 0}, 4},
    {"green-croton", {x = 0, y = 0}, 1},
    {"green-hairy-grass", {x = 1, y = 0}, 2},
    {"green-croton", {x = 1, y = 0}, 2},
    {"green-croton", {x = 2, y = 0}, 1},
    {"green-pita-mini", {x = 2, y = 1}, 4},
    {"green-asterisk-mini", {x = 3, y = 1}, 2},
    {"green-pita-mini", {x = 3, y = 1}, 2},
    {"green-bush-mini", {x = 4, y = 0}, 1},
    {"green-asterisk-mini", {x = 4, y = 1}, 2},
    {"green-bush-mini", {x = 5, y = 1}, 2},
    {"brown-asterisk-mini", {x = 6, y = 0}, 2},
    {"brown-asterisk-mini", {x = 7, y = 0}, 1},
    {"brown-asterisk-mini", {x = 7, y = 1}, 3},
    {"red-pita", {x = -12, y = 3}, 1},
    {"green-croton", {x = -9, y = 2}, 1},
    {"green-pita-mini", {x = -9, y = 3}, 1},
    {"green-croton", {x = -8, y = 2}, 2},
    {"red-croton", {x = -7, y = 2}, 4},
    {"green-pita-mini", {x = -8, y = 3}, 1},
    {"green-croton", {x = -7, y = 3}, 1},
    {"green-hairy-grass", {x = -6, y = 2}, 4},
    {"green-asterisk-mini", {x = -6, y = 2}, 3},
    {"green-asterisk-mini", {x = -5, y = 2}, 1},
    {"green-croton", {x = -6, y = 3}, 1},
    {"green-asterisk-mini", {x = -5, y = 3}, 4},
    {"green-hairy-grass", {x = -1, y = 2}, 1},
    {"green-hairy-grass", {x = 0, y = 2}, 3},
    {"green-asterisk-mini", {x = 1, y = 2}, 1},
    {"green-hairy-grass", {x = 2, y = 2}, 3},
    {"green-asterisk-mini", {x = 2, y = 2}, 3},
    {"green-pita-mini", {x = 3, y = 2}, 2},
    {"green-hairy-grass", {x = 2, y = 3}, 4},
    {"green-hairy-grass", {x = 3, y = 3}, 7},
    {"green-asterisk-mini", {x = 3, y = 3}, 2},
    {"green-pita-mini", {x = 4, y = 2}, 4},
    {"green-asterisk-mini", {x = 4, y = 3}, 2},
    {"green-pita", {x = 6, y = 2}, 5},
    {"red-croton", {x = 6, y = 2}, 1},
    {"green-bush-mini", {x = 6, y = 2}, 2},
    {"brown-asterisk-mini", {x = 8, y = 2}, 3},
    {"brown-asterisk-mini", {x = 8, y = 3}, 2},
    {"brown-asterisk-mini", {x = 9, y = 3}, 2},
    {"red-asterisk", {x = 13, y = 3}, 1},
    {"green-pita-mini", {x = -8, y = 4}, 5},
    {"brown-asterisk-mini", {x = -7, y = 5}, 1},
    {"brown-asterisk-mini", {x = -6, y = 5}, 1},
    {"red-pita", {x = -6, y = 5}, 4},
    {"red-pita", {x = -5, y = 5}, 1},
    {"green-hairy-grass", {x = -4, y = 4}, 1},
    {"green-asterisk-mini", {x = -4, y = 4}, 4},
    {"green-hairy-grass", {x = -3, y = 4}, 5},
    {"green-pita-mini", {x = -4, y = 5}, 1},
    {"green-hairy-grass", {x = -3, y = 5}, 2},
    {"green-asterisk-mini", {x = -3, y = 5}, 1},
    {"green-pita-mini", {x = -3, y = 5}, 5},
    {"green-asterisk-mini", {x = -2, y = 5}, 1},
    {"green-hairy-grass", {x = 3, y = 4}, 2},
    {"green-hairy-grass", {x = 4, y = 4}, 3},
    {"green-hairy-grass", {x = 5, y = 4}, 5},
    {"green-asterisk-mini", {x = 5, y = 4}, 1},
    {"green-hairy-grass", {x = 5, y = 5}, 1},
    {"green-asterisk-mini", {x = 6, y = 4}, 2},
    {"green-hairy-grass", {x = 7, y = 4}, 3},
    {"green-asterisk-mini", {x = 7, y = 4}, 1},
    {"red-croton", {x = 7, y = 4}, 2},
    {"green-hairy-grass", {x = 6, y = 5}, 5},
    {"green-hairy-grass", {x = 7, y = 5}, 1},
    {"green-asterisk-mini", {x = 7, y = 5}, 1},
    {"green-hairy-grass", {x = 8, y = 4}, 1},
    {"brown-asterisk-mini", {x = 8, y = 4}, 3},
    {"brown-asterisk-mini", {x = 9, y = 4}, 3},
    {"green-hairy-grass", {x = 8, y = 5}, 2},
    {"green-asterisk-mini", {x = 8, y = 5}, 2},
    {"brown-asterisk-mini", {x = 9, y = 5}, 3},
    {"red-pita", {x = 10, y = 5}, 1},
    {"brown-asterisk-mini", {x = 11, y = 5}, 2},
    {"brown-asterisk-mini", {x = 12, y = 5}, 2},
    {"brown-asterisk-mini", {x = -5, y = 6}, 1},
    {"brown-asterisk-mini", {x = -4, y = 7}, 3},
    {"brown-asterisk-mini", {x = -3, y = 7}, 3},
    {"green-asterisk-mini", {x = -2, y = 6}, 1},
    {"green-croton", {x = -2, y = 6}, 1},
    {"green-hairy-grass", {x = -1, y = 6}, 1},
    {"green-asterisk-mini", {x = -1, y = 6}, 2},
    {"green-croton", {x = -1, y = 7}, 3},
    {"green-hairy-grass", {x = 0, y = 6}, 1},
    {"green-asterisk-mini", {x = 0, y = 6}, 1},
    {"green-hairy-grass", {x = 0, y = 7}, 4},
    {"green-asterisk-mini", {x = 0, y = 7}, 1},
    {"green-croton", {x = 0, y = 7}, 3},
    {"green-asterisk-mini", {x = 1, y = 7}, 1},
    {"green-hairy-grass", {x = 2, y = 7}, 4},
    {"green-hairy-grass", {x = 7, y = 6}, 4},
    {"green-hairy-grass", {x = 8, y = 6}, 2},
    {"brown-asterisk-mini", {x = 9, y = 6}, 3},
    {"green-hairy-grass", {x = 10, y = 6}, 6},
    {"brown-asterisk-mini", {x = 10, y = 6}, 1},
    {"green-hairy-grass", {x = 11, y = 6}, 2},
    {"green-pita-mini", {x = 10, y = 7}, 5},
    {"green-pita-mini", {x = 11, y = 7}, 1},
    {"brown-asterisk-mini", {x = 13, y = 6}, 1},
    {"green-croton", {x = 13, y = 6}, 5},
    {"brown-asterisk-mini", {x = 14, y = 6}, 2},
    {"green-asterisk-mini", {x = 14, y = 6}, 1},
    {"brown-asterisk-mini", {x = 15, y = 7}, 1},
    {"red-asterisk", {x = -6, y = 8}, 2},
    {"red-asterisk", {x = -5, y = 8}, 1},
    {"red-asterisk", {x = -5, y = 9}, 1},
    {"green-pita", {x = -3, y = 8}, 2},
    {"red-asterisk", {x = -4, y = 9}, 1},
    {"green-bush-mini", {x = -1, y = 8}, 1},
    {"red-croton", {x = 0, y = 8}, 1},
    {"green-bush-mini", {x = 0, y = 8}, 3},
    {"green-bush-mini", {x = 1, y = 8}, 2},
    {"green-asterisk-mini", {x = 2, y = 8}, 3},
    {"red-croton", {x = 2, y = 8}, 1},
    {"green-pita-mini", {x = 2, y = 8}, 1},
    {"green-bush-mini", {x = 2, y = 8}, 1},
    {"green-hairy-grass", {x = 3, y = 8}, 4},
    {"green-pita-mini", {x = 3, y = 8}, 1},
    {"green-asterisk-mini", {x = 3, y = 9}, 2},
    {"green-bush-mini", {x = 3, y = 9}, 2},
    {"green-hairy-grass", {x = 4, y = 9}, 1},
    {"green-asterisk-mini", {x = 4, y = 9}, 1},
    {"green-bush-mini", {x = 4, y = 9}, 2},
    {"green-asterisk-mini", {x = 5, y = 9}, 5},
    {"green-bush-mini", {x = 5, y = 9}, 1},
    {"green-hairy-grass", {x = 10, y = 8}, 5},
    {"green-asterisk-mini", {x = 13, y = 8}, 2},
    {"green-pita-mini", {x = 12, y = 9}, 2},
    {"green-hairy-grass", {x = 13, y = 9}, 6},
    {"green-asterisk-mini", {x = 13, y = 9}, 5},
    {"brown-asterisk-mini", {x = 1, y = 10}, 2},
    {"green-pita-mini", {x = 1, y = 10}, 1},
    {"brown-asterisk-mini", {x = 2, y = 10}, 1},
    {"green-pita-mini", {x = 2, y = 10}, 1},
    {"green-croton", {x = 3, y = 10}, 4},
    {"red-croton", {x = 3, y = 10}, 3},
    {"green-pita-mini", {x = 2, y = 11}, 2},
    {"brown-asterisk-mini", {x = 3, y = 11}, 2},
    {"green-pita-mini", {x = 3, y = 11}, 2},
    {"green-croton", {x = 4, y = 10}, 6},
    {"green-asterisk-mini", {x = 5, y = 10}, 1},
    {"brown-asterisk-mini", {x = 4, y = 11}, 2},
    {"brown-asterisk-mini", {x = 5, y = 11}, 1},
    {"green-hairy-grass", {x = 6, y = 10}, 4},
    {"green-asterisk-mini", {x = 6, y = 10}, 5},
    {"green-bush-mini", {x = 6, y = 10}, 2},
    {"green-hairy-grass", {x = 7, y = 10}, 3},
    {"green-asterisk-mini", {x = 7, y = 10}, 4},
    {"red-pita", {x = 7, y = 11}, 4},
    {"green-asterisk-mini", {x = 8, y = 11}, 1},
    {"green-hairy-grass", {x = 12, y = 10}, 2},
    {"green-hairy-grass", {x = 12, y = 11}, 1},
    {"red-asterisk", {x = 0, y = 12}, 3},
    {"red-asterisk", {x = 1, y = 12}, 2},
    {"green-pita-mini", {x = 1, y = 12}, 4},
    {"red-asterisk", {x = 1, y = 13}, 2},
    {"green-pita-mini", {x = 2, y = 12}, 1},
    {"red-asterisk", {x = 2, y = 13}, 1},
    {"green-pita", {x = 5, y = 12}, 1},
    {"brown-asterisk-mini", {x = 6, y = 12}, 1},
    {"brown-asterisk-mini", {x = 7, y = 12}, 3},
    {"green-hairy-grass", {x = 8, y = 12}, 3},
    {"green-asterisk-mini", {x = 9, y = 12}, 1},
    {"green-hairy-grass", {x = 10, y = 12}, 1},
    {"green-asterisk-mini", {x = 10, y = 12}, 3},
    {"green-asterisk-mini", {x = 11, y = 12}, 2},
    {"green-pita-mini", {x = 11, y = 12}, 5},
    {"green-hairy-grass", {x = 10, y = 13}, 5},
    {"green-hairy-grass", {x = 11, y = 13}, 1},
    {"green-hairy-grass", {x = 12, y = 12}, 4},
    {"green-hairy-grass", {x = 12, y = 13}, 7},
    {"green-hairy-grass", {x = 13, y = 13}, 7},
    {"green-hairy-grass", {x = 13, y = 14}, 5},
    {"green-hairy-grass", {x = 14, y = 14}, 1},
    {"brown-asterisk-mini", {x = 16, y = 7}, 3},
  },
}
