return
{
  entities =
  {
    {"dead-grey-trunk", {x = -10.04, y = -14.09}, {}},
    {"medium-scorchmark", {x = 4.51, y = -12.42}, {}},
    {"crash-site-chest-1", {x = 4.5, y = -12.5}, {items = {battery = {type = "random", min = 4, max = 28}, ["space-science-pack"] = {type = "random", min = 4, max = 28}}, }},
    {"tree-02-stump", {x = 8.48, y = -13.37}, {dir = "east", }},
    {"dry-tree", {x = -1.36, y = -7.65}, {}},
    {"tree-02-stump", {x = -10.39, y = -5.63}, {dir = "east", }},
    {"crash-site-spaceship-wreck-big-2", {x = -7.55, y = -6.26}, {items = {["flying-robot-frame"] = {type = "random", min = 0, max = 8}}, }},
    {"dry-tree", {x = -5.64, y = -7.17}, {}},
    {"crash-site-spaceship", {x = 4.66, y = -3.06}, {items = {["rocket-control-unit"] = {type = "random", min = 0, max = 4}}, }},
    {"small-scorchmark", {x = -8.93, y = -3.81}, {dir = "east", }},
    {"big-scorchmark", {x = -4.06, y = -0.72}, {dir = "east", }},
    {"sand-rock-big", {x = 12.73, y = -4.57}, {}},
    {"small-scorchmark", {x = -10.87, y = -0.98}, {dir = "east", }},
    {"tree-02-stump", {x = -12.94, y = -3.37}, {dir = "east", }},
    {"1x2-remnants", {x = -9.5, y = -4}, {dir = "east", }},
    {"crash-site-spaceship-wreck-small-6", {x = -14.2, y = -1.48}, {}},
    {"small-remnants", {x = -10.5, y = -1.5}, {dir = "east", }},
    {"medium-scorchmark", {x = -0.5, y = 2.31}, {dir = "east", }},
    {"crash-site-spaceship-wreck-small-4", {x = -10.85, y = 1.68}, {}},
    {"tree-02-stump", {x = -8.4, y = 1.77}, {dir = "east", }},
    {"sand-rock-big", {x = 7.45, y = 2.44}, {}},
    {"dry-tree", {x = 8.98, y = 2.44}, {}},
    {"tree-02-stump", {x = -12.21, y = 3.96}, {dir = "east", }},
    {"small-scorchmark", {x = -6.1, y = 5.2}, {dir = "east", }},
    {"medium-small-remnants", {x = -1, y = 2}, {}},
    {"crash-site-spaceship-wreck-medium-3", {x = 9.49, y = 4.23}, {items = {["plastic-bar"] = {type = "random", min = 4, max = 28}}, }},
    {"crash-site-spaceship-wreck-big-1", {x = -9, y = 4.37}, {items = {["steel-plate"] = {type = "random", min = 40, max = 90}}, }},
    {"small-remnants", {x = -6.5, y = 5.5}, {dir = "east", }},
    {"crash-site-spaceship-wreck-small-5", {x = -2.31, y = 5.9}, {}},
    {"medium-scorchmark", {x = -9.18, y = 11.26}, {}},
    {"dry-tree", {x = -2.76, y = 9.24}, {}},
    {"crash-site-spaceship-wreck-small-3", {x = -9.36, y = 11.42}, {}},
    {"dead-tree-desert", {x = 2.3, y = 13.02}, {}},
    {"dead-grey-trunk", {x = 12.35, y = 14.04}, {}},
    {"tree-02-stump", {x = -6.46, y = 14.41}, {dir = "east", }},
  },
  tiles =
  {
    {"nuclear-ground", {x = -15, y = -3}},
    {"nuclear-ground", {x = -15, y = -2}},
    {"nuclear-ground", {x = -15, y = -1}},
    {"nuclear-ground", {x = -14, y = -4}},
    {"nuclear-ground", {x = -14, y = -3}},
    {"nuclear-ground", {x = -14, y = -2}},
    {"nuclear-ground", {x = -14, y = -1}},
    {"nuclear-ground", {x = -14, y = 0}},
    {"nuclear-ground", {x = -14, y = 1}},
    {"nuclear-ground", {x = -13, y = -4}},
    {"nuclear-ground", {x = -13, y = -3}},
    {"nuclear-ground", {x = -13, y = -2}},
    {"nuclear-ground", {x = -13, y = -1}},
    {"nuclear-ground", {x = -13, y = 0}},
    {"nuclear-ground", {x = -13, y = 1}},
    {"nuclear-ground", {x = -13, y = 2}},
    {"nuclear-ground", {x = -12, y = -5}},
    {"nuclear-ground", {x = -12, y = -4}},
    {"nuclear-ground", {x = -12, y = -3}},
    {"nuclear-ground", {x = -12, y = -2}},
    {"nuclear-ground", {x = -12, y = -1}},
    {"nuclear-ground", {x = -12, y = 0}},
    {"nuclear-ground", {x = -12, y = 1}},
    {"nuclear-ground", {x = -12, y = 2}},
    {"nuclear-ground", {x = -11, y = -7}},
    {"nuclear-ground", {x = -11, y = -6}},
    {"nuclear-ground", {x = -11, y = -5}},
    {"nuclear-ground", {x = -11, y = -4}},
    {"nuclear-ground", {x = -11, y = -3}},
    {"nuclear-ground", {x = -11, y = -2}},
    {"nuclear-ground", {x = -11, y = -1}},
    {"nuclear-ground", {x = -11, y = 0}},
    {"nuclear-ground", {x = -11, y = 1}},
    {"nuclear-ground", {x = -11, y = 2}},
    {"nuclear-ground", {x = -11, y = 3}},
    {"nuclear-ground", {x = -10, y = -7}},
    {"nuclear-ground", {x = -10, y = -6}},
    {"nuclear-ground", {x = -10, y = -5}},
    {"nuclear-ground", {x = -10, y = -4}},
    {"nuclear-ground", {x = -10, y = -3}},
    {"nuclear-ground", {x = -10, y = -2}},
    {"nuclear-ground", {x = -10, y = -1}},
    {"nuclear-ground", {x = -10, y = 0}},
    {"nuclear-ground", {x = -10, y = 1}},
    {"nuclear-ground", {x = -10, y = 2}},
    {"nuclear-ground", {x = -10, y = 3}},
    {"nuclear-ground", {x = -10, y = 4}},
    {"nuclear-ground", {x = -9, y = -8}},
    {"nuclear-ground", {x = -9, y = -7}},
    {"nuclear-ground", {x = -9, y = -6}},
    {"nuclear-ground", {x = -9, y = -5}},
    {"nuclear-ground", {x = -9, y = -4}},
    {"nuclear-ground", {x = -9, y = -3}},
    {"nuclear-ground", {x = -9, y = -2}},
    {"nuclear-ground", {x = -9, y = -1}},
    {"nuclear-ground", {x = -9, y = 0}},
    {"nuclear-ground", {x = -9, y = 1}},
    {"nuclear-ground", {x = -9, y = 2}},
    {"nuclear-ground", {x = -9, y = 3}},
    {"nuclear-ground", {x = -9, y = 4}},
    {"nuclear-ground", {x = -8, y = -8}},
    {"nuclear-ground", {x = -8, y = -7}},
    {"nuclear-ground", {x = -8, y = -6}},
    {"nuclear-ground", {x = -8, y = -5}},
    {"nuclear-ground", {x = -8, y = -4}},
    {"nuclear-ground", {x = -8, y = -3}},
    {"nuclear-ground", {x = -8, y = -2}},
    {"nuclear-ground", {x = -8, y = -1}},
    {"nuclear-ground", {x = -8, y = 0}},
    {"nuclear-ground", {x = -8, y = 1}},
    {"nuclear-ground", {x = -8, y = 2}},
    {"nuclear-ground", {x = -8, y = 3}},
    {"nuclear-ground", {x = -8, y = 4}},
    {"nuclear-ground", {x = -7, y = -7}},
    {"nuclear-ground", {x = -7, y = -6}},
    {"nuclear-ground", {x = -7, y = -5}},
    {"nuclear-ground", {x = -7, y = -4}},
    {"nuclear-ground", {x = -7, y = -3}},
    {"nuclear-ground", {x = -7, y = -2}},
    {"nuclear-ground", {x = -7, y = -1}},
    {"nuclear-ground", {x = -7, y = 0}},
    {"nuclear-ground", {x = -7, y = 1}},
    {"nuclear-ground", {x = -7, y = 2}},
    {"nuclear-ground", {x = -7, y = 3}},
    {"nuclear-ground", {x = -7, y = 4}},
    {"nuclear-ground", {x = -6, y = -7}},
    {"nuclear-ground", {x = -6, y = -6}},
    {"nuclear-ground", {x = -6, y = -5}},
    {"nuclear-ground", {x = -6, y = -4}},
    {"nuclear-ground", {x = -6, y = -3}},
    {"nuclear-ground", {x = -6, y = -2}},
    {"nuclear-ground", {x = -6, y = -1}},
    {"nuclear-ground", {x = -6, y = 0}},
    {"nuclear-ground", {x = -6, y = 1}},
    {"nuclear-ground", {x = -6, y = 2}},
    {"nuclear-ground", {x = -6, y = 3}},
    {"nuclear-ground", {x = -6, y = 4}},
    {"nuclear-ground", {x = -6, y = 5}},
    {"nuclear-ground", {x = -5, y = -7}},
    {"nuclear-ground", {x = -5, y = -6}},
    {"nuclear-ground", {x = -5, y = -5}},
    {"nuclear-ground", {x = -5, y = -4}},
    {"nuclear-ground", {x = -5, y = -3}},
    {"nuclear-ground", {x = -5, y = -2}},
    {"nuclear-ground", {x = -5, y = -1}},
    {"nuclear-ground", {x = -5, y = 0}},
    {"nuclear-ground", {x = -5, y = 1}},
    {"nuclear-ground", {x = -5, y = 2}},
    {"nuclear-ground", {x = -5, y = 3}},
    {"nuclear-ground", {x = -5, y = 4}},
    {"nuclear-ground", {x = -5, y = 5}},
    {"nuclear-ground", {x = -5, y = 6}},
    {"nuclear-ground", {x = -4, y = -7}},
    {"nuclear-ground", {x = -4, y = -6}},
    {"nuclear-ground", {x = -4, y = -5}},
    {"nuclear-ground", {x = -4, y = -4}},
    {"nuclear-ground", {x = -4, y = -3}},
    {"nuclear-ground", {x = -4, y = -2}},
    {"nuclear-ground", {x = -4, y = -1}},
    {"nuclear-ground", {x = -4, y = 0}},
    {"nuclear-ground", {x = -4, y = 1}},
    {"nuclear-ground", {x = -4, y = 2}},
    {"nuclear-ground", {x = -4, y = 3}},
    {"nuclear-ground", {x = -4, y = 4}},
    {"nuclear-ground", {x = -4, y = 5}},
    {"nuclear-ground", {x = -4, y = 6}},
    {"nuclear-ground", {x = -3, y = -7}},
    {"nuclear-ground", {x = -3, y = -6}},
    {"nuclear-ground", {x = -3, y = -5}},
    {"nuclear-ground", {x = -3, y = -4}},
    {"nuclear-ground", {x = -3, y = -3}},
    {"nuclear-ground", {x = -3, y = -2}},
    {"nuclear-ground", {x = -3, y = -1}},
    {"nuclear-ground", {x = -3, y = 0}},
    {"nuclear-ground", {x = -3, y = 1}},
    {"nuclear-ground", {x = -3, y = 2}},
    {"nuclear-ground", {x = -3, y = 3}},
    {"nuclear-ground", {x = -3, y = 4}},
    {"nuclear-ground", {x = -3, y = 5}},
    {"nuclear-ground", {x = -3, y = 6}},
    {"nuclear-ground", {x = -2, y = -6}},
    {"nuclear-ground", {x = -2, y = -5}},
    {"nuclear-ground", {x = -2, y = -4}},
    {"nuclear-ground", {x = -2, y = -3}},
    {"nuclear-ground", {x = -2, y = -2}},
    {"nuclear-ground", {x = -2, y = -1}},
    {"nuclear-ground", {x = -2, y = 0}},
    {"nuclear-ground", {x = -2, y = 1}},
    {"nuclear-ground", {x = -2, y = 2}},
    {"nuclear-ground", {x = -2, y = 3}},
    {"nuclear-ground", {x = -2, y = 4}},
    {"nuclear-ground", {x = -2, y = 5}},
    {"nuclear-ground", {x = -2, y = 6}},
    {"nuclear-ground", {x = -1, y = -6}},
    {"nuclear-ground", {x = -1, y = -5}},
    {"nuclear-ground", {x = -1, y = -4}},
    {"nuclear-ground", {x = -1, y = -3}},
    {"nuclear-ground", {x = -1, y = -2}},
    {"nuclear-ground", {x = -1, y = -1}},
    {"nuclear-ground", {x = -1, y = 0}},
    {"nuclear-ground", {x = -1, y = 1}},
    {"nuclear-ground", {x = -1, y = 2}},
    {"nuclear-ground", {x = -1, y = 3}},
    {"nuclear-ground", {x = -1, y = 4}},
    {"nuclear-ground", {x = -1, y = 5}},
    {"nuclear-ground", {x = 0, y = -5}},
    {"nuclear-ground", {x = 0, y = -4}},
    {"nuclear-ground", {x = 0, y = -3}},
    {"nuclear-ground", {x = 0, y = -2}},
    {"nuclear-ground", {x = 0, y = -1}},
    {"nuclear-ground", {x = 0, y = 0}},
    {"nuclear-ground", {x = 0, y = 1}},
    {"nuclear-ground", {x = 0, y = 2}},
    {"nuclear-ground", {x = 0, y = 3}},
    {"nuclear-ground", {x = 0, y = 4}},
    {"nuclear-ground", {x = 1, y = -4}},
    {"nuclear-ground", {x = 1, y = -3}},
    {"nuclear-ground", {x = 1, y = -2}},
    {"nuclear-ground", {x = 1, y = -1}},
    {"nuclear-ground", {x = 1, y = 0}},
    {"nuclear-ground", {x = 1, y = 1}},
    {"nuclear-ground", {x = 1, y = 2}},
    {"nuclear-ground", {x = 1, y = 3}},
    {"nuclear-ground", {x = 1, y = 4}},
    {"nuclear-ground", {x = 2, y = -3}},
    {"nuclear-ground", {x = 2, y = -2}},
    {"nuclear-ground", {x = 2, y = -1}},
    {"nuclear-ground", {x = 2, y = 0}},
    {"nuclear-ground", {x = 2, y = 1}},
    {"nuclear-ground", {x = 2, y = 2}},
    {"nuclear-ground", {x = 2, y = 3}},
    {"nuclear-ground", {x = 3, y = -3}},
    {"nuclear-ground", {x = 3, y = -2}},
    {"nuclear-ground", {x = 3, y = -1}},
    {"nuclear-ground", {x = 3, y = 0}},
    {"nuclear-ground", {x = 3, y = 1}},
    {"nuclear-ground", {x = 3, y = 2}},
    {"nuclear-ground", {x = 3, y = 3}},
    {"nuclear-ground", {x = 4, y = -1}},
    {"nuclear-ground", {x = 4, y = 0}},
    {"nuclear-ground", {x = 4, y = 1}},
    {"nuclear-ground", {x = 4, y = 2}},
    {"nuclear-ground", {x = 4, y = 3}},
    {"nuclear-ground", {x = 5, y = 2}},
    {"nuclear-ground", {x = 5, y = 3}},
    {"nuclear-ground", {x = 6, y = 4}},
    {"nuclear-ground", {x = 6, y = 5}},
    {"nuclear-ground", {x = 7, y = 3}},
    {"nuclear-ground", {x = 7, y = 4}},
    {"nuclear-ground", {x = 7, y = 5}},
    {"nuclear-ground", {x = 8, y = 3}},
    {"nuclear-ground", {x = 8, y = 4}},
    {"nuclear-ground", {x = 8, y = 5}},
    {"nuclear-ground", {x = 9, y = 3}},
  }
}
