return
{
  entities =
  {
    {"dry-tree", {x = -3.01, y = -2.51}, {}},
    {"dry-hairy-tree", {x = -1.22, y = -2.98}, {}},
    {"dry-hairy-tree", {x = 3.35, y = -2.68}, {}},
    {"tree-06-brown", {x = -2.63, y = -0.2}, {}},
    {"dry-tree", {x = 3.71, y = -0.57}, {}},
    {"dry-tree", {x = -3.41, y = 3.3}, {}},
    {"dead-dry-hairy-tree", {x = 2.76, y = 2.88}, {}},
  },
  tiles =
  {
    {"nuclear-ground", {x = -4, y = -1}},
    {"nuclear-ground", {x = -4, y = 0}},
    {"nuclear-ground", {x = -4, y = 1}},
    {"nuclear-ground", {x = -4, y = 2}},
    {"nuclear-ground", {x = -3, y = -3}},
    {"nuclear-ground", {x = -3, y = -2}},
    {"nuclear-ground", {x = -3, y = -1}},
    {"nuclear-ground", {x = -3, y = 0}},
    {"water-green", {x = -3, y = 1}},
    {"nuclear-ground", {x = -3, y = 2}},
    {"nuclear-ground", {x = -3, y = 3}},
    {"nuclear-ground", {x = -2, y = -3}},
    {"nuclear-ground", {x = -2, y = -2}},
    {"nuclear-ground", {x = -2, y = -1}},
    {"water-green", {x = -2, y = 0}},
    {"water-green", {x = -2, y = 1}},
    {"water-green", {x = -2, y = 2}},
    {"nuclear-ground", {x = -2, y = 3}},
    {"nuclear-ground", {x = -1, y = -3}},
    {"nuclear-ground", {x = -1, y = -2}},
    {"water-green", {x = -1, y = -1}},
    {"water-green", {x = -1, y = 0}},
    {"water-green", {x = -1, y = 1}},
    {"water-green", {x = -1, y = 2}},
    {"nuclear-ground", {x = -1, y = 3}},
    {"nuclear-ground", {x = 0, y = -4}},
    {"nuclear-ground", {x = 0, y = -3}},
    {"water-green", {x = 0, y = -2}},
    {"water-green", {x = 0, y = -1}},
    {"water-green", {x = 0, y = 0}},
    {"water-green", {x = 0, y = 1}},
    {"water-green", {x = 0, y = 2}},
    {"nuclear-ground", {x = 0, y = 3}},
    {"nuclear-ground", {x = 1, y = -4}},
    {"nuclear-ground", {x = 1, y = -3}},
    {"water-green", {x = 1, y = -2}},
    {"water-green", {x = 1, y = -1}},
    {"water-green", {x = 1, y = 0}},
    {"water-green", {x = 1, y = 1}},
    {"water-green", {x = 1, y = 2}},
    {"nuclear-ground", {x = 1, y = 3}},
    {"nuclear-ground", {x = 2, y = -3}},
    {"water-green", {x = 2, y = -2}},
    {"water-green", {x = 2, y = -1}},
    {"water-green", {x = 2, y = 0}},
    {"water-green", {x = 2, y = 1}},
    {"nuclear-ground", {x = 2, y = 2}},
    {"nuclear-ground", {x = 2, y = 3}},
    {"nuclear-ground", {x = 3, y = -2}},
    {"nuclear-ground", {x = 3, y = -1}},
    {"nuclear-ground", {x = 3, y = 0}},
    {"nuclear-ground", {x = 3, y = 1}},
    {"nuclear-ground", {x = 3, y = 2}},
  }
}
