---------------------------------------------------------------------------------
data:extend({

	{
		type = "item",
		name = "alloy-mixer-4",
		icons = {
			{
				icon = "__reskins-angels__/graphics/icons/smelting/induction-furnace/induction-furnace-icon-base.png",
				icon_size = 64,
				icon_mipmaps = 4,
			},
			{
				icon = "__reskins-angels__/graphics/icons/smelting/induction-furnace/induction-furnace-icon-mask.png",
				icon_size = 64,
				icon_mipmaps = 4,
				tint = util.color("ccae29"),
			},
			{
				icon = "__reskins-angels__/graphics/icons/smelting/induction-furnace/induction-furnace-icon-highlights.png",
				icon_size = 64,
				icon_mipmaps = 4,
				blend_mode = "additive",
			},
			{
				icon = "__angelsextended-remelting-fixed__/graphics/icons/num_4.png",
				tint = { r = 0.8, g = 0.8, b = 0.8, a = 0.5 },
				scale = 0.32,
				shift = { -12, -12 },
			},
		},
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "aragas-molten-alloy-mixer",
		order = "d[alloy-mixer-4]",
		place_result = "alloy-mixer-4",
		stack_size = 10,
	},
	---------------------------------------------------------------------------------
	{
		type = "recipe",
		name = "alloy-mixer-4",
		energy_required = 5,
		enabled = false,
		ingredients = {
			{ type = "item", name = "alloy-mixer-3", amount = 1 },
			{ type = "item", name = "bob-titanium-plate", amount = 20 },
			{ type = "item", name = "processing-unit", amount = 5 },
			{ type = "item", name = "angels-reinforced-concrete-brick", amount = 25 },
			{ type = "item", name = "bob-titanium-gear-wheel", amount = 9 },
			{ type = "item", name = "bob-titanium-pipe", amount = 12 },
		},
		results = { { type = "item", name = "alloy-mixer-4", amount = 1 } },
	},
	---------------------------------------------------------------------------------
	{
		type = "assembling-machine",
		name = "alloy-mixer-4",
		icons = {
			{
				icon = "__reskins-angels__/graphics/icons/smelting/induction-furnace/induction-furnace-icon-base.png",
				icon_size = 64,
				icon_mipmaps = 4,
			},
			{
				icon = "__reskins-angels__/graphics/icons/smelting/induction-furnace/induction-furnace-icon-mask.png",
				icon_size = 64,
				icon_mipmaps = 4,
				tint = util.color("ccae29"),
			},
			{
				icon = "__reskins-angels__/graphics/icons/smelting/induction-furnace/induction-furnace-icon-highlights.png",
				icon_size = 64,
				icon_mipmaps = 4,
				blend_mode = "additive",
			},
			{
				icon = "__angelsextended-remelting-fixed__/graphics/icons/num_4.png",
				tint = { r = 0.8, g = 0.8, b = 0.8, a = 0.5 },
				scale = 0.32,
				shift = { -12, -12 },
			},
		},
		icon_size = 64,
		icon_mipmaps = 4,
		flags = { "placeable-neutral", "player-creation" },
		minable = { mining_time = 1, result = "alloy-mixer-4" },
		fast_replaceable_group = "alloy-mixer",
		max_health = 300,
		corpse = "big-remnants",
		dying_explosion = "medium-explosion",
		collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
		selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
		drawing_box = { { -2.5, -3.0 }, { 2.5, 2.5 } },
		module_specification = {
			module_slots = 2,
		},
		allowed_effects = { "consumption", "speed", "productivity", "pollution" },
		crafting_categories = { "molten-alloy-mixing" },
		crafting_speed = 3,
		energy_source = {
			type = "electric",
			usage_priority = "secondary-input",
			emissions = 0.03 / 3.5,
		},
		energy_usage = "250kW",
		ingredient_count = 8,
		graphics_set = table.deepcopy(data.raw["assembling-machine"]["angels-induction-furnace-4"].graphics_set),
		vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		working_sound = {
			sound = { filename = "__angelssmeltinggraphics__/sound/induction-furnace.ogg", volume = 0.45 },
			idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
			audible_distance_modifier = 0.5,
			apparent_volume = 2.5,
		},
		fluid_boxes = {
			{
				volume = 100,
				production_type = "input",
				pipe_covers = pipecoverspictures(),
				base_area = 10,
				base_level = -1,
				pipe_connections = { { flow_direction = "input", position = { 2, 3 } } },
			},
			{
				volume = 100,
				production_type = "input",
				pipe_covers = pipecoverspictures(),
				base_area = 10,
				base_level = -1,
				pipe_connections = { { flow_direction = "input", position = { 0, 3 } } },
			},
			{
				volume = 100,
				production_type = "input",
				pipe_covers = pipecoverspictures(),
				base_area = 10,
				base_level = -1,
				pipe_connections = { { flow_direction = "input", position = { -2, 3 } } },
			},
			{
				volume = 100,
				production_type = "output",
				pipe_covers = pipecoverspictures(),
				base_level = 1,
				pipe_connections = { { flow_direction = "output", position = { 0, -3 } } },
			},
		},
	},
})
